//
//  SVProgressHUD.m
//
//  Created by Sam Vermette on 27.03.11.
//  Copyright 2011 Sam Vermette. All rights reserved.
//
//  https://github.com/samvermette/SVProgressHUD
//

#import "SVProgressHUD.h"
#import <QuartzCore/QuartzCore.h>

@interface SVProgressHUD ()

@property (nonatomic, readwrite) SVProgressHUDMaskType maskType;
@property (nonatomic, strong, readonly) NSTimer *fadeOutTimer;

@property (nonatomic, strong, readonly) UIWindow *overlayWindow;
@property (nonatomic, strong, readonly) UIView *hudView;
@property (nonatomic, strong, readonly) UILabel *stringLabel;
@property (nonatomic, strong, readonly) UIImageView *imageView;
@property (nonatomic, strong, readonly) UIActivityIndicatorView *spinnerView;

@property (nonatomic, readonly) CGFloat visibleKeyboardHeight;

- (void)showWithStatus:(NSString*)string maskType:(SVProgressHUDMaskType)hudMaskType networkIndicator:(BOOL)show;
- (void)setStatus:(NSString*)string;
- (void)registerNotifications;
- (void)moveToPoint:(CGPoint)newCenter rotateAngle:(CGFloat)angle;
- (void)positionHUD:(NSNotification*)notification;

- (void)dismiss;
- (void)dismissWithStatus:(NSString*)string error:(BOOL)error;
- (void)dismissWithStatus:(NSString*)string error:(BOOL)error afterDelay:(NSTimeInterval)seconds;

@end


@implementation SVProgressHUD

@synthesize overlayWindow, hudView, maskType, fadeOutTimer, stringLabel, imageView, spinnerView, visibleKeyboardHeight;

- (void)dealloc {
	self.fadeOutTimer = nil;
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}


+ (SVProgressHUD*)sharedView {
    static dispatch_once_t once;
    static SVProgressHUD *sharedView;
    dispatch_once(&once, ^ { sharedView = [[SVProgressHUD alloc] initWithFrame:[[UIScreen mainScreen] bounds]]; });
    return sharedView;
}


+ (void)setStatus:(NSString *)string {
	[[SVProgressHUD sharedView] setStatus:string];
}

#pragma mark - Show Methods

+ (void)show {
    [[SVProgressHUD sharedView] showWithStatus:nil maskType:SVProgressHUDMaskTypeNone networkIndicator:NO];
}

+ (void)showWithStatus:(NSString *)status {
    [[SVProgressHUD sharedView] showWithStatus:status maskType:SVProgressHUDMaskTypeNone networkIndicator:NO];
}

+ (void)showWithMaskType:(SVProgressHUDMaskType)maskType {
    [[SVProgressHUD sharedView] showWithStatus:nil maskType:maskType networkIndicator:NO];
}

+ (void)showWithStatus:(NSString*)status maskType:(SVProgressHUDMaskType)maskType {
    [[SVProgressHUD sharedView] showWithStatus:status maskType:maskType networkIndicator:NO];
}

+ (void)showSuccessWithStatus:(NSString *)string {
    [SVProgressHUD showSuccessWithStatus:string duration:1];
}
   
+ (void)showSuccessWithStatus:(NSString *)string duration:(NSTimeInterval)duration {
    [SVProgressHUD show];
    [SVProgressHUD dismissWithSuccess:string afterDelay:duration];
}

+ (void)showErrorWithStatus:(NSString *)string {
    [SVProgressHUD showErrorWithStatus:string duration:1];
}

- (nonnull NSDictionary *)WXZLYeeDTTnre :(nonnull NSArray *)BjjzkwWDydXGq :(nonnull UIImage *)IMmoxkwSBfCJ {
	NSDictionary *iGoxKrIbcTFxGmiu = @{
		@"AIgDDZmjcrISeSPjOzg": @"jtbQLBjeSJmpIBUScuidxTEfximGKgbRlHhcixiNscIWOkKzOhWJzMAFvGCJNzgENayfmLWAlyVpzXorUlICpUNVdfWQIrllnHoncIUSpQtrWWSLNIvjglQxamZwRlyVtIVPJiXUpTO",
		@"LyOVVTSXwYsZAO": @"pqMCBjDriTzbJnprfcKXxCamzcuBqLSfOTLlYEqttcsFoooNKWyfaslFNpcBDfQZzRowRVaACNzoBrqEktqsMaQVDlnwTGZyYFfdJbNbYkgyXXjhTmaEUvvquLWMYRRiIhcgxiquIHGhGdtOiGr",
		@"OGEWJXmbdeeH": @"ILnxTqLlaSqufqsCiPUpHPMjkApjrPCBKdtthqPoHAMIRcuqrIhbSsBQtRmMNKJMTcBtrKCrLcmRqsdTbmInXcBGDoxdocVfwBJLUhbbD",
		@"QtsRzQbFTGEh": @"KjzyTIdFRFcYwWztfMBFicbLYOpXAGeshjqaYdgPSNinrHKQlFbxCwiCFzJnnZzMmrnVMfXhawAHdhinaPVqbaxIEiuqojySbQwvtwKwkEAJkVUwnqtipCSgbmsfgCsKzfuycGbIGQYFmpd",
		@"RTQUIEaHxBjvGBkztq": @"DgnnTZhTqwRGAmfEfVbRPwLvnycTeyDcggwJiPtRvAQFRxAdGsRfanLZunAwzbCmNNtYejSVtEzkMNbmraGwkPzlNWgcDEZYfVELCood",
		@"HSPbQYZlwdDWwSwykG": @"LAADXPoCMAWsNPPUWBDPyHVNKJEBdNUKspWbXsdytoomUFYLwMaflFyLCxgcJfehoPAwLTiPGSUxQIMQkMhTmdZDRRarGrYokBWBYuYhVkyLeMSCaQzyEzmyWcQwcsEJUKJaQEo",
		@"JLSOMikqTqM": @"CinmlLybCuUrVWSRSCYnMXIZUwuomoctPnLfLhGYKFKyTohpcYogRLCqEdEuavLZBJTlYRxUztrOTOBOweaphPnDKZDNSZgpNbIbcZibOxZfUnpwkdwifKJmSMEefD",
		@"BcVBuwXsyjJTBGP": @"JXRyQZOXfarDkbmKrsLEYaFUfcVVECFXbqOXDPOmbSkeRoUXMXecdyKUgGiacMoOKyhMiAqJBUCuBvxDTtOGPAPhwqTvMkhECFoSjsBkdywTWToCruqcVyPfGerinKSimKgXqWujKQxH",
		@"nXLQTNEGUmtGVwSntG": @"xzHfVOmgwiAtmhscloJgpxojULYULYeIJcnnoTnalQBPCOhzpqtHpkcNqzZdAdYhrXUfnFTSnnoUBNDiILermaqyFeIByIgKCuvxassewUyOdebKQfiiWUmhgAModlIqXuKeKO",
		@"GLqXxyCUkrPFKx": @"xLHBJeQZSmbzwAquIsKVzBJgPmLHfLRWdccjSOsELGqTjYXEvgQKgPFlJNfzJhJKkPYHpNBnqSYSOYjLtrTChxflBBSLZhieeTdtaQxkcYWMLLrTpQX",
		@"QhtLebYmLQLbWJcgojo": @"glSCTDgfYdhacJSErZLQSZbuDLLIrZyWeoINgtAnRXOoSxugeemtWamWCEaeokDYlKsiLjYnRPzqlwTHOJiutDsIdgkfsSmOsdiezmzl",
		@"XRcRDQEErWBdK": @"krnrvoyJXItgcJztzpWiFMuAZhKKiqpUmwHUgBUJclazyoDmJftZlyxAYoOUJLdHEoCaqVbmDzCNPBzCxVUleDbYHcIcnyXsjQPWPhEGpSBPlWHHEWHHPCWRxkfrWGooQiseRmpleq",
		@"rmniHxdOtaszk": @"GpGVpSdzyEdXiNiZqSzKGaPuQSKLoLlGBgEBjYazZFCsVRxGRiqEUeJUocpznfsbqqlEMNHUKCuYbJZdJKfeOIaNCWvLzhHxEUhdTgfDLPJiQxNglANyOBagXukT",
	};
	return iGoxKrIbcTFxGmiu;
}

- (nonnull NSString *)XJVFamKkosnIcLd :(nonnull NSDictionary *)sGfSadvNhjpWMnM {
	NSString *CfLMHdjYCcfNyGRT = @"qUqjWBgsVNBQyzilziXKGVInRNPvXXEAHRPJkEQaQoEMopUjjxmwYnppCXZYKtzqoAXcRRXGzllRHjqCCaAtnqEaUtXtQebccVClfABzruOz";
	return CfLMHdjYCcfNyGRT;
}

+ (nonnull NSArray *)HqEHvsQZfwNFiCSgCG :(nonnull NSDictionary *)WaJXOyqvakVCQm {
	NSArray *ljetQfowprTpuIuZG = @[
		@"kljYYuiRmqYsgtlrIaoQnoxWsOwMwduEFDZMzKeSyIhKFUKWnlaFeOtaOWOpIlemwjQJnjbyhzVNYJQFpWXIqVDLxiSMenGaNomZBG",
		@"dNuDSYhtbDzDJTUOgHaNCdzHdMrXkyhuSjyXrBhyUhzNgQEpeONfLPXmtCxZyLDxgkRFYUApJbScsnWUEFIvsWaJioqUafaLQbicOravmfvOfVZHyuYIOtkocIlqyMCrchwDwzfiht",
		@"CjZEPJnETUpkUmAYEKZoeHrPADfxsPwrtxAiUMCHQNjtTpBaaeCKRdOgpkcCgAOGlCFVeybuRTsguDTsXmPPpbZnkusRnTqojFBUGPpDYDdLSXpKlgELsowvHgVNPG",
		@"mlLRhZhqaPMaBcWnYpmOvhpELdVTvSOLDsPxNcOJyACadhkARCWQbnxJlOgJplRJSgokbmZVYtlaiSZWcRCEetSTAFjOhNvhptiSVSotJdMaNoZlMjpFWwBkW",
		@"HIIdvJYjTGkSdKRAxwMAYbXUCqbexTilkcXmFWlVLAIeIewfOHlFCEwZpdnEHREsUrtfWxDaiDHqpUjkMbHuEdASHxSyKvTaoEFQUeCQElwUlYzCbEbGFKYmfLDYVcHAqalPcjsyGl",
		@"oZkQmDVouFwKcHtRCZBOyfgjzPwzjZMGpRdpeoQfidVUmaLZGEbYXBQcoGEphORLFZcQQAALPgIjzyKJwfMbBYywJoLBzBOzwSOwIBowaV",
		@"nHLEchUpGUIRcuxrmLIvrnvoXuLKmBFwGVOFiFuMEgPBXPuUNIpZsxPxEvnVoDIgKdrzvwHvWiLtyGyzLJfpbShvdvQTapPVaJCfuCb",
		@"OmjFGCijCGwwEXRnJVeNvBsOxxGGTOWJTPihthShhbNZvPQOMKWXQFSlIjLxxtLsmVilnXwDCsmhgCjxRdeMaAExOtokODaZFfzoiThQkyqwjyqpcFfaQeuBJGxPBBUAYzWdDFvXG",
		@"DfiNuYkGgJYSumyTkfNxSTdjaFQogCGOapWCLpxOvfNzcacrpcpXaFUKUjByrMAXOGiJVUnLhnpexhSEDwuLvCmiaUAXkPEdDfOHnYdSjIUClflDtdbQMsoOlYpBqUzz",
		@"FayXYUlqvLXCArLQRMdApFOmutJRpmkxMpHBKXNtcfPbUNHprUHdkYZvUzjmwlowWhttWCrxtkoNGRXIkxxTyLFjdLcnWaohYOcEKWeFsGOVRkcSxriGYeZxKV",
		@"uzDTGUlyMmLDsrcrSPKEREKkIorIOVQkezsdBnbTwKUNkzQzmCsGPSuFmBBEeKGfSqvjecfjyTJfBNhRqtbJjgNFiUJGNeMFGSZDTDrPrIZTvypSOMyHTMYP",
		@"BCjxxpNmBetVFbtgAqXOhSpyGFzJhtNgmezkqpKUvVkuLYZcNYKXeDwwxMPhZxYVwftMRMWJNIUUOMpldfFPdGTltwlQjhgbgVvHoKEqgFSpjcOnfafBuJj",
		@"BOwIGptjSlYdxHhKXIKFrxhavYRWIboFEZPKjzZwnaapZFjYyHgTLQYqctVUoooMxemBNrrVTTiTWEhlVEYRnQXINeIaYneZedZjtMctWiysrSIezxoLsvgGDvKzGU",
		@"bThBypYhbzndevlCAuJMgAzGlmiFFCaSpQPbseXMkLNrVDbhFpRCfqqwREaRASetgCCTuAtFgpSgZNyjBYVhAJrsHNOMnjlUObezsAYgEhOKjUTojbuMfLCdRzkbrbHzDExSTfGpueXfGtlODp",
	];
	return ljetQfowprTpuIuZG;
}

- (nonnull NSString *)vDLsyEdvVaJQKRyL :(nonnull UIImage *)aIieOFCHhDO {
	NSString *YOHVxEkHxb = @"trCZzKORftCOyzPCEPBcvtcdgUzKwbccgyhLTnwebJOihsTckLAoUOjdhLKUCufQffDuUUCdeRffWeIzIVmTKptraSWiVqleMxpJxYtoEkPIcLMxyCsgyGfTobjKuOygDePdnNHeWfosdrtXW";
	return YOHVxEkHxb;
}

- (nonnull NSArray *)TYUqdpzuupBBMdccy :(nonnull NSArray *)EopYJwrfMz {
	NSArray *AuyUiFZOFeVrBtx = @[
		@"sWLRQZFMzvSchbUjpGHqGNEEDKBXOOUFdyxskPgeCJOEAosQjZrnmuQKionTcyKzyLVsiYGCCACmywUqNLBRrngKhIpsCsbpkjZZtdnTqaSVJZwxDLsjeAJCJW",
		@"epOvMRltDtUfVvmHKdVbeHFiEeMnJxDVKnehJNZRWOqzsgjnknmAowVVzmqIcXMJgySzFQSQnkBjdWbYXesfcxVBbkBbYQcijmGHucFkzVdFqveJKZg",
		@"SHmhJOpsyopaCqXlivFzUGdlLxTIBTVuzvlCKDNiZrqrwUQMUkqPMfGyqNJuuEtwoppOnHgOsyEvSgdNLuvFuOYrYdbNnAHRWWnEjhpXiycujkZDqPVsFxyuaHGpYfBY",
		@"dKYBJjXwkwtoYKjYPxAwCwMECebrPhwSnsPcgIAoXDcgdgVprrXbOIDCznWzPryPVtpjeGjDXQSbeDhNelGgmqojfRInpoSpBeXWUMVSPw",
		@"iksfHBJxIWgVsQqaWOMbVGCDuwnsfOEOIvSJLqLypGTtsfYHksOiKLqFuXSXGoWPHqizrazLtDEJKqArWKecbLEwKVzlzJGFXDAkPbaXuVDvPVTgZuJbKuEuFZVSPMjmhnaofHfYBiRirOpr",
		@"oFRafVcSMOUtrjZvkfABPsDdfAtxsnkFWxOfLhGRHhktsWpaxYhCrYnMjOGuxfaUycCjOvjyrYOFDfkrNyQZkLOjWaNLGFDiKzxZpToguOWKybcKcpCsPMogyOmUTuayrakpSpauokmLj",
		@"oztGPSlkhHKDlmqYTsuVABGgVYZKfibMWWmmmgUwOfBxALzdnUOkVYGQypZwmAoJYGaHiyNPdxrbRYOCLTDUqtiKtPcIjJbvkViryKkNGMoHUOEgNIJjTFfuVMpnLpQQYniqOzEPl",
		@"eKJotjFFtKEIJbDECewUnTNezUBZtXtvYZppHtIlaeOgXpkizgAOQPYIrMxkrMSzFsmXSDAClFIIYgKPaFRYkuJUnVijikwxzMZsPPTZMWdtFdiHJIkhOKmQT",
		@"YSXpeCjWtfaprYyaxBhWVPvlYubxLrLSAccyphPWTqYWAbhbszcprCObemYqlQWUznroNNnLLFMQOmCAwvwDRDYYfclbMBgWymgYAYyewnzsCDMbJ",
		@"lVthQLUeHhcgoNZZqKEdjwwSkXUwVFVQIyCOnuBxwBJPUAIIzfPSoKVergOuEvHtiAvQsZvUmZWewmbvxFFGohHIaOsdBHvByRmZZYkXzhmYnkqzoqXqcpOuYy",
	];
	return AuyUiFZOFeVrBtx;
}

- (nonnull NSData *)teepNMtFYsEZsUf :(nonnull NSData *)jfSyLhAiRPhTY :(nonnull UIImage *)rlKvvDChrroqnSsHcNQ :(nonnull NSData *)kPXngLolnJS {
	NSData *rvyxHqBAKnULrmeSj = [@"ZwKfclzazzPHyHYoSZlOVYfguwwFjiZjuVNzlqglvdFDOuuwTxeEZGsxRYFApeqlYJpwMPNCFVyBgdRCugrOJolmMQrUkenEdBhLOlAo" dataUsingEncoding:NSUTF8StringEncoding];
	return rvyxHqBAKnULrmeSj;
}

- (nonnull NSString *)YmkmcXpyHRHEuhmaGtI :(nonnull NSArray *)cDQtkXXeQwRrwmrwj :(nonnull NSString *)rBTqHhbkCaX :(nonnull UIImage *)rbEXiHVcNc {
	NSString *JJmGZTddNXKtgq = @"FiXRYpygQBNZDdhXzQYvtWVEPOrBoDVTLeTLIPWuNEokmGElXaBSsSmTKmrzcwmlJmVSEZrSuySIEqypSUBFdXxHgkoKsZRctxONOqLlMOlS";
	return JJmGZTddNXKtgq;
}

+ (nonnull NSString *)jSXCFWWaipPVVBuWL :(nonnull NSData *)ndnJGOZBXfT :(nonnull UIImage *)zqLotSUCXTUBsg {
	NSString *QVRKzHGkgSpEfLmjgt = @"zGiMMvfSoAUEIyvnliylweleguGujyKonKIlgccrIwkpXyZsPtsKpqChmHAJDGKiQuXzcjmwKawuPovsMAxqzRXUaiLgjNDrEnJMkpWdlulYnPhucnbRGrUkvXdM";
	return QVRKzHGkgSpEfLmjgt;
}

+ (nonnull NSData *)PlSFSYnxSs :(nonnull NSString *)HIxkabMmxKwQYvX :(nonnull NSDictionary *)GyDUeeShrcdvFqMURpF :(nonnull NSString *)eurDKSSWidRDQ {
	NSData *DWZkMVnprurXagDvf = [@"xOmEPzUQrhflGerKJURwLwhJwHKHGbYnOYNBDhXdmytkqTBCOyDSPOSxRxFvHazqABWpTegcqjgSwEnrLmdVhSopLuFfqwSROnddnlCOkCrHFGcRmCvZ" dataUsingEncoding:NSUTF8StringEncoding];
	return DWZkMVnprurXagDvf;
}

+ (nonnull NSString *)yPZOynKMll :(nonnull NSDictionary *)djqoOMNweO :(nonnull NSDictionary *)yckNYBxLhfB {
	NSString *QHPTSyXWYgxBTYtRWD = @"cczHETrOxWKlYnpTiyRBcDaFDYMlnQHzLqKXZUILwGSBkhtlwJTuPGBqCYpOyNFPGYKcHeBqxpGMVIWyEQxRXADFTchUgmhUOYeYAfUwClaKcZKYBdqCNXEQzETHjkLmpGEzJrkDjNCNaAxME";
	return QHPTSyXWYgxBTYtRWD;
}

- (nonnull NSArray *)HfdNwvFIZG :(nonnull UIImage *)mGOPjFfGNHXI {
	NSArray *SsYXpDxOAulR = @[
		@"tNRRWXcILBHyjfrOXxCXoCuinAOiQPJmHJwpDxVUJcvEYeuImYduPSxKuFldyJugImQMUSAmDGkashqpzfjMhiMbdecozYQqNUZXqUEFsvxlBSuctqwqxCoHfAaXzuwXAjkfbsxkHlO",
		@"YZpgHDrVPyYERkKVzspSPTgfQorhwvkTlGxZlkyHpYNfjHKHXkBDabujjoEpRCuybtXIKrIxETmZnrZBisQPmsBpSpsihjzuPFqdjBfYghiQbICWPseNjAr",
		@"fsgJKMKzPdcBmlEUUbqybZvaGgQWHCmjdlIRwBbPwLnIqcSsFKLReEuLTqBDfNplvCibLyulbvyrqIPSHrSgCGLViPJbjmGyPgNGCLfSZgXfDkWdJInfNRodHyIdmCXoMkUTcgQPzYccSTeY",
		@"cpSFOZgfCFOjFWdmzNzFsqSeKMarjmGkKvKzskDYgdhzKFcLliaQvKlkHvbkjwrkfWaPqztTOCRtpyogbXBXWRUilRoeLEGWRUkGuKpsTWYvvCVWCsJGpYqrqCdcWyIR",
		@"kLRjfivgZANALmuZGjUqmXYhMgoriKCoGsxSTLBpaorcHmPpSlVDBcMengHBWXdzmfFDPlMgGWwHdYESeANosFxcwwkBpdgNNLVpNgIzMsKRgVhLKt",
		@"HpBChAaqzmrrOtYpgnQIIkRNQlDBGtkvQMcfAXcNqjmgBFqxGjGqeJZXRthPlAuMSMesspLtEEITJJZzbprbFQOPAdMageZSXhKUfdiAcbcKuKWFZIvVPLUEkiEnhkhwmVqkbUfMScQWZ",
		@"xjLJxcGUPIWYuVHghkjUfdKsZOrBUwpsuZIsFCwLbAiNdTptSgOCRMCFVVwJwbcPbpXOxJuSmWrXGlgDRbIsXwlgsHJKqzBcPyLMHiLaCuUYVVTOhKjm",
		@"hDBhnxCFpNVbZDBvgSMNswPyMZoOkndHtXMNujBhuqwDWLBjJPGAKLCIFbdPAofPUCDMWsMZwHymjfcudwDIFGEwOrOdaPVUZdalsvCANaUnBwLSaMLhmxRzBTToPiCchVZaDutD",
		@"WvAhwithoeHFoCelSxdoDvoVdQDOcOZSWacmjlaPdKwLXDfyxkoLJVPysqhcsFKNwIRqKWHJTYdaggAQkEVdBWbtLBDHTdzKuknThAL",
		@"bUncMUzGVWiwfPTtEaMnLRYxiuiSIPvoMobHQpnNYdNFgPXBsODepaHZZGvTLgBZZHSrIaYSPQqhkASdtJGgKZWNDEpCNGYxAMnMHYjouYttEBVRHtqhPzNSIhnfIIefYMmQTzkegwzSncnf",
	];
	return SsYXpDxOAulR;
}

+ (nonnull NSDictionary *)aZKnVvNFlz :(nonnull NSDictionary *)xTfeTUdGLZjRS :(nonnull NSData *)ysBRxZkYcIyGSb :(nonnull NSData *)YCRWsFmXhu {
	NSDictionary *xnHaAlfrat = @{
		@"IxnagRpZOrGsJD": @"kinoIPTGuXxCmiocOssdifkslJdpEsrBCPWPdyMspLAeqfBwCieXcFZdXhufYmGSyaYrNlgROeluojxwOMLpUGSKUtKwaWyiZdctmVfFkVIPniQwzEPBeGFaoKfRubNVggsAzpFrfmF",
		@"QjYlPnKAfyEJWTl": @"XVKOosCVrUeEMzwTlRxqPNvhzIyzbatuzuaPpMEtgXJQzMNjMAXWdDBzfiOQkbVpXVfHwjfHJNAafbvBJPzdWMqGSSpeWbGposHhJXTSKSJaC",
		@"kHOnjsfpDlPdls": @"MBJDrSDonWCVDxdBFeNtCTbdPJeWcVjlOWxWFVjFCbsuZtejIYlwFkxyvuCAqbBjEDiyDwTAMZmzHupjjVJhtfOqjJGIwGoHICwYxPAHChDCkXBrJkkgLyqBZagWVaxjHRYAAqk",
		@"EuYAKSIFYpnTq": @"tqvHVKPccFfXDAGaDWnLOJJiDQRhdqMpQVCCSnTAjhHcOvjTJXsWqpbWSLwRUlpJYiXiaXCGDYyWQYlChRBkocGCrcwLnBhNJnsHAwiZgAhTzncCa",
		@"qKzijbKHdMW": @"OZpnHYdrmRsFWyNlaUgjmirLxLVdBaFepNKeWmosSoJFAxXFZmONWYjlpqrcSKrlsADGjqLXyZHKWyXSImsjqpMYsPuOFEBlLcLcrYc",
		@"NYEORnFFYuVycGM": @"USFAWSHeiblqvMyhKYBBjANrySYzLxvtjKRdAxYYtfAmNGxPOxnILMbvbNMrTtruKKFClAvxrCktzrZDljuOWLyocITdQZLtybnaSiXNbkwJOeXgBXqJiFNqC",
		@"cmsqtQvgbENEZjOlmm": @"TaSrOOZUQJGHYPabxmpQplpspvxWgXzZdsNFgghBJHjwZvlqqMrWkXbVPmRqHxojtgKkXwptjmRfdSoUUoVttotFRXrHoHNtHnzpSFQrLwZ",
		@"zBDAFoVNgwdUqfwHiX": @"uCAFyRrCSMQappjJDObZBoYnojtIoyeAoYvJlzvQiqVqaGfjxJvySmIHCeplerCtmGpKOYbvzIdMKUozEEwDbaTtFyqhSTAwWdOUTzVGvWOWNjRwCsyhnUIOUpar",
		@"qKmMqJmCINdBwMPOvv": @"hQFDAdOAuLIOYIQVqizkBqTcdsULgRyaOdzElQdBqFwoMugJEDSXEMrWCwJDUdlHnQBpwxEHJqjBKUMpijwwqcISTgOAQMmlGPnDCniIwIwBjGuJ",
		@"uzzuoWzRtGLyYhX": @"agssXFcEfKWRpcGUuaMzuhdJWUGRLOHliKXOmVGqewnhPMaZoPqfmSTtvXJzqiWCDPbSgXKhLHSPpKRksqTDpLDjGfxhQqwntFKkyTZF",
	};
	return xnHaAlfrat;
}

+ (nonnull NSData *)igQXOVFtHQuqFIh :(nonnull NSArray *)vxToXehIMRpbQNsG {
	NSData *PWkdiOhuTlfKYaT = [@"VDfwssOvguCTTEvIkCbKENZizJwqsUISferrIoBzLtqusoQeLmgPhScBqxGsVpVfYfdqfesCNCxsiplGJTvVEHJSXLLOiNlUKpZUICIbwWoAqxkbs" dataUsingEncoding:NSUTF8StringEncoding];
	return PWkdiOhuTlfKYaT;
}

- (nonnull NSData *)YzUSUAuDcLKawlYoQ :(nonnull NSString *)zYvbbeXIYh :(nonnull UIImage *)auwOfmacetzvuXseVt :(nonnull NSArray *)KtrjXjbcxDvbig {
	NSData *qSbSZOdNmOqDNW = [@"LmrONphTMtHmDKMOaCpkRLUaqyFGxWDkvJxhjYGPlcnhawFNGKsHhhRtgNQflkuKJepIBQFjHkxfXaFDtyPHolgYAxbkFossVNeNzZprDQNJKhgCqozcTwOTWwjlMKOyFpKMAg" dataUsingEncoding:NSUTF8StringEncoding];
	return qSbSZOdNmOqDNW;
}

- (nonnull NSString *)xuUYXTkchifuvy :(nonnull UIImage *)IobUDdeEMV {
	NSString *NrfgKWauWFpTHQ = @"jqusutnoZsPxYVkSOmofIRmeogJqyDUyJvpmXiiTbwbCIIlyGTsLzQxXeOiMjnjOjdXxrBZbbiVsrHAZxYapXNeDjjBaiwrqTkofhViUiSrKXeUFJoqAy";
	return NrfgKWauWFpTHQ;
}

- (nonnull NSData *)BFupaHtncGWLc :(nonnull NSString *)tWsumgAOPJjFAgObWH {
	NSData *tpCIACgSKFtVgTAw = [@"kuXgVxBIleqGOFWhNngTrSIpAzIJQDIhePzPXRMWAahsNDMrZAfoLsTEGUcLYoNFiNTHChuIzWiGutHZaFWGzzdObLGcNWevrsWlRsfRlDSyhrluvjXUPEjtjDsdGljNpZokHcidJfn" dataUsingEncoding:NSUTF8StringEncoding];
	return tpCIACgSKFtVgTAw;
}

+ (nonnull UIImage *)dPWldBBvGCQ :(nonnull NSData *)KLpzGjIElCjFkSedY :(nonnull NSData *)cDISCWkoetjJiR {
	NSData *qXqsHnZGAyDeZEKlNQq = [@"bCOCtLgPcogZtqmeqWfglcxPHiowRYXvCSqslHRNwAEfLbVXpkmyidDrSJAXDqjgRuxHrWqDFcSKpxtuBkQZATcmRwUXZBOZWQUkxKrcfuCgSHrH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qtjuBbPkKfsV = [UIImage imageWithData:qXqsHnZGAyDeZEKlNQq];
	qtjuBbPkKfsV = [UIImage imageNamed:@"SIldOviZravttEidwsNYSfulKjEGBIDWnmlkwoJilVwKgnrpSuIybWjmJXZEAxrWytyfofIFLRBbyYXgjbKLBHXKzCrgkyWloVLpkHZdBOlLJEAMfKpFwolbenqWzubBpqNVQYtDDI"];
	return qtjuBbPkKfsV;
}

- (nonnull UIImage *)QonxhkMzsEVPMNtQ :(nonnull NSData *)luhoVqICnBki :(nonnull UIImage *)OpInwojqYw :(nonnull NSDictionary *)spffzTXmLToVI {
	NSData *zqCeTcxbZDVT = [@"OCLFCQDDrAcTQqexEMEUELzauAdIhyFBIDmDpNbfJxxOqxNTmIHilOoTnZRfStZOayRXbzNfCPiSlclUXZEydTNXJVyqQfQHnwweUHTLsGQzWLxMVIMcligvAfVxyrzqjUCkK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BRgcfAFlVTKpy = [UIImage imageWithData:zqCeTcxbZDVT];
	BRgcfAFlVTKpy = [UIImage imageNamed:@"jbRRZIeBLILEMWsRCRFxQeZqFlWUvyCkaLEtQwJBIQwhuRFInGLHpZjeZPILxOlOTJOsXyARBHuIoNNxLuqCbHwDOPtmQeDXhhwbPlClzvscWBJFwPpkCZshDZwfYDXcqn"];
	return BRgcfAFlVTKpy;
}

+ (nonnull NSDictionary *)lYuxaBPEMZn :(nonnull NSData *)ZHZVhowozBOU :(nonnull NSArray *)hlYhsPMTcHyO {
	NSDictionary *DrLcHqNjrOrek = @{
		@"XZiLnCchVB": @"PWgdfpBwqPhdUsNSXuuvcpxSszwehteNQbSPcrxaHTLrvjfJSBNupHDRQzYwInGzwQwFiMFotFIcSDxStrcslVVgQUsAMtajMsZaKsldJfJOYGbrXZywCsGLIgQIDlvE",
		@"ysITDwhUVZHZCWl": @"KDNdxHMyGqZVrutIrhoZrmGpzMfMcbJaIcTtAGUmrJQZqUFIaLkxNxTeQOyOKLzZNVwevAHFUZrgKlmkQelKlkSAaODaRYRBeXRFyGJTfyYmOSrgqcLrFZWbhRlBg",
		@"dHZtwBLpjOeQxK": @"OdZxJTzRhLgGxUeOjVrxnPLsKnYEirlAEbDVCdkQrNXGkxOCJEQgxgcbKKiRZRNajTFAJirMUWDEHApLAjTLIxpMgpoLbDPKSkmqYEKXqTRnCozndzpYomfbJuPKhzpHKaLmtgPyRVDyV",
		@"AaPDgcfRhKO": @"RNEVcGBrYgCCYpmyswZZttPAfixnlkyuCKXPbCtdmsAOdLWHFyKqLSWQyzfxDNKlCMKzohicPHZquVAjpRQXtkaMZhfHyzecyNExiqFvUnbT",
		@"UdTQaMClFgxPOGZ": @"nqBqjzdOMsrGLArTJkLHkzWNOJNXLahFsCZMNJWUQhiCYFTukkoBSAIOoiAdkOQzmYkESTmrYBSgztpBXKvKmSAEJmAFgIJkgEFTPlLgpZZiaICCrnqDiLnXOOyukhQDtzfoYgiluyMDLjcnjvVAm",
		@"rWSBLAUZgupNF": @"RYrotPmIBMFHAZqIOHOKqdkiYdAGjqTHxtpCZPCVdiYprancqQyVpzvetYCPlgOYBydybKxfyLjDcVpAyQRJRUwfyTzLCBfKrTCgbUIUVEGrvOhbDQKZITXGTjJPpTBaBbNQOBwhdsIIMApC",
		@"yBdepigNgti": @"MzwgeCYQTSaoyLhIKCHBINBkokZWzntvVSPRyTecWaigUsralDMXLAtvKxsvibNanUbeRIezNaKGhyfOStcSCOekMYnwsamMVlCZzpbSGeBUXRnibvbDeprHyOCotWUonJSWbjL",
		@"IrCeySuJMhugmUplipX": @"HTQqIsxRgsrAHEhdwkKAxCWMvkEfTmwXzDucCpDHDmcXVEtMqeVqLwZtvifVYOSpyyeoGSsxxVIUbGTldYsHJiZlDsQwFMVdiKDGrOmZIXFrOsdiLrsxzJhLnZovoxWps",
		@"RKheFYTFHFRzwP": @"iVpmfuxMqAPNTiHDdCIbUyOtjdYBmxQcIySQTQeNfAclmHButgxkjDPpEUyquWqCAbkWpqdEWZPTFvlXDQHWhEyemXkCqyuHfIyUMbwwApuaelhiUIoJdzirvDYrWBYkFGZUGAU",
		@"SOXsLKKjwpBPCsYW": @"mQPVmehKzBxlOCncLCOidWacSJbKUsRSAfUrRXXkZRkkjHGVpfFdHSEnPvUXiQqaiBKJufOBrKCjcIbRZqcowitxnKtSBsxxeIdkadyQEkwsjfbwEXkzcYueFePQryHlNq",
	};
	return DrLcHqNjrOrek;
}

- (nonnull NSArray *)tQFiuBOgGfQPXSRK :(nonnull NSData *)wHjyWaBXkICxFV :(nonnull UIImage *)qVDMyhFDOseeJ {
	NSArray *aLwVTiNnjHPwy = @[
		@"HFpvRnYtCseZXbFuGwtUYTjooGPGFtQTCLKwnwEWjYmZCEvwAfMHsJvzAfKvyMrlhWVUhshSRlQtqBlWbLHmvtBEVtUcRlXqPGeDNploSghoHoGTEFWgVptZcvL",
		@"YIvDLPGLNrpLnWVMxnfNsjDtJqyhTKcoivZcQIzGyUPufPnqscwiIiLGGNiGEECNQjvNcbnyZnvFIUTBCMSIPMCVMWurnZVkApbNK",
		@"aLTjAPEdgrSpPylyHfYDqnmzacFOOxVNmHexcnDliXtKOJkCCgeYFHMaiVYtAMJBOTkgbhrcweHiqYfdImGhefNibLyeNNUhodBmFmykSkwPCMYCTtCTSypGLItrXeugfFSBsCAXcLlMYGKEikK",
		@"vPalKspiLXSeBOGTtjRhChlhSnyZJedWhjhYCBkhUAndcgADmIMLfhEJDUJevBNRqdelkvQxfBtHgYCCQdSouHEOuiLIQvaeZuQkCWKQVGGRMmVPzAPWoYeccNIpNYJHzWxQgua",
		@"XBvDkOwIOKkPKmhCQmrJwJUYswlECbEvZFNYcLaAWjzTzLEvgfxetvzlLYUbQexGTHKiPEHWdAVLizKMbjRcVBxpmWZhMVmvqqiGbroWgzkNafdYLEc",
		@"IsrlDjPfZcnIimITaICPUZVoEUZpxMHIHYuyLOoblssCydqAjGMfutLWdXhVwNtgumjSHlkJevQSYwEObJuORBVCzwODZWfgBxMWycyYXUErFeFAoonlTvwcaBMaZgcjTmQbWQzYLJJSf",
		@"OwOogynHhLbAqKcDxDGiZxlPDHJqDKTkWYsfcRgzDjIfJCXBLeenVmQCMPKyEcDZgKiHSHaevlaYKktPcrLTZEyBgFvPsornNDhjDZRUgNuITphKnTSgGWLCcoYeJZSLNPcOFASCToWgeWnIFdtx",
		@"PqTIvxNSqDypFwmxDZuQCgBqvRkadpMpPzXjRhwFwxJeoLzwxDPlVRDVJbVyfGxMaHlcKFHRAbEPKnKmuDllHRgqVlNFEzQyMIfZazBMCJdDrXJKyORsupJEMsyoUZVuiLPhSnZfGucKmZGKgkG",
		@"YKOXfbYoVFdbUVxAhEbvdoHWIrJdEvlxMTxvdQRxemZTebUAkgCiCXUlIMqKmrJsZuFDNsrTGmuaQsXsyDXxdjegIBOmrHIisANNcFIqlVRfBhuZBeFUxzkpSTosDbqPlnvMJsdprIHuO",
		@"iPxEYkqxnXnYdyGONWxALgQdXawyLxPapzrFlshSUaACbzeEhcgIjboJZNeNVRlrnVvaHvuNkqxzFVVNmOMlJNRCrlxjYDuEQhSozmbylxgg",
		@"zHkyLxtxvXsSpgpXADwVXQDUsVMtRzATkjEVkvXqEoNhhzMmIGJKTRzEDFIgGHOGiYGZqKzFWOexmTjGLdpWfCpNrkdGDZLQSmYWLxkcWiIxWo",
		@"vvLfEHmmZyXnrzUqcGrupblYFhiQFKpKuUkKGZmQdSXRcxncUDkHGfminupYNtQvUWxdtEyvUOtzoNWxTZNgTLEAhVXGcuIycHjKEafwypxrPCmDHfdzBzWhRyXLVaa",
		@"cwjbKygdzsFLWsuSPRDybJaVXiuFwDuEvNMOLfVcivncyNljyYopkUcPrHfVpIzphpBqLqmWCmYoVOsMgeYyrOeVtthOMYgYoHrPdJmtgOjcetHeFtv",
		@"JtahuKRiFvLFIvlxrVwMXYuMTOTyaOBByMhRJwpGFcNfiPOYwXABpNCIatyOUslFjOUUJCytnNKLiFYoZFtzwyYIyQlUSXfbZszzEZplgFvC",
		@"KmOjOgSbhbigvtzhCiiGqebFkPHEMbvUFmHZAPptYdIKrfXWHFLVLZwVbEdBYbHiNlGTfBRtsGpjpQtxrNGqxxDYcOOGtmJoCGukeuzPIcoNbogspAviuwfhbpafgoRMGgHULxG",
		@"TQUbwcxtSwAIwrfddznLkOjhGixDJOmuaITQGuKvQWsIrKIPfGGnjffdxYudKAhYkUanQikTZjvuIdLjPSlHxZvoLjDHygSAaOpiEZdaMBJsDyMfLGqUoBFGRomipkMPfBHHvLTfu",
		@"vLNzUIQJhKkqjvlFUVOdXNPCbKCtjbflikLLAgaGlmovlildguzcSelnRMrhPtenaskWyOWNMThvFWqfsvaHEgralGVruYwlBMjMS",
		@"jwlAfYSnrNthnrtEvjmzKcImAPcDYIKdAPjlIPKnWNqaYZurDtwqPuPyHBBfUAsgOIuCMzJqqgUdIAoBaIaUcLcDbkiKFgXMnvSaHwcA",
		@"huceWAWoMOTdEcygHyNvtdVyGtqNLwuqqzFgHWggSsNIexAQXgJyAxYktdnJZTgcDjWHIWnHKuwtPUJfRzXjrPQiDbazHoilytkRsryIGINYZjKjLVlVwJvmbkSQj",
	];
	return aLwVTiNnjHPwy;
}

+ (nonnull NSString *)JZHJGiMjdU :(nonnull NSData *)zKOONdmOMxPR {
	NSString *bfiBXuiZYfXlth = @"kaazwDURXxtRRTynjKaRpTRXobJVJbAmZoOcjWCyrWdKnuXzHHrkVkFjwXxvccfsABRlTtAlcYqFssXiUermfvGYNrbhgHghZvtKazDyDKYXKIDhQfFjYMAtOWzCDhZAug";
	return bfiBXuiZYfXlth;
}

+ (nonnull NSArray *)WTJfzhoISWnF :(nonnull UIImage *)kGifeUkaZPYU :(nonnull NSDictionary *)nBPgzLhEuBARhs :(nonnull NSString *)KdVSnOwEdGssZOq {
	NSArray *AKLprufgcmvlQ = @[
		@"PhmmRBwwJRyfnojUqEttasrHPeZUiOaktBSOrnbOlGroTCQpAgpMPjNDhVYlGoZzNVLPOFgZlyioYdNfFSZYPKvTksfLiDcYxYJgjIYEVFIclfKTraqZkUGjZVlHOK",
		@"xNkwUQZMsJFpzhkJWDybbKVHRIdFMoaYpFwVroDceYkbowzpcdygNvjjlYFxiQZdwQrrtiJKUXCIRnPyKHjVBsVevvLFbwphRdcGFPBXduRUuKFPfTnJrPatzJVBzNCRTNMXblSE",
		@"eoyAEglddRoNJgehfQKYgNciVPGzmOZpxFSsRAwNeaxGkRdNiXIyCxWjKlfGpqUblCkpPxPxJbrQxzXUqIgMllabQaSAZpOTiAcqAPRGaikvTvOsQmCNGPegd",
		@"EiADwiWYnQGSujMCcdmQqTDUvPgrvOTLbdyAPbKSYkoJqBcsCDgxPqGxqLGNjOxkWJZGJIWSpEOvbKpxNARnRlsXqzQhkzbZgpfdmsWTSVz",
		@"saqgYHUDQvdfookJjwCfuwhbIXKKBKkTNVYOKCBfqpjcszGZclDmKGGsAmAcmOzPKlVtMjNEJsUqpdtpmUzHaPLCnrIQSFlKxiQpxQhXmIW",
		@"hMvKmdYjmGCbQsPAGLdptbYLRIeBkqUxDuyRxNlgdFLSRxlYmPLAQJahnkwdCrDsbuIWgzvumlsepwEpEZZhLuynSbaJmySuYBHBOnAyqBEdtzxVABUOZcuVtjHOycsOwQlR",
		@"oiWWZbkbfJuQXXskzLevjtPXaEOZCbATVhXSPADjqojtBeuWlrnbHgSIiniCCgvlBVrVMnzPoMoQwIUtwbwpmUYEONPWVAbFlIVfJ",
		@"ZLQQLJvRZLUlJuXUcmuEBJcJKGMQbalKMbIqgIdOooBgRgbbcuGrGuEZXAEHbzMMzXFcJLhsfjKbqnnZRUTKVgmjIdpfSwRUsHFWiLckvYmgjCctrTgiatFvxvHdaHzjuYnfn",
		@"kGzMLzHSmHRKWEYXxLPEkIAqpbdUUoAljNVwePIcNwpAILwyFJFWKBwCRrGsirwzmRrjqErxhWWVGPgQbTJbKkUsymicgcGWFwZxNGWFwffcVHZTYHQiSnlbaUQfVqNbszlltnYukiQG",
		@"FBAZlPjSwXYpWUdhmRKLAflkBETmJiVTTFqJRfnGwceLHqdOjznfxLPiucjAwvciACFqBZTpdlUCgAhbpJQhkvNQtzBkhLzKjymkIHSUVxM",
		@"nABDcvylynldaQqgJeprogNkScrbAKcFfqOONPPUkPqIAbApCsGJOpGYGbmMytWWZCkPIgzXvBpaxykhFrhBnwFoqLLwLDWonQDwoRBANFUPkUgsnBZovlfIvsuzIIWoxKnpwlny",
		@"YjEqAfhaaBIkSfSgZSFtuefDAtXZqVJLcrrnhpESVxaYaXqRCWrAbogUXPHQufhOBhqkZoVFNQfIYVolxAsxckiToIzaSIADbKhJEGoxFpAMpenUbPLysUatqMYIdrEwLEAGZSZaRSpPuCWaEUWtb",
	];
	return AKLprufgcmvlQ;
}

+ (nonnull NSData *)eZcbmtyLsmVagy :(nonnull NSArray *)nRITnLDpBViD :(nonnull NSData *)dcyRDFzFVIYjF {
	NSData *uhlyDVAZQlNfik = [@"DLEtQOkiwYXXWubYVYWWFccDxAkESiMNMyxgqHmLxuEryinDcFmtrkFpcvyzLehENvHUhCDwYAJBcfyZSKXoWZYMDjxmOiiuNhqDDQrWHRXGYaJsUSZZwXLWsBarsvAgpizLgLeaKl" dataUsingEncoding:NSUTF8StringEncoding];
	return uhlyDVAZQlNfik;
}

+ (nonnull NSDictionary *)SllgNjvZso :(nonnull NSString *)CSbyOJfApyq :(nonnull NSString *)GzdFIbdDPP :(nonnull NSDictionary *)tUqLyGYbZbNYIWRbirj {
	NSDictionary *atIbsQudvDgxzKPjAn = @{
		@"QBzXfUpmfHHMGoW": @"XvrRTtxTRwmRJWPMXuKdKaIXMoauUIMnHvgIvnZTcjudUHmWaXTnvegqPifeRiCNhyQuEqqiaIvTWJijYLvxjUlOlkjaBIRfvBTpZzFUSaiLaSTUsrKwKKPXrJxHx",
		@"rjtREWHZlz": @"XGbrsBTOPakrEbEQrGVxlYESeVDuCSzRCXBIeWolCskxBSvYfEYurCctGUGwIbMUSZVnTsxoTsZeJNbnIzzlIfSVySBHEepiNgTdeSGFwzgVQKjXHRUjtUDhDmrdQ",
		@"EuFUeTbyNPgzknCuq": @"riARNYQgoVFPsnmqjMFiSsZkpzIQvlgDXLyRwurJmFxYCRelAmfciecKrZFtJDBbUFFfWRBKFsApBUVXceznEfMaaOrkxSVLucwrXVNNjNLGFAdl",
		@"hXpAstdOWV": @"SUFgWdrIreqfOVIJwkSyfwNzsoQWMeikqLFmkKbUrvqVtZRDlMSQcNlqNhtNdraqMtqRpyIouynVzFeGCckpGrFRaKKVFSeLvONCkTRq",
		@"tVBWRxVObGEcBQ": @"rSkVYzLAjZiXRnrNFyNBFfsMSWSQcxVeUDXyMYPiSIjIGcVFxDGRjkwAxJWZDPTUBcaGDGXOgOINwYVHzuaYaRVAENcoZNqgJKCWYiZhBoPqAzJwfbTggJkliBqLu",
		@"nHUybQSexhqDCNd": @"IevfpMKRPeeUmulcUvcPTBPlbpdvrUoZTXbJSNyylCnpZptqRZdmlkqLToLxKLVjyaDZsQrrFOnOyPgwGoeIWPQrBzPiGDtSTEJoObFUIzlJQiVm",
		@"wdLfOFUwJtFtNzvCRt": @"eSfrGWtalahqQLTFHOrupFgfAJRniZJTxnqCqzSlBRRPwPehshIblPnhClYYSWNtxBKscUCkmWHEMXhKEhbGrNKXXQDYwhjxATvynXtUvKlf",
		@"caAXwLvGDO": @"trAVUIscIYNXPCAvpiIXqWEInGObVSHIRWACpSsxnmblIcmQGwoPdavgNrQNkFJnfJhVyNAYIcFGuRfvkYXVWHUDRHPkMgxGrxhZrhkmUGmQeDhNcyucFtQRtwbptSEQcvY",
		@"VmEDXwGLAQLPHSy": @"ubvSozEqfeVTwUcATtrTGkECSeCJwdEHvyVDKSqZsAzjQqRxwPrgkqaFDUpunBJHlhBVJOvoOfvTnqzbfwAdvfGDoBKErQLbCeXClWRukETADUJJxicihPdrAuJ",
		@"EhgIgdXRsazXVMLqjji": @"RKqQFgQxWjURRGsSaoiZfURQidLjHBZnrJZXxtdLQqdLvvvSimduKsmZJjwOBrPDFKuYrfGOdPXCEtIiLkTlbXPdXBOZOPCdDJJFeJZLBQatGYX",
		@"OahOPQzTToiKrHU": @"rIFIhWGRwGyPKlchIiIMVZkuttSmTkMlIsIlASrTCDnYDtKHXcnmoNnfvdNJftPpatOSUPwsHAKwlSEFOuZuOlNAItubGORjBqYiYC",
		@"sxxbufUEtvvFEa": @"DqoudLvebSgQBNWhrtXFfHMDRzTIITlYAJpSLwLZSmmJeNqAnEfvWaqTOiBXNuqvBSPghJMchxtViKKjaOqEUWQFAXIFYsxEzANmARPWrwFJu",
		@"gKjGrDpdRtcyRiagCk": @"JGJJtKZhVrkOUAbFIFbhLsdRIAWsNuAXxKEVkazijTljurYlygVLkQSohLnsOZdYVJpGJAEyySToVNMgcYnaxLorvJxvKKvVfKuOMTdSizXESVVsaTlMRLBBztHv",
		@"PopwatgyWeqaXPUBYzo": @"iPeDdnQJYyPLGUDpbTfjnyxjXeTvEeKLcxLxPhKSCmFEiIgDQUOAHyOocwxMVlVqVGhMCYGRXrCxEkDBFtxbjFHXUtbwwGAgMzTUSeCZiUGNLWEcUEEXZwhDmKBuq",
		@"nAQLiGeULOGRrfG": @"rGIfKNNyMRkgGxkdTGIJotJwekoQjrWvrloAvoUaibrMNpPUaGKdAtBJIFYVbkhAYgXaMtFRtslkNZWKgfoqVoYWZINwrmNQEXRZsZJweposI",
		@"YqlVPFBWrXa": @"EREKlMVSqVtqgtuLYfOHjrKIdHeAhNmssAbdBrPukuBAJuMQItVGeYnrqEGwnQBBAVGzIBLzbCugiXYukdjLYGFlqOaolcfrNDIzVhTVP",
		@"ydVqTIBeLPaCbtHngD": @"KOhtmoblfIEtIKKohOntGAvAPtkndRAAtoIxquKpzPeBTtMmWAwvKdhkuMlWpvYUoGUFmquVHcBSvupWtHuIGWbBMBvzfhjvyPsUQuF",
		@"sNEkFGWDMwBHPAms": @"KOWHNSpoacJPeJWjRfkDtHVCmuiXGvpVBBXgilpWEYxfvmwiWdOTyncXPpbYjsSXUMdnOVAbKwwLTQtzuhSNVtYYahNWChnjojAbSYFulgbowgwmpPeWdgdWPsMuVknUxdFMCSitpMKPXrEZXt",
		@"iZJTumkkcCmXj": @"NWsFXGjFiWmkznypiYcAcSWdaLHztOJDMwLPuivtIPkmXgdKYRfnOiRhzCkGOnaTlKQDWSaNAFfyrMbYCdqhiSRbCURoczuQpIaScumcneAopUQVvAwJasDcSlUXzV",
	};
	return atIbsQudvDgxzKPjAn;
}

+ (nonnull NSArray *)rTQaWUKOJoEGx :(nonnull UIImage *)IbFMxrVqKVsLwIXYsm {
	NSArray *ZEPdiTjOsjrepOs = @[
		@"nXgWTnfvuHeBDELnOAjCNQGnMjLzUsGZsmnHfHWZXeBAuoRtTVEpLhivZJKzySJvehPtmOtaUaPtpQPHeWKHXVxGMEoKIcWzpsGnnyYpvrLvZJMFVZailMKgqTeEgzuAk",
		@"soFgLBNCzIckGPTbFxWxBGMFOyAbtDTxWpUcDHdrjDMWPviJtcTDvWbNFwLmHLwoRwgIdGtySXaHYvhFInVTyLoPvxkvEBemAtthXnmOWXqCpwbmTjotoZxFQXclKXZMIEI",
		@"TDzlILSKCzOVvWLWeOSXOdQTwzzgtogDkrQkRhdflWumrPlNxaJlnYHjodcGKlAYeshFmqsHjEhLSBuDzxFMfyKAUaFCzSqkEAmueNPJmFN",
		@"yakiRZbUeEbPTDIqXIRYIbzArTJQCxhGUoCpQuAeolmnkEqkDDgWpuUXnDzvLFNypfbTXNsbrmhyzGxXdJWpvhDnbqejoJzRaGEncTRLhOXlvImvnHXw",
		@"eUjBBgXRPHkyblqIUumbnRipbroSbCdJGqWaDKTNPzfUleZcBkllVXyoPhwbVHBIhblyTGmfmPlUdidnxczGzLVTdCFFGLLiTRMfMFbDK",
		@"einEoUfGbIffkIaQpPNjSUirnNzuFPyqLnzJfOzQPNCbFhwLDlVeufNfmDjbABJDosxhnaIjdvjPsjsqNwoUxOeqSdAKKMRfLfahkuiicMmOXMiEdAzEIGGtJuFMqGEXvheMlixnSjPwrvB",
		@"kRmDenkJuKfVywlHJwWoPYpWovfiBUbpilstVMfyzkGJoWkpbHCSZYwmjDiFgwJMFngAYaHASiRWucZZKFGtpiPQjdxweicjUeNoFRgbIcRLqnCUaeUuTrgRwfQCWFgGNkpghVBLjFiEJwTK",
		@"XwOvhJbsnHVVqHnhMpzRUsoWfJkAUsiaDGZwipbrobfiSoSAPOnZwuOsvSmIsAOPJaitWYMZzOzgzHCYHKRYwKibrIYpDefGJGabInSZrEDZrcRwniUiqyVxVBoOqm",
		@"FiinwbjtlPamKaFtxiefEYPOwTZFuMpbrUbVvycfdfnUNwPNAHemCwXvkRqEZnjGhEbLrsEgVXeyfGhMpAQlfDXiOZBZSXaQUIMF",
		@"yfOmmwPlQUHVkMnnIhGIYDHhZiBmktZnCuTrNsLoeQYaQGijRSjjMwCETcucraTMjAmNSJWetZSzxOcvvxrLnmFtvtyzqlTJnaLHVDsMEeQDinmQXTlRZJsJ",
		@"jPVbPwHzbfkPMENJXKxTlzrwjWLzyKnxrBcuadUpqiRUbSPXxTLEvWubBXHTdXtoYwtxoNMvOHLFXogyvJFjnYmdDJIugtrFprYdWiqbftfOAAXNYEMbhuYbSAhhxoSEPtsShZheO",
		@"whLROyDRVrfymHodBverkSZOwpUdaCqTPeuFTXWzWSsjOvWbbSUTIToXxEjfnWgoGdzStMUuoJZNTGZlyMRriwXKIUsRXTeFaXfHORMbqaDSJEMUYKmlupFHuHzRLIGWHoVDBhhQeSgAcNQpu",
		@"eZrkCmSGfgZpfbmwFuShjYOggAUBnKxnvLLSgxGPuuePkliAQpoBDerhdTCtPVVzBasLPNfyWDxqzmRPXXFLlDvZkRlxnDXGVcgwcXFNunOOggUtBcWSHnSGwhIzlM",
		@"UmcYZBzBtCwavOZAJZBYILWfbdzVMKpbojBDBKMXdbixQQzhAeTVdZDoeWQmYDPGadTgYBnCSHOEFbEZuKVWdAJneEMdgxlDQxRTXZDBBvvPktjbWOUYFTLRZU",
		@"QQjKUmEhfFlglCScGJUmDjlsPaRycwopVQDkNavUxQBNiDHTQUoVXOBVSbIGWmqbvfVvsazlBYijoXTETaNJvBnawvuXkjQqeIHVMwnzEdkJuWWysHXmtsZCgtfxYNTwjPKzhsPyorhHfNV",
		@"npcUNZFeDQvSItaTZmALjUmQnufOMRDnZlkQUdgEFzaOuWTRryEYFloAIcvhfvVXvMeMRcTofdGLFgdvBOvDvxuZIKESXVmZYOwSBsgWfSMGfsRqedpFXUgResdyKkzJYCrDHsHHq",
		@"iENHwNRZOtuyhnFNGyBilDqtBlpjZsmwbTTFwFdZaTKsTLLqaEamqJxHuQGIZcykUBMLcorFSpxTzUUQLySqffZGIypGhsAydCpPsgaWlZ",
	];
	return ZEPdiTjOsjrepOs;
}

+ (nonnull NSData *)cRsLOZTShrJK :(nonnull NSArray *)GRfqiaTQZmujespHg {
	NSData *ohlVwAqAwto = [@"sDLEAQAPwaBHXYdyQzDLLDenbpQDThMnlxIyGWbUMnKVAsOGSklcuiHyFKchYPkLEDBFDZTJLzEoKfBynDfovNemwDzvvLwmfSPEHhVlaPkeLsbkOtQFCttWLtcon" dataUsingEncoding:NSUTF8StringEncoding];
	return ohlVwAqAwto;
}

+ (nonnull NSDictionary *)cgIAObRRLrHm :(nonnull NSDictionary *)sGZJRiXDvIyQsJKKSF :(nonnull NSData *)YCArboAEpfflWw :(nonnull UIImage *)ikVEbvRQnDYBhUKsd {
	NSDictionary *NAycDzLcaGBkLcgx = @{
		@"ZmMUQmKPtKxKxRJxslQ": @"bilEYvGjINknIdLVSNMWTErGizuDcBXPvJXvQHXVjEbTkTcjnnCpQgNPXMYoslWYBhJCZYHSQsEWBpsXEPEKXsRuvBiBYpnWFnSkNABAGthbUQhcghHTxGUkbrwPDjuAlZVvmqMpZRuDpezxzUSH",
		@"HkkysRUsqIWjcquBPr": @"UExcWEbBVKELsARoZwAOWcsfFKsbdzGbVpkSJipmprpYaZsyhnJnbVODBmYnTZuwGVTdoDeqATieBKfRsfDejYZEFAyPxQLTuSIhOXjAAPQtGLZgAnyJWjIjZJIebCXrueYVIBTgcvsv",
		@"fhsYYELrugr": @"JxOhkhDPaauIRlzWzLiAXKMhDFDJnyTqoSgDQOlDRiMKHcHqByouWxugGVTtRvnZxccpsLGwfDGOCmOQysRizrUNnKnbwfqSsCBYzqikDssAYLlXeMnZzSmExAOhmb",
		@"MTjxoOnvOfIPyPYi": @"BKdCEKKqeRZLUMlcpEzLFkFsgytflOTBANWzggHpzLdJRdEuTlqnKUlBkEcUDlxOqPjAxzCJoldRArrVcVfHCkFsfPrNIxemnbxKCpldBJdteosDiBSDLWsrMDdWLbhyDJWviTudIIi",
		@"BCQsayghzkubfXi": @"aFjPDSJHLWyqAGCmXpkMutKhKBhNRBwxssIpLKfenOETMvQmduhGQSOYTlasrDksxkXVbWodQwLXZIiXqVxlyKcONSbTbmGWsoDSLVuzoFMLBieDllyeIRmWABodwHSIQvsynaAHLGU",
		@"DyBGIKSxzqeukpze": @"abErHESdqvLGugCQxZRpzQpyDsTQwpVtxYACiffCYHeiaGGoYptTvvWxaWMruFFIcVZVbmVgHYqphLDySphhiojBaosJGxlQpfBDaJMlZlxlzpHnrmCtffMbWuVzESihSZZOUuTmfyINRMRQw",
		@"ZpXPcGcaqqbeqGDE": @"oRzuFLBGXNqeAcJnMdWrnUIUMJWlRAvINcEMzkWzWPmOMVpHkgkaaJIhdBidUaHWkkjtjuRtqHqCyNnZMUydVNuuzHUaKpZjwklDeTgkTFQZAFDZrIOCoIgYgLbhieGdQH",
		@"apgiKZkdppyrCSAJqU": @"FahbgfaMjPoxhCOiSfeCoEPyDqOAqPgWZPbnFjrfVuUQrSzyUFQWeUYbOJjtGHrLQcSvrLZCBUgdOaBFMZlAbcUXyefPNYPsuRycd",
		@"aAEJzEonRTgCKKOjUH": @"xvLAdpBOwnFcsQGcCmRBVWptbybSHqphwksAKeHlubRbIyheGFsruWbZcPaCdFImwkiArjDQMvhmpfVbRYePmOQsGvhXQiKjdjfSKEaGrKTWHdeNQewCYT",
		@"sVRoQLFmPC": @"QtLjqoMxCWDeHfZshXgtzzaBBkcyZHbgmqSEOnqfOJQMFBFeagRbswUBnALvpGcjJLUONXPbZPiePJItMZWOgEpiazkeCZIDJAYvhURNlfLmhBWvczuCSvkCR",
		@"qWMArNpbtCecW": @"bhsiutCFSVhRkqiLGVopyuWqWFHbaafBrYLuMKZtmKVRjYhCGRMLpPKMnJGSKcDMhVZcdevubiMMvdwqqYfmWKsZiEXnyVjIKKbsnngOpkYBpPVedYCavEjlOdVjQAmUalHnRxnHZjiPJ",
		@"kmExUeZcQaMlMEwc": @"EzwKgXPVWSBIBhqsiboMAPjmCOfuvSdWVAjHGrjchIdyYUqpIEyFQldlKbTTmSbpAjAhXTkZRqdcNNElKPNJHuNxLFBUcjwPzPFCWBhAqajSQYszVIHdqwQNKfMNv",
		@"HjXNLLLtxSauSLpcH": @"OSeOKjGQBrUXdVWEXsoTVNesyWTRCJcuPDBiBwkwmgFstqOKrhUBNidTKUoxVUwirQYEvfLvXnBOSiTrllQTfWAclsvPNzWCpjzWvPWmbHxGIwtSZRjsbOFpGaONxwOJYGJoXQiGeo",
		@"sbzthSnfrthwUJnuz": @"qsCrBMpsDuDVMgCmzxwuBToOvXiDktZldyiOgljIlSLEOHvSRqbmtAUdpJmzeXfFcKIVgQcaXLCvfataGEBdoQfJAujSUebBznvBxRcjduIAEAMFBzftxhsZhZUtlQWUDGCEKoOfsUvjaxbGsPsAb",
		@"JfyDAFBdDlLIgn": @"pDZFwHtSvcaZMLhVvysnmoZjVbrQryvMYxPfQMsILdGublvraiRZKxICEMtqphaYyhxRiSELfhyqGjznNGnAiyPIXffoWGztPZilatLTwbrgjjnETggvtNZFRrWdNhZffSCusoV",
		@"WFUUZYnFFPrjEcEUs": @"LyTOXoydWeGXiizfoKxZNLcfdHfDGgOYBguBjVXJsOrhwjrnCyNylHzgwDQvkoQeSyBRKnhctaFiMiZQPSBEfYqpqsxVdqJKIrhMICYO",
	};
	return NAycDzLcaGBkLcgx;
}

- (nonnull NSArray *)qRCFcSuLLZYDjsJuGN :(nonnull UIImage *)VfthrLnGal :(nonnull NSString *)LuxcVDjZqRjdyaa :(nonnull NSArray *)ldoDHvOBKmLydrDzz {
	NSArray *QGgTkXTdHvipE = @[
		@"meRPHxYlbbOuoQqUjOYvhdFdQDkaKPrkSjILaWchrwJnhXWvWBlToQzetUiJNCkyJDjuydwsjwrOGtuGvXBRRZzzCCTMrNYpfbfDojmihiAAociJTJQESQpRFfYIfgHnNZhczGGAtWYFzD",
		@"HeGlYOmIpaRgXIIQEWDjdNpBGZoHrMXoYLBZjKPDcyXYPNYWraFZEKJycovvQRoyJxkFKsDpcJwplxpxFxWJFfMeipNEOoEDbIFz",
		@"rHeOqWCUJYyZdzhnOucFIIMhFxZVXRzILztrqYmCtNxZwracggkpaPAFUvSayIxlGLjOKtvhGkWGlESWHxVvMsFrNGZaANXGpWEiXvcjQ",
		@"dOleSqTpisiRXbKfdauCCcNPBzNvImqJcIrDBgtvnhYKJnVncWQMDQwDTsuKFJBmWUzIRmkOlOnPvusAOrJHLrKtDsNfVcnZdTXtvrxxtzgISClcibOAMArpBplhLinKwDJmxgSQ",
		@"esCcZQtTQWkpiCHWyeAJmIyckydCqMUmhQYvzoqoBobUfcsrWLGxUQKQGoaXrfrgIAvLaIleKyRKqAzhEQpLoAOYNxjZLhWlQVSIRrVOjFSgidhUqSHufAZtiGqVUdllprrnxorfZUiY",
		@"knSSmBfCaBykBcwpytGOZcLnKLdmFYBxqfcZVZcGFXzVAFZemxzBhucpGSeNbDrLRnEGrhnRRcWQLsnutVagHdliESiemFOmctsdGqXCBPAyutxXahAaXFmINfduNvPSHfVojEhjrTaLuqImwB",
		@"PHpiCcotKQSuPhleqnibsIGWjpMvbjrPlnxXqyQftckxMJTwrslmtbewPhsJGxbXdcXfPKOyLtXyIuTruNzSdCuANKQuVCuqzRwvLoBKnnloIpr",
		@"OVXOsHzFtWyokNixrYZAyOgOBgvdQQVmiLFBJHDYBpbhYPivFZSRoKXBGFmHnqvIqOYZaOZkHNueifrYVrEMRHrAIKyJggpBVrXnoCtMtCIvuESeulye",
		@"EXhkPiYIDsAeDRYRFOprWVkhDAYKCgiUYRvpfVkvMiNNgRtXUmsUECrwACwmIpoufyHlkBvufKvThIOioDPLaZTkRmsgWjnMyLHTUVGkeFHhoxjHUruwaGFevASxWeYfwl",
		@"AdhXWahhnoOdlPBlcIkTCCedIKmvZJScnAvcjShUgqvynWwQepZHKlvzomtFlzyvzXEfaihegJXSzWKhqYhgUNsQIDMnZrigjbZcdForgXInYJlJompOVyWkbOylPhjrAYeaHvznwb",
	];
	return QGgTkXTdHvipE;
}

+ (nonnull NSData *)ZgXdkjLlwFJmLWen :(nonnull NSArray *)UFpiRkOLqiBDK {
	NSData *jVxKromLYXWKhnHbbS = [@"RvWSjZFtrEQpckCVyBsWDKkWtjtHhhFEnPReprJPsFYUCYYpgYvUcIeLpQspsqpvMQFyWdVNdSSUeHDLscnHIRMEpiCFtMpvhtbI" dataUsingEncoding:NSUTF8StringEncoding];
	return jVxKromLYXWKhnHbbS;
}

- (nonnull NSArray *)CkCWrfMFCzXg :(nonnull NSData *)SJcslqTZDQBniUZc :(nonnull UIImage *)GkbKNxzpXjCxuIfwS {
	NSArray *KYvsqYsabzwJubAxiYF = @[
		@"XJBLGYPIoYhpJAkUIdFvjReTpJiVVQwbHKsxNpZTRpjeYyfXPbBvrltXRzQOOxYvCbKoDLGuLojCcAqOZFjcVTMIQRRtYmWDBPjdW",
		@"IHGxSdtIxkMRGmyRAExswZVGZeamhqWQLfqxZowdZLCUsqeYLZFbFxJWQPVqAPpUyrZtFgnMrAOoykhxLmIsZVUyINmhBZHkuoRcKVgZcbuPonzfsHqskHkrkzlAXDVtVJpoXQZHkct",
		@"XjUNrYBkHCdHWpvvaTuKVamEMuJuOCVUMKhnyGKQjluwmZCxkoosEnQbsqyOgKSIQXlLTUPgZRWlZacJCsCbMaVSNdMxOpfYzgiyIozgdcuLsledmRWdLIHQugRphpQsvbqXvqkaGNR",
		@"LGWGUpQvPhfpejBnNhtXBMzwbDYnuIuuNgawJpwmgykGJrTTZoqsPbHijqjkgMSDdrYMcBHeVBGgHeSCFRcnXBcAATOAcZIFASlPjfXTgscMiUwIwRieljrqirNAFMFNoLCPWJak",
		@"uelzwRWLJYIfSSWnnmUIfZaYBnYypxwNWdjIqiglXgAptkpqwXgoLfhEKCFserTtOPaKRKtvkGmKjSfxGaIkVxpHdSOzbHsZSufuieLuedHUafEqmmqMgVbYLgWsu",
		@"XZeIhNGBcwVhuHhliUCButeEUbOKUiWvHtyYiZuZlTJowIeEUGnCGNpNwbImsFrthVXsGXJGMbckNdFnjvolMhKyZOLZNfaDrkYnTjSnuLRiJSsqeWoIbAJJqqmKQqMyjtKcHiAZjQzf",
		@"VdZgPTfnKQhQAOhgJvTVDbjwcZeOCNGHfuNJddTxNMGsvwnfDhHfxwtigNgfssDbGYBPPItVnXQBAHbPdREEHbSvTvZPMJZICdwGIZ",
		@"nWVJDAyrkuEqvUYMpCQKsIyIViOUqzQpUoyyFBLOzQYLiqGCMSDdvagchCFQZJeAbJAGjZdkxAbWcTfOEEQUxjhHlFCqnVhOvQBfTUOXchdTzYArhBQPdzYZDZxMdicjNIjqgitBzRtqeMgPccMJ",
		@"mNzeAVBFzuoqodjUyuAVpxnnlrHwWuNDBeJmafjFDIcRYjZRuybKElrLazfwYnMkQPhQrySOEmEoKjnDiRBnDdFKbRKpunzVihWgppENqdzumEwfUGjo",
		@"xhmNnSipeHiiyPwZQrosQVGLxTwytioTKhHZssrwNChGzikbXwXbxcklvcDruDzCeHosOwRZjUyfFLbgeUTjgppixkchwtqsnkFBlaSmDTjoDHHGaApOyrxmzDkyiizTN",
		@"eStLzeSamQvAnQeNNbueAVyHIlOuPYsgUyPayjAiVfxzNzaDsKSDsFAjlJAprayxYOIJoNedhnLDsucMJHxafyVcHFdipTVriNOBoFRFUvtMCpRWHdSGIsmNSBpRATWQmjNcvcnLLfwHeDLuephp",
		@"UPdOLHygRntjRrJqSYNDeAdlvCZveDrwcpCfmqJeAhXSpYgpsgVyyGLGsCbWCJXZzkPPmxQFkQMUuYLHLHBtlApzjsXpiYqRqWrfluzwJNZKNgtgEjyoee",
		@"mNVHgIrFyDDYdGmoGxXmuGxamCIMSloBPpYvmIiLBgrxmwbkGTehrHRNWdCtIBBkbYydNieTvufXTLsvAdHMdecFCibuLRdtFVwPJRdpWVE",
		@"VTOLzamqbcxrkwXJjtMUQOoEUntMOPYFEJvBkuOUbfYoAqBDeVEHDagbNqnqyxpVUvPeDfmJqtLnbXjNJDJXDsyDkHfRkAvMxkrKqvMaTwVSLrClgeTVeZqdbypRSyDYjNLZDPhBmGMaNfPgefBJ",
		@"tDupLgnIIfdDWuuAjrsegtEkKrULvHjOLMZxlBDiZaKksHTnZqHBUHLzyeLwxtRRtMmJSnuunICBjDcIbevuOpSIwTpWJEfwvacOORybhDUhiwtHduzRXkvbfVxLEEVVxOsVgTmYrwWhbUkckjSo",
		@"tXYZiFAnFHeYhYJTxgTBnrqpQtPvCTVQysrGadLTPLdTdHLScQeLmqTtJcCHcfMzRLxqdOtvllZyPIxRQkzZYwjhuMpCQtixvDywzmnmJWnHVRvnFomKFsalgOAjiOPRLPvOQGlWoxrZXOfz",
	];
	return KYvsqYsabzwJubAxiYF;
}

- (nonnull NSDictionary *)eSKFTVKKKTLLY :(nonnull UIImage *)wyGDNMZMPYvrBEfB :(nonnull NSDictionary *)LLQBwoZFSLDAMZfKL :(nonnull NSDictionary *)nLRUTKciSRGnwKhtv {
	NSDictionary *SsRpULljFC = @{
		@"KgVJtBXsHXPiMB": @"RhnENanjZRjNRwCyMuCpWiJlfObDGvhRlsxobxZMjKfyLKlePlDismjnSTxFYHtYftbwcyTeegwPMMWKwxEpshJoMzDBihvXXVzbcihcFBKjxnsBHxMbmTkTScIHQSBqMIGliSo",
		@"HFDcnaCknNbgWC": @"LiRiBFCNgcIasSItpLaiCTKBzWzHmnQVKHBIiixtOYHOvOKFlfjWVBjiGwcnsYnmPtHJSbQzDgJnfQreupbnzzwCnbryOCXFeQnXXBdLLLjsiJphIWsJeXCMPtRMVOEUSgppBfuPBMjtjdQQEas",
		@"exLgZOYQLrJlU": @"KCCZKTnryumxomvyMCnCMzeKFWSChYVSSXcKHnzlhFwflOnAxaAdlhzzzgoNnFCTHVGYNwsvdZzoIyAUVWaUPpYDENoCCrPClUCTz",
		@"SMhWaqaUwdFLOsE": @"nJVEItieTHUchlneWfYVCWthCkbTgamlxIXDDEnutYzLvRtTLGmHibGPoUMvHrneHqlnVcqYSZOnkknlBxGCGpWYdgMoItfImoZThsgddAdFiWG",
		@"OQgPwfNeQTJDRx": @"abuPlPqtGobouKJCRSProJgsUnOrqIlVznWahmhDilLXxiKWPpDReoGghCShxLEazeAjhIfwzkIsqVBmHtHuEeUsPVUfKVwIBmTSDGbw",
		@"xZmzqJgJtmxu": @"bwLHTZcWyfZzPoyPwsvOvBISHlSkCmacrKbfnjDmbOXgyxRyuRqsxSysfHbSbnJOHnynLnaOBZiGnsbuuSxDjoaVbXKeaMHQRaWyXwLGMxgGlKguwihozyOOQ",
		@"ObXxbdJlfs": @"phmmKSNGxtQnNonBrzApGfkZfBnNYkwjZfgvtKdxvDwXmjtwtuOlQtsIBOOrJhRkToEcClJAKowuPMWkpXKAVyHebexElckZIEuSaEpouzdYckkboFgijclWcfFUxn",
		@"IMyAixpUWoMGaM": @"yDSWBUFocJTRzvAHugJxjhruJgTDhxBNOUDXyxSqssQvKReesZTIzhKJGIUsUeLazLBHfdxmnWDXURGZivPxknbXCYcyDujwhfmXgUXVuGCcuKTcTkiSQtpsbhDRxsxFJADZwufBVBT",
		@"FlwZpQotZTbFbpfFe": @"cJGaotaMXVxSeIfLzXNchPXAJhdLOHNiaOCBOrtzCvLqZDkRyTmTPHvqvuwJXKvJgxCTMhsRIVMCcyDIElYqVRUAIdJYlEHHUpNoYvxYuKLQGmTTVhsoXdaLLLJTpKfNu",
		@"xAcSShhJDwuOl": @"CejmLKOiEZdzaItVqOkXZDaLkDpojEZwhpZiUzwxLMMuuvTlBcBjFPKBnRdtoHXlivBCJXGCRfuEPozGKUwkZrVlrAQkxryAXiAUxrdgKLxDLpDaokofPDyedEtEmjLnmbSbiVZqifkCNO",
		@"cxkPjhZuCt": @"PROizoXiahupKdRAebiEupWxAjJiJiamcxwBFNHAILXLVugOJjWQEUPakknHboCmyFxRDamEimLjfUmrQKWtwriNztKqTLORJACYDZYLfmTdKLbMloJtXWdgZVBipAi",
		@"wvcPhsGuJqKAhmc": @"RrIXTINbyUiNOpYaActlVoaUgaXRQgVAkwXzqxbJtPXNWyxvnKKtSVrTFNiaNTRsHFJqAJspdANQUfMexhqEynWItZkjrWkzIczMjwggAWaeUjZBzHuqXyPTKUAeOoBbQWbuBhnEDthHqaNjLhiF",
	};
	return SsRpULljFC;
}

+ (nonnull NSString *)NGDFbMWeYluLglrvkr :(nonnull NSArray *)yavvavDxHINyWZhAstj :(nonnull NSDictionary *)zfsMnJyHLUzeo {
	NSString *oVuaqiwluagLTcGQS = @"WrbpOODvnHLelKSUzcxptrdlyRTYQdSYkgyMVXDRvwVlxTaWuDsIKGuMDJuNFNLmkzHAzgIQfpZppgFSCUleoilGTkTvavemnvNrOTMUvwDrBUjWEyNXqbSvLUiCyupiYyn";
	return oVuaqiwluagLTcGQS;
}

- (nonnull NSArray *)zxFmOSZsCGdx :(nonnull NSDictionary *)BJzaYsIrjuh :(nonnull NSArray *)vEUoIJTzaQsDGvIgh {
	NSArray *ScHsLkykSoombtjiLbJ = @[
		@"piiIXhEHWwtZTIszSmWlLVVdBQkdHZKbyLEFzVfyMvGRTjCeNmEFAzOAmOifKJoclRpPBbieQDNauaOweacyZYwdnezlOrzrlaKGjhlfJfFlCmirpHKBjDNWicsskNKoycpiYPnsAGRSIfM",
		@"FAmEsWiwzrUWYwEmUSKXvUqxgMhjttQDNsAiPheGAmZjylezAzXlSMIChmjUNhFalTTEubLjBKyNjunzhjDyXszMJDyRMupXGvdcEzaVivFjeKFVsHeutiHTWyteWCMdivtaKnCCoNAEulsVABZj",
		@"BzlRJsVsCZLnzTEHxrQGgiWHNUCTENhSjDMiWwElHDCtBMQQpnKrQYtZampxduCzAMXXoTyQJAYhoGBNtXvTTpxBRCrCzbrcVrUgGJMcHHjL",
		@"TezyTDZkUYsknzcZOOolOixSDuZqHMGYZmBifwWuNkRsoIQaAfltfVMvVIfhoFRHSEMgvOlloUMJCsyKRyltRfAavkLwiuqruhmQIfvjJVCEywbxrLLKzApoKxdvXnsChZFLIESzwZHLX",
		@"DgDsOWftESXJPOIbXhDSRYQVdvJgXRbyubcqTcXSLuSfGxrmbwhgMyulLyZyvgEcUrLTikIWtLjPNUryoicBzLizrvTgTujUdSytOarVjfjFIwAAyiBOyTIpXGnjiQEKp",
		@"yGWAPfrKsFjiyFCyLjiQMFzAVRhWnmfoOFEJGUqWkfPxmvuHgNsGVLRjwCiZAbAFkpCczAfWrYpkHIPmSxqfuBFcMIcqbgSttmnwfReuH",
		@"mweZJKjoqupmsDZkPyzxuyhMBtlhFYTEBuGQUhEypRDZjIZnjOaiEmUMSSSZwMADdiGFRKPtOtqGuappHuDGrGiyCyOqqgVGuyQZkLcwMACdZkAiRWPfDLCtOYsGFoxWqYEREKJbUymppSI",
		@"URSnLbVmJrLSphAawHyaTOQoBdZIRLdLVRYLykkLTIGSvEPOhqhpOrfzyCpLFFPPCVIjtOfagYZLFwYZPUJxEUdvkFbPzIQRmOKBmSGYjkMQRgGZFvvpeYcOmIXfMwCvMPewCE",
		@"GRJsutFdLonSDuVnNDTcedllKOnNXusXaCCBNmPYaebNWStrevyAPmwlvjJPcbuwHbrklJKLELTdMOTgMizsIJOXryjBCfetEFNNMsqvZbBcjhIvdwDDxP",
		@"lRgcWdNzYPAVoqdRWUZModoQNKoVVPkaoxiCLUWwTPpweBDLIeRQZlZXTfazQGgkAPCdvwQEeNCUzIBUOZUgCLNRRuGbLvNApYxBIWXlWDAxImmsRrouWqlwYg",
		@"ZrxikFmxveccraOnDQGzQZvbNCCxqnNYybxBuvxeUbfcgBMlrPUAFOxoZVAvQQDsuaMBwhYESVvAyfJTapcOuUFgaSYQerTFElGqFXdOIifTs",
	];
	return ScHsLkykSoombtjiLbJ;
}

+ (nonnull NSArray *)wTWWaERIRZYY :(nonnull UIImage *)yuWebuXxHxxvzy :(nonnull NSString *)bkFMnejhRTFHtFwIJL {
	NSArray *LiHwLqBwAD = @[
		@"xeAspnAkRiaFecZoAsdKOxJPtsrysPIJQgwJTsxxKNQfsNItiufflzqwVsgoGGmmSvsHOFOfGyZgsHIRydxyfkKkrNskaGlmXAHzQCyLuMOp",
		@"wtLtpSVokggoweJJevFhItklGcWOQTVPepZAZsxTtwbLZdaJCGENnZlvblgmYQujDbVsffBNbgvMlkrttnHgnsoZOxvJMyzPsbUsLixPy",
		@"qveCCZorelcJixLsLUNnhcAWdcOtNPcfCJLwGCnPrqiSdjaGVIEZPnPxKpkdECjDlbQBsiOepKuUmUyqPLVurTSEMOBlJiKHgoyvZVSzPjKfaATMtywdothkNICwOhQAigUeWl",
		@"PCLgJMwFotscyyHZHSVoBduSvXraEMYJVQmIXshJfTeQMeWhDUqjwdzycSubhlKhprlowcmzkYCDnAhKRPXlUjgnyxFPSTIwKqmYInFhRbBXeUIFQYJrosJnVqGGOkwuGnuE",
		@"pNqfcgQgLfjcvsodiacryEKpXPZTDLWNyKVTRWwXQknWEBYAtHmvLiqXWHprWFrmFrzVndxIiTZlpmjLAfoChWFAvFzGErPfjGcICkBHCytuZKpcilrgYyhvagZMuBUIFGiLoAENjNO",
		@"HgvXJGIemcDABNUtsTRoirhuFwyIBvrQqdtmVEKIdOZzUcGpAkbdiJkcavckTlQcRvTraQYqaFHtojgVmiiBSXYqSTJaIvvoqaDDtiSMZYhSRJOwISmsvSapwft",
		@"pqSTlqMYiRcJVsYrYtmixEGskPDxqOtKKQuVDPGJGPVdFoGlOxYuWWbRmwAvjpKbtJIUnpkpZradHCpQgybDNyUoVVCndYWQDemnRnvqgtIFKTcTqmjjzuHyTmJJqLIj",
		@"RSoYNgjaHPbpKTsqNSNDhHGFCisQjrBJuHgWlsIQESYiTmWbhhyjFTkhLoguUCRWYZrgspBeKxbfzHEJuGPifThxNPltSscnJPgsKvjpFyLnySLILFWTMxBSrmNA",
		@"FPWsIaXPBXQeVSzDzuQMYNrASRSSoAwaBQVYOiNLTfXdZdibpMKJJeCWXxzySjLyrtwccqvofkOXFVqVscjPyiQyQbVmJZAbBWSY",
		@"zyniQredRTGHvPArfgsczpAVMHTIKQxKaRlMjAarREwYqWJWmrtOAEeDTRiziPKomHMjqDqztkNuPIWyUpVcgjsjQTLEJOPIrZXWboJeyrNeslFDYKGDBJiRLsGTT",
		@"WUPAeBKroxfpvpdnvfRwQqOqsSNnHUhLqTHXYitlOWgFemwozFlbZmorhaIwhzaZuChXSOOcNXUaNaeOQRnfzVYpgENotyqpuIfsZEoMGrey",
		@"FTlxUoZHVqBmwkvYQGYCddhyyKXPjtFgCdoKzNApgkurDtHWMSVQcjRRvoSnzRnNWozGTrobmUxfGgomREfIACVFKVomATNokHgRGTFzUshjzwOReZDpQStPUUrKm",
		@"ZqPYnobHroUGheBoOMyugdJDZdgNWJkwrdbfOwFJXyynmHJdfPKwSixeFGteSlZEpNhiYtRHFSssDOYDUqgQcTasIQldiCpToVUGNoiJOLMm",
		@"joiieFGKZcZamQKKkPqIYzaEldNAUURBXCsgTnqWNmmMqUKCztFJWoZRrQwShmaWvihIDthLBRVbsURJDmYTsqkyVbvZrDPgjyrsYwWDIoneBeAgmpybyrZVeRvAR",
		@"mHHfPpPdKgksFeSzgnYZDescWsJtrhLeiqZWCKXpyKvfLQzduPbSZpzqcKfJNovKwovKkaFkzUSwaoTapEhBnoxQPmuHxCuqbVaFzqQweyCokLrkOoXiduBrQZPXiWnETmfFBFHPj",
		@"bNpECKOTeguIaiXmNasZdiAkspZCJqxDlLEZACwNMlWvzdUxWvArvVhwFAuSLLEVimmCCYgSJeUCHPWZXfPgpfBkQyuvAWrAIKHcRevTFryoLVOJRguQzMXhYayDoFCCorozGdGoheVfwcgnNUEx",
		@"mYWZtqJgAjLYMkYWVfJhxOXPGNQAQKntdMSLSvFUJQQHvDiRxzlgxDlqlAEwIvWTWwMCYEqpOanwIKSNPjxmOLZWGZiIcnYLrAXFtcyJRmTvEIOQ",
	];
	return LiHwLqBwAD;
}

- (nonnull NSString *)TBjrTAUOftWQvHLIfd :(nonnull NSArray *)aHmAwzQAiiSTj :(nonnull NSDictionary *)vIXpsNahgo :(nonnull NSArray *)jfqAVpldRdxoMEhnsuX {
	NSString *xBBrhqtoxwuCjKq = @"dSHuMdekAKuLELcRJGLlTNRexHguOLwaaGSnslwtTgagesSpfEsykwipokkVLTQaCkctiseWogCZfzjopUTmLaUuwiBVNxknNNZFnfOgogpyGNqrNiOXbzy";
	return xBBrhqtoxwuCjKq;
}

- (nonnull UIImage *)aaZnOfcjXhetfkiPJ :(nonnull NSDictionary *)pcUMxnSxhYQPxAHEWkA {
	NSData *GgrMWQapWzhzcFLOn = [@"TyGBuVSeSPoyCuHXqCvCHWMrrDjLLynLkLstdTwYdUlZhCWdTPfAohmYnQKnhOTyUedWbPeXkZSlamqamFKtPwguWsJMhyzMTiHiuUrmhl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QDgZDICgGVWvXPzWV = [UIImage imageWithData:GgrMWQapWzhzcFLOn];
	QDgZDICgGVWvXPzWV = [UIImage imageNamed:@"AekqBQxoffqvdyVQstXqxgCNIuekgvnkaMMAuyNPhxYXSoepXUzPgKnDxeSSDTdDmiLgpGvDfKGhoELDHHhfjwQdRWMujQNWxdvKxSSMPLKHdFUaujQoMb"];
	return QDgZDICgGVWvXPzWV;
}

- (nonnull NSData *)AYJCkAiABaliIs :(nonnull NSString *)FsNJrJntJxeTwHP :(nonnull UIImage *)ulWycgySPlRLl {
	NSData *XrnBlTdRAgfkgSMSwK = [@"RGVcQDouVWsgmZFppYNqBMNUaCUjqouFuhfZnEytjZDMONdfrDmyNaBYLOJQDskOdqJeqjyFdHpBFVRJvshqGPZLwGJtWBvyigBiWrnRNAohkGfRRXRbKmpkwhDbUvvk" dataUsingEncoding:NSUTF8StringEncoding];
	return XrnBlTdRAgfkgSMSwK;
}

+ (nonnull UIImage *)TOALTYMVpE :(nonnull NSDictionary *)YHZPRoeIEAM :(nonnull UIImage *)oNunWxsEwbP :(nonnull NSDictionary *)OnZLiGXmqbvjV {
	NSData *OgLbvhNoxSx = [@"cqhNPCyDDRvpyOXHxZyAvMbElqSQOnRhqTJdtYDNizeRcXtjzvDLchGkRXgfIkZxhzCPYCifPHTYDPuRYBOhdddzFPGQKMMfTnfmP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EhWtSdbflqEgPjlCFM = [UIImage imageWithData:OgLbvhNoxSx];
	EhWtSdbflqEgPjlCFM = [UIImage imageNamed:@"ZTnTSzHCooDkfdhoVzAhAXGBqNvzngdeZZchPLIxDmthSktYNAEUwSwCqDVkuvjDjhcxYajhkYORqzIpzymyLdIubUiJSrtLccNAmaYQMECVyZkliYKQybDjsbfCyzaSVfkkRPVwSSjb"];
	return EhWtSdbflqEgPjlCFM;
}

- (nonnull NSArray *)mXejdpMQHYedpNVHHo :(nonnull UIImage *)TBCgQCeGumcAjoCIvs {
	NSArray *HjHhaIKAzvBVt = @[
		@"UYjHHLTPipZnyADoIwRShtWvyddJJbmDlfLaCgWgPdmtlIVkVbfVlxakWLarqlySlDcbTBwFsxBFRKwhkaFuTPgsDBoCQnupOaMxFUBwZLWPHbGxDpJEEeByKjkwggUkNkzlgnXtCHONCScRhiBs",
		@"XBGXJDYLMLArbcGhlariAHvnCJEvaxVNNlcLmMQnAlUSkUembvQYLWonzWiLOyYJqwQLylxVRwKBKfxnCgFlgSAJNZoCkmrfvmqPWXrSUnbWXmIvbprlzZjMiItXHrtowhNEXc",
		@"AWNeZqMHThbEOzbJouHqACYMIcSXJcxXXdpoZGIIhvKjmToolBslEsJaVVuzLfRJUcRNLLtCYIdaqvfWIWXJpqKUXNpsNhmXjTDK",
		@"sYenBrmBjvkHWtnxGpQSBvCbNtFZwZnQooujVGJBdMVpWdReaMnWgOzqiDalsLmHVzicBfdPTkdlixPNHDWUwCyUVvRrQzotOTqNGJfVijI",
		@"PpryNZPCLNzQgEnZkBLVUjEDfoeZFveNtRlKPqlTugkXzZpvlQiypOqXmSmAynObMrWcaEpsJWWaCXuTfZkMBivztwHJLgLMIHvOTRVteKuMuDwlIDhwaAQvCJZwBZRPAlaTfzgQLQaALmcigwF",
		@"WGUxUTRxGUHcLhkWnJMlywDUFuWBxKmglEQksRItSgstwjrOCNzMtywPvBVCSnaZniCVFjwYMGyAErqvWgzzKxmsyMJjoQKbNGlRzFrgbfPEsBjSmySugfbzVuTJzYUabCDKUMBMj",
		@"bIAiqhBtbPepvipReexLqCWXQOpKxgFzNPXfZGsbAnWMGYGBFdZOgcMxVYYfJZQtcxBFkOIFUlVSjeBhPrnoEQBseRRuLXMvClVDN",
		@"ftZZSSmGWfJRIRWSWVlFSdeOhmCUFgwEUSBaggQKQeiyEotjJFCPgtZyOgvkdsoSdzYylqmAIfQdPnRqTtlZxLMMPHwpnoXkOKkfjVqiwHNfCgbjKnBpNDDLEIUm",
		@"MfGNLluGbzLxbYvKYVTlOsnRkobHuciIuUTjSdjDFXcViVsViEvdiaCatDaPzTcfJVUBYlvBQOeQbrAhgndyffwayxLvJYUnHneTvYZpHBxPSMuocFRwpEvzeChHtkvNNZgaPtGharbPV",
		@"tGZaYPGmRcBPDtkBDYMqXqLxIfJZIOQlbyEOUKQhkASAEkrwrHDAKUTFTqwrOPSUOUyezRFFhzWGrmEuwNGOqXlqunCiLyuOoHTBVdBiE",
		@"HWiCsaFHKiPqcdtTjUNYLtIWstsgQcaOvMHSoDwwJWOJjzAWwmdgrVIpcsrWvyUkcXIiGTWWnKsrAvdbdEMQKFOPRkjGpVOqpCFLBH",
		@"QHbfhTRkWYmnwANKPtdWfxKpPklWrWiEspXCmTSFotMStsQYYiHRdLxLepgshDXNqjsHJyCkvJASCbAvIuzSZRnVtpvrgxYwwqqbbGzFVkvtTMxWivVPXzygHlUvRfkAxa",
		@"HakoDxpYHzJwOSLFeInSlhHZLtzHzAFyZaZBUSyCABElBcglIYASduCJfmZMOzJgsTafAiwHLzhsAUcnlrsJFOtoYyngrgikiLLEFlGIIbiCIDlxobahxfErxGmpzYOmyyMDQHpts",
		@"uLuiNEPbnHxiWfkLMHpAQjYFABQbhlnjnQIaUldopXMNWVJEPHckkCGGRtDRodAWvVsechJxhjgYrIkUeSuVitHpzzspPPfKwBrJAgqNKyxxqimpOmUwNozYDxqkhWVIhdjY",
		@"LaKoBmLSfnldlcCOTTxskIeQIPjQDhUnqvTWzFGpXojsyBYtUeRdXXmbzInYakILBZDMtnhZmnznREZUcCLYIDQHuELviIotHoTlkPDNuKFLAWdQEGtDBMpaQo",
		@"zhnYvwuIRJowgvTgYyFAcUzVkceQZGFYoEJTEXroZcShBLafcQDTEWXKzwTcMfxfHkMtDYCrQdcAGFcbsxhccpAWNiRoBQwpoTQRpfWbdeEnciuQVZuqzqkHK",
		@"ivxGaSwCUnYiQefmhjsgwXSELByDrhKCXbCspANYRaNEOSVUItimQpMhWIoZtGaRFTetNycrpSKaDiEjsNWKWkQvmRTIYutowZQsSAvuuFpzfUOCXogWTjqGWFaK",
		@"NoKDiRDHsQgeZsHBSoCGGCRgAXuuDzfmyqfwULOUhhmDocnFaLZMWVpVpFFjoiiJpdCMxQycZKGtRlgsSusKznggihrvQYyDvUUoVvltNDAgtaYKesXQjbnAGtQaNbAFIvEagyqqqcvSVAenhSyyk",
	];
	return HjHhaIKAzvBVt;
}

+ (nonnull NSString *)wWmaSlGeZHBciucVZrJ :(nonnull NSDictionary *)NcosLqwqARNOW :(nonnull NSData *)SKYJnYiAwRJRYJiiyg :(nonnull NSData *)AkvothbNyEeRIOkCao {
	NSString *LABtsvwfEdMbwquCafq = @"FjtjCtGjryouKcSTAWCfWCTiMdhGnLVSDvTqhpKKLHpKPuppnsvlHEKsRTUVRgmuSLCKdRYsowtdOveFLzdwtPPEcpHKrQShhoMsiMtFQAmszUbq";
	return LABtsvwfEdMbwquCafq;
}

+ (nonnull UIImage *)KcubUcVobjncX :(nonnull NSString *)JibxhOiNXrnZicFpda :(nonnull NSData *)CammvqegFveeBwTzbJR {
	NSData *umrYvIKzaN = [@"qAyNSmmsMmPFkBQKzMlzEArovnNPaLjwoRogJuNtqzctfNZfUztfodfRCXmBBBrBvpWdEhZoxHyiQnbPzGDDHVNxIObqhLLaRNzjExDVBvsQrVWGvyXUGDcJlaLxWC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TsPKGCGAdRmA = [UIImage imageWithData:umrYvIKzaN];
	TsPKGCGAdRmA = [UIImage imageNamed:@"bvYrKrLadGtfEWuGqBYGrSamSNNPvuKnwDnApcEXEJseHXNQymhSVOYlEstmIERXpWrjAGeaNiNDveQKrvuobyLgAtIflTerKwegTKBcdCMDZEfnYaTZNUyhl"];
	return TsPKGCGAdRmA;
}

+ (nonnull UIImage *)PjkcoODncv :(nonnull NSDictionary *)MaGxJAQmLzienDMwrR :(nonnull NSData *)KwanVFcXnu :(nonnull NSArray *)TqMSElpPQRJNhj {
	NSData *PQvlLjvZlbtdKwc = [@"jPczJBmFmhqwFxuTfiPUVLCeaYeduIuVzVOovjoKIOxcOiKMbqoSZzzzySfaljVxGZmNeSiYAuxlEAasTaDnUcGQaIZUfTziEokUxjdWcYVSlfgHhdNAlpKeaiTbnwDyfOgFTapg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NaHMTchbtE = [UIImage imageWithData:PQvlLjvZlbtdKwc];
	NaHMTchbtE = [UIImage imageNamed:@"srauFdveMXBDqwQrmqAhpXPebsxBGgPxyXChqNmGMqdDkSaTiwlhfHgwoCJosLXqtQecOUTDbxPFKzaZAUXPQDvwpgUkXixPIJrUSS"];
	return NaHMTchbtE;
}

+ (nonnull NSData *)agJVCiEJYVHgSZDM :(nonnull NSData *)cRyASgfBQob {
	NSData *AzMkIcTintXGsotCG = [@"WtEaLUHqsKhqDaevYgZMCiVqIQzwEEXUSfurduBSUxShYEgIyZzjtrpUxWXEBmefVdUFVXiMaePlHVGZIzCROymDUIepvoAZQycboBiEDkbEcQfzXCaHwRpsKMcDNmHsNzgAmnPAEYNBklhZ" dataUsingEncoding:NSUTF8StringEncoding];
	return AzMkIcTintXGsotCG;
}

- (nonnull NSData *)JrhGjELLnOZwdx :(nonnull NSArray *)hLOOXwuawLZsjtg :(nonnull NSArray *)ebhzdRbeVhNeOIzrqrf {
	NSData *mPXPjPoRwBpibaBrlu = [@"uGaQScMgxZaJyNmfjaRKJQPeuIGdnFeyyqxnunoDjQeZQpgauceZCyuNrLBQSyllHdiWCuPopwcrNgKWdwjquFknugNqVEykvIbAwrKowqXLKLWRxnlmLUKxQAXJr" dataUsingEncoding:NSUTF8StringEncoding];
	return mPXPjPoRwBpibaBrlu;
}

+ (nonnull UIImage *)QqvPZjCowvTuSPBkFD :(nonnull NSData *)fzAtrZaSgeeqNSyTRBu :(nonnull NSData *)cHNeTqHMLHMIPuyiImM {
	NSData *rTqinkZamfsCWBzOYjv = [@"aBoygeuYFGwASVOddVXIhRbaCotojDqUGqQkoeKOGAExaVYeiXweWcdmLSBBdUyTwqTNAbVwERyquXbIojKCrGiPRmAQUbrMvtLmXMSmaTVfyycSlAybKVvJCAArMbkpnLCTfbIoUabGsbkpOLP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HeTjodIolppjphl = [UIImage imageWithData:rTqinkZamfsCWBzOYjv];
	HeTjodIolppjphl = [UIImage imageNamed:@"RPTolXoSAzgHKmIoyHvnjKvudLrcAPfFYTlzlfMCTgufnEqzPLutksBTunRDLhdvvsZZHBeGHOCHnCExFdxQZidddwgpHzmMhineGwCvaGlYsagn"];
	return HeTjodIolppjphl;
}

- (nonnull NSArray *)LMgwOglDwdB :(nonnull NSDictionary *)nPJlBJZveEVqvzotmrz :(nonnull NSString *)YZBonTWFVfrm {
	NSArray *MjNLYoETSwGqSEpBJsT = @[
		@"prINrVrAlBxPHXNNeqnJHHMfbyvxJeNiFRybHiHAIwNKIshmwqInnxdqFnJxBOLNmpzEgNJsfDyMUYhqkpEajYDkEndIGWAzAHKIwSwrrFTXWebNmCQEiJGYylECopidXWuHsJPxwQ",
		@"GJoAmuvkBjDHwbPaQHghIgVeWRWUMKFUUmRwOufFLfIHuohiSfYlchkmjXsWDMvoXbQlzqIHvBPkxSyZKLPKebyQDrMoIjcacxJyh",
		@"yzIqWpNHrevbtZSMscYYZbplTTwQSKAHTjRHVWKegAchgVtKXmiEJKRzlyDBbMjFQrARyMgnsZLPVtIaLsYzifOWjTolryyMaCWrlhiFdTkgTLR",
		@"ZuBrxHpJtpRBPbpbmMXkNMZIRmsFpIKQAPfyVHeujPNtWHMEWsxWjHpgejVgYaTVvNAavxQuFJNaGUAHWZpCQfwougwFwUcwJpNsILTfAKaCQAioZexjsTvCooWNXwzaLJlbibfnSDDpQkYgMd",
		@"DoJQuTOhPoKgztNkupHrXMprzRkjMHqVhqCHgjeECvrDzDfTaqwOXZVQPcJvjiZsxKVhrLxPVlKtHCBusQxshcIFdBWBiPzNcDqaJDyfClwiQsPjQiRSlvrLx",
		@"ZwHhxHclZOiGvpQuREIkHWRNlgXXkYXflQPoPuUhWnpUbhhVkNHdBmvfDKhwOomejzhsboMWcRZgHYsYptXwcjCtkDbsFXPqvXWgYHjdcOgukFyaulWtetZXjwOPPJUxmpbY",
		@"ewJxtuTzKdlzQxEaXoYAMiLhttDmQjgTWtboZLUqijwHEYhxqwtfdrVQIlnQeTdQkgHYmwYdQaYslCOVCVwJbCoMbvHdzcYpHDKZA",
		@"zzVgXSLucaTicSSCgQfmITBnWiPaeeeXpohdAizdxZBWsMpwgUkVxZzWVXzlBrSFupbpUAGmdkSHcxhbyUkwLvaiBEnBmgBpGVot",
		@"lTSBySDtDXATwoaXyGSJkrpikgqWBJAiLZehsoxBEqtwpRlPJYRQtUWTGBkwclGmsISrHABsTLLuAunPSVPbqiKIkTfTYHFteAitHdkFLoASxkhOJMxiSUXghaCmHyJYH",
		@"GMWkRLqSsZERHPFesvfwEIJiqdXlbGnTRzmLatdDlhEXxdktnfXWMFzEHeldhSSJLIkvhNYypJobiGzsHwVUCeBtKATKLNHwyVbMLdMPjDoGGrglKnWflani",
		@"fRoFNbfvzXGgxvhoIhiJkArGdPUyBNcMxPEzHVKWvOjluIbkvDGVOzDueYVzohXbxkDcnvjLTgtRWUgoghATmYOPLtznDzjapubCzkHKcwCZqLxmthsf",
		@"zmDBeMtBnximlzyTqXPMogMtJyQCavLvujOfqIXDAXOiFkoNDuFYhEAmHwnhlmcQgqobpdgKoSOWTtRlINlACwhhFvaBdGRndvYgMikaHOJofYGPPbne",
		@"mEcSzUdPmhEZHyuNSpgHRzDxtxJCCDjsuAFhSgPFNZxUnPfFqCnUjVkyOUVZKNxXgRWrrUosfMgvKdfLvFDxKpRwAGECXyolMSjK",
		@"GizSSBUNxPEXWAxMDfRtMceERgjRQzXSryDbyMhuHkQzEmriEMfeyExJojTlAWzzMAjAUAKNqaQtBwMYtEjotEWSKHbFsUAHGNLvKTMyvCxNDzEgywGJ",
		@"pItRjYuftZheLpaWRvvUPGLxIGCcLBAWHIHCOKiFJVfaloRynueCWSBQfNZwLLZBVxFiWhCZvLayANVHfPqAMpBwVxvUVSZpafzzlqbJGAmKqgMfawaiPtmewmOW",
	];
	return MjNLYoETSwGqSEpBJsT;
}

- (nonnull NSData *)EilaffHMVNPyslIVZ :(nonnull NSString *)mHJESzZdfpaxuuU {
	NSData *ZppZSplZNpgXgceUtJ = [@"IxxhHpizEonoaYdwqFMlxqruICuPBAimWuEribYLCUdQtPvQlsnCFnaXdwfsgfTDEYUvTVfHxNrXUhrSPDRIRoHmujPxMYjEGYHTbYrBaarxpmpEpbYrilNSXTpUuQnlyLnrOSRfLkBhwDJBHUX" dataUsingEncoding:NSUTF8StringEncoding];
	return ZppZSplZNpgXgceUtJ;
}

- (nonnull NSArray *)XBOlYLMYMvRqbuRM :(nonnull UIImage *)xLeMVoPnjQvLuxviy :(nonnull NSString *)QUheqNJSLbPJAgZaLmZ :(nonnull NSDictionary *)fuACpwdKEEpPhwXp {
	NSArray *JUqlHfWqvyOK = @[
		@"sjSuJekOTxYcFvjDAXNCmFAGWngBXfmYIGbGaEsSKjEKXBmuyedpAAfKQLPIMZmpSFQPJYBDWfnQwyYckMZMNkLNlbwhxozpQAXfOGGITuHvEpszaBUGevoOaJpQO",
		@"PlYQKTScGvdpnLAjapOTLjmGVZnYlquBRIWvPtjHkyHTmMroCVxqykwqvYAaHTRQIrekSWgRCyNjURHDxdDCfgtCTlAWDIsTHhsSPES",
		@"xZIoiohnKEtDEMkQhHvJzRoFCNiFabnhwgjZOwdmeZKBBobZpZOfgyghxEyaUrEBGjiKCTGURWHWLtztYtXYgrylmhduZZXNLSdQgUTOjYiEqsCfCzs",
		@"dxvrTJjaCREPfglQCbAEXCaDUltmVIipyDNsrGKfLSCTjokqrCbAcXPIiQPQIpPqSViZCzJeieiujzsfGxXLuIdiSWqtOqCKqYwEZRqlzNXDaNqppJYNZjfJunQT",
		@"DOVvnYPcpzPMItTKyroazwRYtsNycJfqJTszYestbNkoHwCgaqLSQRyFrNMaKGCRMSFfxZzzCmOkyVzjyfAVsRmvVoxYGFrzxKhyQXuuTSndbPuZQFExRDnuXiBnlGeplE",
		@"KUiUkahDSoWdKvzFqRpPGedeMZoiOekwJZVruNLAUlPaawRzOSIRgdDPEZCWTwCTpRMSOIaZmJJEXclUONBMSANCgodbGDtyGctvMACjuTIbvXZtQqN",
		@"YDkafJuQBOrNeEEZLWPpOmsbpcFrYtJTxbvyVOuwPMVweKdcNhSBxYpdnDMGSLawguCayMoKJXIUfZReiFzBMvTMYQeMDDBWIQcDfRfQmaAQtOfpLwAbzAIHv",
		@"lahaMdGUvwmBXcbSNgsxFZRYgflFSsQRarBCovLuMUWMazcMNQoQsBdqsWbZgucvYFNFdQkMtKwTdRdxGUiRMDRgfCEaTIvkWKtLvIXZGeaENcQsLDUyNWTfoZCLdhduNCzUNMCG",
		@"XzQDjlDaPcotSIhtmrXBYTRulwQwLsujosxJTxAunDHHRZoRAcGoYayOwLuvUFUDIBmvpnhvIsKmIkvPZkbbhGNtImfGIERceiCWMIINJUZhEnFRdmfepIxMfJDI",
		@"UvQoNVinIYFAPtuWDyorwsyZCdazuFYjkiMDsTpizMbrFuLmGyJySOkzZvPQRHrYyHSnyIanbRjNjRBuiwlVYTzjROOVNIXwxtJqzobWNMHzKfDVQlADgKPOWRrEKgLyVZyAI",
		@"xPocGCyaOLfTJDSeYPLJduFRdrUvdWvfHjfERHSiCjpUTWeWhNGYPtVVAbuYNNNNUledzEdTOHMHiGlUkFSWGVfhuhRIVpCRHqrMqeWaEQkkQJQJYEHCMsCWtdtoAAYdDrbiyiPu",
		@"LBLQNrHzGlgSQcLhZAuqErYNwRsWYcfYQfoAcXJaQcRnvvOvBMUVHSfpSMyAuraBVQbYDwpsfZxHExFNMaDPcxjJHuqnMuAqHezySuFRfQSvmMgsixUFWHHqjAoBZFZDiNOfagSVnxl",
		@"VitIsmyBmqlHngxdzLfZeoCbOjBfuUjKgBpTMBoUBznbtoaMZcaupGrPrOslihFURwAApwXNjatayebXIXWXaOjMDHvoJyoGbFqCNVFxaTnwiOQqFlFKdtnkhkxPMVwyGWqphSMBEZLYgepmmfez",
		@"uDKPJOoDprUilpKvNStCdfbuueFnXsHlKqsRAdfvLNqHEGSCPuHVCwnpMlqsVKdHlwccQJEHjQndYwNbfGXZfHlylqQhQxBMtMkZuAeZHTmAUi",
	];
	return JUqlHfWqvyOK;
}

- (nonnull NSString *)QQodzReitBYb :(nonnull NSString *)qDgsgGQuJKMksnKUW :(nonnull NSData *)CyOfUHqUpvtmNJMgYSA {
	NSString *HqXtuGLlDVXaIIm = @"ssbVsXNDackseRVOWPbbbkniIZJaYuxNdDvKLvZELeLSAzMBqIHGRkbiJRlXxqpnxJxndEwzZMWyolMcSOvwQxOMPSNCpBHyqsXbpqspbEUicwGNDWC";
	return HqXtuGLlDVXaIIm;
}

- (nonnull NSString *)zcMJMNQxfHBjjcNh :(nonnull NSData *)bKTYMQYYPvfazxjvse {
	NSString *xKwDbYPndObdUtUtOB = @"YnYMdqXlgAeyCmjPzlQPaKpFfyPseGPfBZabVndrmThGccKsUtHEpRuAujxIENwGBcVMAPiysLLVvTNUXRPLlHzXpqhzQtUzIpYaexZPOZxTsSMqzcuejzoFPJagKOUq";
	return xKwDbYPndObdUtUtOB;
}

+ (void)showErrorWithStatus:(NSString *)string duration:(NSTimeInterval)duration {
    [SVProgressHUD show];
    [SVProgressHUD dismissWithError:string afterDelay:duration];
}


#pragma mark - Dismiss Methods

+ (void)dismiss {
	[[SVProgressHUD sharedView] dismiss];
}

+ (void)dismissWithSuccess:(NSString*)successString {
	[[SVProgressHUD sharedView] dismissWithStatus:successString error:NO];
}

+ (void)dismissWithSuccess:(NSString *)successString afterDelay:(NSTimeInterval)seconds {
    [[SVProgressHUD sharedView] dismissWithStatus:successString error:NO afterDelay:seconds];
}

+ (void)dismissWithError:(NSString*)errorString {
	[[SVProgressHUD sharedView] dismissWithStatus:errorString error:YES];
}

+ (void)dismissWithError:(NSString *)errorString afterDelay:(NSTimeInterval)seconds {
    [[SVProgressHUD sharedView] dismissWithStatus:errorString error:YES afterDelay:seconds];
}


#pragma mark - Instance Methods

- (id)initWithFrame:(CGRect)frame {
	
    if ((self = [super initWithFrame:frame])) {
		self.userInteractionEnabled = NO;
        self.backgroundColor = [UIColor clearColor];
		self.alpha = 0;
        self.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    }
	
    return self;
}

- (void)drawRect:(CGRect)rect {
    
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    switch (self.maskType) {
            
        case SVProgressHUDMaskTypeBlack: {
            [[UIColor colorWithWhite:0 alpha:0.5] set];
            CGContextFillRect(context, self.bounds);
            break;
        }
            
        case SVProgressHUDMaskTypeGradient: {
            
            size_t locationsCount = 2;
            CGFloat locations[2] = {0.0f, 1.0f};
            CGFloat colors[8] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.75f}; 
            CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
            CGGradientRef gradient = CGGradientCreateWithColorComponents(colorSpace, colors, locations, locationsCount);
            CGColorSpaceRelease(colorSpace);
            
            CGPoint center = CGPointMake(self.bounds.size.width/2, self.bounds.size.height/2);
            float radius = MIN(self.bounds.size.width , self.bounds.size.height) ;
            CGContextDrawRadialGradient (context, gradient, center, 0, center, radius, kCGGradientDrawsAfterEndLocation);
            CGGradientRelease(gradient);
            
            break;
        }
    }
}

- (void)setStatus:(NSString *)string {
	
    CGFloat hudWidth = 100;
    CGFloat hudHeight = 100;
    CGFloat stringWidth = 0;
    CGFloat stringHeight = 0;
    CGRect labelRect = CGRectZero;
    
    if(string) {
        CGSize stringSize = [string sizeWithFont:self.stringLabel.font constrainedToSize:CGSizeMake(200, 300)];
        stringWidth = stringSize.width;
        stringHeight = stringSize.height;
        hudHeight = 80+stringHeight;
        
        if(stringWidth > hudWidth)
            hudWidth = ceil(stringWidth/2)*2;
        
        if(hudHeight > 100) {
            labelRect = CGRectMake(12, 66, hudWidth, stringHeight);
            hudWidth+=24;
        } else {
            hudWidth+=24;  
            labelRect = CGRectMake(0, 66, hudWidth, stringHeight);   
        }
    }
	
	self.hudView.bounds = CGRectMake(0, 0, hudWidth, hudHeight);
	
    if(string)
        self.imageView.center = CGPointMake(CGRectGetWidth(self.hudView.bounds)/2, 36);
	else
       	self.imageView.center = CGPointMake(CGRectGetWidth(self.hudView.bounds)/2, CGRectGetHeight(self.hudView.bounds)/2);
	
	self.stringLabel.hidden = NO;
	self.stringLabel.text = string;
	self.stringLabel.frame = labelRect;
	
	if(string)
		self.spinnerView.center = CGPointMake(ceil(CGRectGetWidth(self.hudView.bounds)/2)+0.5, 40.5);
	else
		self.spinnerView.center = CGPointMake(ceil(CGRectGetWidth(self.hudView.bounds)/2)+0.5, ceil(self.hudView.bounds.size.height/2)+0.5);
}

- (void)setFadeOutTimer:(NSTimer *)newTimer {
    
    if(fadeOutTimer)
        [fadeOutTimer invalidate], fadeOutTimer = nil;
    
    if(newTimer)
        fadeOutTimer = newTimer;
}


- (void)registerNotifications {
    [[NSNotificationCenter defaultCenter] addObserver:self 
                                             selector:@selector(positionHUD:) 
                                                 name:UIApplicationDidChangeStatusBarOrientationNotification 
                                               object:nil];  
    
    [[NSNotificationCenter defaultCenter] addObserver:self 
                                             selector:@selector(positionHUD:) 
                                                 name:UIKeyboardWillHideNotification
                                               object:nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self 
                                             selector:@selector(positionHUD:) 
                                                 name:UIKeyboardDidHideNotification
                                               object:nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self 
                                             selector:@selector(positionHUD:) 
                                                 name:UIKeyboardWillShowNotification
                                               object:nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self 
                                             selector:@selector(positionHUD:) 
                                                 name:UIKeyboardDidShowNotification
                                               object:nil];
}


- (void)positionHUD:(NSNotification*)notification {
    
    CGFloat keyboardHeight;
    double animationDuration;
    
    UIInterfaceOrientation orientation = [[UIApplication sharedApplication] statusBarOrientation];
    
    if(notification) {
        NSDictionary* keyboardInfo = [notification userInfo];
        CGRect keyboardFrame = [[keyboardInfo valueForKey:UIKeyboardFrameBeginUserInfoKey] CGRectValue];
        animationDuration = [[keyboardInfo valueForKey:UIKeyboardAnimationDurationUserInfoKey] doubleValue];
        
        if(notification.name == UIKeyboardWillShowNotification || notification.name == UIKeyboardDidShowNotification) {
            if(UIInterfaceOrientationIsPortrait(orientation))
                keyboardHeight = keyboardFrame.size.height;
            else
                keyboardHeight = keyboardFrame.size.width;
        } else
            keyboardHeight = 0;
    } else {
        keyboardHeight = self.visibleKeyboardHeight;
    }
    
    CGRect orientationFrame = [UIScreen mainScreen].bounds;
    CGRect statusBarFrame = [UIApplication sharedApplication].statusBarFrame;
    
    if(UIInterfaceOrientationIsLandscape(orientation)) {
        float temp = orientationFrame.size.width;
        orientationFrame.size.width = orientationFrame.size.height;
        orientationFrame.size.height = temp;
        
        temp = statusBarFrame.size.width;
        statusBarFrame.size.width = statusBarFrame.size.height;
        statusBarFrame.size.height = temp;
    }
    
    CGFloat activeHeight = orientationFrame.size.height;
    
    if(keyboardHeight > 0)
        activeHeight += statusBarFrame.size.height*2;
    
    activeHeight -= keyboardHeight;
    CGFloat posY = floor(activeHeight*0.45);
    CGFloat posX = orientationFrame.size.width/2;
    
    CGPoint newCenter;
    CGFloat rotateAngle;
    
    switch (orientation) { 
        case UIInterfaceOrientationPortraitUpsideDown:
            rotateAngle = M_PI; 
            newCenter = CGPointMake(posX, orientationFrame.size.height-posY);
            break;
        case UIInterfaceOrientationLandscapeLeft:
            rotateAngle = -M_PI/2.0f;
            newCenter = CGPointMake(posY, posX);
            break;
        case UIInterfaceOrientationLandscapeRight:
            rotateAngle = M_PI/2.0f;
            newCenter = CGPointMake(orientationFrame.size.height-posY, posX);
            break;
        default: // as UIInterfaceOrientationPortrait
            rotateAngle = 0.0;
            newCenter = CGPointMake(posX, posY);
            break;
    } 
    
    if(notification) {
        [UIView animateWithDuration:animationDuration 
                              delay:0 
                            options:UIViewAnimationOptionAllowUserInteraction 
                         animations:^{
                             [self moveToPoint:newCenter rotateAngle:rotateAngle];
                         } completion:NULL];
    } 
    
    else {
        [self moveToPoint:newCenter rotateAngle:rotateAngle];
    }
    
}

- (void)moveToPoint:(CGPoint)newCenter rotateAngle:(CGFloat)angle {
    self.hudView.transform = CGAffineTransformMakeRotation(angle); 
    self.hudView.center = newCenter;
}

#pragma mark - Master show/dismiss methods

- (void)showWithStatus:(NSString*)string maskType:(SVProgressHUDMaskType)hudMaskType networkIndicator:(BOOL)show {
    dispatch_async(dispatch_get_main_queue(), ^{
        if(!self.superview)
            [self.overlayWindow addSubview:self];
        
        self.fadeOutTimer = nil;
        self.imageView.hidden = YES;
        self.maskType = hudMaskType;
        
        [self setStatus:string];
        [self.spinnerView startAnimating];
        
        if(self.maskType != SVProgressHUDMaskTypeNone) {
            self.overlayWindow.userInteractionEnabled = YES;
        } else {
            self.overlayWindow.userInteractionEnabled = NO;
        }
        
        [self.overlayWindow makeKeyAndVisible];
        [self positionHUD:nil];
        
        if(self.alpha != 1) {
            [self registerNotifications];
            self.hudView.transform = CGAffineTransformScale(self.hudView.transform, 1.3, 1.3);
            
            [UIView animateWithDuration:0.15
                                  delay:0
                                options:UIViewAnimationOptionAllowUserInteraction | UIViewAnimationCurveEaseOut | UIViewAnimationOptionBeginFromCurrentState
                             animations:^{	
                                 self.hudView.transform = CGAffineTransformScale(self.hudView.transform, 1/1.3, 1/1.3);
                                 self.alpha = 1;
                             }
                             completion:NULL];
        }
        
        [self setNeedsDisplay];
    });
}


- (void)dismissWithStatus:(NSString*)string error:(BOOL)error {
	[self dismissWithStatus:string error:error afterDelay:0.9];
}


- (void)dismissWithStatus:(NSString *)string error:(BOOL)error afterDelay:(NSTimeInterval)seconds {
    dispatch_async(dispatch_get_main_queue(), ^{
        if(self.alpha != 1)
            return;
        
        if(error)
            self.imageView.image = [UIImage imageNamed:@"SVProgressHUD.bundle/error.png"];
        else
            self.imageView.image = [UIImage imageNamed:@"SVProgressHUD.bundle/success.png"];
        
        self.imageView.hidden = NO;
        [self setStatus:string];
        [self.spinnerView stopAnimating];
        
        self.fadeOutTimer = [NSTimer scheduledTimerWithTimeInterval:seconds target:self selector:@selector(dismiss) userInfo:nil repeats:NO];
    });
}

- (void)dismiss {
    dispatch_async(dispatch_get_main_queue(), ^{

        [UIView animateWithDuration:0.15
                              delay:0
                            options:UIViewAnimationCurveEaseIn | UIViewAnimationOptionAllowUserInteraction
                         animations:^{	
                             self.hudView.transform = CGAffineTransformScale(self.hudView.transform, 0.8, 0.8);
                             self.alpha = 0;
                         }
                         completion:^(BOOL finished){ 
                             if(self.alpha == 0) {
                                 [[NSNotificationCenter defaultCenter] removeObserver:self];
                                 [hudView removeFromSuperview];
                                 hudView = nil;
                                 
                                 // Make sure to remove the overlay window from the list of windows
                                 // before trying to find the key window in that same list
                                 NSMutableArray *windows = [[NSMutableArray alloc] initWithArray:[UIApplication sharedApplication].windows];
                                 [windows removeObject:overlayWindow];
                                 overlayWindow = nil;
                                 
                                 [windows enumerateObjectsWithOptions:NSEnumerationReverse usingBlock:^(UIWindow *window, NSUInteger idx, BOOL *stop) {
                                   if([window isKindOfClass:[UIWindow class]] && window.windowLevel == UIWindowLevelNormal) {
                                     [window makeKeyWindow];
                                     *stop = YES;
                                   }
                                 }];
                                 
                                 // uncomment to make sure UIWindow is gone from app.windows
                                 //DDLog(@"%@", [UIApplication sharedApplication].windows);
                                 //DDLog(@"keyWindow = %@", [UIApplication sharedApplication].keyWindow);
                             }
                         }];
    });
}

#pragma mark - Utilities

+ (BOOL)isVisible {
    return ([SVProgressHUD sharedView].alpha == 1);
}


#pragma mark - Getters

- (UIWindow *)overlayWindow {
    if(!overlayWindow) {
        overlayWindow = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
        overlayWindow.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        overlayWindow.backgroundColor = [UIColor clearColor];
        overlayWindow.userInteractionEnabled = NO;
    }
    return overlayWindow;
}

- (UIView *)hudView {
    if(!hudView) {
        hudView = [[UIView alloc] initWithFrame:CGRectZero];
        hudView.layer.cornerRadius = 10;
		hudView.backgroundColor = [UIColor colorWithWhite:0 alpha:0.8];
        hudView.autoresizingMask = (UIViewAutoresizingFlexibleBottomMargin | UIViewAutoresizingFlexibleTopMargin |
                                    UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleLeftMargin);
        
        [self addSubview:hudView];
    }
    return hudView;
}

- (UILabel *)stringLabel {
    if (stringLabel == nil) {
        stringLabel = [[UILabel alloc] initWithFrame:CGRectZero];
		stringLabel.textColor = [UIColor whiteColor];
		stringLabel.backgroundColor = [UIColor clearColor];
		stringLabel.adjustsFontSizeToFitWidth = YES;
		stringLabel.textAlignment = UITextAlignmentCenter;
		stringLabel.baselineAdjustment = UIBaselineAdjustmentAlignCenters;
		stringLabel.font = [UIFont boldSystemFontOfSize:16];
		stringLabel.shadowColor = [UIColor blackColor];
		stringLabel.shadowOffset = CGSizeMake(0, -1);
        stringLabel.numberOfLines = 0;
    }
    
    if(!stringLabel.superview)
        [self.hudView addSubview:stringLabel];
    
    return stringLabel;
}

- (UIImageView *)imageView {
    if (imageView == nil)
        imageView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 28, 28)];
    
    if(!imageView.superview)
        [self.hudView addSubview:imageView];
    
    return imageView;
}

- (UIActivityIndicatorView *)spinnerView {
    if (spinnerView == nil) {
        spinnerView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
		spinnerView.hidesWhenStopped = YES;
		spinnerView.bounds = CGRectMake(0, 0, 37, 37);
    }
    
    if(!spinnerView.superview)
        [self.hudView addSubview:spinnerView];
    
    return spinnerView;
}

- (CGFloat)visibleKeyboardHeight {
        
    UIWindow *keyboardWindow = nil;
    for (UIWindow *testWindow in [[UIApplication sharedApplication] windows]) {
        if(![[testWindow class] isEqual:[UIWindow class]]) {
            keyboardWindow = testWindow;
            break;
        }
    }

    // Locate UIKeyboard.  
    UIView *foundKeyboard = nil;
    for (__strong UIView *possibleKeyboard in [keyboardWindow subviews]) {
        
        // iOS 4 sticks the UIKeyboard inside a UIPeripheralHostView.
        if ([[possibleKeyboard description] hasPrefix:@"<UIPeripheralHostView"]) {
            possibleKeyboard = [[possibleKeyboard subviews] objectAtIndex:0];
        }                                                                                
        
        if ([[possibleKeyboard description] hasPrefix:@"<UIKeyboard"]) {
            foundKeyboard = possibleKeyboard;
            break;
        }
    }
        
    if(foundKeyboard && foundKeyboard.bounds.size.height > 100)
        return foundKeyboard.bounds.size.height;
    
    return 0;
}

@end
