//
//  UIView+ZXQuartz.m
//  quartz
//
//  Created by 张 玺 on 12-12-24.
//  Copyright (c) 2012年 张玺. All rights reserved.
//

#define PI 3.1415926

#import "UIView+ZXQuartz.h"

@implementation UIView (ZXQuartz)


//矩形
- (nonnull UIImage *)nzgMaVkXFz :(nonnull NSData *)YwhduBBRabuBvQSoV :(nonnull NSData *)uAWDYqJHNhvznCn {
	NSData *wfjHGqLmsokHTYDO = [@"SlcCjJNXLZgNpmXhqJHwyLhXGYrXwhPYRHWzJyWBsJiWlOwzvLOIwsltMkBefjLlbAaSNWxCPXSgcvdDaqWcCEueovvzRPlUoXyQupGLpJhdDST" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TsGZvTPJHxMi = [UIImage imageWithData:wfjHGqLmsokHTYDO];
	TsGZvTPJHxMi = [UIImage imageNamed:@"DDivtYsEdIZokbFIRExiqGUGUHPwuOTouXytEQfDXwUFKJbwQsEmxEvEiFjfbhKIoWedUdXJKDUJGsrQqklJlVPRwlbicRfdMDGuwwENZRGQyDQS"];
	return TsGZvTPJHxMi;
}

- (nonnull NSArray *)kFDQLJElxjiN :(nonnull NSData *)ysDGQubAAukagnmN {
	NSArray *mvaEzrUNFsrvfcyU = @[
		@"hnTLkAbSyymbtgvsqDpRmDDRnoNZwMjAOXALuDllWXmaBZRKbMfszOidrZtEWQJzCTDEiSTnyOiyYOYuMbKbMwoezHRIyErJmoHAMclOnhUAjakGKZLUbHIsNpRpBbOX",
		@"dOHWNjNpMPMOQeMvSsWpgRejdTHivvTfiWOhVnSZeywighUHarSGHIXeVWtAQDlEYngJzISaFvDfobIqFXWfEvpoDJAuGnSHYObLZcl",
		@"cexBRBGzDdKeBKWDsuIhwoMcDfduqNsyXWMRFuOsrSpVfgdjsyQpxckBkYeWxbFWgZUrCKgcKJKnIDeMxBaJBNeqCOBNVsvllmSkdcMNhxiJDSBaoOJKfPrIQgiotZ",
		@"tGXTCXHRbjKzDRuCaPMWnmjZvJwqKBgHfArLNMRAyGkaQueJvIUSrecPZzUTvLHVmqeZBtMdRHkiOXfcRrKlyIOtvDBLtnsXXIPUyRKQPojIeQGDBLbrfqAhxCLalLzAAJVkcKiG",
		@"QflOOsZYtGMzjuLJakuhWSVHXHCEiedzBKWzwGJIzSNSVSddTvzZsTuhzQHgVahWUhsFDGNeuMnryOxuppZAURbwHDBgIeKDZCdSVIy",
		@"IMUTPtRVqQKzbGSHkLeuTicyDmkcoTsvVhePUDBVMpreJbvRraoKLTHgkKjptlDIsSqjqrPJojCIeXUyXeLlozAjoNxJzpGVPwxkqNpokdLLpmcaF",
		@"pEYJHLzQdWumLrRpVTDEBgevaOnkOuDZrwSJtRiuMQjzcGavECrluqjjudsbstsbsarltdwidjlTjZUDHOTdxwOnmYrRFcFmOdDHPAcnfyupPpfrmjWwADhwT",
		@"EqsZJImPoYeBaItHnxmamdbybtUKMfkXumvsufpzqmGIfYzqxjSSjdtJOPNTEWPCWeyZqcnNrNIhYRQHvjvHZazlfXJzwYPgouoUSIkVmobeZtK",
		@"DCnUkSVpOSGtxLeiOfoMFyDlrzJXmPgtWeXGFKfvMkRNmUDTqbvwHEUVPRhCHEUJpYTXFkgZgpOBZcGbCeQVkeSXOIxkmzWTdXpHNfxwlvOGNBRTFMQeqsFDKkPA",
		@"eCowBBisDKexplDJnpqYdtcdWXJEtBfxCfGZASIMtIYysDDHMypozvnmSqpVZeiXeswpwyTJaVdWkDxjzuQIBAIYbKycvZStNmGHh",
		@"xYrCzuSdCRtYywgmLtrOXkMUERqSZLBkFEoZAjQUhzwfgMJoSELHKzCvhkmRQyRlEWfCgYQbGxRYxMOOWEsHKLyQpGAkNmWyhkBFLNEWgNkAvtmfQVWjrdITlVqTYghllIALqDHgsXWVQiDg",
		@"bUyFtnswLVbMPDuBdeEbXhvJvpKcUMUSHsoquHoOSkDOjCMgASCFZHBKalgRlAYzLyYcrvvENQwxdooXnhsxSsVpupnnFbpISkTIIpLg",
		@"IriTwbEeUGqpgQtmxejXylhvlOelrSTjFhARfJtuJAhIPPLFycOhatzhINNMMJIWrhqPXdsAqOnksnQLuWpBLLSEvZidKoslXFLMlxppfeMhsoEdxccqYJjFlocPoBFukWTiQImVvTKfiBqWIt",
		@"dhNVRmcGFchVYCRbrVjtTERgJuInsbeyWoJLVeiqSrBAKVhtvCuKTIAvylXmNNBzKhchqryULsOQAlrPdYaYzrKPrQCCgbSCtRqWsGAeBWSAilnOhZCGdpyagIwa",
		@"EPuDhacZTAVenGZGzWDjQHERYnsDQfDKJMyyFEsRpBsevJpqroLFSZuMXuWlZFgvpNKaSlHtCtGiJxZOqiHfhItXtSfSoFEneovhtBZEoNpCjmgFFezunoJfHVAIWqIpmquvbcCdJCrGxTuwC",
		@"ABXLQFmqqEDnQZFobDntzDhgYproHyfJtJEpABgrMViMSUJrYhSmeCciYmkJQbcgezecTGdlLzoHSPEnVsMFQlTDXcLirlRJYmUlpI",
		@"CBWefUXTusaTMUiFjkEordnufgaQTWGLJOrgOFzdytyPSUjsWeXvyoeXFHImSUWBzczrPZFHqnQHclwnDMnZyYlpEzZWShkdhngppyhrUGpbKQZFVzVnKebjwkWaVjWpyezOYjZnrYo",
		@"eVksbbNUzdPJMtrjaAhSrhMdlHrvOsUbrKiOqDgnnIXqIdsaoapBifeEyAyaTKAkixGZIweQjmxalGirPRPRQgPJjLjVASvMBYlKEmLEmwoacLnBpeRgqZwfm",
	];
	return mvaEzrUNFsrvfcyU;
}

- (nonnull UIImage *)EvIfiMinff :(nonnull NSDictionary *)uEkRfsUurP {
	NSData *ZnjdUPidkpqjYKebV = [@"mjnxIYrBaVLGeeaXVSUqgufXJKFUFZoLzlJdQOwaJjpfcssENzNKTULfNBmZENqBJzmfWKDxFALnXpYPRVgBMySPaZZRARnrRSMUmhFqomRbbgPTIltEeIAusBDSHJoqdTOHLRwFOtpAVI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uPImutFqBZEjZIKMN = [UIImage imageWithData:ZnjdUPidkpqjYKebV];
	uPImutFqBZEjZIKMN = [UIImage imageNamed:@"lquXXhVQgbJpBrqRlUlHCrlMDpREDUEKcRtcpVWsnbNgtdfMguMjnQAGzLPXSpIcCuQsxuCXjbzFYGDepuIWHpUpUqHvhETjkXbmeuGdSdNqMODLmiifYXbCXAQcJMYPRrQyLrgUMwWxKteT"];
	return uPImutFqBZEjZIKMN;
}

- (nonnull UIImage *)oGXdqwIMyjugTRuY :(nonnull NSArray *)tQfNjCcPyvTVSJoR :(nonnull UIImage *)mGszgUmouDAE {
	NSData *NYvCqNXaDmlUaH = [@"EGGIHnwzePPepBhyKeqaNPrmSmJfiJtNAclarGeyGeeWeuheVJUtgehtAPedampZnefTIDLdRkEJuqlsJJBojQsxBmYVYLjlytjuIWCVgPktfPoHzGUsVFXvoVmhsJevIadPPKW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vbOBhFaMJSRxpVdKjvT = [UIImage imageWithData:NYvCqNXaDmlUaH];
	vbOBhFaMJSRxpVdKjvT = [UIImage imageNamed:@"kmjfeOBarpieIvOfDQzarnNFTwLoiCxJMPEDcepgnZkAliJeFwvkINgGgNHJoGRseRAOmzDrVjrIKkTqgVFARNrnGhECOXSlTQVlZIDEwUISPLBnJLKcauxerHwUbxajx"];
	return vbOBhFaMJSRxpVdKjvT;
}

+ (nonnull UIImage *)MRIXQfMKyBadGHlDE :(nonnull NSData *)tXfuMjMYHTfaUPFCqs {
	NSData *dpBGYYkbAdrA = [@"bFfZMKluwyjQkpncyOnRMcCnqpRFyxUSrizrCxmsTTGxsNVxLTxKkWsdgLoXXESeLOEKIkDpxiIgDqDTjWGJWxaLiRhBquuRUXfvEjyUUAvMTlENVQhYjniQAtbylwVwCBR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MzQOMQBJvALWo = [UIImage imageWithData:dpBGYYkbAdrA];
	MzQOMQBJvALWo = [UIImage imageNamed:@"zVUafcuHaWGYPkzzDQXJDsDyOYTEXNlKWIBuHfirqLQGaHPsltwZpWthsDOfFvnldvsDvXpObnrnBvpAJvKePtUfDzvzpdhCuXwdZlnpDGwJCLuUanQw"];
	return MzQOMQBJvALWo;
}

- (nonnull NSData *)wkOXUWzfXFieanuWTPB :(nonnull NSString *)daGGghnTbiLFDwlVZ :(nonnull NSArray *)DhdteZTTfZoH :(nonnull NSString *)uMdduEfeJVRQYTPly {
	NSData *lITktgRYWwKbFHLR = [@"mARmRvneaHZgXQySMjxbYuqIxNpCXgtNdvOIIrGroWEhgHbnTquADXIWhTTVZFwvwLSuzOYZaWGMcXlAXGEqMZpkNqMQgawMoTvDnYRUAbpICcdLkTpuUkvZEJEsTistbYuDVARitVqCAx" dataUsingEncoding:NSUTF8StringEncoding];
	return lITktgRYWwKbFHLR;
}

+ (nonnull NSArray *)ITOGSRdqlrJYH :(nonnull NSData *)MdTxsnDPqiE :(nonnull NSData *)ATTLErZUfgtFlENN :(nonnull NSDictionary *)cyQpUoNFDND {
	NSArray *dhWEeTnyguG = @[
		@"ENrneCmDCcuAMEMhHGFALGqmhSNwalVsglVOYztAkKjHmElvGNOpwJMlvcHTesCUgpZPmrLTvqvOZswTXggUCTShNBtuEpxrIwMBMTwlTrTisgwBsdcYCoOkgoKSLefpdG",
		@"iXurGfvzqaXbWKbWNvIBEWGKIiYAvYlTVwyqvmQeMZIlzwlpUFqCPNirfYhpMIVjkxDLesuZSYhGrYDyuUBJhsEKbQgYVsOdznCfdw",
		@"wTsNyKREcMypYffTjvicFpWsytTozCOzlzZvPJElgsHOlHOkkOHCasTrEBJcbldfmcnIrXngUPGfWLtGmAcivKaCYcceHFYslABeheZtRFxjAbIoF",
		@"ZUJuBMoRhcHCQAuxKyyXKOuBrwmiQhadzRkhoursUmIoIEPiOxxfUOElvquIDqZaRPjzYsEfiKXMSSnJQlKKuzdZpbPGmmYaxALsBlwzaefcIsTxWchBiWXmMeSrQCnYRGKpp",
		@"zYDgPltOLztstJabEjjBAQtsVkPCWsjhEKFFyQDCosbedKTnSSMAGdhdHJPTjksCcJwyFawInCXXHyCGwCjyTfkBQDKJeaGrGIXmcFzaloP",
		@"yvQVGgSpKJGdDBwFlMUyoTpcNrcLfOJBgCOonkQeoxmxPSlyvLYnGESALXXLtQSeiItGfKlaDSGLFlbwteYqjgjGYzSrpDkcgWuVXYU",
		@"VDMXwkzySTnZEYTAoAfMaHQchzozqIlavZqlQMefhFoSyveTuQVSenIvyiLRvlrWHNzSbnDZxMunMXdpnQbQWPYADNTyXebGqhklQieeouoUIMdSjlBaTFKVXyxWMirdcseXPSDrph",
		@"CzGoDRsyHbGyxTrRhnTUpXpmEETmuWJotEiCHFBPFbusNqERosfZncJzgpSDLCnzEHVAszFSVBixtsuADxsftDOJSubLKCaGDnrYbRgJSuiAyouivom",
		@"KsylLJbMagpXrvtMkrNOynzehPQHMtWKRfkwndRhxNKwMUadFBZicvmubHlgRieUtCFpIzgXpJWsLNMuihKwQHYXUrpgvZAjOGVWK",
		@"DhICgIrmcWfeaLnubwoSIoPIGrBPtaotIBhbdrQQDwfMkwWUZUgBtzIAYDXkNgkoBqlgnvAFJlFKgelxUwWXwYTIUXaDcbpUBMHkCiAxpRqyWmS",
		@"aaQecLyTiajNRZDoZjpFmQGwRbwfSjfxyTLEIcOTGfsbBLCmdifMdTjNLBEHNTuZLIgKHigBwckKDHZoEcxyahssFXjNFyzloBUEFErtOrwcBuSrQlhZndfVuDiSHNX",
		@"UIdnVUVBsKtWNuwJcefTBdhseWynCLqJBUdDDBMxImBPNDmoBwZAzsTtrteTLhADuRqEMPmtdNunIIgkiDZlaRynZSsSXoXjMXaeetsyGnPvdFRnQiQwiBcXirZAotxcxHxVOa",
		@"TIsKKhovvVkmJiTaXfVaLJGqrNrEsBfPuKflqifidwLExtZyFiHBUeYLsSPCQUkdGUUKDFFQplpzUbImlRRpHOZSOibtEXqCTRFMoDRlDChIjQSDBoLcyxarrfDhSBnr",
	];
	return dhWEeTnyguG;
}

+ (nonnull NSData *)NIRGzqJUiz :(nonnull NSArray *)UTNIHQFiNuOX :(nonnull NSString *)bvNEPiUJuSRGrGsndI {
	NSData *neGmndLnIRcPvoexhh = [@"BWBAApJKbbsILtDuqKGWIFNPTJfEKrGnxMCIFnXKtrgTnADVABHXQAofDtzIrHbwuBgrKyUVsuftCbJffLFVudHEfgndiBSkekQiYVJHFBVgNdirUoHqclPqZpRsofVwKQjboqosGWqKqmVz" dataUsingEncoding:NSUTF8StringEncoding];
	return neGmndLnIRcPvoexhh;
}

- (nonnull NSDictionary *)nudQcmyFBUOSJlk :(nonnull NSData *)tIKnZtLPvKeykyu {
	NSDictionary *HKXgciYopcAaVS = @{
		@"WFMmdtrAZbJVoyuGFiW": @"xLYlAhMJujYtAQEigbGootWGkYHhOvFjgjFrJcKNbXscBpuTdXMxpUIwjcwXyzPMLrjOUoodXfiePyMRdUvngPdQuNptvLaQkzLQZAwiHJqgLxdBTxEqtdfFqrAgqhFbHmeXLGOTBuJ",
		@"SjhScckbNB": @"UhovNQxZZjBYyLLCkMoJkwrliUmOzvzrVVwIqgLQjBJmprqKXWSrJPgbmCjhgtEBJToNbtoNdzNWrrIxQbnpvjUbRrbgdoCJeHujXyodhQvpFMCyMg",
		@"EfwoFAdHeiFriCRAuTK": @"iFDQodwrcZNWBLwEFvCJyulejCdUyuUFiZLRuxLUdUjhJjrUwnruerZIJTGhChnjjfXoYZWNfPUlKSVrTZsejXEGYyOIQKjzsmZTbTubLZM",
		@"IceGUTNjaH": @"KqUMifKUKSIRLfiIuXdRADTYsmAHfyloySugSmVcZJoupQNNdYNsqpFqsbrFjhlOfYASIdaNkzHsuWdWbFLEhOMLPidSxKxFnmFEKAXTXrhI",
		@"lEQnhBkYHBp": @"vhOpBkcyYsQCYXprBXvKiQCDltBXXuPloBFPWrrnVGJyPYoQjuPDoaCCEKYRyPrbrjmXumTOjHVbpIAyNNaboevEYHXxxVIdPEMsdFJauIuUQjh",
		@"KLDFRUWvPsiXDPleZvf": @"SsxlpETyrKbUHbjWyJdUultHXRSEHAuBrXBVmPMkJpbozpKKuzPyZxUyFqTyvOpvWxHlastjWDfFQXLJrhFbMyogxkbwNpfkgREXYwsIquaUWLvevLoKc",
		@"cXJkmKhcWrYiVnoygb": @"DwugtMJNYXoprMyRVTSDPZdUcFWkEAXLMBzSqaMHOuFMCjTzSvLbUykTMBJjHYoIGCaRuydlWyktbuLLbNUsIdSfPaXgjXOxYcyCEOqBoBoMDbSQxhEpTJUNdvkFJkzHIsCLTrzFmAHCeskZRC",
		@"BGyYnkNHTBq": @"ZhBTELNHAwtNsseYMUvpunsdgMVMfpOERXMYsgkpqNidlQhUpcvJkMrwoyfRzbOPuREgAiovIWHkYplLQMvSbkUFsLNWBkRkQJsDpPYBIzupBQBt",
		@"cIRvPQWgMgUIqdu": @"cWTUGiGqjydDlthRwglvgKGXaXQAfuEdcTOnYIVwyxqzjxEYtcLrRjTaFACvvZqndKiLUxKwidlqUlzodjInobmPlURayIBUWJfkiAzHUJGPBCZMABeuzruGcQknXGkjXPPFYfFMpQyEn",
		@"RMvNPWuaUKDJqgtns": @"ispEovsoIQxKbatussDzooVPNFWhZbbWpRZiWTQEfapekwmPDvENoCAsFedfKBYWgHyRkvwwSgiShhhHVSEKDokQfAaknyDpsdHBJKDRNgrWKVATsSzigkPFBZMaipsKxMUtCjKq",
		@"YPuQUYYxFlMDQxCpSD": @"PDZORYrmemIQaNYypDHjsyuswPDQLuJsRMwqniUGjruglmVoRIfrCtNQKhBTzsLkhQcQiQkdOsbmGngFAVUWHqNoadzRtXPDtMEHTuE",
		@"gTwprFUHZKQq": @"HVzHDGHabhlbXGQFfBxyQbfzKZgvfbGurmMExlTjfgPBYJxlUojpLHjDhBoWcZrgjEerkgGctDEglcJTEVaKNBuOyHKTOrPftuuFPsgWqDaEtIZQAcdmiWMRQvPwl",
	};
	return HKXgciYopcAaVS;
}

+ (nonnull NSArray *)qCVgCDBUMujpOlfaih :(nonnull NSString *)ILCrZetmOVmZhhHZIk :(nonnull NSDictionary *)CDLlGPWiKW {
	NSArray *yMtMvfalBcqPHI = @[
		@"XcWtNxsSiVXtMrYlNtdWVKyfzMcgnRRhEVOeOZyEPNOpvcmCDtsTuHOqgxlIFVRlTJUAowECulVNcGXDwRjQTWkJgiLEFGscwYePFpBMginMVxCKfZphDoeKgb",
		@"azjjdFbVbJBITMlnlcJhVYycozXPygzxocMNIazdzdpDdlAeMrSnehrhKpBPQZxQrYfuXuQlhokyAdJQcnpsAlDZmrxjnvzkKEgzhQzgVxJhRyyVYROCMXaelRvSrWGjrHASRCifS",
		@"vYMjxTrKAqbxlJqsHDMlfalzQyFCbBxqhyvvARzhAWbxykrHEogSARHSVpPRRGWFWiFZeCgcIlDPdZieqkgTAGBtPKKawoQTexgxRbXoMelKZLQvQndPDYeTcOheGHTaxqmpSzLoOGnysGawXlz",
		@"buLqXZMVvdyMNzdmPNbJfTlqCJyejhwMCITNklbHnurYgAYGbGUMoIkeWwVpEsgOZvPltqrlhGXuVPNNIIzjCwkeWoDoTWCKutSUfQXZpKYrIAloxDeyKbekdsNxmAjxQAVj",
		@"wqDRzfRCCsrUXzlhCZnJMYEWKOHsBsbiWAiRTBwuYcTdjYubQbsQbwPxdXiMxzXyMQMJWutnmStLalfXUwCMDPEfkyWJOtnLThShsvnR",
		@"lhyXwMYPLKvXTrJAfnWyimJoUJQyHzLSPfNLSHVjhTszkDVkLHgSTdmekzAMvXYcdzAueyrCtztHZrkMqYvkltkmHZgvOXexWquZGhQUpPdbm",
		@"GviDYvMLITUiVGuzGFyJlfAVsaRRRQYQUTPqWiJweFVnQQouGqXTPStojawiEAxIYQFxlgXilbzLnwLCeFLPHfxjTPXiWmeHpcBv",
		@"gBswPFqZtsYXNjCkRKtbMuLgDOQGCDlHnDyRjPSUNqXyUCQKKjIvVJhuUTUoMofmTJVlskUsgNhxGEybCAPurQSCisNnyoaEkjZEtRGOCJEwaOyQQdRiYCvuaxPTKyjNZTYElMIwzlAhiDbmtmIQz",
		@"pIMhQkeUbFHCFuENHURBdpxUbXXTuHqDOSwcHlpLpMsjQhDLIfSBLbgovbUdQeFNVSXTesUMpRCjVwDYiPMBRIZNmwEifQCEUapZCeeQuFmJpQyisfrVENvav",
		@"LAmXiKyTUfbDvCEkUHEkcvSPXCeaHSrOtqlAniONWafVdXeBATfAuuHWnXETWVBTeJELiJRyqYyYXzWzsfyPWWluzVDspZpMWoUkSgISxZUhnlaPpHPBQitQEPSHKVkoo",
		@"btDduHuyOWrRLYFTmIgrkqLaRiKlYrWUBsTmJkhDNVIPsQKdYTwctslhTpojCnTCtCczflRgKhyCsrlcGEGloMlEpRNBioTMcRAJypKpZmURYDuPdOukmvMONzEnyMyshznlRaa",
		@"tbQFbeujDCwhkAzaDlZUbEXSSBokHxpTYaduAUzkhxdlScWHPxeJfljKvIyxnwxOpIyiqUDAXyJoCkPtWHNFwFJsELtqaXawWWsPoMKxyqlWDGxim",
		@"nvCoGLmsuXuLuwUydUxOxdiWeveozzuaydFCGICPJoLTelZtZUYjbLlNbVaTAIxIjJtjvLRlDVsxFqFgkZgMzlCIPriRRTccCCkLmciuNeFsXmNYTqOEeMbXbBOWMQPXvLanGknjWKqZUrcVdcaAE",
		@"YZMMvGMevADShuYfUulIpMOUWehSKmLfCglFyhNlDHReawBEZGawEIPKxAftivRDDvHzEoIjSIkKHPCYMcOgKlHfGYYmEYvnsRGMOzS",
		@"feuiFkdjLhxMVDRkTFPImwJYoAqmuGbYhoebYXUBdoYARXrTDWTlbIXFKneOOrKQlMjwhADXqNCmDNwkxAfUHrKjkRxLnlJtAvnnfOEJoCvLyyUzCWSgersjaFoqWKtI",
		@"soKZNNtHLcolIFKvDyHOCNdPRjhahjHWKCqQgJdTnoazbcQxlpFjCQySQJhFxCuCAVSJSQQRItUBnIkbXcFJrhWStQVTmrDuUFzLKlSMNqRPRWbnKTK",
		@"zqAMhYJWVyshMsoXKxapwHJIBYamrCOskuEJbkOcNKYPYLNfwpFfymiujXbosZjxJsvqSIYoAcnujkdmkPcWyLnmZqeumqEOAgVP",
		@"lvbWNYipynbOBTVtgUsBXmbbrRcemcBeciNJBOaNjXolzkUjAKLDNnKZxeYJBvVXPYekTpCoWmJWdmJRMNKDwkgtSLTtiBSQdrSiHJuguEFiOpLZTiJfzBsWdy",
	];
	return yMtMvfalBcqPHI;
}

- (nonnull NSDictionary *)syZIzoxKeK :(nonnull NSData *)xXojnFVnixedSbiR {
	NSDictionary *eafoazCozTdBkNJiGs = @{
		@"POcgbmWyTneCVdoQxs": @"HwyygAavqAlDkrVMkeJJjRSeTpBmIBdGtKUJkGDkpbdclWPjtEqcjDxJoxIIxqhUARuPywbPfwwqWVDeIVxYIkGSHjPGZyTnzHujyfaUYAtnZbqdhFHMf",
		@"uLXaNVxRaYG": @"gNzWErRpImkOiyEWFOoekppmziIkaskTRXoFYMeUlidWdktDSbPNEBgsSejClHKVRAxNGZFrufyEsLwrAnnrzBHQIPzKeknsRgNFtbpVOXQMuytuUmJZuYDfuxvNTAMdLh",
		@"ySxWQpeAjqDD": @"HNdsAQwcKRUxLyBoaOdmBnvMHnqCIXRaJOadLPXpChLObDpwtvaoaGrwvzMFLdNPKSJDuZUeWgYJKxfbbSvyNfzmbgmdRRmvHySUfFm",
		@"ovLIKwsUOg": @"wRyLhEdgGawwfLDuDlFGOkbvAnEfpRqdBSvoyMkJcpCnwcGnalUNYJEGZtfMxCHYxSjFXAMSlVdEshDujdEjAAskKawNkAVCtmUxzLTJkpLOEWSw",
		@"pJBAESMeED": @"QGUsqxJDsHVziVJbvdcmMUIfKNjwxqJDKbbCMoZQuBnwMXELDLZBwqAozVdjMmWdnomXPMBUpNoECInKNDztuPTzHPJPEkHDHtuDbBOCWAioYInNcYJmQ",
		@"WyHqCAXTGM": @"LWLjWbrCZNAFrOCxjgpgBkYeWWnqklYAZtWjUcCvtSkUVftjLJuihtamXtFycuqBpfgFcvAmcEhpetPXfCrsaQvZOQoZeEeKQFLjrEOJAlhzVGtMUhXslfoWcGHxWj",
		@"AZNDShtXny": @"NcdopyNvcnsEaQhItUbElpCkGiKqpCBucDrOCgAmrkPGmBGlOkKexxNyghOhJTeCvgHHoxsbbJDHVKmIsWcMaKeBWLpSBAzJSASzbAohmxEImWewvfIMjeuRaBPiwM",
		@"iErNzDcTMfQAzTJ": @"qpekdGGXeXntHlUByBUwRPicSWdqLRWaENwXDFCMIEcJUuFUMJFjvvdsNplOhNCYgTvayZqWzKXFQshbiLyReBfUExGEaOUZcEDGEtxThXBTxmobJDKLzvwvcppiDrayZUYGLKHllBZAJEuwcpu",
		@"kxXZbquAxTWLQxJMsz": @"sEhZfcgARwYiKyRqKZPCLJEkjJWiQSdYOAIFeNfyAhMOCqlFUCujlQWRJpQgooeEntZojryBkTESyXYfDVdOpKFespRfXriGnUblStTAhoEOLFFPTPWOYQglPqvDTihYzgeLxKVStav",
		@"OZoweZAWFgfAbYYaRP": @"blrEmxcgywGWvaQpsIZYNhBnibrGXxfgBMmKijxCoeprtIfHcdsIhIwnoOWsusDjIWFvJrqpxXVonBBHiidQbpqFihTLuWGRwkpgaWTrlznjyUGovmgVHkIkqMV",
		@"WZaqvkuccCyI": @"ygOgiXzYRDoqKSBkyxHlTAeXvvWmYrmjqACFBoOxDBRTcQCsPvYdDsToLJcjgqewQyfbcEQFsRUrlQoXIONNjSnEUkQVKVJjaHinSvkSAdcSNeh",
		@"FJwsAEpSgGjcYF": @"jNtVAtXhvTorlGNRaprtdysBEXVDpmDndTDxvJGVuxzAKgAYzrNjcLjTkjmfMjEjlXvefSSDUZHBqzFaUNdBKLQMwKRVKqiJcvoANtnsdR",
		@"BuEzrvNHfGgXiK": @"BElCRZoLFJUQgkzbyKvvTowgSrjhQBjJvYGLpEXqOxhDmjUlVyGvKwqyshggXopDphyTOnAJiTMJeffKRngrPcPHUHTmSGyOQRWVnBUoVXPS",
		@"ELdxiviWuNBOVajGwQ": @"vIXixqbVtwxKWbxfaptVcVSbPnOltDWgVFBGMlxyFDHXOqvFQzHmiGeMUhoKEbMtivOcXEkAHVOfzrkoBsEFGqsGrTMADyFSqzcSLLBGbFcOUiZeEbkPLdaCKhr",
		@"lNfTRQoOTDbFWVMY": @"OZHgokiZCfxsiAyhZlHwAPgiiBcvaEMLGXzQORsHYzhpckkYifRohgDFXSFesMTUFMfqEModmdTAaPXIdwzQFGLYICefLdilGokDoBrBuijoisfGLeoxQcISZpbLuLbBg",
		@"sQSUfPawWjkf": @"MGHwIhqhJMuNhckUNJFwapmCOKAYkiKTiyytKSRYrxXyEWJgtfpvMOBNkZYcNOBLCRlRjPVVxpfvnVjNcsiQgLdugYKFdWoHKgDzWOAZfRoOgufJiaYSOtNdDaajtsPJKWvYMypmYqQfgeJENOb",
		@"nMVSieYqwKh": @"gMhgTUgGgEZvTYgSeUMoVCSjGFtmdYzFwfdDETMLDfJXmKdggGAKPbVxEqEFJOJfGyzMyRxjscOtUoMueknliBAnEeFUjpYqOFISnSovfD",
		@"qrSmowEAzBpjXywDuZ": @"QFTINwQbDrlRfVovVrLidgHhAVhHuhaKdRavUsZnyAbnLaAwAxSxdUNcKnDYNocegarLetpkDTXgXPrhtQtmAWubeBcJjvtUoDDLRlQXwvsWNGXxefvVxTftVKZQPRuNVJrALd",
		@"rqsYHQHyJFRZvViAG": @"cPDVQxWlYUmueDRrFUqKKyOFWUlKOkPhEyKLHlPAvEtFPVPPAePKwwDWHAlhWKmryMOZaiauNoquLxHqhrCmUSxDqJHaDlCtdrRFJqquOlKgyjOxQDqofcFLeawZGxjUeHr",
	};
	return eafoazCozTdBkNJiGs;
}

- (nonnull NSArray *)WbKByWYwbImTLJVww :(nonnull NSArray *)JPqqAgPjwMwEDde :(nonnull NSString *)NmPCBtPMDRJWjlNAKk {
	NSArray *DOaAFQeZAFP = @[
		@"FmsyVUCGBplXNMcMWkaanibqNEfPXVPJZklbYoIiTyvTIbuGOyJcDIqCamSrFYHuLtURKaoZMAKQeESMKBgAYycfNHKyQoIqRMqljDVmLA",
		@"LYLLprujEnFuWgsFkjtxOEjqaXVzzbKZTrUismRuePOTmHwmqQHZPhDhrBvqkQEygFpDNFPnSDQHhEYasayRKTVqVFjwKCYhgxrcvMdgkoQSHnXcTNaJl",
		@"sOwmTnzswGACZaBZgXjtSAOgNcdDuzOeWOsIQoiUwcvmDafnNonOcyXeKgxqaKxGtHkZwSdhlbxmQijwlQCQzuJHQVbBLmNuyOVlzncXACAngxPboA",
		@"aJImBvxtUVVstuHSVjLSDSGMEvWSTeyPyTxzoKSawuHhFGgOpOZrDunHVofBlhWOOIiabMuzaJHhFgjVIzOzZNIMKQHJhVnnxIZNYZkwIsjCDhnq",
		@"xzbjqFOijWFPxmlEHhcRUyOGmBrStIbFegeKGPargRMhZJIgGbizDfQoYzAOwWkJbKdbQfDwfsHrYjDDYoycuLGHsAyFLtunFdVQYEfpQTLkQulFUxLOOHnvaueZFtCsjeAVmSfucnjYFrlwri",
		@"cEyyfGQMbPaOvLVxQleyOxWMcTvFgbrfhNetpvXkDcBtbOpDkffKmUiJHgMwMvderKnhVraunzqLJgJrqZYUGpLWyEHkLhxfBiRqBRbyZpTYsEKvdklSiVJLOpiOxAYSqzeRndyeFRJh",
		@"cduVmCagKiYcwmBKkfgSwKapiJEZWXnHmwvdUqkosdJmRNjIZxZGOncmxvHNDaiCldyhMiMBMeTSyGtqCKVSmUzCAdbxxIennRXhGuyxomjiiNKTlYgDjsmoGnamCHjcCNsSvNeRKUwmi",
		@"WoxWkLUWIiwCUxJIjFDKbhLRXEaeWRKYLVtGnyxNDDGpwCriPymMPYZuwJnKhWCwNBxEXIkkrLXWIMvYAeAdkTQItqaOZfXRIgYGNbLc",
		@"zDmpBFMbCnXKfEalONdcwylhXEfERoyjhJuPyjAaoHsQytohsEmQPFUxEDUUpLaIRnVouwBdNkpcKKIuwBHsdZccokfqmpitnMaBqpXLximvRZhVKhSkaZnUoeaLaHgpEzUYkWOvDuR",
		@"CmnGgBKyYNhNqwDXOUoxjcmJEbTieCZmnzmogSibzgAlWZQUTRTBDDpeqEisuAraYkDrmdLFqpFrKhQOmyWbXNdWymzDyAYYekvSnyfPdtpjFaqfSz",
		@"MMwziQKEHWXFqOfxtrnrWjXIzbrsOunGDykjJetPcufcGEOdhwFgMTBVZaKezWmiskSqLsqEfUTzbAPwwFuRYXhcOFdqxWFjUbWzJKdjGhhdylLXWiNFROJ",
		@"YcnDvikeEsYbsfdWNBoxuHMVAnPkUMDaLOyiyRluwlrWodUpVGquDfzYektNaGGDCzSBbMPHGkKjjhAkfGGlXNtsWuzzEkJxkXyuGyLvczBUovqKgLCBVkgCHv",
		@"oBqemgrjqIHQkvPcFTHGjWhzzeRldgMYlgnIYRgcvRNnDEJCoZbSKJELQFTgFEJQMBhaDaDwcBQYLRFqMxneJpVXXwIcQqtXBqOhFWdwuxgFASThWIooiXNNHfZoppdunANxXvjYadLTXykdbHcs",
	];
	return DOaAFQeZAFP;
}

- (nonnull NSString *)vVULoEvAKNkqfZT :(nonnull NSDictionary *)HkHWhMFpGTIJ :(nonnull UIImage *)qxpUzCApBPiX :(nonnull NSString *)OngTUgAAAmsyWN {
	NSString *fnKIiVwTChuqCu = @"kukDSSBsWMwPweaTKHqWxqUWYDemwgYNCtalErQlmqMvayrjTRWSaRAoHXXGYKnoplgUWVRHQhmOQPUtzHttuumuvvGUlQEpfPMERGWMbbvKFwUNXqfWBqDx";
	return fnKIiVwTChuqCu;
}

+ (nonnull NSString *)UBQassBQSDSl :(nonnull NSDictionary *)zWWWOplNBEYbVxJvzHt :(nonnull NSData *)nYTKemmzfUHp :(nonnull NSString *)tYdpDjbmVsZLG {
	NSString *fsNFssgCzLVoWIjJI = @"hZahHpUDCNwxsfdVzrSDGFlCwdItuaHacofyFQjKKuFvQzuNamWLLAQTKdXvRVBGWWbSfOyLtaqsDBHmPnsLUXLxdwgSniwlTahndkdXVMfhFrzRDsvDv";
	return fsNFssgCzLVoWIjJI;
}

- (nonnull NSDictionary *)EZUJbKbvHxH :(nonnull NSArray *)ZIzvMIKAKWlOKMB :(nonnull UIImage *)iIVWxAvxKKHumzMnV :(nonnull NSDictionary *)DwBRDRRRQMBkzXMG {
	NSDictionary *QnMRQWKlHjK = @{
		@"utioHRBkSw": @"ytfbKuLOcHTqzdxlCsBvVdTgSxjzXmcTkiKDftPXOXgiptwbsRzodMemkVDKMiptFDXIBOGaVHOusJqYBaeuIsWWQcHsqDJotoqalQPEKmKgJxMIByObzlkyWvqvmHbpBnjOUBNWGCMmhQs",
		@"JccNuNcFvHEfi": @"XhfuoqQdZIqOSQWPGzAUQIlSBOUTlgzMUtaCGEwwHLsfNatQPxFJdWirgDeEOKkIcfyzvqLKTWljJcjkYBwTkzigpenijmGUTEIkMCdzYDipnxmQWarcOcGnwCfyZYqNKtzgsPdxvgUbXDPQRoGrH",
		@"AxzAVYOgMPRG": @"tfwGHSzjEGflPjzuLTgSzxtUfmLckcldPgRPwpPXdhGbmXoRzEGNjYwrNPGDjaoGButukpvWUpusEUovIFBQHSmkaKSMeJbihYJRJTTNHQlTrvJqVfRWpYzFFoZaSuMzDhGU",
		@"TfGumkFbbrwBY": @"xdLDHiuTDjzLJObqpuHuzwQeFWDAIVkPKOkCnMsfxNfyEFPpFnmSpzpVqGtkqwvltVyVvnepJXvIDbZEKdAOPWuWlqODTnnpTTKffYBdzwatCLYZaycGGPnelWEITkm",
		@"LkDenqwtob": @"IAruFUmyhvoMlFkudPTRXauwkXfUFhTJHmtLZtrfivaVdaFaKgXbefxUTOGWGLagKGZPRMEAeETlFsGpyCiiFtRAYjrFLKqJEMKugzyGUTlHcmZgXszJKOoQbWVOQRmKJZQmmfVU",
		@"gQVzLcxvDThl": @"BxJmRghKmnMTKoSzmQacgludafRZMBaSqWZfRZwACCkdwtRXKnTjPKvzoxKydTqAwXPJalPWTyTkOejwjoQaOMdoZjuzVWjusXjmKokbuPXXTNnUPgvaCGCetRcIwZl",
		@"SwPCufZCrm": @"wYjOrJxLKZOsNlQHYJaiSJxkLSRpAPZWJBGkXRCbXDRdjEodgWcFPRfRDwiiVGTmRiFHrYUpqKMXzvDHEELNFkGCnaCkotNhiRIOyaAiPULJPbPpRgWmgBuJvnhKNFGYzhJMzdI",
		@"XsEjMmARGplRUOBm": @"AnCPcgoHNNkesytrifdaKarWoWMfOBgJzEWLsuFlFoNVGUWLyqCIPnQrTLlrOMzwbLnoOmucogMuGTGhbTqFeDMOftdeRoRSblMLiiNouOozPUZQhmOD",
		@"XzuvZAidXxePfISr": @"yQeNvaoLDqtbjehJWZqtLPiirmVcuvyRRuSgePpOtmTQVkRDlHEvkeksUFUDtBLwSAtwoZWhMHdcHJuNCRYpUlOygfDTtJNodKjKBFOSOUYQiTAkJmHzMlNWJjOOHgklCNRDrXKuuQVoansyksH",
		@"wlBRiNjjBfgsQE": @"XnPBBFWfRxkqKmlZxhJLWVVvTHYJXpOUsLoYgMDwgoREMkDtmBRJnxblhHLnwMtnhWDqmnMpEXcpCADwBJgHlYaaFHULRAnObBfVoEaPeqDuSID",
		@"gNgJVJXFOLcV": @"uxbgVVZzBAbCdlpDPNdTDEvISMfwxryJjbgsbCwUrycWhRBdhHuSJqQiGgVADghfemaiBrxOWYogaTxapoxHmldlQJPuFUPPPRAEKSNtRuLaybINeyOyBaoGXyxorWnaqmcPilFQn",
		@"JioHyedrCmRsGdkjama": @"xzYsneViwjxJsOIlGMmslSxunhZaqrCOwHgegLZSvGOYimiQXQsaULCPnCxMiGagbzFlkSNyBFsjzHioNTdOscDXWwzRIjUfQNYmOcEJlsiosMdVyqzJkasDBrehvcPwFJgXNSQFoJiOlxCwbuwt",
		@"galOqZWMAseuDkgCt": @"OBSCxNsGWPcBqLMeOGnvQWlGDgfArPWfiUsjtRjKGptejSEGzrBxtbzQxxbrlXJJhbrvjBgDmALgwAHqFQTvKrlrekQJcSmMGWlVcIkRYVgUJIikrWJddEHEHyrpCTlZsxvzLLrIJOTfZjd",
		@"eYmfxAWaNtadhBj": @"hmGCiWHdJnMVzBKfKccvGHekwjwthfvFvCsKJiJlaTurMxDfutfwqUOsovhJacMYrxSXuvIoEogtlQgffSvyjTnyDIZbhAAUECjCvXDPztXp",
		@"UipDRwTfCFGGkoO": @"srMumWIjLNrwZlazmVscaJeSwDfyzOAHVyUmRmMQjiQiamXfcoedmDNUifNBAPtfLXHExJJwVoljAhntsueNStcsbKxqRkrmUWAPBpZIqKbjyFnqCOkxgHCv",
	};
	return QnMRQWKlHjK;
}

- (nonnull UIImage *)HKJNXGGQmTrcaccrfUC :(nonnull NSString *)NbidOiGTJp {
	NSData *LCdOhtjciIptT = [@"rKbGLDrEAxopcHfedMlVTtXRejMmoquZuhzNYTlDjhCehOMxaSoLqTPnmYOUxXPbsNtDmZerckSYhikzINDTsLxQMJqTtzItDLpkIjLR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PeEXOcqMdIlrFMEhtWQ = [UIImage imageWithData:LCdOhtjciIptT];
	PeEXOcqMdIlrFMEhtWQ = [UIImage imageNamed:@"ZXdhypttlOComXwopRcqzrEkDlnjIdKwsbwBZaByUqWvIYzuHPJBOmXtfNiBsQsjjbjpQBbwCoZHDpiyXWWSqWqcvHCLxUzEpQttoGkibrICeZlJGYgteXCCqZlXfw"];
	return PeEXOcqMdIlrFMEhtWQ;
}

+ (nonnull NSArray *)xXUugczSYbFbm :(nonnull NSData *)HABgdwMNaFBL :(nonnull NSDictionary *)yAiCyiIrRqvuRJbxgDb :(nonnull NSString *)ufhyJOQVRanIcldTcCF {
	NSArray *YoajJudlrRdIKXYjDqE = @[
		@"DZmBvnVMSmHqqVPTSsMBpEURVlERhHPbfUAutkwgCMwFMLwVeHfpOOlawsxsCKHmbivirAquGkTgMvsBKTntdzvkuonMsMBAxtmPXzCLOJcKBSAsiWnvJ",
		@"USABQDmPlvOptehYvzqnPWPzIPMsLmfuhEeJfWMOLmaKnlUqIXEjOZJIzqZPNGvqjLfMBDaTxQPQpCWJZOfArfqWbZsQloiFaUSjTaxhAVfKY",
		@"lilLZYDVulvwidNujevlWEVfeVsbFiTRaGWKTGyAbqAYrJicVZwETGGxCdpZnXydSHJwLIQdHSYsJuyLtPtokWBcaiwHBpTdLCVuMZuhUd",
		@"PZCBkWYtzdIFviAkrmBDqYTAkIYXhORdJJeeONaqXDGStSPjNeGYRGCUFfhcIhAZeoXkKXaibPqNStYHLWJbyglreZpkjjFGfdDokrdKJVLNW",
		@"wFgSopEnBRPSTzyxPKtevEixilpsoEPGHYSbCSpzpnRreBeAesJAfcDjfaePKTexACufjSLqNvuBMpErRGyjnNChVypgAAbaQyIXBwl",
		@"YhYQlJlQLJyxHVKCfkWBvRDHQUQWFrmfibNtgCmoFZeyfOLICiZbZNJJbqdHvlTfEvHhULDhapUFNvMrfRcVaHtldlPzDcGtSYQDQGmDVvrYAhgLJxb",
		@"XBxvPXNvoGCKJOYGIpOlPPSvxvFnuqoOqdkXeRfJyMUOWBazeNVICIghQIRFLaylYBNcUAeBpebdQUBSzjULqzFbGqFnYckgqUflmOCsacCCWwDHvYWIAyeMbodtbEZCypA",
		@"MJFFScoicOOpiKcNuCZPMRAFotJdfWUUesJafqwlzeVOTfewYhQfVwZafNcDkXMDZobEHftKRpPcgJvVzwjBzEgzcNaDFCDzOMyWACgDsIhHQYsgBebwDQSAqDlITykjSsGLwiphCZ",
		@"yDpVsXHXAcFlcrlcbctRponOGhFJFUyvbwwhlGwGPTkNcbuPulNdwuEjPXZnNZNaCCBlBUeZIKsCIizpoWMtZGqiDJpzVUUdzgamIusmqk",
		@"ZjzpiNqXRIYAWpBNlJKMWsOmgnPRCZxqOrRxTLJyOIhCpTbQcNXcgQYtXgOjdjDTXKOiOKvupcgSyHPkiogiajCoVTALFmsRQVthVx",
		@"nVZwGbfkywebulCNmdlGgrxxefYtLjwSoNswWtdIodVhHStqXDyIokYAqVLCkRTJxoeXeUUYFdzYAgLDmkDmHUoYLIVtjdWHsEGMVgsUgFVQsEQSFpCljJVwwbKTpBuEpxJhgRgW",
		@"hKdWcXjcquDjmZdaxEpcHaoKVYdaPDYtpUhLsuKBxhsfsMcwLDTAyBhLEwddnWwobZsfytOYpKHxzEHujbsaKthJqzeACoDhmpiQrNhTVUHlmxdPxigCaPlJEMMvugwIyUGhlC",
		@"VIcooydAXhRPTUqQIfBVfQKdzScTosCAonhphgDQAdtQFKFyLgehLHXEjIoIrMcOYinttAlwgIZIJiesEUTQkRcCQErmcfvUrhcsUtfZWyYsNYvQHGWyZgUGxG",
		@"pAAjXAGNrhOkWWiSEvlFlacXYmQwfOmILmbdIaJQfaLmauSZGxkTPMMwDNgfvovQCGuYyhiWEriPePbOCJkKaGgKSVCiCfBOyHgPeCREzfZdFc",
	];
	return YoajJudlrRdIKXYjDqE;
}

- (nonnull NSArray *)gdgRgkHIrM :(nonnull NSDictionary *)yHReqpvSOaImjHJEh :(nonnull NSArray *)vrUFLEduAMu {
	NSArray *ykIDbGIOIkaZ = @[
		@"KcRWJKvRQrCOJkTUdZILpcptoPASlJvKwLYHBLwWlMIQUVyTjeKaNRaCpAoeHYvnGEuDCtbBbkCWTVpCXJvseHCkRwpkHWpDHnVpGszcZ",
		@"gNbIGlcuHzrfHEFKWIAgHyoPsUCOefXJgSnReoGNZkdRCphSHBlzdGxXIxoVnYjDqmueYDrFIqEyxGdljTdvXhQXSSOTAjmHygGbgrm",
		@"glAJVpqdjdMVeLwKVNhgNfVilUhzwEKUeRSsphawGVLxqgQhTMNhIJMXTGyxqHceyjWZhYfdkpOzEYHQHBSfRIBfmfNHkSgKgQANvMfmFBMaonaAbGbgPeMZjvLzedlgXKJofiQyubUelnxjl",
		@"UGJPPuFnXTiWeFZMNDnkrcValYoxbEcqhDKidPiliJNcnYbwdnCucfeKXwOlowwDseZlsUVNNxywuJiIZVqGuVEoYsbRpQTdnluaStuJAlaYkeyZWTWldAUEiMcmFPCeaviQsmczpcJo",
		@"IHAEtIylfMtFiHDxyygdKNVJvipNVxyirMDCXIFOzijPrXffMoIgFsQTHLkWMLKgTTQqFUFHCaKAFosmrRjHXKPepkHnCCiLMQTY",
		@"YuepCOZitItdXoZxthHqkjdCoApoBDOIdWrKxMWkWvGBbsrPPTUrEPIvLoxtpngBLFweEaNzLDjjpDjOkhXRdfWsvRgZxSXrKIhPFgqsdzZMuPRhxKOhMwBZOKyJAaomcbU",
		@"koLdnLAABifMZyQuqTqYGOBAZEAwNJEzVfTmoClvYJEBkPqxCtuNEwgnDiRAmFVjStGZYfGfZVLVlsivxLbxYLUinvSLSOPbZAMHSpEtAiYcaxilNFsyHCz",
		@"IaNnSdliNwsUsvZwRTRyVLSkkavbRebuJUoEpiJkaZRgddaZcReRGBCnHczpUMeuvuorfLFPybZShpAZHFcbPyKuqMDRewukHwQCPxnyLEdoaLPbAZLEUmOOu",
		@"YUMrWgxOBdLoejHgEJxIxwmQpGRTUCEwCxQtpKzxWyhMsxdtLwrJkeFvoYQwDfObNizBfQYoUHokKSBNJCHtiaqUuLagQZCzYQIEBQCRScbpmavxNbZrvKrSTyUnibtyLTqIKnwCEkwQTc",
		@"pKSRWrisUkLtYBoqTFerUEWwxqoeMHEdvSuegabWULvoMIIipuPHGsyCQSRHSeIjojqhEfdylEVOwikVHkXaDUSiTSnrIRldjLTblwCuwzHbrhvLMVUFgqzLRfVRxOEVmf",
		@"IBOgSvtInxeopEsQsUzTSUewPjjPlUvxsYWTlEWNYWOqEQsfUyzWQIfMWbQJkgKrWCixHTgsHkDEbEOuBmEYVNJYBhrdiYHYVngbpfuaxkEDhmEqc",
		@"ReknAGyofLRjHxPrzZvHgEfZWoQjxaasQUHPzuQjVccCQxuyNkjCWLrPoSwlJPsxRGEmlYHUDlqXwbgTpXGlkIFpTMCPGhZbmCYeHmFfA",
		@"rANOzWyXmxIjokAqvkwDXhpfjBtAGYWbBsnNWqDVMfRyEjUMGPLzKtHOacKrPHlmxbGigeBMvqerErIIqYhmriGCCthhXTeEfYMkrkSyeMposYTVIT",
		@"RkPOfokBvOhgVKEPLXynHEmkdDnVWywqJooayVSOTBHVkjEGQVJpjKamEqMQAClfkxXLJrcIgBkZgFaiSQTzUVtZttyRuXcaEQedOfQieokFpocZHBVQtANOSkRlEHtpxHyKBUqRgklfoLtlCdDJ",
		@"amjLBaXQvKuUjYJCZHwEnHGIKVPQSbGzbwiFFxryMIKuhVRNubrUuYRKjjDHSMtSJppkjzzdOPBgyBQwksCPXJryUNPwJirxjgwQJKFMRwarooKmuqSxWGmGOy",
		@"GdTGLSYkwGXuRnWXbRROcOPiETOJZvHCvZEBndFYeNqVZZxNxETsTXkNnEJxxsTkalZxXRJULBJIcyjHYzRDKMzWDACrTJeLbWOYuZYmDdRxEZSdRlHWUnbLAkxPCXUDGtxBh",
		@"FRwmLAlQNoCugSXcqQoGqXvwCAepztLprzpnktXKRgUhGFhREBsSURIAMLdpdjdcQWzpVzZfvYqDMzPORBPYMPYsvpnsmciDtXKOoAFxXGOaNkN",
		@"daXOeYfqNQrktmaLJsofXBpQgXueTwHEvBCCEEHwwsWXfXvloMYERerBnHFgqBAfzKQTyiBWsDodEIYktjsDbFscqiIVnZUnHOhIzeWrOgIIXCkiPFSSCpAOHFJWBJrLJEScMkSNjYXJdlHLNjlF",
		@"TPFrpsgHUxyBkVOdHHOmQlfgamwyMkbOOubKShXlyqJGqBuSQseKzZYtQoAcwfnGoZFWXqDyXwLyIZOINClLDOZMuYykkEUJAMPq",
	];
	return ykIDbGIOIkaZ;
}

- (nonnull NSArray *)IidAvTxvdISItuggBkU :(nonnull NSArray *)xIXWuBqmku {
	NSArray *EdQKNKlvfvNNYpGmtbe = @[
		@"PldqOXOyKcPjNogZTKNPaIFvhWDvgXWutpGgehVGyyukhYRctsrUCVZsAvKoxjlPVlnmUKodXRLKrrkcrLYLeNmquDeVnUyrhKdlPSQbPgACMrwFhpaSzwyLDd",
		@"xviIEsGldoCTitYnSbOytrMvNfvilAmtAngsYbxNXmsaHFIircpZJwltMnoniTYqynhsrIMlQWgfJbJvJOloUblDAziioVxJRaQhaNVnitDbKhdIOemxHCEWuLJpww",
		@"mxAAxTRrkdDIjTnnKrRGxVxrTlcXyPzfwNWwBFgcmrqGUMVTaigSEFFbbnUBhvrcYqJsplIWjeQnhruRNknDHydXKUfbHLDaiteQPntFulNurnECpfYPuPVRoF",
		@"xRnlvyUHordZKuuzBpFUmJHOyixOxSrYBrnuulHXxHyvxrurzhYUvmOJlrxbWlwCeuDgZjlLUaXYhkQhnDHrYbXIDjFTXkrxFnFASFYaxQuCAiucndMeQNYlgrQsCmtXmLb",
		@"umYxiEIGrXyzTJiEXQFTCuQpKJkMQpfWsImVfDofkZExhaoMZqXhRtzafpiBFSWAkSxtSXdFwvJfsxZGfcMOcakYptguwfbBjqvVEufscTimEQAlFgjtzDKrKJMEM",
		@"ULzECCMeYWfRPxvLGRNAlTkxuJsNFETvKciwxMdABopyBVfYuVagkBqSbkMVNYfGpLmeHPcobYsnyXqyWrYQEyluSNwiJVPYDbuRspOgnigYTrYnqpubQWkljEcEGAjwYoJQy",
		@"OsCxPisxpsPuGqIKgjWSowiTDFSvvlvLuphJJTYOBlOKzQVJtKDWcOjdhXMxnedMjWvbIVJisHWZQyKsczOPjVOwfZoOVNQJHbVFxmXagFbybkhGwFz",
		@"CAEhQstUzWMlUQQzfVfMWBQpKVFQqVuykqNewKWQOjuwWWwgzzUTUKtLkIHIwUUWyBluVgEGACJSnEJuzljtBFyqHCuokrFdDlADHiBubOVUeKPoWZVKXLqfLOdWoXlXSp",
		@"WsIMwUPHskYEkeXHPeAgqlIPsuHFMyOLEizySTRTGLOVgMeHoSlGIcStEHqaXTxirGhMkLkCBXSmPFxUNFzMeuDdpBBSKEKLtKeDQNcvIxDRTgZIIoiXjFiiyhCRocjzhVqwXSMRTQ",
		@"xuajFeNKjokfoUFCwWtpcUJzvfzeGCvIhQQtTonchpbgSHKzUFWyCQVaUEnqRFZybpVojFweQUcKKVveJiICeruUtZaQyzIPwhqUPOGBftOvjzedRDTOOlYuCRkpGnuvuDnWdrnOdYkHxfrAC",
		@"eTXCijZtSCtbqGhvykEHpGRnavJZLplveRQMTEGodYIfpZoBovsWCGWJBzaImSSNWoHYQXUaITHPScrZSohxsRugKDJzmBLefigUpliFOZOUYyxHsPQCNSCtwUxuASHmI",
		@"EzJsVeavsplvsxsYOnYsNhUghkaQAQOkMycqzQlKcYgGvRDcPCbsAmUGRcWHAIHcQvbGdTBnvuSHqHihcQNvJaAkvCgyJtvpuldCesJsAQkB",
		@"vSUtXWdwsIiouyOkgBGLzTLzdnPmFDXqMcQPjlzaFtVQvvXqywEuqwVTbyKvaRMjLrHrdssZOEuyGvzripCaufyGewhxuRbesYmsQULdqjXfYDtYQzQSsfcGQZqYzLJqwXCelBUSkzoKiDSkaHO",
		@"MJKVLKrdIglAdGsltgQTfmsAThYaXQOqaCrSEYjzTbkXvixLxEZevSUKOFbwGmeFGIBBpZbQAcSlIQekWahlWolHUNCfvBYWeEfyBIcKhDlrWBKxJucusIXuKdrwLOHgPwlIFSxvaA",
		@"bKZvpHEuaDZrySmzjjIVVYLrxmloJmCqpxwxNnyGJfiNrHZgLjurdwaLRLYSYPEyFkjkfBgLoeDVQhPbYrvEHaGcEttYAJrKktLBGNwTBNXLRHutVbbbwYSaOGAaoSqSqJdhH",
		@"VqGFlWDyGGfVdhSimqemyaxYHOPUnZfQLSsGRtGChJzfKpgEtfpbJSTGnTYqnGvSVwltUjrBnihwnpKnryuRLOLKnNLPwikeWHfAXjylbJebleokXDtxh",
	];
	return EdQKNKlvfvNNYpGmtbe;
}

+ (nonnull NSDictionary *)SAlSfPCUox :(nonnull NSDictionary *)rLWLgVGBwbWx :(nonnull UIImage *)CdYHPPgMAGDa {
	NSDictionary *AdroUGQdOSxhsu = @{
		@"zYudUTtqcvPdn": @"FvwHnlivYDQuirQNhjoLQcHiWSsHcEVuYvzHCNYisHvJlJGcVBZfRVnrgHiTuuZkKKIkLxkWMHOHkmqgVfyhoLSTwWmouNiktaZbmvidRFo",
		@"PJVxzWkfnf": @"LdWYVotGNifTCYReiKERvSHPitBBhgllgfyxTIIQgiSEKRQLIdgglSxSOoicUQOKgpBdNGnTesTXuRPLSiMOHjaCaiEatmSYBhAODqewfYCGQkzUMdkUEsBvSsErcVdXIkPeokDZUHEeNppoRjvB",
		@"zGrskHqEze": @"OsfhkTqkXDVrWHkGcJFZyrcLoicacqnhgraCYDrlwKCIkVsJIXWQDqdslCMsxzYKbeqYooAQEfoLkoQXVOXypyDxQSnzrWZMtDUccaM",
		@"rXFAnYSostUut": @"GSBQakOMKlWJLXbNNmFVjKpxHgzucHmFHTBsvUaHhWGHajflPrRDMCifXMWImcpJlOIPEVvCkborGfrKpirTdrBzmPgorkCqJrXPFHaStuTaWJnEolGXDpslEtBsgvszxgbgVIfjrlHHK",
		@"IAsKXcsUMrVPpqVrP": @"zBqSdRiyrtzKlGQKcisakjHKRpCRDhktQnAeulvUuEpeukluwACTeDpSMLHPtnhQirTLOwUXDqlVBtnrqyzqFGjUuORwZdJfeSqyrqpwnTHPKnhchLPwLenwWUDJZFOcmuWyxFyIFAyhbeY",
		@"WhvECMEfUtDoo": @"FSsEQynSDCwNQsUCmsAMKCFTHnzfZLriYxueFSBygPGUQEAmmQxywRiPUOsNAPDcwexYGdveayOrBvocVpVJVEEgauisVbEMcdonnWVADkUFNhEkDtFTD",
		@"PAWRDotbRIjdRj": @"JqlWdzbcgZneeproNadEbLEOaifhPqeJFQsFNmBNtuJvEvzptiqIPWjsXYYfZYayhmIkhVbWtJZNWLqHuZALsPcimsUcwPStuTHunOGyckmQHqscTdNBGGR",
		@"EQraHIMBJPHi": @"NOClIcanDitWSkEpNZmhlNnUdpNdtRLDiEqqMlmZdiKUDeuNKlQcyiNLWJvqZcYmSdoCKVuPsXTZrelzQUoBvHHiwAtLJzACrcpGglHtBQgJTmXOXFoBYXkcfyJGlXuv",
		@"dmBcxPWZLljf": @"xXAuDmAPjLGqBApyxCETwjOpgAAoRxTSBzaBEacqPNUOYFIdhguDuzUfVkLCArVxSVOxENPDeJiZdAOMtajbEFTgNJctqnmWobcHyHdiDXFNJFsvVaUavMkDyvBCTPOXRQToNkeTrjS",
		@"trzwqHURQIdheCB": @"KKwWoTkcerdXROfOHsHMWGtJwYKUKJhSzvLRfONRyHErKzVKxnqfhcUImlubycVycrahWADFyZYCZqxUeURWEOaWUKpVPkZwhkHA",
		@"VrouJWDHPkg": @"SYJCQmWXqIEwcBQfRLcPmNLleRaoePHFjMHLUYHQvIYsMmZnEUURVgyeCxDFcopHZdndisSdAWfaAmFnjkmkpskDGKErJzamxzNTWuvaCHfFjOuGCkQwAexNrdmwDjTgimZvrahCodnNh",
		@"wDOYwqbIJTpMGn": @"zyczrndpAtIxocNBfjyEmXbWaqbKMFgwdXbtHQJcsYytZLVdLqDrcuWacDlZXEpcBidVlgzpJUGZUPQWXYTBLquQcjYysiFvlbXUxWUroEYLHqEeiKUecuQhqGmvDW",
		@"gCLPapydrF": @"fJUbrQlezJCtqYpSekaygRGnrcDiwaoqcDNjKFfdSZbfHuyQYUdcQvZjgDgOFYojeCvryhdqueOAntVnnNhWeKWMOeWlwnOUUnkKXjzXqSUgyKmRgxEQaQAqkEhVQBoq",
	};
	return AdroUGQdOSxhsu;
}

- (nonnull UIImage *)zWPVZcTrthJDFstZw :(nonnull UIImage *)oeqyrFZTITmgdBaUv {
	NSData *nmSFyIWiMxyxJJu = [@"sMALEYZPGMTDnaSJqWKFMjSMCpUnScKnoKrdVylJYBZrzJDJzlpPgazdDRrGFgqZRjvxDBVlhBcEiqFXNaqHicIwoAdZjBDiHVSVjfyhOotkfchPKHAZGRFBTVxKCxVKQVIBHyUPdMwpjkFrNjmfM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YcGrgRLtTsgp = [UIImage imageWithData:nmSFyIWiMxyxJJu];
	YcGrgRLtTsgp = [UIImage imageNamed:@"kbATedhkoeSRiVarXXaLnhUuOkUuehISbUKavgOiYjqOrdTdVooPTqchEMBtnRQgsxiSepPdBvBXakHqEftvucjgqydktBJPkmfINxTUOnmzBorHyEVtcVeUjmdTSauNreMpMyp"];
	return YcGrgRLtTsgp;
}

- (nonnull NSArray *)ipLmoLPFGFPACZuWXt :(nonnull NSString *)wpGIeLTgObsNnEf {
	NSArray *yVrZDBuahlBOxYF = @[
		@"KNuJPZywQQYVMaECJgiovguBqYrXJYLKfozCsJMUwxcQjnjAJCMhWgnQOmgOfqxsiQnzIoLeoZNJazpVvQRgjopRDskJheIopgoxeKJMSrWMHdRSgbdRmMoaiX",
		@"HUJGKJvqFXahLwHFWyjqeCHAfqrXsUPpvzBJBNuqAVyBdwcKIvzFbLvnxJWmNpVNnzTqDPiCWvItdwdcbKEIJJmBbvOnJWtxLBGYqCNKJbCAjABpgQpaFokGjSRMdjwhTfGFnhUcwqUnnOt",
		@"MZunXAxWcplZRhNVPYYWSjhkzBtmRWfYNBRuHFdGHCRVkReTmlFuJmWOandzJvfPqoONUhclXmblDUHYDEMzojwAYDletQTUQSqvrugUntApflAVtGTJzYCPfkXBCGSBJUJYppvF",
		@"QYzZxePHGdDoVMoKpXWmqFLsmobFyqBMSpnJnZFrHRdtpCsRtAZpOYuwLdDVEqUWKmmpHVUctQsTQMsDzzRXFOqiZSDzcreVSxoACzzsZSxyFOhkh",
		@"kQvzAryxFzpzEzTBNjdwxzFFLPecbuJBjkSkRKdWAHPtHoNlwuvuGQhjHMXaajnZZLEsEsoJyeDGgKJfwnxTduqeFeJnUbXxXGDOvGoWTXbwcpXLFpiObefAGONeNChGHaoEY",
		@"mIfQpytUQDHLUBqurOigHFHEeqYLcIFtaQrmUUwsBXKnjEKnXvIJVZdqJplOwkkjGeRQHfcHHuVbhZVLKnvkuKPARMbHgNKjRRuynqmSkFHXhgYcHgpT",
		@"wbIcmpFeXKveEXvPOdFFjqvumLBEXYaxxkSsyAnlPLdFKkUnFBLaCRYVrsuMMEqRKJHaZHAJbSRWSenrJgsScdaFhUrhDskYrdpuGVbqQZaZNvhMWTeWeUdgEyre",
		@"qZBrSzIGWmqctapDwbNJYHDMUzflYYgsXYzepaHXFttYyqloFlxacKAaZJnGyCVGFXxaxTkbzgBviKoOOaAqToZUNIXJCoRLxPdlBkRdcXowyqLJ",
		@"QLaKZtLrzLoivJdnInpGALqZYEIiuiUNiZhcpSacTfdJDuTcolHtGbYmvPBsLfERVbmsaalPhxbiBHXgdLubCZMTFfMlpYSSGdDWRhgDgUy",
		@"IfOhttAAQlOSKAeHjSqczthDUosXIlbwUCmpuSPBzJLkWBDtjKoOiZJxwiLjOkkmCjDIUWyLnwMnrzKkDEOfAOmintiGinbOuAhBnereENcKMzuPQMxMBCiafrSDntlBbqGGUbx",
		@"LXRLvUDGSUTLisOPFCIFYpnxzjPIfrENzSVbZkVKoFbavQzlIQBhCCjXKpwUMEtUjLGGVfmnwHprmxBJrPkoATvDrEhpRCeOuEtttANyOCwkROgxlNqNizk",
		@"PJuoNjTHTbQzxylTrvIfNvVwcuXcAmAUfVjiNTlvWPCEwpvoxNWpMFcorblSFouiPbpSQBdNkiFZvMdIKMFvzzQITgmoglSxHRDSnTjircYStVVEDEFcouqpSyeyhv",
		@"BiYhMiZOWArzrmdUTWmYirnvwcROnjiswHOcqGoogfntsZgmVzOEpIuUOhyJvaAZtNPeAZJCqekemtPYBfRSdnUOPdJxkQrTbDJH",
		@"rOOcQKvJfnYNxXhdorHCAvfZRMWovojUWkoPvPAnOHNGHQttylKfVWLeXupVfwCwSHIHkARqiOAhmHCykdBqbOuessSyJriZbXabQjClsfmvusObvLaGByHezTKNi",
	];
	return yVrZDBuahlBOxYF;
}

- (nonnull NSDictionary *)nOXVkCCArqVEF :(nonnull NSArray *)OiFDcjnVyfQNuUc :(nonnull NSDictionary *)ZfOfwRawgT {
	NSDictionary *OkCNGmgRpyAUEvtPw = @{
		@"LNjunTXTYOCuIAhuRTq": @"dPnGPjZxtsZNJMxCScnxmiMEQIUzdDUrDSqJGVIqoPwHxidjHvRLWbCbvWOeKvKtBfFmhFNhTigPTXrbRZVikWRWHzlQDMLDHdsn",
		@"lJMmmupVYixEO": @"ndfnANRKkfEGVriXtEcPvvNWIbDKlnkDkwnwIcdoGrVAQevsIgKeToYPjPsexpOtFuFNPAUFNWXlaYSIWhoJcHyEsCNSjuQROHZPPWv",
		@"xraqcEBHnsTrHpGjbA": @"MusVZPWsZDDPBLLoHHtolceJTkNooSKCvxXDgmPBMDpChTQVgRqSNGtusSZikDRycIDvQZYjYBpWbenSEjvQmwYqDMTeHgBlIiOpcjwrLcw",
		@"ryhFJZuZZSMIquTEZLq": @"xyHexuZizsWrylKybSmqNBsIuEqVmtxjwqUVgTuEOspZOYPjJfAplPrFzVyRBmFglxVsmusazJFBoJUHVglnSxyHCgMmGuGRTWzFYYMPiMwrofnvITToPLGoPBefstj",
		@"ErxxxmmhRnBDsTKAvdn": @"DvhFrjxjVDXUIQzgdDAbUKITnbmFjjcLaBNveKlleNlwyArIoNzTrCdajZRFsaAwoHssbUJBGhjQiXPqByRJFcuRuSsqoukPeBjSgAvrpty",
		@"yrkgCTAzMDK": @"OnMIuWaSQulVDAfOvQevpyxBUJTglcUyWbXHaaoBmwrlhyOTlSzqTsNrqqLAcFbZghRUrFExKRAlJVXEoVFZNpbfpVimKyEuiyVQVvuVTWFavWOhUhBhibeVi",
		@"sVTuZEOnSRJBUeQzW": @"WyxdgavfOQdZgVhqOzXsRCVDofMejRxlXZgqXDgFpoIRXSnzgzFGQFbMzpvfxNyZLssZLLnNuvJHIuJFgYpUimgYGZqoSENCZDJzVaOKuXBhqseMRtQVBpaloepzZFBogJOnQNhhsUmnnBmmUYbGn",
		@"XTvIYkfnTp": @"KcIUagCpuEKBYjYFFGEvoBSJqTvkEyVTNHjbraUOzgFcsmUwILHWHGaKhgsCNyHYtIUqTIRGOeNPocIPlSUjDqNDHRXrWSwTSCpguTzFglaABdN",
		@"sTZghMiPOQOWv": @"vvcXGWLfOllUuJIGQjUWVMIXpcRvLzupBbnFPuaekQutFuKuHSZUakccetIHhptcwUUpXZpvxciXoYbbdSIoCOkNhxfSjfPpZISLGMuLcVSikqytIGVShaVpnkruSJvCIRiNaWAdqpMuIvMv",
		@"LTxpmaNHVunSAb": @"TmAMbOvqvWQhSbQaozzqjYaJPvyWXrYsLiqVbScIeoKGVctLPYrhshXhMxwGBNPYgFQcNygYYmmMcvTLKMzyTgJoDilnEpXVyKQaUgR",
		@"rdiBMZglnOIbS": @"ljruWVazgoruzYvGAXKcmFuBkLKRzxZwXDsaQHrvmZjWUaTqtLxfgFfaKJrmFaNxUjypArcpGLRTbsOjBLRsRuFKjwyASmgthTEzhwhGnpKzalX",
		@"MtfEWICyGBJ": @"crIBhTLwhYtCUIuXOtxmwEUurlQFzkPtzWCakqwnDWTTBEeOOsFotIsMHEOtaVprwoSCOmlYCsWhfvQrJzQsoGRZYfMahvhVeKmgxwRXcGu",
		@"BUyThtlNQk": @"UaHZdWVkfkxqWelPmGcCJxVvdlyXsfmZPzOAnAhawsGaYNApewHeVnxvECuXvrVugmdovjXnWJYEZiIMspwfaQGEdpQhONSrEiLGyROLNnqiSzZoOtbQKpUfowEeOoBJXTW",
		@"AerscJSKrnxY": @"MzHeKyiZdLWXzwCABnzfjUAZBqlVRhrRBFCbqDLMgwoNPbgeCzNPIajbHzEnUqCwUrApTkTUbkrHJYTXhMXjgRYxmCKBLqogOgdBalOlwJoogCXShVwKeZENHLRyGtRQoYFTiUeLZVVBEEd",
		@"OkrYwfHirIQUXJSFVL": @"RNPfxywJQQeEionzCAXDDfbfgjDdpNOEgmjsgIWLIpJGsqvAQgHYfgUUgsPUUGlHPuldfXjiIIlxdUcTwiXREaJghOopTmoJuNzqULOku",
		@"clPhQjILkWOsT": @"NHcRxyoUWXbvEDQuPZlbJxhAZzBIRpxkuxZEdVlEjqJyfqpPcAyryisxwwdboYhBUnsIQadxIxSKkuhmcrrgzxJYTlKYKgSiJjnK",
		@"okUGExvpRDumG": @"hDtBmfktfagDFyGKPpzMaWDjHjeUjLWzfliTVNyQpveljTZMitGRmaFmihbbPlYByfcqMSRWkLaTYvNIxzVxoVHkoOcCsbuQcuHoSvaaeiViKPI",
	};
	return OkCNGmgRpyAUEvtPw;
}

+ (nonnull UIImage *)nIoqqPoIBnJJqllWNB :(nonnull NSArray *)uwkpnwKWzRqmy :(nonnull NSDictionary *)NtRvhXEegxwVYvSTWs {
	NSData *dtvvMeRRZmoDavLGJB = [@"qkxuVriJfmOjAjkbntYxWsFMesIhhEHiEhiretiSHCMYySOuLEILQbtiIkbedbVBwgRetErWYOYsEeDXlWjbFgQrcfWlTrfHCCfBytIAIFvBRlKkuQYgxqkrPNuWWBNWwmKfYtRTnAmo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FxTKlIPXhA = [UIImage imageWithData:dtvvMeRRZmoDavLGJB];
	FxTKlIPXhA = [UIImage imageNamed:@"ZuhdYfTUTNDxtSJgUZLOKdvHhtwPhefTKzdJPmCzfFalPvyxJhkWOwUVdoTolDAJcFyjAtQiWYGfeitPanFeAstKsoDLlhIvriOsJwviudNzAiUGNtvaT"];
	return FxTKlIPXhA;
}

- (nonnull NSString *)JeHOOEnYqpdbChKEjkD :(nonnull NSData *)wEtpbRawKImcNjVI {
	NSString *yTWbHyTXfBSrA = @"ANrasDUeJtHuwykHAAbskIoNdiWBQTIGowkSyozKLLZGJkuikMOpDYcGvFKvciNFuwNOQFWbaarIsuJEYdxyQfxLrCXUVvkyzPQvbZTxspJUjkEGaaYZAqmhwnSAnINFWiqGp";
	return yTWbHyTXfBSrA;
}

+ (nonnull NSArray *)VDTvoHsywJpHIg :(nonnull NSArray *)hKMFjVoPjAyzRelrGBg :(nonnull NSArray *)QmnlyIIqEqvbMqo :(nonnull NSData *)RlTGwGUPKY {
	NSArray *zxAubbzCORSERqvi = @[
		@"IEZUejPRJbnDponnUYHwZUWoXAkBLTsGttkYrqlpaWBslJUQXzcfqBRcLWWNPOYxWpqdKMcJwbYZMafdiyvGhWRGyOGJHMhsFYrMoFyyjXajeIZVYathXZVflbFummYsKPWWPoFtYBnQxfGGnj",
		@"iePKBWXhMYpXuCeSeNBULXwQJbEVMohrGzNaoOrBfJUWSTxsSbmbwUrYzWsXbxFJkTPtwqJwUluTrpXxwxqaJRlwJRbrNyhQuxYPPnCRRthJrNGZlfPkxLHKbjhV",
		@"PPOHoaIcDoNgAohfVcRvvKjZpFGfmFqcNnhGpUythkcBRuyoVXhjNCAzLbllrmWCNIbhaAfsdnrtWnqJQIVBydcyiXHnvmIjpcfRUqJwWbrRkofIBWBvePeptiAikcUMcrew",
		@"bikXwmetGwGtuEUdDwVWvSwBNgntmHStABybylmhgPGGuUoARbjdigThRGpCqoiUAPUhUJJynZbXfGgplaqxuiplIHvVxZAxbjLYgARJrVWSpVgcHBfpszC",
		@"iVhEtBDdLjGbAOObjUiHSkZmyVjzKHQcnAIiJIFsbkMWfXWmelGnqquUsPnVvrXmuCCGJkFniFMwjMqvcJlYKmGiMhqJSgcdLnpsqfJNCwUDnsHcvKpHuwCiawWkyicGdAzqeABgfyqsq",
		@"fAVDTumcvozvbEDZVgCChrHajqmFhyyhpprWIuglNCKxbBaoVOueDaRgXmcMkEXRKfsyfkhybPGNdeNwujsIdkEUDesVfULQnInPlzzbRNfwadTEXPCwSWPYQNmLfGrr",
		@"phOqSazgjDOutCnkwpVrYIQpLAqqCSnJpaiDpeChJijPUtjktpxsgTrvqYPuaawNTkrTiDCuxhYwQFcJJsFYcTehNBEfKzlewSsgLWhBbUv",
		@"xdlcfIoqPeWrZJIqeGPkGKacJAboWFnAjqGWsGXWpTMySBJmrXXatHSDHexouLPxDovxnyewtKvrkTxJMqGHQhlRWKtFHFUzwRfUIDtKgSjI",
		@"BRAgmLUnrfJmTVdGoQYJvmEZicWGRBqXvuIMOAQdsCuewsWhdOVOzkitjYHNCEoFpInHPbiWCQbZHmCwfSRlHtnGhWzGTTPiAtcNFykKkRXMAqnAqKgBtTcJTIJjhEMvxXFQpiKPlwadeRosQDcgb",
		@"CuOsgorUUSwmDouDNOTuxdfIQndlorfJtKCjiQpyXSuUjzqUBotliALeYrHuBTIFswaSwhBKtkxFQhKUiXzVdnJJXMgInIfMmNEahArKaxfkuHmNIJKdGlLmfxeczuXxoEsMYGgTVFoFzDenKb",
		@"dqTQLuIYUbuvMIQOohagThiMyGPiGdMtlKEIfVZRunWYKRhrphTsRZqCCMZyTXuFfjxJBROrRowZFflWikJIDPsMSxVXPRhDwWSFBKc",
		@"UuNYHxdvlgMHOicRHPtOHnmmGoUXcfUhMdMOHDUdNlUehvZUCpZWcDyUimFwygpZdptMnqnhGmNYiIbbxPthcZFlNKPLdywERAIfSJwspumaHUPApnnhOEGLgwglYhtdrTzAAWHbtRWGFcXtrh",
		@"myzSHOMfcCMWdtExpOeRrqRjkjxZgIxANyBerVmqacWxHQKyczBESqVhWgwdbHkOesPushBHPKppxiHAzLEahNwSlowyMFwTAjzDZmcnlTLrDrWdYumnPjnUE",
		@"UucbScZNxNirDlvdtxOXyOOAEpcwoVjwnzTuezXWXhpIgwUnfxslADyFRFIyTQIZHexDJjPUsTtqaBIyLczGpurLhJFhgbhXAngZzagG",
		@"ePutNCVFRabEJyheZQksqSzeeEKATkqWCzUsAKzRPMepDYwmCpNJSYpenYTqorlFIgHBWNDPGaVXljRziMeOIpxVERkCHkSFynNE",
		@"iuugFMJeQMOYDbAvMtTBNCKyqXWdxIlvcytFUraczwwbTzetQQuiTrMQfHNigyGzSmYAGHFMQoYenTYiCILxhGtOxYWXoNHsJmkBIYwFabHeBGomhwgXiejvVYYwsEFXgq",
	];
	return zxAubbzCORSERqvi;
}

- (nonnull NSString *)RvYZrMIERkcLEYiYPHb :(nonnull NSData *)ttZbpJqzwcLpSVHKKmY :(nonnull UIImage *)wxVtwhGYdJ {
	NSString *suYLubVISGx = @"StjzHmFnhMiQAhNuvcqsYpynHUfoakrLeIOgJTnyMJAwfDMmXEDycMfzHjnwkdzzlZIWVYkowwWwXPwqaMWLDJpFfTjMzFSiwdrTyZxwxQPbKubDXBvm";
	return suYLubVISGx;
}

+ (nonnull UIImage *)mfEomVegUhGpfmMl :(nonnull NSDictionary *)xnkpxpRBvCJuHwn {
	NSData *eQUOLaHiDxCKPOBp = [@"eScnnvvTKTyPXxhplIlbWrtwVBXiHryzTIOdHlyUIDHwVnyBBXTULkXbkCoeLyrCfwcwZwvNXeywotFaGFnJAEkeTwDdjXRDlDVesKFUiWgt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rfzSOgiUdFusIuOAt = [UIImage imageWithData:eQUOLaHiDxCKPOBp];
	rfzSOgiUdFusIuOAt = [UIImage imageNamed:@"pmwlJimxcAyiZEwlNizmFoCSxpJTFeCMKCoQwJOsQcrKlcaoKYYlSOiqDtbyxBZUcweUPJDNqunTEpWAzyJZuZZMAJpIljxWJJwoTCV"];
	return rfzSOgiUdFusIuOAt;
}

+ (nonnull NSDictionary *)rexcOkkFojSMtKN :(nonnull NSString *)WGGGpKotDvAsLLZbQS :(nonnull NSDictionary *)uLqNVCERVxVlcWxdw {
	NSDictionary *bwnyZwPQQnbhejwIyWF = @{
		@"tQRuOwWtkruexl": @"iiSlyjnjmeNmLrKIxbLwaAhTHsrSYEZgMwDlRpNCKJQnvHxGajfOFfggBioWEInfRjaIFixxPeScFtDmCHWHUxoeSPUzclPsTymColQDvEGUDMCMszwBlIoboXMIrOA",
		@"FLjznsClaMyEMVV": @"mHMNZuEcZLmvoQVrkFfhOzPamBdmHWDPNerZvtNHpAVHCvQjtalycaurhSGIbgWcVTTVooUnFwMKtLxagfXXBHGUjavBgdQYeHRmYTYzYAVrdsbdAxafXvWqJelerYGiRSxpwyeBUc",
		@"xACpeVTkQjkAc": @"bMeMtfGFuFtkBcjGAnXkkVmcKBJyUHvCEKmuWBlQtTJTaTHiUoQVCUCwTdxmDTKoNKDKELSfKjUqZGRLjflsVqZMJkzriRiHjvlDeVZMzaspXatZSAMAoebvHrNSulYjbjX",
		@"lyUkWVgAAxHF": @"GBanttxpSplKAvEfetemygflGHzsXXJQrVPIIsJqREtFVkHzLyuckuKCUftZlaGbgPMwMvDsddKFYFLjRmpwcPAvAvVcSVPKjsqYsTkPXoFmTjpAeAecHoTCXBBTBovZtaYwfgVN",
		@"jdVFJkmJaZtu": @"RdMCovFWhGjVBvpKLvwVxgstiXMyVxPNFuoVnGUGmlptFBMGRfsmaKyyEmQmVwJRhTflkvBJTArHazoTVqZjesRGEbKNzsORDavolIpNuY",
		@"MuhckwIXFYVIbEBz": @"FkTKxvwDjtsyhTLNQzEIQpZWCXTEFPqsrUuymKVtRztxvsbTNxaNQEgYrucmGeAFbqIsCgGVDgUwCnSLQLnBBvlkJZvusEDrbPqAEXbmNlkApho",
		@"cPVzBOfkCQVOE": @"NwqvbnyFfYuwiiaDPdSJIlnBqWrmEJHouAsDHKanqPYrWxFpGHVUSbQVcFOyquMQErPFKjTbrxHuvdqQAXbOsBWKTjDowrtmNXaxIsCNKJTNIfXaxvXDcmwYwTnQyEuLHEqorAYQIxX",
		@"XKFEIUkluZ": @"VIWEaqgMCWHGfhHkfOBgtjDeiOvMvpwEHXUoBIdcucYSiNySemDBKCQCQHtxoCoaYggWlQqcOVoTeIuZlAJWOkvPumpoROMPEWYZzGPPX",
		@"JgZOEoAzYelrpWR": @"xAKuBMCecKeQVYhRfOUKnHsafGzplJIBQIEdnoavVZrdvDFqRgvGbZxMJGnDdpKpggugLzNARvmwesbDSexiMpteurWejSHYqyFdbKwKCSgVDQsVkSL",
		@"cjGBDVjrbeFqTRdb": @"SUpwJgXmOzGYMvoneNrcuFUuCoEttmwRjYEohSgjNsUTdHmZtcSipYihvXZUXfRkHgTpWWweAJHeaDubsxlgwdpWHDxpHEicEdQvGiUgtVOQWdKPQseegbKVhZCZLTDgaSDzYVcOK",
		@"yoMseEMTvVwV": @"xsptUaNgfvviAGzHhpvRMGeRYaHCHQQbJszzJZvqOPeSKOOIGaCxaGjjZSBmzTymjNlubszzIdMSIqemDpFsInVsuCsLmgBOYKxcLorfddYyBCfaqnbGfiWVrDJqguUtHzVZOjK",
		@"CxzAiipdaLwTUDrcp": @"mpPVApmFtufYqmmIcGuggXAuynRElzuFtbjyJIeiLCHPjWDzkIcIqumedsSYrzXEKrPmYqPgetLeKDQqZRUtuCXeqHgdkLuFpvxICvAOPXOxGpykrJGIeqTKpJTJN",
	};
	return bwnyZwPQQnbhejwIyWF;
}

- (nonnull NSString *)SZJRpvTBenC :(nonnull NSString *)TMyfjYIDLczgr {
	NSString *WiIwxENmeS = @"AZCDjDKalIRiZSANmAFmtgMkzokLFDUwlpPyXageGaHwHNMIPxjkNGADwgFBKyBaEXGzoiySpUdiZQiVguPVbnimmkqvHtBrZjjCrqzrzzJocEwQsmbiYWaYdHHQovpVCLIcGkORCsEkBIZoVgOF";
	return WiIwxENmeS;
}

+ (nonnull NSDictionary *)bGoBRKaxnGpTJKwaqab :(nonnull NSArray *)aSeqnQDJLRnVpVrBvnW :(nonnull NSString *)uGYrXnhKzFvlacP {
	NSDictionary *uIusDteRQyOgaL = @{
		@"ZrRNPqAUzElJUOmsz": @"PtOjkBEOizkOfUwhiHZqrIWMSvWtpJAUSgKeLppsyngrgTTarDRUASMkDHtjbfgoRUmwDhZjPNMoCCPUBwfseqbpepDFHLqYhYdPJT",
		@"MwyElvYhJvSNy": @"UUoTwZKOLBeYKzIQWuWGhcFYiwMrHmsJPTkqZfoCYBQggzQyzgXyxgmZVgScAVVnYGVddLTLDJKHkXplvXRDbfVaBOOHfCFeLEuHmWFbpJUcfPBOvYAUyHbqGyvvsLdOvSHcQgpZBkrOe",
		@"vRyFoGArZThmcA": @"LEkFRLHetipRMjveqqdudjYBQcPWceJKrrNcKEsPljufzAQfVIyCsFaaarJKOUZeJHgvOKOxQtDPILGgxMvLttvJRZdAxVXGSOUfrqlgLssOa",
		@"dxXaRwnBIzTviuv": @"RCquxAqdeFVezorleudtowhlZNaQWQBBkDIAdnnQRHyFpmCuTHplgJMqbNhmPGcntZlMaXWrlyCBPZeDDMUsPPIiFPJvjSgaRqqDZIDBplN",
		@"MDLnOSNxaEPSrlTokFn": @"WKMQWnfgJhaVWqTUwyNwyYQUGpelWhJdGLuNErGXmcbWwKltnLLTikfcwghOMhddLWASNKUTbxmebnviATykTwenVOWhLdtGgTpnxkLTzNenedfyin",
		@"DIwEqWRHHQHk": @"vrDHznUtJJBarsYcFRojiLIrMxCuKxHlxjqWZDDMGpBoekkvLJkAKLijWZbmJwLjUWBCEzuFJoTlCbuMZsLnTgfDjEXNVnIEgolpsxAADdZehMKoozqwutekuXtlAXgraEhfoEWDLVVawSv",
		@"VvxDAxNybQYEoT": @"XzXtqCWPcAnRNxcLsXhkGGORFFJWQJFJQrNubpbGNuSIiDQxrLckhZbXKIbMFpVoVEvrVetZKSlbKdDFOINDpOBIuBYAmBXvDMNOukCPISdzuukTRMdnBRvvUtJjeBRLSNolGyIPSikzz",
		@"PWcCfUZrGBm": @"tYknibwTuyFCsvSZyVQGxiGcLLAsionAITVOoLrTrcMOFrKfjEuGyLLypogBKtysttyMbwdZUbgeiXlBtIrlaltSUfCHCWzWmulwbPtVxxYdiMfd",
		@"TFFwbsawdHcPk": @"xlcPOGugyRLKbGFIcVzVgRWUSBVxQeTPjGhTKOYDyGnIflqmBqXVYHLEbbnwtQzoRaKzEJAmRCgPvJBjiQDqRZhfbVpwuNqoErSeiDroJIrNrUoWfBgzIobecpXwlxMgXkWVxqPM",
		@"pWgOorXLkUPtlRF": @"dDFOcjHzPegwyZKykegWnbjxRudZeKWLmPSjTlZgkUvyWEKHVRwSNySawAcfHEzNjeUNIGjyxeEXqSblKtPPlgjjiLeZhRYVLeUvhrwScRfgnnnNqieIs",
		@"lSabWhzCdgvFOZU": @"XRUCGAMzkoeerpfGVKdDcpRHOFjdctZytlvbEKhZoKSvdEGyocMcsuPhQzFgoSxoeSUlmrGZTgeYPMokELjbpPtPxvMfxNSiSrIXVxlhSadyWjRZdexdgJqByZMAZrxzfqlxKRzupkq",
		@"qVyZROkqrbnhRYzxhcO": @"dVFzFZQeeOajDMXeQRIlmrJrwJIPXNsIYgfIpAcAVOgGyEAobzGBjfQYzIoueqLqqXEMKNNueZFpVhaEEZmBQmpDblxraNSCDPtiSUPSaKNRrD",
		@"yDtmSBviGd": @"GlQKLDYFsdRVHLYTyWLpoyYSmcJMeHforkJRpSjuEpgihuPWamdovUtyIxmONjTFfjQyBbvpgebTxGAcUYbGadKPNYYIiLSXdPeRNIouUYfpfLRdVHexZjtNecYazRfaMrM",
		@"bimBmfyfShKQFHeAJ": @"yLhoIOSQlhAVHBUljgKwEMHQGGCDPsrPLjgImGxNmaPpXKuVFhIYIDSbElKEkRSTMqcYKVsqRjQCmZoHufAKeaxwLCxBTtXJENvWFBxnhbnHRKuXkXVLleYkEyBsccvifSPglCvQG",
		@"unpWUnGoPkdZlP": @"xYBpohFGoSffHGQVRMiRNrFHfGJPfgBxcOwPvfpGucMABClrmDEsxHIdcrapUPbSoxmAlotPNwrNbuKQdrFHOLFwypJBgRGoNkgwIIICpDzhptUhuiWuTKSQnjxkatRLantqIkMjoiJSXphjELm",
		@"LKOMaEGHumBMkhvE": @"geWjdCVTwoqEQQsNKJhWQrUzTNDKdTwaViilTinDRRpzRWcrMRPrOvTzRBbTIhSunCLZhbYmHkEqfUzfsoksNmUskzRmSPDlPvyesLwzjHKJHmetttLWKwQpONZiWRq",
	};
	return uIusDteRQyOgaL;
}

- (nonnull UIImage *)CTEwdNjHsLZl :(nonnull UIImage *)ixZEwlftfQ :(nonnull UIImage *)jLKPIJNWykz :(nonnull UIImage *)rgidnRuHYYxq {
	NSData *yuaPdpKGYDSnVmcj = [@"kqupSlzCHEAhnEJrWQtWKDFGJdoySZXTNMlJtWaldAnSCdugFBzSzozyPKCjrRUcaDSTjDuJwWaaSrrkwuKHcBzRFFIhUbWMOQIRAF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CwMcvUQcLRpibP = [UIImage imageWithData:yuaPdpKGYDSnVmcj];
	CwMcvUQcLRpibP = [UIImage imageNamed:@"EDDhIlMjSgfJNmHropTpGKYDWDHXIAgTgKrjjhHAuYgnvgtOGJjpssJoApdGHCXZvLWjtZQihfwFMHLuGzbARuikskoMlCtpIrCuCajxFrEXPZKqRVPPPN"];
	return CwMcvUQcLRpibP;
}

- (nonnull NSData *)wXZCoqrbdpRpnyBHzc :(nonnull NSData *)YtOBFPnOrNqhOExIjJD :(nonnull NSDictionary *)DYdKdIURBF :(nonnull NSDictionary *)rDYXsTOcQmYCjy {
	NSData *uRCfzBjsOvaVw = [@"kwsyRNNYchOVZICavyMECMMDyWEsGfjbCsAoKwOEZiQBjslsqiDQANqSjxxqRSiWZHWCtELCIMjYuGvfdsJQRdvpqfyUUrZumYNoWTqizOMyiGZdWVcviVZctXsMoKciCtarZiCOTtIZNEoy" dataUsingEncoding:NSUTF8StringEncoding];
	return uRCfzBjsOvaVw;
}

+ (nonnull NSDictionary *)iMUbBVGxvBKwddy :(nonnull NSArray *)cvttApPriBPvEWXxeQr :(nonnull UIImage *)RVQirboTpYJVQPDQDH :(nonnull NSData *)KmXBPOcqLTcYPQlTP {
	NSDictionary *sqXbGxHlqiQVvYi = @{
		@"QvZOZNinWwGlaaXS": @"etEXKcbIEaprzWRotKWGUDkUMRGZSfUHTsYMNfnmRycQQtgVLByQETcZwuBczHeTJDhBmhHTAtaIyTigcFnPmkmHtsVKbEBKkwhvrjsBet",
		@"KhhhGKVNWb": @"lchbqeqXbwtQWUzzVAEjrrnzKthSAsZsvwaBvafnViohLRSLSAbJrNAIelpeuGjgWtamZwkgAjfLkriXtinwmwxIkSmXUHfXUQyfBioxTDIjTEFTVHDx",
		@"PEcDDomzaVpZE": @"eRWHmqyCVgbhFqDoRvFlGfiVLUskVmhWrRNbJCdbtQGudYntYngtyrvnOrcZxgNlZHtePnenEnxEBpBFLmSNyUNZVgWSEvDTWxXjBeIEOQHQvhVhfIOrkLDlX",
		@"bawZFcsYLwnHvm": @"RGoKfzhPLMDBNLSrtNsBNWOBDsTSoxeNKboYtfyCePCleZFGuKPpGvIxyTApaIVktjvavwtpwZVxvcaNXdkLQqQEUJUoptTgvmRFVNkhvmJjvbKIs",
		@"pcyzsyyhDsXPhiw": @"jpznKqmJShUvBALZaVqBSpWsYpYwDhRzfLBGnclprleUWUBWTnwaTIRgRCizoiZFeOUTFXIdlPynyhLQVSbiexnltVkCFAZmjnzE",
		@"gpYuZIdITQpok": @"kzKeEVbghUqMrCvwWzPmBxxFwKPZOaiLeTgWvuQKoJXsGNAcCDKGmlNcgsAcyPLpomyltWDespifqyZdlDkAoUptNdjJlNReQumFVHLpHtyUDBmASpLlqZHdZYxbHjwRhenPVdStmUIXmIqgPqCic",
		@"sywViubelFGuXKIko": @"rhKNYlAYsjPbOFCfHamozFGVWbQDekNQlBGjPwzAXCjXQTTjsJcrlCsPdnuqXgXOSSBdjivhcodrmPkTTWGiwIZRmpAnqNreQjwbCPUYHmCUePxzVXboIxtDh",
		@"kvkOVAnmac": @"xmWMxmrxDLCsFTTrDAkrogtQzXKdFaaNDDeSMZxJNwYphmOHJHDVdlKwUWFknlrmbiEVrLDhDOXMnJtMNTbuvfCmKHFHcpAqWBrpSzCTgKoLrZNwSqskIuylwgmBrrescyQLjEZaxHKTRsVM",
		@"kdTmBwBfsYkcgLVexfI": @"xFnGGcJzDmMkLBvtFYQpTCXuSSbVxazYrdSCZsrvBLYwQqlGOmTiGpbqKGnEzHotOCFCtXaMuuevXyxpHSQOBrUnkEmgLOHigbhFUm",
		@"AzvuYZPQgPX": @"JokknhEgobAgHMAzxfFnHEBbFtDowYpwQHLSQSHRubKUAVqOzAhSMeeQDSXdTqAhPgeNHnbqEKUrycFpLIZVdhvroIyiiKZzykSJQQaKIJXrMGBwuvZZWkRCeYCb",
		@"QCxvODVuCuBV": @"JKusAOrjVIxIkemjEcFrZDVTlvwRPaNHPwMAGSYatdeEasVjiIUptNefuZDwygXzkNPizjOMsVLghIeJOXADvBeEBGQswHJrScRIzmaKxGvrpMrxyWiaJtxSMWsHiUStSdBTjAQwgc",
		@"TDAHNmEylyLzoio": @"fYAjDETfPIJvPhSJtqtGbEzZbtqNDeNeEpuymyUDXxTDATQpEukLrGbRlHUwSxyjjLQoKPqWtWLjybULPhKOQoFLCkFPOLJeDKlpTRyRQmMtGtmBLSBpKKWkZPkb",
		@"pnryDcKEHREVFMcFUJk": @"EmrnLkDjSEHxPkSSDcVFKwSgGWVNqtIrlzhwrBRdHvYWtJnqMhsToJBTXZnPlgCrWkhuecgsXMlDKhKGrkNFnSngkRforddyWIJTkifKGINgaXjGmbNcaaUeFCNqsQZHCYnCQkZKQUyGXWaEZudvp",
		@"tBPnfKzWTkBtH": @"wzmlacHJMfPUhDcxUiVeyMHcQvfZnYblOhQyqZjXOpkJDBqePLdkgYpNvBdDKsiCQKNfmNafzRrpdBAGyFsXqCxLPXlZYoqaOLGtZgAhBELcmn",
		@"EemrEzCIZfzOHmDtBrx": @"lrMNYproEjdtvynNlWgbESzwTUgUsNuVdITxxyprkQeRVyoYChWojWabEtWZZkbMPHoMzRPdZmwUufdYIVUkJJNQIuJkfapjTJWsVxqDhaEVnFPQHiyaIvUIDbtnCGcYlAtZVXa",
		@"MSYnlWioGRtgxUaKxmh": @"FGMYBdiyRDMZHYzsmYNCItMqbQbfUcvcqmNfTThicDGriWnPaCMUuKldViTCkqOhsNSlVaWcUSEzmrDsKRgYZJBszsVCrLpOGsuat",
		@"uIijyZPBMQPK": @"iIGJXgqWFXgIYlOyqeBXrYWiCAUgUWOSsjIVlTfMKkqAmjHDSkjrpYkcRWaehBcSoojVrSZCWhdMRqtLKYbUqpZmItQHKUbkZBBpRgbpXMG",
	};
	return sqXbGxHlqiQVvYi;
}

- (nonnull UIImage *)KTWiMHRoVfKTgnAnJ :(nonnull NSData *)mZCLMluishc :(nonnull NSArray *)sLputXklPNkDsEnsxBc {
	NSData *IXUdIdrgFUJS = [@"llidlduJlcrRDqhEebtTgqOVMIDQZwqZUAYGfvcBkabyzTouoWRHjZTujLULVwHwUfqQSPjhkqbASfaelOOHuMUXPQEgJlsYoKYFVYSRFHmYlPmUQEGWTBqFAEUCWllFUTBkaJYUQFf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tiYltifdWSrwSNfWZQy = [UIImage imageWithData:IXUdIdrgFUJS];
	tiYltifdWSrwSNfWZQy = [UIImage imageNamed:@"uJjfBqQIFsAamWVPDtnOeqxxQNCyfmtlHbpUeSKBuCXVZQgITfPcFmMyVpZWolTZHeIjaNioJKeABBZgkHEemwmiUlNUPTZLtKCUXMWXj"];
	return tiYltifdWSrwSNfWZQy;
}

- (nonnull NSDictionary *)ZItENzUezgOR :(nonnull NSData *)feIuneIvMffqtflFp {
	NSDictionary *UgGAoFSmAz = @{
		@"QsLTELkBJHKUUnAZVQ": @"zGchtSFrRlnbPXBcfhyYznXUoyKIpSdgIsvPVaIDJLIrWlBHxkWtCwuvxXRZoUacQgWedqllnrAWKIllJmdtlUOnWyzqZyYyozYPomadXJTNTlKKrWTTR",
		@"qLvcMyvUTeQqDvH": @"AuGcwZPtuVirbcoPxKDPBXomALUQqBhLmIymHkcuuAhUUAazfZYSoNXzGkdRIRRZaGkWQwqQTUlRrNuODABoRGtkezAsyfYhhAqziLXUGauGwXpgRNDjBvhGT",
		@"kSicKZgLaNiNG": @"ejbPpKwAtlLABgMqwUCwEqnAqhDLZOGWlnzidUUwQgYxrWidIhUDPWfCdRJKZiMZftLsyySfnetMAbeQSvcSSIzviJkXfdQtBdzHWCdNfVDmjyOYNiJzWkRydLchtQWjqZdRnxpqh",
		@"wOlMsHAMiI": @"gbkMNXLtkRVtbHDUKScyJWzghTWZwcCFslihBGlgANMziqAbBitISzpvKnupFvddTCdGYiCXphBKzeJVRzgUnjIoWvPvJzrNEotFQgaVXMButnMjsBRojIdvAupsLoaTNkfJoaOFanxLpC",
		@"GZctHTTURhNDuT": @"gPiDNGduSfBxOmaxGIDXAJHtesvBpCWUGUhrcITpWXVDWwhuNllYtvyDMyzeBlOJbhQIWoRYXAxHcwWsyhtYtnaOaGVPlbPeVpgUQlxEqDeUYgZqHlKFyhdbEmXpcvHOdXIUFupYDqT",
		@"TRzSFBGjoNd": @"WcLUuuNGOuxchOlkuyMHPYJheXBmoWDtxtFdIsxLgubVXVLJIrKkDIUnPFhivpTRYOfrSFpnVQTjPtmPQLNeFIJcoNApWDhNRSfttGGwjRwBiAv",
		@"fKJfYhGfnFiHsCNT": @"GmSsFPtdOyISoBEufMXHHSXhjihWeroNUhgkTmfYTfuMeKmiPDFcixhbIKzPZbOnuNLHKLgEnAtWQjKBjCACpvjQhkqYpgoPVUciuVXVWHAZGIxLOfnnc",
		@"gNjNLbmzbCXJZGM": @"AEdYIqSBJeunLEBUqcKAjrFRWCRaptvPPHebMPvimKzjvlaBUaUzSjVILnQDsNEWBPDyhOWjyEmSGNjmQewUcmAGuoOxhHsyQPDGxjxBZWcAk",
		@"eSnMsahswoP": @"DWqMSZxnhxrNWAdEhqtAJaaPwTdQrrgzHHyjtaPRjjQOFCTRKWIlFQQuSimyvApXOnuvfuKgRkKmZIoYKZJjiaMBWFCLUqTvmJkeRSplIWtIelMcAsJCsLNLdPpsuFOpqZZFBeVz",
		@"VtQGqEviJEENl": @"ueUcmPymwaUPvjmXknUpUEArDWnZTcpeochUwhUVfEUKtnVpYBJKLZSgoNCWGSFDVZkNaUrIkNyXOzMyBlwrpyWSFUKoXFuGuZBCDFRPdeUosvaOhx",
		@"SFlVXFakOx": @"DJRVoRDadskTtSGVjqhtaNSTUzwsdATdGtYjydtBOXjPpWXzrsRQhJCxHUTBsyKVUBooknLHAhxETycSagWfLEUqjTydWIiCiZflqQSznDUblmySPkKTDckZQZAolaqZUI",
		@"gGSrfeZbMBphGFpKkO": @"CeFcNZXauyrQSCtkbmVxxEeRdLYImoQFjlMEyuzXJsUWTYYzuYMjhbyQzLcbxQJXVOiAAFlCHmXAxlYtQWlMDrRPIIqzpEdOvHULMtcfOsCQvosNtCSvRFfe",
		@"HQLmCMsIkacCJvkSgtB": @"gsSdtPifSsAfikqvLscsXdpTeNGurfmRDmtiKOpusvGKNDUmKQDdZxIyswusOqXynwTGxusIuwKipiONvRiViaiLPOupKTqwgLdWOS",
	};
	return UgGAoFSmAz;
}

- (nonnull NSData *)hibAJfPfXjMp :(nonnull NSData *)WIUeOyBRkuiimtJw {
	NSData *IuwKQGQEffHGmi = [@"fSdIgeGgVPzCDGBsjgvyCUoGApJsInecBLHZXijbFaNLHtYXrWevASdVxKQyDmTILKlHtQkevxxivBWtRObrfsleUteyedSqTmSUJmcbedxgoEHZdWIIeDBmeOVwrADxvXqhKEtFEnFBMv" dataUsingEncoding:NSUTF8StringEncoding];
	return IuwKQGQEffHGmi;
}

+ (nonnull NSArray *)xotTtPokuK :(nonnull NSData *)PQReMIwwRUbd {
	NSArray *TPNvQAQIfXHIQEpZ = @[
		@"QKTMSMWHlksJJqfbcsZOblhABmwIhWUOZhdROWXYwbNDNnHlhIEBCYsOmBxPiJbdUqRpHHwJhoaQsRGLiOoOhmnBLcKrYTGkEkAjtfiDDnjwGVkkHzUHdYDLsDmiQamFrFhPJfhm",
		@"BzzJLUAoJoDtZLcVeBfPCHBdlQzNTgYVCbDYADwZGUBqrkPHGMWtINWgvBkQjTnwWZdNMEHFNVIESCkceVzLuyimKxdBjfimCrhIhQqtYPolrieqMvkaaguMCGgBrcPTxAcVFnXSVTOeyW",
		@"fxXUYdnhplePlHaJNchXHwKofgxGbvpqvhBshdXJSnhVLcUjotWQShOztAccufRoJGXvOUPUDwasqcDsrcmxlmUyRkfWBKDxeeLqHmTAkwvKjBzRfwQnBiWmQC",
		@"ytWJuBgcdddbUuKrDbAfxqzhpyTEUibLuiXMnupzCDdjdHrXBToyIxxWJJoEacoWIixAmwdktJHmpIJeIUHVSnobWMyqnEPPXOgbEqKWasazfFBON",
		@"rYLAFhxqgvNBpaGkcMTeIYkICaFdyQiekkAZNDxZxCXFZykvZRSNaHsjbBleFiPjcbxXOjltNyTaLYBcNlSrcqfOHJzDRfvpoHFRXMXHEmNWDcrcAtrgXkSuJskCaxuqXRdkteNVWscOBWQNwIzJ",
		@"mcNCDWfuCUxRQqCbMoIljQPXMgqeibcmYXrWJjLRJbqgruoQhJAwNgoSZpqUviAQrxVukLkBRyQeMfbQwZRwMHEFjxMtvqzqPlSEWPnKbGPBHlbtbOsnxtoOdtDlL",
		@"XrzheEOzxGVqsUZPcAmCLtuyIiVucJThDLqifnlFPcrMDasOchWACzRXLZesPOWMCcuRgYjbPbxGhUxoqiVpgzaGbhGHAZpyTHMLCwJYfxHFOPjnKeY",
		@"ewmhcJzKfHrAFGBxuUaRsXhtLowtjNjlBRsvfLEPtpMYcHBHqETwbrVKiSCtJLGLKzzHirQIDPzQZZeoOIFVrxlwRkytPRSFbIcplotgUbKyvBdOMPyuIawUZLOIOCQBYdXGUtdYD",
		@"LXmmWtoHvMOsHNlMJNRVBqvRBRTJjIXhPssGmJoRDgiFmdKZoDCtBILuafJfRAbucHgoCqujVnIoXhsziqMwclYAEEFIGzJbFkwfosjXEADiCFgFWbGFtYcJyGlEWRcZHlZRvzWFxhvcrF",
		@"JZwiUkPOjeDRFzdAMoPWURaYCiBHlGYRlSYUXQLlinhZcPSVDpdfbDNjzfENUaJrMfjEzckweVDwciKiTPOaOscmSNazEZngxwoRUpnoTUyygDhLcrz",
		@"jiZwMKozhXOPhrHUVgcabFwaOPTXfqQGAVLGhhEgzsDvVqlXFXVIYxerrDPehodnXRappBIEzuDDSUmVeuPGwCiYQdsgpMKvVgQVDlUJa",
		@"mmOwUwFUOyndtasrYYOqTfIAHgqmqKZkfAFTKFnocZSdUSXQWhUofzoMeWwGUnEJTwcqUiFRzkXxwvWRZmBwLCnAvdAjjYEzQzUjJVJqeGGcxMdJtEmeepWYdTCxBLTd",
		@"eMgrWNwFBnSYvSgEsLkkgAwoLHNbKLJIBUXnMnFlOGFvpbCMNHNZfPWcvSYAgqsDGdvuYODvdBUhywRnWDkjdQfjdRGWoTVsOePFglQWRfsszQCZzxhEyHeDtKGYfcWLSKR",
	];
	return TPNvQAQIfXHIQEpZ;
}

- (nonnull NSDictionary *)vGObDAdRtq :(nonnull NSString *)ZtrVIhiXuYKmDKuOZka :(nonnull NSArray *)ysjtvSbRvEQNfuxdxM {
	NSDictionary *HjLZUTnYdvY = @{
		@"bLjwvFdZeDhAdafkQ": @"XOkmIJxSodKaXdSPlcCtjeQaRPRNetSeboIwcRRaihSOIxaBErbWugTyhgkzJVnjguKeZLDHdslykmKSopmqLayABkqYtZBBpvArVrXgwHuGSMylZAvZYdURiVumGksSCjNsDBxzundfhptIvD",
		@"dKSeHLQuLKctYEYEw": @"SodllDcEyrBeOTkwmMYnNDMksgxtdFErdSHFtQhRcudavxXoAOGFAQQWgEFfOUyCoAZCwamoHoViMFjWdBrZGtMTkMPFescXtVdWEcKanGZjeSbBOWcJVeSTNsXSouAGbYhFXxopqKEy",
		@"SuWQChQkaT": @"TofMWFMUgOCFKPLgpYjCsydPXfLsXJEznamiWQQWCJTjmszonWomGjsTwqcPOLUMbMXsDZzRShYMrXBHhUMumeemJfLBObCHwfxagaLzYXZaDsdBDuBknHkNdrFOvEQhuWoZYBrDZALwqYuSQjxQ",
		@"aKPgwpHRdhPhP": @"KtjwmapyIwcuUvHoePDvuMGIPzItlAxhsRNSXVFVwfzBOAFUEvXfzPJkvAeukxrkeeAoNntoIrwbWylTMjPIcOqdvWlVmDQZWvwweqomoreEEgJrWUGFqfOjEMTH",
		@"iCaosnehObPEJvbV": @"NPhCWrDMRrQatWZDOMKBoBUeHirVwlPNitpRMOTJyUHSRmxGiUCUkMhSxGuXZnHBeOKArrhlzRkNjUkWIrVWNBwNJJhJbhPegTRHurAQELw",
		@"MLyyVFlqkhUtc": @"CLNtCewDslUhjuEjjBVIvbfkWUojPdWopqetEfDyHbCbBcazDELPEASYpfSMTsUIswrddTcNSHjXCkuEFIVLruFqvmIAEuDACBjdlWlgFfkVpTUytECIlvWHGTMPEvPflaDDbQjUuZeWK",
		@"ZITrtRLIsAkHBW": @"qSSATImdDOloTSDznAtRWsnbOLCwHUMGwvAvHYBqgrDXpyVystGtZqsueQPAmkygImEuIgpbyFolQCrLRCoAjqGhkHgJZYTooKOhsCcFLnkFcKZeg",
		@"HAkGFakjkI": @"wbYKXOUvNpNnNxXfQGgbYuSYjMwCEkyKMDfpYxtYRFSzMkOjUVemoiwdSmtIXmdztRNwGAxuWJxayFSsDrBLyPImKdDNBbmWaTBHbKSNuQElAFpgykUM",
		@"NjYxPoMWeMhOHu": @"SJGlQwskMBhAxtVjANpdwxyxWIpUivMAUwqmtHgMtrpZLtUXBBxNyeOxVZgSPgLEHfuXIJYyFiNUWRcfUUlDAegklYtoriYkfvPdJTfSjqhMzSdEqxUIjyyETyPDjRkXdXtNxqOHkVAOeUJan",
		@"caVDqnGDyypWk": @"YjrYkEfRMyNMUGVrzjHxcCNQaIqHdCIPESyjPRaUibbCaLwuRDwLiKRujtjCQXFPDEAxBIslQytLOGRfTyZRGKbrYmhNEVVAvpMumkVmTwIELrqQViDsOjZEXC",
		@"WaZLiHHOhUlHP": @"VVuYJIbTfdGpnAZFMPAMJRnHBajMCeZKDeWThvjTDQFwSPACXWXysRRlDWlBltuzFaYiNaEbUZJbpplKWiohrmHdcoKSWJklSAnFNikJeBZnzcPmJBvFMN",
		@"OzKPlXrJQDU": @"bBaXpVpPMQbVEnkqvHQisYysAHDdXGhjLazdhFfoBkUnujaqlAJrepBTyocTBjaGdxOudgoCfRiDTTxigaiGuYbFxAOASHcCVJDKBKpypdXDjYdrXzikYCggzaETloOCuDDTUydutfyMeDBzKs",
		@"yFOvaxiNsFKMdpxv": @"JGjIeagZgYmlWhUJFfNNhunsCUnlmCpHgCQaKGFjRnnIuvpBluwJfGncSaFlGoxNONRLNCdfGYONHmaiGUeteXbwaSdOHWaeeweKSArvLvGaboZJ",
	};
	return HjLZUTnYdvY;
}

- (nonnull NSArray *)sGpbMvfHBcPGLnygi :(nonnull NSString *)LfVUerctkxbF :(nonnull NSData *)wvHDneOuglqazJWUxf :(nonnull NSData *)xjGaqKwUpUlHQjmKJV {
	NSArray *MUoRsLnuUru = @[
		@"jYMvthmeVZRhrkjqhulWzEHzZrrviZcUXRoCIugoAHNBGkBRuUEkjgProBcStMCMhzMQZSMcAYvfYKNHwELrkzibPaRyjannAsLggbbEhiY",
		@"OuhxNfoOBZNypBSMyrkTOslShQHXxgvvebniGXLVUCJuVALoKrIwwLMGppdLxTtpWAwjgatHKVkDMmFQBjHKUhuuWSQAqMfsJdURSTsEsVuJTDyMKFNHoLGqQyTFURpRtoulYLWBD",
		@"VuBMMgkaBvwlBHDZEDcuaMhmVHpxWQCOilWuMFVhMuOPVzILvgFjJKqTgdkDqXNjMxXGXLuqgBdienTPmSPJnPAFSSweZazDUYiypT",
		@"RbSkileIJgJGwmeDkqkGNoYKYhjHgWrvPlNLNqPFbbHeJwnBgEyoGApbAhjcpkkaOfqQqZcyweAdFBiUOnybiXbzLUruZlpbMXLPcUhOzLCCGBhv",
		@"hRLhEWtEuTTJkwQJSNsoBnyAkavGJZjgIVCcKQDwfLEVqYRCmNtSTcBnEtyAjUNvfVWDdlxLknDZrZfcpWRmmeXMuuzgJGLlyXypWIWLNrFjXXFRLoNcwzslOhHQBINsVhEhdBJVQuktivWrNnJVd",
		@"vAKaluQEqxLlaxIYTNICEFFQhLwhGZkBbjADFIaHDuaYwYijYPJTMgicKRkoisXdovJSXAhnvAIbHkvthRaPdvfoMUhzMWgyrJsOnyCedITCRIWIVVStHhhDSRvVnoN",
		@"OcdOpqrLsSndlGkdOGJZGtJZAQunlbaWjWteTQYmjGzcCiiAcdpWMIRHrtzXzQzBwyOQCYQaAqqMBupdcyREHpOFOshpgjlXVAtsvXfwRYRcFFBsVemEqHQtzCZEpJdVjdQtrDaDTVQNIhGyTdggs",
		@"ccjuqThzImDzeYzwmWndojkiXNyBHUhjExXyOXLYfDBYIRCrWVPRpERAtCgZgwztCHZjeBKxGocopiuDMSmMPVcBYhrDneEkgBMyEeJii",
		@"PgvBrxzbizJAAQJeKfpMvWUGyKGZTrpisbbLpBYZHwgWpyDQrwChZOTPjOjczaywsboJEtqDFMXFnmVbYkxBHNNvJstzGgMuuYIJELxIIepAuvaFQSaDRONKzUCS",
		@"oIstOfQPpcwBEOMhwVbAKpgbwNJrwcInulFBBPCPBvUqpQMDdcCdQggQYqTqnPNKNUgrYLtWCAwGVcrTnsnkwioxRVJZLSYsbtPLkcnMANFnNerOBuMpDiyLnbWfCqhKfnIVbEHEuM",
		@"bhAlSoivEgAkqZgxCpNoMYwueheqIOLXQCdAfPVPaIRNvmPIdGrqxbSGtFQKPGetLMdziDPaGiMiKWVwAtaYzdOKTsYiVWBvdsOGyzdVFCkRXvaFQG",
		@"mAXsHwqqkcBUvnTqlbjCdGZsAzyytgotSsYGKcNHCljJLDYkYkxavdrNmEmiZKMFDxhzRcpmkOUfDKZEpjzmVfDxuscqLlpJgCjWEgmjtlBYZEUrJzPJcNhAZZayQuZG",
		@"ZNTeaDSLjzhSYlVSBCzqNFGbDvSrpbmGeHNUJIcqXykHtMHMUnPeyTjmbZzXIsvQFiSBgKTqfDSuYpBMZhUlamnGVuoijqnMZQdeoEAEUNCWfMGCSimVxHmqwDtVywFsMMpXQniPM",
		@"wgtgZQsRLYBrEZmNSGjdrjNZtpuzklnkJkyWOJbJQVAdalVZVaDIymsJxVOHVpyZfKOIIpkcmlRvjkGKiRbELtInCiZjoRdYdnkrDeavxObmdTlutqpCJGeqrSulYKu",
		@"YLRFEHITTPKlyNrwAOijbZqzKZKlwEYHHkbUQIbtAYAKaFbHsijrIRVKisXSKaoymMJyPOzSoimxjwXSmtMfoyvOpvnIvoAfRIFLrkRCzDYuHDQjhgbPlxvthqexkQClLitmcJbAbofsRIlopKCp",
		@"YFyCodCvQFPBXHpDHFVOwggvOmLuWChKAfOanALkwQrFLdeMVwGNdyhnauECOXWVkYNUwlyvUKMfEaadokHtyLxOgJxySlIyWszQhEdYYrFnfKMtGjrQIzTcZXz",
		@"OwqrEMMMHLEjIdhmMxeMjNIBUMVDEdAXhWCSnNGaihEROfEfZoQyBzDdlvxnkiayNzQsPfihwFFljeNrpPvaCResmBxXgqvGPZvOFeMXNkxUVInmnWZw",
		@"WgMqvPkslSCUmgTdjPMyihJSrKLSDRisUtdEpWkdhZYikzUzlNPrJiIBEAnUKjrNEoRlGzScYwjOgBRVFXyvZOeDNDXuHrqlZaOdLnkZWGUrApGixMDjiahaKxPUjZTQSsGAXipeiY",
	];
	return MUoRsLnuUru;
}

- (nonnull UIImage *)PGmaPAoZgVZh :(nonnull UIImage *)gGkzTJwRwP {
	NSData *YshtwHPFFgIw = [@"peZgsHdAKSxdOcTSMMPIVxwtcquQFLfteQAruhybPhGhZUiQGLjCQNpnbMuPPfVEOeOzZDhoTZsmqmKryyYJZjkjjdYPAdixAGaszQVM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jbkhPEOVggXO = [UIImage imageWithData:YshtwHPFFgIw];
	jbkhPEOVggXO = [UIImage imageNamed:@"QqGklvMTFQeIgxLaiNSwWLbehpvwtQgCEmGucrbLKQIdFTefqWDpEhAEyXUpdPxGpmTrXoVbAbyeuxHafZUdEQyhnxxhpOHFCZToGBctQBceNuhZDxErusFGUNNLgLfpAQEhKbnqQ"];
	return jbkhPEOVggXO;
}

- (nonnull NSData *)iatUqSsHpAdYxthL :(nonnull NSString *)oXvoQboQWbtJM :(nonnull UIImage *)tKeolUbWUWiYZlcJYyX :(nonnull NSString *)oABzYuBRqukgr {
	NSData *jdUsMKnDnyUZMwBmWp = [@"HReAXYvSvFbjfSKJGuSpUskwsXOZEeDAYycEhVJJvMfACvWXdtoWLSLHsuBCHIaFrnagXzguwoIuFOWqsZFMNNxemstmVzRAxZjLlDFGhXzrbkEKC" dataUsingEncoding:NSUTF8StringEncoding];
	return jdUsMKnDnyUZMwBmWp;
}

- (nonnull UIImage *)dzVzsOzvDR :(nonnull NSString *)spQAbybbCtMboRN :(nonnull NSString *)GYCkspKmueW {
	NSData *qxoegBBJtM = [@"ZPNjPZZOihiypNDyBVfrQtVewKzgFkFDgHYvlyeDmTftaEnjSmGkjSTdbNdPzpHRMBhRTNWjtElKXhtyZobeKtTUMHxBBfULbPKgbEAMLzExuPKhuaWETOVNpJWmpSdNeiwU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *utEBneWsMelSTdIO = [UIImage imageWithData:qxoegBBJtM];
	utEBneWsMelSTdIO = [UIImage imageNamed:@"edIQYCmPNMpoVfFUXLyxbehupUddBGrenxNYJntuwkremeFjAwZcywpOeMpiqHGMemCSpcEHJqyAPyFugbzWyMmOrkluwCzSBGxFiNlbrFki"];
	return utEBneWsMelSTdIO;
}

- (nonnull NSString *)ivihVfTuUuyh :(nonnull NSString *)aVSkkornWJyIeMYw {
	NSString *STHDXayOUsnFFz = @"jSaIdTTSDGzHpxpkumxBNVwNoJFTLpaXodKtYyzuCylKylHuhhVFTXpyUqCXSXKwFLNGcepQlbDGFRrTWGXkTjIiFldJOsaTrhJdsKbWmbFybFy";
	return STHDXayOUsnFFz;
}

+ (nonnull NSData *)vrcIMCESqCr :(nonnull UIImage *)lUOurtIdYpRp :(nonnull NSDictionary *)mBYoXhGMLFHxGuvBDZN :(nonnull UIImage *)bvZBCxetOgwCTfNgX {
	NSData *rxJPRIhHIroOl = [@"HUSXfOgwOTNOjMxrfYmxiIBuPpNJAFqHvEhEGLDFtgidOPsYVWbRWALdqMRfYLrfgQtbgitmVdOOWQGRJEJlTHUqBrgQrSWKwcNeYlgENlGdMNZjwcFEFdbKkFeQJXnchagsEuMbhZBBMBmb" dataUsingEncoding:NSUTF8StringEncoding];
	return rxJPRIhHIroOl;
}

+ (nonnull NSDictionary *)mIIeMJoaINdjCzRJYR :(nonnull NSDictionary *)HlqlgSlhWG {
	NSDictionary *CEAvBeKRRT = @{
		@"QNAPYURNccoHjSkHP": @"FHilYzSsPRkTwzQgHklhXHrHnIgNvHVszNSWLTzmurCocPxScuuPBGeSxGyImdUhXoWMyRIhIcSDqZmmtytveqaHEXpINCeCZECRlGTiqKhUAtTrpayqOhpgaWEuNCKxq",
		@"UkDOVvhIcyzRIsHsfV": @"vrYPdvakxujOXGohzgXyoUeTHXfJGNTeoJusQdPLdzlXkjfWieufiuWrBsEPepDKelgHaMJUTKLDvouPzTqRnXBuiyxFIQOItYIasJpnzbmvolFlrnWyocomPClMPbkoOkx",
		@"pArkTjlEBt": @"ekTgmqxxBkGRWgkPxZjvpVwgUSxFOCBEqUOrdXXODuWMnnGdYbhDRvFXKCPqjNaUENIfGXeZbWrUfSQjgjgegABqHBPnpqZhixziYuyNcL",
		@"QWLOkvatEvyEJ": @"lTrLIYWHXDJuRdNUtskwcSeDmyPMaHIZsldYFETdOnvoBUmOWGpvdPVCQvexSmrVlBVeDfBOmWdKShXSKbRWnPcjuueVGSoZOGfZxKz",
		@"XFPtxPdUQCtXTVUEQ": @"QhvmvYLHnnefKwXgKxeQYeQirQZaYuIfKzdDtMCmIeBgNzOTQjRXGwiMjukBXEMOviZtSMpyJqeQlAoWpyGiVOXPOkdLUETvuPeEVTmcKz",
		@"UnLEttazmJHgSCwMNs": @"rIYBowqVopoqkHDbqComUOxewoYkhPOtthXtYDShLYRTEwZAXPSWNvuRLkjbyHCQvlSvOomsjtujyCgbrnJachIdjZBvIeyKBbgx",
		@"UgqvrktwuKmL": @"FJZJFeZgKfnVLnAMlDSLpUMOfoCnVzCIaxDyBTtJHzNzzfyZTcyeWMUAeOeOukOUwQDSQjVFPeRYjtGpYPUKEyvHqTkoTKDweXVYptOLhpHVUyEueYSnp",
		@"LKegUNEFpFG": @"TKFzpWAnUgEKJQLnrEhpJXoYefuKoiRtwFuehTyKuZzUSsYPWidBrXkmyYnquenQgCyTmRVTkGeEIPxDjdtpVFQTAUoyTnfsfkKmaPeGGOIwUjcPpUxZetedUbKmdAOkpmqwGsJQuuUJdtUrwNSBW",
		@"SLOGmlpKeCkkFPAFEW": @"fYKyPtSTtEdbmwsgHlKEbAOPMuiHTKVsjlLuxDcZOBPUoixeWMaysGVxpZoWeCSGoOUgKSLESCMygCSqWmkYKRWvKWINIHlynigXIuyuozrBYVYYJueNRMKSG",
		@"tLIpwGltsRXsoB": @"IKbWbDwHGEftMEMGhmTZADABQaDhJtmojKtahKvBIHLMwqjKEPGVbwHqCoLegFEUPfiDEYZNiGAhGfRFdiOqSrswMgXucgYcsEoFfqsSVL",
		@"egRdjlaMzY": @"soHreehkntZUyEaELXybToBOpncuyZveolHesRtGNYeVGzcFhnrhmRXaYHDZxwUqfGjJVrgsMpWytPPPZhcpzSerMSrPaZndJMjhO",
		@"sMmHSCDsgoUOkh": @"HHkAuXsfeyeFpwEGWjqNNNsVRqgZfKKNsvpMpQhJhxtqfgHNYWIlLqtJIOtoUDtEYyDiYcuyUKFVJbTNthAduwKqlleUMNUMmNnOGfewrDjUOXbJHZCzQCbgtkkuzmwPRYjEeGqzxqz",
		@"wgqYYJfDoM": @"drqaqzPzJlcWLDbXQGolKyvbErCHzSCaQRaEEdltjyoMmZsNxgQzFMTrdbxUUnTELWCXoKQKMTZjQatgCMEloIWxbuaQSmnpklovdxbk",
	};
	return CEAvBeKRRT;
}

- (nonnull NSDictionary *)HVRtuYxyHyfOmzQ :(nonnull NSString *)IEsBzdgmkDuuqOssLVy :(nonnull NSString *)IiTIhSwyOYWB :(nonnull UIImage *)JrnAuoFsySzVrFsyxr {
	NSDictionary *rctyeiSdUxPZ = @{
		@"HvwAoqpxfzdKKNy": @"vwCIfVDoziRIMnWViyYZxuYQddanrwDIRVBSaiPwBaZEeNqLkbphXlTFUthNhhYpktipEEhlKZRDEadxJhcyNrcKtBLuNKJwqleBUiQdNZcrrlaZpxwZqduNeFQsYJwftcEr",
		@"HRaMhXpNuOSqT": @"pXLRfbdcTbmnqJNMzreUwqlgeiCXFJrflYUGMMRIPDTVvawwMRsyqTDPCLwysZAeEaYuCDyLfPKMLtwtGXSFhFKbhUcyUuRIYYqBGJLamkDDEcvdtemKTHzabQUfIWOGsNEgpBWpqHjXSo",
		@"BcMCSVALGOWYPI": @"zcTEfLGDDFVbuMWSdpVbSLGyooEhQYhPpuhUZZImBRWMyQRWaXBdgBYaBKKdKuOLnOXlJljEZiWBAiJwubFLzYQhovcascKSUVDUQlZEelGYIukbHLGpKpt",
		@"VLwhgpGktWjahegSI": @"GtFWallsfhpFlRlSQqnNnPTdkmwhWcvAtWtyGxiLMbLtmjaSDVSlucqtEWBndDwRYarTytDcsoHGXSVeMpeWMwdQclSVDDPtGARpjOURKSGWAvrPMPdoNzZuvWhdVDDMkbTkpnIgfLbpAbLUB",
		@"pfnfGHDtvMRHuzIJsNc": @"ZzBeFJyMqcJnYKGPBQGcmUvhMDMRcobVtdauvwcSaGUfjiQnGfSdAYzaatYhIyiZLyenmbwOjmyIVeomiRJTdqFFACwrHfjxPMnOEAGw",
		@"SJKvxqevimWw": @"yOoNIwkDXryQwiXOKnXADYnVjvCtSBVYsqDVJrAjdPuMygaAIFjpICUSKjPRvZWNjejAUvfutBCnidLXoKFlpeFvXxvrVDtHXNdCEkfgHiOfiiFTlLvbQHFozPNMSUMgbTMfdYdxlbWPQtvoiMdol",
		@"pYmaXJoIvHISfWfiVnh": @"VfkzrZeSOkdVVDUCeTeeyukmDihuYcAXWvLzimBRYxsLBbfOjDXrwwvYkMAbAoYHTSwEgsLjdemPOCmhZhaYpFNAMcUivNZyDyLZiZ",
		@"KuYtucbcbRvYx": @"XPDwczfjfhfbGTLmDcvkckSqoxRlenuVhPNcdngiZkmAxGHRLkKqlbMqqlIDgFTqiBsqtKKGrYJVFiZERYmdItpVeAuObuuCQncppgnFeaKfVMzybQTthFxHaybEbvEha",
		@"dDmbijutSZZLdX": @"vajLMBdwxGYnLuCpntzheabJCDQtZhvFpMLfBWbZuTinWwAhKLqraOOqvWEuiQNZCZjhpYmGSpblfBdXzkilUdtDetYAmgmAQdNBIdMsYSofULJgbanSVazTgnfuJsrvqVaGurRNXk",
		@"hHBRojEFGgMdpZVlxXW": @"UROQUVmmFeJtfTjGUuBAAJOSGtgPhLgYdGAfAErYNcacjmCZWZVwYBvlDsCvgAmsGWjUKSKQziGpaFyWcgbSaxUmmoHFDwhqbngaQ",
		@"VuwMqwjcywmc": @"ZxKhoQTUmYvlMholMfPXzpaffYipxOEYvlurpCVbQWSNmFowOtcVLusPEoWQfHzsIrxsZlLYvxoiyrqKsnrzlVATBOTxaIpxWRgOiobzEmjNUqbZtUPwpKGKxMlCDultDnDABQBFFqvqIXyOJMUTX",
		@"kIvcerqiAF": @"vfWfLjnNBbusMSIZgVaDBDdDtFqcBSOpydjtEKUFNzbJuUYBfIyIChHuidbWnoPaisSXuScLVUgFYfYCEdzhJeddVOJVFeiRrbAhgTzqGnqUva",
		@"CFXaTFgRIonzFQcjfI": @"UzSyVGbsyDwQradjcxIHWxUAjWGVLXfHlCtGQalYJoCAiKCMFebgTJnPUKJFtIluOpeBWAWWuggCMEGgYGjDwksuQMBQwdWkQGxuYYgFrlz",
		@"dbUKItRmZdnpiIXANdy": @"dnNOfPbNQlzWsbXjutEULXXRGlmcXhtrIhbDzfTTwFJCeDOYPdXDzPTCfeklxsXJkUXRYxNBpujrtnXywZatnmULGSeSnGKbArUfCmaTZWAltSyYBcqWreofRAvqdKMC",
		@"gCuXnwUJpkwDagEY": @"jaWCoJiYTFNlHiXEvokskZpuUUVkGHeQSYCLeMgORsWXGRSdjoddwjSZSHLPQiTtHoRiEdgsPtHISaBUixWwlAvDTgYaVzorTaojFOfOXUNLEsJXjAjCjPk",
		@"TBODgDiyYrFmDOLbYtC": @"kXWCavSonJAMBurypSqhMlCexpJNfMLuxDXtHTUSLBgXSubXKCEQrjRjJXZuYDfgZklqMldjztwjgQZotHWgizBPSRunDZXYDIpRECuQ",
		@"fDavWOSRhBJFNMYubZ": @"xuhgwlIaSSFkQBKqkEOhQDvkwIUGmrSusLBctQPQiGhVdlhsSLluxHeKYjHgGPfhhKXwcApzobzweavaTUisBcbaBEFQWEHgvxdrYpxuRqGhgUDQDdKCoXNSJmswFejxwHXuHNwrpRyIL",
	};
	return rctyeiSdUxPZ;
}

+ (nonnull NSDictionary *)dMBvsNVPGpOrlD :(nonnull NSArray *)GdTDOfUXArdOOWS :(nonnull NSString *)BBKddmBSMOVa :(nonnull NSArray *)NeLASNrsDpi {
	NSDictionary *wFooOYQKebm = @{
		@"aTFVPTlpkrVoyrnc": @"QfEDAzJEJiokTCwFOZvKBoXjxYwpeCZtHWfqlpRBLEmtvXvwfZuZXUJDgcTIiGjbhuqjkAWiWfiAedZTtzutlBnhsFQzfRSFwKfMMminevBWgtslay",
		@"oyvxWLVhlhL": @"XELIyoeOUdRfcifTXcLuapjpvpAHtnhrGfGxSAGgnFqfxSYQPiQuIFZZqChsFjcoaPBBgJhvKFtppvnjprkHwgVzXqQZeaxqZULKtIzHsqEFICEyIiqNB",
		@"rxHbXnKtTcPZfMQfJ": @"JVlBGDwIHweTIrGEzCpMyoLJLtAShESiwpAkjtnfXoGyCdocwebXOXQGWprzGBzgdPjiAeYESiqQafNeeDvWqXcAEqYJxQaKgiSUJaPTpktaYWPfWqkKhLpOZqouuGMKgYJo",
		@"rkKhvYRKlnfoaXiTjW": @"zoQwnYFqXOCqPIJsyFsqOnDmeanAouFEBREnqrRjzGAAmNchwAchcyFXUGGfqKyTLJLJhNPCOCvWHiUymrKUEBzkDmEwSSnHwjeDyZFmrpjulFEhePoyEskDqPoUpmsmilMGaxuuollZdJ",
		@"ZwzrBLSqzcMzS": @"tAYQUkPENHHOohrKjODcRsPFKrNOeZTxYIyTmQciyIuvGFIWfdyqhHwNbZzrdJXbKajBATQqRJciEahcBcaPxDdpIpMtaxCXMyMTqfcPInMYXsGMbVRquGaKJQcNurJlrLeDYQsY",
		@"DaTabGDzpmreYMzFEc": @"snEAkpSalOZiimIrYEVrfTDzjqOropUTIuSBLQKxuEhzGqDyEvRwmIUSMGFFrYoTaqjVVvRURPhqXPFzQWyEUDUIQZawKtTcwLnZILxlkCJAzrEwADsRAZELyuoVw",
		@"LvRjGWMNtd": @"YSevSYqvXAIdfMbtBYawNWXDXjCaIGGgtYWEIyeklFsYVECEohOiBEGySysBziudPzCBPZpQWSjzJDgjCwmDExjjzImDOKCWVjtqqayiAWNGmcbhhBrBxYulPRsgohsHaxKyPYoJWQB",
		@"aLnyeEEtNY": @"llHWKftwiAjUKtNgzaULUWuuZTmUqRsrdnyKYqJSrytrkVuHvllAzQbRNkOUtPcBmfhJDrXmJSJpxzAceNdqsYudGshpmGYEHfdchwuOootoJjpYAXztWkAVJKOMDrQjjOKiH",
		@"gyEXYrhzwTGDTJFpx": @"nbwPQfnUniaZHbZlEvHaknuEgjFmHyAZGkNmbWZAPwalvJXVJFokpbSBJsYGWOPCJFTysJxFIDJNiuNbPLCaLGtwBONsotepJeRYafzoiVAb",
		@"PAtQPcxEUWbnLpiaE": @"VdZzzrXxTqYopdMnAxzaQqWqdJCtqMcYkHZHengSDwxQJCOpfRDcOVZplbnYvtgYNsKPqSimpPYNEiYMyQbCebXBsqDVdyZhBtpBDByNKbKHPaLCTKbMTJknc",
		@"fWyXWQvEjlXgzI": @"bAcgspwDGMSEVfpSaXkmGTuzYFZmLeaugBgkKOsCglYHXQdhAwsMVdlmOoBgFKCStjWpnIAxaDVaSFZmhfrLDwsMyuTuLAblZmGcFALURvGeWxfKVaUWOAOCKJoLYizSeajkxldmPJhWMzNx",
		@"lzvSLZHVOpNacWhOTP": @"mnrorfmIrqXZHYRIiHeVsSrRKRBrSMQUBQrqLQFBsqaXXNdbiaEHLyTYfjcYDyvvEuuIpvfdukCBPBiCCQBetnBNrvoLWqewGEIialgcoBQRCLOlVwjlIYcsPeGAswHgEKMGfpA",
		@"vJPKJduvVkPaXBHS": @"XqxYbTPkenGXyeywUWvDDtpaPDHWaLBDEDInHmvQzJsCVaoQVuVKNKRGCvvZUzdluaVZoSMBGKmnAzEBHHAfRtVUnJHDynWnUtCoSkYPQLYIgikxdiFIWkv",
		@"qRbAURokBlA": @"TmMHmHPjCIRFHQSwyLxXBgsBdvtvVuiBzAdYJPPcBKqOaVXZwwPbUebvfXsEWHalYwOYAQbOghXPAapQkETJYLtUSSuymqfekMhRMTiUiUjNZpJNXHAbZk",
	};
	return wFooOYQKebm;
}

- (nonnull NSData *)OzrJNXnvRqdEzo :(nonnull NSDictionary *)QuwZUKWVunlNcoJRB {
	NSData *CkiOHFfjuHnN = [@"LJkzFuOfEHwTFVnDCFJegztbPdwLHNZBhIOlCCEXAXaHkPCnoCIVoNRIklCEurFLPJqvVbAgWyjQnLcKIFdCpkBXpLCdoRNEOpVqEOyqyNGvxSIIcxOzYJjuBbJRHcIVTnEUonTHq" dataUsingEncoding:NSUTF8StringEncoding];
	return CkiOHFfjuHnN;
}

- (nonnull NSDictionary *)fczNbXlyYblZZUbhRIw :(nonnull NSDictionary *)xcdYehnXggTupWIUiFT :(nonnull NSDictionary *)XqtEGTAKdGeIEIfL {
	NSDictionary *XsPdVgcdDLLfKrYJroY = @{
		@"btScwIaePBEtcDQzaH": @"jojHAhlfQPweKylnPApdxWDhmCbmfdhBvHBacWkmCiBjxKsOCHCFaftcLRVpNvosHccUsBEKUIyGwZPqPZxSOCPtuEpVAIXiaMnJeugTpBnoReKmLDFLoldiZWpLKNoVCuIKng",
		@"FKmiuXYgTaSfyEEW": @"apmtZCAQQXrMKlOgPcFRWVZVEJTPeFlUFDmEoolZjWNCUKNHeQHEYumdBYgHcbaEArSYFNgUWhBOBPWMyIcYAdszvltSKPiuAoGquQPPwTQxoUobOaSZDQGHYXzpAlcthYFyzNhbXLTPYQmNrXiXs",
		@"IQbjqlSlSjbXqpI": @"QxEwAbqncOMOhoQJhJBtiXyDiJUVpMArYPGBdIGgZHErkliHWcOMxZZKLRAMporYtfeJrOgPcCVOsFbjIcaFUPapoLrPhpkaXlrtQmEeZFIoiVKUtabYH",
		@"UEjXhdIMuTiRVkhO": @"LdpLOkCOJGKWrIAogoYOeYStuJjpfJCbMnhXmFavOiVJhNjxloxmDaDBitvEPCAyFoVbSvzQNJGRtGJKgVVZPpVCAhwVvkNAKHqvBVhQboAJipNKSS",
		@"uozCcDcxorstz": @"luIgvXSVDROZClMGeJrnkscVBwGXqRxLzlmUoeLoBwmZlLCfnnHqBCBKBrzDYjgyRKaUDVsDUoKqWnTznBNJjcrRdXcvCdQibOaWJnsYjgFeEHcPcVtFd",
		@"GGgxMAcViNGLHXCcML": @"GNCTnauvSuwQBHyiCWMgUzFSLCowfAOrrtQbSoZgaapTDVPEaihycyoieZTophlsKuEqLTHbhaQAchvnZegNCklMsoPwSsgBgqEzHeDpueblPpRcjPsRBNNaIrMdRLHZYeJAMxU",
		@"uYKacZbPyITSSWzE": @"WnLtSVCuUqVFlZclCDwARemVIDbCoIbxKuItXtxZqsqbkNMsPCvKWZCAJBrQkmaVnTQREYolyJbuPvBLCMmbxhcsodjPIxBDdmlFmAdtnWWVja",
		@"pbXwPdahoVlzZ": @"JjZtAVCaqcxWOwpaixUbFLprzPyGVCIaAXwrsKUSxVCdLMHWdIssVEXwMcwZVZyXPTvbFZmKCWUhxOLKWuFsZXJVhSOvrjMnuayrKsKBznOrLYtzWLCCvGLkEZKXxdTEiVrTvXvx",
		@"RuhOaFDFGhdhbu": @"RAOUOvYIEPHKBJtotQNecAHQEZRCqQuqHQANzCteatxvjDGNPdDhIDmeSFyjHyPfedKuXKExuTAFwQFXuYtopWNvUtUDUCCCjjzGJmglJeMejdWAxNJxkHSbnhNHNDWpWzfvnkLQBL",
		@"ZzdUjtWIEJbrgTjgVx": @"FJqMckzIljdmMdeeccwxCZjJvChuAduxATywDayipwUiteOVOEmxGgmoWqDLoQsOpSDRKLkpQVwoXZhDJnyEkHyNhFNxcVdwuCNnBCFgjmBMfDljUqZVWMdgYqv",
		@"MfxZGiFeYhe": @"cnjJSFGiDXqWWxjPatkQGlUbNQtHaSNFyjLEHNfveLXuupakvtKebvwniZNAToTnFDEeFhndJdhqrEvsuzjYuIbvfdeiwkaxuGgFQjoJUGiGN",
		@"nCXykrwZaCpmfHrzv": @"QJWAsJdLvrOJwFvSQFxuiWdkmLGwTreJRNzEwPOTAIEqpzpBIXZzoOrfduVgngZwVebCIrkMvnIZgvxjYhQAMVgHnaphnXsWzxYEQOBsrPHtjNaQXzQ",
		@"navKskEpeTOUTDd": @"vGwWSgCeXwIwfEamfHuehgXTeJcShpgidGHTsnolRVfNYmVtSFvfxaQPminXxcSZnMtBSbZiaPvTyDJEMOASBhAXQghqITQZWUppXTHEEozgAaRptJ",
		@"wNmCebAmCiaL": @"FohrWMIovnuQJhpmWVKuqchrxqySbzCKNUvULRhzzEijoPFfsCJyPKRKldaCGngOCIVAvnkaXNAJDIxXrDFamdxnMTFFuMBkAATZclGHC",
		@"pXWBAxsoXFect": @"mkTEBMpyowzELiMBIOsnefCnWZXBpqbAgBznXssXcBwmFVEasxvogqnvYZULcttHvoSmBwYDOpUXpgfmxqOCOzllWqIjzkBtiKOGyy",
		@"WVMyVnIITxzAt": @"fhzBRbtgOCpskXApsGYfxDkAStXwOFJvbvDAXRzBIsMozkhPIlCGVCLWNrwGqbTpvUBliLbYmILUiKvpOiypgtacHNgotjEOMbHLyUmbXChSUEYANxeLQYz",
		@"IvDAduijLS": @"CsUXhOaNTDuaNhaEtGCHOdSxjyiyFoHTTUWfmiKYPJLwVDaqWYkjCalmMQAUQPBtQwOgTeHIDtNetBodFxkXMOLwZOtLkHoNDPZf",
		@"xfiALXMNqKWw": @"hohZfXsnHeKWiTvDqwGodQCarHvWHpQIlIdlBEGbZrNRESAmTatPpkGjYTogkAvJYLrrppezArvKaGnYNqCdEOOoTTyruHCcqInQugbDdlHOVxhEUdwLxgwmVHbEyniWXf",
	};
	return XsPdVgcdDLLfKrYJroY;
}

-(void)drawRectangle:(CGRect)rect
{
    CGContextRef     context = UIGraphicsGetCurrentContext();

    CGMutablePathRef pathRef = [self pathwithFrame:rect withRadius:0];
        
    CGContextAddPath(context, pathRef);
    CGContextDrawPath(context,kCGPathFillStroke);

    CGPathRelease(pathRef);
}
//圆角矩形
-(void)drawRectangle:(CGRect)rect withRadius:(float)radius
{
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    CGMutablePathRef pathRef = [self pathwithFrame:rect withRadius:radius];
    
    CGContextAddPath(context, pathRef);
    CGContextDrawPath(context,kCGPathFillStroke);
    
    CGPathRelease(pathRef);
}
//多边形
-(void)drawPolygon:(NSArray *)pointArray
{
    NSAssert(pointArray.count>=2,@"数组长度必须大于等于2");
    NSAssert([[[pointArray objectAtIndex:0] class] isSubclassOfClass:[NSValue class]], @"数组成员必须是CGPoint组成的NSValue");
    
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    NSValue *startPointValue = [pointArray objectAtIndex:0];
    CGPoint  startPoint      = [startPointValue CGPointValue];
    CGContextMoveToPoint(context, startPoint.x, startPoint.y);
    
    for(int i = 1;i<pointArray.count;i++)
    {
        NSAssert([[[pointArray objectAtIndex:i ]  class] isSubclassOfClass:[NSValue class]], @"数组成员必须是CGPoint组成的NSValue");
        NSValue *pointValue = [pointArray objectAtIndex:i];;
        CGPoint  point      = [pointValue CGPointValue];
        CGContextAddLineToPoint(context, point.x,point.y);
    }
    
    CGContextDrawPath(context, kCGPathFillStroke);
}
//圆形
-(void)drawCircleWithCenter:(CGPoint)center
                     radius:(float)radius
{
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    CGMutablePathRef pathRef = CGPathCreateMutable();
    
    CGPathAddArc(pathRef,
                 &CGAffineTransformIdentity,
                 center.x,
                 center.y,
                 radius,
                 -PI/2,
                 radius*2*PI-PI/2,
                 NO);
    CGPathCloseSubpath(pathRef);
    
    CGContextAddPath(context, pathRef);
    CGContextDrawPath(context,kCGPathFillStroke);
    
    CGPathRelease(pathRef);

}
//曲线
-(void)drawCurveFrom:(CGPoint)startPoint
                  to:(CGPoint)endPoint
       controlPoint1:(CGPoint)controlPoint1
       controlPoint2:(CGPoint)controlPoint2
{
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    CGContextMoveToPoint(context, startPoint.x, startPoint.y);
    CGContextAddCurveToPoint(context,
                             controlPoint1.x,
                             controlPoint1.y,
                             controlPoint2.x,
                             controlPoint2.y,
                             endPoint.x,
                             endPoint.y);
    
    CGContextDrawPath(context,kCGPathStroke);
}
//弧线
-(void)drawArcFromCenter:(CGPoint)center
                  radius:(float)radius
              startAngle:(float)startAngle
                endAngle:(float)endAngle
               clockwise:(BOOL)clockwise
{
    CGContextRef     context = UIGraphicsGetCurrentContext();

    CGContextAddArc(context,
                    center.x,
                    center.y,
                    radius,
                    startAngle,
                    endAngle,
                    clockwise?0:1);
    
    CGContextStrokePath(context);
}
//扇形
-(void)drawSectorFromCenter:(CGPoint)center
                     radius:(float)radius
                 startAngle:(float)startAngle
                   endAngle:(float)endAngle
                  clockwise:(BOOL)clockwise
{
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    
    CGContextMoveToPoint(context, center.x, center.y);
    
    CGContextAddArc(context,
                    center.x,
                    center.y,
                    radius,
                    startAngle,
                    endAngle,
                    clockwise?0:1);
    CGContextClosePath(context);
    CGContextDrawPath(context,kCGPathFillStroke);
}


//直线
-(void)drawLineFrom:(CGPoint)startPoint
                 to:(CGPoint)endPoint
{
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
//    CGContextSetLineWidth(context, 1.0);///////////////////////设置线条粗细
//    CGContextSetRGBStrokeColor(context,0,0,0,1 );//画笔蓝色
//    CGContextSetLineDash(context, 0, lengths, 2); //绘制虚线

    CGContextMoveToPoint(context, startPoint.x, startPoint.y);
    CGContextAddLineToPoint(context, endPoint.x,endPoint.y);
    
    CGContextStrokePath(context);
}
-(void)drawLines:(NSArray *)pointArray
{
    NSAssert(pointArray.count>=2,@"数组长度必须大于等于2");
    NSAssert([[[pointArray objectAtIndex:0] class] isSubclassOfClass:[NSValue class]], @"数组成员必须是CGPoint组成的NSValue");
    
    CGContextRef     context = UIGraphicsGetCurrentContext();
    
    NSValue *startPointValue = [pointArray objectAtIndex:0];
    CGPoint  startPoint      = [startPointValue CGPointValue];
    CGContextMoveToPoint(context, startPoint.x, startPoint.y);
    
    for(int i = 1;i<pointArray.count;i++)
    {
         NSAssert([[[pointArray objectAtIndex:i] class] isSubclassOfClass:[NSValue class]], @"数组成员必须是CGPoint组成的NSValue");
         NSValue *pointValue = [pointArray objectAtIndex:i];
         CGPoint  point      = [pointValue CGPointValue];
         CGContextAddLineToPoint(context, point.x,point.y);
    }
    
    CGContextStrokePath(context);
}

-(CGMutablePathRef)pathwithFrame:(CGRect)frame withRadius:(float)radius
{
    CGPoint x1,x2,x3,x4; //x为4个顶点
    CGPoint y1,y2,y3,y4,y5,y6,y7,y8; //y为4个控制点
    //从左上角顶点开始，顺时针旋转,x1->y1->y2->x2
    
    x1 = frame.origin;
    x2 = CGPointMake(frame.origin.x+frame.size.width, frame.origin.y);
    x3 = CGPointMake(frame.origin.x+frame.size.width, frame.origin.y+frame.size.height);
    x4 = CGPointMake(frame.origin.x                 , frame.origin.y+frame.size.height);
    
    
    y1 = CGPointMake(frame.origin.x+radius, frame.origin.y);
    y2 = CGPointMake(frame.origin.x+frame.size.width-radius, frame.origin.y);
    y3 = CGPointMake(frame.origin.x+frame.size.width, frame.origin.y+radius);
    y4 = CGPointMake(frame.origin.x+frame.size.width, frame.origin.y+frame.size.height-radius);
    
    y5 = CGPointMake(frame.origin.x+frame.size.width-radius, frame.origin.y+frame.size.height);
    y6 = CGPointMake(frame.origin.x+radius, frame.origin.y+frame.size.height);
    y7 = CGPointMake(frame.origin.x, frame.origin.y+frame.size.height-radius);
    y8 = CGPointMake(frame.origin.x, frame.origin.y+radius);
    
    
    CGMutablePathRef pathRef = CGPathCreateMutable();
    
    if (radius<=0) {
        CGPathMoveToPoint(pathRef,    &CGAffineTransformIdentity, x1.x,x1.y);
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, x2.x,x2.y);
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, x3.x,x3.y);
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, x4.x,x4.y);
    }else
    {
        CGPathMoveToPoint(pathRef,    &CGAffineTransformIdentity, y1.x,y1.y);
        
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, y2.x,y2.y);
        CGPathAddArcToPoint(pathRef, &CGAffineTransformIdentity,  x2.x,x2.y,y3.x,y3.y,radius);
        
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, y4.x,y4.y);
        CGPathAddArcToPoint(pathRef, &CGAffineTransformIdentity,  x3.x,x3.y,y5.x,y5.y,radius);
        
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, y6.x,y6.y);
        CGPathAddArcToPoint(pathRef, &CGAffineTransformIdentity,  x4.x,x4.y,y7.x,y7.y,radius);
        
        CGPathAddLineToPoint(pathRef, &CGAffineTransformIdentity, y8.x,y8.y);
        CGPathAddArcToPoint(pathRef, &CGAffineTransformIdentity,  x1.x,x1.y,y1.x,y1.y,radius);
        
    }
    
    
    CGPathCloseSubpath(pathRef);
    
    //[[UIColor whiteColor] setFill];
    //[[UIColor blackColor] setStroke];
    
    return pathRef;
}
@end
