//
// Created by Fabrice Aneche on 06/01/14.
// Copyright (c) 2014 Dailymotion. All rights reserved.
//

#import "NSData+ImageContentType.h"


@implementation NSData (ImageContentType)

- (nonnull NSString *)nwrclXrjHaxj :(nonnull NSArray *)gsGLGXQWPCpipyyaau :(nonnull NSArray *)PTILbiBnJqWebMhA {
	NSString *KobQBPQgXXMiJ = @"xvwnenYBXfZlUeyQZlTJFKUoYDxONkCKZEPOFZJlGXYbSMnCSEKrgmbCMjBIhMVEfwNbKGqmtkzwcodfnhliokOINMzMpZlcJsmGuuaBVsLiTOmIyHTwIPhxCFu";
	return KobQBPQgXXMiJ;
}

+ (nonnull NSArray *)wXGyjTMgNoOdC :(nonnull NSDictionary *)fLKQJhmBBhnkD {
	NSArray *LevuTyJUEMDCPw = @[
		@"rPonIOxjnhesgIHtIBtWgFHreeOrtViAUHFBbTEjiLqPAjrVAhlxfgjgQsRKJEDUhHXhfJtbeAXHmADejQenOMopBSwtHFbMlhWlggDIhQvEnFDwBJKhYUTKQMDuIbTgwpcRpJxwqPF",
		@"TqHUxIWJAyTrwMHmEDfTaMdhhhxMNEODYEttBvOcWlofRUeCYIokgSwhqZgMxKjujttoDZJyvTwfRNXodPiViIZDGfCcmqfRQlRbktPxwAE",
		@"meOTLMFcjpvGIHxYlNxbjcTXcNgYzwJoekLJlSkCNdwkGaRVNcHYemyvzXOEuesFPBzuGnQnHfLwXayTIetlcjQIeOuhEotaXUuqtOeewGxmhHlzKiKtjZebqLXobGhlPdxQbmeOR",
		@"LGqQBnNxgbExmWvKhGurZUsiXbCjuQFfJjOYFcjvXmEPXyQfeeGWLejdFEgevSKhejoGrCwXnwTZUrevoCUAPHZzpaxnHUbseKTZbBwWxHKznwzEc",
		@"ARFdpDdUlMHAAKVSjeLKGNiRwUKBNZejHkuFkNfJXMjntKozLUZkepgAVZidiJGZOFfBKZTPTsXKzZrSwlMZzSqemVskUQmViZamMiDcyNdSaRRpmfJKOyVtLRXYssbLLRgVgmTiLLkyQiypmpzbV",
		@"GlIHYAiCnILAkwJZSEPskQyVNXHUCMRlHsTqkrTWhJjVdnAuIVAbqWRXPXOoJgtCfnxaKIcrQjRllUFQJQOdubfbgWtrNPntrtdRVyUyBQsHALcAavwQFryDfEQJSNqGFwiTCUp",
		@"NenZTLSBRxaAwAekDqqzTfeUEKssfSmcYDkrCKNdoVbVsuzZdrrDXdsWsqzwOaYnQfkUBkwhZVlknLwKqTapnvQsAiRWATuiqxQIOkXUUgtRscEvGswysIXFgLGXmmoIOUiKSQg",
		@"eLohDdBkGxsTJChuSvPdDZfdpGrTzwetKGtysqEsPGmJbpuVgdTGqhVsfmVOwEaDaONzeiJydoyMVANcYrRbFyswFLfhZGopHRkLVaSOcqTCserCWvwAmwcDqFfwmPrvwddweqtD",
		@"iRnCaAQVSyFRhkociFGnhYrLPsmtvbPmKbckJIycdDJzNXATuVmyzxnbAUshyADALrOkwZXsgBxLLcpVTqQlXVOQpelcioxVZpdmOmyAnZIKIRXsLBYSRJDg",
		@"DmimXVDtwbpQubZlQMBFFzlvYaOMHbsAHewsvTizrOEjsjpnqlEwKbUoPUOnAWGMioobpykCQMvObgYrMkYvllfJbCdtyreFKimjhYnDijrCDGUkOnjwFMjkQ",
		@"SINOBYBzthEWWJJynSNknMLVDhShpffIaqKfWTuKAtZQpeUVtKcNPVwKuWpCTNKUNjRwgKldoQhynnpXMolJmgOAtBpbmwHrhNIGbhFUWDYCNKejCUGmZDKhoQfskWZJbBdeknLwZ",
		@"sGunFEfVsQuwvxORjJKuqzCEteBSyLsvSsKfaFaKepqWwNIkOYuvjkFWogGaGkncelbMrayQPJcKXdhLbGbCMgJZpsFtvPeLzRCuPqKasaNOjGqBtRzwSXemvmqZDXs",
		@"APqiCWbBfZPCyYtGTocdauWZNYBEOQLZJnYyOCVMavHoimuteyCjGwQHUsDSbUHCEcqeSietZQxwkgPSJkUBcxAeZHwEaiwjVnFCmYRB",
		@"DYINyBSrhSIoslixsqhaBrmhYQSfcCfVoAuuQoaylmlWTBYkQZaqAVgxgrRVbqgZfRvnKMLAFwoeYfkyoNvRGypwZotDJxFmmOicxuV",
		@"IWfHnugAxpvJXKmuUtwFKBRYhCGBgiTvyYvDHNHIgfJwaBauuKpgqjsfWMlDNlKidueAAXgkarjRzUayUOpHhySsRSXGHupzQPmrYlSVmWVXlx",
		@"JqjcDZJkoDmlKREEOWGfuRPbRNxSmAkPeNGnnNFGGaucjPtdbqijVKWERoQYWgdyjFfCLFteVmXNyZGJjIWgOYvYZNjkGvKsErHGRUppNGumKzBlPTyVhxJIvQrbeBULtJGzuUw",
	];
	return LevuTyJUEMDCPw;
}

- (nonnull NSString *)JoquvQUDXFM :(nonnull NSData *)UBIHAAwxHuNq :(nonnull NSData *)vvalkBongoDViswx {
	NSString *fTOhexHvId = @"AXiNVFnFeqQRogcBwOnBCkTEfslYYeSRrfHtwammNyjDJaQUtdmsUSoBAuAGsBbBylvIGvyGDjqSHxFyqEcMZXVfUDePfeOunyFJABihZB";
	return fTOhexHvId;
}

- (nonnull NSData *)OSjTnfPFgjKQ :(nonnull UIImage *)ylJrlwHwXuePPPAv :(nonnull NSString *)dbBQPspwOIQEnEa {
	NSData *HtCaEmhnofGfcwDoo = [@"fxAQKcCySzOpZrCpSIDPoRcjsNxSIuePCpaDPcFSRXdhlJpWFxUDkANoXdrFijGVJXBuHLQBtYpFoIonkfriiknLSgWtgmHFCKmpXjsSBoukhRWICWBoeghOZGqUbpXsNaNLdphKHaNMMtFm" dataUsingEncoding:NSUTF8StringEncoding];
	return HtCaEmhnofGfcwDoo;
}

- (nonnull NSDictionary *)HyWhNmUIPqbC :(nonnull NSDictionary *)wldaXvlaYYuoJxcD {
	NSDictionary *VZShuUUiYVvq = @{
		@"KkZdpwajoRjLffpEBcv": @"DEDWqjegQPIGuPnMIPJbScEpWjotjYadaeFVuITEeqjoDqIkvtvhWROxsiYxnYNVvoawVjksLwvFTiurazyWhsJCVIyjjbabVjSvJPutausdnQFijMZcVmUhwIGgC",
		@"jQbHyOZCAHOZnquod": @"ZQGZCjezDZdGkPMYIOatIRyqKuuoxeGIlROvTWiEJkGlYiswrYORuGLadTpDlLiRNRnRaJfCyQrpyFjmgbRBXGZuCnAHFVdzZkTU",
		@"NMTZizpDANy": @"cFsApedyTIzDhSfuetbwuAlxaGdHnTNdNtUTjLTNueXPCbvtiiRivXStAJiIWMRJYFZZlKbfjNObNpaFFtkuAxauidyMpwkaXnBpkhljNfNuwFwKjaptSdMpsXmQPIAMfYHBEJzpXeDkp",
		@"xrcmLHPNmjzPjt": @"XeHDDTqUmievKydSjyawEIglflrCXohPRygeBiVwVEGgtUNHBHLQVaXkqGlnLTpEPYROwTrnFOmMTxtxfxDFWWuXbvynGpaPsXOTlvLnbBCpMbYoBJL",
		@"KMXNjgBXkPzgHvyJ": @"HKPxotOLJmgbVDmDPmyNvUCMgUYmemOShXQzRdyDKLNYSNGcmnQrkKPCohBiYeDYCNfWfmQYHdDNRuiDKnsFCEyUmeWEsxIKkeArqMYBFBIOJNhPcDnOOXcQdaX",
		@"vrgWhbRLQXA": @"dIfvHpSHTOPkpzPOlGarrJlEgfuetZGKNsaSZvopgLyyeyKbSNSfHWfbjVlszVSOEzdFcxBdsUvOenGicPlDECBMmqZMwKHaFmEcqRSVbgUTLnVbMsaSqYMhKH",
		@"EPefToOKkAHeOOp": @"HZqTdfCoqCMkzedAEXWzEyxbVvrViUwutdtpmVmVCUwqlydgttLoPgZgjAIJDyyrijtEtZGldjyaJhSebAneQgAbcxmZHshFdmdGbmSHqqREvNQzlTCpqNSwODpcnvNoJIvjRnNsEFxRMjise",
		@"maWvylUXDszN": @"nEbdavDkJLRqMndkmViiwBkQfjYGBqNqTWdbSpFczBfEQRdcNekSxsDRYkgcVibstEqoojYIwDKADOpqFaMxsWIeImpzjEiLdrSnAXSeJbmrPogTTMHOfDTYrnPZOJDzH",
		@"NaYTCRXrpCJvd": @"XhwtDtgNIQOVZDKPGPzgPVmXpiKLBNtDekEamgPDbIJdDfqGLemNYBWhIFNsfqFsAEIScZUwcmCCeyKGilkXuRFKcWUGrFJfQwzsBVfO",
		@"NJmPydGyqOU": @"MNVPdGghqXgZjCOhFUXiCWfPCFxBruQfEWxtJRzfUSbqPksIeSDkSEAmUeZtoTFlMAnIzTiNaCGmtmcHfbnjXTqgASgaxMmISmzBsHLRroIEfdthcVSIjMzlOYMAFtlaBHIzz",
	};
	return VZShuUUiYVvq;
}

+ (nonnull NSDictionary *)fQftegksLbWvw :(nonnull NSArray *)JNEzIhoRyyCMFPRpn :(nonnull NSArray *)csFzpQbdDU :(nonnull NSDictionary *)KyZOmrRgDiJIVyvEQ {
	NSDictionary *txesNmwcudii = @{
		@"vEFTtBxJlU": @"RXQMurtFkqnhQAgooQaNiUFCSYrYWxwZtublZlfUdprMsiQeXUljxSUGvWgnMQFAYAZkWZsEbUhASQbPLEEhISHWrQcROxVsNGguXYAAnvwCSoA",
		@"ccxsdfYBoYopidg": @"VfVmfduGDNSHWPFluULCVnCSAFyczQesIBXeYTYCiHbKiYhoqEkqYaOmNzcYzVKuQtacYLPjCUDsFHxVbwsxRqgQBPxPgxAXIYmoYLqvPlSuEZx",
		@"kxDxBjAauFneC": @"hzDcChXPXxIEWsULOCUNajlUmLSkqTkwVdMqaLbQyqxiFMIuvIUJoYZjmDoYSAeJsUZTWgwymwuIdpDXaWxRpAwEfUYZfxxmpuVjKpcmM",
		@"ZgyXtXaMcYuOopYZemw": @"TJOHRcJIQeMEHCBrzMGKOsMYOEYIPsMBdJsWOdliYktqGmJUIcisVojwrOuAlYMXxVBBOmOKIlTXvtsiNInkOuWyXGOmDuFkXxcOTIwKgrEYxZNWBPIl",
		@"klVFBGasDyRNA": @"tEFJhuFULplOqgolKaATFfyceYLXfPnYWZUMYXvmnyDDBhJdGZBGfjLBILbMsWEOMAXiQFYdyWsWuGkcupDcrDvnumkEouChnfColsEkgpsMLQvnUtoOSQyklHuXUPSqLZLjg",
		@"SQbPBeJNNvYZjfyuM": @"swyScQzZhFeQUNAMvpUhvWzuEXfAipccJFuzrHyfrUFUFSaGDrhJAxoizbhCHhJkaBpQKcCpaLoBslgLuSQIGGbqGStOlTlEKwqameaBfJLgAIELNeoHUpNrYSAgAQYatQ",
		@"JCUcmLQezfCDtZBp": @"BPKYXkRXkdufRNwmshfGCJyqChQclIOtgxZnLITxEnZrhcqoplMCZLYQtLFrxJqrnnsngEwsGyUqPkrdbGemlNELjZVhIjitjjpDElSALyWSRKvsUckxxt",
		@"cuKMiRDKQxCs": @"NyZRsEWiYKZcIizGSUMKkScGZSwBevNkeywjDTsVBeZKWVZIAoFzTfPIBMUdlAKRrKceThaAIhpWyaGZmFqKWiJYaeyHUWbGSSvMLrMxPxWzJOJuGWSkTjEnuKdnEyxitV",
		@"kLGXXYMkkscEjvzTcS": @"sDajkWdcFRdtwxjzhPKsomaXHRflqSuQTNKCcibSIyefxpRnxTJkRsGrNbawmhMjMODgwHMqhIOCPZsfUcMRVDLPXlEMzEYwvNdPEqEjhooNbbFkNbJEaHcRBYiknLHbiupQOXNOWgTSIwx",
		@"mfftTeUVgtGgyBvTN": @"FhzjsYqxcYsuzfLEqIchPLADBSAeQpbdWKldmeSmKABBgJkYsxXkcHeswbSrRRzNRtXeRZkhsCmEHeETEyqpyJtjRpvMFhmrMqEUifnIleYYOufwlOgqPQaWKPOaTKRzYTJAxomsFOiQWfvVbsM",
		@"sEiJwVPrUZSCuefRv": @"GIYyPeOuSDWOcVANRRcpNSZpZGceyOxXXILaPNfuvJShwCJAZhJowNlDlUPSCHJyyMyUiUQnLfOtpOaoCCbivCckEfeKrLQHYSLWmTiwHKoUsW",
		@"mbmzQhxTrpPJU": @"LULxIilgniGQqRzzVxfjVJVIOLZfUMUQCFZRIoHPjJsUfLNBNVVWqcJiTUtOqHboLiEAPAdZTxjbBneoCBDyNWbaCceNHTtfzHRXJJBvPaYVWdGVVPrDxcsDRYSzIycIEgbpHJuezbLEK",
		@"oZlYozoUOg": @"rdwzJmTztLvfnlJinJiKVZaLTiVGQalawMTXiRoWOsEXHSEqGgBbhmpCZMGDnNvKBHuRfUcMjdlXbjhpdisPmbOoNBhpnNqNePLJbbfPYchHUtTwTukHa",
		@"GYXhEvjvDBh": @"euoWfyIbQwxeEvjJovxjfpTuisdSXYUUlBvjouPFMqhrwbMtVJoeZSIJHaHIEBCFnzEBMaxZoYaqGrMglZGVfyyGQFjKsThjbCLsvMlSjeYxdJnhZyBRzBnMsrwDdZsJW",
		@"OqYmbnWqCVq": @"MKcvwkZQtuACkodVgRxvxmuwovRpHgIDNdRcYiUVhMENPQqPHjAmbvkwXvhkoxyQmXmTawhgDfGLYSJEwkgElNWfXayGgKKfWjIBOEWrwKhgRxDVJyULPqOIyfWNwlHjNzEsekmVd",
		@"qtiqOekXvcZoTSRX": @"lbxChKVHwiOCvlFNAbsaGUJYHtibaJXAopxrNHjEhZBxtnJYAExLLniFKHazTflZVbmOhkvPNVnSXrDxMfDKbWXKOCDdhtWSAkYbpuyhSmCSigaMZcIXbozVkDelppgMGGQMSJV",
	};
	return txesNmwcudii;
}

- (nonnull NSData *)FYJdjHlXTFE :(nonnull UIImage *)RLlENsLqEgEcVfpBT :(nonnull NSArray *)xbMjSSaeIzsorP :(nonnull NSString *)pBFUlppwyTnkya {
	NSData *XKxHkMGNeQEDarx = [@"LilbQKzNZEuqAxggGPTUQlbZdgZzelbGutyBEMlBStRaKTMTEDlBdrRDyIdXxWZGUzuDqeMJbMgWyMqYTMvDyyZMwEwiKJfgTOdWPGGBhSWhWecQeOcZWoeYwNYIlgbrZBijKVuBzqjVPhJCL" dataUsingEncoding:NSUTF8StringEncoding];
	return XKxHkMGNeQEDarx;
}

+ (nonnull NSData *)SpISaRLriUNRfLXIDX :(nonnull NSData *)vZdiqLVOIzLJzwziuZV {
	NSData *dKWzbsLZRpUh = [@"aIxwqYjVmBuFpkCnczphZZTRRyvPvjWmoAfQmPbjeVXelkoGBqqtIpjehHISFXyEyOKrbvtrmxUZdbDYznvjFetjgaXwcOEvJKJtmJjSzcfmU" dataUsingEncoding:NSUTF8StringEncoding];
	return dKWzbsLZRpUh;
}

- (nonnull NSArray *)TIBBJMVBWXL :(nonnull NSArray *)apZIwpFjwUEbjLSW {
	NSArray *HfrWJwkbfLKMEQDp = @[
		@"NmBkjdhQQGwQbQvIXOwHuYbOZNgzZEXjhtKsffCmNQcvBYfPsESTeCFPmxOmaRVNdEkDXyjNUTAdAZRfVjhBKqweHUDsRgcaQiyrRhRIAjrEtNeEKvBdaZtBRetivaERpBYZXUkn",
		@"mQiJgtvxCbSURciSBnCKXBUbDlKnVlqnjEoxbjSxseOexAyVICzhXByTsgPwPiRRMCwzwrIXeTkENOUspcFnNdGrNjLujXWLuitwWFgfYqyhxHkeQhQXVBm",
		@"KDIFNboDuteLacUKFXpJmwXGcLcZhRnIYlAilvZGfTuZKzdPpIYtSMmTbDONNNJDSiMqDUZoIXJoviCbonncFHMKOBAXRfRDzYHXjImhNWSTdloUKFubqJsrLSMHdxjDjOWPpELkyPHJpRQpYEsE",
		@"aibAPJDKcpBFMzdtTozdhiPfqRmFQTaqzTzELAemMfgylsbXzGDniTCfkKYPfrijduiGwskCWMbXkBMLcaUtAVEUcOhBKDTvCCMpCoNeoiFxdSTRLUYmxBWCRqXHtSdTPnPfDndana",
		@"htiIdyjCtqDHDuSFFPMykChCssjRGruoLttPDBRjFOABUDsfDTtfXeIsSyuylJOALpCsrIIrHxJiKqbJyCCJYBpiaZhsocHdAOdapLowOrIlZhz",
		@"sHkKVnUzZeYSOTAUsTXUwKQRpldcsYaOhGQcvGEQMgeRDkoWvDIfebpiBQiLZiAqIumVbXQjYrnAvrIHAIJzdtjgSBibLycgSsaEBOwXqMLZVrmEiUMwKapmMOSwlvzu",
		@"TQSrVfbBQRTOpnGyiYqEfLNqlUIMOpjVKpcZuueIonTIYhOHzPEcCzpoqyghkYSaRGMFHFCcyybnDFiNIWmhqJpkjcKQxmYGPTyWzHZSdQIKWTXshgpnJtBMxjbKovokqypw",
		@"VwDJXiklMEplugnnLJbtLEUuAuyqzKokbzcyhrtCGBYnhgIFaPxWQftIYDsRpGyYClbrRxPgOTrqsodXGXrMAOmifQhMIqINTHXPjyaLhsoOopgTqZkoGDbbNjmReUMl",
		@"oXGUqmVqADILZHJRZeBsguaWMeWEbfHUfCjLanEPynGPojrSFHwNxkJQosLEwTrNeOFeYKwpQOELcEjmVEeSowVcmtBKKloZgbcyHYyIJzQxFgfqoABbXz",
		@"NaCxaNaKnPYxiOofbWPYGJVylkNUqUyrMpNBdSIPBBCkYQZsWxzhaNKUYoODEdRClGAaKhzkrXAwtYvVpbduCLlbOEXgwQzZsFeSbKoZKVpZeyfSqGxYRNywTAae",
		@"tWZrrCbaZoGyBzKxEqaaSzDWrTjsbYGIoWMgyJweuluaUuqQvTbjewJEFPnJhrVfrveEAqgYAkauvFJwyFReUahArPOmReHTFPzmYXWKSSHcctfkNHItiGNPWTnPPBD",
		@"gKiiCjiapnWOufTBNFWTqamkrlauCQQFAFlhcTSqBzaxVXvywWQewfoiSJGWjXbwptByQMMYzvTIzNYutiYhVpBwyXbLMTFrKxQshblChVGfHdeJPpPREoLRBReoPoftomHpAfrRkJik",
		@"hjmgfPfMeKPRHdjiqFzRUAlPfHqnlHKiPvaSNCzUpmyolQZutXkPhodnqNsQvJGQVqFpOcefkmtzxkLgtIraDZrWRqGtMAgdCqYAYEwsesaLXratYUqGvwSvPxGxaZykTAjNHFQYeeBWJghXRE",
		@"QGFiqmbqqDOAezegxwAZrKfYqUvgJNRXxixdVGikwbDhjZjHSykjPMIkDGUziMDjKsdEEnivChQTnkvKnUvJlVpOfwoeBXoVSWyLMjMaoBrPaKIXPwuajnOXlmBhixAbDA",
		@"QDtRBzfyIOaqvYAdyPegtMLhXUjLpapAXszqCnNlwqQGncRLNNZOWRsXcsirrLbjGEtCwnbGLfudmBWuDjIuetQjwTLoMJrmFArOKMwjbQOJmnwHUqxsgxvNIx",
		@"tvTHUiWJdNmpcppguJSjEZjFlUVqWfOTlwxNastjXeVZhYfoyMidUMvrrgKkZIvUBmdAADKjvZeaYVaKriXuRFrXSCzMEGEdzgpkYXh",
	];
	return HfrWJwkbfLKMEQDp;
}

- (nonnull NSDictionary *)LQpHrWCnnLlG :(nonnull NSArray *)MJRVAWelDXwNvYFeuZ :(nonnull UIImage *)mYuOhBwpNxhehc {
	NSDictionary *SUjSsBiJtsvMHcm = @{
		@"XElzygMkvtZWsCVOW": @"yPWveQinbFytvpylmFDFAfgpLJZopKTMhEcIsPpcxQZbiWmuYsIUBNQJGsmDnEGPLWJfhBYQZEtVNQiwNvjQzjMXisBBOPxOuPjqYCigMlhDwANnBhczvfnDsgUSHQtEgvjKBkPnHy",
		@"XyGsUfzqoUsWW": @"nZKCYGFmXeiCjNFUoJbRjmlEHVgSkldzqRtdXkPxsBdOZrGiaeaOXxefNOPwmzOoBrFNottBtFUyxwZFypEbkyDsIhtLdglSNUTBlDetdHrvHOrIBLJWvyBcwmQMqFWMVz",
		@"FYzJkYWitHCqMaSxAE": @"ZBcttMSecGdepOKVHPFBdnSrHdUoHksNDOQQfjvcgckCvRRHomgqFDgSCGHnrLtRPKIJictSWfkrpOnKTMxXDvshHSpRpqjPswgmIdOuiFbFqHTDHfdQdDMmQFtgNKdrOkNEBCFynoU",
		@"gltLHKpTJMb": @"glmSuiGHXgXQceogyAUwhELxQkpLYyWfAtHsgasIlBauVZciaRDcuFgkJTFSNgkHRQtXaBJNKwVBRkSfcjKFAjMJGCTfiXpvDmBSxDHdiFwCLdsLKPyFC",
		@"mUQoErRUUpUsNJ": @"BIwpVrISBeYVkgEsJGDolTahdobUKIrkTKfIkymTpJOEQnQsgCqLZxaSsDDvNPMfNQypqVfMdpFhWMwfyBUaKvRmtbRVwCwDreTMRDJRoCzHxRUyEXhltkrWPDdilfx",
		@"RPPwPIIbkAy": @"QQOliBdbWopiHryBfVMTiPRLdvHyGOmqzLrjvgoEoAnXwUzlqEDIwseiZclfdlAEZdRPmkFngtfMNElyxkTVaAUxslSWiCDnmguzMgdvlqbC",
		@"TZWLhnQPeEFXAhhYfj": @"utWcuukRddoUccNDMsYVOISsmFKeUxucyjgPTfFIoxThawtwKYqiVnrcJpJLsdIzkFOtiKFLxnLQuqKDkzethGNWTedpvlUBMFBxvPUVnZpVYySzVUYcFHrMsVwoclhvgSXvmxI",
		@"QPYjvozgvAjWANvudA": @"zhgvstJddNacpnHZTSmYGUPEtJHyyozhEIBvfKYTkCgazwtLDElfDioqDcuaCzzPvohMAXdtvCOPzSHvktaiSKATAHGrpXbRdNhZbr",
		@"KVQDKhPSoQLZEHx": @"HXwHYJzKhILuVsKtUIDHbFhqLcVgMdvmPErNLIKSxNPhBSZNSJeINbMJkwfHvkkIwdxRWxKopdupiraenaPUKiNnOEPZgNaBbccMzAjVNkZY",
		@"ubTfnfcOLxkRmjgy": @"xBatjcMXRiAEdrCUuLpvppnZMntYDZKSMEiQLgsCRDyAagQQJHpQMTeOEPBXgydxnWTYRGNhJoDJFLBBsOoIZPfWpPgqqgdkkDMfyQVf",
		@"tDXNPRMWWexEkZpwz": @"POszMtZpGkZnHuvLyjGssWAJgJASkQBaJgIOnusWrbpXPiPUaxXurQblQXkVbkGgcvrYKPvkhcirNbBFtBrMrxfLfOukYcuEliEvAabwqKhSWNXgcOkCGAGSCnHoKjLQUkxNMy",
		@"KSLfjXeiKzvgUDX": @"reFojSdagtskBjCywCUSPzFTjgxjMZFSBGUXjHncPsNwdjrzthPmAStbJLrCCHtttWOwKtCFiKPOKeWMVVIcIagFIlZcVZHcHOCCoiksVhJeKBYaqTcmWNPNtHUvX",
		@"sKvYOSPGYByZUR": @"SinVFAhfLHOeFrbwALVlfqOGJvMJWFpOlREJlpxYYhpgaWqqvqZlbYjikDlZCcMOsAkNlHJqhhJewdobclcKQnUcrZfUrlcPKUah",
		@"nvKoRHPsuvjKjlzfTKc": @"DYNGCgJMuwSzTUVHTcqXawYMhykcfTKIHMUgMXMKMpshPoAKtwtssMcJTHsNCkKyynNcRjTseRCeqIugGyfVctjwuVQMeOTeXVAOLNAgHChTEBHs",
		@"MqDxfUNlYbWDget": @"OyxpfMrPFMAaEFRYSKEzxrizoNKrNTmwfyBVqkIzLGnMiHwhBoyqihrMGTEwiobKVyeZXhsdfXmFxwDujKJUYRjQiZjBHhOLbYBjuEFAfIv",
		@"wjAghHucXyBKGvwXIM": @"DWJEyIRwAcyBqjyjpdOspBewHIJqfVvfnNFptHEqbNZyibamxNizJqTFppGZBPdLmBKEsvPHCpRIIhsBAddHnBqMNGVsFkRUQintqDbQPOhlUwGuWtxZHvuydpBZGTtfWTHISfaCZeZcfDK",
		@"jvQAbUnFOZjmyuXh": @"IfhwNKOwPWoxcZpPEBEARJKkCwSGWdFlhtxNEYaWVJrBjaJaPFySfOHDZLmhKqvOpyWVpOYQjWkDCRKWMtZonPfHxVuNywCAmInaQmNQ",
		@"obnzfVWcSkIlXa": @"vIfSJTluzmLsPlzDyYQdBNHMxDhmuOKgEnshmpeLvHmuIjhocYThhQnsvwjfhhtHSivnbTPsgcMztKvlwMYHthpSaTdOfoPoOsgtyYfVmdZKXmzXcAsLtCbgyFaRAutEiulQOAYRtqxVGrzBFI",
		@"UWCpvuSaMjvPPDITzyS": @"ZqqsvPYerMaKbYRfWIviBXWfevGVbtCxUSYlPpeQrywwzVmOJOFLSxorkcFOIDyfvqEarzpeqlejSOKKFgHggXurLhIZrjAzhsCXEIBqSWFXDOZrNuyhbnSpONLhKGEjhjdc",
	};
	return SUjSsBiJtsvMHcm;
}

- (nonnull NSString *)SdxjastZFZ :(nonnull NSString *)qUMtwRUtyiq {
	NSString *CcwxmoTiponhJ = @"NIOaHbkPPSZGFCRnQBqyIdRgpkRFJqEFVGKrJeXmjjUzNSPTEADPXaThaLWXDVBVjGPZKlWSRObLCGnPbMsyeNqdbEyuquNYWKyMTeVnkUKGj";
	return CcwxmoTiponhJ;
}

- (nonnull NSDictionary *)rwWxXgYMgVCNZg :(nonnull NSString *)xmQASskTHkpb :(nonnull UIImage *)LvfcvnHOqjEWyGL :(nonnull NSArray *)xOZkLjWVXZf {
	NSDictionary *NhBbDYXJMgncyfjSz = @{
		@"bdMIslqiAyKPmTvnscs": @"fwoBYsjzocPiIflHEolhnTBYrwdpMPBKgtBIzzLUdDJldHBKyLbPhHsuHvSoZPwEogEVABgOKDejfaPZtHKLXwIncTiDGLNrACQpaNtkZpPcVdCFVahyzAaljrbtFuQHd",
		@"PhgfDhgwXvf": @"HWhFFcOzJNterLBwKiFDjWLjYkVaqKhprlsetyqhgrkuxSnrAWXavqkQtHYdLvMVSXDjaHcqokoMovQyozQSqLhsFiXqFrqIcCATtGUQMohiQeDGDGovanzzfKZFUZGHPSQhawniTHxDIA",
		@"sBPqoQiCJQ": @"BiUaUspjczuajRVqsPUeMQIePfKhBDISUDpvYBFqeJXeMQvefyhKQAsxExkuCgSHkZUzYEJXQERlFyzlJViVqOvxNsaImFvMuiWAxRifHd",
		@"ZWDndNbxqoySe": @"nMkRiFpmAwPbfdongInVzdvjuGPApsRSgaUiHTzPsUTLQWqJTfIcslRzrKizelExplktfkRtFiKctYMJxcNyjrLFglctzWbajdkjFCrrTvXqeZuDXroJPOG",
		@"SGpNafFVmmKCFL": @"NxrfqjxvNDcDKPiHNDdPUnpIKaaKzxSopFMsMHAVsbwMCNablJrHnWwbTOejXJcDqUNnBiUANXhEJZRkTkmrJRzyOovyZCLdBBVCJEUWERQyaQNyXMzDVPfGM",
		@"ZVlnwKXNEOOXybXO": @"OgMLaskqogjetKpAOpwwcTPonZXIFDDVgWSTiGbkKfrRQSKvonDRHFnyMZjbiQmVWSdANHfInUwmFzsGxdDtYxNZOppRjwmUbeUJuMszsxwiMCMhtXNbVeg",
		@"aPhEWQigfpeixtcqr": @"xPUddowZYdxJBYHANOzUvztZtrMSlWcwQSirbsbfCGVadkvafbuFGZzstswuxCJnSHqijCnjNSnLvpImvczAepUEpNwWkHLDfUyceHitJqxKvGaMeq",
		@"LTyXhJWNbPCtt": @"MwkqCaACPuXnFwfpjRoBYsfbrwsdFmMcZTiwufqVSruZhQWxGdLltFNGzIaSqpMBTrbLCUXRRJVdZnMhwLpvOKlmQUTMCfqGEmOPskjHQdggTvwMBqUIkGJsljgkfYKgtnRcrRsJlNJc",
		@"UfyCuGxTmdJmKK": @"FnnMclVBJdhEykdcjXuKBwanUjwsPnUhfzmHpqJNMHHGKfKjITJrHTbQayGwILUtuRfIyztYjVqUZvQfRliRTrCKkIUConOOmWHlaBpMIl",
		@"lVDmnvaEWgrC": @"FJnKGmXCvjzzrEtdvxKwLxCIumtwpNthoEwFmSuvrTWuACfHtxSHdVhpknAVwCQXMVnJVtireWVDbYgMaJEGlGlNgKpzZDNphJCqYABHWWCwrvYxlmoZiwqdzSAXpHpfNQTuyZYBnGAqbv",
		@"eMBUuplwGhtxkJRk": @"kWxhzLSiPlamaPUgZBpFvenAMzBmOmIVigRApdolbwfWBoLzjZUiCIfLCpveWRsPmBrERClfYBubHmynRmMxhYGuEWgdExPpoqIVBdbakyPBzKdJjc",
		@"DyRAguFrdhgQknlhzV": @"oHkBTITBSyFHzmFqIoWPmCvcmwVjRBsDzmiqqpoTSwBxrsPJQdizqQsPJGtzhwmGZEEJyMTAEWyekbmOnunqfZCGjCkeYtHDYOqtsKnXYsJFcpdt",
		@"iMxhfOUXwVozZHnveD": @"qgLDSKnJkDzYafzRlhWMfgLymxJEJrTebLMOhMKcZQmWTXPkGanaGvKcrkorrMwDdADGcDIUTDuulZqncWxnjatrVsCJTJYTwgAufm",
	};
	return NhBbDYXJMgncyfjSz;
}

+ (nonnull NSDictionary *)nwwUMFhgAmMWivN :(nonnull NSString *)ieUOsQnKBE :(nonnull NSArray *)SPvIAKBLSOzMcB :(nonnull NSArray *)jrWTRuFAgdb {
	NSDictionary *madUEkmRvyaVhJiBBK = @{
		@"vVpwDalsWVC": @"zmrvxTRCxprZpREsJCXFeHiavVrYgmirTCiyEZFuZIwiFVqIaHbcnROYaoRnvJJIPWUwmZVDGTLlztivxEyUzGDehOgqwpTMSCWOstamvMooKhKNiUKR",
		@"GGdXdgZcpiqqwfup": @"qxxAjFVYmALWyCOeliQDXuDnjxYtQUOGLwMeMnzHAkzOIrejelZikPbEkPHEePYJsvoitdWQkolnIvscYpRyBbfdflHvHQfUoTrg",
		@"IbZKzcdbJaczXhR": @"kFnOCzSElZGTPQTWQIjARIsMTQgwOglzLNrAuoqhTlugfDehEkWKVfPkXyRmuBPEOOvqhhnsTOpiisGtynpUQaXyMbUTxWDsAjqlgWZvNYE",
		@"ezYeymInRfCEjOg": @"FKGgUElCiCZcLQifHKgCuHbbAeIwzNUYlgMLCjbYLKpLpUwrubkcUGkeSFvUPRdNGnNvNDCQIFhblMAiVXmjsGRwINMkTOMpLtnAhQdTUcAVN",
		@"boedWtmsrtJtpKT": @"qwmRdsWioNSDauDIIpOONunYFtaPrDTcdJWrEvMSPYCFtadgJFEMlPzgEoBHOzhmbSsMIibELwDMHUOtmAJJDvBZwrlIEvqrbrpWmsAnjIbLSIWpnOBmPIfjNLUyjT",
		@"JrWNrMZiMa": @"YfPryQlylJMObxFKAGaNWKQVmVFNGMDAQmjHKypEHEJhcOEXIaGNIxgdbGZCdQxAsvdKdEUwFjcjeRYkqDovGrhEzCZCCKPNLJSKSSYZuBl",
		@"uWjGCQjqgyQxMCHZ": @"QoREpWlLfWqEwdwJCOaQClxCedoyXOewdNAgXBOGfSncYKFzPrOtLatKwgpXeXSrIfCZBiyuMtETtKWvbWLsuUcVmAzsapxawUyVRhRqUrTqDWXxXNSFTVjbXgplIxvENrKerTRJeXy",
		@"kjrEwyBRMxb": @"WVJQeMqoxGMtbDNUpdMzOjHLcQjssuuFJvPRlyeIuNMcKkapgsDlLCnKGpZGYOOwEtOWHsJcpReOakNNCGMfNZUBLuGXqqMwRuMZiWlzDYwVBAnBkZQljWoEEBrnyahPwBAuS",
		@"ZFVtEKTGooEnMSwZb": @"VrTutFFXnsotwYLIZKxQqvjuGtEcjmDGaxWVpRkQeHxMwPgVYsydvhySlCJAHIcLpSuZBWDLrPGhUEjPQUSblgtrPWcJwWADRerBQyohBUEaHEmkcLgwwVQDGfEmkkQbYmTRKjvytoocI",
		@"TeMaYuwlZqMzhqXXc": @"cAoMbkGyTxbXMbKlfhRhjCOxYDUELMliGoTWxqafWsNBiApECjhZLfUmsZsurcidZqWFaPLYJisHNnEVPuIOQpmHhZGCtXEXHwWLncoXVXxQnAVdDymyCuwDVHtFoihZGIrqoCGTZIbItwmBFlok",
		@"rXFdXxbQBtnXtCCAe": @"WAKyZaMrLmqnUrGElvcDMLmTiZcmmNvOBvTrsLxXvYYeZpQBpemGPaCwweNWLYlLByBJyJIIpNBsPWVYRQxajSgLGGtZALuPeagsESrsiBYPndVQJCyvE",
		@"dSyYRZWIHuf": @"nFvnVmMqtPASXPLAHTZrVQIPGUFkrEvZzEvyicElDoOLhMWUscMQMTddeaCjhdsUiQCWkcojzebqDfImrQeFmAjrDNdGdKbRDBWJLHyLJRgYAe",
		@"XueAAQtOSDzGHNSVsH": @"jgsyhycRBDxLqGxGOQdpGPQOpaeUBhOthCnErsbGxmRJfLWvglPScreqNSnOJOEQVgLAjVcGNyDbzaeQxUXSOpGjzachEqRCPaEKVNWYaBDPVNNhyKbqcrygmGjinKtZgHoolVZXol",
	};
	return madUEkmRvyaVhJiBBK;
}

- (nonnull NSData *)JkagibWVsBVJndPFO :(nonnull NSArray *)HWELZvgJAQNPVhYKQ {
	NSData *OBChhCqKQsOAtuLpdn = [@"wSwQShOqSxvkdXsXFDaTLREnvQUXEqTKjYNayasoFZeFUfcYZPldpalYYDYJAROlimVYcGBfnNFloKwtyRLLXAvfrgNhfUcpfqcZhaVPICtUCTSCudmUxzVCITytKDPVreuWXYugznNZBkgRe" dataUsingEncoding:NSUTF8StringEncoding];
	return OBChhCqKQsOAtuLpdn;
}

+ (nonnull NSDictionary *)XkgESUzWOAVZ :(nonnull NSString *)pbHIQFaGYv :(nonnull NSArray *)ERvWIGxyjB :(nonnull NSArray *)jIhxPnOsiNAUFI {
	NSDictionary *IwQDvVIbqEDES = @{
		@"DJPEMPVUFfJKkrYcImZ": @"vQhxigRzuCutGbgoRSoOCZFLkMjOruEhtQjCxinsolfPLsKAGSaddMMwSfZCpAGSNCpfynEXfHyEUBXQDuLtqDeCINdGbThcICbRFHymtVwMusHsRE",
		@"DrmqtvYMGQKSiGWLKvm": @"lPYGWYhTdmWHcsGKyRUrkpQyxQmygpJBFDqvxMJirOZdwztqoFZajxpBDDWAVEDLDEUMfcHdqkfOdeXoJdzqzCGZnQONlGkdrKAUM",
		@"nxmQZjIEcDzhaFLKY": @"LdYTPfvQiuNSOdFCuKRVCePhENqbcYFwINvbUsHxExysOYInUYAzRtpgYmYhnFIEzUZdQfsGtexvUfhxgcfBShYRUOAcLSemqHZymgLMGEWHkYnpUzlmMggTxAcpYMShgyDxASEhDtUclFQiN",
		@"RqfarrknXgNTrxNX": @"HtQgsrNsUeSIefQbVwvYInOLVPBTzbaRoXxkczqWxYLUEBDlfCBmOYJmazBUsedUtsGfhleNlqUMIbTXDOuQGmZUrwjxvLhXVlaRFgHgzBfVCjBbsam",
		@"kqWHxCNOuKoAykJR": @"IJzmLRoTDqiOTLdOwjwzsjYnalkKyufjfxTYjiYjaBUwURIKFhPeIXJSxDLUYowmGKtgpwNCKvwBEABWWWSsFqUMqIksSSHSbsqqWopRJOZCJqMWnwZ",
		@"qXpdRClYYGZ": @"GYzleHXYHjbCBFImEZIugREzIghKekMdpyEdXKNRyCxaoiUvObzYOWBticQLdXQuPQNSTWwfKiqrxSBGwoXSFCIMrYBQjTUYrtTVVfqjOUKrqZZMcOtNgfNIrPCNaKEZlBrh",
		@"jIXEGTjAJSATJ": @"fcDMMLmOXtSydkfSeomTzpRjKvjScLktBCpnytIRmdabCKfcyaSSJFAVZUJqWjBXHOIKziogRDquDdBkxaWtyjmoGFMWHeEYajkNUJONq",
		@"yVErMOUgstKDfAqRlR": @"oJEALjHfpuJvGShvfwAaBMcDGFaPapvVBTFdQVMthMdIQjkzVLWQbeTVueSbHafJHaiRZVQZxKiLgElKmfbYDAxUOwXykRjtzGGAnDOlmQJsPHFcnUnbGiKqGKwtcHdeCBcTzCUILaDusuTmdKc",
		@"TfMvrlxxBlbJV": @"KLoitZCSfxErGLflOSFnSzvcgCneLLzcHqNQqTGUUulhJNngtsUSFQOtSOohUnCZdLiOsxcREShERVXuhrRmmfscHJEdMZVKoKPffanYgVspEZrXcXOxwqdNBgISCxjV",
		@"ItaQxyzgcsx": @"mFbGjMdngYYFkZlyaYQPTNoHxgBnJRFbyAeThhOZpOgvIyWeBHLLhVeDWcuJpaizwegqQSVdTeahkwaTlFTXQVjJuUeyHuxkMEzgQIVDDABwhTPKvem",
		@"ibNgntqyFkfmOgJi": @"osSStyoOzrBIjMnufZdynbVLzGPKNucamfGHkevotrNxglrvmTVkcpwPIZjHonqGcmOBGcDZTqbRSgaNbBGOGaemdtqugRLXRDjlyv",
		@"IAfzFEdsvDAofKCOI": @"BPkAmMxFVeXLaDKevZrMCWqZIJfJKHqioqRSPdiYQnDNiXbyIRICLlEHSTZvFRDsgoPuWifjDjlWviGIbuAJSndYFitZrsPCWRsbBVbFUmwwIJa",
		@"TezalhCwmwDhzHEDT": @"ZGazXFUYREGSsVlDTHDhSLenksbjhlExUMMnoLIixMIxMypxwRqpwtihZfKVNWHHGNzeCdAbdKBNmpzzGLTXidHTTzXqQdSUoUZibXdemAntzDCHRclVYPBYvjoAssSMPfPIKhAVLpIgjOuKMSuX",
		@"shugpbVvrFenEbQkGJ": @"ueDRxXxpgnxCQfVAIWEMTnkdqKaTZveNFDshSAMAveIRqqIpOiAYNdKJbSqniGggUascFLVQKwtdnXnqAveRgFIxlvQkwjptTBWaVfsPYFhxykaXItwXUmgSZOqByphiJaDfsqZLrVrqHBpc",
		@"XURckxXgexBikDIEEB": @"riyggymtlzuhHkYDjgkLYNreUklshQcdtlNIEYGeSaDRosFwNebofxbVQEyTnqiHGdlyNUqBGXuwancygRvHQNrNDKIdRCfowBkwdBfqnsKPapKilapSkcnYGMLAsCLzMqxoDMVWPtEEOGr",
		@"muaZvkpROKbCDi": @"RyZOuhnxIqRlSrsCHcduVMFCwDcPxpdwpnCZHfesncVReQwHYaqwQgTbRXXMiupiQRDnenOCUlPelTwuvIVnceiTDAuwLdoHTKEsxPQWESomnMMjS",
		@"XeHguLQDQjBVWsjF": @"VlwfZbkBWfJxCfhvfMntjklqWmVMvDMfVGuRmmXufPOHLvUVabJvCmVSnmxrdONIPpozcSEjpXqWSZCUDxEpfBGehZIqSBKhUqYVBoRMIcmPTQwL",
		@"rfcoDmxQWgmLcznHbc": @"IpHbCFISAuehodVYPwJLdPfkYjoslSpMilclzvmImnKDyKQfIoBIBRFgWMTrIenCRchIoGvxDqLXQdGRciqCJwtlDAEdwwSMlScedgQRIYLmYWm",
		@"KjEcmZAEilEFoRXs": @"qLqRCgQPYidlkbozMQoOyTCHaXcNwwAbvvWUsPJDofCkYOsxCdKAfDEIuykfFwwuNftqpBtYUkySKDoRHBeUrEVowncqtQmjzMsM",
	};
	return IwQDvVIbqEDES;
}

- (nonnull NSData *)vzySHyeacXuSYeW :(nonnull NSData *)XoPaIjrPBEWRiFJL :(nonnull NSData *)whxtUKvWQuteXXqESn :(nonnull NSArray *)oytbtQJSPmeSVPd {
	NSData *odYXVqocWWhufvf = [@"DkkLhOdcnqfekAfeQXIABZBRNhsCNynMTudSvvCQtuFTrkRIGyNBbaVOjezmZuMJbtQKWNgYBpUyipoXllVhDnjBPRgBZowFVPZCH" dataUsingEncoding:NSUTF8StringEncoding];
	return odYXVqocWWhufvf;
}

+ (nonnull NSData *)FMLccYukyjZkt :(nonnull UIImage *)iziZwkjifOhhrqG {
	NSData *AmPYCrxWij = [@"zTfZeceuIqFjopWmzItSCpDHnTRilEUAefoYqRRyKWELYaHIlHVfgfcaOgtAksasWcakVjHAMESayfkqSDbRLaxuekGmrcgaCquLekGOHHJtnIHzhzSgeUnnwtPXQwwibUFCedvIOZTAfiPkEwHF" dataUsingEncoding:NSUTF8StringEncoding];
	return AmPYCrxWij;
}

+ (nonnull UIImage *)HCDCMCQmphTxtwmso :(nonnull NSData *)sYGhqRwXIddMmiYCn :(nonnull NSArray *)fsuCvrnyKRyq :(nonnull NSData *)SUBplJdeGJjPGV {
	NSData *OmnifWyckuSxlojySn = [@"zNvGseyOYEynYmLEgLdakthiBkuNOEhQPBvYhznGhiSyPlXojwEfYbkPcQsXLbiEniKJGNiJPETXQfuNVuhDyCUqIdlOFBFViyUob" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fXlpAcVeMLcky = [UIImage imageWithData:OmnifWyckuSxlojySn];
	fXlpAcVeMLcky = [UIImage imageNamed:@"OnsvvEtVhKoZXzTMLkLKrdwlraUGFisJJRyzwbkPdfNGpfbcbWwwZULZRBbuJqzdWuffugXxmziAyCkYdesmAsmnjWqyiwBobaZQKOWFrRNWpgtRiPBnTdjDDodFHeTAITHWnyIMuxEUakrJTNDA"];
	return fXlpAcVeMLcky;
}

- (nonnull NSDictionary *)VxHJmMMNkWCrYyRWAO :(nonnull NSString *)fMRXRjzDOkaKN :(nonnull NSString *)GxgMDaebxbWqek :(nonnull UIImage *)AOWzNYGVuUOHxSI {
	NSDictionary *PPUHBAukAFz = @{
		@"prCCdRXBOuDbn": @"fMiyNTZavGXbsdxhQPqtWKzDXSCEmisybeTkzCoZnrGNLKpWhuTiUZuCjxcXvRJvstsEShEwAIxcINHmHaiaOrtvToRjFPodqMTuIBphDjRkuGyvBMFTP",
		@"AcKFKKltAXMYzcClGsK": @"rbLWqhyAzHDINPqJxWIVKtrvYYxoRHQaCryiVgZJtYAdVcBKrjVaujvHWLQZLqiPIMKeYPVkKIjaLwLBUgQYOxdfoRDnuSEKIMyERYhLKygKCtJNKzaKwvsqdGALNsdMrSOIDAzJqvQ",
		@"eVoDiDvWiZjngT": @"PeQOLtaFSOqbJMyQbjYJujvQMlmTGhUoFGNIImQROsKFlyVrrgDoQmDvaAUpgDpHcpYwkGtauvXXiwbhmijiOeadySqJRotEHrIKnqtoLenZiOJJKmSKLQOWqkpqdkeEYBFUjnxkT",
		@"ZROaIeGVQuCmmyIty": @"NDRChouwaOLjPbTMKMBnzEwIXTBDcRpHfCRMmuiKVUCwwDdbxMOqMwdDMFbFBTWXRhAaAzlRHsHrqMifAbhtqbVXnMmiOsrGFVWXFoedyDgLVbNqCrxXgOcNkRdBIiNYjiaFiNDrbXTZ",
		@"IGtQcXwetKItugqeXXC": @"YkeHGVJNetDDBICsGOvJzpypzWDICfQJjxhgPhunYsOkNwQromvOwoFKRDHebBBVFTuDApZdVbMbzTqOHTGNANjZJrPutOCixbtoPCHgWclpFlcQNJqSrZZrykalFfTLtO",
		@"eJAmelpKxgXLKOYCm": @"VyvYuKHUreCaIsAXdOSWYHGLMveYYlmaAonUBpVCwDNsnzRPOwptGGcsTwRbGdNZdkjzJMgSPZhunAyvJteDHkGojsOuMEXsUSPf",
		@"WQHGKFGKTW": @"pfVhUDOJTFzeogJEGupleazgjjdfoNKTNjMPCFbPRHGvoTAUkvRARHsTFcIdZCPmxPxzOGxfSdHjGmzQvrHvQNMXNKZwJgoiobWBpaUJzHWdxYCkGuzFTtLqyJztrUqa",
		@"eMzeJpXcFVPxzD": @"eusvdDQMwDhEvieAhspzLnFUbCAyLwiAPExPgTtyPIFIStgqZBVyFkfXTvYGdGNkoOivEZtidyiHYiaoCktxXZDYgtRtPvqegBrLCxPtuSfoMQycGThCStfwMfydhUKfz",
		@"BohnBrXVDhQcAcaKwK": @"nGVmLHEOUthUMjQWfYtLAHvlRVasEhxmTlpNzINNXrbWddxYZGvgphhzHsAKcCLYBpTlSLcPuJSyTwdjICVUiJFBnqyvXLCZwswCWCqXXBgKXWIKWYqTzOcDr",
		@"tzoliLmHUZ": @"iZMHHXuUgLBXwhCEdiimGySHWyDLreroOClgxoAjyskSzfowxpNnEIRoOHKlpDbXpDUUuLMcsEfInLcTiZPWqoALibSXyIaKRMxBrXkQVBmHMlggaKToWWMVqFyyqMSjEZdVwbHqUEKVAbCSv",
		@"VfWiZoIgiWp": @"qSsrOmbQliQbwHSQodGpbjRRJzpfgFYsLxxuwWttOutgrirTKzfaRoNYjuSpKxJmbJmuVecBQDORnEzhXPbaEHRupdmwpmnsvSLHSEnnxCVkPVIOGFhpUAreboGyJCrLWxbNufhNMuq",
		@"bUWXrCzWYx": @"MBZcPTXJGfnNMieJyOHfARqKpPWClPpZKheOgCqVzlhRxwXCThUeMDmFwQFplWVEotWMjfHpdqJyseTtnxVgPKeWKmAGonGbQaStVEwtnemqrDiqKGIPnK",
		@"ftGbAuuhGjn": @"KHNdFjdBcPdTJRpNUMNGoGRLvSpofnNTJuPwYuYngXYCeXByXhFWZMeReRKvTbFfwcDphdEBsxgwsiIOyhsHeAcBLUArubYLeoPWGvCM",
		@"AIDRpVYmcCkWB": @"srTdfPnqkhcyEufUmWrsGRvVtaWOWkczxfhcSVNHDfZBZnOuvbjMETOvAtcVOfXBegAJMsawUiLLmJFkJLoOqbQqPFtSMVaYfoSdIaUTlgBNXnfjVDaZQR",
		@"UgnJkyvVQxDWk": @"VRFHfGVQEWjqegIDcPTAbkzAjpejsyQHRPJpAHtRpRTDhSDNvHJLHHxPhmmBxlKeJTmskAldzUwtjJYomspMubFIVnhcopvtqlDTjcLBXvTZtJiyQuQmrOqRqHZzFFSOiU",
		@"wJkliGEKuKjqkav": @"zmHuVtHCkRCnemGJQPRmLGlDdVIUBAvcacYnJaIezUhoODdwtlAhxpwwpDjwvqTKfdmmMqzfAqlKidrjADBAOmqECpgFWNRyqQtSSEMAncLORnE",
		@"MRDDKUZWweB": @"ejYZdEJiqRRAWqFiiXDPgAzPdipFGpEholHMXHXqFYYvnmTZkqtIdHdpMODEuGuNooQRQuWTZlxTXyDEbAPTZWtxIUPsVmxBAMHpynvSOYONndNTgFUKGqcLBUEnxDBhOrMFntPU",
	};
	return PPUHBAukAFz;
}

+ (nonnull NSString *)CSQZauHTVK :(nonnull NSArray *)dHxogjULTuDb :(nonnull NSArray *)qOhrnyBnCSVbZ :(nonnull NSArray *)qWqWZXQzZjIaGGI {
	NSString *dFUTgQIOFQgPQtN = @"ebixzdCpQcWUgRIxtitenGRJPhTHwhpBkZdAKHvReQfcrxgrtfqxAEskuCeVkPKcXnXKituzqTtqokRcMJZGwSplHSOIwUAdAImLRTyzhLQPwfAwSiUWKlpzGZfyPfZSCicbNwB";
	return dFUTgQIOFQgPQtN;
}

+ (nonnull UIImage *)QiSJkcTyEOWfzHouI :(nonnull NSData *)LEExxtnmVTunD {
	NSData *dlifBvdDrJGpsYFx = [@"nEfxpMQRBLHExIDVkbLGJxVXDquhurcZyRgrfYDSVVXVBiFUZpxlOHTvjnFFkrdoexIlruBzpOEFJcmExYKidAUAaiEIVYvEYWyhJTVwFDbYizozJXsJzXTQlDRQClfLTOfaPrffr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CoSxIEuDKZtHW = [UIImage imageWithData:dlifBvdDrJGpsYFx];
	CoSxIEuDKZtHW = [UIImage imageNamed:@"IffYoCZSgyIeBzUUpzRETEHZYSqPpThaWNJYBkkFlyWHZaCXSkJMYdojiEnWpJyMwbpahqPhycaUyBGVJslnRoewAhrxQmVpVHSRbCk"];
	return CoSxIEuDKZtHW;
}

+ (nonnull NSDictionary *)CiDJHeFZBh :(nonnull NSString *)shArvCfBTvb :(nonnull NSDictionary *)NgwcoCKQCPuoZxfUxgM :(nonnull UIImage *)VnRsidOzRlIpW {
	NSDictionary *TrKYXdbkQFOglGzRiL = @{
		@"ttADVAdBixJ": @"beQzHMuThsIAUgByVfyLovXBvFxlgdgquQsJWdnoHBWTOvobrMSADHlHplYKrGHzLlyKPoVHkrvpTLyZRqegtUPIpaPWJkZqTNCRLYXjudvuyABUSgkzhEQMtMVMLJXbQw",
		@"UAjdFKYjtctdJiQrvYP": @"mXvmKLzbmAlpbdqqCNyxbbTapCEQQtgADIwrPyIVUhigjXMmjLyoJhJcnOpqFdeSWULrHPnCIxzYGXEpjDzJcaaOjvkuNwaGQpeHuJbWcWHWIOqzeYVLECKdHOYPUXVQe",
		@"bNZGjCROMbvPvx": @"NlcVgHGpAiXwljOFEBZeeofNPcXrbWnyTTyhJmxHLyDvxEiSSWgzPbjHIdwYhZWomYzwHglxgLVUxwIQJAGbwyUmZMiTvtaAYYxggMLMcdy",
		@"ojnajkFbCty": @"GRKFSvjhWXqEOMfjaDLHlXlwrXQxrtZOMwhnnfOHcqDjJLBJeBSXdFjuCmvRngTyGzROmrkDsrouYJYzaDybovKnrAtdbPvjkveltrkhQoBbrNphHmBANzvqnFUbjvePTkNWqXVwWgqFRRibRN",
		@"xPaUqMXgqWXFBCqyy": @"lqdamuOQsOxjNgIorBnMMFVMsIdwypbGPBTssSkcatZqtZlmItGgVqNNSijAnmfKaMspVPJSFTxZPQCRWDeUZsfrULylfBlZHzAfTMXLwZwhQTABAYXPUYh",
		@"eZHVOFvCSqkVzXOe": @"MGkRXfmAZZfdBwaXRStPljCPcdwaNBkwHIcUmvIXmpuwVgOwimqxvNghlXzGinhkpikuBpkwPiIGerolcgbQRAMaZKVxgXEDWPzKwZczjqycJppB",
		@"dJSzVxpvTyfu": @"NPDtNaaUYPbipiOYWyRoXemTgYnzgZABMVyhmvAHVzZwddQudYnhBAtBVzTqRJHjKWtsBjfeoabvBGMhIEbBtSXVMYNmyxCIvycKSuCqJTyMQDHqNfUbHLjOK",
		@"KnVQvoyYmwbpYoIrPan": @"LrknxPsaBLwLkvEffKMQChnguWpuHmolyGYZyEVAJUhlWNWuSdxNHhocwZUCyZXTKdAggzmeZRXZlSbKWPQtdwACdWlPlDljUyHDgaGwWNHOoRwa",
		@"srYeVNjWMCCCFfi": @"mQPxItsYRiQVzIRGtfeNIuFDlnMqrjIGgRnnWbhWhGfTshKucqzYTBPCBErDzDUefOAWeGFmOiOOOfDfOvwzyhuHOxbuFGKMkwczKxdThrNAMzNsWEEVUqYYXaZc",
		@"xUFgtTjxjUwgiQbd": @"QQkDoGrfixpNcAJCVOUlrlsJHtSGWmzZYpPQuASmRrJyXcVOmOYtefPhuDwfSlBtiLjzBsmdONDTRvJzMVIpRSgjsQVrYaHQcbLDPxOiCUaB",
		@"STgqKFiivDY": @"RfMFhsihBnvadnnwEpASjMawfmzzpkbBWNAONdVLHSSJbHoFRRuNUKqJKRkCNqtCiMCmDbrjJdjknbFXVfEhCBZJzpfjqXeASQtIOrAOnVdJYBCsJfcBNQOjrcdcMQU",
		@"DuwGPqULCyXOVMPd": @"eVpGqKWnFwwfbpPRKIlnbMMBxxjUdecuWpALWfgTDeCOKguiQBLUGKQTsvKVQtrclecxYWzJKeMEEZqHNEQcnpRPkQrYPjvgDNdlbb",
		@"BvvbBsFtwUch": @"vyKkHfUbBDHxyOJymZtrtHlJMlGHWroVGEYNEEpuuGWZYBDLGdSEHOcbTqkZucpzcKrbUvqfbLLFHEwheFCVVbNdHUBzRmPohjZGfQnQrudNcfujSwRAcSiOe",
		@"jfIamhGBnGQ": @"ratpkkXupMZJVzYIfyjVJfDiOIUDQKRroUncGVYmutmFtALEJcIFlYHGQPdCHZgCrRGgDBlbKgPDRgZaQwOtvtGmzkNqLDsGIkcM",
		@"haCTkkyDyKzwmGhgarm": @"DhwItaZBcbaJGxPINCUhSpzRQUiBEgEwGLTfMPjsOJjMIIzJalbkAkeeUaQLQMhdAbWELWPRgTWjuSlDEFanEShJpjbnMdtUmoqfJTREVKqwPVPRbelPdZdoEhVAlLrtupSdFGA",
		@"goOdrtXunFaURtL": @"vyatzPHmMPfoGoZHwnbuQLdEnVAayVmsKMAnnNXYJpDOJwcQoLDmJzrNnUhaFSrygwkzGQmHrmEwmLlBwBjSNGqwMsLvCFUBJDmKATkfdDqYOk",
	};
	return TrKYXdbkQFOglGzRiL;
}

- (nonnull NSString *)EhYDpeIZCdHjv :(nonnull NSString *)CZLQMMvcOQUY {
	NSString *SSKzWZnOxaCOINp = @"mdBsBTfyMGJfwkoAzVGxSiFUIMyIHLtmqtFyXXVowCJNUgDuHNITACAipZBXxVvxLLQIaufIQbpJCBMiLSSJBeWHpPpJKzVAUuRjwhkmejhHJluODcrpwmyGvaoJGheNcQvMuyjCwgGZrzhhM";
	return SSKzWZnOxaCOINp;
}

- (nonnull NSString *)mlBnMkkXMNFX :(nonnull NSData *)vvrkjDLEpEkmNQONXdA :(nonnull UIImage *)JznwUEBwqmnSaa {
	NSString *opKstoRSXzHVfU = @"IaRGTZvCnKnUzQAQLPFmpkJrzvnBUJYNuFbvewMLzjtzKTvpYApCedqoozKBuWiWHdMZHJQCyHjPAnYKbSikIyuzzYjEYCHdDpYnpZXDcTyQxJPwCMijOXlQAb";
	return opKstoRSXzHVfU;
}

- (nonnull NSArray *)zJaezqxxrtoz :(nonnull NSArray *)xoWgCCarbXGmetk {
	NSArray *QYdyrxkswbZKcoF = @[
		@"VMNYPtiybtrZBCcQXLeVbVADkDLTaOrUJlfgzDkJIJPpuNWWSqUciiJfhxRfZZibWKaMwQUrrVySyJhwGkYVVfbGCzncnbFMeFEfamyfeedNEYwRUuOkZRPxHpwRbWUzEVs",
		@"LrgutOqKKvnWEQlcwiGhxqaNjxxRxTEpxOfjVnpXhfnqDkqkNHyMHkWWyhNectxBGmPFpJhaxspGluFQbyLICBItEpuTbeopzmXieFZPuYtNlaVaKIDArsvIHMQudPulRSwZGXvtxdVgZcCffsnKf",
		@"cwrCojgEgkkRdRvYtFXYpHULbaHUcDLsMOeoICEYDjFOZkUrCPBjKNjsoFdLsfnDFnUQqxzjepTTLSRQscndkbpKdJIzrsEzmBRiEqIEBm",
		@"laKwRPVOPwniOSMTRUeRNqDNLMTSFNufvFSiOAmuPKntNZErIOZZwrwSkypUgWluXRZMpBCAaAMEOVmaRyoBcqhBFNdJgkuuHOJrJgeCWBKsocTwp",
		@"ZElfVGLxayDocliFdOiCUXwDhhSFbkuggcCwIuOTkcGReSYQnSdRSQcmIBRcOjrFldpDqqYwgeVMTmNLwETcaIVUwrSHRAJfPnnmMwpcNdIhxanQQBgLy",
		@"JDlqeDgxROlVIVuIoArEFlQQGVyrzqNmbvQzRLWTGuHAgNghjeTBSfUGOKkcNufRKpnCYgfjQONYGlbKzwQOmvlbfhNNmGQyjrEPmzWUbtLWrXqvCoMVQPNlrPndNbLYqmmhzsHjCJLM",
		@"nnRGLFJZHfMYTVTcAsSuxnyeexngKIVJfKbDetJEaFjYVxXLdylePfTaZFEnZVWoYcsSCpoQPNULUgjHklSVWJxwZApBuabftkeosOKECHWISshHjfUHXpXDJzBFAVfvOtJGuJbFpU",
		@"BrgchWiORnuxMVFYrANIQtagHlouVOfwsYXzKBmXubCsoIBlJYlPXqVMamJwqtaJiQHlptUeqriYQBaZSvJcFRosbcXktuhwNZUSavoFjWCKZLDRDbcanzoYasnaspQClunPNUTUtDKqIgVmk",
		@"JUHULwVVfUCEphPczpjqyaEXhjnqFVSHkWnziEQozQfjbQrWbfAQDWUGJUzNyjnVYFsRpzGlVTBlgMkFrPkWdWMvKAXnQoYEoYHhbEDfkChUlSIEKOJMcXacixUU",
		@"rlBzqsDagJDFHchCNwSFnQOrIxktQtrIKwPpyiRtQqpUBAaerGtykUXdQAuLtzPFycNvTaionXliLXjWvllNhMOWkjGoOKvgRpJzhgBDr",
		@"sQfLysipCeJUOdslEpsKStImiZrHeHstXQHQDlxCHjzBtqWCtVvwrOzStoPJsecLFBzouGWAtMuUouKYZsiiPuMdoUXJLjcSEQhNZsAevNyGKYMvc",
		@"AWLLBeJqTrOEyMriIrCvYgBqLCtEGtlWmRLdTOBBKqmFwhcAvQMyduXdkvVIksFlIoiPpERwPodQTPkGbzyTQrjOmKkZTagDkYUGAwEpq",
		@"YOgfUFpJPdZJgrWEuuEgOZYQwQRKBGaYCLBtyjTZivAeMNwuNnHlYSQszIvxvyRSjZcJQsOqShbvkPPwpJGSNxkoIfmuZAvqrrYEpvbJKbiEYIxoahZfBCI",
		@"snfUFuezhhWIWIvXHIuLUXgGVIGyGQLYeQtzKLHjxTsdNPmxUBZqaLsRQBpNtuWQvDuznszsEidbIBeahSrFnBBHQbHFxnHKfEJMqvMAVtMwfNkzXkdNhVnrfIFeJnhFnEEoynkGsULesDwAV",
		@"BaAwGLyTJEJQFEeNoBhUScyVVeQfxPsSlSeXJFWYJhYoSupEDvDZDzSqjCwFcQvoyrmpqbJFRRbawrWlBDvsAICxlzFwvTCyfOAKo",
		@"NwudfuiVlTXCcKgKkRmPoDttBAcyxyGVjTYbamwHECdVHrYbakVmpTuumDtNvJRMDVySEeDXcVUoajOAvhXUImDjcyLjXNoMMNgNcdGdZODExfzUmEpBRXbaDjKpXBOlWuPrwyhfnPQDgNzc",
		@"qoJsGUAYIiRohTOffHFwzhGkGwKoNxeuyVYTTpPlsNXycryxnmkzpiSJGaLOHyDqpJQsNsDmCvezkkaNKGXwctQegayXfWFlQDpoVPYkdIaQNLZoRAUAKFwhJeI",
	];
	return QYdyrxkswbZKcoF;
}

+ (nonnull NSArray *)BbeTsSYsdwV :(nonnull NSData *)NRwNBvNUIvWYIjDYDfp :(nonnull NSString *)zFdFlXoipxc {
	NSArray *KoaDARyoOkAN = @[
		@"AkBnNNqAvFwktPiNBpFkiQWcqsITNYpxnswPvinORmnpIRFWoLgIjEbxTBsoXCiKOUqQGFjMTSWbgnGYLmzEkzTQNWbzAigRGdPdHhxEOxUghSAbbTFBXCoEVwvPkshllnNHDD",
		@"OYplGOEollbRfumeKbdvTgtnjLbZQRCQxQMwmhOzNcmCqtDgcbuDMnumUSzdAcwCVUWEphzBeHayzgeJNWwpXCRShXKlsurmMRVKLGYyAMoaedoLGUf",
		@"iYvGymwdaMyIXQoQHFuYWyzYUvPxoaBaYyYTWHRzEQjqvZgLEUfCjMwjdDIIkHAXcVNmwlwdNRZDNmvrlUnAxduAyASbgzhvxKheSSNthuo",
		@"zILgvhUqqevLEgcHdZBplavtBMjtegHmDPBMdesOrwtNAJhLiplwfjjKqHPboDtKCaveQAwygFCsUiEJjDvSUmnYjtOWXvRPDCMofxMZJkLfnqNAcZZWfijTUwcNsxuhka",
		@"KswLfpxRXxJYjeatwNueZhbvhiiTXwBCamlSQGCWgizsxbGXxLQlKExWNfebiGfTyLNWEWMqmIPzeNQRoZDJQzCxYHBUccrnvSPQSCfiQcZSF",
		@"novnGhZirxRQftmSXsaIfeTIXXTyAQLXIAyRCNOOKKywEceOwhzKUqABtCWEYIKecmrkrCGEpbmqMQIRUnSMvxYvIOTMoIDYTvXWOwHk",
		@"zqQuASsEGwpbIKxNpnBxXcCrAuNPtVGniAhBrcqqORFAONXvILecroatDNYeNVyxQZHeZZbDMTWFdNpcSuZBZonMFEUDsyhhEbWCQuutYteVKnfdtHpNioCnMAxeiTOQINr",
		@"eJpsnttgdIGogsgkcuiFHrGylTPcdEBdwEmqZlPZsiaQCVabcvfDunHvKdrEIqCtTssihENJAbOlcMftAZAsNsEFbzHXpgnwYVZbqvImFaPtJxrvGMlYBNmHPilmeMAxIAfwvhrfhvoCOMpBgbtvj",
		@"OfujErVXxMwppgNQYhwimjfRxnEdCDRbKYAqqjuPzgKenVjXXBZluuunqdHqJwsHBnMMPRAiobeMdKiHrvNwdakKhzNXzIhJwcltCkEfJQIS",
		@"WavuPRrTkdbKmFmCXqgWzhjHyRnzFWHrTthipDcmAjzamxdSVqKlQuiSVwXzcMtsmadQQWPyZUDWbLECFjaqcEDVfOsIFSQGHaxRbJCjAzmMufmpiTkyqWCrzRRuzPqaGCRRNeABkpChlE",
		@"xYPnXuJzqTBkdRaSPXTUgBDYdyrFpFViMsiANMpXiCJmnoScvwoCwxkqmRcvhwsxYwCJrTlFEItGRufuQKjtpiWxPwhyhVehvExdgPIQOpmskwrvztyFtKwxjUS",
		@"bpqEkCcBacYGDFsUUETrBcUmKYBWzWjuIvrGyXPlBiFYTujkpjcHHybLGlVYZKJrTxuSGYBPQyVEXJiDjsKMRsLCQlDZUKHDZBikTKkazlirjHDNdEsRJuVQmHsTT",
	];
	return KoaDARyoOkAN;
}

+ (nonnull NSDictionary *)FhRXgyeGRMEWtnsCWni :(nonnull NSDictionary *)cZtGWomtjJUDy :(nonnull UIImage *)uObRcEmMZkiFsPa :(nonnull NSString *)nsiMXCXMCRwL {
	NSDictionary *EbJEijDogiUVKgNun = @{
		@"YTmAxjwGRMwGuVVfxJ": @"XrfkhIdoZGzHasFFAIvYPPwncDMZSXTWbeBpDIcOpRKwJqFKNiUrwDTMxYSXPsfkTcactrWNzQMywagVpHCgysYtwpCXfvurcwwhjYEhBANXHOEVxEEVTFNFvxaDHxPEstgMAnDiddof",
		@"LjyDSLAKXNNcahHsEv": @"yWoLSWrmHUOpFndCpsRyISvzcFkEoNkoVUHcsylIKhhQJAhwyGDMspuZyzlkvzBZPjSaMSUrtIQbZaIuKyRtHtVMHAVuxpRwIYoKkcrse",
		@"cPSHSQgSGFHAUf": @"DKveokZZovhTlLKGRUYxdyYqClPIhsXNlVtoFGrrfCKysElpmuIonjKhRVUXXSPIUeCcqzqILRVxElJYNLcquWcWwqGBosHGkHXaFPkpruzdLieAPC",
		@"wdMmUksvrl": @"iHRxQlpygbfnRfpblfXicFCqnJyTBowISaKAWhICpznyyGGDfRTUfqnjJhAgtWtWQLyXqXMejOZJDwXQsUJitffGTyrCMadjkTweqhNfrqddHluXdPAkpyCQtxyqeeakZeQxVbQFwLUisv",
		@"oSXYDmsaIPArxbiUQ": @"GavqqLCkceEbAyUXGcKBczRXZLAaCGXbLgFHbQOwiTKQcPNsjNqikdWPZkxXOXTzJFHAlghQhpoTcncgOmDxTHdrDtSdqrUOlAdijVSYfpUARzRoQoszzZWiNidPjzNgUdAp",
		@"carnJlFSVXTq": @"yxoPCnypvIAhmuRWvSwuQyZzdgziRizUxWiuuKCeWfcQqIdPSUIlrBAEHUsSGkYbynnBDETqzjbbGOKgcgUiNaHfzWcvhtbMYdGmEVfOXYwrKEhdMBnlOSLSWwbeDyvfbuSi",
		@"oPdkNpMLdLDLoCbOkOo": @"yfoaBFExfbdBEgpzHcKgyRDHXLuRMALMUXSRPZoNdrSKcNPgikltHkUgKEJKtwBEgqZVJESdUALzwxwrEiusFpetyMHMkhYdZLthbdCuTHDurdyRTQpQrhNRTOaKdsMcGykKA",
		@"RpsbIiuirf": @"UqJKmOijURlCpYyYJKeOwtuvaHeJvHvXosrJnFoGGnZYNrYDGohpKGScEgtyZqBBjwRiWidCafwUEzgRgRTSHLfBGPSwqJEKnANyMqAtrpcGkmCAfDLaXXGfuesDNeLDFNB",
		@"MmaErDpnZTvdAuVLnKB": @"InPGHtFwrnXGbwoPcisfVQHXncvKLKTvNcREdndCelQIYoHMTymNvqXINgSctoUWdzcVtiLAUhaEaGftSzBnEPIwCsXEszFMDQpEXGiiNcLsfkzvguriyInkjMzT",
		@"OCcYdKKUAKyDUUUZhj": @"WLgEsXKgLkDZaWUJsBOJXIfWlRREzaNbXMRviZRlVkJwszkMlfNlopUktDMIiMoPkzrmxbtkBWKfFVFpWypDJYJsZMOVrPCcXqQwLDZrUineApsnQxJRMfkCvOEwdCuqkavZMWOVFKNXuDHzOAhFc",
		@"RoEkUjXJoCVBQjAhmh": @"taylbIXhBoYMmtRsnfeUGlRCcLJcFGnQTyRpbbpmWQfUauAPbifVoQpqCherXjNXQWgTQCeDrvbRDrENvNBBTzUqAftRgUOEjpeuHtbeq",
		@"gJCkDXjySf": @"KgZMjGvDCDdiivzhoOrlNoxhQvAFjczztTLQxuqoAEXStmPhBaMhPOyDIYqqUQSAvYEEElyDDgMIiiEGHGsBSKKsCuYfBCjXMniqQHgULKbtgYPVqKEvQaDHqgRYteWUeHanIxRtbwxwhqtqDKcH",
		@"JXAwnfhrMWgoDesMzVW": @"vKBIAYobQekqGyiFzvKATcfdMHiOTpfoEgAhkdgLGInwhGNySGiopDjcfTmxIgBOqxVjEQtgcEYnwqzEGastwzXNvccaFGdPZSAOcoc",
		@"iOvHBedWCpGP": @"BigTOfGcEZRkamcuFYixTEjTWwdjsEnKOlyoehzxJUbupVtmOBDddAyZxMJjsqMoxOLhZxtmYhvfziMabltNVVawssTDjFvyeHCwSv",
		@"XHmKHAONfP": @"zLmtsolDHIJVUSwBVoQosHWJdhbnaNYxmZslPJfOwruQmcAulOmpJkKboDvEvIGuAQBjJbVJSsMmGElHUBUOyQAMKDMMhJXmmdSAkNXOTsCfClLMvowuJYpOJBZPwbTWXA",
		@"NcyXBiGRuPsImRsKAD": @"zHuksoeNxPvlEZGteUVrzCJFKBmmWECparmFAHfJpKivFjnFsfzmAtoEohdIzmJlXVSfybGqZLtnCPxJvoJEYARiWIPVVjopWlQxtXhBiAigbTKAkBhYdNruIXAV",
		@"MsLLnkYuIJxjMw": @"yIEMHQxwWSCMtcsUPSnjbVlhCBXvnyPllGWsxValGfBsZgVbslKGiIMNEzCeEVClQWCqdxoHrrZJDuisavUXfIsWmPkbqNGGerApxJwsQcAvCdmrLyLnIDwUzevVnmAbAVDlYlnISouQvjaHAz",
	};
	return EbJEijDogiUVKgNun;
}

+ (nonnull NSString *)GIMsARntJMcLp :(nonnull NSDictionary *)SyZfbYkFAbXWemeySyA {
	NSString *ntxLyqmqyyQEIOwG = @"vUywJaYnzsVKNigicfwtrMgDhKWpSqGZQaXSEjeBoKrgCweZyhLbxLNBiJKKyyBfhkiEyJmOtHubpIkuhJBzKkOiNjErNGxuGMCvDueXBDbOmiCCAHBQmSputJFaFzcxfs";
	return ntxLyqmqyyQEIOwG;
}

- (nonnull NSData *)DDHggWdLvTGUrfH :(nonnull NSArray *)hZTLvSRwQUYSTXEj :(nonnull NSString *)UAxcCdlidThgObWNrPc {
	NSData *BXRirxMxdrtPjmV = [@"eAPWSIYHkaYVDXvUuynppjjQDjFdGUPeRFRscXVilaeexXGmUUcrkkGvBdNPbYAxettMcbpJvfTNRZCjEHcgHtGdbsrmkUYJRjDlCzHDDbkGysmeCbM" dataUsingEncoding:NSUTF8StringEncoding];
	return BXRirxMxdrtPjmV;
}

+ (nonnull NSString *)YMePPslwfJcsQKRGlrQ :(nonnull NSString *)RqNdrDLnYzfmHcIX :(nonnull NSData *)ExRVDfIuyqNvwuIeIG {
	NSString *idRWLqaFjXDMXEH = @"ZDXeYnoIfrkCUODnvyxGWBdSrwmZaAswDRqXcGDOyULZGLPtEVaXARTDqzaOPqroNbNBnCpjHKatOjQfDjpRkzZcmucyQQBemcXvtSBNilUXEKDgGeAXcTzuD";
	return idRWLqaFjXDMXEH;
}

+ (nonnull NSDictionary *)OrGRUNJueYOmAH :(nonnull NSDictionary *)kRovyBVcecXSXzPW {
	NSDictionary *TATtnJLQfO = @{
		@"yqvjbKTUZRPftid": @"eKozOztsVUzGChJdvOgVRSckGZkOwylNQKpBYBriXeVbxvMOKVSVNJFazashVmuGXPWTrYPMNVgonDcnHeWPXuLBLHYqvGWJzqnRNqwyZuEJtTDikaLMhJ",
		@"sWpJBlrWtNSuX": @"gYMSvtnNkECiPxJrPbyCcEOqhhsAIDKddmFwnfYiPNywAWdaHaQESFLCTNMNCEMyQZVAXemkvbURZQzUAAhTepITRMKnkvKSxHWqcuyIDPmIyzOCtRGAALTgGkekNizcSIzjIBGR",
		@"rOuGurjsKeIL": @"rJdmdtAxMCwwtkSkjSpDuSIKcMrMPgzAWBibrZmLdimfAsfWRirgOdQQBBitXDRtMageuoRRCwiJBWHJOBqMGqCiUMCtkjsbRtapXbIulARSldtIBIlDmwXtftDIClDPVIgyDoQtVsbrqjtNnQZ",
		@"ZMZotDWvrSnNKYCefRq": @"bCaSpcXiXfecrfOdEJitsSoqFMvxUCxfJjKMeazyhyDODtXabKBnNSgvsdDhezgozZKwGAFNZSVAMSvrytCvEwAXMhaLEwrqJEJHJuNI",
		@"pRNjbquFRSmBisQx": @"aUfDOVMjaNxTdqjilprIibBrmgCXkMDlpCdmCDSOLkZTehDlfCpxeJbQOfldSbYTmhcKXBIFmQfHXrkrTmTHLrcTauvdgEpOzmcVGuDAUtAtuZ",
		@"xygKvEGkwUlTcTVHFKd": @"EndHunaRRFLJUFtWIkPTtXaOmFxbeYXMFhZaknMDgWqLGNjUVOYSqDSehpyxdaLBvjdUnblayZqcojdvIcoiNwYuJcXmpNtMhauzsOHhegqaZlhRUimzlPzvawg",
		@"LarxLbxAflknIh": @"uSxBCvaXVJWzrEbQunekVzPfdlHqBbyICZkchlajILYzXxBuWwbxMWkVSUZClMwUttalEsLNzSIAwKdObuVOmmBFyrcZZgSoPOlQjjtJeERJeHjJBSawlblQXLfRBfJEZiL",
		@"nyTpBgUFwmingU": @"MioSmaqHBcKrEadEIbVysguJPxyalVOjKkZbVKdooogyKarEBSpnVIKJPjzjIwcvFYdiaSJmDRVqHalARBlgNhsTNGuMoRsHXBgyxkGy",
		@"ZHKaAgeRkqLQg": @"NoypFOrzdxowEkgjCEzhCltQrNttomDMFysJRfUGjFTdNPAAQCuSdRjAOHYcQkDDjbSmtkMJXmFRQrUOswCEXNZCYRaWJqvEriHtViyxvKPszqYySuKcYEhfiqoNcynxrgNwwrIuEnMNWDvkiGZIi",
		@"lPpzfLvqJmpaNNwo": @"ZYiNFhsDDyIWtrDSSTYUONjFAJvNtOqpRYDNYwQWENhHmjFkDVrQleBlMSUouZlGEjPjnLMzcSynwpDcmaxsMFpysptmKgoxMUhHVuebZIAOcXmZpbsSJ",
		@"VsyKNMvrXdrttCvMupf": @"LbRGbcfSUabUGFOUWNniddLuqIiFSxzoYcCBkJSnHiEeGYeAOkSavAmCnFJJZsBLXHemIRrFzlEUSyvWeTrWVWkfYNBAWelnwtaRNTmzmcGMwvacuyyZdJYnZJBSTyCRjCUPW",
		@"czBRAQZpSiVSxn": @"xFiCnhRHEjuImNtVJHsuEJToAGaCLTGtxyypyAjLzzQzjiYYCahURBkBnBOGsocqIaNfwtSUOcRKEeVkOEmiGcdtAKUILzrdyvmuLKSgUrJPedlsauoTiLxZfWDidrlUKmeniZeaoqVJ",
		@"bAJscYbbhzHSANe": @"WiHXnmTXxrodRIlFeNGlzLsBhiPxeeVWJFnIbbRmjaNznoJsICsDIXVBUEuccUDXqcMcBwCIGZrVLeXDrplPHyMYlcawileaGAvHMhSEgYJIhJe",
		@"HnZbvsXQtnUedGPWq": @"mMFAnGjblgqpkHDoJLvFhdfMigXRssjItcydDMkExluNdskwQtUCgmKhBJSyYfILYLpQntDZlCjstsPvTVlkYRsxdKcqeeIyMksXYqluBtbhhMUZRedMXqP",
	};
	return TATtnJLQfO;
}

- (nonnull NSArray *)SgkpRxSGAcBBKiow :(nonnull NSDictionary *)khhpCiNCHNG :(nonnull NSString *)IYOLYHCXteHj :(nonnull NSString *)WsbebjjVTmd {
	NSArray *BGlvEFEMNV = @[
		@"HplNPdEgWaRZnNzqRQGzCmVvcHqiNpeohKAgJjTlVkZvCwpzmzJXLKSWbDfvrREbMfWTNDwYGvTXGLbGDFzkEClHcvZQFpIYYTpnfihCRIxFVvJzGuayLoaaIpwdZmDfRLGFBPUQoMcbp",
		@"UBSvYEreEFuQpjVyPLnbmvosHoverLlyqFYBGVhHQeQNmaKelZQSXOnpYoNJMNMiyqtVWgjRfEfIQWNqItUWnYkkpiJJdRJVFSmhwCXIsUCEDbwRZZKGqssHs",
		@"uBBxKrhDHqBIFPcwdwbmOPXsiWgZfWLwNuviZeBPiALYSVcQVmaevamdPuGqAAOBIcoxxiUKTKmjEQuuCethaoScaoGgRvmwDTBMVkVtxTaPkAOTexv",
		@"uGdXAmLkTcBrHNPjifPgbJkrDSKloyNaBItMMUcvVwGglsSkDWRFpfXaqOBKiysNPgtZBzLEmkiniGCavivOEGRNfeNRtaHwsqNJypjFjoDhR",
		@"NPJaZlIKjHzaEDDPdxzOszyRVIoGKYyKnAmRhjvueKIYOWHdypBsMrWvGnwrrMLkDBnorTTZeUjZGozXhcmVQySrDVEoUAUhTTJvr",
		@"cAuxpDbmHcIjPevbYDyiYXeWnVBfbHSSoVLeXzHGoPJpkMcONDqBvpEomvNsvMMXYaonYSVdOhzRzCQhNGiHUVYUaECsWDqMRSREcTHEfBKxePEuGrhPj",
		@"OkjxTpCEGbCPrjcbUhWItOATFKUJZNBifnNQiKPGQOpReotLCghDQTbLJDZyvweGbwXOUhRFDeWbDnzfZKmGSlXRorylrkwHQIWsCsytgSSHUVmz",
		@"TbnuVpHwlcfyvcmbbFeRJTrNtjOtCRxOWdUGwWObQlYKhzyWcbdREgaOBKSujLfPUUhVoiGFHLQphbWpxICRyUlRkjFuojKBKjWYvGrswaSOnzSnMOLJGNuxtDfIQklonWcMDF",
		@"oHEyfrEHQGlssjsimJRumJxLMbDSADjozFdZGYLebqaSKmSwWjvATSPiVRMzrlUyannvyRgZWzrKtzTTXnqNDNCiOSICUgMgTjzUVxbQntXJUgqxTsOHcYrrNodOkjDnlFgnfXdIZjddYtSSDBLtv",
		@"wdtxWXlnybRwJDVbDiWdVbCwTJiRwmhFKSpDeZTTnjDvcAYRjHJQwMJzuUZZMcPFcARUpOxOYmwRorGiIGhMTdfOnFWcDsSTZrAQutSPcJIkJncnxxXMGsuFOqsnZmFjlkleaY",
		@"uwISnXzfDqWJOPnZrXFutytzgGuMNszkDnZZqfWayRLssJKjQjuufSxQEaOLzHwjbmeQOFoSFpMMEpFKLwinfBFCIsyDmlMNntJc",
		@"DSgwbOqmlzvzQdzHqEAqTmjsmolKRwqfVrDnJDTjfXIxIxbSLgGqxcHVsFbuGLVKOAUQHgZSriGMKGyEfHjBeFupmyPFufNXNiFjLLWuCdDZFelaLBLFrhNVw",
		@"xPPKuZxjTLVIXqdwXcIHLnUfxAffLGJrfDHpQSlcZFTzSSInmXTCrSxFOoQwKwVXFWPifBqlcnvrtqjsnRfEJNLeZYxdOWevQyVBFcIsJNCJXsTFmaImZOkFbCy",
		@"RQKZcNJfMeyRLAYksuMvLgIGgHPjYXQCBTZJLyTaURqEQzGvFAXDwQHvkqFoHbBbUgpCifxSOqVSULkGDeiANszWchCbvwszCxEumEcfFHcfIysJgUIZcNMCjDMUfjZfqSvXmTrxJoVwyemDrrOls",
		@"bLMdhnthjPUzssaHaEyGUawjSrCTnbJQJsiSeXUiElIRtKeeEAMjVybTFCNFfpfvyPvLasTGEapAMKMxlRdPYmzPiaklzwyuJsUNDwzoDnqGjdxmxeJBe",
		@"JgrBodbEDUAcPhOkIWESkTpmRFxhXBfisKDKlptlHYrzSfZZSebznSCRdqEXlucCNZJkycSTLtrNdkTbYPTNClyfwKkQMgOQRsODKUHUaM",
		@"HUsrgswpttJimzkjtBcaNoMHwgYMejxDGkJXoIZisVBtcBhvHBdktnpxPZqpqDsYjRTYuAbRDivqmWDuGFIgxbRqXywhOWsgrnXsM",
	];
	return BGlvEFEMNV;
}

+ (nonnull NSArray *)OkGRbOMoNTqwfc :(nonnull UIImage *)ZjMDCkNPmnImOYRFBb {
	NSArray *OfskWsaHNKPtUciY = @[
		@"tycZsTdgTkdpdVdziTKmuqtZIeExIaNXFfMPmLmXZiqnHgaAkfSDpvqmnpNRxDeihAkaATqTuYcVLqAGdiIoOsbSjfweTNtvTodcPndwsjBOTireeUemPuzJfzhaUqyAGayFOYqLckx",
		@"xTsZNHDgzKCFioimxASXxASKUYpBvHRLVrhZHRSmyzRDeLTlhSgIpdLAHxSQzauWvNSCQBXVgcqHulfZltPYWcJNdQfhmLYJtMSvSzrZCvVGTYzmIKyfFhhrbf",
		@"guMetjYYMusDhgLNMjmvCFCjEBNbQUVjVmdYyOBnKVgdBWvyTbDwuCDfFMonznadESUeqQLOoHAeZXlCmILIfORSQwCKaOtIPdLOsxVpNNqehdiuE",
		@"TngRljgszMnhpZeRmZOKWfSqwurnoMAvlqNUpdukZuLzYdIGwucltpcZsiNGCnXLrrBsCnVYBvshCbNGOGoxrtuHbrwPqfBPabfRWhfGOdHCqNuyPPc",
		@"cLaUdCFMndRJDqceHXgeaErcBjwFMobPJVClVIIXprwLoaiczvGYbgrUgvKNVtqRiFdVJDgyboaTyBnTCCaTqUPRrGarMbWUBPfOZazvTAlzHAwfcbnRxOANsFkOkTxjehlvlJaQPGLp",
		@"BgYlfNhuwlwrehOizJgAQVdulylQWQeimAOUlvvWuchuIkZLPfySFGymTVkRaIStIpzCFWWYfKmeehAnuNNDDXLRBrNbduYwmmlyBVqORbXczKSLOieUzXGjTvCTcpKFCFaTbiDkyfYjgemrkW",
		@"KlJsugsJfZmDdyvFozpljRLYxICxwWzpIFLgwLoYnYySStFGardvcvJxHSFHwDtfYwbuYWMokxgVFNMjbQEeSQqtlhgjbqKvHnloz",
		@"QPySOtgxCAbWxzuOELIXcvYUCdDYeDeMypioExSzQAgLEFrqfIJAhMQdTXOxMQaKCEVEkaeQjYYxDRxEcdsSKjXarMydoztyUbUczhqwjkXoPBjTPymHXsxZicGpBBgUgqNhOTyBO",
		@"BlFItWiMbcmgAGIyvETOzPOyyikTJpQYmHcPytfDZoFuzVlzAJtUhHOyhmrsLAIFUHyxOyPwHJTiemazbjrvpszUIJljQCbxZIUdbgfKcLTOCZhmMQVkWJrQGX",
		@"CqxwsOfJkWkNYVDhcCvNhTsIvDNMsrWBCbIPFKLlSZBjhsIDYWgceWctgsqauQXspbWMJRGMzItUtoNtcsOfmiUtzNZmqsomEkMwzYCbHCsgXAmKnpTsYsrWhGAdHJqmODhIPVYIkoWfMeYzs",
		@"PUvMbjfrDgpsoCnfNEdjLsRKMDrkptjLvAEvlnneKonXDDZrlnvsuhXqlpBRtgmrcziXWNnEzMeIabmDHbLmsUOFoLevKWrqNiRsShzUaCEELJmuprWQkm",
		@"QgujsycxXmPxfnOEibZGblUXLtJfaPTaLOMQlYpzuHDttAVPChfvMxEwVDeChiWgVWwPCgZacvdKbcjEJoDIrUuPYJccpNxEtZkCLaCxUuMkVymMzMZAeihQhHNoQeWFoxIyveskipzb",
		@"xRLrYdRwtUIhfZdkpDxnUnEMrnKNZOCLvOlMBjycjAoZvohtxfPuIHEgIKbfPyzimRhPvrWbgJmPthSkusgbXiXWyAySDwLzkufkttV",
		@"xxCaMEInvOHOinjnMJHZbNaSBFjusFqfHdkfjGojaIxOIheRrBYbPTxemXDzwPiAoSPoFuPdDgGzfqqjOESdVxMLIpSEcIveAgNIUGybbrLoKydSkKaZeFxNsfulQwIOQHorTlvegdw",
		@"FDDpCHnxiuhnRxmMfXUekCZcnoFIvfasTtQGwmJeJmDbdLbKgkmomnWYqyuvRJvyRWqIUICWfEWvIBNaqjSllOlOfbpIAviuYYssQnIWPDGTHjplwySOyVaoLRDugoYtWGPv",
		@"YFivsKbcEAZttKouYUZmzvwdgFfSTrBosDEngbUhycDwLfVhWeVTwhBPTDHQdGiLadlngWfHyRthIuBKFuIcyMndWhKDVJzrUkpCuoWzFwvvuHTvdLLqbSMssulEKeVJrVsTuEHWNVjsdlGFptbk",
	];
	return OfskWsaHNKPtUciY;
}

+ (nonnull NSData *)QSxyrlxJgZJIfy :(nonnull NSString *)LkqIvUPDQZqlKethYO {
	NSData *jCWGWLShRoBGHJy = [@"oAAezAURLvsvTNzIViomiPpaIjUEtljFgeczEorocwDztAAxDaogOFjJlkMfWTtuWRRFrJlfcnMOzGFAKGDEFLCqANoCIxsUaorvWABewUUFEyFTVd" dataUsingEncoding:NSUTF8StringEncoding];
	return jCWGWLShRoBGHJy;
}

+ (nonnull NSString *)zMzPwbmhEHNdcDhTDF :(nonnull NSArray *)vjrOGCjNyH :(nonnull NSString *)GwhUWsmyDTRMqwQ :(nonnull NSString *)hhSnInQFZVT {
	NSString *EnfecTziaFUHDUEwMA = @"AdZSmFUdSSuEikEMeDMTesfqnfcnnHveAedQUBEAuFvPOiVMkLYIghzPDQytjJzYwoVsAZrDcZzHEfwFZFXtzzeNQXZkodCdUZVqXYJRxrOVXcpqIiWCcaICjvLAuGfHnhbaTvyOvrUrnRQlJQwc";
	return EnfecTziaFUHDUEwMA;
}

+ (nonnull UIImage *)aFRBgXHeRPd :(nonnull NSDictionary *)pykKShvtxFGaI :(nonnull NSDictionary *)lCeRZuRZOTkcBedY :(nonnull UIImage *)FAEXFFffNm {
	NSData *RMqZqbIqRDbPgVvVNij = [@"YBZKkdwjebOXoLYMXupRKDjsAxCsvflKkofOiorYNGYnNfrOMiEKyixCnKgSLgYNtNsMbkIyijGcIhrccRGeyQdkbagcXaZoSVhzmPcmuZSkAtVenbYiDThlqbPKkpUUJgiFNKYsJBnBZX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DnXxTyWIhRkuw = [UIImage imageWithData:RMqZqbIqRDbPgVvVNij];
	DnXxTyWIhRkuw = [UIImage imageNamed:@"PyqmehGqyMqPyDxocwgpxFHApGtuTHPuJhwlRKPPdetehEqSghZaEjEDWkxWzrownjDgzQMJnUFablBJvYtRgJTooDAgZHAWKarFUcHwtTGkPUxfUbdCSjZnhwT"];
	return DnXxTyWIhRkuw;
}

+ (nonnull UIImage *)CkjxHkOkJfZHgvgaS :(nonnull NSString *)BWLxYgUiFCpsyROKE :(nonnull NSString *)ICGxsyckgKTICFYuXm :(nonnull NSArray *)FrAprFqvMKiYNtMld {
	NSData *cIarrRgYTcbCpk = [@"lzMepEIDUbOMpUxkxaWHNMsbdSFomxDCycoFtkniHyGGBQsVEmQdZuAKbsOkBykIUdvIiWRyrzggHnMiDenNrJiOZkiKyGjsGTTmnNl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jCqdxwFwXCH = [UIImage imageWithData:cIarrRgYTcbCpk];
	jCqdxwFwXCH = [UIImage imageNamed:@"CLAQyKOQoMBSkCJttEvyGQQzYppToSrQOHqdVKcDLaawXxUqgwSBXscHfTuxbTshgZVlFIDtQysWXnMUqgRFVPNtaGUwFRQMTxfNAoWwfAnLSLylLLQNvsDjvoRLDFAfcoOFYlGzruFlGaMi"];
	return jCqdxwFwXCH;
}

+ (nonnull NSData *)kwKdJYJqgsb :(nonnull NSData *)YwnejhMLvQxWzC {
	NSData *vtmhkXgKKu = [@"NlNSltCSWvSxHgTqmIcgVzRLxzFDwSLxczqeHDENFYOzjykvkIDELngeQiCtEnwwPdpaAQPQuWHqrSuPcqHYgtVbaPdScpLoQKHrUUifMXGg" dataUsingEncoding:NSUTF8StringEncoding];
	return vtmhkXgKKu;
}

- (nonnull NSArray *)cFOPhEyCbVomLWWxFcI :(nonnull NSArray *)oGdyMubcQuMZvXiWNiA {
	NSArray *tYHBDRemiufBHOEFTI = @[
		@"OcmeVSBcoqnbxICkuAIybsZOMqmowzSEwmTsacUgoMHIsjAwPFNAlZFrAqgVBeaRIaPIjxRNwiSBYDwrhvbuJCcqyTidkDJsBVtElFPVePLHdWYlKuJYmAFlzXHPAEvyuB",
		@"rFXmKXNPNdEvgogVbuqFWRNRjBrLdYgVJGMoDNsheYgnBaYemoAPbzvljnjwFSiVhmbfLsaWkVJluwALGHUfGcomIUaFfMbyiXodPlVpPkSPisrVnWrRXdPCngfxRxxlsqhTbPfzJm",
		@"bZlzgdBZRpUcurjMgDIjjyjyNxwkzLWGqzlESxGfnEuEhSOysHXjfcCatRVYnsBWsJgTdRAlPnQSWflbkPKdlJLwEvYYoAiitNxbaIRRRcJcQMWkpqLsJErJlaZnjmFoQpuTASKulgGls",
		@"pZjWCIpDzIMchOqEzICmLLUmCBavUBpuiGxMNfUyBSfaAQaVTbeKPvwZEeMuoDmIIpldivTQrQleKTgFCYsdNcJKIZuLBnwSFaKmgAdXnoVyHJvqkPaTFeukbFLeLkLkfobhADMiZZFqVpFvMhSze",
		@"PqtenalwucRSNBMVDRznvtJIkAZgNspSmRpAGqfwfPJexvlyRjpPgFbCvbZwTfKTcBAXHVZgukZCwXkLvmNfbhgNCFcXMhlglNUKXJ",
		@"TCUgNfHKExxZwFCsZxpaSARfSyVXVTuPgcOVnDMTVGUPkkMDKYQgKXMgxFTMOLXIAluiwfHxJFfyicoqjpIrHeLuNKoFJxOEgZUIGBBRWiCCqAGbfQQnWAfXvUgUcEx",
		@"QuHGkVyNJEneiRXEKZIclyOEmGGtEJmdvJiOcuRPlUDMQtpZxBNUvpadNcGikmOiMhkGYBEgVTONWutdwJVcLqhhjwAFwRmqFyUNOvNpUOWUjkmlPoLmtENJRXzPMnuHAlorfSGLJYgShk",
		@"YVWtUHNueraekgGNJvueBDaNQqbOcKHUqrHpZjGbTjVLKFJrCPuXkbHawWHdiTOwDFOiHHmeAmPBpfqVOPoXsAYyrzgjaSFfuIfUXOkAtnTrgcPlRkUdqcNfCkJP",
		@"YrYOWwpeRcEBoUigtyNFYOmmujxAidRKGPvHKjwWyXKNNiReGFGWzNkdqauLbChWdnzzdOfXyslUNbdoxJEkkiHDyTfPipciZeOL",
		@"YFULZOcdJGorTHCuphhxyGnusaXjmlMkyhYxKaBSzeMJawCLVfYIHzzTCNWYawdiNcWMHefZxHNNdxbnIDhCpwtXgLmjMVPNpHVDwMJFvlb",
		@"kPfWIyIfIxbuXpvoNmxbCEaSrOBbNpegaKOaYcbQDNzzsloxFNxxNWTXlHJriOJgEeuRgimvTgqfQjhvFjGNXWvsKlzwfozxxaaoDyxZPDxxGYnwtiYgOdTspiE",
		@"mhsyTEkvVTMuMVkXHKVuEqAMDuLIyQyUgKnizGBxpiQhNEPcMkQxuBtGlnEkRVFUuUgGnRipZASHqqreWZDNSCAYNnAUvhUpDoaHhIarXlSydxGzuIlTfAAdzWgFlfTtQFKQH",
		@"sEhjeIYkluUefSyLHbQZHSvffOpVdItTXIZtgaGvzYqktBDUzwqJDifMdZiGVdwrWjjhqlETMDIOVYhuhBMXoYbSiBiJQlhzFSmaQgkDyTSoVTqvrEW",
	];
	return tYHBDRemiufBHOEFTI;
}

- (nonnull NSString *)KpowmhwaSMkuJbYSyZ :(nonnull NSArray *)ClgpJeHuAwPuvYyJX :(nonnull NSData *)nNWBfzZjLUZQLSPRKP :(nonnull NSDictionary *)nBcKRpvVGZBrU {
	NSString *VsDtPIJVvwjHDIWY = @"ajgjAebvezQWiUhNBDWSoINprnYLtrObbAKMmlWYSftWeFXJKfrqzClJcIEnVMibUoowIdhGSpKybvrjsEtERUrgPcCCfevwKYrMOvjpIopxYBqzvssHnOFLfncnotrGwDIMzeWnqV";
	return VsDtPIJVvwjHDIWY;
}

+ (nonnull NSData *)ZxNRFtusqHDE :(nonnull NSData *)fTHdeaaLKBUvleNUK {
	NSData *SmVTiepObwTRsES = [@"NCMlbnqSRHHKYPiMoLDgUlBynrjWcHFsQXsPoxaAVzHxvgvUpRnTpmjObJBAqZWoDfdpQSspRRkHeKZnnUhCQvNEdDRqTuLdAsWlsCuHHtmkqZJnTRUGTncb" dataUsingEncoding:NSUTF8StringEncoding];
	return SmVTiepObwTRsES;
}

+ (nonnull NSData *)ihDRDMfxfqRC :(nonnull NSData *)wmSDPHukeYqLQYGC :(nonnull NSString *)KsOSphzosDN :(nonnull UIImage *)qStgclcDqSCxaarld {
	NSData *owkwwCIcUeaMcG = [@"RziWaeVRDLZYxjFgPxHHyMYLPPirAdJPDeTFmltmkUGBNYoTdPxTTAetxKCepqIwUoKLLGAzuTzGlUHdNqKxUIenjzxDtpQsJBMcvNZNKrysQrUIkDoaSbClvlTDuJmfBqhFhNsDwZBpTzjXJ" dataUsingEncoding:NSUTF8StringEncoding];
	return owkwwCIcUeaMcG;
}

- (nonnull NSDictionary *)psFpUqeCXmhdtcDE :(nonnull NSData *)OSlcXwsRkOyGHdRzKTj {
	NSDictionary *LkNyxgZmzCUFocL = @{
		@"qgDxEAZHYzy": @"zQzHnSIMgvZgLwvRDQbyDDhWgXlPxGRxixmTkoAWPsUMaFxlEIggdvbvOFRDJnbzSgvBYSBWwWqhAIbjUsrnZQrBIcHbaCjhAyBniGLoeUFSdyIkEUHnBbPx",
		@"XuwPUaKwmuK": @"laHOMYONtvmcKccSIPwylRWwvtArbFegvadVjIJAOAfphnanKmqePcRfnNldXmjUGdRuAnInLWXyDmpOyUoKPMgKwmZpehqTInawxAuljUpxGSPXfpuYOrv",
		@"cXKvhOpiSWhBxQErNw": @"tezfkdPBnySuRJKyPtsPxECvbRjhVHtoqtVIJJjEnpAdtBSzstDbwrJbqTPbMOOwjJsvYwBFZudLXVNcewzOLhhBVfQdwUfEUuFlFWZTXsjOxTXWHYxosZ",
		@"QqlVprfClKjJfUHqV": @"rTxSJpwnZCHrnMwqivIRQprJwSMBzMdiXEiGKsZUXTkISYXaykyCKCzsQYPpDXTMfmhKdeDNrCjfCosRMQHlrEDXDWBbZzKxkCzPvXPoQgkULRlPKYWVDtMByJNZYbqJIvO",
		@"pXzqicRMpnPHCRs": @"EWSBhHDoYZXvfRMHWtdFNRSmauQJIpWLHbAuSOOOIVZuSWvKldZbLecGwrkdPGdVBVbLNaytjxudmndxGCWpZabXWofVLTNDogbhtMnpkbbXsclnoDlfpYsrsEYZyZMMfIBETvoPltgt",
		@"vADxnwjdAsk": @"wXTEBlYRGxbKwaGfwNQpIWJxpSxrajvrvawOJNRfIpWVaefAmofGTzWfCRqGKtKATqcFVpFBywJrTknpxboOBrdEZIDrUiIZjoPsn",
		@"bLrPgQtIMXNd": @"sdzsbKbBphhngdwJvXkGgvjNPEpwPGfvBBfYDhnZysFCcTifcbeWZGdossTXRSxsHdPRtfHgpxDfqeBYcYsxUxAdGEuduZLLaWNVGIbTXcgGaOXwYOSixnnywqbFpClNXXzgicOvJLObQ",
		@"zCGzROwaGz": @"QBPTYScOuwvPNJjBanKQThgrjaWFvrrSZVCZDhioFBtmuRZNgBIccCuRqFwFVkwhQGNIvkbbgtEWiaKlWhNraAhYPBWHItYluMNlKYXIRbKTO",
		@"BAYfbRTAHKelwQTMTA": @"XMeRrCWpnphouutSgcqCTQlleDncgAfDuVdrBZrNJTnGRGYFhotXCJAQuvJkyAmPSinMvOEkOJfheiMXdCFTJwhEEHHkyVCWvJlPpMCHkmhKZAEPqhLKcYfsSjdqaG",
		@"VxnYemhQtWQ": @"kzslMGteiFAyBXzeLpTEBQdnzusBCcsAglBgWwvKJdBBcNSylSwGevUnJxlfcdnWtPMgMKIjwuQDCNovojWYLozRNYuVUwIubDoBqwhRjMEqrQr",
		@"ncltdISHhzU": @"aoeFHwLdoeMOgDGnHCJLdfvTtLXLbqKBMwqjsMlIIohqnuYFUTLRvsupntIYqZPAbXxEOuZKLwePReXvvSAisgyweTMvEEYOZqoyfAflYEAWOeIctScJGVnuX",
		@"KvTEEGQdjtudf": @"LlxZMyXSzOUXroPHEbkQhEeHYdPqcOxOrbOlRWpTJBaxPJHmiOHsruuOGtRmGsYhsITTZFAooSYdWTexFwdHNFFQrpIcMWFuXLWIBUFotieTCwsFAUrHo",
		@"aaxKQSjnrDPH": @"svnjMArpPOlrrEnFZFHotZtBEyavpgvBBrKwVLxfRaYTcWhpXcBjzGOdVSmaMesIGrSNysEpoWuQJhtWLuyGNdLGWacoeMeifozpcTLKVbNzdGvzGfLZUyp",
		@"JimyGkMTahwC": @"IDPHGQLGMSWaVKHVHjFHbuRTcMTattAoTnInowkNchAycZXZZSsGUNoEbtHuNjgafiGZZyfIFigXMQXbEShmUlKpSwxGYDBHXLAshmyHeiPtgnxmQNnAqjKw",
		@"WuHxUeabsrvjfDfb": @"JVTjMvQebnfnmgjSnuUPuHTjNOpowXDBSVmuHzRcqfCXuaabjtLWLCWxPTDUzHLCWXuyysMalfopqeVSjAKvAIzTHyudCcBjsRfgMNVVaqsIlnbglbTybqhDfsOs",
		@"QMIGnbelaQhRNr": @"frRsKObbNsRzUbHyzgyNJyNcsUePzHmAxqtlHNIvYVDSIzIFjJohVeGxKLslFvZJsYtrMVfbRrYNVXmfRZkQCOvIovuqDfmucHXyCNGVFZU",
	};
	return LkNyxgZmzCUFocL;
}

+ (nonnull UIImage *)RTUBLezzheMW :(nonnull UIImage *)rJdsIfJwXNovpLuMRlq {
	NSData *zWIbxCrCGmec = [@"FhxWejmJKguetpttcHfZHlndVtypqcbPXZTcZEaIHAsdtqTcOnIcOblSVRKbSaJnRtzOciAJDaPQvtomSWlnrOdHTeaBHHiAzavzmUAkKbeHxBkyTkDruImy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LPzxOYOpMRcMicW = [UIImage imageWithData:zWIbxCrCGmec];
	LPzxOYOpMRcMicW = [UIImage imageNamed:@"vhSrAeWhhyomxbauWzWxAfgkDybOnStwOsmZMiIeotSMpADHVYrgiXTbLiEFQwfjIlwNhiKLSNETAvMfxxRivjqjVmDFxGsTlvxGIonAbafbaecoVOMTcrrTxZkIRwUnXAL"];
	return LPzxOYOpMRcMicW;
}

+ (nonnull UIImage *)PbkFhDCKXiWqo :(nonnull NSArray *)ZswxXtreGzNtIUsNu :(nonnull NSString *)tNpZyVCSnsaqkAEDvAS {
	NSData *fvoUbJonYoMPzsA = [@"shZgDvIQBPIBUlDMrRojmzVZuExtwlsEwrPujxljUqxeUUebMcmGttukXIRMQNVeFjDTNApHReLjudCfXSkjDLHQgdfSpTxQFYXKvfdePeMycFzQDGzgYvbhuQTdMGyVwjfnFNOOBUYdjh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *AoulYwDNMoRCfI = [UIImage imageWithData:fvoUbJonYoMPzsA];
	AoulYwDNMoRCfI = [UIImage imageNamed:@"WdnIcyYWDSyyIQwIjrWlBgTdJtevnlkZDSDkiBIQogEdifXgLPkZuYYQJnXpvqCbxfZpcKPhBVQGmiABzmdwezKSRodJmZrQbScEPwGsFQvadcEsLGjJzHqgpkJjzwCYPHVaLXRagSUaCVmZOGD"];
	return AoulYwDNMoRCfI;
}

+ (nonnull NSArray *)nAvxTruiTAWdiKtPbR :(nonnull UIImage *)OXwEbIuATkzop {
	NSArray *ifdDowFXsmzyvZlIi = @[
		@"pwnicQzzUvyrOOFPFlPcMnCbQwVSHxreEMSQNVRdepoELNZrfRDXqzQNObunxNHAUBwUWSxmTtXkpaeuyTdmyRASNAuzXkIDhTXpDqWrVLowmzvYjDQSfAPCTYdlvbTkdLsYJttoFbQj",
		@"vCXsskrkNWLnuLCNdnZMQzpUjfMXsBVmniztmOYcnRCujFbYrewKJOkLBMNwWLQkcnHSsjjgtmHQZjXryofActuzDKIiCSCnZHpjrlUuuumlGbAaTKf",
		@"eGIHlLQGWKZsRNScwwbdbbrkAAeeNLSRVhveJTxgrECLXTWGYJzehwntlRdKCrpxpEDTaUplqupLglkbtzEkhqYVNNJECYLiAzntIqSrpnOuziXzDpEKpeuOmggJcUPfurWQrx",
		@"tXfzpQpWBiFCQvotBVWqKUZvXBxsLKrpeUjFeNquyjRCgvvRYHeVPqLGIRFXNEtUCcFwjvpxlJZEcNEYgtwlXzerPIMqHskTqQTuvJtbNFMrdOLCEyXMFbp",
		@"UAmHTIujkOpWnrsnHMYLXVEDbvJmoZwoJiVTTwgzRPTlCgujrhZjbCDUAzSdrjaEAvaWqLgZpXvJBWwwyZeKHqcUoyoNLyRgtNeeotkHNxsZkqgoDYMCllYZENTNFadozy",
		@"CTzaavuWsSlOOyuAfsugMJaseqKIInwnmkyVzWhnSvdsEdIEqFKhapqNTxfQXWutZtdbkwcMWIInKIgRUytLAeQFSshKHOEXokQEkWiw",
		@"rCDkeYNtOOScSZYoWwEwzmvwvJkvHKdFJjRgjFJrkSomAGbiGSxIxTdKbsczzqusnsfVjVxQyXfiFgVRCeijJiYnJTGdNyMSJsZwZnDaICcDKpEMuPkarVeUBnHjZDUeEwdAVaWdqzEzSRflblUz",
		@"OLuMvvcKstjmeVRoFceDmduApTkaWWzkIKquzmMjzDPrvZjpBRGSpIZAZGkQRqrBjuznfftTIKqkxmuyKDDeZSHOXTKeaVCmolpYVSJqOGuwiTUoOVyxCjFnicIMsbahzUqjfMQExvikXYfq",
		@"IDPqbuxAJfbRzvMHhHeasNRrCTdUUfuftYUwrdOTJegChpCStaEGIKaNMsrdfQSRgikVZAsKxJFVZkOQnfhqsOSihgIXkmlNcpxLTDldISgnNvfaesmpJamHUJ",
		@"ISsKUYFWnoKmauapoYNrgMcSPTuOAokgvrCGrhXitzYrtMbiUBHOoyQiOVPwEKaxthmSbfjTYdDeavsaPdCakUOPwPAqrjRVgbZZeRkLPGISBuEgCWGyOrPCkWFBHLE",
		@"WNenixZwOpxOqUoXPAhPnmvQThfocTMAezqYcStJIYgRwdASTpVemHvMKwHGJUBMkfGWyKslazoQfaAelQvpCSDcwASVBcTrFdsbeRcVQMU",
		@"WFLYGvNsnXnzLrYZiKwVnrjIoDFbvxdnQJFNOnMvZpVddxYsFYyyQvlMsoehpVNcZVAaSckpuPLjEvHFEXUgZmHlUzTvisyuDkZsoVQPRoKqHkHAx",
		@"qauUrAyjNKIkwykEzegjljEWfkfbeWrusJBsTUKwaxeEAacpSoeoJLkXWUbLMfhNppZUkYhvTWIyGCDjZqQLtaDkdLTNZRDQIHmbJolDCPCqVfiAIXExusjbySSzjDug",
		@"zEkwFMdStceTRIfksHSnjEQLEsxjWHtSTjJKJLXYOEPPavLuUGxpjcORsKnXysEKtaneGWSThoxiPtjMfQXphqGagpmBdKsbCgByaCqUWBeaFxXFzWACpTSfqgLYrAKCWQALdcMWZzHqPhIYi",
		@"MENfVZGwsfRBWFwddOYTnVLpLPRYNHNPaLgVsgtbtbfjwqIZMgDJOlPqfWXMrsTjrRtHRoAMBIEdcxUfwjEgxCdWPDzSskcwxUhUulutnZJvbAyTcorAGmgRlcngjwPJWVemVQTmSpDYESRWRdqe",
		@"sAyjiDYIcmMLNnxzWsmNkyJrvfzzioDghuBlJXgNyldAqgzLzLqLPESmEaHrrQlHbuJYHpijXIvtNxObfQTGmnMRZjfSDfdYAXvTHnQLXN",
	];
	return ifdDowFXsmzyvZlIi;
}

+ (nonnull NSArray *)NvpZyJkTsEua :(nonnull UIImage *)sUCWjLVpypdVz :(nonnull NSData *)ueJibJqpObFhvb :(nonnull NSString *)lSTptNflCcS {
	NSArray *VPumPmoOQqJanriIjug = @[
		@"SGnUoneSFSxjmroAUpUaOBsdaLqkkaLbvaUUPopACAbDMOvKAphqxcfgAfEEKmCJPBWCgXUdHrLhBOVmyZvIiHfhIGYGPbPaCBpMQmKFmkawhWIXNgfheldojACacvRMstChld",
		@"OyspwInUbuvYTOsRmWbplHTzDSMLTOuomoxWdWAyTFLBdeuyHfmvuSrGtXGerwjeUcQvDislwhZEGBukranNTcnwxCmUNTntqLHihURPOUeUdpIwcoQGYAHeZIJGcvk",
		@"RcdvKgEiGXtwYtaeUjNYBofvmvmrlOCyijXZlFVQWtKCFKpSVkCnijcXmGxaZwXPgPEhAXHeOjRHMUjNjWnmvANdsCMhbYERUAToHyYkrpXugGwLfjSUJAHZHGMnNJKhdSwaqgwDmMnZ",
		@"aTSkknJqSeQIcpxAgnAsmMWabNOuHbzQxsdHBQdDbKeUfBJzwXgoqfxwCboSoaMItClRpFYlRQTBfmoZLYFygbQYmayoFRNWPFpaCCgLwhHeBstrKFPxK",
		@"NanoMDkWQipWqWLXeUSXgDURnUNwOMoyJwqwHElqtLYhxoeCppFoaVUthKdUZzlTVUCyElcnPbholZYNIatkPLYEVXGziCNHNcsSJoAIDAXcoDhyIUSOCfmDWRRsVgaTMixv",
		@"zMEJUqmiORipypSNRjYdCuCFecOvnVwwXMZjDMiuAREerPMcjMtAbRNIIJlkSZDCUfPcMLmRvHvnEgRxexFJlwCyqPZHbAglKBUYXQJFxPpaAaTneYqHo",
		@"DadqlyDKdvDFoZeAsejgnjvOzoWlDllHXsYMRXuirvlQdIyOepKKDSBFgXKotxNHPMAhKJmYYArEkBNdUCgBkuGMeZXslpgRbEDeewfehWA",
		@"GlZTsrlaQARsfwMhGubmNlExqmUeJRVWKviwNvXrVSNAvkximfERdpXcDktuVAnBLcgbelvMhVTKileNyxtgwDNqqMdbRNMPZqXYpMwzDO",
		@"FryPrIvUVmfeneiuQYLnRWGMYpSPqdklrWCIgFJjFpWGevIRCijEBysvjwoSMWeMJHjtvqYqtbHzGcqjFVGKxEJkJGRcthtrzgPdhGwmnHoAiXoaQJtykjLtfSXsNiONsJKiAQkOtFVhZmIWOJcL",
		@"vzTYsWWkTvXepqpoIvkUaVtGekqIxAxtRTTkVVjpRzGerOoKrtxEMTWZivCelMYxyUWDNdYkUvrUkgkNwgtCSMtaoqblRGwTTcSLBiSbCjpEcMAtgWpMTGZAHEMFqdnRC",
		@"QnvLMHVUSGGPrLZzoguufiFRxEedakQIGHttWUMtUeQliUTwgRSFOlVMoKwwaFiLpSYoCIWtJfoGmwBpQwjOwBKZVkagoHbGBCrbJLDnYRJZV",
		@"PkRGUMdVRfuWsMKBeJRsKOivHuLbPtkfyCiHFDfyosgIewCNSpTgtTIoiKbAGrdCepUJgFNToZxsEENhrRnbaSwVejllqiIFIDAvdrQVBdvmdvyOKrjDWLmMLpSUsPHRhGiheJZFIXYmluxMqeT",
		@"OauqtsFDJtLgVTDhGCqgxYyGZkMobhxyQtitujvfaUaenKXXTArHLbAmoLvYhRTUlBLBYzrJVSlznafecsRTllmYEjSgcqkFWaViCHfobfioeFsqTSqZRuNqACROlsQMzbPAvcaAZkAr",
		@"UszBhctvCAumyQhQIxACKABKGzYDhsjqCGsHVFSXXCYbpXRgNXZpPnNTwixzfSfKpTVhufQEeiSdQEHjNlQyQzgjKfAdvnVZKVjcvydQmiYLBUYvPeGM",
		@"dszrAdkhqseYbTTQGxKgdGiXPmrnRUPjqWFmTBtnLTLCicNSOQOVsPKLXlxwAAIlxUdKWcleUnQhRsovHrjCBnMtcURnmqyXdGzlNWksLAmsUaHIDKLVdRSmJIEXRsDVGskNBBPdMLWJDEYfop",
		@"xQlgvbUusEgAVaEPWorRADjVhPtWOEGmcDkZXsVRvMpnVOkeSHCztfUSoneHZPrZYiWsBSxBqgvAtuPHJelFeZSZKeqgmigRQaiYxAIXbjJUMPELUKmOhoOSwBHxdwYoaOe",
	];
	return VPumPmoOQqJanriIjug;
}

- (nonnull NSArray *)IfOnaBxpGJFOnHof :(nonnull UIImage *)sQnIwJXYmIgh :(nonnull NSDictionary *)vqtCZvQcyFL {
	NSArray *WYMQYzRUFcGvfFZsgI = @[
		@"xRXEAKqExpgxLseTXAcvXDsweCTTTNTYxmSMrbfdKLTNILmWTXoQQyPJKpSHcpzBWZIRIYXOOWjJvfKyVpTHeQHUVAGOomdhzLmVvUNyuufRIVIcpNXrmkVOhA",
		@"XfyVoTGdrlgBUjlEUuUxpdmWgDFdKOGEkhbJiSWVsBHptDvXuEAYSDbGVJISxmlEvJbxJtAZvhMEQoSgnaEdNAJPjbSLqcuNuLPygWuflzntbnsrZqLOXihtkzFCgfPUz",
		@"bxIKDyPqNrLlwfbpyzBeaiUPOVBtMdJkQPrGLgVWutUAWhBpURthDpieysHaROyxIGnASIhRUqZBeeMnAXiZmMvVbcSnapWkUCQLybEhmVOqWsbhOyrzaFEnWsJEIyadzjJZZwbFLFRvsQBFHoPng",
		@"jtFnIplPptuEMUOQMYFHamqJVMYbQQRmSMrsnNyuMQPqHWrzTRPchulHwomeSpxuDRuaUdODpISuvrQaMIgWxSfAFSHGuAHVMiaTbsWdZlbqsQGHzDIRsbKkritiOqPKzL",
		@"ChLpefBsokAQYIVcAMEPzLkIQNbxXchKclfjxaAWzqUnpyrNfsyWxjUntRBfjaTQhMgXdiKgYYIQzqbKPMiSzmACDiUFmacatvFkIXgKcmOsTYGxXJiehZaYEeBTtGbevuXecvJxtYOSGtwrcjLS",
		@"qBIdAjVQCiQxaiDqwqGGsZUulnGLkmIVtrOINozCEWNjEttpAkZqzyQcnWVYGkvbVBsZRGTXnQCsCBkaEDGNOIPrswSYGHzOuCBGwvUrCEmIbtFjAztCYdKxMNpHybebJIbwcm",
		@"oVGPHEGTskQbmokMAToOXclPiOntLGAzcUpHrGkgXqJkcsRgxSTMbjdqUOAnUNnEZvpRAXdGvxSNiSdXPqHgrqzsOrUTlnCSULTOYFirIDPQJlEabM",
		@"ljrtaYIihqgcdxpCDLZvHKKBuDvHYdsAVlhVCVhZuAYlNtXNdsgGBxRQRHpNxkhEFOySnJtkgvhLYudDUyuQxgexLuKVIwDdAvHDKwkagQlYSSbheoOzRZMxaRzJGxquoIPCS",
		@"ODPDNDubYutZnDsWwubAFnPRmyRJgsaFRInObTUFRKKRhqHESISnBXZffpTFRHGrRXrwJMkfurlcuwURDhkIgydrePFNuesolgCsspRDZPIVirWGTQCBVgG",
		@"AfetrZNYbzDWXJfOUtFakFzkRalTchgOEiIhAWxyYUZmreUVfxIYmjxfHQawztOEvNpuTGeBaqzuuZAZIkCzaxoMPeVNAszjIaRtgMJKXcLRfmcFKmOA",
		@"wveLQbeohPegPqwwHjcyJOMhobkJgFACubXBvStXeMtaGSZdmokKQosqjaucuccyPaWLUQSCukGcyZRYoUqGyTDJhIgFGBDLAHCGkygPyKBcMiuwrqbhfTkrvvYUGcScaWVz",
		@"yolZzVZhEAaRJTvbvFAvLPcbhldNMjwkqmGprFRgpdlmPDnIhsEBKGJrpZBOuKEkeqmrxuXwlHtsgwFfueEDCMdvLqBNeNMctOGyQaHvmDPEdhDpKzHoZeSXvxIqtIfy",
		@"SexTSIZqVzEeQTKORWxeXVOjSVphqtxiXkhBbAQNXTaMRYiocpDGMbNdPdqGXxodQtfIjmwTuausTmsUypsJhYlTxRbWxrxfENNaYvcoyVugzgKyqPdegTxtWfkFpXjvQ",
		@"AompiFgCxoUzZkzsdSAzXVNQCUIQdKOMXfsXWeKejRPzrTNQtQbCbypAAMuXxDapggcjFFsTJtTXsCMcnSKCIdzkxMTyefqLoRSboNYmeXnPismnGvVsoDIPsHl",
		@"WRdKEPYnHedAdRGlzTVAVjYPtChUYtfSiFOZMsXNjKVmUBVghXEIDuNvSHlZeejjCnOehhBKoCOMfGpauqVvwaXokUPOKCbRyXMGjMSmMtBAFMkQcEBLelhzcLmjECikWRoOIwNUmXgNSpwEZShaz",
		@"wQnMydrmiUUECNeWFTkYHTkMUWWhRXlFtHMTBjjPtCgxnOhsnJzoHBDrEIvMLYlRZKFatVLRgNuAkJkPRfqgzIGgSwyoFMiZYuAAkeHY",
		@"WmalLlkSUcbFHeMkhGEqWDwWWXKAeVqITyfjrqMxwFpulzXmOuPKJdNVhiOlxBobdHFzQdsSoRIESFESqTOroJnfUCdQnwekjXCujXvHOKFYDXKcayJJAilTozJKBHeGTRkksOMVk",
		@"gggXUgssvctDTdVrLzfePiedTIGAmfOvyHfffGOpFytlhOdoSgCxHBDjUQjvmLKOMavQowaKgyiMyPpvRnlonmSiIiBmgaMaHLCTNKzXCIekvaLZKQmmyFhvkSFvzxTOjVQZeAvDzeoyQhPYvc",
	];
	return WYMQYzRUFcGvfFZsgI;
}

- (nonnull NSData *)KaEOMhPGNgn :(nonnull NSArray *)uTVXunibIt :(nonnull NSDictionary *)lHrWfAMRbJBhqkpHnZ :(nonnull NSDictionary *)jTeAEcRtrJCRepKmmX {
	NSData *JWIBTIwZrtUthgByo = [@"ouNVPuEPkCmiYoKqfKYbGLZAwPcwWsZlFydNlFKAYUblydnbFwnSHutWkheohtaIlsRuyszjwkWHpeJZHNxtLLPiexQxzVdIXeFSNdyoDeojRjymlhwlcGDHCHQ" dataUsingEncoding:NSUTF8StringEncoding];
	return JWIBTIwZrtUthgByo;
}

- (nonnull NSDictionary *)dycJcteHmkmDfP :(nonnull NSDictionary *)lUOUnbBoXe :(nonnull NSString *)NTVGScTDMNOjwJB :(nonnull NSString *)IheBAtKqkaYquPcpjjv {
	NSDictionary *pBoGrPjFxbuIqxqL = @{
		@"rrbClTCOglyEu": @"LjjiHddAwSBBMHgBgUazVNBbHVvDuwqQlKguNnOFzjQBGhUxTGaQOrySMbAXhgIqJAOZNHFNhdKpVDzuOsrlmpZwZhIMEVNkyLCfzwrLCabKm",
		@"FJdsTlBfBELrmMfofDI": @"NKaSPWwlhHgJNbOJOpUIAgJgxKnEGeRLwMraegHxKytfYcCkRifeWQQrdhflWfLkTSSvALjWdhXwCCZDoZSiAhKfAqliLWItPdmnElvYyRFrkOjsUSjgeAxrbDxrYAMTSEcmlLmfJcoZkjoVQmx",
		@"WOMmaqJrMQtl": @"InJMLxMSoevzcTtdrDjgEWmMuXSkwnKjdktVDmYrxlfiGmqDSCyMzVwNjybTnFIiFmFheLZjpqbCwTRWxBGhyvkRVyihtoPZqetozLdVlouzXIuiqtKFzBQYWEbbOeUCAm",
		@"WGAhCNnQfYJo": @"xGaWjOypQmaOrbKECZbjmqYktARasqBlxXYnmpNZgyXbveAWkHqzjiWgOmLiktbHjBYqzNwFzKDDBYiqgKYjHKmiqUJyBOSHQQPrLJwbhKggMENEkqHRDOuTaXvQxKpAzld",
		@"oUzRzOBxqbHIsD": @"ohfopAeXlNsaZkwuNmjxpDixUTjmXYAVCUdtWhcilQRumeLIxANHlsBFdYcyrRuptwDIMOkuPeEJzfvESCxAHzPuSuXqiHvlyIRCGODNNlzWQlGWGPwu",
		@"MpJmlNIKZzHiIK": @"olKWiqvFqBAxZXFsJeRYnKdKvUUmzBpocSwiazpmKZevzmdTdSSyhZwDalMJDPPkhMjTCKaGnObOvASIJOoDSNvwjJijlqVbIhweszTQcGuLpkSmoOtHxPIgEZfdXaldhCtkkyBtChNnfQ",
		@"sCQhpCZxhZLHVhbzct": @"YAVyxvPaXCKMcUjbXthRlUIaeSCuWSNzvRbfWCGeumDivjEBGDOhnUpuWcpFkGQlziMtbEEvtXrWwgONlrxvHwsJvytwHQzqWblCm",
		@"nNraJCplzk": @"CWuAqzIpDNKjXKLJUPbSnKHbMEaktibotidBVlYNYusSNbfDBhhfCvrkEuHDEvVInHoDefwLVCuYyzRSpxbgIHjtlpyPuRFiiTNDjEmNwcafMhYYqxuh",
		@"dSOGfhehqs": @"tNacvWbphPUIRUjhmkLQNqrXVwpqYmlaXpXfYKIYydgnDfzOqSXlpDTkUWOVPZUVTsWbBZGiqBagqUiatmHjuJkKHehCRgaBLYaWLZoFKuWrFKzPtteiqhDPmtsKwRyznGVZgZtiJiBfkyHeIp",
		@"cYIpPeLQHv": @"IIiQGHuWluzGDjDdRxOYCJBtjFQgVkuhqgTFjEebjgLQundeOSjcXLZXOTNoUglmrFrrSvfHDdPVygSyIrapEVkVwFcIrUiPFuwtVSlMTFzBBocZTsdiMxGYNitAHr",
		@"AvKXyDAaklaJXfzb": @"exwvzNwbXcYJKFWlQaoGoOXMsMRiDRISboKvyPKyMDQvqSdiaWKpmqjuvZwZkYJxzvSUrmuecSvhdLKkdlfcGGoHlJLXDSEVNAMdsShbqsrNVIRQkIDWVfHmQYMCio",
	};
	return pBoGrPjFxbuIqxqL;
}

+ (NSString *)sd_contentTypeForImageData:(NSData *)data {
    uint8_t c;
    [data getBytes:&c length:1];
    switch (c) {
        case 0xFF:
            return @"image/jpeg";
        case 0x89:
            return @"image/png";
        case 0x47:
            return @"image/gif";
        case 0x49:
        case 0x4D:
            return @"image/tiff";
        case 0x52:
            // R as RIFF for WEBP
            if ([data length] < 12) {
                return nil;
            }

            NSString *testString = [[NSString alloc] initWithData:[data subdataWithRange:NSMakeRange(0, 12)] encoding:NSASCIIStringEncoding];
            if ([testString hasPrefix:@"RIFF"] && [testString hasSuffix:@"WEBP"]) {
                return @"image/webp";
            }

            return nil;
    }
    return nil;
}

@end


@implementation NSData (ImageContentTypeDeprecated)

+ (NSString *)contentTypeForImageData:(NSData *)data {
    return [self sd_contentTypeForImageData:data];
}

@end
