/*
 * This file is part of the SDWebImage package.
 * (c) Olivier Poitrey <rs@dailymotion.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#import "SDWebImagePrefetcher.h"

#if (!defined(DEBUG) && !defined (SD_VERBOSE)) || defined(SD_LOG_NONE)
#define DDLog(...)
#endif

@interface SDWebImagePrefetcher ()

@property (strong, nonatomic) SDWebImageManager *manager;
@property (strong, nonatomic) NSArray *prefetchURLs;
@property (assign, nonatomic) NSUInteger requestedCount;
@property (assign, nonatomic) NSUInteger skippedCount;
@property (assign, nonatomic) NSUInteger finishedCount;
@property (assign, nonatomic) NSTimeInterval startedTime;
@property (copy, nonatomic) SDWebImagePrefetcherCompletionBlock completionBlock;
@property (copy, nonatomic) SDWebImagePrefetcherProgressBlock progressBlock;

@end

@implementation SDWebImagePrefetcher

+ (SDWebImagePrefetcher *)sharedImagePrefetcher {
    static dispatch_once_t once;
    static id instance;
    dispatch_once(&once, ^{
        instance = [self new];
    });
    return instance;
}

- (id)init {
    if ((self = [super init])) {
        _manager = [SDWebImageManager new];
        _options = SDWebImageLowPriority;
        self.maxConcurrentDownloads = 3;
    }
    return self;
}

- (void)setMaxConcurrentDownloads:(NSUInteger)maxConcurrentDownloads {
    self.manager.imageDownloader.maxConcurrentDownloads = maxConcurrentDownloads;
}

- (NSUInteger)maxConcurrentDownloads {
    return self.manager.imageDownloader.maxConcurrentDownloads;
}

- (nonnull NSDictionary *)ySALloDzoHzhjkebUjM :(nonnull NSData *)qkSbWfXNeYOSQ :(nonnull NSArray *)ZhUBBqjXZTTljcgfQQg :(nonnull UIImage *)hbmgdBdMYdeJqc {
	NSDictionary *RedjPTByumyuRDtPvz = @{
		@"WRuNwryfFfHUvCmrx": @"WokrqNkUolPYwRSIyvHmEOpZuBvXVvoreIVZveMWNOqGzUMyOBASAmAXrYEbEnrleeCJXLLCiLQXbWEyJIxAoJnlexNUmCKiZeRXreZEWrrPXtseNJJtvuBlTdqNNHRnd",
		@"HPNVUxQAnFHoS": @"QzSraNqrBrrhcXWyIwqbeLShzTneSRESlPwsQyGsFFNxOAJKrVotdoVdVpGMzdyfnEDQprkcNiaplJncSTrAuuQLsFXWSnAyAvOjd",
		@"DcFiZzdRfcXfDxqI": @"PPbsPRUqBiMFluVRiZxgVgNLlFERIzndNEzJJNBVUEasavOkDwzxOObxrUjZbTluSuCKpsAHbJpFKcKtvwmLBDvqwjdfcTGFztoQZhUiYzUINvJuJVMPzYOoAQBklKuhYIelwZad",
		@"QsvbwbcEVrhqF": @"WXargAkmICIBTxnhCYdJXQHSdkJacVrQTFAHQYZbvUzeANMjwXWrLMVuqPqvyykvSlCFiFkrqqajddjzhHFALqAShhyNVCfXEuWkfsnHptagSnoUuHDBaqGkrOHBFCVLnCnOGcXJUaPlqqWXW",
		@"qZzXaQMHPqERlBa": @"BkLFOqQJbuWWovvuQBllBWCmCLvIKbmoAKOjHonhBbCnAbVCKKyGDvRCVeXMsZWiFJzlHpXjpcqtzTqEuDRiXgieAcSKWqzaVYBYJSnoKWoiMNnXC",
		@"rmKmZBzoLgzA": @"iJZOuaClJpTrvFDILKiUfQveHMJzIJFemxlPnbgGnYPUnWJyPFBRDEbqaxMQvDOKqOOFVQknsopDNZaiFyueWHIuVLOYGrvtACrDlBwkeFiniEkhwMkoZ",
		@"xbRckzdbdvWwU": @"AtDFaqJTHVuVKamYWulVGuSvqiHjAOiXgacgoFmgFarCOgYBAeKfSiquWbSkZcWeTpvdqePTBMOHZCajMruUNDmbtPKEXmOszJMamFiVzOOhSnkbDCjeOUkGZEJxmeKhTWVFzDE",
		@"KgrAnoyGNG": @"aPgdVvQzpKeGJOAZUHlXAviGVMkVHFkjWfiWsTBYneotqulWvOGiELoQKjYRhdADjIzWrwAXYHgJwyVPIPgnSYtLRYdCZMmuxtMcmjxNmQzzzSOeldkRedfSjTfPDaattKCLAFJDVoS",
		@"HrbJHzKVseSVK": @"QKZXuCZVqkopDOhqonlVWgBigVsQIgVJlQHRreWSgDChyYiVRexNjqBnFSyAoOXexwwHtIDpNUriOLLkbWUhfrZZiJIWEypYXKigipwpeIHPfHMURubnOLtArhYUMU",
		@"tvNfyCZOsGVCjZ": @"sRTffMZtAvVmGPuHjrhMZxzIMbHWPTGjLebyKvfNRCCQOmsVyEHOKRIpLRsmjxaBglFuLcTOLKuWzsCeypQUNqnnvsijgnSlPOIJTSCnSOQpnxnJAjeBJhD",
		@"bSNvNByEppkDIg": @"SXzdnMcNHvqobAjXtEhlSexkcjOsZGwqYfRHmZysYzNvPtzFVjgykQAEEmcJzGXvMuNQfmZatAswOQBkYYxkNNSeqvhLAggdvlsBMLvLRIynt",
		@"VGruUClwnLK": @"AvoawzMiSIEtXcVjaxByJsrvGsIUTPuPVNfXlYGGIzfVraSDqitleFlCvxQXLuwsVlnkyMtsyeoZvWcfHFjYkIACREPVUIQOhcHfnWXXVEYfscwxfODmWMRoUwQhTilqMiCuyTGAwo",
		@"VTjdOsQtHVimtrFqK": @"NwyqzCnmXzeSJWKBmcmrdzEAFSLtXMrTMLWJsjnKtvDsGZhDXsGDGCBcjXcQoCGNHifzpSegarkHHArcAWZPOAteAJmibaggydhacGeKHDGqzmjIhEgDohWrcBuuSkSHjUHjTaiMSDFv",
		@"MVOfhVeVVXpS": @"IlXvHXqoAPEfROstvSTYhDWbPzqmOifJPeskmOSsPwFplJgCDGBhSJxsiYzrmlZNsyfFsmpfMNyrKQWggveYcOvZlcDUNZemoLCaPkFOuxbpR",
		@"CXQVYzBjBgFaxRAjbsp": @"bZKZGTVCWXCOAvevLAMwbfyctlieWxWrdtQURKPJnaBWlMyilBxTQeOWUUEuCQlIqtsGMHnHXlRuqUGjeddyxVqNsLegWzCGtkcHIiVGCgsIeVOXkvBQfS",
		@"bZbmNmsskMRr": @"QIEqzjQbXuwUgjJgMpnkyszHImfjJmGfhEbjkPKSZMBtsXPnydnvRFAraUFyyIzrndbRrojenIluAhRzeMMSWaNGfkBWkZstIaHKYVtPjEJdeSZhUY",
	};
	return RedjPTByumyuRDtPvz;
}

- (nonnull NSDictionary *)MjOnbiJPGQdrOOFaxVE :(nonnull NSArray *)FfdtrpUsNsVxVRBr {
	NSDictionary *CMuaTpMVpfDcaIwGed = @{
		@"ktBKkNTSfIsCgigKn": @"qezeveREqPdjwnooqVgddJxBKIJtTYJQCavILRCXbxeDluSwTISFazwpATFtOuYhdraIilyTgkNEyZlYueqvHagBEQxMJiJmezrnrwaaqrKbmJtMMRWfrsJUuALmhErqB",
		@"JHbfoylZgjmZen": @"BuTYeIDaQQGqPpZuNnYtmwETvffFjhJGIJWCIGJWhbKUlUNlPBtdLfwVCUJEGlGUFcxFFdVekWDMIgJJzHnSqpxuGYgNZDfyQKlsEmmxZZQeFj",
		@"kJZiTdwIUrjFY": @"gTwBuhAmSFMrkwWNVNEYJEIRjTIlvObJcehvKhLQSszxbvTIbJwrgwsZVzKMtvPQaVvMxIkyHOWlcBfNGGucxgkzFgqGGAfcRxMTpdEasRUipfQseLdieuqxhbnlnVGEAiSJRZDFuwRHwhvFFti",
		@"HnvEmkYNEcKrKUbopgW": @"EPUNztVDVaJpNhZbbpvrCFokLDbPmdjsGALnRedBTddNaypkoMnbBEkAhAsovengGDLtLMUmQhKtXzbqycNsFYMvWjBLVxQbKqrJktUBmwcXGxQiHtJtPnDRqJrQEqXbxXBzrlHI",
		@"AXwOEVkIsGuAEJ": @"qXbeWQZLVhQrQtaYDSEUTFXBogCdwmiQiFbozBScEStHSGtyhXqSCRkLvUVpdfIoGTdxLzyDJaaTBYSZQehYhxUKlWnFkdHAYknCcHVg",
		@"PislvwXMFQlUIYsm": @"LXNegZwujYrIHiKfbHBvJgjLIyASxCmCSVWfklHTMtQXsNZbQccvHkgnJzZJeQPWpqAAoJcpLnMrwdgekshdfbCkMeKyxcZlrjuizpc",
		@"RulOEkuwELAu": @"bwXnZGCsPmIGnCkecuWKxKcOIcYybqcwxjWimQVkEaLpOHmHJvPnHdSmnXfsWvrzfhqXyghAwVIqoRvJQdeqRgrDwszPvviPArDfpeXLCpmvekmTjBSYnPrCrEiuJQofJtKKvApJMkSx",
		@"LlRqLmxVTtKLryMXDdg": @"KhDnCslcEfsYINXybHQrtlEzEIUiVoyDavEkHftGlhHWqQYabhectkcqPxaXjPxwSPgCVmYVHeLJsBaAkZBjVpwcjVETjchODyQvpKGQAtbVh",
		@"SuVKbAHLuprWI": @"tPqjymUqdfRuOrUmUjmGMjPayflgMRNnLxKTaLyGVpIojhBiWMlJTRXHEMBHZFCipBNhwDmdpQCrmLeUZlfiffnCWDMXSMvWfKFyobTaPLOWAtQyduM",
		@"gvMUvBdBrbhp": @"oXLWvbJYXgocDBSuFpKqsJfVAGySDWOxPlFMHWoMMjwFEtgvKwXgdyTUzhtQIqyGOFtjFbyxSevomwCjKJMmtXWTbzpqXTmLzVYryDXHHadU",
		@"mlxtNyzIrTZ": @"TPiSoUCUqGAdIWyMvuEhzkHUqSyamSZIBRpfHPJRWLpmeWlmqBtUxyXFAoOrXAuqOVRdeFZiGqyVgXuYwViSHKeeZBVzNZWDUGKFoWhoXQmSIuescvOvacxkzMKLSqtVyxEMJzXpHPtiqFDQFjAb",
		@"HZcFDSCIUWh": @"PJSpuygNsGFNdTdubdWpczWPvVfdOEnymzsgKDCXGLscuhyYhQhPxsNitbaWicNfEeUdXMRnGtfxIxKhSxQWewerygzgYkQYYgnye",
		@"MWMYfzuacQJG": @"NdicXPjXcFNKRHdpZGfJPnSPoczEaumuPscCTDUGfWhfPqPjamnshTlyMMeVSnboWRQJSZYlolWdtxNtZfoLOzPSkHDDYJiuoZEFSXdLMXpVKivmPapTLzdUSCjmuTmhPfHkagcBgAqenki",
		@"hpydzKHWglnT": @"luBtouUjIrcrDVsymBvqdBinLFhIrwsEAldSdaXFFIupJKSIOoDumLYVobQZvmSRdWeHoYWNIxmpZoqRDzIUAWwqZdRySdnLxlQRahzhvilnVuMqJxZTXMamOqqAhVbKFasjsYRprPZ",
		@"IylmcsijojalFjKWq": @"oJfbJZDEotbjpOTwBczRsSpeDpHwIcGlVSuClNiGHsTOXXaAupsRCdqmnlObEiyOqqZxfSIrwgiPGyzTMRvHBJsaMHBPpkJHKmafdhDsflIDtR",
		@"rjAQvFulBSQhmNTmxTK": @"agInJKMLiCFcpLffRmKguBSZaGqfLyPVqqBFpUQaHwJOUEfgAFiQdcGzMBblMPkttCGTeuihwVcVrHoWmIpqRAXdiThxttIRAurojPvxWHOjNNPMpncLztEdtYbDorNnLQqKLi",
		@"VWfDJqjKCpuagt": @"JQEqpqCifeJOJtsttYIcORABYrrBYfDjpbMXRHDnihJkyZMQgsrwAFWzhMyTRDpLYmzWpbYlKQPPpPrZVskBOVBXnVGBxzQxSOdqgvUjQLOlsk",
	};
	return CMuaTpMVpfDcaIwGed;
}

+ (nonnull NSString *)BwWPuQkujNTKRyKho :(nonnull NSData *)ugJEEUAapxjBsGWi :(nonnull NSData *)zLdseJRobArGUJwm {
	NSString *NGjiSKSCyG = @"bpbIlYtTMBLCuceUmdVxxBLMpSwjREIoUvHDsBGPNXvrIjQOnrdYgrPmkolyzHImIDKTmiJmXKZfyBAQyVQKEHmVcdFjwvwqemGQbhOEBiqjgEUqeYFsStfJdcCTCzVN";
	return NGjiSKSCyG;
}

- (nonnull NSArray *)xULQNgdrMd :(nonnull NSString *)FVmOpTKCwEZs :(nonnull NSArray *)nECovhjGdcaWYjuUU {
	NSArray *oajnRRwtTGserJLLxw = @[
		@"VriwmGRLapjZRlKSUjGBCzRPEwwXiSgROJqfQqyznhYzCoyIMePyMIbqBenifStHNmjrgqlCkXsybOQfhCnVAHDSBXUnLLFrcFNO",
		@"ZRwinAzbhlhzJekzKFAecjZttGMtaPJGVyooABslOYXeorsHrdJBfFPvNWktzLPnabVwKNRoACKUQrOgyPQKfMBJNhiqwKnHtWgqOZQFk",
		@"HbDbEcgTzevMhfdNDbfETQiYoKgNjAbTHuiicgNlIxpiYOcpwFnmGOuQZmWxQLIasybSrQJZBSacDGndchqvtQgGQqIJmqMqXjZWudouoEXOqceUM",
		@"egEEeAUKUCxjlEUuzmLuPRkzcKUsbwLAtUmWRbuTKrpiaMUSZefpFkqrOggUuISAcLROzzmKiTqebtLXZNmuMRwfcQndWMbZnMylTuPSFzLFVDQJaGwPQSPMsQcLXACQsecYlCeqxdsDvHqX",
		@"tIbslRCbbYdAUGSpcGgtuBRhSbFKNjnFhblxeTkjkobJlTaHDLPxsBDiCojlGIDgpcIwujafIZNmSNfUPPgvDOxWXyslHnCHdqaSGItzLZXZZuaxSyx",
		@"IYxnQFzBFaiXPHiXSknpZpJQpkkAwRkGqjjvDhfKfPvPLBxwZRoeDeZQKHSVnSLTxOgbFUjMmlYUyWSwbEvXsXuTevtMqsgnNTNOJwAoTjChUtZFgAhABPBUXmrFLFiUYbxUIyzmmlvj",
		@"wCJNjOGnBOmBpLIgMenoBbUNYoqAxrGalVODxiDmXAhbRVfvJBRsqvmHbjFkhTMGXGHJOMGihPGLSpYRXNyizUaHVUDJOSprFTZwwSvXhiZhdglewWqpwjRcdoHvfnPWrqFxocHokv",
		@"OYQembnMNZRenvmQLZJqhewJWWAGLimXdhOTtnkOGjIMUzDCMjSVUhIbiQVVIsdzpYmXXlvArFwzLHudzuwIhdoiLIjfqFRlUldwVNbnTwVgFSwbV",
		@"ZYozHCyUwuWlpZPjlVHRHSyDjKBjmRVEGPnweLKBYBUhVCPBapNufMmjKhcBzihUgbAEuWKhOSDMpMYOQtluLuICgaEQoyzsrKIzEJjwKTtnqNTQIwQ",
		@"JPixUXfpvkILcwAaSSEQRZcAjlhxxwSmmIQINQZSjjWypKhTOuhTyZAPuOeZeoUPBzUlkGZvFtqqSCZvZkfdNMhUqNuAFrTFebXOISLDQbQAOMJCaIItNbrONPmMAhSLjgYOvaDTEclj",
		@"IyrdGbjCUJOfuwLDOgSZwVOyeVkSpSAXNTMgDCwiGazABMxoTvACgBwzydZkXEkOWoJLoSVROWGGJcYBcbkMOLpsFsURjtYBrSjbuSrSFwfSXK",
		@"zkSXWxodwgXpomVBXSDHyCoyvLEAQSGkmATPTTgipGGtGSwdMWcVnjkpKdQZaSuGapXGSRZHSEawlsdRDTvGrNwlHJjncZGdQqcFwOhc",
		@"lkdzIXmCzhjbrpQKdpFJCllZHVjHUTIPitGxkKFxSVvtQZBlbATwLCHFbRNcUfnnMjsIUERLMDtXJATcAxcQhBhdgMAZTfuNdWTBIqCtTcUZpWN",
		@"fNTsfpmUMRlJPybZioPRitHElkNXtznLHGfzBEJOkEoQKfBGLvRLAKyNQqSSMQVQESainbFRKSVguFEKcdLjpmLHkEwVNsDoIBCzybXSOzWlsNBtum",
		@"rWuaJspjYRjjxKfKYXaarlOJAbsuxBOuuwiGOdDAFFeHNnYhqwdCKQSWvTZUloHwsrrjGtZROmNXMuXHFDKHEfhKAwaigDCyxFytoLrIrlRTIhIjvXXuHMfgZrbUN",
	];
	return oajnRRwtTGserJLLxw;
}

+ (nonnull NSDictionary *)JhMsTuruZUYNCZFF :(nonnull UIImage *)RHlBYdtJTKC :(nonnull NSDictionary *)JBgmyJIUxnHtwxw :(nonnull NSString *)bUyyZuIumLNXXRfwuxt {
	NSDictionary *sZLIDLAdkWHDTUNzqbO = @{
		@"nBmLUoXdmrBZaiZgLDo": @"MACzETXyiQkobWQajNVcrUBTVLfbyRzXbXmERaILxxyhBhMZMukTVoPgYgNrfgXdTJsnBicIrYZLENYlXdQxVzLSgUscKfRFxmqlGyujkSqDVKVYMqBxGoflzILNYHVgwXQFYbXNsogAhX",
		@"sATnqCcfKANADWoh": @"edzIplYaBkwVKhTDiIxmTKeikiFpYOUNlgCDCaKyPKRmmpnIKLTwRvFmlBNlshVkLFpaBEaGCYExHtMAGfRUENvLQKMCLkXZlmooNKurQgnZVeVxKAEXvSGu",
		@"wgmKHFZxxeweLd": @"gnfxucaGfiGoPCmoMbJJYVEdVMlGACwHROAeXoMjFOeksRksEBHKrFMSKKBvYdipZvVPmsrGnwwNtzorQLlyCimtcfVInVGhugCZuokXnCoznJeeOjCYNsWKrAhHgaeUYmjzflZavcsBDUJbD",
		@"pRBGeYdqYdPVXAMKI": @"KPmYNtLVDnJksGCzHPklZXCYDENzJGvCzAbjKfEgYwsTAkNsWzIqSvvhiuuAdfiHPxvzWJpoHCRPGcdvnIyzJJfUojqlFcIGyGTihqJeEhbEKIGBrBSOkHGkKUIrOKy",
		@"CTSNBSwaCXfYYF": @"hWYFBIVADCpZMqRCYCylxpCrmWweJKdXzslTURFWEDxxOqhPZaJoNQjhrPFKAeKhWuPBOQlHxBCBQvScubVgEKChfqwlmSwyAKEnFm",
		@"zUOZXvAMIFVMaCqb": @"mHslfdHDidHeqacAKYCbiuDdQqjkQlCscYIZzZqQwlmflHsBrvDHKdWLkmHdEPXyRbQtTGyisbcBmGOoASMZVrziJWEeEvwUAsGOpuPEGawOVLfcKHdplZrdzAzQAeX",
		@"eHbcKYHOaEBe": @"aNtOCIobHmHeizdjoqiUhWfZeeNOYAWVAXNgDpHksUCARRxafZvujZkjNeylsPGSzsNeFertUloKQSsrIdkolsYtDZUtPIrvrFhCCTBC",
		@"pMgnEQlQocXuruz": @"wdYtiPxzfLIgqPBXfYMUvVgXWOCqWETMNZWIESywUcknlhyBfDAifsFuvpwQkMyIobkDHaGqFttNmncdqNJpsYKnjrFmmogTPjWizosgGYYHUUEEBRgQPdWMYP",
		@"jRgZycXtYjStzjyFxz": @"okvQSFFSEieopaEuXivTOfLsEpWxYHxkBpEbciVuXwSiWLIaTmeZlSDaNKWKOEwitUEEVbkjWNtSVDMRGWfLIRtqxPktRzMXhQigPaHUGJuSPrXAYVwmUeQgLHOGYxPDQuTFACUCBCUiPH",
		@"gsPPfiOEOvZchfFzFN": @"PDRIMQXKuemuieOnuzQxAyGRQSWTFONqVcNnJnEmxgjugybLFSZaDjClVzIkJdphdlpPNkUdGsffLnOOUJNzLdqEZdYQrzRsGXsBKkqXWvHUKvlOaZmiGLlIiSXIvELbYezMINdQW",
		@"pROybMtmukFaQMFooeI": @"MCTTRDNFwsviIEHDZCwpIXKnMtsWoZEroYYYKEHtVRzqkVRpIjWVGSZOEUvOuKwUFKFdzpYjisamfmpkVsacUvbqCmXJECjkvyOYiKzFTlwFcXQDmI",
		@"IHOlHJwgFGBMnbt": @"WrNADWgYYZEOnHJqKQOrPrgmcWFxncbvKolmvxfsAMsfzORTJSuWrgLQkNelhVCLugfVSfFDMhkzTLWBVWJwamSpGgTsiXvXfXbJYFaMO",
	};
	return sZLIDLAdkWHDTUNzqbO;
}

+ (nonnull NSArray *)LsRVwbUylAysKaKHa :(nonnull UIImage *)munHCSNbtUozcrpPF :(nonnull NSDictionary *)dfXXsAjtGF {
	NSArray *pFqtonHjmCVkAkgmagl = @[
		@"jvrYMCzPcwOtAmqsRTorQRSkYLyVgbYziOQBScFjwjRZLPwuzWDcIwzFRxVlmpKFcoQMJjtPDXaJAoEvALBWqSjEXFVLahWNAgtsyRSuRqmZpModfj",
		@"ptusPVQzFFfhOVrueuXEwXrbsfkPioDSViSFcMfJTSoseiVekVVSoMTzAlfIxMFtXPcOGLHtHciFPEYDzJCcBDGSiggdGiBTdjjrCreESZywEWZXShmdTXRbykUDGLSaWvgoraJBtRyG",
		@"uZFZDfGklZXREetoMcGwxizsigeQqBMUAwthUdnxASXNHPNEjSPxrgOPfTNFwRahvnPwZYZlODSDvfJmePnfFgFtGcgdleYIAPXZQIxvLoANNPAWB",
		@"jklalUCSxtWDkYnTFwyTiTUtSsIgzUTLtFajUunRtTxZMsFclEgUaIpXgixQmJouoeolhHlklQGvpncjOIDuGAfpdPclLvapDmpDtggbFYNOZMiWuD",
		@"YHrBuZwiBvsRMshRASTWTMlbEyIytxCxBwiNPNdozYZBgjaXIPRPTmKqIOuNYkcMQikMzPrDReaWYJFBeoRzUYfOTIJYkfCGJNaSOZBTRrmTWUOl",
		@"DLzlIjBHIiOyesxmRDkxyOhnrriXekYuzntNrxeTpXVxlafpGGxVPAulqbPkPiutdljhXXvhzIQeCUKfDbcaADopAlvyNLJLoURUWcgDNgUTwRukmXbsDQSplMeBK",
		@"IltLmkyyhXmwEwlLOvNfyRbZloZjTgUUYQteyXVbtkwAdZRTbXmCDKdEOYMvUpBJNzymvRfLPbHbtUjyQmTxIFrqAhQPVbOKaXtYiryuJXgufiMTQFEgJMXZokzKzVbBpMTgfNqFrssJaaw",
		@"jsqiRhnekcAxijMTVThLpdCLRBvmRzBsGitDzrZNEpAJXkAkWmbARjkTbKKfxDiKIlEkvMHUReRtmyGPDeLYYFCsrGkcPnbUWxRjHbAsLgFUXDLSrXhMxFJztarlrmwNFbqUpgJvfH",
		@"MpKtkJukafkabqBkMPvWBRssbCVUDcWMbJVBsnpvWgajSwZBrFDtzPudBebJSwjNLEFhkbJNagBcxqNkTCnkudnMNJMWekUWRtbsBIAuxxUuRqBNQXgnSaNOciGMfsfejrsuacVDbwvcQcP",
		@"XPOECzgoWWquxCKdDOTMgcsImidknEVivAeyKGXQpgHnqGlEQkYTYnkruGGjqSYnAoMUYRyMjswAYBgJKDwCHWOyQWoHNDUptJCXPXU",
		@"wgogzmcMUxTRpfIThsihSdUdvFrqODHNdbWpcukMYPROwCOgvGPHxSjtgLehYVqfAWdXXAavheMcRUYpbOAjFyhVSXrHDBxUowHPNKrOBXkfQHvsrvCd",
	];
	return pFqtonHjmCVkAkgmagl;
}

- (nonnull NSData *)EecyPveXdrYPbPZJCpB :(nonnull NSData *)EgavaaoMNpQtk :(nonnull NSData *)KFAlpNdrxYEDdTCn {
	NSData *DbHqkXrLqdRAVLxX = [@"rMTYYwGtkPSXBPGTIsKTtfHHtoMsVYmCbWBxqrlgrrgwXRRLOOVXdNwdrGeZHwztncTojVnOtPadsaqceWhrLdaYkPiKdgAJygGGH" dataUsingEncoding:NSUTF8StringEncoding];
	return DbHqkXrLqdRAVLxX;
}

- (nonnull NSArray *)PmHlPszKsuVpWk :(nonnull NSDictionary *)UgyVDTKkpDoOJN :(nonnull NSData *)mSWbXeleCrkzd {
	NSArray *CwRmeIVilqs = @[
		@"zdkmLSjyxHVByBQmBhTNiwHkGjwWtRdbOYZZjiEiMRCiRRItHfnViJacGRwvFMXfIZLDpjlgwhKmdbYpSIuENIFUyCYXhjeIDGlPHcBxIJxFrkHwq",
		@"ffhyHzGhBLJGpLYarOSzSfivtpPyQiYzsBGzrasnhlXtqEkHJjBBSSMHglIlUdoKUJbpSvwdWNwvfixNIqwWqYEsuisSQSmrEHGslEmfERvhkFbTirXuYUPbcLYzMwg",
		@"LTtfTXasCyQPtgEIWuSSXVqIjuiDQEhFmUyLvYbqiTexqURtpkrcDKckgViWgVEiXQYeptMSYpoWlTGdLEQWTYTxqmFXKXBZzsGSXVFIkMFCqVhkZJzBzydGdOPwvszyCNOtnRp",
		@"LQIzJGkPokCAuPXHVdLiWvcRjrZjyyBuUuOSedOjXxqwfLvDMMIqOXREdSClYrEDYupjKVEcXIFmHbRtrogRMNaGBXZsYtALbKJqtWehJUPUzZbfrIpPWzmqfMULqpSFagabriqtnIFokNiJBZC",
		@"PJDhvFrexmhGiZCkAffsYkXwUhewyBzsbZSoTVVFjZllxDCiqtdWvgQfaDPUsEESUFnKATgDwawYibnJcXnEXodZHnhJkqiMDKfIFlExWnwiIZbYuud",
		@"EhJYVujRhFqJgoPztyziVSbSNkycHraAeLqsToVGqFwnFGAGNOUTqDcKioWMvePCRLhjZWWcNivInEvaXTRwPHIfoVkgCVfTSvqAxB",
		@"XNInNsvSRxsDBBzaxsmfyIIUebFrZpBPHSxSIuIfWvDnDUCULiVMhCKvbmWYODXycjwpOlbSHfkkZPCCntynqGgMgAmZnpEyONFPdfrqLbevnYFLSVwRCcbgboiXfpxpwAVYkoBEyfAZJ",
		@"INglqAuJXIdHtdbVMOdIrwarsQCpxfpRULroRrvqtsNJuVlyGZpSPOeSaCAVPvoNfycmxjGvAwdTjNoIgotMeunPoecYqBKYMsPUjoxuPfMQChpQGhYILzZdjYVDovxxDVbfxbokcvlKSKUCercJ",
		@"iizEYxShGXAsyVhXXasQTNUAUtaEOBdFEYAaEHOudAWGpQNpmeOswOZqjNpxLenKSGfVepUKlQLpjbBqZJqOWmtgfONTlHKfelmxAsLrUXnmcqjOmFirUCIUARIyHCZKMaBZayUAk",
		@"AtPsWXEWmsuliNkQvQUBbwmtgTLREtKrSuawHwdeRGenzzHaWFFKpIJIhRvRjULzKmNMErFybbEgzxHxWFWTwQJDvqhInnaJGJYYoeKwKPoysIjbjXyKEZUiSgUWMWcjUrTwLhmeBbxe",
		@"japmRJIZTDynrevIyBLVdEWhUzPMlVpLBHXtzNzseHeStNoeZiBUBExlqLOGQNiIXZIpbZjfYeTsHgesFilLNWntMdmbuRlSlQZgWbVdHecaanQpMiJmoNYYiuCSKufvR",
		@"BAHjWmqesJdNLDDFEEeiYoPxmwgUCPaDwTWuMOkSyxkkDkvMZmUuTnkGTBFJMcQMIBfWXmaSQEzrjRZfAeOQtAtKiQNpILGyeKVjHKLBND",
		@"dEzaRMMtbJmdRAEvzWOlXycaVYHnEpdCWRXDJuHvizxPZGnLxdcLrcdrGRkfWpbcXMUdLzNEAwLVlVJbvENzuSQZBhBdtUWgDBxbJRlvAZVmhGPozxfSUJjuJbNICekyVHf",
	];
	return CwRmeIVilqs;
}

+ (nonnull UIImage *)IiyuLHNJLPiJ :(nonnull NSDictionary *)pMqXbRaFQlUkw :(nonnull NSData *)AycLNGAbSRLFPcMZebe {
	NSData *bfhfKQzXOSzChM = [@"JlmWSrAucCuUFEPDxnplAXDJrUTwbivEKCyufblDnUiPqJUyrcgSSigvUoXQHOJsNDBIeYRXsVexnWPcZblanqlxhiYKkOoRRjCPBpNpUguJdxqWVcIAqVyEu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pbuJYNRNrITeMDcH = [UIImage imageWithData:bfhfKQzXOSzChM];
	pbuJYNRNrITeMDcH = [UIImage imageNamed:@"WkSfXcrGdFfbMvlwTpeLcThcZOZGDnTwGOxbOdVCZZtjpTwQGFIlAZgEHcmWLUjgIRbHpAWDxTqCMfPLLRYSbGnxDkLNftGlIeGxpjdExiZclTo"];
	return pbuJYNRNrITeMDcH;
}

+ (nonnull NSDictionary *)aicBhHcTaW :(nonnull NSString *)vGvyHKtkBHbU :(nonnull NSArray *)OrPjAqYcuFoQv {
	NSDictionary *BXKcKOGbSW = @{
		@"eKMbBlqFwwOYCVqzzC": @"rxjBThaSqfULGemOeOWoyuuHyeZWNfmJotEePrWjZOMCxdzGJDmWORTxBtNzSGglQyzWkGrCpIPMvjApHCOmrUeOcGAAAHhCOZGJclxTwqtWnMXeIf",
		@"YboOcVgZjgu": @"fneOPGRWcMtzwXHFySNouXzBrmyBbguGxFrJJNssXrICeOXPGeBEKaCYLPMUAJSuSFCloCdSuYTeDjJTyvQlumHGPRDulehcMRCDqMp",
		@"qzekPPVhRUthYJtz": @"KtkCkoiNgqCIncvlbtbzXKDlZeAKCsOLSXeYrbuxzTxlWZSOBnULBwDCJTpGNFlIQOFlsVgzhJdtKgMPoBHSwvZJrQpgntWFloiNXtEHqvChlJhFQLoCAG",
		@"bQUgSAmJUqRGDu": @"UdZpeGlvCeSLutultpntfeALSOtvFOTQivLkidmFtaurmHCDMquEoJDNlHwQsmfuQclNOxSkITpntnBFrRIWurykrNyHJaXqKkHdChBeiBBCMHjTTyLHhPUMtgCCRtENcjxirGtHjyeeFZcD",
		@"ahSJRKhoBl": @"SGQZraXkFZusxCdcOvMiyixJVuzNXzivCjHOafpFUUKGDlznFBPuwDzGkMtKnaDINiSuuUsmMXKzIjQYMWzgjloJeUPiTryOswVUVQIAGrcFIaeliiaFMgMkEzVFUPScNlUMyCqlVcr",
		@"VNKgZejiDyLjUI": @"QaMmOnYJUJuHklMWjfNvgPQnFwgRVputrgHcUubidgUqAzvdriBTreFdMEqThsMfuuaujENvvuwCiStraMMBrAkBbenrwqtYKCCGjAMEItpUxtfYqTaGLxaUjuYIEzOXK",
		@"jMihLBYCXtjj": @"uEwmRdKDHBEReUVyTeCKRBAimbVxhUOefYmtprBQYapFTsdqsxomgZQPzrOsmudNEkUARbcUkUxUdZlCqvWIprRqdwNgEjCHJPYzHLvgIDVdC",
		@"MtErhFESDjwZcxmd": @"KPjiBcVEomWYvrWusCeKUWQFZYMwfiHHBYhHAlCqPWmfVwLYsZHJEtlkpTkFsBBDWmTZpIQLRmldZqxkgVBtIiCaOtBlIHeHMjLEJhtQfAjcTIanMPqqDmVjnrhsKemeolqmiWHAth",
		@"avwlxyzrxGwOEE": @"PvtXpVPKWYSWMkEPvcHoTqcVnJCrhtqWBnWQXOpcDOkDtayuYcAFbomuNGIdIQxpmngvtlatkDeOIQbqTlreGuDCLnAeSYNzQjdSjRdjBkMaAQQpJCVapayCZwmoSAcXpQ",
		@"SUxWzzWwOVGMhwgaGtm": @"oUhDKKIQOusGoRFCWYpSoMvyhWAjSxtkpxXXVYDoelJJluUdDYJYTVxtJbRhefvhmxdsOupEFVQWjNxFKYtXAKAYeXHUixGGjYOeXwaXgqFcWKIcMpmQfwHoNoofjMZaJWvOrWSAlZM",
		@"saWPzdgRIupnYlLH": @"OXXwXyNxorHpoRsjgmXFwYOaihJykgNdXKnRHWYTKDtPsrdwZFUwzZGtfRXziyGfmajlnhYBVIGqNSuHIvteeOtvCFoKondrMeDzwtQFYTFqQIHoGLLeFhabZhTKUuCXEMuNzzoDRfAqneWdq",
		@"oyBJlOyfJckNBt": @"OLtBUsmoUHXKRCzuKDuvXmuESZShlcTPnIerlbXYyWgYxyNAlkcmuxYVRvjgTZwtSxoKxispERaJcGAnmZDRFyorvSpVRLsfpCvXSWIGsCTHhOKtBznsYhUUwvGUEOsLRc",
		@"LIHKqRGiKdAPz": @"qvRddQNLSxvnaKbrHHgpwVyQKKketwqjSknGXWlwbgVgyUlYAUQaYfMKPwgKdilimCqRWzAGZSGqirEHVEcVSMSNcaKivngjgVwuunrQcNONtoQbLSROYkDdgnsYF",
		@"kEeCsIIYnrffcGqFM": @"MEyStxVfsNYutmYpNRelbbPpjeiafJxoJuSnsDsQZdokknlhUlImVAperqwenuPUwSKrlwnnAZhVzzcQgHLAeBawoHjjGEiDzKglYYLceKGSmfVZqWmLgDCCFRpyeIri",
		@"iXgKNGUHpetA": @"nDlSDILaWsRSbsYBIQSVzGhaHUdSQrMLoTYUXmoJGQRDlneYNJJSCLDDelrtQITIsvDksaJvbOrGJDxilADQePIwmossvtcAAHEeKFdXVSOFVXMBEseALbHmWDJdYnkwb",
		@"HdIwSekbgVZz": @"PHZBgwzpegjcbmdFYYOzRyQhVcHdveOLCTHKsiPpRkIcyqWiwAsBWAFCAOpkopCBBObrIEpGNjksFbdJrpZyunahfDgbIPoXUGFaVK",
	};
	return BXKcKOGbSW;
}

- (nonnull NSArray *)azZvDdWcPYWId :(nonnull UIImage *)gWSOXqTAgt :(nonnull NSDictionary *)uPJJmtJVdEZf :(nonnull NSString *)DwzTWGKQIx {
	NSArray *qFGyxgzsIFhhEn = @[
		@"wtpLKWoojGPHNcljyxoLvfkyEzezxekDXCdSnzXIGCcuiUhhhHAVzxboqHZfYUDzNXLnGMdUbkAWPxkaHhuOeWiQbSavPIJcOXXfBCtRYPbjEKCsciQC",
		@"CasqktQCtdCxHgCpeRNVrhwuzZgbpMlJBRtMyGyzTswSFQGYitcXpiQpOYgeEEeiSdwlbkwplxfcHUouXBcLnjbhHqSyllhIsPblOXUqzzsMkmnFPLgjM",
		@"KgVDFbSXcvRrPyXKIltBmLIIxIuLgGRGfIUzZHxIeNYWxmUsmivgGigmWupIRSAWIHgWOkkJjIhNgXLjIbTqstpcUUbYelDjYoFuPBnjmoUorStCD",
		@"vopAODURrqHhRwwjuoFoOlhpNZMibvnbmkxPqdVsThqSWDKQCCQeIwfFhwVIZljmtTfmTqVFwAMZPHHZIhlVzXzWDngPEoHlCAdKWVGWkMNjVpxrSbVyUIZEZWiNQwGApAhgDHl",
		@"BQWModtWUhUbCoSuArnzYItxZapvRzVCYFAqOhcNCnsuZuFvZSSEQduJmffEpWEGPTRdTopVtzJGeHxDoxLfJFbrlSaQxZFFZuKBZvTZKOWwxGhJpfwJRcJGVrICBSaXvBEOB",
		@"lZXrLGakdKuSBKlVuhyumSbLjnoNUlSREQnBtSSGVPkRapvMgsseKxcvoAWuwhyMriFloevQWJWTMkfKuaLbgzMNKUXBoUCNeYWQiMkUfvCxBBsCCF",
		@"pBxkEeByXXXajMPWWgTbLFLrmllXUwsqVRqrpIupRajifZVGvVDuqoQIZMiYVYxbejYnBYcCfMFlaBxfnkrnJBanWUGkTWZBRdLvUgJJZPaGTYD",
		@"XXwjrhzdOxWWvTjzngsxRFetTnZYKuJVBxyTdjzxfLaXQkMrYxGdVrKjvlkRgkTyxmAtMwPJRkhOvHbplxxUapkNwXSamSCNRMUgAOAIFBSLMgCTwywIIHnPTARIBYk",
		@"XFruhMigJUuWHxzvtfWGKpnGeSynmMXsQRppqrmGnqKCufnmgmlHXBoECAPqtwKjiWMrPbWpJzzXGRUXaTtSeOHEydZIishvcBaDhEvsZPNNODtmVZ",
		@"QSxIqoBiFfzPifGDGhAdjzPDgHQwMCnTJKvmoqlPwzuCfNAFxrlcCDXGBiDbEqEHVYYniouFJtvwCutaIzauHaEaIWqoZcohnWzuafiLmuwqcoQgISTtSqh",
		@"WiRDuFOaUyyviUkwBCmNtPWdKKGnxkdDkbKUWueUqElRoMAEFQqqmUhDPXnZgHEMESqEBcHdEKbXmcIJWOdoSPwSWMsBBhmKzleENlzeacYQhChSDfM",
		@"IImWGohaCpbWFRlYyWNcmElJoLfbIuCsAKMNrAxPRgHCpcujQEPYSTgvDctQQyDunGyuYkOpmADKnAVpXHWqbTkdnDedXSlZwHvakBUzhJ",
		@"KLqKptvXwwiklDjLNYIPdAAypELwfCBQaHwUZutousfDnbCzruDfPpUqPVEsDIhANmTcBEAQBrFaCVcqvsexudQFWbDbtyTkPrvBlrYloodPMoWYKeudaVvyaSGChYeiRsNdunQgOrnYOnmPCOhdP",
	];
	return qFGyxgzsIFhhEn;
}

- (nonnull NSDictionary *)HwAHWSwnLDxQkPCpk :(nonnull NSData *)TyHuvLTnmxpD :(nonnull UIImage *)BXwphBmAvfyrr {
	NSDictionary *aFHfQLKPXKmlXI = @{
		@"XELDmzrbuNqSuz": @"zbbhuPdwdUccmuPKMuQdFQcaxSNibZQftUaDIokcKaXotAImAsfmrwuVwEUCWLWiDVWlqLYhWOknDOOmYpuvoBWqFoMZFALdIbJrexqMDSmofQnsjUdlvvzHyTXppCpAxZVGHKhggx",
		@"eLCSRPwedMd": @"PHkhDKnwEdjRGbgtOInTcSBHVdHCrDJREbTkZITKHfCsZsVvfKsUjwiHSBWVwaHJeWNMrslQvFpWWPPffUeGANKhmPLDgUmenOcMtgTIyaxxIBLzKSFNiavHyaHurWcpaoiXeypAUSK",
		@"PJMdBfvAOAbyKmydIb": @"JmjzjqUcOTkAoJpPzJaIsbzDMvJvWGpUrDYfUGpaeeuwTtEYlHSGHpbSCVZOmGSegfQkUQTfwKNgoQpcZNfyxjJLKNzEahEKKowBwLcRoxYiCorJeuag",
		@"fbTPERscEfY": @"pFUYNWDdGYpcdBFXbzFmGQNOkOaegZvpiDyDexVzXjmPtxomGxBmrDvwQIEqxEsqCRgWYyzmxYhnIOPrWiCqfhAGVSONTXjrQqkYRsOwoCtldQFcptEZkNDs",
		@"OFLMkGmGLq": @"XBgKtgxWpuThcRmrjguZmCXzFavYeseKJZgBuzgnRpJmmHaXCaFxppDqAeXrUNUDrxAsReykYprcHzttzZBVqMuhlyVsfHocrzsTsVnJDrnqboAMgAanAwtnRDOVAfmGAMEtfwTObJUwhMXkhaor",
		@"KnFGlKfNjM": @"lmkDGQVsOEGpGtAnrBWparpXTlMONtofUKYWsXdUYFQQiSdPRPEVXJiWNAVSfzobPLXOLxddGIbDsJPFYNdjkZiUnZXyGLLNbEmVrnAMKpTeaBlRHoCDhPdoPTpzrOWlOOZEZT",
		@"ZltEdPuTsfHiIRHohGa": @"xTXYZBJoSBdRNBuNwPnUEVRjnFJsOfqqXWmWADKatkVhBVHVqjZjgVVWFmqCZRmlALSzYKRKuAXxnfFOMRQsSFCIiEaKLieOZEGEsQwlCfMpHBWUMQnkzfepNwVxDP",
		@"esMUoYzHPPupoeRWjHh": @"uXCsvcLKQbkhUmQbsFsWokBFBehudGVEoFOokjslRSmwXkGNrdOQfTeXKGgpzEZwgUeJMNblMkDNmMVUeOdtGceBvxVxFOramwYBpxRedMhXiCClDKvlKhuxPXxqUwzn",
		@"pHhnnyXBezAgowo": @"BBwyABVLdYGZGnkgpMBrXRkKBrehuWqlgiPkRIhKmhUdQLXGldlZgpdwVJumwuHdamqpSlTLGbdPYzJskfokCRAdHmFUlghBQeNeqkhYsswJhdthviawTyYDAMGhkVhJhLyeRjPzbIGCP",
		@"ZhCZXyfHVI": @"XeZAMUlppPTePjWUHDsXeSECRsAagSDzUZJCgWbfUwMxzZXHmoeDjHWUEkIeufcYlLAjztEIxOvaxddGDEUVbAkEXJuZJpUfTZiXDFVwwrtKKrAmajwGBXqfsZHxNuDAzIposMh",
		@"HmHjRoiIpAnwgX": @"GjhdCVpqpXKpGDDNfnBZVAhKDSftuTiIPgYijkfzppPROccFGvZVBwpektOZCQRAxAkspNXrLhAHIxWoYoodLiLlsMsQbMxjXTfHxDCKln",
		@"uuKAnxdrMZuHvx": @"CPnCnslccBKsRHsjBfGdxeBztSZajDhXshSBoVDZXgBZWZNjtSWiwElIJjXoQuULRfRtralkPsHDPHRxhSGuagpZzVUuMZskQYWRFeOhaOPeDbIDDlogbvccpQLmyMAJgJeqLpsHWVTBuTndByeiu",
		@"EanHASAlokVezYhd": @"HyWbrqTvIXEtHBJbnjEsWOTDefIdQiKoMUfetwiclotBMJKEvRIMwnWlSAilJnAHUkSPplwdWzMEeqFXgjveNMBQPaRpSkbwYMWXPIECgFlZPG",
		@"GPpoJphnqz": @"ozZzTXTHuOHMJLKLuUPjudTcloXurmmFNJlAZkUkuNFoadBMZMYAafIsyUIiYhdoKZZmBoTAxUVUeTyfRMkEBsItSEQWMHTbfonY",
		@"YmYIuDQpJE": @"FnMNOjMTqKwHjFmgHcAmxReduZVtJNOAdWSfjslYVnnGxqXMjNocoZqRoepnWkqxbPuggTeZnwYPATgDfpRDobkQCfQgARbGCeVHzIQkEHqvDNXEOMYmfZqHizczekvNcXPUpeASHuUOzPev",
	};
	return aFHfQLKPXKmlXI;
}

- (nonnull UIImage *)mZxKzIEyAjnVXQsq :(nonnull NSArray *)FikNZMGNmW :(nonnull NSArray *)esEYUsZgUGnxDf {
	NSData *EomqLMStUkSIOhJX = [@"yOlwdipgPmPoNKoxzvsjLuqGKCPmZCbjzjjlkHiPMhhSNkjLgovWAMcWtdSkUevawGeIhReURSTbMJouTvNkqfDUbMFbcSUfNSkFgRLAVcDTbfttzaLSKraAlliHO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xTyHdkYeDoWsg = [UIImage imageWithData:EomqLMStUkSIOhJX];
	xTyHdkYeDoWsg = [UIImage imageNamed:@"ZsOCAzRSmYJSfxbrfzzyjbXdklkOSmsoJXOlaRfhEouzxIbyFjkceRLANZKvxIoTdrCAitjAXgaEvSKeHDxYVRxxQFjzrIKHVUAWvW"];
	return xTyHdkYeDoWsg;
}

+ (nonnull NSString *)MBUEgNfvxKqCQLQwx :(nonnull UIImage *)MMxUjjSDrwGMg {
	NSString *GeFvYbTQGNPpnd = @"euhvXVviLZykmTPOypFqWIfOiMPJgnkNxoUUmlJkZCFiAZYnLjYuGZSVektFZhStOsyYrszckdHJiMKvDlsedpWFogYVsKNjPdcemBjQppNARAeGHNcFUxFcQMGVuxvXHsOsRcpc";
	return GeFvYbTQGNPpnd;
}

- (nonnull NSData *)TwPNCAifzG :(nonnull NSDictionary *)kgiNybpjkTvoIwUxqUC :(nonnull NSData *)jwPRqaOExbFT {
	NSData *GBHvyYfesZFiK = [@"aZwpznJyleDxQFUuvmWEZnICOCUQYwIPMyemtTfFFajdnhgIxqusMfmwgSSccxEPxlsdRqPjicHteiTwRzGhFCjTfoyvmhwsWhgVuLAQKnvwcVQKSWbLfJScwxTRX" dataUsingEncoding:NSUTF8StringEncoding];
	return GBHvyYfesZFiK;
}

+ (nonnull UIImage *)drjdVVyQkNRj :(nonnull NSData *)aHpqzoxyBaY :(nonnull NSDictionary *)ChWjnoCwUBaRwBhdFp {
	NSData *zbEirYlxXM = [@"VfPXaRXGyNjZLYyEQfzMFKpXJkzbQLNKIgVLARnUnzpoekGhjHxGUmYReHOzUYtOYmWHOnhZBvXvaOmCJdxqkUfMgikOlRacraBPLYTvBnmvyWYXmmvXKzYPRwEJlSGicMouEDWTeSQN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dcHcTbajCry = [UIImage imageWithData:zbEirYlxXM];
	dcHcTbajCry = [UIImage imageNamed:@"QxVJwkKDUgdhPJrLYRkMHXuxADVRxEZHbcVUXnnNUQvtWBDxqyJBXPNJTkzRMYjzFUJgziQDNansTyJaqAFoUSAOwiHPVrZCBgnRzvStPcCFOMcXgakzSWdboTqYmdjHKhlGvEnEj"];
	return dcHcTbajCry;
}

- (nonnull NSData *)MvsDltKbPohIMfug :(nonnull NSString *)khLDSrGwqtnxS {
	NSData *jAQXeLFAFonm = [@"TPErpxJmdpKbbgRIDsKQUkZLomAyYSQgFbXvCuYTdQwhYZAcYbHMarvIKgZXJsqEzywiFExnOoCAEyDVuMoTQjNJinrZwtnQZLMImbPhMWhFrXegOQMMBowYyVmHKOcyHCjvHKuBrEGYfFsTMKcI" dataUsingEncoding:NSUTF8StringEncoding];
	return jAQXeLFAFonm;
}

- (nonnull NSArray *)CrnSeLEprhjfwj :(nonnull UIImage *)ZuuCstdWrhplzKTSaye :(nonnull NSArray *)cRpYDqkMHB {
	NSArray *TqeQdyspLKtkPLYXWB = @[
		@"aLHOnpsvTZwerfoDDXlAaNczXWumULDmLkMVLOQXuiFglKrxxZfMZjbOybWFrYjsGIXkTyQuEYqaLWMEQbFgBYJmfDWtUrrvvKsdaxRGOESpnOqPRXgtLxrTPmhPXvdVOayQiI",
		@"rEUqJByNLAOqAPiJhbUMhuoPFabdMXkZePkzkePDZfFDhPTfoLSgtczwkRpFrsqgRUHHtHUdiJKviMHSktNdsLoOBGUBszhWVtrWRrcRmFphTwbwZCuPDoaqabvXyJIXfsctFJIV",
		@"oSnbUfxiRQcLXQoTMeLnMTIMtBvecEwFGHBAgtLbXeXvtAMyQAvgPvJyRJBqMwqIKGqMKrQvTDGEolfoTeKYhaFMTpEOFIJakOYuVUCssMqbcPnEfGsnKgfDeDolZksft",
		@"XCyTaNRkWucWqxNjwZuadbIJLnJTUtlwIumfQwHzKimRJvtgMiZoitgsEPOdiSUTwRKIPobyocQFyxNLAJOUiHfKePasPFTfXzlvGEwnMWnayiPPlsoWMWKWiGTfzQxTvxvfuOpcR",
		@"JewzmQXCoXUqyLaidSYwqvBTHKkMmNItnpTbTLRWEDSVbnDcUcebpVtdNNfDUgDfzPYXqzNRnmBWvJtgiTpdqorITZkglZoGsYwVNZw",
		@"SXkUUwKOoXBjiUlvcNBuCUSSkEwGTLBKeOqwORAeexRispedOJngGjdYXBBPBhmSpFPAnDBHeTrskEBEnvaVGLJInoJRJKxFAlLVttwMZpCCeEfASeyBPGgwhXgzWcb",
		@"PcywfzOpZPQxTxPENFSdKEGNdgbrbdMgEeuZlMWuRLCuqMGTujwaEuDrIWjijzuwBAldapOfLZcEZagoHlmrCRJkLHohjZvVIOQvmlVwpmAdQYIuMoKkHboycGnORn",
		@"bOblShKjeMactKSBJOkOZUhEWcGHOsOhjLDkbDaQZCQLHCXtQolekzmIMVFIPVVEAJeJUDKUbdsXLZFYYUqbvJzWsRNOaDjYhUnfgMmylpUIMgTxFLSjaLysTOAxzMbmXsPDtKdHcWmyRIIV",
		@"RznQgPnACRFBTUQooZLVHmpBfAFTAZgLngDKvFnJKuUrAnoxlQVoXjhqrTEWokqKJCBDmNzgMFBFBaUPVbdnSbDgvGZHyjEDKdXtXKa",
		@"fOmAnVABkCTQSeEvztDXXVYqlrmVIgXkgPQtBPyxlqQjxWueWDDhWFEUaWQFxCSOKSsedHSxxdEbfuiWgivJVLsJKJarSjFgJWKPcTAlLJWsSVmeupnCgiFILLGMzJDFHEroWwig",
		@"lSsDgbqWnfPmFrPCOkSVVjsqCpRkrOmnTgcSuucAlkGMxKIrUJrBscoBvAXrUnhgPuxNzvMuYzFhwLIZKyLIvoGqaeYZiIltqwfAFMBrwMzgOVztzksQgQIFgysiLMlAXkuZxAF",
		@"SoUCDOXwpsnwxAtAIvmDhCFdacEVDmMUmtQjparuYXypcEWAoVUTHpyOgTGmyVHWCNiNvEJtGESCOmQcQZDbsDPVVMnufUCWmrrbnJyACDfaYWod",
		@"UbUDCuYYcvtnbQgVeBJUAfsKAxRzrpYqEMmyICSskdFZozuDsDqcJZxGNPshPhTWZDLLBsznAyThRSWOKQTGWMfQrPlinrFmYlzWTCWrwOvKvgqacYGrf",
		@"ogaSaHHYQjoSeiUTdaBSjXwyMyvgjClPKCyfvcvPZsStHhsPiVYjRLxReqkyvghJjXoRWPjxzsCOXAzqABYauExxHmYQbiYYGybkUdfUfXkpLbaaGeDdBiyaXoGCeXu",
		@"LrozWhlHfSBwmoHCFKOnoSPMsNuUNCmUSXwEQGlgwRlbrIihtrXTeGCGzJWWPeddaKYORooOnYeOLSroJciscqSUeLPBFwgEtKQnbnCflkYAEIYFWmGMrvDcQgfXZVqlEcrs",
		@"DjLAoAfKpKmcIjYGFtpXFcEAzhwWLXduBGvctypToZjkuMjqqocsbGpcaPaqareXcVEIeTgdympzhFibVqfxxHtPBBTSGlxLVxTEdpdRVYlpPfqVVkPjqlUYbV",
	];
	return TqeQdyspLKtkPLYXWB;
}

+ (nonnull UIImage *)jChaQZbrjoydMoStEF :(nonnull NSString *)WzgtLENfyUVvqAigeb {
	NSData *dehHOgBiAaWQpRAS = [@"dysrryyotIwftmVPGHDPxOGmeYLYHtsRvhssntfFUWxjicoVOjsdwGzYiGtJMRajiisOBnGmeFMzjiYorcRYAdDrgVsggbjNGmtuVZHWRorD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ObgJcCGsftanohS = [UIImage imageWithData:dehHOgBiAaWQpRAS];
	ObgJcCGsftanohS = [UIImage imageNamed:@"FzfuGvunyCJIDuVnhBQPglnvWFdGlvVaohFXxnyeYONRRyURGYrhieRefHsZsLGATlKjihpTELPEkNZNUAoUQeQLAkCkwCoyTqINjW"];
	return ObgJcCGsftanohS;
}

- (nonnull UIImage *)GaoMnAlXxTAXa :(nonnull NSData *)HotZrULDiKObDQfie :(nonnull NSDictionary *)CcpZdtQYMZnSWE :(nonnull NSData *)hLBrPXkWaCc {
	NSData *GWUwNDhPCsrN = [@"xrGleHWcWXodtWEQhjGBSNuVcGjJItbexhwArCDWEfNjSHgZHLjswcqigCNKJfMVIVCGcsFEdslZOJdiaFhfkdPZSdooNTsLsFQwUtlU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DWDBfZnQnrw = [UIImage imageWithData:GWUwNDhPCsrN];
	DWDBfZnQnrw = [UIImage imageNamed:@"cSpdIlQuuWbGDehVecpUcTNwraXfeluyVJWvcyzFwghMYpWwPeWhxnuzacVPgEtPOYTyeYyCtUNEvcnNECFbuVChquqvHYqNaxYIFDyYVChdNLgCsJXNOSxUBOfrvhTBEnckAF"];
	return DWDBfZnQnrw;
}

- (nonnull NSArray *)GykryUjSitwfRMtzJe :(nonnull NSData *)DERdJfLtCOxsoLeuiOm :(nonnull NSArray *)KLaPYDQzFiXqvOcw {
	NSArray *FFVzjKmoGplwE = @[
		@"SalcWLmTsqphEyUWkEInyQYLsDScqdOEMOLKMJkrvQcqEGUwehSasxtacDulORMxZQfvfbbURelydmYfUIBncLIjePCwqxToTTwhkezhZoKrFohyCDGZRyzrPBxbOXwai",
		@"AfsgrbAWdQbPDNXMMxeOPplfxAvvkuAzrcZPVftlWPlnFunaqmFGZbIhRQNBHsBSuzHaZwkZtPqeqzHlTJvipxPhKAKOabECqmEnNVkcjHfeIBf",
		@"JIhPccEpIxigOhcteyyDsFbjTBOjnBZrCQdaatSCbHciOGWAcdhXLBYkmSeLUEzlnvutAGpFnwZHwMjslMiCJcoHOhPYKInhZQiChglcRrMRdhfGhfrgGllXUBCGFbQN",
		@"RXEwSyrNgVnYFYdjYaiFztOVsYTlLLFKoftnYAKuxNPFHXMknIKjBJvMyOdznmFqzBTYphuxAqPlaIFnuaQlAaWZXgqNaGrKSMFhWspVHSImLFryqdpKKCVQZnfnHULOxac",
		@"LUFGYpvIaWlTsPjulYArLuRYziCpCLaXXbZzDYJVSlkCbDdNAYRqTcQroYPvsBzVxEsLcGjobWDfTmLIfbRTnboZknpYDnsMDQxWsMJXjujEFHtVapNaVTDisecRlE",
		@"NDJRoaIoMDDgNJpHzmoSudUCOyPJUyqKzvGOskIeUjjuzLceMftfoAtWNyfjiCcgWeBbEPjonTUWikPAtZJFFxNbtUtXyOkPTdTCKwpLjoEduHEYHSozVAGpfHJJ",
		@"snPETBjneQVgQSIZCJKSOBKyqsCNKoIymsOlLNezGoJbBEMfoQKMnpaWGUigvNPcUwzLEOCFlJrzjHEkHsyFBZciqmxfDbdmxYNdxBDFZXnKaoJQao",
		@"kNTqCNFOCUhsIRHAWlbTOXvaCLyRIxTNwjMdBCFaWpVMcoOcywyKgGeGIzoqgOYcczvRGpIweVVfVshTFOSrgrkwTfcqLoWSEmjWCpoWXzcQtoAtKoYrmvABFiBqTHGCBWbORSexsRRrxnpKBjxpf",
		@"hjHVqwvGYzlSPvitRjdxSVCzUQcRsFuHMkhhzPLgAXHCpjisgECTtugNYaqtStEubKdHSduKAfzMmshwPgxpRaCHdjxEoIBMLrmYZe",
		@"JmGrvhqeiEZCvHMyaMjMvXGESxrJinvXmildYovUliDAPLbzFgBwfygWxJcZawwZBRLEfnZKYHzIwmuOFQqYdcdjSAzwovRzQlxkZsODgtuZmihBPrfGvFjTaCIIdJrKwPIGTwGXBYzHUjPqIC",
		@"fTQbDUgaEksZoyrKnSqIolSVIhdHDxghOOUpgtrnIhNPJKdwecPkwvCPYSpAhWyyRlzmDmRzxwESjdzGUecWEsOINtwBOIRXUnBAqsQawikRvRCArVKBLGJXFDjZNUvFTGnejQgayAZyZXEzxzcP",
		@"eGxnhpIGnryvOzyjHKhxvLtzZRuNvwThobUADapoNBjjYvnjHBydwjCtNJekKozVBXiVoZHZmqHFqVXHnalRAWziDlWgAPoERqqvbqdBcQnYpZmzYVYzbiFXcspSYQJMNsvgiftxTiihyKhgamw",
		@"ynzCedSNyCHQrlEKPlarvtTLCVIWawaEnnkkiYGfnHdniDCVdMkJGbmkuEeEMzrcJrLAHNdQCBzALEytYjBDgbGYOyHboaYErbVmeN",
		@"vkSBIQORHslvdPNMDxPUHOdnkSQskRjGpLwksNQpfmvFdVHnPYjOFWLQEPTBxTPrafUdbxltGLZVocTzPFqusLlKHDXhqErQJOrJhaSafjQOAUiMQWJYtTNKaeDQYntVPcHbgQjjYYdNMUJuabq",
		@"tMjoncnOVqkLMyGaRxTKDPuXEFvJCBzEbrbgSSFqCgpVNrBtFXFzAzXXbAdkBLejhFrAoLHulquLFnybTrVFAsosjJUsIUQALnBhqFwUFlHBVthZNWGlThI",
		@"uTEMwwdXxWoCUcFVCoiYeEQnKQFyXjFiHQvzPMxPKPRoxcpjRcanyAGplfLbyPhIuhmjvrJKOASooXAgJzPJlPXNumcpSgntnPDaihkgedOZjTOXPvpDnIJGNcWHzvznuDwDlMIpIgm",
		@"eVeSTvZYKsyESueFWDmuFchpYeqbhTBONqWcOIJYJHscksbzDqJSNlCKpxEZJrLqewnjPqMlnVvbNzIHsmAoFyMMmVNnTcMtKjyzdAzAlrVwgLSvbfxhYzkzWNlDHpFrcZHsfQlokIYO",
		@"ttSwYNIMjEYoMshebbuwWIfVDKJoxuUbfNkOQgEeLzeciEHfuwkfVRiWAjjmlEqXKSdKkJbHRXDggywAtWKALvvFGMRiNLaeJvvyvlIjbpMoDAaixNyqVoT",
	];
	return FFVzjKmoGplwE;
}

- (nonnull NSData *)arppPdsYAjjwOyB :(nonnull NSData *)KvRlXcFphvinl :(nonnull NSString *)dXHoDzuNblTJyNTbj {
	NSData *rTBuilABJLezYjMaa = [@"sNuwGliOBwTCAReXPAcdHVlgdOuvhwxUtKbPQrfFxHrRlLIpJeQcpGgScdfQHdYKxvojhBACTmTJcHVqNVjmFwTjRgiKOhfxhzBWqGyuZkxrpIheIGsgaxEUaIkdVXvboYMDNXZmqGs" dataUsingEncoding:NSUTF8StringEncoding];
	return rTBuilABJLezYjMaa;
}

- (nonnull NSArray *)aAKkmuCGIvOT :(nonnull NSDictionary *)RtQMtwLWSJoGy :(nonnull UIImage *)bAFlbVjlgRKfpHmU :(nonnull NSDictionary *)CLEigOmtzfMfT {
	NSArray *knoIJqtdeWSMpYXCA = @[
		@"oOaXaVBSvBpHJoXbGvPEiLCDIdjjTVpDGHKCTpBrSmteqzIvWCuapDMoqtuhNGFneAZGeZhxkIvKQMZyMiZYpnEurPYaqwVehWCYbJLvCZqLTUwOQJOzeGcUZDkJUPZVEZn",
		@"RcWNuGpWeqWgkXGxZgRnLYenLhedijAoKyXEnhGLNVrZVvPWIGmRZUYKIwCJrdRlfsEOhSpZySYCTAWkGDKrZIDNLKvnPUVeXVGv",
		@"zuRbpoydSbpCpLxnmZSIebVzmMCJtSbFNcAWVoiJOgSWdMdgLysXxmwHtbZWCoZZWAQTCYXDizzKoMZdvYhFBglmoxksOpuAnsCfJsCOnmhpqBKndUclVoWMMdxifJHVddMTdcGXkBbWWjLW",
		@"BKnhqopNgiqXZNFraAJgHbHcsGlcUVTcknbzCoDKhmPJlEhfXYBPIXwVKOsLJZXieiXMsBXsYVwzupApnbHVLBemeCAZYcFhVwBOJhkDUBKlmSucmJYiLVKAabTWZlQFnNJBoTuLqrcOGj",
		@"gIyKndPwbMApiIuXPENjghBiTkALEOtfGGPZDCurFZzqxXxNCHgnHLAWzyAVxlrXlUkIIArApAffbMjDSatyLoYodZPATkzjXURMtrUDFzoznYAsjzFk",
		@"cpAlRDfhcjSDfCAEaIBloSluAOxvcoDYUsRWQZfQKMhVfBEBvFXllDsfOLEdSKQwHIBpCTUGEvquuFMSazBuIcpWvedRGoMorMNTwSrYPONMUkwPwNQPgwz",
		@"PuDFSEsoUMaMtLalhIWsNaWNIrEqGLJaKIykqMSfIJQRYTYVmjRYszqygpzMIiDsWZKCZCusSAlItaWrdCtmtnEipEsHoymgRAcClzBSMi",
		@"PyxpiMHGtkfrdrfjzhihwAFePjnfQEmefJCztuUkCoBrDeWZzQhCLjUrqWjvnQpzYsaYAblnDCKEzEtypxaPwUaGEqfGkgZqzXQIzzqytIjKoKRgxqiJMGiTBQKOXcGQrZV",
		@"DZasNwhdplihxoidHNIexgSzQMYBzyDTBedbAAhlFyGvMwmPebQsLdGcvCbnlbbUVvRLmyAAloiTrIfRjauamRtKAtqPQaaqtpmxokfYyEIhIvCjZfMbAEjBIXWnVeKVmlJtq",
		@"rQQJYYbvbbkOzQZObMqmYooQxCZFhRvdmIBhJCNfMYxUxrTtmyyNTwmRkKOHgRaziqBzjTEOWqMxAyHXtRvAyhJXIEGbqVoBSRfWfXwDVYiihdKIWchyCZLizNaqYFuOlVXD",
		@"UNBkxdQGJSovXrnsuhExuKFsrIFelZMbscGiahBMYLvkNcmQLKKzkXRiWyvzieoLdhtzHlzHzDJlkEOzCLLSAEYmEzeHqkaSRsGTTnZfpmKgwyTNwaPL",
		@"dWDYsNXUPvsYhaRTbbFEsmXnWbipBhXcWKhfZQWejUKupaZHWXgAFGCRkTfZcgTxOAgykdxnJaLIqyHlQGqEukdjnZYVddClGzuVyolUpovAZktrdiQIKBkRwkqRzvubxNhARVONkeCOPmFXHp",
		@"CMRiNnXlamnfapPjCEpoSOGVvhuagSXpzKsvFWIVlvkvyMsxUZfbkSMGRHlwCCiWJKrCrsJCMtRRCCYfIVSLDrebXPiJfecXGdZwUYA",
		@"IKtbnDOnPtJXgZqXHQdnvCmokcFjycLovpqVcdQKDcTPDnmklJVtIxozQnGBHAKkmIzXabecBLCwEiqJnQayIrlmFrNnEzYQxkkFh",
		@"LGTBlGJMadiofYGaOXxcwMLqYVJFRbymYMaYtcvhFKKaXVBSDhRHSVnIgByGdIDOYWgCDQImPTFeTRUMLOhUGkhUFOltaMbKZUMVEXaIFEbygUeAcUlZeORRTNSbuUFVnglWDtXdcCl",
		@"vsaXsUqZiSMwtWoDGubdktSZjcLPTxQoJYgmCrqoYcOKwnaTFBetIIVpcmnEaHpIEsVlPsYBvklliUbEsmSJnGHLzidhWRzfGmzDctEkkTagBACaaaVaLYWiZFGxhEWt",
		@"PpHqEExnKVYEaPyISAeStOrTHuXvMoXseTNfAvibMqVGmwqXlNinSPfSPYCevKBootOQtTohaNabFwTobkxXbKOOCJDcWDFVUQZTmOhbIDPngNxibmAwsHfpbgwF",
		@"lmbOOfqevUQhnwRZLPhqNBFjfvnLkSTABOieNpohiKsflYdZOUkEqlYIPdZPBTiWsHieBcezHBfJilhRlZGGWWVFwspShoupCcMfJLXWZPnWPUL",
	];
	return knoIJqtdeWSMpYXCA;
}

+ (nonnull NSData *)HaYlqKOizhVE :(nonnull NSDictionary *)tNloRURNmXgnjgU {
	NSData *RqaEPOKzqW = [@"dkLRevkVTHmZNcNripZVYAKySyPwJRQtleYbnSmPkfGwiioNXXeMpxGxPEchfbvZmnbxjYHQULRjDAmtpeGnCvthJNJErzVXzUSzQZjyQQDZHeXdURYXndhwd" dataUsingEncoding:NSUTF8StringEncoding];
	return RqaEPOKzqW;
}

- (nonnull NSData *)RGHfqMdTuctMBBJi :(nonnull NSString *)nEGxMpQBtRXlnXOGTT :(nonnull NSDictionary *)tNleXiEbszp :(nonnull UIImage *)fhCKOkxnePYJRdX {
	NSData *vRXKGhxBcjw = [@"FebvFFItPLNwGbCkSHqoaaFLwhvHiEiIqykSRyWbYsOUTuqEPlhEalacHEeKQGlxothLamHAAIVhAONIgTUWEwWJEXVgWCUYDjwRwgnMFuJGbjywqJhzlSpjiRrhDdCnvQaoHatSxLo" dataUsingEncoding:NSUTF8StringEncoding];
	return vRXKGhxBcjw;
}

- (nonnull NSString *)kbROQUdjnYMdonaF :(nonnull UIImage *)YiwjRNmBWfakE {
	NSString *cGhfwIoQkBuPneCvIcy = @"ZPoysABcnkuUNfDOIiaNdHCjWHjpXhWfxwUfIqmPkKWuOBCQOVZJUEWmgxHwPpbHaHdyRraDHcHUlbTEKTQAijanCnCOmzdKnzDGJqzJmRtJGvygMpXrpgbeAHOaLlrrTZZHoauQUuuAPuT";
	return cGhfwIoQkBuPneCvIcy;
}

- (nonnull NSData *)zjUrErRJfAjsxlVYjqh :(nonnull NSDictionary *)dXKDkrQydct :(nonnull NSData *)bQMIsgHgqWZPUmd {
	NSData *BFYRsQEJPNhui = [@"oqIhfRxgEgVLeaBBxWpIlcizbgujykIOIgLsFINYRJzHjSOuELWSLIwSozWQWcYMEiighTZXHhkpEEdzKtbuuRybMaspDNSKjUeBIgbtiyNgymcFNfYISaFxCKIwhpnAcZxkDtUnosPrIui" dataUsingEncoding:NSUTF8StringEncoding];
	return BFYRsQEJPNhui;
}

+ (nonnull UIImage *)uUDGguNcoVSy :(nonnull NSDictionary *)GeAmrHexOWqQgRMsGvc :(nonnull NSDictionary *)YekrlaUTRGgiQVd :(nonnull NSString *)QqnkyLhvhA {
	NSData *ZaejutFIWUbT = [@"vcfawEDDCtgnDTwoxJKlwaHHJPHvCqRpoZTyfIeJaIBpaBaxwAESJHXRAxqKyFJSXDAQdHJEkXsMbQZFVOYQACJEYMddgkAELsGmcYguIbbWnOExdLUUYAABcJudWkwTDNzjP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QYQXWRqOrGYgjRGs = [UIImage imageWithData:ZaejutFIWUbT];
	QYQXWRqOrGYgjRGs = [UIImage imageNamed:@"iKeZAeMYkwjhTDJSFggVEmNPHYorAYqhobcwekHLMDCmxdWhAMQQcpuNnZhtsAewJPxHbPXRrYRcqusoYdTPoDXrWCimSzbzbDaOtfeLFqWKY"];
	return QYQXWRqOrGYgjRGs;
}

+ (nonnull UIImage *)fRoFjwzbzavfB :(nonnull NSData *)PFKuuLflyslAHRasPB :(nonnull NSString *)hnYjIblVMk :(nonnull NSDictionary *)oHohQIgakXMnhJhYBtO {
	NSData *JeIGHxwwSvuxAtMzZSn = [@"xsowpZQrVendOKiySsrzfPIDcUblQhEybuQkqLcaQyYUOLRBdsCcFdxJTOCwXCHpBlmHJTXCqDUDZDqLsqqGNDjegCtZqPELgMghZvapQvreHZGRokTwLBmOPnJOzUdhpGyenvTVUvUwcCB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FvxbNTdlEJpk = [UIImage imageWithData:JeIGHxwwSvuxAtMzZSn];
	FvxbNTdlEJpk = [UIImage imageNamed:@"DHTRwnnnriYnPYaPpUGLQZuNzKopcjuWTKdIQQQKPkrPeaeKvQMdwAuXOtsbJYUxjiqgEMwgYkJmCmYFbpBCtXkdDmpqcyyDyKhWVbRtuqdbaMUbBcTQLMElAMrVEwGl"];
	return FvxbNTdlEJpk;
}

- (nonnull NSArray *)aNEsEGUZLp :(nonnull NSArray *)jXmJTWJBoFJzuSDZGHZ :(nonnull NSArray *)CjieXVhZMr :(nonnull NSDictionary *)NpOjnbhssTZCF {
	NSArray *xgMOPJqamClpQnYhMf = @[
		@"DtjTGjRrWATRTMfCqqSNXWHUOzRQrGkQkuzdFxZWIRCsfjwFyDFKgFYFbCVfHctJMoUXkPwdNqjGZmsmvznVkVZYhtxyaWehxffmSdxC",
		@"RVROicpWIsAKgRyvwQferUiIqIVZextFmiVzswSdSJQSIEJOXzWLoqSPMuXCVzSkIgCzDcWihRtPZgaKXMvVbiXCmhfQDhAzhjAjBWuietSJtbVKEVNXFQaUF",
		@"WDQPBQwzlmRTfCTZDhIQPLRLJthsSyjIaLRaemEhPMdxFYATWsQAeFoWtEnXsxOuMbeQkXmAefxdonPopDEZlwWirYGFHrvinZJqFTrPBGlcdrYEzeDSJbusiHmsKA",
		@"lFWBbQspfXbczeDCDSGXQGIUMSfcGYnCvSeAFQvIGEaxkfGWbnkjvKdWhMLteptqUWeAiTPUtVQtNBmkmrMFVtrVfeSnlhNDUvmPFRzJYNWteW",
		@"ePYAxYAfAVZAVlOXxDhqEGtxKhomhjcpXZLdYLatEopZVpcSgJAmykZqJmVXuAfhVpZBXmqUHLBnatAVrwANkyWFWFDQixZWZFrFnWQnFuapNuwEiwFGjmPmJxwixFhdAhGgoOSTTWkVYhSupJtZ",
		@"LNxrpgRIfsWtPSImwOTvJDWBuvWLaDeYcZWpOBaeQQfcpvDNGZYEGboilrlfuEgjpsulYbIxSUrPtPNGFbVJHhOngYnEMrygtEfhBTHqqHQXSYtbtDBwMslFbRcFQbUG",
		@"nIpAxwNsNGBgIthPyDnXPTvJujYfylCxaevjcgmrXSwvlNnfjPLLLMhBLKEdhQwRZhSQpJSkTfXgNCzTRcetuIvKOVBvLpoXYYeAuHPwtWpxVACSRMRrLdFvaaPRtsNMNWKbpwbmZSxXLK",
		@"QdiJjScYLBbeJPMNtOFFVtCOiwKpwfGzhuNQfjgjySwTJDmqKbvVOKbxjlwjzLVDKyXhDobZcGmNczERedzWNklbtwRlfJorYJcKtnjsk",
		@"esOankEnNIqfRtipEnMXTuYhEYxBcWCWhDUNTTgTNxsRDVZHwLNnRcSqAaXWXZPrumWqtWUoLzxsLKmMEXlGniRDGOXOjFcVFRGdlusTb",
		@"KiEswMyBPynIHfvIxpVuEzmmuoTjooEuMedTfmDOsBPBTkGxiCUXZeVwfPxvAybrFujeZXwOSOdcaxciQuUyxWrppJffcOIDPCDbSFEgDzVLVMWvRdJAcoJvXOEAEYMYSueAkUUOHxwcq",
		@"byXwrrBkHRDCLOfNEOaAPzkJSifnwXEfQNsTcSpquUiTXjvXTHMhjDBcsXdYERtQIbTTRcuEkujcyCDrfyHulOmhwdZDbuxtZwgCYZqKNAatTsOHAAgfe",
		@"FFPRcZuBejAKhuemKikZHgGIGTWxODusykNIhMTwOvKbjJDhtABMMpWswlWpTDgXfyfNFXPoycZNpkdEhGHtzdTHwMxvKpGhcbWdLtREcFqAHhqdmMGn",
		@"MVIDeURYUdgNWAVaZPjfbmPEmBgDqoMyihRpJfKbSvxsIQmjRsjoRnrgOduzEVgDIhfzGGzbbDiwDipLFfpGonHgkcTHCRiyDUDeqjHOa",
		@"LyktwujydHMOaDaPFvzHicmGBbmZTTShwumDEvjdqTXiCbKllPmgDHeiVGShJgntUQalQTqCMQnUKIPOCqacOHPCShbUIEJqvvUPPj",
		@"LWhpsLuvYoEXQtEViPcrgfYJwqlDhznYKdAQIhvGhqgCdJsYmTmxKvYEuoHRnzbapZbEDTxRxOGWROiMtpRbBWzkuZIUzRNOqGcTr",
		@"XSCOshiHsfFmyWiTAlUYJnvATSdgattiaMtJhFSKdpcQDprVuZXoGaBxddGdXjaUcJnSxKWBRPRguiofuZSeuRzawAJlQAotTTFQyMKmzY",
	];
	return xgMOPJqamClpQnYhMf;
}

- (nonnull NSArray *)LXbSRkRHzdNfxphCgyb :(nonnull NSDictionary *)sdurcWrIsSAfIXkvWT :(nonnull NSDictionary *)xYhLzZaTUVUS {
	NSArray *sSXLdmCuKGudUoZt = @[
		@"qYIfPNDLOlLeMyNEKJLqbYmPGzPKITecDmlzyFkQBEOSpBlltTLGqPNZYSEBhpnAqDZozTbWnNmrDdbVCJUcivQeaOxkxfoDAQFzaiEwptmEZgBiiwHt",
		@"szkmMWURBamWJmFyHRzUfcGiDFxrXPwYyoWlDACJvDZJicaXQKMDilUOqsFKzKZcxcRAmDcFVbRkNDIhiutDfomytAVkaBWoUDJnHVdJLdzI",
		@"WARrtMnSRzXjTpYIgCqiVhxBdoNSOptAboPOrwJvgbvHTzbNKIrrdjHBSyKlORpjfEczWViLYphcBdtOsvPCZxKAiYipSkOMLjnKPGJoeKrjyZk",
		@"TvCJhvxBJDWgBNGLXwppuVgkxjmKGrJJbJrrAqtHqpsOYbibjRTiKlMKaNHVqZWnHXRnzQzDxuagiceSIFpZztqgnAGgiEgTqTqzVKUgbSEnthrPYjjmrQaDaTxEEHYNsrur",
		@"vAksSdTKtdRlRVKrXozZlgApZtHJNZcvDaYzOYohefntRgORYQbhacZwstTHjunwRCYFOaoNoWTFYomURwOGfVGJkuPlJUOdnVsWlSfkMTXAhOyDbkLnpDAPAzIMzGKWY",
		@"IICbpfsfaRGYozbrLPNTepxifmjVCUqAPyttXXzIaFEUNUMVVKVFHCWrvKwZSkoSYoSrfRUoKFsrBSHbyZRdqmgRGKtVuyPzQvNXCnjTGrsCpXIvTkItrXKOTfYjZsxiuSSYyYRSuIjB",
		@"MBkcDIMfNkrWvfCGroyGQnIbsmgBqAutJnAjZNpWzxIuRnUOPJMfGzPdlPguHltbgLjnPpcGoJWdShxcNNdxoRpnCUvOWtuKHixpMURofOnaMsTDRIOalFlkbbFC",
		@"UTIVZZRgTcLPJZQHhtWOApkubEIoKiEBUSIxpssohFgrjlTjPRVrONrKaiCSROFMVaQelhMMPlfMXxcRUYvmQjaLmrJmulmcxifZenakodyMqVfjxNeouEvkJTHGDmOSbZBlvmLByThpJnGtyzIuH",
		@"ljOIVWXHZcwhrcCdRdUMnJnYGXnYrdeALoaJgiXMcJpxMAGUyOIyupUhNFuYvcXowcjTSXLSQaVPpEBIuZrMoEQZmJGynWWNsjmBpqgTOKApiWlYSqNjReIrkQnTkmkq",
		@"eFwFjWvSjawrzQhrTqVkLSPpmwAQlVPaoATKiztdPInDtPNtCWViVBxeslrXnkkHxIqwBYUppscHxfeeJhOkTNuymhZAtTWStvHTzUUHkWsfxZvGssrurdryGGhey",
		@"rgtlNdfrMkvVzCYpslqpUayaWQjRSUmEPhgJjIgpKvhGxYjvMnrNpQiYXbVIZKjqzntyWBlsqHneIuxNbGuyKehylPJtKeNoUgReXeRehwvNwusSQfQzNnOVgYnahByjHwbBdnENheAidSFrt",
		@"opNheNfwyTrwPovCaZgJbvrSjhPNmAmqnMVHQzPRfBpukVCSzgoEHjQNtSjpeClWLhDFxJOLpKzLHeDXtvjbeGqMDOtrKeZfMvEkXtThyLwsGPQgxONeTGdRdTJassq",
		@"MNfpLYAwKQiQoCNFHUJfxfvnjVpdJUtuQPFDIetEssASXYUHennIeUzgpWtBENWgjAGhIhgWuiTXDZPDsLhMBMioxoMPSuMtnlYKLIQQNpEiWCEhpKsEwcAgGxPKnIXUHHXwZgue",
		@"UaifIywVHbbUEYrjJSHwjgcZoJYjBTLxUzwCaxmeVnIBfqpbuGegKMumBkWDIVRRygbtIYngHkMhaXIFnHEujhKEIGQRpdbplTFsPViGYkwSWNgbseRwUEuVuaGXYfPTTQcmkWhDsFYYkJKk",
		@"chBZeoOoWRjimovDLSIUlcteIrOKsDwyEfWJTHBRwwsCVfMghENQRQhsZmHtuMMBBQRhOPTJVrPvIbMRFyfkRGyCBtdkJcHKAtpxqROIrdDIfLcXCmBAJFfxhwFEQbhRYAeOXxktvWofradTxQS",
	];
	return sSXLdmCuKGudUoZt;
}

- (nonnull NSDictionary *)VNhOxuWMNSbRarfFZ :(nonnull NSDictionary *)RIdUmRuXNjvl :(nonnull NSString *)vBMcapAKHzPXOKNS {
	NSDictionary *ARVjGmjvkVXKtdsxA = @{
		@"mGzXRpqHSGxiGSb": @"cRRMMSzqUsFZIYAVKTnHsEaVbIJUqMHSjlXHEsPnzzEPUzhwfWjjNGBiMYsOEloJujDOuCBvoSgeBmjLWnZBDMSEMpihQgKBHZBdYrb",
		@"mUjNQSdhgHXEJPbTuyS": @"XPUGoxYxFkwHUqFEzlmXIqUOOdQdGBTeifWgfuyWLxdFhmMuRwxCZkDRiarAmQDwmIkurETXjDpBQMiqfdlPUchKELUOkpZoApmZsNbldVprlltBlYcSHQKYgBA",
		@"jjkxyoUHSZQEvYJk": @"TrxAmWvKqgxfJHFEyrIXgVMgelDsidfsAfELYiysXbikcdjJnwFmaNPNYXoujVBlIAOIPYpBVzHsQwSpyFfcIOynpvfkRxrDKOhHFlJhPPDWLtaJPtNqJXCIRtTkuMFwtLIlWBlkBm",
		@"TvQSKnKwdDXLHTRHqpN": @"wmGYYjGcrqzqrTrUyCaAKOZAqIfzDeWqpujdqTDupRtBTLUZQZvxZfupzLpzpYCTKfwmsJLaJMUneSPjsPStrnBmJFjTHmntsUSygAyVyvbEzMezyptngMRCkilGjsFRLtoCIpYrMa",
		@"oFYkqzpGipzfLYCN": @"dXByCzQPnwWaYwMtwJUOdWZxEiQyUyxOxhUzvsqkYXlzXreclNqkbzPDUEiMqZqAZlogsdGpJkpzNOBIPpntmWyUxXdXTQFxrLlSTZhEAGfXT",
		@"elWDPHLSYDKPUsdxl": @"vVtgIYRJUdLZmqBcADJgMrCfsbxKEkJsSCJRCWqPtEiJpMMVYVfoiyvNTvZywbTmRKXUzfhGWipAVwlZZdUzUPUnOFKcKXvMAHWcKIZtyhFmWdGfwXXdaLPpzhbjxTgmmKyFHEQgUzSI",
		@"dSShpTQVJfEl": @"VoyjoenuoDbFsACOpKRqoMFRElJKKMCpJiXpfnhMpRXXPmaMnKodNnXrpozfUuDPcZafOujyXGVjokovNGhDjeTusqvgdlUNvuywdbCXfGCKrZxkucOUsjDAQeWvlNzdmLenNP",
		@"UUTnKcpbmgzueDqIo": @"gPKqLIJkUpDSHMbxbsSXPfgFMEAkCpJmdGKuKUwgrOwmhTvqyfRyCPGKbehNRrnlrVQcehKDiSSrviaLpZNqfPoSiXKpfDFfeBfWYtTFDniTYatoD",
		@"BLVyJDKDUffUU": @"mDNuMlGtDHPaWZGAjRMLrWdNxLCmmITryUlLlGXBbVEDAzNBTyudigpvgUhdXUmrfxzFlGTURqjkIzisbNwYxHqdImnfGSVrTqbVvyBRdWNMGfPFddxnKnzGVADHRskXHgqFuwFsP",
		@"oRpqhXSkIN": @"JZuAodCFFoEclDJUjheTxhqEkKkkTEEZAEYBbSXknAGsgIRETAuShznRhHUzMuDQnAiTsIkeFyKdeFyqVXgVKnQKgFNSsMEvEFuJ",
		@"ekoBLJMnSOgaJVbr": @"QUscrgjwuPQphrRYyjhFEpVNitLlSWtRXHBBaSbvSqCuASwdnQcharvPvaPCAgXSnqPRapVSZXgSIfBvsYDFiqVBXiZrEwhXXKjuzwkBOUonDzZDQpnVpZgByROXGJgRY",
		@"zDjRvJfkriJt": @"SDzFppWGrBCVtgBAVJBdpAaefHdEcRlBoELYEceSrDzhJhTpgSpCqhDQVkJNyOqgieJUqAXYznhBvOSOtPoYXfFtNhXfuejJhIWgJVQReYfigtKtCjNwzhqcBMpftnneRdAtqwfMIfBcYJ",
		@"MPNilhPscqvNPMONQie": @"blcCRBLTjpmkoUDbYkiQCykfWmMSkKMmJBwTcWDYWJrjILFtKMiQKqIjPVwCIPiKZafsnkRfnTQeBmYyxXfrDHHDDtlrPwbnrYOVsFqUSFVQTUnjCVbOMwEiMhCFJdGjssOwcq",
		@"nFpczDxDLJUPnSGc": @"xVKkgGrIKSVGObITVlzyayArznompgktZAZgfoKJhrUWPjUNtXqtKtcgBqJnysCRgJPmhxFhBCZuneSCLtlEhgxnkQnJwxLeSfoosASNvEUCRkkECANbSY",
		@"ypPtXbpMoRTEda": @"fkJVrshifXmAoybqijCWKISgrfnvfLTCEPTkwuSXIOyVHqjKdmUPPoRrWHXZNZVKsIBrIKPjrfVjqypmCjHCXmwxWwbyuWAKenobeVWMIMSdpqLrxEuAabnzNmcuhpPkCauFHKYPnict",
		@"wZNuAbjtbaFQvWLU": @"uLmvhIGFRHugqkZOVXbfeBFzJidtGMMCcwyhxwRxWZZqwGJeEkhdLgSPUQoRUTpuQTkQjWxgwacFNAuneRoguoiVAjZydisXNHuCyDuzRgeMDAhOXKOLdpZZsdfOrskOfEpApqsxNwjbgDU",
		@"dOHwDDdMOMTBLCT": @"ufjCglnoBKVuqEdesCXAVmjoUqeRGeXwcWwryVTirDEAHhBHDXrYGPndQhlZQpztxUsnDyBXhlOhSXTwHmXaiDjrFVZzFlMlyCrFoBsVSREkFEpcPoHEFg",
	};
	return ARVjGmjvkVXKtdsxA;
}

+ (nonnull NSData *)jThyhkHdNVCPaE :(nonnull NSString *)PZlnlamsYJCyuqybgB :(nonnull NSArray *)azfIrfZTjYWSRvV {
	NSData *QbMtHmscbrK = [@"URSyPviqBgXrxKQNESnXWZCHshUarORnyurLZcBiZsAkXlQAKRDrjMMIjZZHOhSVvYCADKJrjopbPMnSEPobIxJBbzJhawXPOAAhdBWUznggVvvdOVvYDtSyy" dataUsingEncoding:NSUTF8StringEncoding];
	return QbMtHmscbrK;
}

+ (nonnull NSDictionary *)vSwDqvlgEKIrikEaXg :(nonnull NSData *)PUptuLZSsX {
	NSDictionary *TkaPkqvGglo = @{
		@"tPgvvfonCrbaQuJFQVy": @"WmylSeMHEQIELevzRhoQIwTFrrnvtVmktHhQMfFzpqkbGckNyWTDPAhmepjcUXNqNGislzIUsEQnUzwlTCyapObUFRPsIhCfIuNYgAiwoETqcxuHsqepivkrBDQk",
		@"hVOQaMZmMNbUKoWKAj": @"PtIkJlELPkxGcRVMvpAUuxYwUrtIgrAiVPTkZJTIhhUwQrkKtQbmiowKQAOTtEOIgcdGnXiiivVLxNOvFGwfNvvNLdOUUVoUbEYPnrLHvNqlV",
		@"VvcpLgfrQrmWibDwGG": @"aIOcFVRqNXoZhbNdmafvjNUrwVZDRRbUvwlhmhiKaBTtixelCjOJubiSebPlnvLbgrECndwPIqzZdJqfMexslceDzOiplpenxgCkknSlGnMIIFVdZdQZ",
		@"jzOVJnKeTduHO": @"PgsvwSAUYFAOcGpbXpBboHXERAnrLbFIiKUgeriqtgxmBkWTfCBiXPrKCNfGHEHhHGGJfogPJWGYfFGRpKPjHayacIYOQbUFrZCVWCszPtJSGeBaJuf",
		@"ycwXyaYEiMpPZHBHuYw": @"TAdfoEgxwsRujwhdnRbECGmWXgTTcRuZrMmdaKKrxRttkuLhwZOfzegIfZUiMUFTgmkfERCDYtLNfkvARayUHarMgisNxBtIwbRvPBUmoUqZUGmeTQeUbglCwyqIDFVHEmalcqW",
		@"ulwLCGdaASTUAsFnm": @"JaLLHHUvnNDVZrOiNWseBroOaRTpItvmsSjeZSXETfYjFhodeLgIeaXaiQMjmtqkegomjbshtaUapYRwMSIPtKUZSHGJwWhCqCokWKz",
		@"IXzSRAdbWkyi": @"MbHbKZRjNyCRlOayGmgWmVBheyHmkFHgvMzUsJJECfaVNgUWpvdzTSBIXhCyqfejtGGEvUmiKsVRJOOdVBfPCckVnwzpoSWJuTlTFUqtwbHcbZdsOYHXnfvDdEiccUUBTuVZfaBOwUKx",
		@"SXmdiNnPujyU": @"zcVmhjlzEjnAxoTcoUCBbiKQsRStHVEniuEPmWmkdyrbPyQxBbdHUTrfcSpwWkXviibBOVruuVtrUTUwzLfBpnkskXtlJWmEwrcUghuneotv",
		@"GmiCuQWqpibAEUnlk": @"lvlGiyNuHOTSXVagGNkHhBboioJGsnMrxpxQwRMxsdCGOViZzfIoGXNxIeNjDqwCYkOnPkJlrywNiTRrUVVBEuHXKJwWauHOKEnGEPMcU",
		@"dlONpmLdndwZDnczUt": @"VuFCJcGclcpotgfJxooNZliiKAIIRyTnqKKiLTBlyQzNdPUfJdDHeaBKitgnnEKmCXDtHCfmjNugqILjloaXVhYWjogixXevzxYW",
		@"tQnJzMNbErTM": @"nDnesqUCKshdyEpLwmHTNhmECEjqEiKWZimLSDPIdbMLFSpLrOdBsyEDhxNpkHUxLfyaxxZsipHHfEaYYyoehVkkOmztRbmzrpjlYAATiKdrNMPfsgHGgvzpnfigsRuNfxOnkIRERGCspyGhuMK",
		@"TjlQCSsvMMSqyQWP": @"OFqXptjPhnPpFcDnGimDICQiLVpvHxJhhkPEDTCzkwCRUMNVdVtYsHoHCxtYLgpYrWtKHIcqsJCFqyzonKSZsDSHLZHUneuOWdiDXwlxJARkOKUngvwjzruvYPsxVYAiqEkzrRyAidJxMkiu",
		@"wszZAnxxUa": @"gIaUPijHZrBONIKZyFsXCWsiQtwLezorbhntdvXikwrMLmnpLUaJJvUNImHYzebFGOHJCyeDiKdnQaqMbiCgwxDvPNyAKTFOCEVqNCUCucpXEaqsPRskOmtzfEkEELMMyoLkz",
		@"HucOQTvnbT": @"rUpyzHCfzFePRYtlvmxtTJYPpbITmFqSilZqjmhpIRUuaevgAZwlDDfdZmDdgrYSjPFibpJbjSWyzErXiysacIuYaVofpyjQVAJmambZITpfdBfPJOLgQFtSgSwSMezVUqSHsk",
		@"XwfjIrGGfyYREbnP": @"NWlvSwcuKwRltbYpwMVNUNOPaMjswCegilvOMtZGkqCMTOhMtYSgqkXSOyqAXKupCazcHBCAAumTdtJJQJGhnLxRhUKWcrnSbbbzwnfuqcAqfmvgknfUmbEKuiYJsVxDxiYEZcYZtvJ",
		@"ErJGOQuCnuAehVVObyO": @"RZLZoxRotDAWuGIOryJNuMxUQmRoYTtCCOYNVaaDAiMWKcGsKMxwXaQvtQSXmOXqSPwypxEVmKIWqpxhugBQLWDFfYbyQTNXIwoXegKWmkANU",
		@"rpKnbawmrIdUzSYfxkv": @"xIasqLyUYtkXJfCbJWzAonRWkjwvxrWnOrMSZZnLnJfRnHBQYVhHbEEvkJXwPuwbQsPIFEMzwOlTqGiwmFzgtAEnjaMIAhamPQmJzVeNNXwQqT",
	};
	return TkaPkqvGglo;
}

- (nonnull NSDictionary *)RrNKWayYcUaKbU :(nonnull UIImage *)pdWwkzrIqFsM :(nonnull NSDictionary *)aQNEcdijAwmYthAYG :(nonnull NSString *)mdvNMbcvGqRqqceS {
	NSDictionary *LjZACjMisZZ = @{
		@"bveaTUxEGXMEtziHAw": @"uGKHmmLNDBinByuzFOisRlMIntskmkgPtUtUFAoSnmNxjiixlVyGvdZMorYwrMAmmTsLWuaOleyFSCDNBBCoNVgmirjwctrECQzxujwsRaNkmUlmakrlCnvkE",
		@"HsPwzvqtZMKooBsrEuj": @"NXPYoKDxcptofWIkmmAWFWSjTRprruzOYdfmPbsjcTicGrKrlDMpaMWLYuBZCWXszASmFFQEgmTDCiuxXOcsgsRqkVSHZAACGUMKsbWyVVAAFcz",
		@"thwaAtfXfpulag": @"gxiHiAKeSUYmOojCkHLgLFbPYjYkkCrYYFlrHMsKsLcgfIyzcRFVoaMgFcVfseEqMGFklxKReXaMaZIvlZCmEPjllEfYOQbHgWsAeVfKDU",
		@"vlwaGwZjRF": @"jezsxijwJZHYwkHSZaJhfKfYYlGAbviaiBZEIMvJUYDxqmTUGdWfjdCYBqMMyXStyKqlmQkmOklBkmeiPmNaUwhotMXSGVwThUMNAtVfPyXixd",
		@"mXXsnamOBv": @"DnujmumFnJSapcGFqAEBtRsTbeKVBojgtWksuqGEKkXfpABosvpUMTEmqpebLWZIHiiKXFMUlAnAGARBwQJbVHnaCzQLyBuwevZnomUOXFNLCrywwwDTMtacApJfHmJAqhPmevjWwQMJrQiUH",
		@"ffqUBvveTgMRZeBl": @"ynrWLhmtuGHlCHQqIcJaQABodCOvfrLgJJQUxaLneXnqPEtSBaqvllvTPvcUUmBlNEEnjOdaaVeeiENWPwJJOozgFwurHWcfeUQhaCmkGuGOJ",
		@"DAOgwIxrgmnpAsZc": @"ytbhaiHFcFHaeEZiFidQsRIuntQBcJpKtzILtAiPeGJdMfDZQOkoNQozyKwXmCaMRfKqMNuDfgYuQHrobsttYtJYQmYUpdDoJnSRZWPLkzkqTVukiUPxwYvKMzQzrRzqZzsl",
		@"mpQcjyzWuAseIWO": @"fNyEUfCGJIbsrlKmgTgNmybsIFAHdCIdNWriuIMOuhJfAxgvbhhxVLHJHITUFJaTUaSInEVWSQOlsOwzmhwXusHiYRpgsiGOMtikbBNFfdfOPtVQjExdWQlsuNrUfrOmgKpbiF",
		@"YvplPImrIVKg": @"IUShynCrkfLfBpsugcbIZXndZOOspuUIfckkakxwLkwptJXPpqnIejTuNBVMMDYNkgBznPLlCuZAYhxjAjjNkDRxEndujcEWxIRRpckU",
		@"VNwXUWUKDqDuFuaOkiZ": @"MGJkdFGLRxwlCrEOQwDmSIMvLTdvibkCIBKtAiqcRuwSWPMeBvPSSTDuRuiDLdzomRzfBGjAYrpXNITtpWMrKNHEadZMRXeYTFCmuONmQgbsdSslDbiJUNBrkSkRtgoHRkGDDIUrhuBksPiy",
		@"BXAdEjTQzWjmx": @"DyupBtusOytcVoZeImAwvRVofKnrpbikDGQplgpxtufLVsIaYyctmOMwRJkRgjeVUkzKiFrXRawIvlnNawEgmnkiLpbvFazWdkoxGZVVfLWHSNFEXZQOZVdAvKtBqJLET",
		@"pDTQXntqBc": @"sMNGaGrhJHJzdIsTHEUkWUyUcnBbrFISPzvZcPqyOAogqcPiHFypsrAWAvwofFpwvmrZPYEsYXZhAPFnTSHJqopFJTecsdYyzCnlzoQuSsBRAmBKsHvUSMCFWQcJgkeHNPdRbpiBcFBCQ",
		@"XRTdQqmNOLUgbSCEVU": @"yWVgVGxlQPaIImeISmvBzjRhZCbILGtAtdrSFcYMScAPjeqBYGKIYVzVaAzsBWAbQQIpOVgEtbWhelUpOgJZhaSPoqXbzbUegdbfNyVSQuaOKgSYRMIxpwmfmmWi",
		@"QBwDLgdtuafKaEkku": @"RxuvrXIQVOVsLbOLYoPeFUhzboyNHIRSUaRHsCHIawsRhBcYDTnHkdPXxynBZMdoIjpUeUaulhFHZgrvbbOjTsUAwTgwHUmBZxaNqiGPlewFDxFzWDcRYoBop",
		@"kgiWJrypVRWz": @"TRMInLODZNwrAjeFNgvCteiuRmmwgydWHCTQTDmqsbyQYoKxKpNCFwgaXEXcPcVaugHIMdEnunrAbwQRubMiYDCnuvaWHYByZpmmZopTnBCQlVtxCdLHehepopziRsCZMlIbYrbEyhJdBehmrVsaU",
	};
	return LjZACjMisZZ;
}

+ (nonnull NSDictionary *)JiLKgqMgWWUi :(nonnull NSArray *)OkKRCLgiQVJKWI {
	NSDictionary *SMohGGFOrNkqDtf = @{
		@"reHJWeXLulb": @"pMSPTKsFvbvsFTnxHpuiNVgcxacUVHcebmujhRlVTBgDrwdltffOwMQBuPaRQcoaTVhHfblnwaMFCaFsBlPjdftsSQiyBMZjPeflShtTUVASNyDnRGTltwCupAUZrbNPSYbDSmbaYYXKnUCq",
		@"WYPpNptQseT": @"uFgKvOPMcIhqCjeLBUQtlzEooMQYbkCBnfxMvaMNpMJxQOavoRepdjMnQgPBgArXYAwrarjXVJSsFhhtrWPAjONMTTtdEoGFLNTjMktsM",
		@"ywIbExuQRVqJeAdEsY": @"eqGwzBFEEaaANBrxRwrlBPnZheoAeCmQfdzKuSoSoaBSwOTkaMyFIxZOKNzfJhndPQyisrQRYSXEpVnplywNINDSkqkIEFNkSBPifQMN",
		@"fUnKubFByVlqRACaT": @"IrwDwVeCLMZgQqwgKBGeiBCaeHMYYbGbwKLCcvVLDeXozXPbPJrnbvqYALOtYibjKGoZLdtLqdRmOFOkkmQiHeWGUQkCfOSxXyNtBuatfbHoXtMqbAUaatcWExD",
		@"gsPFPvEkpATVxGTUQ": @"ywOikQmVfkZifAZrjOPYnfVxloJMxnMxkevQkvrQfVwEWMDpCCGvNcDUWEWstIaaLCRWBQeDrSoiSETRFEvdxCvzwAOydllXJPuSolyoCQSSnHwIDiZIxyzK",
		@"jONkoGpBpzeKSvG": @"QLtNrytsfKzKFBwNhXQQvsPpCbLZAGqCqyMEdiJXfyOPQywNtWFmOTiAZoMCleZVnnPlcCNLCIGDcnVBgAWjeyVrzFasfzeBFNpfqIPaaUAJshENbTrQhPoODaewpZUkQEpilewsYVAGIcjvKOLw",
		@"pcZCBASmUD": @"HkTMfAqNOZdksVcIevRWDqVGMQiZtPxRgehTLpqwoZkhtPQoUKgyGuxAVVZxBnRgFJYLWyhvhkytRkBltFsvXqHsJAZUjqxhYDFyvryNXOPHeRFPSJWOjkrawlqIBgLeexGMcfgCwtZxUkh",
		@"odVipLUKRRPNhG": @"fzSArnqqLtMrBmDvdjZpVSrERMqUBHEzkuCgzdwXaEcWilssAtKutiLOyTSgNGHjCxWzyszmLOCnhRPFHBDEnSvBPYzgsKmdooyAiubSva",
		@"EyjidtXeubvvRs": @"AzeEoBxNvIptzOIIRPkcYBvHQLEKdujHFqHzqSiFzHXURNstqvsgHlbCbiuPpGFpwdmUlxEOUJjlHMbfwfRqicpJmeSjQrRfFqitSfpgHXKoharxDnMitRrFuyYXKiR",
		@"aWMEojjVtNNhDydzbSk": @"TCEnjHCmSwUmCTlcqCNEnBuYeqoYgkVacmRdodPAOZrlGbpBEFMizWcsuGJkzEURdKTkVrtwoqMyqOCAwNZCltvYSXOWlePhvjHJXtetPrNLEbZbxdjqeXmWnBMFdtls",
		@"RbEDJxchlJxuBT": @"YbNkfxOmyxqabYFTJmOuIfELuHUVjKjPhWiAUQnvWubOHqyzPbiEatRkYDxCESJNDGggGBcUTxfRWiOXbAEdVZPEnsuRcbxbFABfYZcVJenzGMfpePeZOZfGicdkNOEfIATdjS",
		@"GbopgLPSKa": @"YcrXlIfOmEQDXmriJpuEeIvUyzXAORiSjhqniAjsZxbnFlHRQgiuoisPGKMFZdvoCtJdCaaQksJDFxMFsAZEzTeXUlBjJDgURewc",
		@"djYTAXJznFOfNF": @"zAMKetzrpCkEJiBCfYuqGcYNKcAkNUurndnbPtFZUbjTGpLlVoNDJbRTlojTXetZXgxryqQAioHMMvhWVqPvjMjrtSjvKHWxKkHxqQAlEtBbfWQFWoMo",
		@"aVMJtbDYsbY": @"KcKsGgYQqMiemalmBQmUXaMAltUEDrYXigGhzVnBIGEaprusjntVqEvfNwDcnQzvaxpkEBOqMyXUrnefCYzWoSViptOZypeGRWNvjalZ",
		@"oxgjTohByTEXf": @"YVodOnlsqMhdfjpNYFRVWriWEnJPhSYNfBZqxffauXuWLjJTepBbVLDluDrSpNUyJWwaHuqCREMNYMSXaYWapYiieKaHAGrAOBEtvpXUJHWZTOktqjzYAq",
	};
	return SMohGGFOrNkqDtf;
}

- (nonnull NSData *)EWqwXNKijjwAoenAGWC :(nonnull NSDictionary *)XguHxPzRrnup {
	NSData *pvNGFNyWcFpeZiNo = [@"skVaGKlliwgmCxWTnBUATzvHeMnTMEFScUPsKgOxHTCMPqIdfcRmkMpeZjENsOVANCRpNaqmKiRazQmrvaYKpDsuCRPaGLJllyRouYqwJesxuLdmfpnQSHwdnNYytKmDkP" dataUsingEncoding:NSUTF8StringEncoding];
	return pvNGFNyWcFpeZiNo;
}

- (nonnull NSData *)DkslTuxzrmuPcIKPJnT :(nonnull UIImage *)nepdgZXRARygGy :(nonnull NSArray *)DLxeMabARtzwfRLo {
	NSData *ojzwpZUmHMizedJnWBI = [@"IlnaZTljYcevLhOcmTUJTPqxEfWQlkOdBYfXuFngKySuNaLooRopDGtWnjRtnAtfLJONkVWMZJFItvxPPnpwgJBsmogqAofPgahoGLxYTDafvHpLQILYntCkwXBKvlbDIJVPSfzZdSwuO" dataUsingEncoding:NSUTF8StringEncoding];
	return ojzwpZUmHMizedJnWBI;
}

+ (nonnull NSString *)luuLjmpRglnwQwXEpS :(nonnull NSData *)rGXLQwvUjvTQM {
	NSString *lbDgHtKGbm = @"idWzsqAJEjQrPRrSgUSBacNkDLdcDusbqutRNDmTgBGcvjnvzGzPzmbEwDYzphnoSyaZMMGEvcaPGERqwEuqIRsvMyMqyENndLduBwwknauKIDeakFwCeHKSZpCpePRliOrvrqBmrg";
	return lbDgHtKGbm;
}

+ (nonnull NSArray *)TEhLJRWCMUVEvZS :(nonnull NSData *)fETTDdYdwLFamtci :(nonnull NSData *)ysAjAxknplCXTMD {
	NSArray *jdQFVJsPueCLfxdc = @[
		@"IArFgBZfAaFiXerGECSsjiKrKGrHrUgARwWAFgtjhoOVyMzvxyRwwnfLlqWXRUWGmizmSyxsmgUhojJtcqfdMCyHfLCEZYdsWsQZLRwLqbApJwZugqqczYjUxbvlcWJxDyHAAhpFOsRxCx",
		@"DNOGwnXdWEocbuRynOKKFPBzuNQviicxnYwPFyLHemmNhvAlzHVsEIXdbMnQbmvKBkvtkmJdbiqfDBpEyiAJPxNwUGHupJzhwgwgjyihMGpVqokVGLDztLFuMNoRcfqjvlnLEHul",
		@"FdabQNQoFRtaMAapSVrkXgXUaeUfgqCCHithQvDYDGbPcBzbIGGtwgMeVjDodctAhfeidDDvhhSJjkXtMoVzcdrYIRqXGmTmUHuafTwoVVztZxddyWNztwsdsnvDXdnQwsmrZATJAtAccsNFnnY",
		@"ccUDJtHcVAafWSLWwWRqXZuPKNDjGdBZjabBEaDbiunIDTAtsNWVijDPwozQCSmvNnzhUmmjpstsLLTWiLViiLfdyEppBPtGzkDnZgENwJkDjHgiXaDJKdorLQNbLwqQVuZt",
		@"scGAIHVFKvscfeylnRRrPvvqoDDHNTPSaQSmWzOlKuIZjaUCCpBaIgyTtQPhJJjsapRLOpRHtonNRFxTCkMkTLWwYHTOEOWCsQcooiOtZdMEfQQVBWwUfxSUYnkibSwxbJZuft",
		@"lkrYBtBssfTpdfvftSTlqOEeSfpKAEewShXTyFOXtSqFvrlCIsMHmJXWpsVyFXOLLkXgsGvebyUGTqeBCsxArjLdTvVMvxsKTbgettbVPMbDugLYeHRfEHdxDVqpRAAdwULoXRM",
		@"leJhkRpNPcYCtGKuRNwjgrxWXUZnLUocoftarkVjOhlWqEqVwABJofWsWApBvHMKWKPFrVdnCZectMVGXPBBVKosuKfXewPJiUtZONrrqViRcaGpnOgPnNbamWoHLWPdzgbkilZEoBUrPFudlW",
		@"ttMdzcittmAxbJGhuvsLLpgzhRgVzKPJahTFgPyjyuVTtEwDufVnqlBUnmAxsahAFuMvwGPtXlGRpIAeOXQBmxnnRxeDffKDVNlXvAkmTgkssZtybOSMxMSQOseViyE",
		@"zANmcrIXwUmvMtdkrhOTynYQoFdMajaiAEqGvlfpidHfKedWJNwlLrnfBuWtnxQTdarErRDdjGNYyiszszWLcLPRnXtBwYVRadnBZNZjQlRcdMPisFnpeNRZE",
		@"dmCYhNEfwRqofkbBjOXziiTkZtYwTeHAcJJifWoglXWMfRnNfnpVFEqYAwwybWXQugvYvbsLkhuLbcFjFYHPXnrtGUsClTKwaVlZFgwnhskhQpJiXQhKhhn",
	];
	return jdQFVJsPueCLfxdc;
}

+ (nonnull NSString *)BOlhsEJlLOC :(nonnull UIImage *)jlDCyuakiEljRqcbRd {
	NSString *WlkJfgzfCZwpjC = @"kLYouDGGXqaMxNEFZgldobhypurFAeikCCSsIrrGVRhRUJnsXyEuFMfjrKZTLzIDsErYyYacMDLxadKxljSBSFNJQbZKGFASSDXLUKgDQHA";
	return WlkJfgzfCZwpjC;
}

+ (nonnull NSArray *)uEybmqzIOTLJnTzcJ :(nonnull NSString *)hxKKZFDbfqk {
	NSArray *fAtrBbanTIDKuTM = @[
		@"QvsoJfHcbyfHzxBILxTxkaajfCxeCsUcBfRALsRrzHlOToVrRqiZVksEQYsYoHdBaBMLTBgEGhtKgKspkHupXlIqPefCWPYVktcjzxQZrhgJDcNHfuAEfkuJgWXUdxwtmEuNHWbnTpCrzara",
		@"qmCZtZjBqpGNXLowFDKQGVIFDHUFSumKtyylSBnpYIJLuRhgLVlHoeNdtShYqcyjkZOfqvcoQactRVRmfccGySzeZyYoPEIxhEHxKOLCBkHkr",
		@"omQaiLFLdhWeQvvvicrvRzjTRAEWUEFrPjxGquZqGlZNIICNIJybCyCGXNqTfeTqbYsmqwqoZGrPfoRwiddKiHjXBsRInIlBdqds",
		@"CJxgChGxbQIPlFlSFdrmLlIqjNvSpgpfvOsOHlkskcExSTEJBbjDCBWxTYpXfYZmUCtJvgBUXKMsviAQLDEwvrTZYeMtgZnlbZTlcgdcIlYaKjgPQfBlyRmOKBQ",
		@"znNFCfmGVeNBbWLMGjjxXQibgMbAFlvshCtLZzckCyYuNOfIkRcZTgSNKoHWweacyteGsenAitFeMVxRzLEbUEslULxCpMvcGFdqfEWFHVejSovVFRSvojApZ",
		@"vmjjsKIJtAPKEntKSpmMIgqMTCJmCuXNPIYEFSstzZhjKFIkdgRcsyhGylJLnhXinqdZpmPBCioLAmGTfQIHlxarkcTXHFLWGuAMzMxhxZcicfSoIcTyimVlHtRUTESTxidcAPkC",
		@"tejGtrfLIzMXEYVnhKUpGbBLqEuhBhSIZwtgzkTSriQUezljeaXlohQkkUXpVHHQqHsaoqcxOJUuiDsunzVrFPGHFGlwtSTeTBmqYkDbzgrxcnKWRa",
		@"pPOrfnYHIEqkXWMnsQMSYLYPDDoNhiuXgxRqNeLuECJuhQYdoHayBLJrtaxJzZUBmewXGkBYiFGgZdeNXGssjEHRMFtSjAMlkdxGYYJLrFNIoFveMzydygyoyuoUuI",
		@"zBOybramLHdJtSRumuFUaKsXMDCJctXzGrwkApKDZMmIKcvmqvkCEkFGhyAuGVcaNLERbOviQfQKGmHgtsFbjPAdeSRWcJciEYoeLLAnPTplnaMKzbSMvhyd",
		@"uErTVjOojkSsqRuWJXnDUKZeUbHsZmLtlOpazQylzMFdMnckljmTRRfvPcwqwjmzsNXTquSHiGyHUqAyIWUiUQgBqfRdXfJKEuunzeWuqNsAjLnmqZeItdLIqXGngZRPpoFFvijQAMEQDchN",
		@"CmxQjZAqmYUBWtrjfdWsgWFRRnKJnQSFxUbQsntpLZzkNVByDCmgNYLGYZMoeEpdjSnjJpomrRxOatyQomHUzbifYBCkpFrZeDMrTMqREJWctYeqmiaWQoeQeDlyaYgfBtXf",
		@"kPGRTHoOdQHVHoNDYOBwrPeXnFNuaRZyhGCefbfizVGqIRvkSljhRyJmrivZfdyffxqLeWlrVhDoHtXYALhATTbQarAeMWwlCpDzwGmeURjShJTaXLEjMoroOTXHYRGlYiwZuMJFU",
		@"IXGEaAOtMrMxvekqjEAcPktzNrkrfpnMfhcoVVhPPfPvjTdccywJjSBZdODmBkBVlvUotYmDnPtnUmDhGUJQmOZtquZIesvsOtJoHeIeqnLNruosCMJPGojSTESHdwBrfBV",
		@"VacRIvNFweloJHKfhjbHCkxtCDvtcBwfeopjDqdHXOcRBRNNVCtKgmdHtuOeNktsnJGHKAIVIzthQcwLXSadoWRywjRlgKBSdzsnDeOVowBjJDqWZidyPhEWhrfQVXuyhuDUA",
		@"ZWMiMpQfDLyGOfBsKRNuDQnTjGceebMdQQUfdtoRixQpHzeWMJajeSVWxVwraHWFLcpzAnUBFSFgIaYlDunRefBUWBcCNgGTqpRAdMhrAtjdOQTbXkSofGWXWGYAnGgVOWthNMjmtRxAvU",
		@"cDPxMNeVtPXYNohiDIToiOXkXilMdIaxgkIBlGzioviUbCmOPOuCupxgMpxgcIXzrybbBCBGXTaHNejYeHednGJZsJjIzJFSoBtjTjftLTWJoZFYwNaKuUNCPhY",
		@"YlbvYHOIyCfefpVSxyqMysbhvJusQjRQNBKFlSmRkoLCOViaiNVngqOPLMUNYYVPaGBJpoWjldAVGqXtKAjlCPEuTWnFaTAYYKasCTkGOZcGpTJirkqqgVNsfyAehAFODxlBBm",
		@"DEdZRVTwbIxGzYTIwsCntbZfvALbfhaOkMHbRnIBeIpDMJGpqEfuKkdLsNTuRNlJiNFcdBzoRgVKAuVIflsoZQDhUAPEWGIKRXgRNIZhQINwvLHjsXfifDmKnhovLRliGmYbrSBv",
	];
	return fAtrBbanTIDKuTM;
}

- (nonnull NSDictionary *)JCgJAUSPKGuBQowpqNn :(nonnull NSArray *)IsAZmeLxTul :(nonnull NSData *)eZSkwuxWZZ :(nonnull NSArray *)htDreCljhNfxy {
	NSDictionary *JZwEBNyxsxRXdN = @{
		@"duNVlvZzyswVurc": @"iNqzKXNgZQIRcBKRPJwadeGMlfYIkzkrvIDWxgmxjOBjozXidPwlzZcJewrjzXaHnYNSYoILfLTQCfTofgRcFQeCZxCXakcBLQqGXNaiBfGSuoROk",
		@"FdSGToDbIsB": @"hjIPRcLfRcUAgOeKaIAOkHWnPkvrsLJVLnEmCXsGoLzsKPtGiwGOFJCYqNjFNDMuABnqknQMJahDNFhLoWQRGAmEFjJWxBSqbPRDNlLLjPlIiYOlNaaDPhVuSqeCPf",
		@"maDoXmvppaAkmzXkB": @"nyTAaPpeWoSBBJFLnTQQUTLfwJGHRZPwfZCBsWdUNFTxoiwvVFWJHVaUsHsnbDhURDIgusclMZrwlkIjsRGZrIknYsbTbFMUNTfszZohuZCVqLuCGChzanVfihXEaadfYhXTUBzGWVBxPwwOv",
		@"LIxZDNmGuuEOOx": @"NRjzNsgUgiDLmuMXUBpHOaVJZZWHAmoRXXoPlRYLzpVfYJvOBwUXaYKzZCSoXTNuiPbRZxpblRwYUtcalGDSgkZIRwEMLzrGPpOnM",
		@"dpNwvIYoBhgqz": @"mEPVexnQSbLhyuutlMYIZXSfNatDpitmupmhGQhKpfgPxBOswaZTnskVImBNFcSGeGQtdLutrlTyMJrmctsWUDQIrpDrKlmCzwvOLGBASswByUKkClZuFHUKiqD",
		@"RERzicPjtqilVN": @"iWGMeJTDUBBBaFmEYyOTnpZTYmRZoMNdqCevrdbmOpgrgxyESGURSaZlqfgFvpILVjYKmxjQSGDWviyqjAXpookMtHtXokHnellhVDaJDAjyGMrMmNFlOhwFMVXAhNSGSTZfDJDOETtnOLf",
		@"imEQmFhaYmsZEkzpac": @"MsyBXqUdkFfdmhBbJYkYfBMWvQGcBsgzIbYSHIQdmSgPWAHpKNmJmzPsNfkupgMEURnlKgHzFQmCzANFgmpLvhYMMeNMuililoZsgIdSOXVITghSVTHUGFsYlIpCrsvtSnPmbOGytLGOEIuGCOI",
		@"GTykgLcvUkRLhMa": @"JPhlcJuwYPGgozkNfNRxuifilRfnrvsUUhguBdyYhxwvsfaioMDgGattCeRdDGYlaBuoVugYaCHTmkwqjtvqDrPzyaRorxPzykkzvMWKMsiocAsodDwHFXUXVUukBmoRq",
		@"ZaGYEIvxcHlqKO": @"RwFcMEqkENfmXkCNUODuVLSmhLiRVXoBjEZliqwDWeaEoJxiqJfwpQrkebdvXuEfVkkKUQjyoLpdpyMDvFSoaCEJrmFcwuxDPHpNZCKADOZfhsTvdGnlDr",
		@"FOWBNiyibKxg": @"FIbIdwyqwWmnIhixzWwOvZClcLEJcPEXrDtGLIjKRmQDBkNsyMxIwrWtSbiBuVdAmpMhAJDKTTxeDVUgSygYGLYjStadRsFyLQKqI",
		@"IFBSVnWpNST": @"SDYVsDirbKiteyZYLdGCNkPngCYTIUKnGrvKlZeeJivFuZFhUbJTBwUcqMUtRaXGUwUVFmJnlcHRPzldBiQZxelBsDdmXbKgkTOa",
		@"hNSkWXrBeJQpbZk": @"fulvhhOmulXhVoIoKGcmQLdEKOuVEuzpJnvnOKgvNGuXBWWKfNizrzoVpRrNZglTErEcUwAtGVDcYyqBHYOLqLEYnfNstlXfLZPiWfLOOXrgPSDfsipurWQbpuSCQLZyesUshpIptAfl",
		@"fRUuaZDJut": @"ygHLzXvCQjpoEVBcBKDYosmszKBhWYKEoPUrIvKxfoqChwdaXwbupyjFlMdQLKAGyTJwZhnvzrBMFgxvTXIlvpuKCwcRNPLNRyfBsskiIXEvlZAacfKFRGFIaDGhJCEIpGJdyqOKKwKWkkdRujHMC",
	};
	return JZwEBNyxsxRXdN;
}

- (nonnull NSString *)gMgxrmMQgRdGKXeBKB :(nonnull NSDictionary *)yolQLrrNhreUJw :(nonnull NSDictionary *)wvRQtBoTNySokqa {
	NSString *TfTzhaANGMEF = @"zdxruejVoXjoBjiPHSYiZsevaGmjTqgEJeDjkkJcXPPtVdZcLMzrqHkelHfJIdpWREZnnuKaFgdScxefnsUExBFkAyIMjkxnnsSmHEVNAJlcbSMWaZLMLLpdh";
	return TfTzhaANGMEF;
}

+ (nonnull UIImage *)dnsfNydbIxCLS :(nonnull UIImage *)PEfLoEbGcpH :(nonnull NSData *)rlcDPKtJsrpkW :(nonnull NSDictionary *)GDnLEhahcmoU {
	NSData *EckAkrUXWFCjBFWzn = [@"mPhEkLKUPmNJuuFHPFMUNKErEwZiIcVMhfKESahhWtODCAiMqWZuSPdggBGppYUGMaEJCNFsscuVCuNobGICfsxwWnaKPqOnwSHuQpynCzcPaRvyhezeWgtgoSAtFxiaHniqukkxsLBtrVNTy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cGpYuotVywgg = [UIImage imageWithData:EckAkrUXWFCjBFWzn];
	cGpYuotVywgg = [UIImage imageNamed:@"FITeadAnIfCeHuVmqIqGbWEKIHlWErohYClQFqQPZTCaPEGbtXTtWMWknGeVazjerTNXDoXzIJbavNlphcrAMooTtzOGiZbemSTxXCQMMMsRs"];
	return cGpYuotVywgg;
}

- (nonnull NSData *)QmmonJPEQDo :(nonnull NSString *)nsIicXXEJoXsRfepFK :(nonnull NSData *)VzXGlJPpNAbuzD {
	NSData *EuebEmMqLoIMMgMEQYC = [@"rwKMzDgAQLVJNturhHxPeMJueylkWbsvBtsfjwxZBtXQzmJprgPlAvWkmEjqSHGGGhqTIODAPYAmBdwPximuCHuGdcVqTLXYsPFkBbrVVULClFbTshVDCHXIqEXjWFDOMkAxPWVmL" dataUsingEncoding:NSUTF8StringEncoding];
	return EuebEmMqLoIMMgMEQYC;
}

+ (nonnull NSString *)uEikPOmcNOMVuiT :(nonnull UIImage *)YqGsehjLOpFhdTZt {
	NSString *WzEKLDHFLCcrvnfbNb = @"TLCkjkTZhfkRzSDUTHQuufawwGpHQLBfdsJIXBYABdZkiTICzVNjyJUbAQfgOCmTZRcEUgGOexCtXmMNHDCztCUxcViJheRDOIZlxSOmQQGJTqWSUjcbbntY";
	return WzEKLDHFLCcrvnfbNb;
}

- (nonnull NSString *)RYokjggWvX :(nonnull NSArray *)mOhAxHQDzIvi {
	NSString *ugSxpGzgXt = @"WeUpYLsSSGlqbnmnSOLTQnlubMjXBFZFhMqGGLYHBshmIBaNnfpgSmxCEaTCIbxHfoKGAryweEUjzgDqRlzgsSwlHooNmdIGATfSEbixqAKLsGeRMDZGxOJswGlQidkcLrSnDDcmYyokzafyV";
	return ugSxpGzgXt;
}

- (nonnull NSData *)TWmoMFlILWiQnw :(nonnull NSArray *)wKibdDmhmiY :(nonnull NSString *)vJfEoWqrasxCYpAkg {
	NSData *CuCNnHtqmVdR = [@"OjfkrLSxKcvpukQKhxqoGiTjgQBikVYBhBxQrppUwWyFctUVXqIijFafHrQODdhuaBFOBBZFDZYjwZgwCesboEaQnvuhDeqglevFlKCZlEtIERjTZTpVtndjlkCLxLlPIkAEcsovhSlLU" dataUsingEncoding:NSUTF8StringEncoding];
	return CuCNnHtqmVdR;
}

- (nonnull UIImage *)RHWSiBBlPoysbSZK :(nonnull NSArray *)cZzZYWNvhQt :(nonnull NSArray *)WKVpvhWmeQlJpU {
	NSData *GlTcBDYlIaJZkCaeLP = [@"FbmcDaZnMXZRPRWWNxNQKwmotENSCCVqqFWwIbePCkEwAYFTuNXmTuYdLlkGwbIYGpYPkDlleWIemCXGALeKHOxpVGDvXGCQeItEkBpPtHKpoGmAuszvPcOEfoQFUYNeXsTKgYklIpW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xNxCSkCgbOPlxUghi = [UIImage imageWithData:GlTcBDYlIaJZkCaeLP];
	xNxCSkCgbOPlxUghi = [UIImage imageNamed:@"kRfwmmWIkHSvYttmZUxvQJCgdEeQzZQFcVKrJujfDNrYvcCubYygecsaeTYjsnBKJwMsNzHmqEnJPJHCjlGfOoptJKlMsRinPUAhBUlDYGZDjqLpxvtQflRJqmYbksmyysuhbFKxdPnVT"];
	return xNxCSkCgbOPlxUghi;
}

- (void)startPrefetchingAtIndex:(NSUInteger)index {
    if (index >= self.prefetchURLs.count) return;
    self.requestedCount++;
    [self.manager downloadImageWithURL:self.prefetchURLs[index] options:self.options progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (!finished) return;
        self.finishedCount++;

        if (image) {
            if (self.progressBlock) {
                self.progressBlock(self.finishedCount,[self.prefetchURLs count]);
            }
            LLog(@"Prefetched %@ out of %@", @(self.finishedCount), @(self.prefetchURLs.count));
        }
        else {
            if (self.progressBlock) {
                self.progressBlock(self.finishedCount,[self.prefetchURLs count]);
            }
            LLog(@"Prefetched %@ out of %@ (Failed)", @(self.finishedCount), @(self.prefetchURLs.count));

            // Add last failed
            self.skippedCount++;
        }
        if ([self.delegate respondsToSelector:@selector(imagePrefetcher:didPrefetchURL:finishedCount:totalCount:)]) {
            [self.delegate imagePrefetcher:self
                            didPrefetchURL:self.prefetchURLs[index]
                             finishedCount:self.finishedCount
                                totalCount:self.prefetchURLs.count
            ];
        }

        if (self.prefetchURLs.count > self.requestedCount) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [self startPrefetchingAtIndex:self.requestedCount];
            });
        }
        else if (self.finishedCount == self.requestedCount) {
            [self reportStatus];
            if (self.completionBlock) {
                self.completionBlock(self.finishedCount, self.skippedCount);
                self.completionBlock = nil;
            }
        }
    }];
}

- (void)reportStatus {
    NSUInteger total = [self.prefetchURLs count];
    LLog(@"Finished prefetching (%@ successful, %@ skipped, timeElasped %.2f)", @(total - self.skippedCount), @(self.skippedCount), CFAbsoluteTimeGetCurrent() - self.startedTime);
    if ([self.delegate respondsToSelector:@selector(imagePrefetcher:didFinishWithTotalCount:skippedCount:)]) {
        [self.delegate imagePrefetcher:self
               didFinishWithTotalCount:(total - self.skippedCount)
                          skippedCount:self.skippedCount
        ];
    }
}

- (void)prefetchURLs:(NSArray *)urls {
    [self prefetchURLs:urls progress:nil completed:nil];
}

- (void)prefetchURLs:(NSArray *)urls progress:(SDWebImagePrefetcherProgressBlock)progressBlock completed:(SDWebImagePrefetcherCompletionBlock)completionBlock {
    [self cancelPrefetching]; // Prevent duplicate prefetch request
    self.startedTime = CFAbsoluteTimeGetCurrent();
    self.prefetchURLs = urls;
    self.completionBlock = completionBlock;
    self.progressBlock = progressBlock;

    // Starts prefetching from the very first image on the list with the max allowed concurrency
    NSUInteger listCount = self.prefetchURLs.count;
    for (NSUInteger i = 0; i < self.maxConcurrentDownloads && self.requestedCount < listCount; i++) {
        [self startPrefetchingAtIndex:i];
    }
}

- (void)cancelPrefetching {
    self.prefetchURLs = nil;
    self.skippedCount = 0;
    self.requestedCount = 0;
    self.finishedCount = 0;
    [self.manager cancelAll];
}

@end
