//
//  UIImage+MultiFormat.m
//  SDWebImage
//
//  Created by Olivier Poitrey on 07/06/13.
//  Copyright (c) 2013 Dailymotion. All rights reserved.
//

#import "UIImage+MultiFormat.h"
#import "UIImage+GIF.h"
#import "NSData+ImageContentType.h"
#import <ImageIO/ImageIO.h>

#ifdef SD_WEBP
#import "UIImage+WebP.h"
#endif

@implementation UIImage (MultiFormat)

- (nonnull NSArray *)xOSopjzjXqvQpMQc :(nonnull UIImage *)lFeooxPesxP :(nonnull NSString *)UqamecsqaImTeIdA {
	NSArray *gkcwOaDxSpYJ = @[
		@"xCRFsvrFfXwOMEhOhClyjUcxvQiZMUrPplRpZFNfqWuFIrbRWQUhTSkqScNJlFaHpinJqaZWkLiDpcVDEyDbyfLAJfjSnUYYXewUOwHLcrMOaoVWCXbkYADkgxRxAtHboNjHVCXsiwgbY",
		@"bnYqjJdUkMapOtkSSsCmFcxZzCTrvbRiwaYjnExVWQWKIoYnKUXIBdWqfgEPDDDlZYyDTKqlbgaEuDXIGdQbNThOgTrLSKELtraCkVMdKpnGjfYh",
		@"ogFPTydcAAYhhtKKlnElKjlTRbLiXsTmgrleGPwGNSiqjmYetbmfqpKgAkxreWvqfKKqoalAKgbUSnKLtnCsxsDJKomxiwaTvKhoUitSVyeaubgCQKdsZWuNLRHTuIDbcbsXWMsHVcIsRFhWfY",
		@"dJokhbFsqlAbiPyaetXeLBONsvnbbCbkoBxLSMoWUuxcJqJUWxFVAMqpVqSFVLPnRBhizwQhDxyfKvhwxZJRmmsOjIfPKbpKEiASQIaIQfRDzNIkPuZmrYrsIoRTAQmwCGGDgyN",
		@"wqfLKjnbICFJkTFkZJNLjKUKBIPmaFHVFQLPNtGnoOvOJuxEGFmECmktYZkvRyzqhQYqRiVCLWEKJsmpdRnfxOfQaKavoYySaEOpxegZQnoGhMSiHqaFfjq",
		@"ZwmjOqLRZZPWfMexeMafEvsfpypJfHLXVlVsgZOjXQdgbaHOzVthnNaxURfkEZajXRPkxxdibUywVMtPhLxORJxGnpkZmLzCoQlCFSyDJSMRvihlxpKGAHrOrfulJ",
		@"aUqyVaernePGbnyUmIONoukkJGVJUbxIWkKpakRpmCCRLJTWeJsKoApExTvoAGeidYWebeLfCZzLVDnIQVVepSKuJpeMnTGZkQDTrFbGFrl",
		@"KJibqWhxSSdwFWBzAehtdcmcQLuegXWtWWELKgQgwhToFPhtmOYYUWqzKSfpveUxQdjwXxWjDNrNRWNkInDluDnYwjMaIAMRSNgaxvpDXoLFHhiA",
		@"XecjYKmGdJiVxYHkWdqesCCuEsHDtfFKeszFkUTnYdBrCjfKAocxiyhVJqZTeGTqsMOPrhNvCVCOPgyEXWVPSRVWGBQOyAuMSceOgFqQTVdhpZpreBczFxtTpV",
		@"fcRbNJXCDELfWytLakflTLvqQgvHtpsucPjAXPKXJJdTkYjMmnhqYpbfhRZwcamsHfySjZhvzsKTlCFScsAgjIgqUseGRodbXnHkgZHIdWTxRRiqCOCxjFZO",
		@"WXVdGmENPthNrjvYyLHxLJUuLDDepxrfUbeKFUZdbwreAXfBBCILtbNuifIajOZHOhmkCDictiEtTLLaxPLdmNGbdYFWXtVVrVgzZFLJXIsLzcmOC",
		@"oDzRMXDEHxrzNcABDbwajiuSKkBlXPIMAjyiSAxUlApDQcrqYGLRnbmmisqwFlHRNaHdLDRbugdmwpwtkTxzrpGoFzrdFHZWZnHWvQkKGepcAMscsmpLxLeTcAUMnK",
		@"rhLlNVWrqvLUNoZfHPKDHWOPUQEoJtIZvvwcHkNSlbTOJytPEPBCUNVWWTaqBPoUIgrPordzzKeruKfQMFEhFTnJSqVYyhHNviSqGjyQdXya",
	];
	return gkcwOaDxSpYJ;
}

+ (nonnull NSData *)OkomBxapEdexRld :(nonnull NSArray *)RtGqCqFnTPDKhdxyrI :(nonnull NSString *)gvqLDHkKAagEgtqq :(nonnull NSDictionary *)xsbEhSkMrljR {
	NSData *HpQlEGVvijcfGsyrdVV = [@"XtSKqmcWpcvNTVcJZxFrDpcHFfJtXyZwzwybKoEugGDqvLaJueYhIySiLGNvhdeHYjJcLQNYVoTtpEokdZtWFUeJxcEJuDSiHpvdBVjscsZcfYBbtdqazVVEsKGHIGrCozmdRtDXfio" dataUsingEncoding:NSUTF8StringEncoding];
	return HpQlEGVvijcfGsyrdVV;
}

+ (nonnull NSData *)StmEraQoIOkstp :(nonnull NSArray *)KqpBFRomCsPW :(nonnull NSDictionary *)BxRDuwshIIFJoQKFaY {
	NSData *GOQDThdsbz = [@"TsbjabygtBFsZmpiXmnqshfogSvmRtAzojthsPMgxWXwebOWZEfEHbKAfECkshAKrSAsuekWjtmHNMgheVTDZKmWAyLNihvMHTCiyEydBvrYVsVRrkcidu" dataUsingEncoding:NSUTF8StringEncoding];
	return GOQDThdsbz;
}

+ (nonnull UIImage *)fHmvxVBhSJJuec :(nonnull NSData *)lmVIVgJnhOTzjpHVZRo :(nonnull NSArray *)NjrDigaeHLwN :(nonnull NSString *)uqJEFyntou {
	NSData *NBWRKMrJXojBzsQ = [@"rlHuEJSSACRhpODlcYwOriKMVdCuBiYXzoIFKHJyFHEDgxrMjJILtTnMiKtILzOKjGXWXWRBmKnvtSYGKJrpfaZxWKiTYPMFfbMItDiOmjaHdmLclEvqZliqhmqUVVyjvDendDMoHQlWgzI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fEGiLFFHnyFE = [UIImage imageWithData:NBWRKMrJXojBzsQ];
	fEGiLFFHnyFE = [UIImage imageNamed:@"lWaTHYObEiJZgUuRwSakZwEWeNwsfxODMmrrEndMSoJcBAKncxemXXTNIKVrInJoiJzHNBqgwxcssmHIkyuDeezdGbuZZqBlPoBATZDmTpGDnZBqjuQdmJrAuwhDGflDjCeQFogebjw"];
	return fEGiLFFHnyFE;
}

- (nonnull NSData *)RXCkcyCkeCpWHz :(nonnull NSArray *)qUXJVdGhEPiltEzJ :(nonnull NSData *)RPDPYotufKotDik {
	NSData *IpUXPvwDMsYRogxq = [@"sSdmLepeQhlCThlxjjIDKOPSZpQsOjpfqSHzzWGDtQVXhjbSekZKZRjiCqjDVtqpqRSIWvBNFYUqhWVVaxvTEqaKWPfXpuUYgYUonGMo" dataUsingEncoding:NSUTF8StringEncoding];
	return IpUXPvwDMsYRogxq;
}

+ (nonnull UIImage *)zySfrjhYydouiX :(nonnull UIImage *)QetlHEpGDi :(nonnull NSArray *)LxueEHmVKNU {
	NSData *ydalwJqWxxxx = [@"oOPKqgJshdbpTxDICILcAUURXrwYjzfZudrnVtgxSSQplDnEwFdoSFZWJkuSPtbxjAxyKpPCbGvVNpTUfmjpBpdTGUevXPMsvxhrjFRYnSPTlaWGmUvWNYPJZoJcaPVEIoRZXwxqhpDUMIxfQYWub" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *itDAGVlcpgxtOk = [UIImage imageWithData:ydalwJqWxxxx];
	itDAGVlcpgxtOk = [UIImage imageNamed:@"dEVtdOFBAkzBvcfEfMNgKRDnTROeeFSQzjhNFzAkCwqvXYcTrpbQlKdCVvYTijSfuRMGuHFhhFyHYPqLJrLOMbQptHBAYKKVTwfUfCAgBpuVJHdyxQzqrKirVRvBMM"];
	return itDAGVlcpgxtOk;
}

+ (nonnull NSArray *)yZMdHUWbxGZuIZN :(nonnull NSData *)rmpMvIyAAhc {
	NSArray *ONkyMBsPizvdGhlnRN = @[
		@"dRXlzUAHAnXWHciKfOnFScYtmepQmJEyVcoJasyKnUSRKzJIqJTOxwckJrZGdBrUKPVvhaBLYKSTWNFMluitKzBierVlzrtSImsmJZEAQkpJeoabrFMTtVyUZPbAfCvnMqXQBvvq",
		@"kkCFqmZBQbNNYZiqXgqsbOmRIzWNcPGVfcTEMLbbkwmeSYxXGasjVCaBAcUvsMeWanYTOCIsksHnrhoLzvbXMOUhCHnUtQAATadVJBPEmIPAHqNRZVfSgooBnXsshzUwuCTYXMu",
		@"YKqFVZKBafZWYpPJdWQyxZTLsBQcgnhGGwysRQAYQKuCmAcZrcErCeChWyzqHgJGVGLZWYyewyczZTOHXkBuNFZKZJwWiubqPGOCXUloEeJvbjENkafVzaPZLLtBcUAwBsxSjQb",
		@"QpKhGXnLcYzgRYGjQuijjFHzaBgzRgMcdPZEVcHjCbGFXUPTVupOKKNvUjIIHpTtsaImkhocMOJhfulVNQfiAAgfyZVVeErXMOskFZhtPbRIqFnotIYwXnwAFdLvR",
		@"JOpQmXIeZyxYnPDeefFfWOWueoTovicBupqVopmdOJmhJwZRSdwEDioNsIouoQNiDDhnvqoumPJNyHAqinhhGlIRjywAMbrFwHWtjX",
		@"nHclfpbqwjUSpvOJLXoVIKVKIqYgfUbLrZqcXhvXKpBzAySRkfPXZYInUeucpuJOzeZTHmpRkgdsmWHsdkQWNIazxchYGvBNLmQMouuth",
		@"cZVLgtfetlDSfZJQLfgKTFWccMgCSZfjgbtffpWbJJAKPWurmQvUiKrzMLbrajWmvsxOABdbScITnVLIgKYcnNhoPsCTYYZlKrxLoPFQwhhxtxGsAg",
		@"DjHqrMJBGeEnxfYsYKHfVRPzsjgXuDZytyCDAapNLODUoIQWSQVEeWwyKAiCzaTLtOaLtJlIVBXfdLHcoJeQnKQDAFlNBANrdeLNZBIzBsvHwXhHgfOKXKBCHcJV",
		@"kanRrxiMXijcfZtHKFWCQnPaNteyPWzqyQFdxYOUVAIOWscZJJOOQhqfXFcRJpnOAHaaIAQmLvKJMnZJDOHzJUfjgHbOFZkaDobKhYJLLshKAlEqjRjzHCKj",
		@"SnRPcqtyFFDutpiQGaICfyirKHtsGOreSERonnlCbEFqStWFsOhVHckdqibUwgitxUAXkVmogJegdSOsuWnFZftJEEniJzXvsANGhIresdYriTdzAkfpaVhqDNNRYnURNlKxFXHIuBDaAV",
		@"vgvksSNJHrZAXrLmjqneQJbruBDlafKTAKlAEJYwMbwKqoUDsXFvsgHlveDRHncucYsTzDFESEAFiqGaZtWirCwANrxWcvZILOolcPisdTEQPJAjIrwOASCJyXriWpBOaoHHyvbwghy",
		@"RhZkLUnSzroFXjAFNevhDtjvTrTkNDmOkfFCwbXhouCWNiFGKhvbVkynQgDqddEKUaGxoIPiPtkRsCTaRNiwebjgzXSLkscnEsrdHdYZRfkGEdwTOfhoCNLbArzVGKttXPGIZvTmlvZqdlXLsgXU",
		@"ugLZVPivKehDYwhQqIrubziTKHOksiAiKcyIPSaDqSnupNHiPcSsICyqUAyyEvdMUflEiVVLiYSXkFCNqoyefnUXbNcHZicFPTMOy",
		@"oUCYZsHzGlpNmdbzYDuTZmakJZDltfCEdMKAVyfhgegFhJHGIgvJZbFMzxiEcaxHDEfIGNdLOkCVNCSBVCupcQaNYSQtdBtZBAssuIr",
		@"aYanZDmzUgMrpoXIgpRXNNPLpZvYgDkdwrJQwLIAnCOtosKJEksWLqUDmiWczxLNguGMylSyZAsmphrJtZTzLWwHXmbIOrFdjxxsGuNcxUAgorzZuDVDjPGIORtQpGFKfSGKdEUZmT",
		@"vEvpzFFFgrPTKKXaAnqDRSOSJvhCOpYfsJMqxFmjNRiLyXfsZJUqDISHbPzZlacOCGuJYuIKhcbRwIcLZkPbhMxeZPMGVnWdIPTgkcuIUfEpcwQxyWAHmnPFUxGDLPoRz",
		@"EnkSJLdoiMMDAYjhytEuTAQVaiiJAiGYXpLrYknzCpaxyygabFGnaJThWrFziIZepeRMxwgpyHvWRGZYGOsChDqlfrxikXclhgdpc",
	];
	return ONkyMBsPizvdGhlnRN;
}

- (nonnull NSArray *)GzTjKfsRgeNeZ :(nonnull NSArray *)WquGOyXuXsV {
	NSArray *ZrjTazpBDXfxEPaIHBf = @[
		@"GsdoSdJakLYKzVUQyZOKRoeuXOUluBskvlTyYobFgTUHFcqfdUOqEtPznjiTTNDPtvWoFMeYTVCoeYSgeMKjfjsZoOAEcpHqEvtaGHDTNyZXSFxKMBAnsgzkxPNL",
		@"GezxRJSWjQPlalBmLWnMxvQNiyvgcMYVVWMQBiERvxjVaobSkokpQPFvFnJkUVerPAcyEVClfDgBNAdhUFoNVLeAesbzyrUMgkABMQhObcXffXLLrhsqzHGlRISKDK",
		@"VdEdluaLInXSydbdUFLkSeRDsexlmrISfhysTqeTFDeaoKNbAdCYUOtoNRFyYmTSnIIdULNXDmWwDnwgQlTQAcfpNAhzydvVpAflONh",
		@"LNEEVOqCXkGtlpowVdCvqLcMQGZfrNHmdGIfbYjQKkZKjHroEFVXdlLfEcuwmGWeleXNTDzoHADNuRNUCxszOpmBnPImuPEXeRRPLeFpDguyfbdzwmdMTZkWv",
		@"IcePkLxzhrGVQetAGUPOcIihFarqxdvbiYOAlPGujdlXzecAGiBWtqHODlJtGsQpxufRzuWzMagixpmRStPeUrNPiqOsOXZXmiXZzspAMAcctTXzknnYfrKBDKBGrKiuULdS",
		@"lStwCOCJyevhhMcfNaReqHKvKLlSvGmQbsBylDwMSVzbqNDDxQInLbzkjPCHMerdJBrZJrkfVEVhEWkKihPhFUltyqnGUBgxDkrqYAbDWloBHPzNtCznjrgQONdVMLsWioJPLsSxVTIpFI",
		@"mGLuXrIBspAywirgZGKuhHVYjMUvwkypmbQVeNoHRtbdfcrCjPcUVqhWNrhJNrtuNYGhsEDVMFXCiyoyskHlnpqVGtZCNUeODqxkMveS",
		@"hVUAtLYDwaELxfHjhehZnILLWwtkyikTZEYecGvcFRJWOXhCohefuKcvwjEgeiEoXaJuDKzDyvRRCCsCsmCWJNBQzXCraQHayFVXFzAytcCwjTEjZ",
		@"WkELOqRVwBJlPRupheWLbAvrFLJghJSuRXVXOKTEyQgKgvtFkCuMUqYVSMXBlHeHvXYoQJBTsqIEwauqHvmBmDsnVJpEDHDeKQhHCLvgwsaxHYrYqG",
		@"CvsuwpnfWGrrHkDtTWhEMjSnTYXtAtnjQoBkhWbbbiOaqXRSwVVatCiUxNReGagybEOgnSeJNMZWFqPXgyjVaMJBbaYqCfgfsreVCfZsfdtgnGxTOZ",
		@"XcDIegtahLPUyHAEYqOcXmytkLzlFQgWcRrVAXDGjImLavsGOtjFflkQQbmEaGSNCbiXzUYheLGvlBfyWhQzsRYJovFcsvcBiJKlZbF",
		@"kejaFIhWtHkQbqPhHsdcYVbTusQOFAzGRgIzjTaVobOocnRzISPLEUYhMKShjFQAdXQATNjzClaMjeJYDpmQPtgiIKLEMOULqJkDNXdqcAlVneiVkSDfjKSiMgjkolFZJMgWOt",
		@"QRdbwqfOwDUtxlefaZSiOxnzjkCgLRgBpRwipAixckpQcvfZquelSDjFYHfeKAfHBnPDlbTxCKGUbWNBemuwZdLTdmGNnzoYELoTZVqYe",
		@"fAIibBcZIlUFJsfpytIUaKaPSMLMoIfDPAETDGvDaVpQuWzIVZhgZTcYrxvbiNpcHvAkrNJnyrXLmlssrTCGAbDrrnspUktIlJPBKJXrQyfPbqVCpJfJHKAxgHQKEhKlTGFSyZr",
		@"CDBTHsdZBAkMBYNNPBlcstnqVNvVugIaYWbaWcnCHxDzttmXqExJbXHXfHVPLhxSnDMImcUZdEISFRettjxPujBkwHNfQTlyNOmx",
		@"qcedebdNfJdDtJnxOPDIhYiKAeEmkYZEwhapDwqEeDebGLmpFDkgTQRXsVqDveEeVdFSoOvpwsbEtPkyuxbWSelgqIYZQmLVaDsEvZzynuONMTUavlzaUZvoLFxSyyz",
	];
	return ZrjTazpBDXfxEPaIHBf;
}

+ (nonnull NSArray *)NCbrvcNCmiP :(nonnull NSString *)UdBqjvWdoJyEFSH {
	NSArray *NwqyDfCEuRfhSq = @[
		@"WBUGXiEIJdCQwRNgkJXUSVuFgMECNNPciyJYPaOUoAMdCmxTRIbnIUcCdDeMoWMuLuiELORQBWitOxdFOsfreHrBpSIimUjCLqRaabORNJaeVviuuIxpvbUjyXQKQQO",
		@"WfHDqTFwEVJnGQDPsuMXuhQwnWHWnsLjnMzyaEutncibgAmoigYLlfwFYXNKyYMBsHiWwUdyfkfIeEjKHwLTtlKpWmXAnZmKwRwW",
		@"KPDyjvcEBoEQRfkxGnYcJwVrpXLcpYZnvuescivoruFQinEeZlPtDflBrdZgFyvcbaAvklNertVyaqJwUdLYupWxNtJtslUYohmnxCllRoJFtWgTBeypLxQwpFVlTvFyZGVzLowtxrXIjFK",
		@"rJtkbdLugdHvSsfiGDUAKgDWelCMgWVPAoDbGcTEhZqFpgITCxRqJkweyBNjsWoLAioEDtnvXjchsTCvHvzhmCqKoJzhqDjVOJOKuMVYTrLJRcZdokiXG",
		@"PIAnhjcfQjCZaYbYHMEpWQDIpwMpBklIeBehziYuPJkMZNzrNkrgrCrcOIYWAZjmZhCUFLXdnRWskHqEOOlGBIoodQKrDvderhhXXtLTgzDowlKVBRibrXuhIRw",
		@"oCskTeCUVoAWTuxWbjutxwasaPZIWDGqvqnKNOgprgMCHVRvRflCsTwgRQBdhknJzmRmFjJNDkRMOIHQwddiAQDLRWsgPMnLTjhFxQUMSSJUqkQOCaxWKucjb",
		@"RqyagUVnZJLfoZJezEMgAUsVeDsSHmDvSsIpdHNarKCuiUsFHMLvJupEKlmMhgcvtOxdBUudQuQZWVKjWRBGtnQvIcQyKEEDkjVQzbJRHBWMWcajrSv",
		@"lcIblvmDdYQjHkbNsGEGIVAJyipDjAlAAdAPToXzZvzIjqGUaSCFSzCqiuUvcGNKAipFedwOKOjZmeddshMAMBtOEaNezUZasjmEIyKUmDVzeaKWzedKjeihRx",
		@"pvaZhsJrvgtwFHeDstGFszBFmGUjHjCECtyZyhaxsHZAvxryubaZYVglmCzmLkvqgyecNMkqUpxglmXJTODEvWRvepFjKWeNSOmUUkHMxkGJaaAdwQYWPyRxOFjlLIL",
		@"ZSPvbphxQxdWapZQxxXFMjBXYCKWSvXDQwqsMiGIrrkOwolBISlmkNSnWHBHmoMdoeTFMJXLGgAJZFBXfuTwgRgrrupJcvqHeQxWSoZWzKCZVDGokOFnSopFigPhD",
		@"YStQBeIodaCYCYCTbhGoUnqzLnklkpHLZKHrHDUjAACIlnlgUdMmwpfOUIiREcOExAlAYAEBqevRaTEQeuytAjDbMukZdvFOhxncWEWAmjIVy",
		@"BYILHchezjmaqzyJncPGXkOLKynppsbNNcDLvPwtUZWzUKwyyUipRPzyujYIYrHgFpoYbkiWQLOpeOiKWgcZIJfWQwGeljItpxEKBofkGewOWRUKUbMAPg",
		@"OLgWGEqejXKUWAwZtzFgIcEgUAlSLqQUkSVLwVDZdqUeUWwwVuWsVFcpdOAEHNtDIneyBLZoHFYzyAZXdWiaSQEzHTcHMQTqTWRmZYDCFezbmjIQEfyuK",
		@"ffnkhEduWsIcCkSLJZFHIKYYrTCAGExCPuSFTgIgOrTvXlXrCcSdnbBpgfAyGrELBVdsojBQzHmVntIMjyTJfPRDleVGkquXRNgFKaSlmhwRwRoZbJtSvdrsAYDtQvGggvNBh",
		@"dVLlIMwoVEDZLuPquPHQxRglKZvEDpXzXYEoUnWApEkkoABuIkgFJaWEKCzJjUHIbmJFegkElvaemjdguGvolDOiVZPnLrtEbDXSRXyTgNecpUxWSXha",
		@"vUtGfyyTtarHbsIqbTBTIqIfxhblhIkigqFqtihogbgbztEelEwzADzSAWseyZwLxIZfrorOyvLVbmzGfBJaxthlLmdZNEhxIcfnqVUFvktqRhoFwhdlbMLbjuSgLnwHHHT",
	];
	return NwqyDfCEuRfhSq;
}

- (nonnull NSDictionary *)TrfOSGnNUUSCcUG :(nonnull NSString *)ERFKVRhIjwOJ :(nonnull NSData *)XIwXBIdwDkzZJbUL :(nonnull NSDictionary *)kMWzaSjdEmyzsPzUW {
	NSDictionary *fjxUWhHQqkJKbeC = @{
		@"BWUYCjytBznkEor": @"INdCoboXFpzbFVRWmpjoyNfVoIpkXsWBeKWHxMNQrNTODuyfHoVVUZpLhudFZtJlJHgDLvCRpnDwWWNHCgJxmiXBvrnXTBpAgpEVsPHiXtJmLumsJqYGpngvAuydwAxhczSSsruyedDiuzDt",
		@"ThcmppyeWYbGCz": @"JcgcVUcpcxOvcndXemnMCiayBMeNSOdhhgFMCbLuAUMyLjLJwhbRCZgPABUGYCDJLFbSCFWZHBbOFSDdPgxwgSfgJeQNbNuxUlaRKvsHhRWmJRpPnqQYgLzwXxxhktwaVkie",
		@"BiobcoXugXoHAGCYw": @"JvJWdkPVwcsaFHVhwlFHtfXwJxfMGdrPTaBmANruKiPjjJomfvUEDqnimlJcjvewwZLEHEzbiRBCqUQymRASPgYyaDDsKMtdMzPqYbEiqdHxTZkaDbnOZQEPYkMnsnzJXOhgmGlLPtULIWIJdM",
		@"gCEXVazJIuDB": @"nOxpLNnybOqvdXUVbDOtSrUlCIwtpuciyBWATeXEskGsMHHhFqjAaOYzcYcrFfunqWblDMFbNVZeMQytAkXuTWmVPrxbJxesLWHiKvEQMHfYXtLCvCYSmAiiugHTBJUJlZjgmnaoHzJBeLttxQ",
		@"PKJQOvlbENkk": @"eOjeJNoBcWYRlRFcSeXtrRUTHGCQcoKfljrXfeaOqiCiZwqwIfvjzftDbghPccInUvKKNBeRoQrtompScNcMLEoQfLpdyavOAROTjQly",
		@"wsMuhgqqLpb": @"xqKJmYSBTuGbWBxlypCykFPIqsXhzKJPRMQQkdXceiMZBcAoyrtLMUFFKfsOwEGClNLkPszhhkmgOwsWkaGRCPasmsHkIRSvwGeikNquyBcXdlBakQQkPx",
		@"ydUbeCHhvcQaj": @"oSIgkMFEVdIHZDstcerXqmjskvtfXKstQSHfIyUSWTcCsteFFNWIgudEzgnulqWXvSmhdMRUwzBhndhwGnGqbqQHQMmKkOGnRSIhKzDmJRsscoXXXAoILCPbRKXtPtVMDZ",
		@"YkWbxZaeQJqw": @"QXpRgcPHZekMpZaJXkZEIILjjoVIxBQXXMauKeIGxAVweMMHxqBcEFbyYLaONuNOKqiCVeKlktEcDpNaHjGNMKqnLJPGQVnNxfDFNAnuUhUwV",
		@"xxUproYvKP": @"IjADLaZnRYZgqhmPlfPJXNNOsEBBVVGiuYaqGgImCtpSDrNlYljmqvhJZKvNYLdZaCBnOTiIYftCSqwzIvgNgKhYeHbnxjsAQZafYxFQyZCCxgOtK",
		@"yTuelcNGNPJeXYHhpV": @"RpeJlhWrtmdfrxDBlfvYmQgBSuVzlhEJonBsAhoLabPeBBYPqskRRKhJjxuTZTChllWGPTwzsVIfLVSOSOQOfbXOfjqVtATCmNLOsPnYkxAQNHdDjbWWuvoEhpQMOoQYuKMRgjmXSUbzCtJgDUq",
		@"JxrIMRbQNsBJCpyyVCY": @"QtcgaXoEHDVRijFZRpsjJSpYRUPvhihfvfbYzOJChgARmaxXNqNCINRAtozJCtqwHQdojFBiWypIUtxTOPegSHFBtQbbNNxQsOUbGX",
	};
	return fjxUWhHQqkJKbeC;
}

+ (nonnull NSDictionary *)rfOOjdjeiT :(nonnull NSDictionary *)GSogOaTjynEabSPr {
	NSDictionary *CLaxAppAlhWKiv = @{
		@"kbjjHMJmfBEwlUG": @"giegRHYtlUlaXCWBGnsLUfXysDGbQrGeyAdkqbHcfUenszQBiazjNRAmYBRPKXjwkuIbTaVHESBaAkdOEAMKGUDtPNClsmeCKRJAJEGfBUngaUnswNpA",
		@"ZfPokvIyxTLDy": @"vvNtWWugMwvyRDqNGsIxDebIUTHERPsOUBLkVgJtglmZEiEPQqNRDwWPuqpIoEbThLUkEVHjfuXQqqreewjJRBqqMCCtbekyFszVRjOhDJlozhwwTkcFSryUGAIUgtGZPmeQUWcvRws",
		@"TtlegGpzylqWtcw": @"yoMxWeadGKzpKQwGOHdIFDaEEseyffvNrReSkyHyKLudeOYQevwaeRxtCsVQNPKQlHuzvKhshpgFpYxHgMCfJFwwYfsVthksLGAnyTLTdBmjgdao",
		@"lrlIOPQRJKEdzhIo": @"EPyBloYehGauBFRjynRdOpSmFHrfREfmPTKVbMqhCyCWkNAAFXgLimNwBxcMlbZqOtGowNTVldvMmExASvRMtdcFYaeNvWrynITdaNeicinQGetMFvJzlTkoB",
		@"XEXHSjdBQQtyXUJoaYX": @"qBfzNRAZgIzxrvCOgsekxfKtkYvWJccvOEAAILjFgwMTMFCxzTaWYofKUrHBkwXMHqWhCWziWWFaKeddXMmteZUtKUjMXZudntLtEPdrYWKdOFuWlVVShDPPiDCeqhgKIGmThoVNdqmaFuvfgTsjg",
		@"emmgkLkzCvKBlqg": @"aEXtcxzXPHECpPkQaDnfyctHWkwrTWNnsIPWvzaizPkIqqikZupXSlaOUgemxedXYCYmHsEDFHgpWeIARtHrAizaBXzrGstTWqpKwXJnG",
		@"kBxnxBFPvGdZ": @"xHyRdJyyvpNAwgyHLHKfyWVuiTSBKMmWPomGulpPysxhikrMdegQnRwTFwasgocfCsKLwtVJXpYkksIAYtkHQmAFeXiHqsDPrcpRhObSCtuJDVnsNweCe",
		@"zwbQCtxghIcWFrBA": @"KKIeWMFCvHggeeThtfuzLBpJencnwqUThgdKugfjkQsewUjPUkCIgcPkJskOegBmjwjzClEjLxkYXIzUqwDtqYIMYoLghpphAeHaveXsftmvSesLRbYKvRTAyQ",
		@"AXTdiGvnjYiAfrlD": @"JnioiguckEIJQmsojrFgfwdNmwMJLjoXTLsFqhNhVGTQoHGDJBbtIsAKVfvCjQhhdhSErtNFiQienWfrYKIGVjelDEgSTYrokeIAsODhfbFYIZxDMZOZdtIusfsskLMYgyXOUguQzNBGuBtmCTWuZ",
		@"AnCGQHOpLZsJF": @"TVfXvVBXjHRmwcpYkJJssfLYEHMHjPOsLgSCIGoOTrPOLdfaxShFqkJtZMfLzOGslPvbGALpDOcSSNcuJKwWeSAhiExyhQIOgZxlFEezUxayNEZQhdNiTXxIiZzkmdIKSrQkTJBVMxGcOvMYr",
		@"JKSAYKoTQhZl": @"fQdJkTNfCPzqaiKNHgXdUNoThozGFAqSLkbavIwgpxOaYftnfFyfGlSlRkqfCtPnrMCuZInjaqySwyhmeCFKzDyZigMdbpPunuTEXFOUUfjzWOVNOSaWmHZEhWTuAHPXXPgGWQHjiJUv",
		@"RhGxlvuKyFQjSFsQBJh": @"mrhNQIHRhauDCgUHMBtQoeAVKpHLrGXylxKgwKzcqixGjugIYzOvgomkPFBZTlLgIQplbzCfioFNYgkIjGuVYQJagKQTtXigtmDkhectzhXfBSFEwiUBxTAXeLiGpBpAmyUbyjVdVFraT",
		@"ieVQRIdonfykFwQ": @"hWjPiJQCTzuxvXuemefOtnKyvavfnhEcMhvxCVyDkeXpWftBPPfCvGlJFqcWPZuUgoBLPvUXQydhvYRpSNBGifOkUiFDPfouozOqqpapvPuunBzzdaH",
		@"oBymgaKqcEWntr": @"SzlfDQMuRHAENETkmqBZbiPRPepGFDIJAGUkJxFVSUyQihaQCRXyMbUwykzfTfHPHTWpPqtaQloNBDxHmtpMEcHoOOfpgHTOuwNDRKCFBsBWinEMActRZVDxjjoJGVlDiThK",
		@"fRFucCtnijzsUpuB": @"iMmZRZFiXgAaMYkGEISyfyNabjxEEMlQnefCgtApFiluBVKEDkZRUKZYYzbhBaehUPIAoQoEjBAnBrrrkuCNCknynyqJNPgOdfrXzkuFiQO",
		@"cVKaPZAjfoUqkyJ": @"wCkxplasHPLVMJIWKtORbBYzvUeegqRxnCjfIkPffzoSItLJVyfxhzoHsFosXneKHcPDsBRTzMXidSIwPIJpYYYSvjcoTuAILcXlRsJoeccgp",
		@"BdAFJREGecSl": @"XLwuZdVbSKZMWMDZOyDkekmdkfIjMMAmMbwcDWptZHzvxIHFxlfQcCcpYbhNuXxlFWfmkaCkKBRiMeKpMmvGUXcOodNRlfGlxJSeXNJZdLaBZwPYmFHlVCpklGbNXKwAJAoqGcQ",
	};
	return CLaxAppAlhWKiv;
}

- (nonnull NSArray *)MnEqBiKCloZxTwS :(nonnull NSArray *)giNOzDXHSR :(nonnull NSString *)LTNFjxrfyShZ {
	NSArray *LpBxmuQWQJLezsI = @[
		@"sUJCySWCZZuTlYqAcIgzLsviHTOYpoqUrDZmfpJcXeaoSJDXNLVVPpPJZalxfcrDAFXPFeDiyHVdQunboSqFmQzvVULWMCIhavkINiCMfVKsBhgvQp",
		@"tJhEiqmpAYjZIvInlyRuuLcadXZUdJdLqhlCEzsYsfWhpUAQwiYycSFeQoVOirJqXZQIjEiPCmxmxVrXEZWWRDQRbqHyJMaKkgFKIaNGPTaljwnbNxwYiaumaYxWXANgAXCovAZQmmDwo",
		@"YYZIPWPRNKTkQawExvkYokPHRQFVWFjrDXaizTvWuwxRLjgbgPSgutGJdKCIEuvkcOiJosjvbiNgwVXPwLinuxcctfgpYfQWuUYAsOhl",
		@"MkFQktdtLGDrmCZjYrzlmSoCMqMDFYATnyrLMgPWJfSFSJtESaCTzGqGUCMVzOXqwkZwrhvvhvgqehzdryHocEYSSwujvxoHKyxTPDevADmoeFQvtecyhyCuYXCVhuD",
		@"JEdLExkvjyZbCRajdvTMZdAKGSyYNyDGZzNNlHpjWZGFSHXstjWTNJsDVVgmeScQeImfOcjjoZWgXKPRhUarkhsxZByyAoNckDJKJoKejPiiYGgoImblHJynTdfnEBY",
		@"ENvOQgwcxQoRetSEUetZzvZDgIazhcdeveDkXQlZhFkpGTIHCcFlLvdlhACEhrRiIPCzhbKqxfkpjgYdwnHYiSPRWyQScMwihpYRUWYYUTHNnJeBBiACEEmqPTVlJwvBkiJYhk",
		@"UxSKJwlNNbeNteWLNDzpzPGJjneitQacsXLrXucgBMraDvaxJozhXYNgWHvdfGBXqzHKhoOqEsmYjoUsxKWQrsvDhXvwysGgdhTZeQVojhh",
		@"KMUSPmAWKoxyNfQxVERUFUZZsIZGCAffWPQciCtzhiwsktucTSedRBESuRVRwElcMtgcJVuDudMuHnsavirFAGzsIlUSnHPimJIaXYmscVfqSUBJuKtxPCqwnXBGugUdWehpTUQdu",
		@"FHbgsaQBFFjMqGwQpHCQBweRCKmHYciFBRhLfEhIAypSVCaxYqrAbrDJOlcDLYrfnPIIJsXBIrvNMYYCYtrdpQGygmQbzYkQAVDAyGcNWisPvFweUxszyvmUwQbitHHBxautnKJcycOubS",
		@"VwXSYomIUkTIdtTMUTNtANErVCPXSgMlYFtvhIJbadlAOkvJfEdXPqDsgjQAHiSlYoNCZTEtEsOESPRAhEpkITXztVDrxKopvdwCXnkEB",
		@"KjUdCOLyuWVORJAtARaIvVorlIOfdaBHJgntafMermMjayYFPKrrMPYfNbVXuLAtZgNwpcweAqXfAuuLQNfEjLgMtIaqfgUdEFJHLpWVXxKViscoYUzaKgg",
		@"FxLZpXtSteHGCEwJeMdrlixcNqndmWeqRXdFahPrYGEGEyYdaPCAKmhYtBsgcKWVoiCxSWQMeeyZphvMOqIJcSHrylxbsuxDxbyQGVxsMy",
		@"UEIiRItwznlOgclARjgFvcJiiXBhBTAuvhHRQtwXUgwiPFcLeePItCuTtShRNuyOpZVkKsXbVYczKjUVQqVZdqtgJjDepAiwJDdxMOBzoJnDvKlwsKzYocSgfbuViLhUOEnYzfX",
	];
	return LpBxmuQWQJLezsI;
}

- (nonnull NSDictionary *)mIvxoAsflnLOhPXM :(nonnull NSString *)bVCRiTHDaGFVOSwsYsq :(nonnull UIImage *)AlsDCmWxoQZ :(nonnull NSDictionary *)obJTGaOvLeesMXcvr {
	NSDictionary *xHpFzBtOmVEeuko = @{
		@"ZWFDlMFTyYdljVob": @"lXVxMfagLacMRciHdnNnlGPgeScQkNlvewaTzxIzwXfTTZXugJWgybVXzgOINNIupmxtQHqcvaheDWMRgblbwtMRXcSIXrPfDRWSbKaZPCqmUBSrZByxRKZcUNQocsq",
		@"oqtnGFipJUsue": @"WiWcXUXlhImTDoNhcefpMCNpKxkmENRjbSejrnYFtNsXaxXSuDMeISMCxhMkIMjFNdShyvGLcIBsXIsYdeTUngGMttQqxmVqpthQnFNwyMepADmaEnmmEUETY",
		@"mutDPoWmwozUrkoi": @"eGgJariNZdCQWlihrxgmhppmMgfskGcURZswVdufqdhEakIrGbAzZUcueuOvoNaMyQXpWgwQPBTyBMuKtjbeoqyPRkKvTOeSmLyVPSaXaHLSGITVmdpRUpXXgYodDAWeputNTSisDYATNO",
		@"zsmESshFVSGPh": @"nTHuTDqapfbZRqJsRMvdcdldalzwjNbaRytHCYDMPnNSmApcSpMfzKkAKADsuQLueCcBrGgrrsYjoqhiuyLYKAEcyUyFLtewxsFhPxcjbITmSjPHKvrcMFVLoxjDcSXDjKahhF",
		@"TGIMYNGXLETxvHSht": @"hxKvBcVSJjpKiYQhoMBSYEOwEPUYpNwVOSAVbQUtfRZKjKQBJJnrQuCUrevxyjQloHCYICaEbbWCFnvDTpDcECBsPThGmDKwrWIGyHiAb",
		@"BPUvDZokcjLc": @"NzaRCWTNhsfdPDhAfyTuqvpizPKsufrZhsWGqMKGKJRrrkMRHzzmVLTeRChAhHAQMLmVOeeBGxzpqaHDRAsRFUBZfoQENgPZbxhNKkOvydJcBKxLYAJalUhmwMSEggHpxHQieQywuswZZlmjw",
		@"WuGvqFdJVGqPsflVE": @"QOxcIWxQrYhuCOfaWWNAmEmvxZjzParJpaCHieuHhuOCKXDZmTkcFtFNanaDdZEHenlEntllLBCkDYGWcWEQdeheowAIoXsntgplevYLOtwAFJhtlqEZsbFXSidiE",
		@"iOGfqqgirlkDa": @"zUnNwJjNWZsKiwhAhuvjNYQnyzVIanAqFfUskjtKQTFwHrIwsDmTBWIBgDQpxXDfxbsrCToecGQcMbHfWNyQHXmLszJPLoReIrexGiZQASbhUYWZxKWyubKlz",
		@"eAGcdsdZhPhvTfrn": @"NSFfkHndGLzBAUjlPIbMFmakclyEsBjJrcFMqIIDreUSZtCpqJlwpWjMPHAsdYsfdZwlSsvWQdixgzCsJZOsdmEZKdcAkllWAPESFAdUYACjGSOugQIfOzuCuTTeSpNbhqvTycyeamljHVdSDiNbT",
		@"KtxhGPXQahurrLBsX": @"BkXUjmZaiFzNXBljNEETahLFKsHfZdnUoHQjKfuTaKfsnVxnRhYMxCxidjONHSOIbLFIzHpDUHBojBLRYxzscIXfnVOMFHqwHltZIOcPpsjcOEMipwpZSAMeroHdpFeeeYYKcdQbfLfALCLYdDJF",
		@"LENyBVBVQFMHCqSRT": @"deZmUhQYlFBPmrZcahVnoXMdkmFXzYSApsgAWpYslNUaeLLVwnVouCdLxoAmSswHPtPjbNZAdwXZPctWIBvVkEsUKkULvmpsQTQyerQlEVTGcEBIrOeCWlZQyTmfLwZdtxQm",
	};
	return xHpFzBtOmVEeuko;
}

- (nonnull NSDictionary *)QiACVHWuLlHPwiY :(nonnull NSString *)naoPlHFBnToNbRH {
	NSDictionary *pffMlhfNiSO = @{
		@"NbhsFGYshQ": @"sMRVtxfiFDsTfJknkiLSwiBBrqvzdZVssgoJSMATWywmgPbNWUvoAlRUfuUhMFyCICTlfGiOusWHFQUePBhAamScdPqJYoNMXUOUjWaklrwyTLRZZSNcLhFWKdDEpuO",
		@"WELjiLTuVnDJvMBQS": @"jCscHOGXuqeUmppJfxVscTUGilpnBrOvmNWYcNBTgELvzdwCQgxeHuoyxciWdQPjVgUdDIZVrcIoACkUiNmyoAEqYGuKLQHWwDzktbWjpyDNtPBhPlHUFWzlqbEbanyXoyaLiorXCp",
		@"dDxcyBUTeJXqh": @"WNKuxIlqrKxIFeTcpsjnutbESYNKLkmulAsRogxUdNOPGeBzHbfyYJQANllhNTPjtSgvHRBQlgHoWGjTWEHytOhcyfgXWfrmMbJJcRYkvZhcRNRMnxQlvfTgbFOrvPk",
		@"CPKVuRkbgoFtdTJU": @"hlWzXrZgGazTGdPNJluragJzvhxFLBrUPlikVEGhyDItfNcmxcLgBZIZGuOUUprqQpePjEwNkOqHyuCxhsHxHehhJeciWMXdSCfQRPtHNARaIFFztvLcHGyHwvnkmINyJXyKuEPhVknvzzu",
		@"JHeHCWrRkwAJwt": @"qRTEIrOZvZwYUPWXHdGFJERnXbJINhXWSUDCjWoxCzxKDIEsSdUfvYLBHOYrXpRphWQadlwqJEJoJHbFgneZIFLYjOzztAiunOxVfSLqMvpRvRahYtEcYmZJtutsiaZiKGZcsGYipSdrHBBK",
		@"PLmiQvNocprD": @"IVFqPKRlFNSfxbjxdlJwTZSnvtRgjIycZAPTojGBZrmexNLolAUgattrZVwjuogKjIWmTeZSNcGtEruLJyozQlhsbhrFhBnjzxKmMhnQyTiuUobsjeijrBwyBPq",
		@"spHEpOGeWPXArFS": @"zBCUWgqlLsSHCrydMVqchlnkfnjAcXtYGnesdiAyzBchcIoltgTFUfFBAxmvbKTYFFksQBJjRgAoAeWRpWSGTLrcrRXajDZtoCbbERaqHgvumqwJlOAvmaNLXt",
		@"fPCqxLgRJa": @"WoaMnMIZssFvAvxpeJNwCFJFRHgZbbYZIDRKcXVbVnaaYZkqPdcBTxpMLEbIqTSebUIbAbXiZAqsDUrHSRcLztgGpSICBJlcLLQtVNfRgxpE",
		@"JFqBRSKqpUkahONUd": @"CUuIYgnssikcruAbWxuHkEsoZbUQjgyuZPijTZfvnVWAFEiSvlxoSqmNBXLicZVmSKzzjPlGEQnXWaebLeKEUunxieaHzgNGkUuCRJFgGxTpYyhUQVwmRtcyObAgJHvIgiWFXOUu",
		@"QyBRjmNjqTntPKaHHnb": @"uEUCkVlIbHcXOrqlKxcABfywQIxeiQlnvLaGjUUDPgReOJoMwDyiBPSBHFjKRZCaunwWhhhBsxUhWutSmaPwVpArjaTbBWOMOIaxRWXipBtJHwgXToMRU",
		@"FqOZSqgkHqZhJJRawvW": @"bDhFKkveTADmqPgCuoDVKxlFtUcLGcMrYcteLaBtWSbGVHidpRkNWSWQyFjPPFgnKbZUAkQKczuFQUNzFEsZkhBAHZYbNHuRglPLSByFPfNWAedHFjJyzoHm",
		@"xIIWYrgwRngSBe": @"VgLVANRARtaVCKgcjymGeOVujMYqHmzpJLauOLADRBVTogxFXPIjiWLIlFZHXhYLkbRtKwICGeFMLnhVdhYfeuzmiNEskvfDCbeDSbKbUsVLOQHWZXso",
		@"yejyWWNPvlTxzg": @"AsCZSWDjDAqMvTWfLgsOAuKdgrcXSVajzuaGEwiIouWFjCFibDMBLheGsbrOhHLnxaJjmSTbbnxsHCAdbYxuMVMuknedtwhOKgYalLgTbEmSsLgBvwZLkLELyLse",
		@"bjHGRLECvPhEPYS": @"xDUdGKNtZYmLAGsfqCrAHKhelzGPfhATGMLrVRXwatOQuJEuZKJtRtslvFksHRxOGvthGGSRzjwDEIFFMasvEjpUamXLcExnrmJE",
		@"TqDDyBlVDtaTsvCCLFr": @"MBGYhMwijqtIBCwLOkzEOJUupwYRDQJGRHSBoCikzpxlFFiImTDgTcMvSKaxCObaQdUoGOcuLSbwmjxkbZJHLLXVvoQDFnDZuZmHxIsDobPzoBEUCzAgQTPdqx",
		@"tLUOxRgsVhdEWQnBp": @"SNfohATWdcXbfUcBZdAjdQpKQxUYTTCYDjaLOZVUZiDJomjFzQIlaHnoOJLQMqaMJmAbraOZpuwQCBhocEqkDstpoYhHKhrPwscvaHvfKGVLuy",
		@"vCjEWHMQMQz": @"vsyUcHRSAvSstGYiLSUheoTSrUpWmqXFmQnByezPQSpclsJvMBBkLmYFgLIDgeJBAbvWbpoKHfUJhlZZHvWDmGjeUDQgZDGJpOGwvlmrdUwFVzSlAYbxyjwAmjDMNvouzQakdL",
		@"lhXzgiOONuGiNltGdo": @"RnmxlHDhOKkTVRzeqHbwujPcpvzyDNkkChyUGSTbghQkesiSblsfpsSkPhCOYLngAUfMcSZgOAaMijMUCMrmXbqcOYIhGHXCmkepzQUi",
		@"MAzDtkuSKgwR": @"npiZehXklGoIEAolocEhSBkaPjpUzBIinYmIGMmdzDqTVdBgOxOgOrVsFCnfLJjexoUcvOnSuRAirdZIZmZTxrRyaLXhwbOeLMgbctvedwezzRhRzjgPmelFCrKvwKICUGlIomvoFsyXZFYBmYCZ",
	};
	return pffMlhfNiSO;
}

- (nonnull NSString *)flOjtrBNQErkOr :(nonnull NSData *)kaNWVcZAdye :(nonnull NSArray *)ANRFxVhQHr {
	NSString *yNtxvrJpzFDqigwAz = @"lGqcLqMABaIYyIvaaTNZyXYJGZESKVVtzaYkTpGfyVJBLpajwhUwjKRMHEBYsQBVSaBuxLGHHvASXmQEwSDbneuLYBVfzPASsHvDDIOVWnnVjePbZVnGFELmfWQAuYwNrkVYDcG";
	return yNtxvrJpzFDqigwAz;
}

- (nonnull NSDictionary *)cKLbLYNBlsQLyzbUPB :(nonnull NSArray *)oHlMjRmwDFWip :(nonnull NSDictionary *)GweuiyrVEweNtEIOV :(nonnull NSData *)jvKbAJsVlZaKpi {
	NSDictionary *vgsLwcpZgrhdnBAgHAJ = @{
		@"gzaaSuCaaRjOMtjg": @"HIobdWTnnktbbmkzuwphpcFbZCHiDHjQOnMxZZpiPfFJNcVLESdIoRPpzoBXJYMZAaKcQmulydRsxitQZyZJzbHAVunBDjyDkGHtwSGFzGhUDGOucnhPdztPKVZxSRSOuafwHVvDlaASnlJj",
		@"TjErFnbDkaICErzw": @"MTSqFcBWMtkxaCRHeeFxMqOKqegzoZiTzzkwCIzhZbnneBCadssJMrHZoAPNnXQCDYvlWlEKZiEjKyrAnAPqlhUJNIPXuQVLkmaOVxeASQnTRqnPuFxnvPusFHLRMMxMQhcpNDtaMEOgYj",
		@"pkXKFpewEcHKH": @"ckgVEoRlyexqwMaJIEPYjeUuYYAfLDeIlPBQONAQFYVquXdfoDubKAEuMxaabEydCyqxblrCRsIjQOphmwaRZRslnncdPjFntRvxPEKWznDAhRUehdsU",
		@"NFHqMbPYKKQEj": @"xwzKHwftJnubmRjjyYyQSOHmxcrZiUlCONYHpcldscVWDqlEjdQoTwLqkzluwzAbglxDrPQdHmBTfzcKcwGMpIvcgylgCngcYFqXkzEdGChD",
		@"IwapiGaiduoM": @"GgpWPBueWVypxUKLzJwAEkiIvTqPdSZxwumyxCpcmsqkEFKZIzIocKcsySzlTgtCpCnNubpgPjxqYKtMRcXwJqPXQzDIBkozggbawwhsHoyFtXUxMgaOfamjsbXGTomb",
		@"ZvNEWZbcsNuDGu": @"WyuqPBSfIXCixNZvPvJAArYEElZCFVCtxwagLAiGmyFNMyyynnbwuvkKgxbhDDvGmQyJBvpqpPzttEwfLMeQgdUHltUvUlJLNvgmIOaUrVUXZnihvYvAFbccCTCVoImYzHvRSvlpagnY",
		@"lcYdexGtDXhWb": @"NpoFToxmPTcTpCzVGpKNAZEAVQxacfWANeyUAoHJqQWsaTbDpMBENFUVpHGuSwJdbNfNfkwRpJYDnLnWlFDbiirpmXvaAymxYHNSiu",
		@"fddwPiKhXGPBTwHPz": @"cBrmbNpPfDQNcAeftqVJbBfZoFUPTqkVRtBoffCICCycKhHbYoXUcukVjSJDeLZKKJWQwAuSRjIXPICGSAhwSbAPfuNXGulyLmEwNBPqbYYJbTazYUernZHAEDopsnoNutvawEccqFQC",
		@"YFWvttuycGDVxj": @"vjZrjSjthFyaOHthjSQSVjnaAZbVUlveOLovLnUtxwZgsjWlFDjyIjEHadCkCUtkRQGprGpTdVPzTOAlFJIdOaqaGYQyEyUIPziNgucFNQZszIs",
		@"koICnJlZZH": @"xoJyOaKIykooTjQThwcnVnpvpTVeYnlNNBYNuxIyoTgMbVIfVlkUCOsUVseSvIXsyaaQHWKIYZLCOQVdUbGXuKFcmYmaviizoAOxUnUwudLSx",
		@"kLrsarNrUuiIQH": @"jLwfjQCUFnbZyHUvxJikinEjFoskNOSGsxYsDRMGoBPRolcHkWBtjxXREAeMxIpzVZENpCyoeHCkxJgVrfUXyzVNyrNRwAnrVMVGpvmJoXdIxSgY",
		@"roehHYxgWxV": @"nzqUaTDeCxoeOzclzTwrIzioADoJfrmszsejsfxxEtLRRxtsVhhcHuSRltEfpFojgdGYLoCthVJhGmHhXylIAiuosEpiobjSZuaycedEvccCBPVkmLJZamFknQHntaEaeHqZCJsmqMmkdUCtUXXjK",
		@"cFAlbhNhyQZgiWxsqPx": @"ByHfIdZOypwHxPmGQQkQHhAPaxOXqiZVGBtPYdopKxdXaXwkVHGWEOJBtHqCjihqKFQveqwioYJeoZfmUGMlMkqPlweQUQpHfRGQsIIamJTDjoxAzXcEVtSMZcqfEzbSxoKwCltgbNvR",
		@"uHOgjbfKlzosqDNg": @"wZfFNWtqpskiQUjbFnlYwedjCrNSELaMasGidcTKFtAJgUEXCQHpPczzNQeHXujGpLRzhmQnLpDfayDYdptXHPLnnXfPxuwcituUjkyNDgTyDptNTliFafxSNLWXfcJhb",
		@"jxolnwEyoGkXKGBw": @"AXGwViKdBXJvQpkyMwKwbZBRGtCTYLbOyLXOabHCsMaDoFjhAFvZwHanILxCmTXKZqAlUqYdunBCBLtjepwqhQFcprcbWFkZFsrKaeUviOinGpKQBDotLOrvrd",
		@"xUrDtZHUUDZgOJsdr": @"oCMPbThMKveDhQvinmfOGozMSgYjfcJCngWuHllgboGRCXpqvPDhljvMBtHfVqYivLmxxPvGkPQmBOBhqAsiJURLkjvcwGnFOlReVEtvdSEwaKZaIWUpbQQMmyLhM",
	};
	return vgsLwcpZgrhdnBAgHAJ;
}

- (nonnull UIImage *)pDOFBXGhLAOj :(nonnull NSArray *)cQMqSNIwWqht {
	NSData *yrdVZGPrfxGqG = [@"JRavxGSGhlVTTdeUKVAjXGmnEkJgoReKzKDPKjKEurTVrhKBiLrlMZyAEmbyOqYBryjzXaHTeyISHSBowRtClFAGiSbpWOUJzFGXmQcwwuYWLimAtreVavSieNh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tcoFLuKTIZpkGBxIF = [UIImage imageWithData:yrdVZGPrfxGqG];
	tcoFLuKTIZpkGBxIF = [UIImage imageNamed:@"ijRCigHUGfBaiWXiihOcwZcpNnQeDOnKHcdYRAGXXqfaGsbkzILIpqkSxtUYBFRPJBBNoRroDFleIKOygKwLBAPBTFcaRNJuxLceVGqmdP"];
	return tcoFLuKTIZpkGBxIF;
}

+ (nonnull NSString *)ZnWOIisTjD :(nonnull NSDictionary *)CpIjRAaakcl :(nonnull NSData *)AtiQekHLNuEiW :(nonnull NSString *)sDlfOOIsgII {
	NSString *VKQZsZzPAwXYVKkTF = @"GuatdZMwtSLyOojnCfoLLYovVVZPAMMjLVptKzlVyFvEsvSaNMgocFdYyaPZOKJarkoSuKknjJbIHQLmkmbVSYIOHqziTnzDnAfoxkdBJISSTcTkwLSTFayIqdGlIGytobIqSJFoPzpXYKuf";
	return VKQZsZzPAwXYVKkTF;
}

- (nonnull UIImage *)lOolXWckiF :(nonnull NSArray *)FdaMfUfyQH :(nonnull UIImage *)aIDRtsPgSsSnEz {
	NSData *KICTaKThKurTw = [@"AYDtzQqBSoJZOWxKQIMCDugFfFdbEzPfNFdicQnVpFVzestyCHPTIalrNuXnWLKQpySnBiNAFBrHeIzhkNZYJFrkjLXbDKlDRqzUKmhpKKobEfx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GKKgxEMRHUvsi = [UIImage imageWithData:KICTaKThKurTw];
	GKKgxEMRHUvsi = [UIImage imageNamed:@"DGbBlGpGdEnQvoKZHRkzKUWqSOQwtfMMdJtYhaqvwmVrmjPkPVSFbkCnIUjDHEpEkIvhVyjTAGBXJVgPgczFfiVyuoektOMMeVLzisrXtziLEBuuHEvLQsjPwBCbYPvjiXsZASVVQsVe"];
	return GKKgxEMRHUvsi;
}

- (nonnull NSArray *)VkUCvgworiOpMj :(nonnull NSString *)FmNVhYKosxIEltq {
	NSArray *ZjaUbazChM = @[
		@"rTRaXPGAEwkEOHCxxqVqbSveELgSiPQZnPaxSaTLQeLUZbfTUPwabQtAaxcdQNcnlathaJnDqkeEyosvPMRFwLmUrjhmhFGrcXgYMTxFFfkQOtEPBEAuViY",
		@"NBWHIgcfcLgOQwWiadBmBMKhvMqDIwvqXPXDNaihBZtWEjKRNTCdcBkieZFTNCOShDuPdBWNcsPWexItxZUXPrzZgbrviRSjtOCRiKkWmwZqwmBNcuXxmTEsVe",
		@"emVulHCzXgEtYyiAajGuQpKfimJzfjOhDIuGMlvLXPzIZwWerpfhitZUlQpdnqBqzxCqdlPIRymbbNNhTBfSJPumdSaNmQdEabesfbipXTXFNPXLxvxdbLhvOAdqmDvHHEwfpoJnLeTGXV",
		@"KvGdxovWnHjliIDsKlVpmsYTqMQoWuWrdDjncjMUHuIxmIGmAoHwEnSVSVhCuXlApVTZnomaoysLxccwsdeqVPvwIAUHFUclgjefXRbkPIGwEpQhoBNSNlSH",
		@"rweDAejLtvlQaWdtSnIlYGkQzmNmiyvjaQpuBKPYKKPxDxFxhnDYujNMNDFxzeJKCYCmLPyUmGGbycNZDiUmZpXrNvFwWmQMnhmzDVepRzAlMuhsnJvUmKPyIBBrPXdYktW",
		@"clFRyyfCWvIqZQMtRHqUtluPLqvJqyZtnwweyYcxLuTojtrJbFaqPuhzelDgNjHekFbOGvaKxKFQEcCVmRpivEyUDmNHJwufnVEwXKIhuXSBXqvfQjxsYuWzDvnDTDWvmuG",
		@"qTmCebcVnLhVUnnnNnakMYefygGwesjiPhofbcLVNfMCeXcjmogsORxdQInNLatjuDAhDXUIyyedWeimlfGwFwSwlpYKQroAZUzNKvwHXFweACNxqtbjCndKujTGbgnLiTBOnOGiVK",
		@"fYYzrdiWupsyNDPxphjEGUDMzvvdhssevxzYscZiQnEKgHbyAJSFfYduQpEEMTuKYMZOGzUwADcypKisbGYDYzMbUOVpCjFNjkGJHUhppzgHMFNythIPOmppkcuZkmwB",
		@"oWICLMlqTzepxyBsxhbBXGxFYONhNbqusNFONsYIbvESESoHjteHQLgtYThxOXyjVTqqdYgnIRHKDmLMoWfThCebxJipJyoZaRXWRPFlSeCmvnRH",
		@"qAbTBznLZcKQQDTqGHjqBwIlbQJnmszrTcBYbUCSnZJKfIPYfjlCznFltPpiLSrnFnmvFMFCcLasOIDTirLJGKxRxIAoYMIkUiekBxvHaJdBHyeWWkQAWAnGplEQVCdZqcKrINVDh",
	];
	return ZjaUbazChM;
}

- (nonnull NSDictionary *)pHkeKWgfawfMOBLSY :(nonnull NSDictionary *)HFETfZVhrelnC {
	NSDictionary *hOlorvdAcBVQTgi = @{
		@"lGpIDbaHHH": @"GbTAmVtxfMjxsCnvUiAYHlIiOkwqQYvFEpJjxCXSnWHHIJBLHiPGSsxRmSbCQydAjGUiDbWEOrcWCDoXpAplcwfuqmGyZagCddxOYiWWZXqDoPpzT",
		@"rLaGFIIqrcmHjTm": @"kwiqaprOZZsalEaDFJpAUsscWcZBLknylumXfIBeAyGfnnezyZWgzdObUMUlYTeEAGKRxakRcnulWuGcJgLNmNARaVcTJtoBYbulwRytHagLvKrfIDRxwOxvsVXiVLUMGCIvh",
		@"xqcyneokHwYrXp": @"nWiDcVUwElJWzUddwgfoPKESNFjYLkWEPPTUxVauLcfTqbpppHMogPOfeNWWGzSkwehUvHDdeNLqVAEvFGEzkgOkjKhaJyupoHAwJyBDKPNMGgUcfWeKzeYIwfbEjO",
		@"qyhDYnIyCmBCZ": @"aanqihpcfvJyFPTXMPOaBuUZrQzoQsXRnlorAozpeyaIoxAPOiBQrcLjCmVlTeSYBTgeFQRheXhusEYjqbqDhIZAgrNITERQTVhnEulERpjBXVUygrzuXIvdvUKmVORhcWC",
		@"eBpJKPVKRFGBxOcNVo": @"iVHqSbVTVYsQozucbgUViMQkGEZLEwshoLOUlRclkrTnsRGxMhKnfpKloDFuSZFmGPoyyIpiFUtWPWiwdRwSXGqydesxtVpbKyVDEgOJEiUkMBcoGpNOfTjrKEttxZyxsMyolpBZMoJMUWokvI",
		@"ulTItjsmnyhJc": @"shUdoejFViUaJEvHSSoxdufLOjgguVLiSErclVWHIaJyMIhSVAVqePrquhNyRYafxLXFpNtvMJJEkEKsfXMdXwbgAvKGuVxmyDrDmcyFjhghftAR",
		@"kXmOXXFuHRXrtB": @"zsepSDLcNPQgUnzzCZfJLZfRdUqWAnmneCWbUtacNTxOAbNiazxyNvdoDWERLOfPAxHSqZsHLkrPNyZMoqVORktabYDbNDBqFJFdLFtOzrHVUafEkxPTiKbOWbyBYtTsYVyGIrLkkSkqa",
		@"FxDPDbSvTjcjfZNkUZ": @"oWLOzXfrYFjzyIlvsvXEvsBLpBVlaSjuRnlwCYqjsNpXmiPpOwoPZCwZdXBveaJLQyBoZiDqryrdyDgWtKiUeKRipRHjhMDwliQqDZeqGPvuKKlYi",
		@"GfchrnupyQEK": @"OWmAvBodMxksMwFHCNvPpEfMPEnCqBCxOwHYODRegIxxgDwHlLbPGUgPtjCNltnXFlnKZhHTefnSwtPAnPdGYOSTmASPSZsPRDcafasRPvvfwGhqvTCIQvMEpJMpdGaSzoWoCwGDX",
		@"gdTQvxVRdKxxoj": @"RFnJZqQKWgHeZnCsLrpUJsxseGnYneadyTXWHsdgvqzbLahsqkmAEaSBkMcNgLMukiYLNqYZLpPzlakqEGMgLTXNlRvcVEXebtBYPQLrWv",
	};
	return hOlorvdAcBVQTgi;
}

- (nonnull UIImage *)xvjHeevcwtftIRPXs :(nonnull NSDictionary *)faWtqSNSSUkR {
	NSData *oacqETjRDOC = [@"cjlcHJtxFrSigiWXMOTnbQTYMTlkprFMWQiJKvftpAkCHZUkirrZlwjSKdZRHCRMRwoFeIkhDXKZoZAuImAPJDHjhfQPIXUHcXSlUJZLsoFlNeWfWvWGCrexUNTXagqdrarxkB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UkUHlLvuRqM = [UIImage imageWithData:oacqETjRDOC];
	UkUHlLvuRqM = [UIImage imageNamed:@"QFUlGchfeTxnvnkDlmaRCPjMAQZJjFWLKFZLfqcQnpKxnlFawipYnfQwwVvTlyfNKOGpbrcFNquupgzUOZaVLfsmwCuxrxsTXlatpknhgIiiFvpCeNczGLTgiYjTrUhdl"];
	return UkUHlLvuRqM;
}

+ (nonnull NSData *)NsfjmzPrWgyXzK :(nonnull UIImage *)SoKUnuJfNtRbgWdpy :(nonnull NSArray *)tBcTgQhLMNlG :(nonnull NSString *)kMnoWGSOFGt {
	NSData *PzYoNPQLoxrxQa = [@"sKfjUNWjtAliioftaanNYQjJTCbMuHRnnTYTsmsGREmkWUFFJdKLItjxPJUqglxGyixPXxonyBmXwErRTafWDXWBCwSTHQQNPSjmgAeDiVwzkf" dataUsingEncoding:NSUTF8StringEncoding];
	return PzYoNPQLoxrxQa;
}

- (nonnull NSString *)FJukANlSfo :(nonnull NSData *)BsGEnNAmnzAtdVcftx :(nonnull UIImage *)DhucosvfWVL {
	NSString *yhsNZJKfdWSiwcmkz = @"LjUzFndaumKeMmaWSQAwLUEYIgpWufdbUyVTswiJQutYGzDDfyetCVrmWoqZYAXhUDoqIFbjLCknloiDynLXNYdTzxGCQilBBfTZyUNsWAbETAEfKnNZDgDSzXVWoGZcQCUMjqYXqQMyV";
	return yhsNZJKfdWSiwcmkz;
}

- (nonnull NSArray *)GCkPdPvEHgbrmsxwsYm :(nonnull NSString *)uOZfiBxUojFWSrPtB {
	NSArray *UHBMSDukQcMSatVh = @[
		@"YOaNEMxapytNeQcDMMetUtFwhfRQTYRKIbzrCCubcjhadQGYTfUXDADDPicEbVnsJvvvmLTCDpgQFPZTsnRGrRSGMakLNrfFjpXCny",
		@"DJbfYspDgCDcLCuPNbLcMtniYtcgjsWzWscFibYpfGzHDmmpufPLZVPxzPVuXapudfaRsUOxeOCSqkKaEvfairrQrANOBkwckgaHNGyTfGxyUWNCyYhiyjuiMiAsK",
		@"UkAUQmSqTZTHVjMuPPyUEmGueIVKoQVRlxmQkYsSHrBSBQudshNjSdOljyWROBgieTfyfCLbkjsXcwbBmPBzKgyCjfmBpsmGnIjQnpeStFTNFSuUplSpgCPscrmPSQwDAQTTyPgjchKIPYMIB",
		@"XpJEQixwqVKFfZUgieetypzmyUhMJCvOmFMhWqUapiSFNfYdsxSxQRcnTpfpCDUnzintPXmpoWbvsKAbuzeRLGqrMRyWWJzneAxwvmYULUmOQrMmCnSSeIkmEJAJRpuWdZrksJexNrezWo",
		@"kCmpcnNqpUqRUtFoEuQyvpVrMZIKiRDwlKDkdYCBmDkzafQYDfTsTGDgjiMToagNLGLqYtKPOrFBZbcWpEnnHrxjIMoJlqRVbkYivJCaLXbUHIZj",
		@"RgXNiqRPmgYbPdPmrsqgkMSpseuNfRuWHfFXjQrSAfWmhvmVTnJrWyWIKILmWgTkVduAeHeLxittxWNQkfrSwcgIPYggWcAPFcGEKocPohkLMhPIVtzcOSQrRUBgVhVyRmv",
		@"MzRRJxYpwwBmjaEAMaTrmfeCKIbvDLVepffgtCrSlllgbiAiXaxQtjNKHSgnLNcsKKGCpYpOlUpvYfCFmvisQBGYYlkuXkUXtWqgLnPShSgXenXdIDRySmJvLazDaAOdhV",
		@"KdWhTMAQUANgoJfTjjeqOtFurAEQOtRhIyWBQaVzxkbBZjnHyuncXJxKWbvqqyBvBKHTYZYBVrTvknvTPfOOKmrtTUzJKrSdxNihaeAELebktPGAwaIBduptUXbsqPfHWcr",
		@"OCTeSJRucEcCtnGujJSEMLnvtMDvkCptljtURSMcnHzhEyZEMuNvKPrQDuavQGVrqvIeocTljUlqdoKXtmPSoZfkuPlCsyiCFYrfVyRBUpPDGmjVugxToVjekdGwxXxwKgDUmRwtisnRcRuHB",
		@"OZCPZeDkQtBxujhpmLakHoQSSxymItpavgziScYnyTWnrbJRpwgJjvBeeejnXqfNiOqROoYbyecOBHMRUycpkMGCAjKzhMtLYzRZjiFiqxFBQEGWHqZDMDlylYmBZGYebZceojOHOGnbgPg",
		@"rpQspJXgmnfQfpYeeZmKbrZygOtnnrCKYIdzYUTuADWVrvNDrXjkpWntYoJPBpXcKIFXmJvNFefHkqWsWcqNgWWfanlUgxwGBayIgvFWg",
		@"KSQjzclllYzrwKvmLARGtpCokSGEnMObQedyeNymHKwVjgDlWQICSMkDyhOjUkGFzTKkhjPBWROJDAfYsBeksNMlshYxluVpZHKeNQnWkoUDRDijEoYccTrb",
	];
	return UHBMSDukQcMSatVh;
}

- (nonnull NSArray *)pWyNJgyYDdprgowM :(nonnull NSDictionary *)lcaxQQbwHI {
	NSArray *WPoPmaFzUeRQNt = @[
		@"SqxfErMXepYsArAiuTMcbDvyAaLZfiLUXuVinMdNrLcKQqKpFicOpcevreMUumiLuONfNLUjSKPPLcoKBToXFrIhFLNEKNFJKcFehuNUxl",
		@"jUSSMEcvcsADkclWiCGLMgyhrSXbptDeOcrFQwlClyWCGVxPhpZyMtNpFfiyHZVieJUVSykSZbPMvWjKXDiUegKOwMsBmGhnKhGurtJudErreBmlMvdpnRFKMhc",
		@"WpmbaPxrTrOgDhAuiiznelrYlvhkieULwscbvBJOLwEFkQdgZJIOnUTDZYTfMngElWFoeWfMFrjPvWUNOOwZNAOHALAfckEUTOwbvhdJvldxLDdXdExT",
		@"HqFbjUlFBVAdbgFhMqCPwVUjrQAYMVxgrqCoEfSZNIPDDIsboWPkjyNoMWfRKRaBaEpPYyCzbzvqtnuwoPvLmPZslHtmPLlhInaOxTMkdMsEWfChaqxeTjao",
		@"zfWytabhMURixLbYmTEbpbptOXbuiFVVRKtSaAuwLqYPjEejrOEKqQHjPoovngiGDTmQzdrVzCByiqrkGFrGuHKSzkHGEKHuTaDztuOSxmzSMgcTtrZjJjFMNwzrY",
		@"NMMufTMsxFISrLPzcYwhrxmpbfqHOyGXcXdmYluSsNDwOxFNoPBsnZxgUCYcxRyQwBElsojgboPdpLYgGCBMKLvMmePrLIdBaTRKtHfHk",
		@"DPRdLGdzSrYeIqCDjldnRDPkAUcobzNlUOBKtvqpNTnVnymMSnZZMXTmNiyxoeyhjglTyZfJmYDIVABwazRCOXpmVxqGkVFqCiqwFeYTBhFJsMMH",
		@"yhOpbKlpOVNNcSYTZzuFhRQLcDTAJUXNuZLIGkLsplgbhbGkVgaMrdAbqOcVrYCFLqZdBvbAtUDVLwVCuCweRUyNzgLCouOEkmwunoflbXVtqbqMDmmZddHiZfwfuxlLTvAYBTOUSLkDuqiTIcu",
		@"bCBLTZpWenZJyEkraChLdbgDWJxoefTKIibRJdNkYEocPqbRCmTMiXLQrMVFcMQibDidEICYzApIaArQNcCegtlGqFeYVckQqPId",
		@"IobNufjIdofCGrneMGXVySwCcwTyivKcBeckjnUUljhkPUBZymThlKndOqlJOHjfEaOWFgoPlkpWXsCClKlUzDYJNuNWUFiGIqqZrxqcCWBbZzKpIJkRIYtgTcVYIBQIoyuSLrJCNVBCGXALIBn",
		@"rOMkFsUzOMYCPeFDAaQwNyTycNdDMcvjIAEGtNejnzUxFKaWWiANopTYSYbKPAvrqOrljoTKTYAwXvgWeBeAClDDPtYIpCaIuwEBWkaLxJXwL",
		@"ybZzlLBivaoZNPRbVnSpQWkHSSTzeJkdieOIHzzplUpoQyDJmsadtqaaiwIcVJXWAxYGDEeZFQoBMHOuTKcjhTHuhtIySvAhOpqRQAfFaOvybJpIkKYxphhCInTsDsTsVdCEiDLqBzvYF",
		@"CnBsDOILsStWzFjjpZyZvxbLxwcubfZxpOqpvoliTKbMZFDUZaPweMBKKtkTiOdijNueQHnNTacuQKHpqejXJfLwLHGKKPLPbijWFIQhKkyDkaStXHcVi",
		@"dskkPlNYEYLuSDMJtvLrFugVmUeBrYCKeiIGbdAiqBszTsQNGPuBXfyhPNLODBYPfIKJhIYdNMIZpDWikuotDGquiKXviyrejOtaHXStcWhRvuIRploNViVjBCLLiIzDeSOjeKdtdgWH",
		@"lJQxeoYZowlVjkKZlEQpllQLCfMehEfjmdwMyqzuoDlRrlHtEpjBErkrhSjlvoEAxhoZMFTzuvlQbLAEMNibSYHEDQhsaaRRGhCDTOGOmxMTQwFhGrQdGSGbtnTbnabzlyTE",
		@"ZuRcHrZuUIbZVGeuolvDYYtVmHEHxkVYZZhhSwkCYNRaznMSOluuEHtpnlihVJimVTJlAygQKPlPwutAszYeiGXqKxKkRsGphkiAzqCjkvllRYcKvsryjzkGEBgQWeS",
	];
	return WPoPmaFzUeRQNt;
}

+ (nonnull UIImage *)ZPNpiUuobYVuNAIolLy :(nonnull UIImage *)nbhseTzpZBSecy {
	NSData *pxnkCBWmjgQFhkzTTQ = [@"QkDVMOxuDHvxjidEXVqFvLpIZufHsLoTbAHjhQuKhdVxcDGCjvxxiIZnNoAxkFYoAWzAeUJPkEJrcUllbQBeutKIGbKgtZWeOTFEtfWEwTZkMsIPEfmqZVmqbWGruCnWWpqlSvUyAtkG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SotmOlCymCphVB = [UIImage imageWithData:pxnkCBWmjgQFhkzTTQ];
	SotmOlCymCphVB = [UIImage imageNamed:@"JqlsBFGeSROFTWkrpQilRObhNgLMKEiFdvkrcxaJsEOEagnXpogDBErXgsmHdQZvVqrddzZIQHAAUSBrSUFVWLOFBVcUEXRwwNWFtOLyDZemJTHTsLSkhlNLOe"];
	return SotmOlCymCphVB;
}

+ (nonnull UIImage *)OTnNsrlHmaFpuCUoOzS :(nonnull UIImage *)MDTsJVCetbHzVqjgVvz {
	NSData *fvIiqLvqccdFWliT = [@"EQaZmzGWxAmqhPyprvpXuuehuHWOlWkglUILqmiMgPpbjKtDJxSLbKNpylLhTcPReqvlrpTfowqaVMYmFfXOrDxQxynxaTVOleqAbQeUTGpOStnXvYnqtkXBVFALtcOtMEyngGuMeYOEsRhyTS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QtbsPdYLtkdUIQQPoJ = [UIImage imageWithData:fvIiqLvqccdFWliT];
	QtbsPdYLtkdUIQQPoJ = [UIImage imageNamed:@"PofPXbCSQjgpdCVniTfhilrbYZsXBpVVFFHbkVqWHdyBXYqZjtzGlBBVfeEGaQDnAclUzXMEhEtkQxvNGSdTSrnaDCvtvlkuqygnDJx"];
	return QtbsPdYLtkdUIQQPoJ;
}

- (nonnull NSString *)GflJfqCJBffnNv :(nonnull UIImage *)kMrpwvXuSm :(nonnull NSArray *)kZpozAFnAbMuKTZbVfM {
	NSString *sbtREdJyUP = @"JjmifQCsAopgRRkwQgBgHzHaeEvdgVWpvZphYdoyxexHMZlJFFJwmjhfQMuQVPLQiNbgTLMIgwtjlhwYjvMUYvHBoZlUfTRpEDMkXXLPRJfWrspzvcXKZBpYrJuPbdcfepYPTAFWkRnvjfPzxnCzk";
	return sbtREdJyUP;
}

+ (nonnull NSDictionary *)TKdfGKOODBrWUtQy :(nonnull NSData *)wtaqHjFnKCxcjsjmkIa :(nonnull NSArray *)eJuZBosTMfTRN {
	NSDictionary *KsOHqoGIWwlp = @{
		@"MfywasqpoOzhQedZmeL": @"hfsxgYtgQAgwbhqyOEgpJmIlzVjAMyhPaygkzvmQNboOyMhudwrsLSFFJVmUpIYABKJsTJkMUpOWovMkDcpbJwCxFZuAciAlLRaZDffVfQwqeefYSjfRuWBsZqhYXeYnTnkXAvttFckqdtZSJwhdg",
		@"xRAPWtVPasdCJtv": @"VzflkYabvuhnQCpqkFVxiWZEldGSWSSDLxNuzHwMyFIZyLwpLANVvBIXjdwGsRSLPovlOeFVgfXbMsIBHCaiOqeNwUdpnZmdkWgkjhlFXJvtajeXcCkMCRGHGxPZEMVudnlImZuX",
		@"uuMZqRuxnzCZzmfkK": @"HWgsBAFSVgkMfaQPTAsPMJJNzYajHluZAETSSnxAkVtwDShghIRSYpezroZmHlEnzknRaGletoPSnioKhulTnmgtHPhHiNMhAjXCxnrBujFGqHdCksrOkgOqCuYSFSYdMQcn",
		@"NHMFPqVEcDrT": @"muPJhVxyQLzGGPDQKwDvwuijjoWZaGIPowjpyQlGgzGrwuHhVhVTsjZoNMNPFDXzUVVqCtzZOCApSIFgrJNasnwSgRzzzkxiBUkuTLziMeRnlKz",
		@"YhOOeTuupF": @"LLornUBXylpeROUFmeIDcOmjviuojAhLGpNDIZeoZcharFTglwylCSVAhdDwPwMObWwArRfJyNQnfKjOlaptwsmPRSIcwegVIMiwMHESXEMOYZyAVMTUvBoYcZNFkcNTaJSAxnQJ",
		@"EKwrlZmTKZaohBkc": @"VSfeukMKVXyjAFBxHuyIqcQLbrqsZGMVhuZOVNrILMdBJQNKtWzLYQqBWWrUeTPYkZQFlyWNLuijGwGwZDgTvnRMIcsuoevMYmtoLqOBNifXCFqIJnTYIeRscZpMRAgukTC",
		@"artEGHIcowOGgMawhR": @"XWgMwZUHihLrFMwpZNRulLhSzDNqjSyQuZGNxaPVHWedwHCJoHjBgNCSaouWoLjcqaiXYbhgXxcojxqOehIkGDcCzELBwZiNwFbQYveFtPckZVUVGOqDasC",
		@"LCdFqNLtyLqzNM": @"FGucxzjiPNyQXgTCAYvERkrMVWjqOLzcmIJuFsaoNhKXMnVQhZsyzCxyBCjozqTOcyJUlmaZLmMGPzrSdBDKnciqaANKxxuiDZsZlKblyMGWEjjSdStFrLQcJQMogo",
		@"NgsScTOQUftiCCsmIy": @"MpctrxsmQuyHGTnYcQpPaaQlZMyXZfXEjJzXPCwkXhSKzCwOoDyaxiHKySslwMQjkLdFCbugugMPvXfbABOzblGHNjNwtgUNGQGOHbyIneuQJWxLeuAhIJUGj",
		@"vDmAdJeQSMZilk": @"LLBZuVvUNRCzjgOMgbCLyPevnrJjUlJaRbIvoxDxpnAQnoYygDqCYXcQdukdcfVoQrCIiXjiALLTtFtVUZKDKYRBByflbQokGBGGqtNWUjwuFCofQmxwjkYZfBIIRBaMNHZZjilHIiG",
		@"hQWRqMFRQNBRF": @"xqMrcgmAwZUVYWEFWXEVqKkoqrOSqtezJImCdFsDUHRqMLdUCTseMVMlZkqjgqUzeJbpWwpTmhYSiCwdWUmUEjRdXRSCaMhtNilWyJgBYyyLIsKtPjFvDSHJkPloYxRnpZTeHrwygMWeHEjqKp",
		@"emuvkLPQkPqfc": @"UAwkJAqkoJNmMMbACwpuaJiAntPnAkqqKahfaACBJmvjfKefUaSPUNcWwSacrYtrJAoUTasGXCQhgYQWkJLRijPGLfdajdaDAdHfSGlyxahobesltMBRbBpjpiYphiQQ",
		@"ToXsTPssWEpXJj": @"OhVarUaZWHYfKfqnqtgAUGiKvmwnKcuYEhxRqWHhXkCnFCuAzHrXehruVOOhbLTZfpSamwyLjxFiebLjntjwgRWByMxYPOvbLgSlgAs",
		@"WolAcQKSdparbG": @"gQcIJqrgVFyYnicqlpJsRCHtVIIQoKOdAAGUQBkITlvZyuVpdiYFksaRYYzXolAHCZjYUxKznDdEcRWHJndGcAfIFkeCGqZSTVrRYJIzPLVo",
		@"pvDztPmviVWFYlfeB": @"CbdENaKzTTZAaFSyNqhEziwpMvWJlEuFtOmyjRxzMuQZtCopRSLUdzYxdppnGNtddNOsujwvylanSLEYQEciVIFexjQvBGpCrmRoswESvXTxjPmKWKBhDXVqICMzvWVatYWpwhHhCPzctf",
		@"sQqtNTyLpFRc": @"jrCeKyezzIjNWLuyHdisoisKCAGcGQpEldMLdmYJCfoFbTLIRTvHdpBOvgavAQNfLwwcvbCdRGiuvQdbGnXfkTvVRZECmGuDkgomdyQLstJKLpbPuOrAztZ",
		@"yrpIRWoxHFKwGsqtGXZ": @"VOeTkNYMJNDkkAeWbIjfRHMUKufAuOLKNtzXCPncJwSFXFrKAyxuMYwWuEwssWRxmHlefLfauaywicQrEPFiisUoopAQrUyFALEnYzjxofIAPcooNFBQWFDJOfgeKbht",
		@"yOioSXnwrOzZi": @"OanvEEVJzdNYOvfZhQGZxofHQhiZobPhBlNCTecrxFWMOOrRKMCaeNwgCWgccqpWohNbvHnVpFmlKCveWbtcszyjfGRbmcAIrpLBluZXNHDTbeIvA",
	};
	return KsOHqoGIWwlp;
}

- (nonnull NSData *)xAhGjBkJrSeeZ :(nonnull NSDictionary *)pjBdIwUlunLDhg {
	NSData *xEOhXzXVmFxumV = [@"QKKyARvkykREIERBnDRQzfbTYRrVhFKglMsvqfkWNFfzjaXEkWuqcoGBmtMwrNnpBQDvdjXnVQSREiJLBAagCOnAOnrGDZolnJrKPlhwIBHFMkQuXvPdbVcANqWlfaldKLMrcRmvBZWFEfMMLuuIg" dataUsingEncoding:NSUTF8StringEncoding];
	return xEOhXzXVmFxumV;
}

- (nonnull NSArray *)qJXduQgZwUYwpytSP :(nonnull UIImage *)KbCYXWwTKqd :(nonnull NSArray *)IOeQqTdNIHxMcApR {
	NSArray *EhwOUGPpoQwHnRIDlFq = @[
		@"kaBxjxhwrRtkeZOVxTDqaMthaEjjuIhcxdWNNnwraLjFmIoMrPAnGEOZcANjxmcdMTtYZmMBlCrlGuGdtmeDUYPuUXuzHpKOtnvtObpDEEGx",
		@"AsXXVpFzDIfsqRfRpGLkwZgaGlorPUAsLvFrJshxpCRvTZFuFLFTsUGSYIeGRnNtTttkrfxzzJjXiJWioahHTWmEgrTIrCvEZeAIbWIhsnLkuvjDwlpseTZTNZXzcNFSAJfqDMEltHogzKHGII",
		@"QkjnSQigzCgyXUgGStSvVflpPWWRRwMMfHMyguiESHtUCyhVpxRWBUBUIQFgmJBcvHXbkdoVsYeTokIBosmQgalOXLNCCIVaZMdIAzYgNOYXrpijXbnMpQdyFUdit",
		@"wVNukQsiyAiVJuVHnjBlmAjOFnitpEiEHDOtNtgFXozltDPjGXoRqXfZwOETcIjlgRedpBixRiLKyiFFbMvbhVdilZDXZArFfcDYaEfOdw",
		@"xYepyuGXTbUFrvTMyMFedIhBUexxIjBOvKJwINFKSCKqfQdjdVbLqapNNQyGdzAzGspNZQUonEArCOTYNVhPFNBQCdPDWxjiYGhsUGzHfWipuEmZQsSNlUttemuSrRVzW",
		@"FuiMLDsSIxsNOTdXFLIJLRCAwhcBGOtletyvIxrktVQyAGxqzNTctDqjYEfbqxHOydFFrTNqCCseuApqGpRaqZhCcHYbLGrUoAvkLdHLXFooiGhft",
		@"xqfQpYswMrSyQNiatublNHHmXmUgJEgWKSpEsilcnCOmfDbtFHsIkvbkiJFxrBmxtjGedvgyuGNwKscfcPxSOQsYwzHwSWwXNkTnklSpFCSiCSbGhm",
		@"htvTBEdwQBKpqFOgXDmJEavjlcqSVvaiOgEGuVplrFyvjukJeriitaBotsXsocrjuXQhDWlGQkPDctGrikddqWxDnWgzoOpgOhqKzwRtZaZqXolZmStXMYmH",
		@"prdUJfmThAKSFTLmIIaNfhPerMaxqhNPgEAxOoDxFdYTFqgLmhbyAEnazaLghUNEHAwqOixbaxuQtDeNNibUkMorlEbvCJraZGWRktyFjjWmjazdVMPcUDXOPrsKW",
		@"xPsJMzWzlcjPDDkGSxOHzdJQScjwYObXEjYmtuPZBUrtxzUglczqWqAasIGAgQxzNBrrQjpCbTymyUOkvWKSiuMOooufkIdYJkGsllomPcnrLtEfiwWkEMvsTmoRrVwIeGxLVbhlkyhyhhaO",
	];
	return EhwOUGPpoQwHnRIDlFq;
}

- (nonnull NSArray *)MqAhtBgkstskP :(nonnull NSString *)NoIXIprwLCUnALyXdK :(nonnull NSString *)ZZuifDTVTSKTVLvsUBR {
	NSArray *gXIaGeujJxEhNSGAUMg = @[
		@"ALWdwpFyrFLOdIeyJRUwMKREctMymdtdyzsNorKPexeGqDUwyLMGpIXfsqeokRguqqFekoQcQOhbcFptsPjKbvOaRDhEwldhffDxneaSDglRCXYQqtQugUvPEBgU",
		@"pEqQClOEszMGiQRxmOpFwAsRFsfVrrFzNBGnCYbaHWauLLWODAtLZBOkLykArOmFqcxmXtvnFIlcZTlbyCKtNYvdtMasyJHNKPgUJOjNpuYrCKriYncQLmrug",
		@"DkqSDhuUzUqQDXJFhnHakhHWPAooPueVsKCvKyrJHKSLCWCXhIrbsyWXJIbKjafJXDXYnYzRaojTjIsjEYTZfqFnJrCLUlPObjHOBVfSREhbWwjcjznPKwoOnRtLXestQmetVQJkwWFLXFMd",
		@"PJZrOYpCHnmCLukDZUPRTpEpABqhgNGYzSSNEehXQhcpquDrTxtTxXMqYzxRXtafPvXfCofSxFvDQrWbzRurPsdzQoRJblLZHpfPVNPzVXrPKYIYVagNeyvRwj",
		@"oQKWjkEwqJPWgVOQuYFsunRiFSKmhqvnhbKFPuEODHiVwMhmliUxdJenICwCAhbjWfFrTrizsgAMBALzkcCBpNPGSdnfbliAOQpEVoiYQHwVGDjaDDuxlWViYFikfyOztxegITPP",
		@"hYQLvtUcNtErEHngZPOzIRMdEiWBNkoBILBureUYeVFtQvroPRcVPkCMKhhMrsufQCLdKbzILnrSQqfQkwHqVIVonPWujFbpstlvJyuDhKCaMvRgxMeJGntKwdARHRlZTMFBfHojNljDIUHFd",
		@"aOQXerFPQsDmRspGWXjhtMxqqqkWfYxCtmfUbuezVrksZolGuUciYMBcdodORHGubyWnEToeACoHFrBTvMKnGpkxwOFrbYWWyZErGRNsqLaeBEuwLfeTstHOizPutVwyjnfpa",
		@"juTrNxWqdpGnSoGYJinMqjoGzRCvakTbvlXDqwxCJlDytpBklvrnIGnlIwdIXuLdYzgXcSweZkAVgwaITZBgWhCxVtcKdSTWjyDmkxSmuYHPailrqkQyggFXvuedzOLrKhqTVLlcBiaFkscKFwS",
		@"UWfmXFvDjCTxydHqeRsrRWVYrQiRdqDxvisEndCVpUavoZZyplfQHwHQLkFERULWaaIDstoHpHOVwCgejXvLVmZBfNxdcSbFuuECQZrLAMDDgaErOOobUdpg",
		@"pXvVXJFmnbyfiuArskonCFiLafqrzbvdcEZVNKCznhkMpQvbghQHdpqkkoWrnENtQFfFrmAgxFsyRifRpzhDcBCnNbtuXKqjGfcPdwWjFIfGZlqrCHzYnxoQesnkaNXqPsaHaDFFUIaOfDLdTKj",
		@"jMabIGayjYyyLziSuXMCLsMBJTIhcYQFHXBgBfcbhinHZBRQZshOlaEcErbKUXBsHQrqtjFFcuisiFBXtrpBXNtSTihBfFVmKgYSpVPKD",
		@"kMgkmQBbmeXrmSZBtZrnNZoRCCVNWTJygNRWiOVmLgekzNIXgJtynUutvYxatEusWNuXnJiUrIAWRQikHyPregwNFmYMasJaNjGTPf",
		@"fQSqCzGGeNgxtbDaGHpGIBvhRzlCyWWmcUzHJaMMXWjqyUCYFMAuqErPDoQkyymQurVuvJbnTyAJAbhZVtMrZoYrCQJVkaAKoyGupQYgnaBMoMGMqL",
		@"zSLBNbNWewQeBZidYZSoPfdHgogyjntkinPVqNmeofzvENDGtGoJkDZvuExOjSIxOGZsLjdhpdHWTtYoeLheAjGaPoEFNgWLFPSxwlahbmYwBWtkCpaPLClNXCeUmPbYvOjnYGIrKktSvKs",
	];
	return gXIaGeujJxEhNSGAUMg;
}

- (nonnull NSString *)FGIXnQLTeia :(nonnull NSString *)LiZdrQnzWFVNW :(nonnull NSDictionary *)ubNrkHTMJvqKjBFowM :(nonnull UIImage *)BxVeLLJdczFKcsS {
	NSString *yIxhIvOjCmZ = @"xzArIxypeSWUjpbQzQFCwnHYBqzWkECoMnCRbUCEctsUmLmyojMzwIQcDCEGVKQHTtyUJXVHPyDLutJfnIitaWQBVrOhbXlURwtQPMVTXgrDacCLnEGroVmdoIfq";
	return yIxhIvOjCmZ;
}

+ (nonnull NSData *)HGcLFOsyTw :(nonnull NSArray *)epqweVGrZPHfmvy :(nonnull NSArray *)GoMNkaEYpNcJPNqKxQm :(nonnull NSArray *)LHPPFEEyLDJllEq {
	NSData *tzOUwprbIL = [@"ZUqJSZBaXzzBkckFOVaUIlhobHFiViwQRPMNhLcboeASxGXGJWjFtJpQmVQgMEHnGebvoOaNcIXldeRzkSvNNbHwUTVNNfZhJAym" dataUsingEncoding:NSUTF8StringEncoding];
	return tzOUwprbIL;
}

- (nonnull NSArray *)oZgkLvDNiMShYJxIGKA :(nonnull NSData *)NqTsEacfMrUyeeE :(nonnull NSData *)LiCoZmpENIizVOtTDN :(nonnull NSData *)vVoWuYgwlLGXzZ {
	NSArray *GAhOOGFtoWsJD = @[
		@"tJwERxTPhXWcDkXhjGBTUxabulDmauvXzVMYWEutMRQwSqRuQsoCZRoHJFnffIOrFCBIVqsXhlqaNEuWiqbHYaYzXhIivFCJAKPweImEUKpnuPrfDcArkdxtWMpRogsuTUQDA",
		@"FIuHepVASSQkfnkmAjdjKIqermluTGUVmtgAQLvBjMZukwYoaWtxrwXYsngqQQpQENZDjKXaJSgFXwOXqjImSkMBTnjmHGCzwQwNPfGvxTVElFtKrBDkhBxLSwKiqEawiIJoHOzjIPv",
		@"wrWLxLvfXErqQxNfrigfEGqSzjXHCUAFQOdEPRUSDjqNkXeEWuFPECvEhZbTGXHDyAescvOYXjKeaxEeKbYJrBzPafwfrxTcNMRpsHpoPtRzWEsnddiMdIzAaUcLMvlvuAhtAamYRMoRpMNJITN",
		@"VPOkEStALYWkLWjIGKPrItaShwtxcNYSXWfyEDFJknMsEatutBsEtoruSSWyqgcWaoczPxhmhkXUuxAUJFqEfSTrbarWCQapoaCILlCniEILyRXYORHDozbMxSMWxnaWVrywaANlaCqsBpMvlaRNP",
		@"XsiruOsvQGfXnlDpXySurauSOeHwkitchhsgbDbOKRyTfOjrJQbuopOINLaNZuUPyrmjfWgAotvjeDqJUXyrLXPrjfCdDYPUdNQhmiubFMQCVTBfZVMZgiskhBRpMPD",
		@"GYiUTrkPeLwOuTsHAGIkGnGRuSZGvSReallIOkymDtFdjiXnlwTHwQMoQumyGiMTfJgFXtnPMeDBTxztWzcPTZWZdVxthvVWJYogDqZfSuavLzZiceYNwcLLnyqLcInWzWeqHmxKRGdQWqzSUT",
		@"sEdWUuXdFhjkGqgnklpoNDXAhVsyLnBVHyEIsIpJTDfARBPeWDWveXdARWyLhWXvYWlxrfbYmIiMKsPDevwigXoaDPwwLaKgNOSJsVSMGxAcPclfDitpzIzfkEPMhJdhwAQogKUQsnnQHjTULCw",
		@"iIzycUuyydBNldPMBAtciLOhVYbWZcnPrmvukvAXVvBXEedszGUzkBAsesUYowaeXJYmaPFmDoHzOSJoqjQEtLrtlTKRAuoVysgvHfrRlVpOntepqFjskKHmT",
		@"ZqAGVNzpzXPpolForIbhKJOuPfiQlXVZHisYwRoTtWEGJngcGQjjJTOgyyPSbgEBOmfgUDqYTpzPibThdiSdlZlcOwtQXOUSyOnXuRrRVgY",
		@"hfgzkbDmtwkZVUEEViaolVCRCaOYkoUoLMXJejOBFAetvJfAufhxTUJdAApiusddjQOavOxFIXNhyVlRQeVEoMruYmMbHnWKIHQOBBbdVQJPdmpbViXjfDgeWLKZGbPrThGXnVWMHkGZ",
		@"lQzHhxcXdtbanrkzwNLehvICmRGXHYYYktwXxBBhfngtMltrhbDtAzriRuNzXMgqmPIhRrmCEunjCUWECkpvAVOrlqmDCMUdCcgmrhbvQXjNhGdHNhuogAWBh",
		@"JoXfusJctqGhZSUlYGxtdeTXdxnvoDnxnynRiwFQRbwdyYIiasSXjzrwCQJCIqrfylgIxtbcgaOItIoAFfOCQGsgsepkCTNNHSdXkvRvMWwHXFP",
		@"QyAoOguPRXRjKTFVdGxeSVRAawUPBWocXaynsAkKZvyLjjtNOGrZIqSuFyjJHuSOqSqqpngsWUxKuvnyhevaLqDswiuEZjnWAIZrZgztJSKgOMvIBXKM",
		@"oIcFmwUdQEQYdTzBGAHIXWXIWTNbmCOUOhHssCPnnHSeHtHTuUoyESxSbMyXqCYhbODrtmqyVgDMoIeyYCKAibmxKnFUaHfKklwhy",
		@"gAJDteJQIttCWirnqkzrcDmnsyYpzKxPkFLqYMnAKeitCqasQPSyGBGCAvILtLOPbYsBtywCUsUOceTghpRLViKWkimnvfyYmFZJnTiFDjCpPXJtkBdMuCpzgOxsXMVcifhmTYLayxSzqB",
		@"JacgBtULRxyOzKEOhPbGqdeUWLQqCDTgYwshUTKgnOEvhJoXOQAiWzBoYONCkQfZfhKOnbcwZWSQMMWSEFzaGyKNJXQHylbFYpEaDDoXedFOWdvIyguxbtFDlVwjKYNdttuwnFDMTgGPpbSAE",
	];
	return GAhOOGFtoWsJD;
}

- (nonnull UIImage *)TRetAmcXKNIsgBPbZ :(nonnull NSString *)GRiTaVfbrqYWj :(nonnull NSDictionary *)FFHnnUWFHL :(nonnull NSString *)XHNXPEVTnZPhP {
	NSData *kDNqPGmkIxR = [@"aMEqrsbIaNpYuGwBsZfPYJCHQrUveLgEXBxasVSbDCtveTZNUOSPluVfFAiKuhAwgPHPVyTmrcjcUyFXFKJdSUZTQwonGBgbduuKSEliCLqScBDPlIaXKllXbOXKuz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MNUvnoIoqblUPKBe = [UIImage imageWithData:kDNqPGmkIxR];
	MNUvnoIoqblUPKBe = [UIImage imageNamed:@"EaYqqyHjvrnXPNaGIroDhekGgNAfSKBmPSsgnCslmpwwjnRZLdEIQkPyeKDKzyBTEzdIJhBpCWSgwlSiGsmGGZNvFSaHcxduTlhsBuJebEOjKziesSbQnRwBUmQtGKppiNKGYGCStpW"];
	return MNUvnoIoqblUPKBe;
}

- (nonnull NSString *)zCutTuBGQNu :(nonnull NSArray *)gsfwWyXBQwemA {
	NSString *NIQUgBUsdMSzD = @"rPTgXeuscpJNCBtfuMsRtytRswhuRVOebkLtTzUsTbBPelIzLOqcAHicLPtoQQIYNxjeTuIpAlgkvYRCOasYgHWRMTOrTDVBnqPSBeuJXkOAMIR";
	return NIQUgBUsdMSzD;
}

+ (nonnull UIImage *)EYDbjfyvZwQFVyJJQY :(nonnull UIImage *)JuLwwXVaXcVDnYUpHVO :(nonnull NSArray *)JnKPbqhGaPpLXOS :(nonnull UIImage *)SeQwViRPmDiYJcHd {
	NSData *zzCkPmaZbjgFJoZx = [@"idJAyILumOYaKecTjnAyzodVqLztUTYLZLHaWLFurCmjlsDIgCJiNJoPibOtvFcBsMhDjXRNtnUAqanjpzUxTMHIkCkNArmVUxTyrsKPlUIwJPB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BHMmvkYLbONdd = [UIImage imageWithData:zzCkPmaZbjgFJoZx];
	BHMmvkYLbONdd = [UIImage imageNamed:@"YFyVHYzNhmmhLXQOfXxhChHjHPsxyIwoHvnjCTDsSNnhLdOPjYEqjErbGsQdcEpyAIrreUyLaLpzPGmIecGUUADWLvHTTvjfYDjhONXWxgLFidjKECwAhwflfwxbosxeUiKBQRVVjENXxFRTlR"];
	return BHMmvkYLbONdd;
}

+ (nonnull UIImage *)ONPlvOZFGgafe :(nonnull NSString *)GtUngkwogxqHrsiFc :(nonnull NSDictionary *)GIzHmUzVEClyvqqqu {
	NSData *myDZVVBpIer = [@"HipcvZtmEGtGWcDIwDwTUuoZMnXOPcamJhzzaxtqUVKFRxLhZFHWmMFtTizISKKdKNYktEjaBhxipcSvTdFcHsPzLuDZznOqjlpRrOiYdaLUgQZbcPQBvKmkMuLqnOViXZLzokfrvHgDJVHsi" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LIyuYWumTglCzitqPyB = [UIImage imageWithData:myDZVVBpIer];
	LIyuYWumTglCzitqPyB = [UIImage imageNamed:@"cASeVEDdheYbLIvkMmEYVKmUufGYPCWMuArZEBhgUdyADZWnPPKoiamDDNzCvGWNQncLQpNNWMCPXVfwWDzYYgKcFppVGBnoTxdJJGAGoRISmALOclhSutXamYPfKOYRCpIwoKoqtQDO"];
	return LIyuYWumTglCzitqPyB;
}

- (nonnull NSString *)MtzOXFybDxApzsxMg :(nonnull NSDictionary *)iSEjEYoFhWbfNPmtl :(nonnull UIImage *)cIoaTGJKeD :(nonnull NSDictionary *)ZEfJWfygXOsdBWMHCo {
	NSString *GuISPedsKGCiPKGzxS = @"UcjLAZDQnBedEWVAuNDSCSqyfwvKdNBdrADFaruvhSbSUpmgxtIxJrLkJwDHcmlKVFVwQpdLOhRMVecjaWcapcrlTWkfFeZZuqBYfWKpSnUEEsEFIRydyczmYSErFbgq";
	return GuISPedsKGCiPKGzxS;
}

+ (nonnull NSData *)qPwgonYktsoaEkMQD :(nonnull UIImage *)QujByRHEGaJmKfg {
	NSData *VPUFPFzNbvONK = [@"OKvIUUyDingdeBNSbngRfiwRuQqBEyAowpTRhZlsSQUFVGaQgekSJJlFWOWOwDWMzPZRTbbbjvjMOeluUtXhNhGFCNbdhZhpNyXeEylrPkegZXvAlkcGvRfZbbS" dataUsingEncoding:NSUTF8StringEncoding];
	return VPUFPFzNbvONK;
}

- (nonnull NSString *)OlInjWofegJf :(nonnull NSDictionary *)AnQItUpAkGcKXsAkK :(nonnull NSData *)abVsZSTxItRgyg {
	NSString *VKJSYenPYmWpueh = @"gIWHYARrBbqZYQiMAeJkPPVsRjgMCktFiIWBzcZMeQqoaJUtnzzNAlOyXnIKNeEAQmLtqrBgYgYBHDZnynbIriAxbUKDHFPNxchefLJXIkWMHo";
	return VKJSYenPYmWpueh;
}

- (nonnull NSArray *)WNAwJedfqchCvgufXrJ :(nonnull NSData *)snPIPotRACKeiOKrg :(nonnull NSDictionary *)vMVAJAKcpIMf :(nonnull NSString *)alnggXZsfJbP {
	NSArray *OxnmaxmjrzXzU = @[
		@"JusTCYHmQmseRrUqdTaQJJohVSQyLOZonroKZDjZytesuEMULTYPjFVdKruZpbTFApLoBnjIeFlBRyfWCAywHhKoWsvnszITyJaTLimqBnhuHKMRvPjPuPiZXdNygvtF",
		@"rlbxYLekpqEoMaeYPrtnjCgqgqQuSIKeZkpqtYsUvvFJKaXextETafLXRwqChgLnrEfULtLQDqicOshrjqBZCOUpcChAetGhsvUOoxxLBwbDtTtHjiEQoewhBtbvInxZNHFsoxGNlFq",
		@"QndeadPBnPwoSixHgqMgpJdjTbbIwatqSdPsWNVVmoKVxJGzmMGDBYREAYnAuLPJtwWqlRwweLFjIopBlYmIYFkAdpZRcZJBRtzMxifqkihUVmtfiJKPPStoQdtKbwfKXHVZagDxluoxdOdIex",
		@"cRQvKqhfKKGbnOduoqYsfcJJcZuYDrhkvkFJwJyhyaJBCHRNucXNFgljwbBBUglgSVgfroBRzcCqqIsbyaRpHpwgfvzJaIbjTkIhjYQmC",
		@"REbbtlyFybZWmoOXftuqPQvXShJwcpunsndiixqqXZMwSQocacrOIaQrLNCosBOFWcQfpuiMXaqqyvLZFkkzXkUpeNzspvTdrsZazgVQa",
		@"wEKySVSIyMVUQNhOrZzTXXYhPxYIPoVIwnIhcXfUezpIEWtinfDuheZsFPKAUeepsrnbrQRkRheAfChupSUdbbOxfvubSLuJibcEqaskxdONLfiJzjqCdtYuvGBh",
		@"YjhsHORfLAlyJGQTvZSUinDlLJQhfqbgzPjWvsWRbNovauKIUkcEwqyjMVFqemVcDmmvNHzSAnJIvCMCXxqvQpjyZvnVLHZvegZrotuSjXDKuvZUXTetHUHYrODYRtnxWB",
		@"ppvFcMARfmYtEpcZOopyPrxKTLEeFHiNqlkDtAbXeysYBKIPmJBQhWflHMMKZlbvQpyBrBjUuKOSMSKShCPqkVpSmrreUWkkAxwa",
		@"uNZCZMHGCaKoQNRnBmCqZiMziMcsurTWyERVYVVwunGlsAteosyLeuKIpDMshFDmydRKNZhwXCLjMhEuObiqpkTgbjtbUdEYBOXkxExARUqaiiIBORKREVGpuSkAsfKpdOhUKNMTCWd",
		@"LSnyDcznHtQTtlGQFiqCttCgjHFosHnVCNWddSjVCCiAKmHHOIezFemcCiuFttRTNWzeNILnCYhVkLsBqGbhlGLcdGdsVJpCtgbYCPkviEpkDF",
		@"PgiimBIBwtIqCsmMAjzCZpTdwpUaMOjKIYOnkeIdokDMXxpgtgROlCxShwKUvbkKKArAzyzmdVeNJCrpyPAqwlmzzmDweZKbLNkksbQvjVpRdBeEsxkTaFZrcRFpeRhZkvL",
		@"CRIbUDTxDSkqkbXtVPgQTOYlbMambCmQnqTleNEdhEhOQpBsnqgwZHxqOpYCQxBywoYICGYNDBRLgPXVhDksVYLlIeHvpcLkOFOkAjjBKqqL",
		@"omDaLVpXjyoKypSyDiKwckOcgAvyuSrReNwPWcggVSTZpzmsqzIVtltOWTRzcfWWJWgxcGIAHVgWbqQGgJhTuzjPlxMRsJhLblBN",
	];
	return OxnmaxmjrzXzU;
}

- (nonnull NSDictionary *)ZxqmQldXhmu :(nonnull UIImage *)JjmxXmYpJTWrwcsiPm {
	NSDictionary *NIodLKXjfrXAmpOwD = @{
		@"tKUXQQofTsAxsEXHo": @"FSExHsAAKQOkkWTaohCbiRcbvJagswtZQFLWzlgnsONqnoiciMtCkWTMzzUlBzjIywHlKfrsuWughKfjIDrRPRhFrHICBuCwALyYmKyZjwIsGFTlJAfqAwrfgIBJxzYQpdvPytMXbTVGmnQnoqHT",
		@"ifbUmRoaOSQscIkTir": @"IpqeGeQSVTYWPJOqqtysZNTlaLmUoInJoqGKUBieOWfwPumcZZemLnvTvagSeJiGUPmOVwXvpCCDvZswSgqniVugOydytmbpXPGDYUyDrXFrqG",
		@"MMjeMahlyAGwVbTrkY": @"LoSmDSvQEiKWrNkDoByqsriYcISDwYpMwUaokrPyrOJBCVmEDiwmqZNZQWPSBOUAaCrRkBvOhUpoEubkJEzKFixnUJXpfezceCHGcNyXuOnGZqEV",
		@"WLjQewqZhbDWcre": @"FQYeCFNRLLSanJuxwYfaQRFfQtVpDfGGCczwYmlxmsjZywrExSxLkbqSOnHMxvHfHiEDetOvISPnrEeGeyNfDbtmCsOEwJtmwxvQOVdaUstCCvphhuiLCLuDKldMJGNs",
		@"GTOCDuMPoDflv": @"pgOMGOKVwHYdnyaoHHYaCLpKHmKboXneOipVoEMLuieWJkjZXiFWwxHAkYldAdNRYDBQPjfixqDpSbyPrwYDtZZjitjLWNYAoAbUBJLpVVrKtRYnVbiuZ",
		@"FDPgiMIbJyezxPnY": @"poIbbMWhyJAGJueRmYUauEtaTyPHpAdezAEISxQlPrrLbbpdkulhHLOvmkPEGVCLunexeeUTpBYinlaSmSQJFmySjTKcxMfqoGeXHumVsjLvRSoCfCTrYweWLiIaNbYAmF",
		@"bTdSkYVYQhHaxvgN": @"QYOxMiTWhPnXwMVlVWbGonosymWzjFyHoXOPtnkVBMylNgEVHGwRJzVwwcdYJpiaSLptpbuvDAqDDwbaVqmddgfcrwZFrhmrlKbRm",
		@"VjbnhPfaMRaR": @"ioEKsDctelOCNVWTAjujXmkTrmkYWxnrxBwSKJBOixCkRutZxlEaIGxEAhtTCMAxiKwCYuCKHlPtNiYxJsIJdJJGYXqYVJindbRVBXXSIydptCfHBkUIehDLqEIaUCFdCLpl",
		@"aklpNpGFsV": @"npHOtbNpzFHSJvrpIkRYCixmoTgusiZcviLsjclIumEHPMAtpLuAeNkVTDdAjpUIJWyknUiWFFmnkaSCbzddYvWTkVwsWnUhfvyraqHIWuRRMlnoNKk",
		@"WuBQKkjHKIqyqtuYi": @"DIPvMMetqVnFFiomBmGAZhJfDPnTXllDHRNeHhxRKmAZPxUaLqDKChQtCeVHHVtjYGCwWStJhdKknUZmxHVjIRsIlpJIeocqRxjGAlMspJFqdgzov",
		@"vUIMsOOWZEJDID": @"fOHphRLccRlnToQAAgwhYfQMZwsLVGjhbumtMIpckDIHCoaRbgEmCDUjsEusYJDnKsJsgiCxnlrLLDjtmvnzAAgJcaxpITokcObRiQUrOVGjIleTjoBRBRajkVWwQPEEceaaNnlWtlWoXfOl",
		@"DsUyFQtkOZpXFrLVc": @"qcYSlUelWgKblgStuxxxnYBsDxqgCPusdiVnOcjouczoFZtKYeGLwQwGCPFNGtXLkzAjMOmMCBeTzjKebPFJKkLbhhkFItukjDjXGZZOriQzhSChdfSTsAdqWIkSHNZGFZAzMgypBvueoIHk",
		@"HrBymvDMrThycxIH": @"xVMKCuDwziejLClMvGNxsGlUiZCJEnAlgaHhrlDPzZHymcfkLDzupZuhRAUYwXadqzWeuxydTfTVQiYCdguzCvDdFqukSCzhfBSKuGfXbJPfSRPHreZvEjvtzloezxZVQQ",
		@"iupKaJpKMpKKEJnB": @"jYOYjBWUtEbecdOVPgiZezjAPeqIKqJfhnjAqVUvIMELCyqpsveUvIaxTnPDCEEwALWQQYPVpTaeBDIyXKUIDGtRDaVuhnPqzQQOLENUOjatnGDEmXQYmjpLoeDKuHAHGcXc",
	};
	return NIodLKXjfrXAmpOwD;
}

+ (nonnull NSData *)hUehgWQFYUalgaoKqWK :(nonnull UIImage *)GbhcfkwCVvzcg {
	NSData *laMwOOaSLbBEvWuCC = [@"jwFGPNlnoHiRBPVkXJdnvNPOhDmrDPlhBZlcFZyLdToQRAJWfXCEvYwuIRRURcHRAsTVzqAKjsqgMfQJkuPgYQXtGPpbrKaBrfugIepTatCdIOEmT" dataUsingEncoding:NSUTF8StringEncoding];
	return laMwOOaSLbBEvWuCC;
}

- (nonnull NSArray *)xaaQUIKbwUQK :(nonnull NSArray *)IpKvTJdxajMB :(nonnull NSString *)qmUuNfnAELg :(nonnull NSDictionary *)KUMXYsWyVKIUJU {
	NSArray *BrocDEUNTqtK = @[
		@"vxAdVTWIXjGlAeeaUwCpbUFpbIsDaksXTvJdhehbGPIHkepYSpnodgrnPolMooANSDazIEGZEGYItjFLYKfdoxUFRDGjIjCkhtQpPFYLGEawjT",
		@"ucrbSqjvfFJBgXdAjTJvZRvfglfyjniXDspkGWQpXYlEzhKfbszekeykbtIQhGfQvzTsBhYSRsyvFbWfANKwcsDxFsPSbVidfrOYMlPFEVNbFCMwwmnTyRAyECfKsPyRyqaoyNWaUekFIzQvob",
		@"gUoAueUFsgIoWPZZtBOshDSiePZEcyKDqXQmeOEiwXnflOTVhHnRNTUIVqwYanTZgMinzMRktgScrHCJPCLLxszMmjUcHAIqEbXlBLiPkAv",
		@"XPJacxjCzMycURUVnvQNvbNqsyJDpSjSnBVQrtWmqKoUtEifVhgdZgDrwndVXxQnbRENzmpOKwdMIqDHZEUbiJzpHwWnfmMpqFeEowTrJgnMgPgHivDPKuKrPJZQULO",
		@"vhEEWwZEtmMdjxwOTSZKWgDCrpcYxVKMGeKLtXwVqaisUqxGgRsVnvXOmPBKDRvkNiNdwnWFyIjPovtuynzjaWyMaQdCddzJyDSyZONHSwfmLNCCsbFP",
		@"qBCXzLzMaGqmXSZgJFzDUaGlxMFnVJPXUTjDKLgyNZEEUFjgklgjaKytowTppmjkWLmesDOBARiKRaKCFeyfvRkXVPpkVwMFWpUvwVoEZFaoasGQ",
		@"PrAhDULqutUkqrEHwxjPMfWcKnPQlaUxvWjVPRuAmDDESwzJdCTEGqLLXeHvjEquBVkaYUtsoBfGwZxbVfOSbOCGZNOAyoAPKFuhc",
		@"CTHPZGilQckwcdkkMIUyIQnTemuzFBmuYMaiEmiuNiJrbMkOgCBTHkRpoqkETrVQHTfzyFsEScWdKYqXsaKTZvKUbNqGyXiexqMgQIqQYeorKADReMoysnMRybWOHpUGkmOKLFmPDImpK",
		@"whQIXnRASCNbhXkTzvznaJGZDKGipMrgIfcbovqxCSWIjqhZMsmCpHKCDPxHsPLwXcdXYSVqoXJiGdYrZxNgksVvNVgzCOjlZMVnXDFBqjrIjmSCZElaOBn",
		@"vbTGNZeXcHUVuXbFfzRVReFrZPTsKMYOkVIGvDsJGqlZYtJvadFigPkMJkHPiaRZpQZmmshQNbyqeRRuFgCdriJuSjxscjCcDQuxqpjcsfBUVIhhAbjLGcsqFU",
		@"WWTdchbjfkPobbTvmicoOQkkqzMbAepNsWunMqjQgzjFbmGworiFEQZObEYIClOCLmXCFSYEbXAwGNiwSZFHsRAEdMyorCgvrsxtVCuxitkPnVEXPGKkeAnSCHFogXZrOqHharfoUWL",
		@"AAcDzfPiiVsXKizaTMElKyiXwAxSQxnMyOHJhGQctNAappVUuwnPssgnNNGvCInSnxvgzyojJWYBFJfRAGhlfjlLwaMtLOdrbJHFTdtfbGaZhCsog",
	];
	return BrocDEUNTqtK;
}

+ (nonnull NSArray *)JTLAVCCioxlrlsd :(nonnull NSString *)kqiFwMeqWBQXphkVv {
	NSArray *QOkhNWonjTLvHo = @[
		@"AXcUFWYwGrfsQnlGOadOPBvrjGHNzOKrUXtWJUuUZiofemzQULelEaBtqQlbvounEBUDLskkzyHmrhWQPYxxdEceuJtnGdIvpPIPwIfiCsFWkfFjMNbGCQfjuRKgzKYgjFCvpLIPrgRAiNWJ",
		@"kCJQrtOAtYcxzjkrwZuffrCZoUIjeCKZkXxhRqLyeRIDDyuhIQCJbODIYAvcxzjlMwjHjGeGqdGSejkDCfBzDLNHWBVjzKbqEdWQfSAbMuwVDMeDcPxETSMcOoxChbBdnMEpxUfmoMHVOruxj",
		@"mkQisGMKTaNzIxUofmhoMcjLsqNjVacFzhSqLKGqeocCeRtLIEkalZtHzzSOFxHZXWqCwyxSiDNabDsETbchJZUCEbPUXuTnRQDpvmPecepogw",
		@"fVXkpsiGzjRZOxIsQtGdQMxCzzPClGbsrozkFEKvIaJDdFnubxvKXrOenPvTDzQFDEbDivtiDIfVAxcqvsMoEuuEEpbrgiLHJduzcAljtNOOldRdrWAeJrGatsdyfeBSpVIpCuY",
		@"LjVwwqsJdTCWNSgDwlphVkbBadOODWSoCuItjLtsBHtyyvjRMxKbdLKQxGbXUjmrtgzuERXdnRWEwHoadbVqfkKJSRVrOryhTXvIuMoNcbZVIkSPRjJHrdhUPwFXutWfogg",
		@"nujxgFWwtnjnyqAligrWMOAaUQIjLUNifTnsMWwffoSzXvFFxRAhMxltfKeFBZHKXizLmOWIxUMEyWKvtCcvHseaaoZPXAykXzbpoDidLiauhAJvOnGVXI",
		@"NOOJeLXSLHwJIZjvppvnOGNHNfbZJDtwEYmZTZYsJiMRKNOYULRwuSiTGMYflTSWhVhYHJtJiPDgCHweMNgJJKOcIvybActQTuakiXeqnGfjuBcBVFFYOHJwsvJSI",
		@"DfNfAWThOjziyoOWOdqDXnxLovlLRXNlZdYDqJinMqQVeZPXpquqmwmlKaIqENGuSEOmdRSwBVvZIrYBHJyrzuHDieMifxOTjCaheCwFiYlWnpfQtmmrbDsQKD",
		@"YDyzwTWtvImpUsbKwRiukEQSULUFZsQdQYYIlrGHIRAHBvSeDvnVdKZRvFaRMtQvUJTYlBFuuqEHYjuxjfxZppTQlWXpzofUCJCcc",
		@"DdaAhkUdAIWMoBPLAmHnGuPdQNLukdOcXLLAyNreirVENNnAaOhlGGhuItksmALrkIOYndjGZWpwUjqKpEbRbjJfRKvdnVHNblHdOCXj",
		@"QRqEoGkpWUjmDvWheOqDvCgHLKwbHNrinfopxKqVTWFZSfeZOsSaRAaaBMWfQfboBRZJJQjJVLrWWnYVdWDoZClTytVTmkrKMevrqHqOADltEDGgddkjSoeaejakIALaHFNtAwwqMF",
		@"JZxaAeXvFzmgRbxHwwRNDAkfmIKLdwisijPGnoYjgZGBPnEctylMZlZcvkRSHLzuiaMhWdGqHqIDUdxoGljrIfbJuVlfiOxDqazgolnLeINGMDcNBJEbCHNQWsHHM",
		@"eBABkVzXqlkuYrxxUrmFjzsdCbmcqhZNmDWFvuLaRHaPVHxSjZUApLsrRARtOrcXjILnRqgGzabZPaHjIMfSNgYUPNkcKmATCTaoWupLKPsABawuLVRdxKakyNr",
		@"OiQicXugHarYAqIyFOzzFnCbEdaYeWVCrLkrnZqIaJRhIhVDrecKBRVCyUCmeDPKTUWtdwijXnXIHabGunfUlMSNYvjoBSXepHEBzLvEDzzvBSkCKZejEOmXZlicvTOVcgbPCrmGcDOeuE",
	];
	return QOkhNWonjTLvHo;
}

+ (nonnull NSArray *)NBPvCQvrWHsBoR :(nonnull NSDictionary *)JdQGxGBkqMalNm :(nonnull UIImage *)fUlmIboWoyJEhOV {
	NSArray *CsIbkQRCWVJ = @[
		@"HEHRurtUgArIRbgWCgJyBuYiSJyHeNXVLMITdhsqUvKtpkhnpKyDLKAAfwXBwlfWrFAZBPIFAaoUPLghpuYhNhksWUfRoiSRLNtpdDOFvELe",
		@"aBHqebAkhSOWKJiqbrcOFkIHOpReObmHdKfKrQiZEdHdAKUzQqQRcfYWiDYmqqSZAldPcDaJdnsZIhnxxQKqzwsEHSnFytKGhybZxKNRRJDIYboecxTnUpbadqMsA",
		@"AKrbeyeKjKtYYTumSfynIuMiTxRrSUcTRPgFamkttmiNXnblvCnWtzHYATDYAXDdnVzmHChQKoryWQreUZsVPMXoYTRkUYmJYMwoAAoOQPYdsDhSxMtgXRROEeUpPsIx",
		@"SRuIqcxQbSpMqIAkoMqRcNwmCgTMAQgUQpvPsPnUzlpFNjOdZxxrELBhwgvYYXmgwSXmiUxITaWKUAVZdhgjWCLRvoqLLjucjGBmUGPqzzQwgarBiXugQo",
		@"XFOwQIeSfyUahYnmKxRtyvdReQiMqROkzDYtczQiZlVPVQsNriHfdPHKTCNyfKMFmIkwcSJqEjvnbHzztqNtxkOPRlqDbimGFxAJekBxrjeRKOObOAT",
		@"VfIGHPdqhmJleeMtRMtEPtXPjKhSChulqYqrUaDfewIIyySwQSUqftbXUBAxHmOhXwcYHndbJcZIZFrGzagBPSwcXCgefDmPsprvwCtEgIewwNZxkAodAgqygfwIapJCjMrOHrCZRfgjowVpstik",
		@"WzgRQQuIznRKhCkPUkQFLqoNeruwxBvKdVjeudmvlTEhxgkjwoDNQrKwRBbfKkujNjOJgQEeIgSJcGwnIFPvOORoQzzScEVlyNzCPOYQHZCrMiYprpnvRDvTXshBzMVDUIbssiaxxCukrETfiX",
		@"JhLeBodNvoKOlOBzNSjNCYPUOxqDdQPIbyXrUVYMeLIEmaIijugTFqMcedJgBXRPqkQPImNDZYstsEVjkBenGZnBIjizGxqnqnaBKePfsDyxVl",
		@"LBXxQNBhyNYrTQjQsCoNfwriAJJbJHflEHDYNEYKrvTgMTfVRCshCqErbZrnlywbPrFXcSsbCorTgeLllmrzjvfgyVlYdNSuwAsodLccOZ",
		@"hEfvLoAQdoUsOSPFDCsOSPgmWOWdvleVIfXgtwgQKnIAQhkJlUJciLZDpZiUsKQMaxxmYsBDEUsSOEnUQEgkLvTCOZiSeyCthFYlKbDpBGdXhouuvNgQKMsAMfWBY",
		@"ricUmKasUNrXNpfuaUxXHtqYyAnKzsWKZrixaGvoVHJDGDWycLucPoZZZihdECZWDDaMbstPUQbnXmjGmPRaBsScwjUTAanjqmPqtZcfcriSYC",
		@"cnwLEnazEZDfRpsyRPldGkEYTNbTGbSmHiOaSNTnfZpUPhKYdNOjxSMmkGQITTcaqNWFHrKpShOHAhgwptPsmmIxjVIkbHaXVwGIybBvWULrKiru",
		@"obdFZlodnPuGkFaMWeFfKoucthvTDHOrUYwcfcnvVOQcPLwnQIwHsOmbvqEuOnVDQoLNZrMHJrBHNsTMEHSLinXUKgxBDgFTOZIHGFNeIVkzyBXyRSMomiRLqKysewMDjB",
		@"ixvOGgyOcaBRqMLHgsggESDSrFxaHMJkQBGniQFPJbzKCJEMSXYuTaqRXJZYyoldyRVAslLSepIEuuFTzlgfKLhAJrPOwRMdsjYNQrzHpruwwXftIgcdzfd",
		@"jTIlueSQZuyQpSNyMjClhyMrKmNOCsqPjTbfkivPpcqApgwhAgiNiRwFoOgHJNazqoJgOdoashvDwDefFZtNvVQFFJnWKoaWwxmjSnGCkvuHp",
		@"aBHuyaZYLOqOvSukFxoMBwJFcYcDittzqJQKjqKfHAzbgrKcCEjfzwQxmbBhaLDClsWWSxRDRZJnhcCJMkQlYWJIUElNjVUNxzMytxTjgAwcTJ",
	];
	return CsIbkQRCWVJ;
}

- (nonnull UIImage *)GvtbdSxIeaRwhhpWg :(nonnull UIImage *)VHCRnUCeUtGjHMYO :(nonnull NSArray *)jMjqVUGYiPVnpq :(nonnull NSString *)CRjDDxKsCLCg {
	NSData *iYvUJMZiFYC = [@"pdGdevFJDZsKEZTYUQEnMHhoGevXpuQjXNdaDnbmYstOPCjvscWdcmVTRKdGsswqDtBcOuWsVqOASxxUTGYTrOSIfcQDSGXOcFoHCLEUpUZIlZUwtDbCkqEzIHlSxdLdyZdrbGcDIXxHg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eNtgvmLLuKAzMl = [UIImage imageWithData:iYvUJMZiFYC];
	eNtgvmLLuKAzMl = [UIImage imageNamed:@"sDztqbaThqYbwpfJbCzcQXbIEFUOKUXIpfsgbKMRUrSjfLVSLXKDapXxoFVCAwBwHzwwePCYQEmRHCZaRJAzbhpYWqDaNYnxdzNi"];
	return eNtgvmLLuKAzMl;
}

+ (UIImage *)sd_imageWithData:(NSData *)data {
    UIImage *image;
    NSString *imageContentType = [NSData sd_contentTypeForImageData:data];
    if ([imageContentType isEqualToString:@"image/gif"]) {
        image = [UIImage sd_animatedGIFWithData:data];
    }
#ifdef SD_WEBP
    else if ([imageContentType isEqualToString:@"image/webp"])
    {
        image = [UIImage sd_imageWithWebPData:data];
    }
#endif
    else {
        image = [[UIImage alloc] initWithData:data];
        UIImageOrientation orientation = [self sd_imageOrientationFromImageData:data];
        if (orientation != UIImageOrientationUp) {
            image = [UIImage imageWithCGImage:image.CGImage
                                        scale:image.scale
                                  orientation:orientation];
        }
    }


    return image;
}


+(UIImageOrientation)sd_imageOrientationFromImageData:(NSData *)imageData {
    UIImageOrientation result = UIImageOrientationUp;
    CGImageSourceRef imageSource = CGImageSourceCreateWithData((__bridge CFDataRef)imageData, NULL);
    if (imageSource) {
        CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);
        if (properties) {
            CFTypeRef val;
            int exifOrientation;
            val = CFDictionaryGetValue(properties, kCGImagePropertyOrientation);
            if (val) {
                CFNumberGetValue(val, kCFNumberIntType, &exifOrientation);
                result = [self sd_exifOrientationToiOSOrientation:exifOrientation];
            } // else - if it's not set it remains at up
            CFRelease((CFTypeRef) properties);
        } else {
            //DDLog(@"NO PROPERTIES, FAIL");
        }
        CFRelease(imageSource);
    }
    return result;
}

#pragma mark EXIF orientation tag converter
// Convert an EXIF image orientation to an iOS one.
// reference see here: http://sylvana.net/jpegcrop/exif_orientation.html
+ (UIImageOrientation) sd_exifOrientationToiOSOrientation:(int)exifOrientation {
    UIImageOrientation orientation = UIImageOrientationUp;
    switch (exifOrientation) {
        case 1:
            orientation = UIImageOrientationUp;
            break;

        case 3:
            orientation = UIImageOrientationDown;
            break;

        case 8:
            orientation = UIImageOrientationLeft;
            break;

        case 6:
            orientation = UIImageOrientationRight;
            break;

        case 2:
            orientation = UIImageOrientationUpMirrored;
            break;

        case 4:
            orientation = UIImageOrientationDownMirrored;
            break;

        case 5:
            orientation = UIImageOrientationLeftMirrored;
            break;

        case 7:
            orientation = UIImageOrientationRightMirrored;
            break;
        default:
            break;
    }
    return orientation;
}



@end
