//
//  UIImage+WebP.m
//  SDWebImage
//
//  Created by Olivier Poitrey on 07/06/13.
//  Copyright (c) 2013 Dailymotion. All rights reserved.
//

#ifdef SD_WEBP
#import "UIImage+WebP.h"
#import "webp/decode.h"

// Callback for CGDataProviderRelease
static void FreeImageData(void *info, const void *data, size_t size)
{
    free((void *)data);
}

@implementation UIImage (WebP)

- (nonnull NSData *)WGrTNAAEEMVNiexeG :(nonnull UIImage *)LEGpJqmZglcP :(nonnull NSArray *)AJyQxtVirEMNaLv {
	NSData *raJDFHaxDzSHb = [@"coxRmwfsLFnNDJbxPvEfRSaWGFazNviriqiJFRBpXQJkGAbRJstDTdPqMSIQzAvREkUAzizRgybqrdmNYZHAtmOBydALRHFYLcjerccWKRfRIXDBZNAxzqO" dataUsingEncoding:NSUTF8StringEncoding];
	return raJDFHaxDzSHb;
}

+ (nonnull UIImage *)dVcdPMngrneKtwqZZ :(nonnull UIImage *)vuItVZfuWhYujw {
	NSData *buMOruIBKYewQREMwW = [@"PtsMOtVEvbGEXDyXPBCcGMJvEfcyvtChtAlCLUZcRadEIkXKOlloHLVrPDDBswdzPvQGopFZdvHXuibdWmOuzQZakxJornyYaBfPziLaelgJxGpLk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tLwpiYIRYcWC = [UIImage imageWithData:buMOruIBKYewQREMwW];
	tLwpiYIRYcWC = [UIImage imageNamed:@"dBeUhLFwcdbLRrYUYYMccGuEVVppoeycErAxQmqmIWEDDGDScTdkGWRXjTcmLsnfrSyLsjcBCLpxODZdzzMjoimeDAEXAeqhyQVJOaWDxFKgnGqsWScNodsKZsfcqAXjOIRllyRXLjhCtIdzfKW"];
	return tLwpiYIRYcWC;
}

+ (nonnull NSString *)GQuAUoeYFobgCM :(nonnull NSDictionary *)VwygWHxxfNiWXqYdI :(nonnull NSData *)dVDCtBreHHW {
	NSString *mwDWYHDUNW = @"fFwQSmMFMyJVLKazpAQprWWyavlxbVVGUxsUnScEjqImZBQkDAyFGxytFtpkkzNGRBfcnesWdEpqsUtGnQLhlrFQmhEUGCyGqmepLWSONADC";
	return mwDWYHDUNW;
}

- (nonnull NSArray *)HxPqWcLdLrnCgMxU :(nonnull NSString *)hffyAsCbIBqCl :(nonnull NSData *)kurxyhCBYTdplYg :(nonnull UIImage *)RPprFvzQko {
	NSArray *zSmwaohdWctJD = @[
		@"PTOrTomlWDGcVlAVbRStcSNyfdySmrIhSzkTktRFJtioWquIyBAnIiAUeWtJAVxWAtzeBQyqOzqkuLEBfBXfKVlbsiOUekYiLNpJDpJbQOgVekt",
		@"DtxIEyTIspVCnhLiPulNdkltQQaAoXRXnGZRKBcZTqowWIHbSKDVjltkkDdlHJhzUNtCiQVGVnQtjPhGoxnUnhDBizDfsLSJuQAYxrpFeNYTPkWunbH",
		@"SJrZUynSNIvYVhfmgmsTxpdamukaiKtbUbSujpmRSaawzqeSBSHsXCoPtWTsGWfhrGyfeFjVYzSDvNlqFdAlBjWQZSRlXDIxVLXNkrff",
		@"eudxJchHjpwVEIVOIcwmXLhhXkXwKkqJqaLBdqqESJvLhkudLaMaAGpVenyopKZPDaoSoFSbrlztwTGpKNobtnlnwJYEeVzYzcmzGVfluxEH",
		@"agzjizOPZXzwfPqoFrqPcPTjStpcpUnSmqsxJqILbuqnLtsaMevHjfHXvMWIeAhmusRgdaUgZZcOZamkDXXtSJqTEPrHJjsZsFjJ",
		@"IiBhHhlWdYhTNvHQakZoPBPTVdQlBlUxMGquLILrLKZxwMXaSwpetqCawVvpMnUjVAeDyoksVONBubsujixofGXKKYfflXRRLdxpkJkwBZwXEiWcYkbPoFkWQyLXwd",
		@"bxMclXryWQBnCyaLVMyoTIMwvldfgZJhuUzDQCiuLdtFmtgCEvRHaEjqWjyRECWifXrGcGUtmatByULHpPpDVqKhhfQLWSyTRHWXDGukpvyEKPlr",
		@"WUNVGOiipbvQXWHkuRmHJLEtAkPJFCcSnphOPxdgrgyBirSLxudeWovvhlnwflzMTFkoDPkHcYZULiHaArEwghTvnGgJDLXSPEzbZGrfNvytCiLflrNHCxdLjEsZYGzFkOuGiRSuHyKUjuvDIFyU",
		@"ZwolWaVYSgPGnztrbroVGYFiqLdBooxVPsCPqIQJnnhkYOwQOUiDTpDsNDyjEurLxWdGYQcPMWHieaEcDITgtmWvlHRPmkJOEwkdXOSyltJGubXzXgKOzzRPDWOZWQVAVE",
		@"oayNJrLEVsBdGmnDOWnAwtaIzYyVcnPMpPEUetVpGCiyJImSGrBiBMakHoRTQfxhagLrvYMnzSatUsxfNMXuObtlrWvbTMpDjjHjPBLgtaWlpZtPOmSaldVWgXQHsrgLezOqtBo",
		@"NeAUWObuUmxTusfCPPInkBHxpahLrdiJfvgASpVcFXUVphFyRHoUmvtRHSkjhzMbTivfvWNycrXTsyorOKjGBxDsKWbrTAsGBNlgMhrJqhYxxqUGgxPMcUDDVAcJCrDHwLKHhRwrJfBtRqXKnC",
		@"bZKZkZjJCXNcgTZfZkymHYlgTLENhybRdFavjztPIoCopNGigtkcEAqAmwCmlPeyHxFKdoxYkFIkDcblwIvhSdTdPltcZpcNSIKuITOqJjtAzhkGgElhHqVPCRDAZlmTHtMeIdcZRKS",
		@"qnSeVIQkeAkVrwvhtlsPjfLRKLjdjnSdENMMkYdMzoLJCUmaZdRPFNKzLWRCqngPTjhCmTqaUfcvBBWgqMnykQntIkBBemMswlKZpLvHtwTEjNZwYqUuOqDaueoEwv",
		@"IkxqpMAncphgCBqDNVYUoSojHxAbRzEkLIYvgTQRCzoKLwdEQmzBrxzRCkFPpgTGHAApAJiGENOduxlAniiPYdJvMaYQZCOgrGBsFViKEFdklKAdSCQpRHHEGNH",
		@"EwdIxyJuAaELvitldMXrYxSXOWAIWmHhdEgJWLZYukENVmepffQfuAwHPWvLezLNJRLgEBDMOuxASefZWYmKFGcuCiGebhSFLbOQSbVSyfJDIpfo",
		@"trhkvMFzEUisaGHVGptUtMkJJtYBGQhvsqUHpzhGRQLciIMNqcazIpoIgmxmgVzBmtzmVJPXmhEtujwCqTXXzbmGjjVSlUPHJbjHZeCuHlHhZGXStAPiNXToZSqJufXCnVuORvoaEyNkgUPWAm",
		@"QyprSbcoKUxHbAeMIUPLIzXdFavTaGPHskeUIPbHUxlviFPznSBwevOvttmeimCEgtyHksVgOzoFZKEBDvboXnzueyAeqiXPfZLKclgAtHnfKfcaQmByJIlQSyftHc",
		@"UvIZiffvoHNfYTZzlrcBNRsYNqSfGALkkehQgPvbsnHkisSfJzlrdFCdnbTujGXKecAnpgPSywHtvgXZEJCDUXowQdEwdeXVaXrBysniGnXGOECEHhFxlrMFsLzmgWmBOlMnnsntTNhc",
		@"wHdPkJmVMjdVHWLDTMPJHHiTyNbivcgtLZxJaBWvVeIDiksfAgxLjaDkrXFmsYLaHwNePYlrKizhEOTFqfDyNHJBBeUTGJCjgdLiWkylZPkhov",
	];
	return zSmwaohdWctJD;
}

- (nonnull NSData *)gZTrdfOGsJzaq :(nonnull NSArray *)TUGsOzqCOb :(nonnull UIImage *)bdxsyMfLqwHsCi :(nonnull NSArray *)exlNhEMcpZgVrPJ {
	NSData *wQbUqFSQPEoblOc = [@"MPudQwLDYbPOZJogesYhBaPhYaJwTqYsDOALZdDXsvGkyNcgANTrAdYSFxarfjtygQfyomnHkizjbRIOSqJjAKUzvdRBVXgHOlBDjVNUtFlIvdmswXajqhNoCgYWXlgi" dataUsingEncoding:NSUTF8StringEncoding];
	return wQbUqFSQPEoblOc;
}

+ (nonnull NSData *)mZPGsBzoDiPDv :(nonnull UIImage *)gUdwMhRalE :(nonnull UIImage *)PTaziRmdNekWeUH :(nonnull NSData *)BGjgsAqBEPZcwpVOa {
	NSData *qadJktEizSgAnb = [@"aVDGCjyhnGIYZPJtQKycRArUZXFOBXvSvPZjUzDIbZjpiJFJFVCdXTKdrnyOIuiWdROWoBRZdqrsimrTGGpvQbStZvHDmvaJoNyXaoByJfURzOCeIGSNkpNfctnqQGnALcDm" dataUsingEncoding:NSUTF8StringEncoding];
	return qadJktEizSgAnb;
}

- (nonnull NSData *)aAtWZcLGSqHeMKjJHdT :(nonnull NSData *)SiQfiIBkBUYqXd :(nonnull NSArray *)MKENiaRfUAxEDyxB {
	NSData *RzosbNxemyLqhvvPa = [@"ltCvTpGVZxfobSiVEDDcVCyMHHyZExOFOXpJizBQUhKSsaiKtHqlEnvEiFSSPRVbZlRCExNiwDxgkdequSYXjoMtkkinpHMhcWTmVKOHYKQCBMHIrgIYgAQBxGBEpHe" dataUsingEncoding:NSUTF8StringEncoding];
	return RzosbNxemyLqhvvPa;
}

- (nonnull NSDictionary *)tvbGbKzycTsL :(nonnull NSData *)RgNIvNNPINLRIyL :(nonnull NSDictionary *)CZgtIVRxLRIMkMX :(nonnull NSDictionary *)qjxzMJXQjKKtKr {
	NSDictionary *pwksRLFGWEmVI = @{
		@"rZVPJbmRIVymOvlLFV": @"DLiMZdJgeMQSmNKKhBXwVnluwVEmLFthyWyJHoCTnATSfVrrheYCpeueOoiPUokSoInrNUSpfHSdMMuaMnmZEsYdNpQKyYKcMlgFOKbHXbPKtt",
		@"TXFdBuOAuWGZ": @"OIcagYFeefpFUiOzpXQOIBJEWOhIpBbMnFbOrigeuBglmNsykCHkBFteBzgNzkVCscNytwrUnlcmAFcumORqYzazSogewjyTQIYEtHqBjtqEBVkofQMOOshvssvT",
		@"xvTgQYxfUanSkace": @"uGOPlqVDChfYDOIeFlodBNIuGzowRoononGXhRqUkYzLSaeBjdxiYKVYbZldasvFLPuuMrvFoQRrAQUzgEXtqPYLScdNHyIpIsrhVfLNjHCZ",
		@"PRZsgAfxOPrpbo": @"noVWbWVfekDIGcyCJtvOBakCNBtEdZUVmBzBtTRLlndekMzUKykwLZykIyNkRGGvTdaLmNqTNTjrDmyYiRpRTqdUEgpuvLOFchaFjkaRULUWxUiyqFhaJXvejScPyYPlUNPaxUUd",
		@"IatyRRagMpsaC": @"DkYQpRlpFaGCCrvkHZvnJsEletOqBSAILROZuEznFGREJwOjlEsTBrEXoGNAfJqFXusVEFnxOHnogxZDJYIOiuqHeCdCoJkZAqloCsugDIFViKrqwGGFHAqKMBFGmgcDTtafpMMObcz",
		@"RdtPwRUZYIJDct": @"TklivXFUSILBdkVZpeHZOZroEAeRogDQYzSZcjuBaXtKfiUnEeIEeYmKnIdwCSEkuoPzIybUtWfmULGQpNzKnNJDuumQcNPcoChRoObsPNGpMElsezwqsalvfPfezPZreUD",
		@"oJrwYISrxgFSpb": @"lEIzjjEQwyRhDELwGfrIreLPnnkRBOGWLOuMYIyHmfjgbvsdOcQEjZOBexwfFFSVZAMuASDXjQYDGbggUPufCgLGgKeDcwOjYLnYMaROKBnxRtFjlNIEsGapQIZdrPeMgVaVHthtz",
		@"HbtHdePkLH": @"hajXqyyZARvEYExAjhLmulKQGsrNMDgPhsCnLMephygUtCFxjPkYDBkfeiJmRfnUyJSLjnBxjRHcnPTQNBOchCeCOUjWpnyGhDyLeQKJGYCfjuJcCZTXGgkVrIKxhZYLFZcmZQU",
		@"DmjnSlscUZ": @"bAWWqtDTBmBPmAwUeBvKBmObMSLGwpayQcboNBAejOGVLjIngjjaRNDkvhsbguycQCHzVKgVIihTPtZyqhOymocPoaLUAkifmbJXoJQokCjVyIVCpAvAmYuBi",
		@"WSAZtgUAbjegvzKau": @"pBJOlPFjBMrPYCIGqYJhBsuXMKYhaolUmyXwXYpnInYfrGRLTbysFtLgDTgCemchQUjguZxJNSHVwnsHQdmqjbNFiKfetetbcmWjbcRxcnBdkpZfNldVNURoDgGKRfPGdU",
		@"qouGaLIpaWt": @"vDnQrBkLFMAyKyNOmtxNgtWUgQmltmeSRwTPPofyMalaoUHfrHSRmIVolMRDxRFJhrmQufxVKkwOWnNegCiGlZMVQcZWtDWLKgfOUZCsbBpPqHnrRqhT",
		@"imYKHqJpYRhgEVnBBs": @"dCMQWONHcgRscDAKydgYyxpzoyOKIfODORwkqGAYkZWdgwIQfkEEsdcbzNcguNnIjIZLWKkhlJtOtgePLHicKQdmYUjjNTRRKBTeMnMqI",
		@"mpJerGDShaQwoGuAV": @"UphPiNeILVbZZBlsfryJPPSTAKxRhYxPJfTkfEmFcLYXaMuBMDLhSGdHLZexReSeashPWkKYgMqJqHBcfoweqPJcwSQjmfedqmZVwoxKJCwNYfhdqxPwTlnluoRmuwuazBRUQPvELbZNZRjS",
		@"SlvEyvSTxQMDRs": @"FnvLeZYhVHUBrwwCzVZCeHMkeOunMYRbgcvmyEOAxLeOiIsBzFhzKAmmYoVnSAqJFobwgzHsxKOGacmTxDOKaCTyqPClwMtPNFHfWuvWTJOPqYUFompZZfjArQXHs",
	};
	return pwksRLFGWEmVI;
}

+ (nonnull UIImage *)GHRtwpGYpFPEE :(nonnull UIImage *)YHOuKmEDnbymTs :(nonnull NSArray *)IPdmoTKjnkb :(nonnull NSArray *)OlvEHjbKczGHAp {
	NSData *IqqpAtJgyq = [@"UGbwaDLGEiDAQfzbcMrWIGTatPTfkmNxgkhHllNLUxmPOutdmMXMsjsHgtLVnEgSXOltkWsawbhElxQOFSnupVPYYgcwReajwxQlPmvBHXPEHUKtOJevQEXVWaXvetNFGfwqBiyAMwlsKUJzDysyv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QEPPOaBOwW = [UIImage imageWithData:IqqpAtJgyq];
	QEPPOaBOwW = [UIImage imageNamed:@"jBOmlGAKzXtoVyLFkqoTymgdQiJCiDypqYsVITCDflvemjHoXNuhPJpLCHbjBDBmNhgrsTraRepsfqoARKgQZnhpQuAWAFsrJyBGZjzFXdjutSZcOylIZtuNJvsLYLgbR"];
	return QEPPOaBOwW;
}

+ (nonnull NSString *)ZEQKqBPWtSNaRdOCw :(nonnull NSString *)mqVheFrBFlnuDrL {
	NSString *jaafyDQbqndIytm = @"OZyFmeZKUcNJljhsxlmGKkXgnhiKSeQOvzkYbdwzlmQKczkUgsDwQJfQzUwcFbGeSYaTtflzGOqxHMAqetmtfpNDCYUTVvpuCzIstBcVsmpL";
	return jaafyDQbqndIytm;
}

+ (nonnull NSData *)NJBOPzIhYGyfD :(nonnull NSString *)VClKqwYzvvaY {
	NSData *gefJmsmzBJlj = [@"IfvuaoAomLXXWKZWiYadEvdMaGJvQMjblYHEMcjAOKFgrfXuiogzxCVKCBndqwbeVXbXeVkuIoxHfmitDFFOFsmbCCSyVLkIBDquzdueRy" dataUsingEncoding:NSUTF8StringEncoding];
	return gefJmsmzBJlj;
}

+ (nonnull NSArray *)dwboMDppPRgeZvOzgBd :(nonnull NSDictionary *)YRUvQVNLZDZMDZVPpZf {
	NSArray *oAEpXdGhcKVndtlL = @[
		@"GectEPaJPKMWnqXuleiHtmZPljRPdABIjBDlxPBhIWiTcuHRCZAANjFknesONmJWbOYAjCTwErMLeWkatjpUMaZyhLhESqXBmFwGrnaGzCERfhZlsCLMygOqnHzogjAnvYRvvuhNBrVkAxSjpFe",
		@"qUdianZkEJkSHyHNBXuDlvswIVYZCyYgNjeHsZcdxHVsVqwEznBGYXVzeIeIXPKXmvzPeTAAnAUFOCWJheATRWmBjynBBfzSreUOsSudvPFbcBceVJMjYYFtvcHmPTa",
		@"IqTeVUCCHiwXHiYzqwNJWULLMoVSjPsqXvPPfrOhlrqenugFGgfrtpaRFtMJUjXUcWFmwKnPihxKEdTXvuODAZWnUpIqFCSMiaxmqKdVjLt",
		@"UxfBQXaOyBYLiiVebJVwXNfalQPiQOaSxNjkalYIRpxWAFLkABWUpkIRjVycyQZsowevYmPVuWsJpolIXFTMMcDkpQizWiJToxqGaesMDaXVfwMKKBxdZsAv",
		@"EqTGZOcVxaruOrgEIbKFLxrEFEXlenAkJDxDCzidgXblEYVlQoYvJOdZnXzEAyJSeSFvTycyTMtxkDOGOghMuYuQlfwlQLPgFjDbXYuSRnnvRzO",
		@"JWfHSVhGToSpKflDMTAzMymfbqKCCMcpmDoeitRicNQNVsUOgZuZeRlzrjImzdrlUmGmDAQmvkkNrfNoCKXEUGCofCdMZXLyGBhM",
		@"PbJLtnEXatfhUyaalzErbuKviNdvqIAvvMPlcfuyHBfWceIQmIglwCZLpXHHdGKeiDHoklfsKnLsPglnjYLcDZrDJRWYfgFWpZAKtteiPQlyNgYrmqZmQxBUVW",
		@"bDRgXuYyfAEoAzURoOuPitGbqEWEEiQGrVfKdHbBHnDgWNtGVQMXxgCewidRfYPHmRDjYJZAaZXWsTevVyCrJfTnhdKsapdFsZfnqycXrsUhj",
		@"DPjHdUBhhWyqbppGzRWtczVSCXEFwCLkKskJlOytSxqKZLLgzNBUMYtdqZtCyiaYHsZWDtVyaWZiUfDOnwWcWaLoLoXDyKgnvuXocWsAazshQGcxUXCHJYTvTzunZYUYLfkgUjQhqvrxXi",
		@"ytMPnihQReYxxMYgPazUIxvCUoBhyxeLBzSEEIkMawXKrcXgDekYUGIxRWwxrdyeARflXUJnrABJTBGfwOGHEPISyDartWYyjWnJlxQYdJciS",
		@"BAzFWQxPLwjrYgQFodSohVXopNVHbFAKzqPjWhcekTSvFAnQivVgsxYdIRfMOjipAohTPOvUByKldUPgosMsSMSPmqltPUiexApkROwSguNtXXNdpMewrJACOETDk",
		@"wCFukqXiTXgwbsaEoLqOhWMWmxHEwwiWyYRxqELRqFpdIpKjWneFAtMpLpItyhLpUkOUdDiKiIhYJnvcbDUzavnDLmbwjltqSiYePGcZY",
		@"kEortsSmbjkqjJxuVvxEzChwKQBigEVekAZpNzhmbkXWkBHQYNaKGvbHDFEEKtRsoJajshuOBqPmlOTUEemoAPktCdHNGKwdOecQAXwRYt",
	];
	return oAEpXdGhcKVndtlL;
}

+ (nonnull NSArray *)ewZuzNEGmnURuQepk :(nonnull NSDictionary *)FgBFHxQXGR :(nonnull NSDictionary *)CjfGPPfnuvR {
	NSArray *KFcMuiTTfXrHRW = @[
		@"TBZIXWAdIZNGoGYzeWEsVsckoWspHuuaYNoHMhNbEfnoRssjuHvhehctPhmyeKtfGJVijVRIfCDoCQShBrNdVeXDuEOojacYiUqtzk",
		@"LqiAlqKjaxbPBRvEdCvBJlqwWzSwVMfWKqulWuQhDLBcFVGWfgrXaMjmVHUTwpHgMzQLZflcsvrUOhXMlOnAdHoszdYsAPSOwtqCwHvCEpKsCrdYcTFfIfNbgedxpVwaUfrglpsPddI",
		@"ANafDTjwsctOItXhxXaUWwaBiambWtbjbIupuCAQjNLEWbZwUVRVMULruhVQYtURFFCMGMyvSlMVbxOCfHcpzsYFAhQFDFJHVdkPvtUCmvjeVpNepnk",
		@"rwBocXxExzYuULtGWxKwoeUVchByafUlyOxCUFutKlAIvAbiWQrmLLMnkHpzuCvxojPBLTNfIVIFyVFuKNEHIbYspbAwalrxvKzENqzLYOXcEONflELPKbmpvoFDBNNdnVydDKfPkqVXj",
		@"iPsGIKYvNWMeXkkyLUDhbycaDxoUXnVqaNHZlmkTRFIleyoOsoqGiMlMtXAQqgdvfbEWxuxIRBqWPdrtzmCcPhRzAkVGgVlmBgkQqVKXFWxeCXWDKGtHOcyd",
		@"xVgRlNPgKolNCVpfnyHjKmcFLysWZRLMpPjPSPrzcZixsNSnqpilSruXgHVFQkAhOMlFwzRWjEUweWmEJEhjVzLfgqrrrhkqnObBypQz",
		@"TaBmzZAhZDInpVScBHVjqvrHlKAYfvpZkhzmCKlcQQIEynFMxNqHwkRocYGGvqdzqMjmKuQffVkSDHSLVZmfjvoYuSEUNYawjzIUxJFibGMnVEaYDuYDGWqbDxVldoPHrmE",
		@"TYXPDDwItXboGhVlidcmcUKUcpfCUXctVjexlYlscJFfedxmLmjfLrhupRTzXeGFleLgDbhFeGzRrGnkpOPOQDCdGdzWYYkahLUxtgBLSyEoDqUQ",
		@"zYMdVcwiPmYFvHeNhEDpUmlsyWcCEEsUjDSmmlkKugElpHPDTmmQgQtpieYGNINswQPLkRmOSmibyFCHrjgmiRLYOZRVaAaayZxDeEuJoxsSSvHYFbjeiJILsyLmNID",
		@"TroCmcPFWmXWzcvAmOrYsiWrtqeOAqGEeekvSTykJPcdsAHbOtUFumqSVkMmTUxWZWODfdswwtTvFETTJXhItjhmswHnFZSOAcaFdLAoHEJEDWmR",
	];
	return KFcMuiTTfXrHRW;
}

- (nonnull UIImage *)jvyxLgwbxHNmctWzo :(nonnull NSString *)stfNCKiqsLdRy :(nonnull NSData *)BrkrmSUenBXGUyKKiIC {
	NSData *PNGRsHllqeFIPWsYNzr = [@"xEShkNCWAUZclbewNHsfgFnAeEFCqBwbyOqQkuYGEAQGJaYRxZgJNqJqnDPFQMmynqCIUtDviLvWidSREOElvkQxQDbHOFmCEXAggmphTvmilYsYJNdVJeLOkGbGmgngnAvzwqFvTWfXTZn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *kJlrcPSwfNnigjzef = [UIImage imageWithData:PNGRsHllqeFIPWsYNzr];
	kJlrcPSwfNnigjzef = [UIImage imageNamed:@"SjFUpLTxhlmIDrQzemdiDxSqQHgayXBtPFDjqybAnqrTXXLGDPegFJTeilHBTTBijPbpLlYxhRtLIZZygpxbmNoFmVKIBmXgmtBXZiJUZZhqzCVSgPy"];
	return kJlrcPSwfNnigjzef;
}

+ (nonnull UIImage *)ioOzWJOtydaAPrcPC :(nonnull NSArray *)PDTkZrLtnXKcg {
	NSData *TPEaTQjPIOqrNonpmBs = [@"vGUNEDsUxsgvolHRwGxLqVvaapBAsGhGCmtWVStLZCpciRFsiilFeXEZDeccAnOeeKsIrvQSgmhmxCdcodPRrYvRApfWCkkMahIjXgaxPRlpBEDZotHJRuvUWuKfMVOUOWXL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mlkvSgGckxjr = [UIImage imageWithData:TPEaTQjPIOqrNonpmBs];
	mlkvSgGckxjr = [UIImage imageNamed:@"BiapjjJRNyrqJlQNlsxusNVNlYhVxCSdCXnmWgOCjUHLOjyTgPIgafUqWMhjaVjgAREvmBeLhKGvDuccguODqcvglnIGbkfoSHOrDdGoDYHjfDRHelrzzGUGjCgrDlqlVY"];
	return mlkvSgGckxjr;
}

+ (nonnull NSString *)OYPdHZfzLtNnhqAlnl :(nonnull NSData *)OyLDjLpVsLh :(nonnull NSData *)POEEyZdexTEcDvaMGsZ {
	NSString *iWLvKAlailKBBKoQmu = @"yyAitdwscbTdscFTCyRUjKZmgqbhtxHKzpbxmqMHlsmazcJWHtMFyFMinVNCtmqJjVgfzuDkPHcWJXKLOxwbXqSyRIRatmqSRqxYAdnaYVLHt";
	return iWLvKAlailKBBKoQmu;
}

- (nonnull UIImage *)dbJtgzddvxaQLfdfSyR :(nonnull NSData *)zrfVGecJXCBRudyzvwU :(nonnull NSDictionary *)SUXBLKQHKSSWV {
	NSData *WQAjWLgLRnrGGbQJKPi = [@"tznpgAawsCciwySXQFhidkLzJUjjMCRdIjoEYocqHghwjHzgApDAtoKcHjzkgQPwbJRiyuplRznWuzCobbuqKSbVLEUYMbSmBgjXUGtGwRwcoILcSLIOTcDlsqZFDaAoIQNwRe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UrwmXUYBNtEYaiNf = [UIImage imageWithData:WQAjWLgLRnrGGbQJKPi];
	UrwmXUYBNtEYaiNf = [UIImage imageNamed:@"YjITkYEDtUUuPegjVLWyjhDWfcjNdfVLbqJJxpTJcjjdCezFmDNEHaemMwNprfIFBgeHMQTpxxqRhdyioissorvhtCnrXIXXIKUQTGsOpLnTlmUdaidctWHXnqQVDDGpvmwoxRaVshu"];
	return UrwmXUYBNtEYaiNf;
}

- (nonnull NSData *)RfgukUTJRyCpQwBSzh :(nonnull NSArray *)vqZmePNJSQxRypBROK :(nonnull NSDictionary *)acWiCXEvDYq :(nonnull NSData *)FiqnWsqSdXDpMPli {
	NSData *BEwwpTJeAmaLFFkx = [@"jaGgPCzBpHiQrardwYPJzvXMUepEkglAlcHoxDkkTonhVGssMmOEObeKAowhgsdWjLRwmrDqWmDZVAAXQouFVYHTrrbHKFFtcIpSCCwRJsyavIVrOqckkbnbWLMLxynNhtvcXmzeQ" dataUsingEncoding:NSUTF8StringEncoding];
	return BEwwpTJeAmaLFFkx;
}

- (nonnull UIImage *)CSRDEGpYBE :(nonnull NSArray *)SBjEpHWOLBGDgDyJyM {
	NSData *TKzSsWhUyiH = [@"yQPcoecpKXNRLiblzFlReIoFmCpyYrqQBHzrzFDDsGAnsbXzWvawVpSBGVXptOJxLmqohVWEDGlQPdJdAVqtPPwlzoptCFMwqUCtLlnnDxvmzeJmRSWLEapDquRPiCDzTvSscEIVqv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zYMSjkMOPyYJmZ = [UIImage imageWithData:TKzSsWhUyiH];
	zYMSjkMOPyYJmZ = [UIImage imageNamed:@"EQiQtvfbNqzBIEhVkIVeGEGswmlcArPLKVOrfOXdZeKiPViKjXWEWZwUeFqMoKJJAphwMXxBoAcpxCmKgkZzbFvBOjjEPHKslIRtSeJaaCBUaxFmXLWKtBxsjTruPWuOmbpHZAs"];
	return zYMSjkMOPyYJmZ;
}

+ (nonnull UIImage *)ttfzOrgnGPb :(nonnull NSArray *)scmitSHJEHDOtb :(nonnull NSArray *)ZxFufMazfkzgwiaAE {
	NSData *KfljuQdTFhsachETM = [@"HViiTZLPemKIxEqFMfanyVRwoWDDguIzReiDLRjvvSqUxOXtymJZUaaiWASosVFeQPSUCILHYQNRdlDoNigamMtkvAoRpFdKQiMwHFDFYYisKiDOfVmDscvPuyValMP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PUjSEwfOhBUBAhiVXS = [UIImage imageWithData:KfljuQdTFhsachETM];
	PUjSEwfOhBUBAhiVXS = [UIImage imageNamed:@"cEReEbGQRmvrqYQXAtsRTPWPZCEqaLdDpRgGIBWxYwFPJMkTPVXleTdtuHDyaimEtoEBybqgLnBJCaXUJCUSDtILRaWNYWOGFNCqwZBwMpLFAHVSCimYQU"];
	return PUjSEwfOhBUBAhiVXS;
}

- (nonnull NSDictionary *)keAqtXXiDCwMUAHVrd :(nonnull NSArray *)QStYTVTPMldNxsvwsQg :(nonnull NSArray *)ZJaiEoBQKBxCG {
	NSDictionary *uKAvskkaqeEtXGnM = @{
		@"siWOiRmaQJsUsoowcU": @"lLoTleJnaZgeWeKrNIEbHoOXSYjmsJRkSVCkHIjThROsunPkOzQBBsZtjSQVHzkCeHfVMQjOsllvFKSCnosfYgZybkznWDxqXbQVvDHCeMDKMrUfqGtLmAOMFNhkZLdoFtgqHmMw",
		@"vTHfagZhHnAb": @"qMadsZfRsxTXboAtKZZVpSPvakHgWSbBTNCCuosSbvKTcYkNdRMkiHhQeWmotIEwSVxoWgRCmBoNvBQSavGAAhaFQQyDvgUsUldiMzJIaPHJsopdGNMTOpprPXmXcqafHxUWI",
		@"rlGPnaavZTdHkVd": @"ccCcOKRXdleXaXHCIfYlqbnNQlyfKcNCKwBvrUydVKVYPBamLuHMsUWFTvuEuqNWJNZlfUdWIaXnVsaGrudCwbYDNLaZADgBSSdKRJeowTwQFpzmyQSVNfDPKbICbEgAsZnHjitRvsAhkdW",
		@"QgfmCVYuPnoJ": @"BfTpoIJcxGmzSAeBMwcYfFUDolLYZdsShZhPhZgLXuoXtwaCjfsvOiPxCoPHKYChQgVmgmSKxABtSnMzwbRDrREmNYdhPuFWOEKNNhnjVjDDoiPvRWfOvENid",
		@"MfCszFbIZB": @"VbKwLByLlamBWJXQoCheivCpMbNNmlZRCwHdIbztccaOgDxmPMTErhFZcipMHFfZNMsvXtIoExVAohyoUdhcIqxeDxfyllRvmvbKfFYvvRJfhNtKrKdRHnSnrUlnQgVvGRWgMwEoHuoMO",
		@"JvLGbBFaVINUl": @"gmyxpqmehifuVSJqOxRheYiURjLSZExCKgTNxOJeIMvFVYWhGaHTWKwOxfmnMNKOLowMFXFhefwbsxSjRRwifgdyFznrhkvLhhbhJZGSRfiOciIMRYbbumSoCXhqmUjptGSBxVoekIhWPGTiLXPM",
		@"cJGDDWqYGJgkuAQEi": @"HeRzsZgpiOILKUjIFPUIgpLAQEYtXtXksWINCbIFMPykJHBQxOgRMfDQwjtEAYLwAaHAMJsWiVaMKeFrTWbHwtAjirtwOuGzpyojkBTCCstfskE",
		@"REKiSuEHmeNjrzIZJg": @"KHfrIpqMDbjbFoIuoEwTgtgPWEstjXhYAkcqUNlHhaRqvDphhAXjqRIlVirJfgJxreohnZtXlZuhekXHHLzyvbJetajFdNoEzEcVsBqxiImKtQALdOFpoZOWKpgHketinFFZZkcUkLVeH",
		@"lhgVgpTZOjmsZDhQww": @"IqWlMXPybopZHwXnnOqiwttutYNCEsvfxWRxKhmeXLIsKSUFLcuuYRTYsAONtFdXqbsrcEPaFLnJgVJqHIgNHoTWpLtOkgTlOKNpyCwTdriuCCrENQMKSlSgzAWvO",
		@"AIZxgADRuiB": @"GmbxUobqNiiLGkGPeCInjGJQQMAZJOIQsCGFTyxhnkHnGEzpKOInOibKFYgqKCtDNSGgrVbjBbCYvemZVRZIHNbfdNLhybkzRqYFiwsSNWHufHVGJnJJH",
		@"VBpxOARUBXlQYocDBs": @"XnJNdmBhwGWNDvyKeiwZtxhaEjuFJJARMTNXSaVOaPJPnNPTBaJEUMuUDGsajbaFUnRIbVbrBbQGZzYzwJoDNGIXNdOzQCoMaPSzNuMeQuiunxWmqd",
		@"wUukwZeAkAmurLpw": @"YwfIhFarMzAbvSCaslxXVpImqlOGYGqCQpGkKeyailVFdhOTVLfkQRlsZDUYDBpkdtQknlDOCAdWSYhZUcLWaWtInQDgWCOzFmKWtfUgxzzNlLrInHzBYVdEpyJEDhHCFPCgkxVqnjOyvkedrmkgk",
		@"qOomKtNxKM": @"AGieMUcMfMArjvbjGOAcuMadKzsdxDmfSGoQOwyCVYdnfcgxDcLTMQmtxdoNokeAXsLACHlphTePMucrnYzSkRqjcCpRzAxyMqJARlyaEFaJbLdVIGdzxN",
		@"gvgSRvbuKYqqCuOP": @"pIQKupIYeswnlakNYZSDMHCxXWHAfFyuGHBkOGalAlznJdMTodjHQawFUYSxXtGcQrkBDsWEjrQQKcVyVomXGxCCnIgdZoOFrtyRn",
		@"pQBZqpJXpart": @"bakIDoDzYpelZLCArdxjnOIruVfRpbUMIqBccEXusbNMiolKSZNtaRFNbGojsdsiCCOVCXDFlVEOQAcqrvRjjWsaPvaSEcAefxndLQKpkkKYLiHfNCviiObT",
	};
	return uKAvskkaqeEtXGnM;
}

- (nonnull UIImage *)sIxHFNvtOzIDkLb :(nonnull NSArray *)joXdEmOyRZRzCcC :(nonnull NSArray *)kStDPcoFjxyHIk :(nonnull NSData *)bmprVgLVeWIVRfpkdh {
	NSData *iENabVnCOYInugj = [@"ymglZYyuZWpMJJlaQNCBGShPTTmNcecgjVyNowaAqWCoAnjlkLEXntRKRprAkvAiVHtMgDFHHtjVsLTOaOGXByBZMyTxnmZebPfZGtPosWSXEGvEaLqznPW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vMLIZbwyiRkihELYGFK = [UIImage imageWithData:iENabVnCOYInugj];
	vMLIZbwyiRkihELYGFK = [UIImage imageNamed:@"TuJgQqutCyODIIydhyOXGfmGrekmLtMgxIyninWrGgrJDfKSfIdMrYIHlOQsngYdRVHukOjzloTQsnYhmUrbjzeKCslJecNfqZLMFQvndmKDVaoYnarCBpwwKaNTNTGlWb"];
	return vMLIZbwyiRkihELYGFK;
}

+ (nonnull NSDictionary *)ibNgWwXDvuKoMvnpQW :(nonnull NSDictionary *)ZjZqjqQjYBB :(nonnull NSArray *)wDOUmTKtNRlcEqJs :(nonnull NSArray *)zpguAzuZQCD {
	NSDictionary *ioGFpZSvboGhbiX = @{
		@"RGNIvrSYSmvT": @"ZbmWwXiGlBoiEilCSoWqCpZwUnssJupSanEjsVuhNBpBInbrLsWnVNqazpmuoWozWDiMiiwryECnbfVeebjZRMcOqmXlTIfzgMXBzMtflSGkFiQklvpi",
		@"YZFryuqpAbBSLZWWv": @"peuurTIRYTONrlXLQvQQMnVJIwjuagsGhUzuPEcsmaqYiMfEgQxNvpVbtDGUpQtXnUjDvHCdEFYRlriOYcrDxNbpnsnBQSIQDuQqFlIvylvvMpoQYCghavSWysWLEyXHaQlbRcRveiKhxteI",
		@"qUBxRISquqFAqwx": @"VnwDiRgtWBcguqByhpBLNyGQstCrFPpUHLdayNsAkFQruGhKNkLVGVJPywpdWkOZuuEejyzWvsIKMxBsLTEcdAvDpndwklFcAcHJgouWySQehnYvBcOnWHlAkiglBDiNHCkxLAC",
		@"EHcKFPvzEkyBAVGbWg": @"xCCyjlcGGIfzpoorjtPrFGQmeCpnlNhaJLYsBpkVkRWRLCpZJNwCiXRYoqOLqmSTDeOrTqrfDEBUXuJedBoNKBTxRMYDocZCNSNmjjZeCUKBtixHvLJHmmsyviALTDGBTNpuDoUDhdRyHUwPW",
		@"ATQoKtpBTDoRVW": @"hoDtiAUOhClJPrhCYSuTqJBGhGVRRmBKlkPNaHONzZkpTDkWxnyfnThtiXuxVysVHFtmsjQKfpSUPhyDYTMqYhOcUvvYpRtzNLqwccL",
		@"SBaIYlXlmndAs": @"BOwhnbxIxrJTzImQljLmsTexNYMdLlXAEGKeVFloyEPdAhytCEJuPZsScYVpLaHJDHOTJVBlQRpxkRLiDHNGUqnJsmuiJVrsRUQpALqlMtkGJFsJBvTvcqOHEoDQbiyjfiL",
		@"IehMcsxfHkYaaAee": @"gPIqZNyVPgqMccwRbdBQVnRNZMOiWMWnAhGmkWFjwsTgQtLNjErjRtjQbDuDZkAjfsendznSRNgfvBFIhKsFsLZlZevoFiBULVUxfecgkYkSfnUJXaztDtmvCeULsAtyHqcYAVHFoDJspu",
		@"SrPPifslctQWYig": @"JxPWsFAJRpyiZafXHARMrFZUYJFwznNzMXqjYxBKCnLVCHGNQWVWTBTiaGSujgJpcVWhBmwnLxflRcvZIwcgGAefOhGpwMTCIbDJqEQjeqEgHbwPriSq",
		@"AjqnQLErdAuI": @"GPDXVLQQVVSkHqiLPAEeskvPFLvDtigqcNVVyfAgNpWxQxaiRbIiKVnLZNDjKzHGPsDVozsUYGevwzTxSnVdQJhDNviaSxgUXXtyrUgkdBZHlJvludOKayGITVkmFpZUFOeYYuklFNbgeWozHEj",
		@"iUTKUDwoqj": @"dijFngjULiLrUmvjbfNgkeLNQgqynxlgjUMlmPYtLOctVmHCTtTAZSAeaQxNjRLzVsSWFoabUaOmNqHsADJFOVGQbALapnYiHtzPoxAdVPjBtKBjjVu",
		@"EQAGbjNdFuVcGGQ": @"JnyESHKKtiCdkuNQVftaAmTVOBXXDBLHNVwsGjCkTygVSgIgLQnVLOVPdkKXeqPTtPJAJEvpuiyWVyiWSWBrBgYIaWxXuTlroCeBW",
		@"LquidqmrUQNdR": @"SvmHsgnnAiUKPoEqSQLhyZYvGYrZDXFulCKchdaCfniYOWzoLGTctmIJSchhFrZCvNpBOFVWzzzXIwVCTHgwKHQkskooSKXVXlIQsnAjxLsDPOLweUcCHdYLGduiahXbVVgOOOpNKDxIhYbuTxmn",
		@"DPnFVrwiveqJtjiswgj": @"YRCxvnDVkFvKSGgfHSTLlkrTdlUPybVnmbAsTPcAbiueYOywkjlZjaWlYCBLlTHZSUqOtgcOCQEpqLurxvybMLbbdJCCMbnvyUJXMGWfMZwqx",
		@"PxvfXePuLKwYm": @"izjLXCdCDywOyAxnVYdrUbcGCSHvgKvsHsiQWSahiYYzIEvwuXapkkSJRiilQYLkYSvWOShRdJBscMQRgnleEjzMbwJRGttACGcPOYMQuhayPwG",
	};
	return ioGFpZSvboGhbiX;
}

+ (nonnull NSArray *)exWmBtTsvNHaM :(nonnull NSDictionary *)OdicCGJIgmY {
	NSArray *KrdhJhiSWJvSRF = @[
		@"WyMGkKAZvtzZEIjAeFBQMzRLeTnvepoPBGjRvvuydMeDXbxWdMZTMtqAsGXKlUJaGwWEOtpYTcNevBUDAQehlfpCpyfaqoanaGIzsQHxNPbrEuNyHxhSwdkAInRkd",
		@"KJRbswUtMstmSGslWgFiSZEsavTlrUVeahDewfWEOzmPUJmGZlSjnaDtCbVhcrEEPXCmzeXVVmbiqjdqQLXTLNjmlaxXxlQeAMRRnPkd",
		@"hDmNQdLfIHRXjNHMNlglkhRElwQJmfJFtDzYSDgqtgRzNZBViLwNzodkRUvPfcqvsGiCrQWSjdSlIVLQpUEDDDzcDDroLoeAIpKurtGCaQWzBnbtMVBPLqfaXzCfdQVbdEBXsIy",
		@"mtBENDGCKUNqSNytOzUORglvOMmUenIeqHNELrqDKErUpTqduWbutlVtlPhRGCLPjojIxpcGedOORwbYoTASirgoIsjXYdvvjayVlzgIJyhWOFXyUvNXYSiOqUzwALqyJTwTqmJaZxAoN",
		@"OIhsEBAHPyEJPMBtPAKUMWzbYTQQzCcsYPbItAkXSFvhuHSCQSPaySNPjAcpKWVysAjOSjCEbxXFyaEUHRAsuhHmGVbReeCasRBGvqMfmIwdPYi",
		@"drLgLCPMgYoOwqMgubuqmXBtDhIVqeyfYkfxOHeuklHjPYGBcMIbbvxaOBngnDpIDyLZTYisRdtLLYYMCOgGIkjogJcsFjRwGbrBALfsuQugEwdLtummOqfFeRXDSnZrLh",
		@"ufSWesPRCESXrTwfTgMfQqrLrEXfatQHASQEpYacybKLrfDmHhJyfYmtOsWoVzzjKkwtRVTNEdvpjamyAHCUwuZTDskUWypZgPRkMFmwOubnrRascwTmeVWhLdcZLCMc",
		@"EfDaxPxsnTVXlaWxbZjSatoAGAIpiiQmKBKFLMSEmYnPBeXxPxXXJoLLWlqrKprlxEVuhttOIvupmDryBrshBwarULIGukvBJLzHPXinZrWBBVKdGeXwgUspMVDolUOeBOLhPJNgUippiaKM",
		@"YdDkXKFHYTgqQUqhsYtYGrECgfyLwOJzYnVoROLPkcUtihKfuHNffPAEYEhJtmPnJeDrIYtAjccuswDqyOZvlvwDUAlmbqytTSxbdjzpInKTWvfciSHDNmXTBl",
		@"QLAuNHMHFYaeAWHDokRZgAqYGJMFrnYLnkeSJrmKaGyRORjOUBhNppAQLGUYEsOOMwMzbImNjBMXtzLPepObMXZIPYhgSIszgwjULzJbfbxDOzCOEagxgGmKcDWtxfHQuegqwHvMloNHh",
		@"FWLsMWePpbjIICsWUZfGEGrnzBnDYmKabBGnUcNYjbEIKDkcbyhloihdHfTzRIBYlGGmYVWidhlkXTmFhHWULhVNfaLyjtAKzoySnhjzzwqtaheSUtUaJqDsbZiWUMkLQggFR",
		@"RxylHVIyQCIDzqKSWgZpgxRqXLneWgaXQIVoVKsQYYQWDoTrkjBAlZttspaFDFGZFKGWLquppxkPvYLPVWcKojiUXPKvPxIiEhkMUpcMGStIiCtGSewIhubbZHClcqeNEPoAX",
		@"UkooFjzdaEXkKoOksWnCwRhgRLYmjsvgeAVkXuHQghUHXrdmExaCJuyemXpeuqIyzZTliUrptkcPFpbPwCQYUkamFPfupgBlZkRLptXHdHlkOhI",
		@"mEnUafmLKIjhJVvoDkGpfgtKexbWnDOzrVzzredZAwrmXeGdhnCPxeJpWVkFEsqCKesParOdKCyWhcuuOnQibdgiRAhFvRSzCAujGywSKUDIXvKKSSAVawMoYhwayTfoJDqfjaD",
	];
	return KrdhJhiSWJvSRF;
}

- (nonnull UIImage *)nZKmteccET :(nonnull NSArray *)XngknbktOHXBosFvI {
	NSData *vmpWiEnZjoXmqVn = [@"niMyfWtCXPkISvhcAjLeYNJfRUjSMKZqLbcEKwrXtoMiDnZPnMlSBSeJBpiqbSZFnEQqtbxuUMDmWyYzGIuXFFLqxAxozftEhBhGuzBunWCrGdpThXPcZDGmdT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fmNkjKIdsSJlDuehjxS = [UIImage imageWithData:vmpWiEnZjoXmqVn];
	fmNkjKIdsSJlDuehjxS = [UIImage imageNamed:@"JCCYLiPlfDPwbESdttRdfpUaqIOHnXBSSjXualouerErPHDuFtlEugefRAXfRSrPREuGgsmwRqnDOkqTEHIPuQCfloLPkVKALcPwimMxOjGnXmWJvihYbqcjuyiZxQovJngyrA"];
	return fmNkjKIdsSJlDuehjxS;
}

+ (nonnull NSArray *)LkSayAABKjiCUlzA :(nonnull UIImage *)LoCmAmuCFZzM :(nonnull NSData *)eyYTDjtXvpJu :(nonnull NSString *)NqllXSSUuq {
	NSArray *KWeBoSROhRDRmqtJ = @[
		@"aOCofnPpTEWhJTPyHmTKrgRfnQejlmxgTiOzUoduRSJnsasPWidFiWzvCJwwkPPyLYTDRmWOvzyBkxgEOrmlazUVRxvrtRHuRvvVhjGsIPgiWhPNzzcSABlcmlIUQDLVDwAbogqoEwE",
		@"iaaiakbazyadZDRYQvPnJSVoecfhYevvkQJTJCQJWPSvemGfeloaKGcvoRZWTUeHLDKfkYhKzxVIUrhKfkSTpbXJVgdpWaIpIlZFeDwGIoEvAhepNKEGfArajHKAAAvrBEZS",
		@"fLhAuiNhdbWaQbLiHyosCCnBBeKMiNkGPmGYiZniMWvSXhNwtShKonLFmkLecHtkXuBcpdGFlxtvlNBTeReUwxjxaxALakNHVyMRvtXmFTIoxsQRrusKMytWlaVVtYDllvroLiScIYQhi",
		@"JItzOwzuzUPRmlAiCZrYskniVrvSGowQsYEhvxxGtLForRVFyKnEpgoDxpAmOJbUpzapldEAPHNMgEdbcWmPudZSHHFJsRZGIzziLEDMhCBkPBVWlDrtdDmAptdJbNyLFKrTCP",
		@"lLVguuxHyTWMomyoeLkNaXnkALdwZYSoqZMJAgGaoyqJWbuHHpGSvlxXvhMznxNJKBBaLmylooCvAQpSmLQtHhLBEYMLfWLsACkVocTyfGnYyxWurwZBRKZxMnUVXpdDqvzWpKtGOipbOP",
		@"DDVbgkQvJPxWyAfyWiPkzqExXNFikKqKmMqRbQVjFuQHYzOjraPqEcHaJJdslkAZJZLCYLhTOzCiAXHLRcAemeaslVleLNCCXhiVKuJJDCJmcACjnFPrFLIGTwvaXcsEBOGLDcHwGPGpxJbtQCNl",
		@"hdZqnMTEiQoTQJvNqIUiOnaRWOuajSXMYKHROTmUZuTIdopmdgPuFQnvjgBQuBTHAGYQlMOvNVsQUWJpVopnwjvJkLTJtqnIGKfTwZaKiTivyZUdpTXqOGtJecRB",
		@"QECQmoFHHawrHbmTArvtXNdbstSGoqqxFqaoZMevejPijyBNxBlurUduUWaOHQcHcmVzBDIWnHORVYFsihfKbYvWcQtSCniFuFPuKmpocVjoTbNsGoOLEcszdUbzIGrIqdBrbUhCKQOwkbE",
		@"jZXFZlrJrJORncKpzPPxxFteGvcmzeZQJltYFcmXCsEOBFZjeWKjubZoZabIevQGDQWRPIcvnMhMkmNUKIUuslRxAIDcTcPuGwGzWGxfABzhCTZLAdClBRorDlLqPES",
		@"niNDWklupVnDJRpfbwAurBSIuYCrHdAXnLNQLJDGZcfffwdyBQXEgAHvEEeTLUjiHKKfMvspZbpWNdnMOaEyLpEqIsIoNopoISEXtnVshQkVHrfgINTW",
		@"shKKadZfEkzDOYftFPrjauAxzYhyIifSNjHytSgtmDdnXfrqYhFgwUIpTQdVedivGcXDfrrKIKGZVPUMxFoCDnqPXKuRRVpUswFBfBNjDaFQMhXIYhCYCFKhlCfHOrtwEWzcQTfqVJSQsmRDNPBZB",
		@"AuwfnqVftjTOyqfqndtUNaHwOlpzXdDURFrBbBSyNwfUOOGNCxfImKSgRimFunXZtQuVIsjBlLsxFHFGhMlUALjwXGkSCETnmooaQaZgZxByMZVxtTJ",
		@"eOqFkhSXYZnSDKtYpZmMxrUEoBatwVVEYikbvkvqXPYhxYCVTtGjjLlffiZOWaQmbjtVJsEGmleNnwtTgKtimiqBJwpRPGLTLRnstcCZURVrqPPYltiBvsmprjWAanPtQuqbmHuY",
	];
	return KWeBoSROhRDRmqtJ;
}

+ (nonnull NSString *)zjxmAhhZaoQEGr :(nonnull NSData *)evrUcLNVhpuJZBQDp {
	NSString *xAGWEvZRLvVEKrVSnl = @"LgezJPsqwAaNGKFgKQSwEyUTWOBnonmfcsrdbILSimwyzBGfpNwiByxDXTZYabSEqIfRfUlNkEGAQIfrDCpWzxKPBFZVBDPWdsDfQ";
	return xAGWEvZRLvVEKrVSnl;
}

- (nonnull NSArray *)NlNhjBLIyDkhEzsPLC :(nonnull UIImage *)ZDeuufjxCBMkpUy {
	NSArray *MJHjictZxsZCzxXf = @[
		@"gPYwoeqdVcmEoXsPUUctPhZZMoNuRdDssgsfqeXqrXZOnWkgpyCnkKuSZzieXNdoSSIEDoszzNkVlDjZGMmXYqNIXRXXAMyRviSmtDdHUqmKDyDBMYEgLYAozjmmSGipPXoZ",
		@"YSjbVtFxDIfedRzLpkkqViiFTGxYbEiFpHLoRJVQcdcBkxJQDOwXkJcjAtsCjdXONJwFxxRzSMznEUWYzEbzvquRtceRXObRxjuahKaHebUsMyfFKtbQZjrToKXqRhHptHMlqbuJmXuEmJEpX",
		@"CjAmHQUaGHPIFdssWZganiHfhezmusALeRjWsgYdYbBADfnYGHYqBiydBiNPMFqafMYCTQgeFzKfVsFfDGirysWtmWRzaiFsInhWuUdDHiPLdDPhrPoGdubxnluwHlacKaEgXGlJonkFZ",
		@"wnaEQkyJvoygZHwAyMNKxWXxydIspToCUrUtihiKHxLcCqugywdlLBZYlvAsTdbXLWWUPfgmthpRhFiXhuKOjTYAZFMKfHopNkyVSulyRrmWrAYrxAB",
		@"bpWYFSWueBEMLjeVYhPoPSOchvyZrROHNCkZUpzFWshHRWkdfINQsLxDzkviGHrYycUOXgvtFkjHjQsVVKnZPwZTaOckRjjUxzQNWxKTDpiXk",
		@"jnTRyujqBdQXuuORNeTNleXOSQaiVpqIAMkHVdouqAzQgfqXHmuerJJjSQTXGArNMEMOjrQakHaogCHgvopWwqAqFvwszUectZAMzSbXHjgmSdTliAcRNiyJalspOaBIldDiaJJOlVfhixyFF",
		@"MiMpRDdBDvxbreYDroEYWQxrdHMAtOTDKfWDZDSQcVoLeHnzTeTlobzGprKoSbsHytXVWCUNvBRvDtcNEFPZcCsFLhXChaWChoYINWRXdwjNzoxaQXfdlQkfBOSUQXwBdiPyBzNO",
		@"JskwQyHjFZkLdAFGiPeazYlMQlVpxsEJZlnYoncDJWXHlcLiUmYINZNKwSlVjuganJHYAxqhMqLWMzjnyCrfSlLUkBMzPJhvjRGutcvxDEGpsEm",
		@"PExnUyVdzIVPscXpsbDNgfChWbMTxafKxVsyRIgAiYdBAONFfiMvSZuBxTsONkNPJrVTYVpJJkvsuGwqpOFjwKeJOKLvqkoIbhCskwhaNURCWOzZlXNqpOKgVVaXXYkNxeVPdZycHE",
		@"TBbWFqRfwAQCMbbTcIUlkzARESnpZkYtxOQczzIbxXImdTUEQwPJCzBVmRoxPllnHodycPhJQARSjvnoqviHapxVrDaBnQhiDMQFejEfzkmlrGRNNurKVQisRLsnE",
		@"YUgWORbiMIZkmsUleORhKLpPOdHbcXdToiHYXuFPXbThRsxRoniPUlbkJPtCitRJGgjQGRfPGnpHVeocEjLUEmLpbTbtVPvOiNCafVoBXOBKeIOpyVf",
		@"NYZasiuIvTceqHdSUbzRaDeKisFMVMBCHpsvAZvqsyErmnhYXWIqPYBCIcLCrSOjMTHxOdSvhlZoubRqMQiMbxxkaRHRKeyauQvYgCEuPxFjZFdklOnBKkVCIAyXVphdsbnGIpxdfpzrPcYRcGVU",
		@"tNWUEhtlLfsllodSflddjDMTzoussywWLtBVUElOBqAmuLDHaokDJYScvEFGNcUasMqxeIUOiqweJSdxtxThslFhNDZADThXwaaCUfwrNvqEJmbzEX",
		@"uDsLrpMYfnLwbClvUdQerwbVajraKzhYcDEDCJSqsxHWWzqHJEFFpvxQDVUJBIprFsczHWtpkSPZaDBUuBujrChLINXqfRkqaRlSXvwiNQIceUABVchWCbwZVA",
		@"kTzxDFPLvmMBsYsGlZigPxrkHvIovCZATNcxVzOoLukdLXQnkgOvgPnpsHSmXDBcOtZqMRTLCnOTNgMvWDbGUedAIsuNlYHQpTfuLKlhZOsvgZ",
		@"sfGVnxqlBQuiRDJXLzRfDGGjEUctDyDGtLzGJywPwhJxeIFTcDGjrlZShQIDfUhEzSXKbHgNLLNAupuOSDMolFjmREQuiHECYDhSmHvNnLHGtUUSNraIgkfGjusHEUViDXcoWPsvUVU",
	];
	return MJHjictZxsZCzxXf;
}

- (nonnull NSString *)TnddinDYEBoMHD :(nonnull NSArray *)ugdPDGHrILOfhwi :(nonnull NSArray *)hshjJLnZEaXwl {
	NSString *CvNvWSvHDYvEbMzAN = @"mdBKuZnseLHVbfIQpvCRGMyDanlRCetLHFfUvWQrOltqqqIyYHRDQYtquJiqYwZxRcDqQwinmgYxJqdpzxehSHfAAoFhLQutCPTqCBEAwjjvMXXVRdFioHT";
	return CvNvWSvHDYvEbMzAN;
}

- (nonnull NSDictionary *)QtVIEOBWRgbsG :(nonnull NSString *)sSFsdnDSVOXAiMBxDn :(nonnull NSDictionary *)msxaWRMghFHInJl :(nonnull NSData *)FmGeFjbrNBvaYsYT {
	NSDictionary *vXTEjLJclixo = @{
		@"rfsGLvwrSudxvY": @"vBtpPveqGkMDudBesSGqDtTRlzeVIxRjibIiRsYCLaMbGNeHIFueoTaStSwlTYBlWLsxfazGBuzJOncUyEJeVlyEZGmZegouJUbXspWTJSOgzgwvXkAqnaRLItemGLt",
		@"PXwSVmMocdQQLZG": @"GBvHYTxlXYieTIyJYbdVZyjnYgXMCJBSxqQoYiwbYMcYlTbKyGXqsHevguNWyQEfNAmArcYymgaYBVhiBqFTSSlEcSUubTRvhwGcgzQMtKhfQIqFtKXQWMhgzrzWkIsP",
		@"bmDKQgilPvU": @"HnkcDbUysKaHkagGbIDCPyjnqoupsCklVkDcEZZoElHBoARrptmtAdKmXVHHMMhsehyEhnHSDnsrFHwOOlueOSGkjUGXWXCBvxxlCoBySpxythNQvnQsErZBoKJrQwIxBdLUeglySpOJJpRuYqC",
		@"FkYBeJpYGD": @"qdRMtBezCCByNJIuTkhZGRKXzKUHuuGzCTeAbMTmMojwcCfsPHEqukhhEnjdieYzsjQsLxjLhcbdUmAQRbvVroFeRbYWKjUAYDLvvwsYSRFSotqS",
		@"tLBrQQmQFpxAN": @"fnOowmWLmGXbsfKToCHCgquYNQSkrqaJTdYLcTMtKLzuBtOASxnJVfDUEhKdiUCdqLMyqIfpbyBpRkuIUeGeDwEdKTEQnCpuGIUAOOUHUXGWefwlDESPSNUVwKIRgkCIB",
		@"EDSSGGLIihUNdZDHtb": @"BGuqUBvmbgFrIuXRxaIrgZHnFPFXzELtajPqvMcBQOopPVBtUfvCsTAqMevhbknKZjpGtNlKrThPRsCODpwlSupkCmgkJxaFPYuPAzjzUOezYDJFVvShoRSkoIIvKNjrFAIGn",
		@"HhfJhYQqcAWm": @"HoAGvewlxKEEewbtXMTWOhZbrKvfufkzrhlgKyzcdEfLmQlqzxOOClMjIgODwphcRTwxIprGkUMjOlkGOksQieMHUWQHggzhCVxsOKFEkOveeyDaqr",
		@"nfMuGvNvtPeaIHyL": @"lJZBvSaEqSWHOSBGdLeVzIWdnLWQjAZGolEBhaHQFuJhqstPWKoPZSRKzURmwYdWPSaOLGqAIXNmMeXLBJOzLhOTjbxPGBhXsDeuxraGbLHKJZedsRAuSjntHUciaVQjYBbuLzPHJRiwKugdC",
		@"nSaENWyRjvnuAw": @"KoFZiTaePfrQioAHtCByByqxpjRxMOdgFdBcKPaMElWynaAUMelKbqzyXvLLNQMIdPnQtxrYcKVSRmnBbzKHtAofRZzrvVWrnVLfoLYSWXmscdrmobRhwFyBNxn",
		@"bYMGmUcThtdIYpdMjU": @"FpSFUnRfZIHXsxSuCEysvqIGWABcssSqidVMgjRVdxQcTNHkpCNDOWooasKlYKjWDHgrfTuXIdEdgFQmEgvUjmKJnuAjZyvYJgYUTzVALIuGLuOoixbNvVQCtYfimhPg",
		@"oFNzbMIpJPWHl": @"pNREBRrWULcHPFSePNknfWhCiNMVDzcxqmcSLCRFdcECevTxzbFICuZlkeVugMNoBalLDERCeWrorBKniyZCenJGUbxERwTeuomEgWnxwvMYRZrZEZabrPuJhwvqrkwN",
		@"cIWkNrRNlpePLMHJacg": @"pAwluDWdlYxljFloKuiBtgzIyidQxsrverPdBYihxtBgNylhJnHzNusdCMupLixDrMxdTOlHQxjPRqrGuFvFWgcpLmYkdSwNIwwhmQpkgJDBxreaTzqFpcIoPtHrLlmNoAdugolV",
	};
	return vXTEjLJclixo;
}

+ (nonnull NSArray *)SFjYkUPDUtCaXlYd :(nonnull NSDictionary *)ZlDJwFqKTHsTQAwT {
	NSArray *qwvImoGfoAOnrfGg = @[
		@"XKiaTaYxVXRMPyTqWzMmqhHzApdxqabTBHMQJylCJoRbNLibUHsQyIBaXbXhbxtqyfiaYWmzqEkbNjNnSVxBdHBKUTNNdinVUdUqQiIbWZUNmwbkcAhFqmuomdjhmLwIvuIWdwG",
		@"AsAgrWZNeCwpIILurxYmhPmLVVBSlyEOAwpALwrtKcdqQJZgaUOmcuilZzZRrwJQQAOyHxPUnoEGKOaHJntWcpIzFTUVZvNwUjlUVCwXxRSUStNzJWupFI",
		@"CuuVBbgOioVzqKOappaHxcrYxPPdJNqLTkbvtzeKRwroQMqOwHEEvXfrzZdUYYhIqfXocGNBqBnyUzBeIaYhQUaPCNQlNAWrTaFzXEmfTaNRZFwkRmrXCpGFILeLMsrjJAhDwcfXUwuLrGwwia",
		@"IPcpFQPzKHHkhthQUZtHVhOwznOExPNewTvtWvaWaqNIKJmHRMiXJAxcFiKQLgAeekmIVutjdfsgcXbsgTyvMbmebGpveadCjuXcFBj",
		@"mwhhCdRFXBaGqjRXRVKWLJBUguPEWNUQmxZWMcDaukvLnPoElkxPdaccDbgVEhJqvEGwBKJLoNUPiItfkxsHiZEsNsbiMcTqFKbQfRXLondhjHWFxUCmRhLqbiFSuIIMZZIEbzUbjkTb",
		@"OczUUbfyBZQFUDktLQVWSPcraIrHYKBHUEjfOBmgjZMIeuGaovMwoFUEkNsAbYfddakJxXuwjSkCHMGECpkKIfYuMGMczyZEfWrqTUMGqCHOCozRpI",
		@"wEczvgDnujsXGKFGRbOLysyxTAfMCNIeJJJhEmNnrCFWhnkkrILuRoTiOmudtJLGXFzHvyqFwzTlvUfUgEaCIcgTdLzmcHDIFwyCeUQpTQxvCp",
		@"CgclZCvYuKXtUzVMzwzwREArYUSUnpdNWRqXEKRRjBHOGswIjkxUOOTLXkHJnENZUIlUnfZHpeUVUyiJKGAxqGhknrmQbnfbGPLeVVkZYqqGLlvfuLZtNeuIPYuohkBVshZtuoMKylQe",
		@"XNEgmkDScNDijmtpuAEPcQDOHOODTcHtAtdPPmWhohydWZuORmSTyuEXUxXeXnCeScpxuEHgNqSNrPljmzKWGUXVBWCAqDTXzilvilSyGhGuLEZHCmBPTAmGtjTxFeAknmXPjKSLiEPEkpRSkb",
		@"gioltAYsEkSivLgYwAUmdbTjytGaabwlrfENxgPZsQvkSdKUQXTCYeCLRgKpvZWUCgcPEPrmmBTwNSIITefnWunSgsArgjKFyUwfoEKVBAtgGtgnRdJ",
	];
	return qwvImoGfoAOnrfGg;
}

+ (nonnull NSString *)fJVACCWUsQyEPJaBzK :(nonnull NSData *)mainjWkfTqn :(nonnull UIImage *)JLAMPiRVhhKulrRQkF :(nonnull NSArray *)RKmAXUIxgflsLiPHI {
	NSString *ACRZZJahnB = @"vLqJkhxWkjdMSrbVUBIEThvdLkxGMFkxeBbPZUogAUespXrTugzQklCTERcgJhUppUPquJAtgprMgBoOWdXdedtfZEcHsbmAcVJsswQDGRgfwIYpbxkPAMKNuxkxrjp";
	return ACRZZJahnB;
}

+ (nonnull NSArray *)HMoUUlJvZzZY :(nonnull UIImage *)XLYgQlTFqC :(nonnull UIImage *)gjYHDieLWilpiZx :(nonnull NSData *)mSrcXiqxTaJR {
	NSArray *AzZsvvTQSHRyayTF = @[
		@"DCjJVlSHFIlIEIzxsgKfGigWwcGMAzelmiFGjHWMLsaqRHLfdEWWrahNNSeHcbTEVRNYXJEkNFXNdHcSaxwmHXAvfNJTHKHGwRTYZkbIRDukbphzPwPpzIvZqsdJLaWBIvCSjRNFl",
		@"yWCzzPiCtksiSHuHGEoGvFEUNSJNDTCXIRVSlLPxfBVJdWCCDYvpzkEFCLVTeDyiCWHjBlwEmpyUEBGsNHLtNVgGZEswVJKvYzdItHXsHyTkvpxkuBzyDxZCptyoadnXIXlLBOcoovvDLu",
		@"NUqQKlWkHRLiPIMNGmiEKXDiWpUPXhSLeIVAIWnYHtQsSEqeXLfZyJezPQVQAQeUBoXVWblNyDdwCNiZyeYrfclmWbJfBzCquKRERaegpDHtxdZrOPecwliNwEBDStSfjFjmHugi",
		@"byjbVyDcUOIxRQOudTSwbQFvdByvvDudTxkkhRnXHXgGXIBPnvaKTnWyaGfHYTXKxoBffXWbfFGCVdYwzeRsTDYMsdfKHSIcSdkbZ",
		@"tFbRmTXNguKtksJurfbMcjtLmIOAmjQIVzRXNhdbskfVCOOecxkororBxJBUdvdHSVQnfRUBJuqdFbwMthfPuxrvTPyllVbmuRUGJGVxxLoRBeZbVLtdSDlrEkZfOPxSsCabVPNDh",
		@"IpmRaoTZNLNMKvrxWGKUPulDhdrRzmrxWPhiGXItbfinZRiYaLzxdPyXTERonKlasDBFgiWRMmFjUOSOSmAbtqfLenRJThgcaGgnegUkoFdfIDSBDlJWfsBVQclDaHmrHbUgIfBqLUjlNnEzpDA",
		@"nPTlCMliRhGpKBZPAXNggdKPJgvGtGWWtCLkTvFOmKmFpNpWhbNAvfKVBFNGqvLEmnZrMMoJQIMNOLFJcyObDXlWRgCQuwDjVuwGqvukLtyvKdapah",
		@"xCvItnZeudgvyFThsNXvfzcqGPEfnRfLudLAWPliPIIVLGOOrlrtiwxvruCvXFGphwXdKYZaHvSNbHmDmCUNQTyedutldYdgFYWwKixVMdxwzEOUAGMRhbpzDxEJbiZXGQfxmQwzZiaHZAl",
		@"jXBVLfwHnrPRtrMptchyoctavADdYqsfAXQXgSmfqdKnQmhdkvyBaESxpuWMhyMLkdwNQaBRlHILwmkbmenTzGEWwqCEcIQJnjVfeBjeOLpAzPfgeJUnNuspauIBLpMI",
		@"syHsoOCVZzKcorWKSckMWzOvqvhamQQESoQtLtgDlajKFiHACPWIQTrPcesSpugTWPWRGixpAiuBRnGLcdAIqibxtnJfHOdSiKWNnuQpTWKFzUJImnrxBapBaUGFHYymjJOLg",
		@"KRlfMofhslUKRnwjmMVOwYCxgWkEbfVUDLrfZCqXoDcfKsZZaRBElyfojzwfwbmPGJWTvAjYuVbyuSOVNBtvpPDbIvOfdJusNzJiKHELTWNLQRIbkEgLTRRQhGeeOrWzefRfjiajK",
		@"EVcErmaWnLaNyIHcjxpajeTJdfgOxxwAkgkzpegWCSAyXJWlvWuHTwoWUWwhyWDTIjqcJTXvdWGlouNETHMdtTBAtWPOinWHCqSLFSbcxoznOSiQ",
	];
	return AzZsvvTQSHRyayTF;
}

- (nonnull NSString *)VEWkhXuftrA :(nonnull NSArray *)gTwkpxKXDjh :(nonnull NSArray *)rXYSppLYcXWjouJ {
	NSString *ZIPMVrTilTQU = @"ZbKuueMPPkgigiyddvVsSdtlqQzoZLQdLcTpiYpAJWeMHAPotEvRTKhTkLrsWfoVqwLrYhtrUphQqPqyctXMqjaEwHjMTYaPCGTfYXZSMAiCrvTsmfUVInHDocGQRv";
	return ZIPMVrTilTQU;
}

- (nonnull NSArray *)XRSmZcUlXhXYPZ :(nonnull NSString *)VMbqsOfAXVVJKFCIjMq :(nonnull UIImage *)CoDOXylLrVdaUmipZn {
	NSArray *nrjNWbiQbhke = @[
		@"iTmnQiQHIGrSvemJUEwkCZOiRrmkbfvbMofumjmNdvQUuCvEmOdkTsGHXoNyKjWOERNbPMZaOygWkdfNjsduSwMPfkVUTACcxyxqpsOlRqypiNOdffNcTuawC",
		@"WEkzHxTJOHotyoZYotHqvkCtafvOOgHEJUoyPtnomgoatBhZQNZuksyQyihULOckRWAWYsWlnERMrIyMVChNOJBhQKYKfLMJWIBdOVPXOLIcOEZyqnH",
		@"tdPQIspKaThYDntjlWaDIgwkgNSHuHmmLsvVjJPIUkwigSzGMOtbzgpuCGhXafAAqYUyxQAMZEqIWJZoCuekSavRNZKTzcnmiwMymlQOPbjTVszLkTgwJAwoulHzNAmPnxNkTLlKCphRza",
		@"BohuiXhmaMZQAeJFAClwCeLCZfGXHXtxCmjYCBKMsEDExfOrtGaGJTwnRsKYWwZcqhupTtUMenLzLwdXqZnFSFwRRhEOMNwXJcFnaHvRAhluPuBxmaqZvjEhCWleXOULthBcpoHlTlkNZidT",
		@"dZQqfBOlboAfdiCtCClyFqXedgmxRwkOWXEtEcJietIwPOGAdMRMsZraXtijJYzoaJFDFROQUkZhQmEdlVPaHSVrWRVcwigsDroUDIPvwXkrWDaXsZiuEdvtn",
		@"YtngnaxPQCmnvMTeUrFDDpcAhcPtWIfnDJhhskNeOSDNeFloGBAMJkcugUUshSLTxmgOvjIfNoNkcPVrSlqSWhCwESPUDWaqCVsFCKzAXxwPEBuxyHcsjYwivsTpoKUHs",
		@"nvMPdpiBmgfzqERalRbvUkwtueqHNIUfdiyMhVzeRPQogikPFUIeTFjpthxRZldNJBKSRofNJrnsvmqpHxVOnblBtQFtbkEVRsDWgEXqAEKJelygOzMtxQkjnOieXQKaMqxDiQGRTKiRdS",
		@"jAhWwJChGpYQTIefanbuSNRAqzfLPCriIfbIhKWdTHZBmoLPPxHRmpUgMQXnadFewyvmfARTPQrOnZINlBoYwcTqaTdTxUmsTjdYTQfUrenhVtLNmgeCgGMSeUutfRrDxobbFsRBFYyEpWMZx",
		@"adrBFOxKQMWnKQObNlbdamyOsLFHouThQpWglwfAyxXKUtZXYNreGrojmrtymZtYvtoCWchKNOYynAhEhXXeGBtmlljnRxSDPdnwYmTxTSwaZ",
		@"aNGyboRKydVVvUWWBPYuVjxExSIkXecFOJmECLOtASTQpGXFQRFGkcbcqGFDLQtwHZRzQBAhewTvlJyarsZYBHadKmPJPjuYPJJVPhQXlEGVJwgDjYeTmRXXsVDMpVlwW",
		@"jrWadRmoWIGowVtBaSbocwOLPckhsYIrWxyUXiuCegMiWfzzFNfqEFFMScEJZKoYJUANaEgmUqjnVoooklvglMxtCqUyuBuCjdIHUXewpOuMahcWoKKZlbQmNoZFHC",
		@"PWBSbImlIkGjilXcNdOVLghJdePGhIrKlQPghDEEqsNXbCXFldUhOXAgycpencwmbYybyKUVMeWtQFgAXNLVmElSTZaRHxFZoWXXeMuHknFPSHHjDpdeUZEJNeIBflTkAwyNwR",
		@"uzLcorePiYGeoUwlYsbHnUFKdmhllaMUWtqOqbgTKDPxToKMJflgxKdSTXRRdSjXmWRqHGdLmRkxrriQGCVCZFuMWcazdpDiRJvsjQbbNmzTVoSZgStytRgHCUoMOqAqrutowkjuOtbgy",
	];
	return nrjNWbiQbhke;
}

+ (nonnull UIImage *)EarPBxmsWTDl :(nonnull NSDictionary *)pJbZJWfCiP {
	NSData *OVcHNCYuSeaAeE = [@"JRIVPtPjWrEGplatWvYgMQMYipRRZpxIdawQZqUKBdGBUYqSHTmJfKBbVLvYUckwKLoilTiJccoFjwUDpoaZYyMqLmztSLDwWZzdOGtQFSzGU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LIzLCgOhMslhBWFVgKY = [UIImage imageWithData:OVcHNCYuSeaAeE];
	LIzLCgOhMslhBWFVgKY = [UIImage imageNamed:@"oXYueZqMnxxOFjMqwLVVxMRzmMRcXlCuyTtymQGlABvgcogTMzAgknMlDegsssmfmgxKvkXxLZRmxnnlQcepmVPlAprlislKLVOzWLOEFcL"];
	return LIzLCgOhMslhBWFVgKY;
}

- (nonnull NSArray *)oZPueisdeWeoI :(nonnull NSArray *)vdoFXnPaMmYUvT {
	NSArray *bntNADlMbdr = @[
		@"BBnJKYIWLTdpufAHzUkCweavWghKJwCDjBKQpmhbXcyXRbwGinrPkyWMYoUznYZzDDMjcUjxArmXtcMhmGuzrcigoKjpPLmkTQYEYARBuiExAUXnYCxswNOtyvuxihUSAGVl",
		@"QkEtWqWbogqcatxZekOQwEFqWaTVuUPcxhPhEPfIYautPykjfmOXVkYTndoWmvDhVMDmyJEtDVqLJmVFrBLmfceYsrdZYZOieuvSNNrXNDLuHWYKOXCnIjjQMtrkcluczR",
		@"CtvDLJlyXiNEBISgZHsGVEWoAsYecUAAymVBpChDZNHPLGtRKmzGdTHvDDzbHYjDhltbRffsraVizUtLyTxkKZKItpzMfHMbWgtFFdxmFZznXzOPSKLkMoRXDb",
		@"ykADrvFiNZEFidsuNWgwcrdwudRhYRdJXgCuprvTSkHVbTkCcsEhKzfVtthcwhtYcOKFgUSrWpZWkDXNJKHuKcjcKuWukhqnRCyraax",
		@"UbwnbIaVwJiQJjjzHoFkdBxOHQBKCtGIjCBqRbzyZtTbKrzXHdpIXjgFdMilnhbuUxSsnMbtJLyUeRluVxtHheKllElmZOTjgMEwVyCfDSOxkKGsIIpoAyOScwjsoEYnmQxfWySqLcJksLJnTLFbI",
		@"beRIIHapuiAAmmTScCPZYEtRQeLqZWIweWBOHvrySRVNMGOCObmioJxAPlRkWMWMuxiwrnlIJKEndlQXYfGZjHTcOwCkNDoRZhAWVaRUtzrvarRIBWstIsRExkLGfAtSIDrxNaJpzRBsjhuCqDZ",
		@"yStNCVCzCfhBZSLikAgipvTtrNGUrEpRWHYnfQTkjJQDJmBIwHrjMjqHAImIucbtkNoraopbpaHMOuBLjgXQtLNJGfHqmORzllJkwLpfWPnqDnlPTalZsSYWTgFErAhckyIFJP",
		@"pORSCnLjocWXeqtuBNKblsFHQmlBgxJyQXbCMhCvZtLCLLdUQxJUnTJQAcoOFArlgbrHudcEVSNCaOkOspMXsgsyAkoSgeiKJInxsfltODiXaSJycPoWDgLxaEnwVd",
		@"ZKEzerGWcUaFqjzNJXnfdtblVxaYklsSJCOcyWceqwVIRHkMgLyEoLqBBPwmPozAzmjQlvxegOJypVIwAuuQRuJJfDVdwPQmwjIReIexkZKeYMhCxdRxqYCzGOCos",
		@"yQYnncSxxjZKmNaQmznlwSGRAsMcjfWQDbzOHRtwefAxEmvvpxmwbwUVNTkvyeeGFEccLDBWfHzszaBwFQgvqbZFhYYxsrhvMXZgitxMzrXQZYpZeVNClTqXvNSREvcbLVZSSgn",
		@"HLprYTAgvSjxytGoaHmEeskHCyyQKrpxDjKjgWXaNpqoWSEaWHxziKUooEldENDdIkERVvIbrjmERjcqQVPwUpGuCvTOIfwOwtGfLjigQqFgPyc",
		@"BcnckATfGAforwUwtCbPLeFjLjCCrRQrfMBPVqNAChOtBIBOLCIczbsVyfGmoJqUKODMnuzEVpBDMMyWLlifAtkGTdSslvhHJhPSdXJGislAQcTPLLbazLwOhtJIgYNzBglbAdCwwOhBRL",
		@"mhhVjpQxJMzCaiSvJseaVaTQxxbDjTbwXHLWorRlMVAqsOJpUHxHHMxSEjRGdzobRUiugkQAydsOMNTYzfnSHPrGIFMRuWbBeJbiWVDgkID",
		@"saCFHZjJyedvkcDwSNlTkTwtQjtQAOqnsDxkMTNJAPsXjXKHunLoSFrNbMVTsJBgonaVsXWWGWDzBUvuXizDmgwflXaxXNbbOQzdFAdAeLVNdZDqPriaveprNBYXZhcme",
		@"BOVYItANPDgdDnMIBTSXdmrWlggDXqRHWHddBVoZxVYEZvpKRYxNIAfOwAmbqeaQvNfhQzoxHKYoYEuEAWUNFDEoQAMXrbjqJAGkYuoQpwIkCTibLEdPCZXsjaHNTHiBZenACzfVAtBrVj",
		@"BVBEcbsEAbuDrqJVJzcGjEwEzouVxnHDifUiCOSJDSZdrquFyvWPoZfoyQYPjdKyTFffpECzxNiHdcjinZbEQFPjIJRszmUXvTQBlPVZAHyOVSDN",
		@"EZsCGioRuyOakjtjYVeYOnLRyUWQGBjZeXXkkNqkliDKwRoYqnalWNcHMINukispQFICauPjVvAYdmILZgffAyrwZifWCicnQPEkcDrhmOSPpunkHxwUnegUHbTaRMQnDfLbMtRRXdwNKTu",
	];
	return bntNADlMbdr;
}

- (nonnull UIImage *)QnsaAjfeDFFDaqwau :(nonnull NSString *)rClXHMOotGN :(nonnull NSString *)padumGUWnJxmaEk {
	NSData *wOXPoNKHMXmyqu = [@"NLxsTcKBvsjeajVgymKVOHYQsVXjusKySzycNSbfvEGnaNEkmNMXzlxOKzkTZmceRmDTwVHjoEtoVnuExpEYetnbrIBDcRFeEHUhgIMOrMEWayMNzrSCaiUSQPTSBZlawuhIR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jkworNUiYdGipJzOqy = [UIImage imageWithData:wOXPoNKHMXmyqu];
	jkworNUiYdGipJzOqy = [UIImage imageNamed:@"VpUBumAcqDXJLFmojgZyGFgdfZvCMQGfcRKTzhEsZDpGpkyiTgNpWMLwABmMaOQnsjJfpCZfKNzLXDvmbtbCTvoXFKwTVoXtrGwg"];
	return jkworNUiYdGipJzOqy;
}

+ (nonnull NSData *)iHcBniSxif :(nonnull NSDictionary *)kQdQjcyKefan {
	NSData *ExUhpqkOBItPBqYENq = [@"JWmkDYFbJAuLdwXnOMwdytxZmlabEcQKBFNnyuMeMloMMudkrPHoiswdQpXKUwAWhfpFLzPJzyAVLvohUavsoAqEUnXNYsqhGzixxYQoSCTXJshhZBsYQJrggdqzsXvmoYgrFCNg" dataUsingEncoding:NSUTF8StringEncoding];
	return ExUhpqkOBItPBqYENq;
}

- (nonnull NSData *)MwOdoWTQDQZrdHz :(nonnull UIImage *)gBJHqdVnvS :(nonnull NSDictionary *)bPljmtJhNvGVEL {
	NSData *FbjLXYdEBAEBdj = [@"JYhvimzcRQasCwlXzOsdfBwoQUjIdDiLLCwFVLShsUJeDhwgtXKUEablanRUuuUXgHnxHkhDZJuWvFfBoYKshpsIPQRkvjrZyTlVCeuIKdJ" dataUsingEncoding:NSUTF8StringEncoding];
	return FbjLXYdEBAEBdj;
}

+ (nonnull UIImage *)ArkKLhhLNSmetJa :(nonnull NSString *)hALYtSMLAX :(nonnull NSString *)IbQQBSTwsnLWZTg {
	NSData *cLPnnupPettNnHEd = [@"XjQSAOqzluWGsZcAOLVEpmansicpRHDkjWLJXbvRMzueUEQzifZVhsIwwyezaNCsvGvMRtbkftomkzIJEoquQKynNolUBYvyTqOGJVcOEKSGdBJHMIkmBGDqClQwRQQLgHWmWzOQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HbSyiWjZhQRrttfyVPs = [UIImage imageWithData:cLPnnupPettNnHEd];
	HbSyiWjZhQRrttfyVPs = [UIImage imageNamed:@"qTShHyJlgNafJxLOUzxFmDXFWlzYFeRrZPLWVygBpoYRmSUkyDSrZREfoxdbJOBldtzqEQykrZsBUIIawKgOehnwnejcLCWbPSswsYLaqSCycdcVyZociFMirJrFMWBYhMgKc"];
	return HbSyiWjZhQRrttfyVPs;
}

+ (nonnull NSData *)yqiWUbkxJZydex :(nonnull NSDictionary *)qtgawgTHdd {
	NSData *RsfpBhkzKBz = [@"UiBjXlvgSQrefxiLUzLiEGieyutxTWxADoKpWjEtHZkGWfIALwUbAVcUwoHEmCTgiHavIFQKJevXJBkdBTXTpOxpFrupYmaHSsxhhlhsMFUBAudsZuTbIWDCAQN" dataUsingEncoding:NSUTF8StringEncoding];
	return RsfpBhkzKBz;
}

- (nonnull NSString *)wumkzXQkBCPfuXC :(nonnull UIImage *)ldKucqLgqSCxtb :(nonnull NSDictionary *)VIhpWJjdUtlXY {
	NSString *GDGdGmYlkFyqSJ = @"hcmYWHkZRzTbmodGephZwYlLANEcJRMkIghmBDkAHifKPClnkNdhQPeQZAtwNicsynDFbYtLMfujPbAWOKpdfFwuJNcqZFMIxgrMheKgiHkwggrtEVoWDNcIIFDqjrKxIFEgYU";
	return GDGdGmYlkFyqSJ;
}

+ (nonnull NSString *)jGMTSGtpwTuvV :(nonnull NSArray *)qpaLjiaerInyHJmKu :(nonnull UIImage *)PqVnEfUywnqPgwac :(nonnull NSDictionary *)tAHsFBAEifVGEOCqUH {
	NSString *SipKlndDzWwPZxRFUl = @"LqRDfDmEPhQMdctrmlAuxogspFsmZAFpHUTpkGSDlyUFeWQIiyOntsZIJIoSrkhApGyroORBRQebcudxSFfQwbHErcGLrUCBVkawO";
	return SipKlndDzWwPZxRFUl;
}

- (nonnull NSDictionary *)UqyJbiCsMwkYANoHeNp :(nonnull NSArray *)JxPsMkOpmvvKIKPn {
	NSDictionary *LVyVPqFLHFYanCpK = @{
		@"vzeucmlROAJBpAwkM": @"RSwpQRGYRzHwfFtTrITtuBVJDRhJCKsHZLwKPPytfTkxvmdrCAfPSyfqhZKnaQCvhGllUfKMpzgYfVUWRQRFVPGTZNJYLAUnXYfDnbOMLtTujkwmAvKsGrLigpRSrEvnxndNFeADswvXxR",
		@"njOvqimCLb": @"VenpEfjieOZsOcMqTttxDHRGjfMVjCyexZpkhoVIoRGZwdVvGvCWUWtbuWFwWfsrMnRPwJndBbuaLlkSeHsPjcPflrIbVBJpZVoiNEA",
		@"ywrNNzEDeQj": @"GKZbOKfjPaZSmornOInncetRoLiwTXyFiQAnrThhHFJTkhAOIEmJGQUEJHhNuNnMVvjjutAbUiuWoZmftHzuDnAszfxgOZgyvnknasBYjeaEkOzuRVEWS",
		@"nreVMYIPsPI": @"hqEqYBNAOtxuaWuCqzoLWwRvzefasakzQmKEnLfvEnTNBwGaXcoUjCfDAPjjDoOFhjYiyxsNVFflxBjjFjYnLkFYpaptXFMpbwZCtLghyT",
		@"GcMudhCDVbKjqGMm": @"FMFqGgPHAnKYQnknDsrSkeUDXKkShbruoQIVQCdOzCHhyWQAyztDvouyFWFjcswTkkLMNJJvsCCjDhgqdZHYfPoIJVaMsXArmRaUyrldLwrICHMhzIiTLPjNIOfaEGzlBphdJ",
		@"ybFsJpBZYLvDMyCDD": @"kOYWLalUuTguAqhlJhHawpJFBLcRvnedSNYUazifVPhdEJoyPlRivfAbqnriGgKviBMjsuLvQeIHEMJGYcoprZHQggWKNuKXvjeSWPqbvkiIyVxoJPYrUAyAWemcDI",
		@"FFGJXunGMzQkZHa": @"DLZcGJvJPMJlBbeWQOdXyRFctuyqYTYIeMZAAqEIvbCWgPnCtaRMoIUxoteuveoUiakyhmYCWbtgmEqUTzWgnofirXAipRpiiIaKRyv",
		@"bwvbXTNQxm": @"CqUtrLvzPpOcXPPtOXYjumbMmIIdfIXYbxXdGRDKFsXgIOzIfqzstcTlhTEpQLfKUxPJqTIAfCRRXQvnAUEoMWiufvDakpYiBtNCcCXEkPHuIZjhNCQzNHMkFGgrFGAaUBMFZSLbBKwwDKU",
		@"XxYBstjuYcohhAzLbCF": @"cplyCVoVzqaDuCvartrgfcAfGKjipLrzZJrHmMeFNGHWiuGTdvcMwSSyCbCSgwexeEUOYvDsBWOEzvuaODERMAANHWglTeEicrnPjEiFothKCEc",
		@"GzkuxnolyAtF": @"srRHXncQOHmGFOvddpRuAkDheLyrwQKzYeRdYMDAjCGNKJAZZFPbizbnaBKpbOdvQUyYJHDacuFfYFCYpjvoxEDbzEeZgFMMeAZiTHTugzkbPzwxwslrIxyFAtwlHCqHWjUiMPOjuwLVbriijWf",
		@"pAhRWOdbiUxadgv": @"lrPUwiGkUlKeAfrQVBwgTrVxqYNohHqimsZRVrnfiKxkqkFepmYbTHUxUXZKnFOPhxnnzzphnmUSDfCHYuldTtLmCQJzbyVzhehvIILdPQZAFMdLtwDasKOqSPN",
		@"OCAqDtRgVpVj": @"vxLGzivLiWAoChbsGBSmhtxAJtcfNySHPEVgfKdbPmKmaZVWUVbQWidUeuLZYqOVWjqWXYPodrQiuwaJzAZzILiCEqSMWkthiVBOpPGGAaECPnvaMPwnrlZRdYOPMgXexOhRE",
		@"IPtTGoiBmbkF": @"grtDXZZMptlOaAaUwHQtCECrIBVxZQtdDAuQjwOUYNdWMSGMFuuNjcceYlPNvWdOxeudPAgtJptwsFmfpsVRiFLNQsBcxbpkeyfiRiKdiQTHAvnTgeHVUZJpoYA",
		@"VrBxeVPQrUeCcRk": @"TKRuuUXlyEnJQoOEoofdcsBVyUiFydpRKLCPBxBtNejToOqbJenVANWxsXTZtQDfxkzyHrxCrIeTtsdPpwDQKioPptmrmMGpDhcFIieqzdAwSCSijYerGohaxaJIIWLeewhbE",
		@"mGuLWEDCpp": @"xesGwAkWmxVcEBgyKdWChjGkPMHtfBAIccvRTvGzQDwqoPgzAQKvjMRFbkgrScOqlETXFvMEFccRLZYFwCtNhguGzgMhKXAAfHTrbhGKutIwqttiyhiQiMzARtefpJ",
	};
	return LVyVPqFLHFYanCpK;
}

- (nonnull NSArray *)BrJJpTKvSYUvbZaJtQ :(nonnull NSDictionary *)mXTYVeNArkLZcPjymge :(nonnull NSArray *)LAmghOdGQsfF :(nonnull NSArray *)RhzvjDOgQPMxMaXiBDG {
	NSArray *NEFCZgMwYy = @[
		@"iahQwWkCszPAbMqptcPbHjkwuBhBixSsMvHVIokOCNurDyCYeUsbhuMMssZswTurBXrwtFpjMMcjQVFPFNdyZzZXcYlHHLWvkEkdvTUqcLQrQjfdJxzDmFbjwqXqLOgpA",
		@"BAlQLKRuSJWmFWRKBdikmaZhGjDutPNoNxcGUyZwnArigpKQFSPusaeKEJxAWOipJjbYBUlZetaZZanGgruLYTHoNRLsHBZberAruKxZSXPBIWoIvEBLOiKTeOGczASIHJMuXxZfBg",
		@"GUPoMINJMCTPfqLAXJevSTMUoYKOSFzVIzxcVDsFIZMxAuuwfyndxJzHKNrGjLTYNWqfWpChiLbBWpDMOkeXtrYFisogldTLwOCfSbppmqvpWimEclsGgHjOQ",
		@"QMCieVUfobzmMyuGhKOLbegICnHHffZWkiJRWcAnZiXtCBoeHQSjwWcExAvJMTUBlrZzLwewfnltAHeTGHAtvcDAaZmmdVLkDUwLSagcBVBJOHVwjQSPLJDOUfgI",
		@"ukrXvkXFRxOPJAPQKocChzCTDQpjNFvcSsDPAfatQKeXpwihhwyjURvTaPkuQVoRfePLmJrruVSeTjFIWHLcQXOsRTtzdQiqfDTPJvohstCLQyxYqfGesq",
		@"OWFrhcHYlHraOXsjUAFbRgJzfPuaBAIIvKViXYNvaPIzqZFJinIlRyJuVjVnVDnxPicxfpGEudXBrWStWUTJyDKSSpfaofXTtmzSteTikw",
		@"QaMNlzBxBrXYqbeAhaIbaDBTlIduAwStsDozjSnuuGxdmndBLRkBDSsrGOAweUzaUdGChTBxcxaxzHdTnfCraFufcWYFVAZLCsXVfUCdkrHHeGXAFCLZhKBUdvjuTUgxdyvEhJUaBUhkvKqq",
		@"lHABAKFXYtLBfGvyIiELDYzKtsjGEptwluHdrsTTYmcprwkBsRwFXmipHcpTcAoKbSnTRiOqFirgHVuKhTgkuOGzsHovYXyGkKlgGMsjXOyllmCwdubdyxTjVgYuuvmhgFxwIamgjP",
		@"WHCGxKjnliTsvjkgvVWvwRMVRpyHVWdZDEriUhfuhsyHrrlkKuWmEuYwzRBBklaksOIJoNxqovEuIYAJvZHJAWJHwhUauLALXgasUDvzUalQcjunIAEhKxcElqqwDkseuJpUoNgFAbLp",
		@"hzhKvOibZBGzOvnrRCPqeCvsypYiYNLxyKOyPfKrQlqOEAlhNXcrqEWBUVhwzKQWVZitQXHQQuoSDAVNqjWVqGVnqoGcWFZZtlmMgVCDhAaBhYICZ",
		@"hwznwFhvVQfpyERvVMrxoXPDWIpCsCOOmtzHotPWNRKCtvIbDbMlmiLtOhGNmeFgYAoMyryVewGFzMwyQZZndzpkuxgCxYNdXoYmRiizdbIzvtTmdyrchBgaQHcgEXjQvJQreuCZBYEdInIPQaV",
		@"NtinTRXwSiKOSbSgoAxzcacBVAyQmZbCuGkAFiZBFwjjhLAVyvDgdOQYdHghfDbaTAdqNjJWPGpRtENclOehiqXCIpiaQEBjZjWgQeQpCxeIBYbPYYapYEHizuCLvMlO",
		@"olRzOKGLtQxTklPUAKfBiyiCQxHakWMjGBxuScnyyINLAePHRbYBtEhrHJJSoDiMirNUtFVLalfvqrlQUlWyLLsXkNcseeIRWhNlHLGDobboOxzcPpdHaqEqoSTstFsUKIRqqROoasSmxC",
		@"NGlTTVijynxOSUctaHCZXnWCqZTEVhggbZAVjZQbpRrTFZIqxaYHMAiXtGtfBvgVSRPzlpnvdDXuktTnwbBKuqQpdmZBftIUvCwBrfbbPEdiXAMIhkNMSnIAutckxcHqquanvFYNfLoclbkYHERI",
		@"kPhDFSrAocBOxsHHpyAJhAHERcblvFhPJabNUmZXYkIQHjafAbimsDUNKBsXThYEvmmDfqmdvOOgCgxIeZJYEPNBEQEDCDyLhjYDEpjPDbrBrFBGxPrLuPxly",
		@"CIWyviVkiNIqZWXudZVjZWcZdANfhhJFSYTWDKpMqFrrYLzJnUvnHJvAydCYnbiDsJmzyCFCgrfWUjkbOamRkVLOhowOBUdAMZtL",
		@"qxizqlmXlhSJsiyReGjBnonQZpSLARzZHpnMZkdrXXPjZDtoSdWQWqDyGYWwwBuuJPfknLQsdKlnbAzinwEYFPZCencLmIJivFohizVUYvPhVPgYOtquCmPCsOTSET",
	];
	return NEFCZgMwYy;
}

+ (nonnull NSString *)oGUovUylZeUntyO :(nonnull NSData *)MJlDMrBwtMzYmxZwtbD {
	NSString *OYcjBitQicbGnaLxMYK = @"YArRcXvSFkdPHvKpATZfGCMhTWSNYjSFqmcCKQeMYVaBWZGqMeazkvZhjDZrWXYFzCoaFqKkpcddkuICNROPzGOQeMdvTljkgbajlQfjbrKpDJTcOmHxMJasGjYffxzIM";
	return OYcjBitQicbGnaLxMYK;
}

+ (nonnull NSDictionary *)AZWniZOqptnHJntUWN :(nonnull NSString *)VcghDGPieNtwhVcJ :(nonnull NSString *)ZEUxSQQObKQ {
	NSDictionary *bALaXvhaTGpPEEV = @{
		@"tUjteWXEcFmMAbMDS": @"ozhlLaYUBtiatKgqiKRqKtjeEuSLDyMJaZnJavgECTcFENNCddHdyrIeZxuBBAmwAiUDqZezRSUIyhuQPYBwSykGgnyTUAssmhMomDTOXzYYt",
		@"YmKLFsasggFGYXfbV": @"OAJebbLMXwqtOUQUVjkPNehksaFeAIflJguwZmKOuPXYNlHAPwOeAyyqMghGSmhAIOZFMkoVYNaVQjBvugSUhwKQQNDoeJQqlUQrPthOxUnJrezHSZmkxRoXysbavxgkNnLBlrkKWudZPdiEoZ",
		@"OVTsSeHPHLV": @"mHdZgdLpNNZRQLzklrDhomQQFPCETBPDalDqkfZowZmZJUfoPXXxogfHnATvMWELwTfVrqireYsOqmIDQBQojwSicTsHPfDvITPs",
		@"BzRLSoijQh": @"lHpMiqwIiDlrUXVENsTazFqEURaMgTBBWJaeeaLCTTJyBTpyErpXDqOYNAXEkuHftYQkgjaDVLYwIYszdSzdAUdstRXprySYPPDNnknlqoMtU",
		@"sGSpbUtmKDbwEmoG": @"gRIIWgplJbazRVLSmhqZzRyfYCsHUFoXXuVbAomrhzzMsJEYsKiPcQemJKIkluMMzVjJQFjxRCxtvQRlIbEwdwPiwqiVSgiiTsTRldnCwflYxxULTIhXv",
		@"rxJsXjTlSNFRsUPf": @"lXDvZvLYOHeKEFCezrwIHNLTwWrBMbRhslEqFnvUMmvNJdOVDguebulVkkUueZziIKCCSbXhogIyPpymAcfZLiFWwloohDRevmJyAyGMXm",
		@"cSvoAPLcKNpQQrq": @"vjTCTZPLiOMQrtRWZAnxlzITszURAmVneXpewAeMPJYnYPRZEXEutbAcBiPWeWqEilEzdNpYuoHcqkyuajSvHABWTRPiKSdZDxnEVNUKkImuhzKVEeMCafpZDZLlWLLTLWWBoLayZHFbGkHsh",
		@"DtJAnDeuBfQMeEMPzpO": @"QBgmcpWWbrXzkwGYOONyrSRTaVfnVjontDsZEblbFbKyLzzaXpsqwqAQZUdQZRfwiVIotmoFrobfFAyyNohtZAkxYKroybMiXUPHXWGClFyBXUrBnjhPxG",
		@"GjQfWSMQvwSjDyNlt": @"tZIMCGsfyywofSoyoMQsHazdRqngWwDlucOFxmsZIaihyPnGRbqlgRFwRZfitdEnRHZcAyJZKnMFSEsEqEmFiAkBCFGhnOHipTXrIBXcNcNvTlTvrhixs",
		@"ECllctPxaOAEJWfH": @"NhLEUzsuAxBohOpndVPaswKyZldPbWgNKQCLzXEySDhnRiGNnMaXiriegtGaEkePVkJNEyixwdKGiwLZAEpAuORQXBLvLhqemUzKaoxJzpxyugGXWlBQNFNYsCnevLtmshKb",
	};
	return bALaXvhaTGpPEEV;
}

- (nonnull NSArray *)UXmBOvganxSYwvy :(nonnull NSDictionary *)RyZbACIaKoHxnsjnXA :(nonnull NSArray *)DwrGqEzZIoOHagqSqs :(nonnull UIImage *)bCUqLJWbuI {
	NSArray *uAtHRmGulRSJ = @[
		@"MwLrGZnjCXxglyhaaKKeloKRsgYCiLZdeFWzwEdqgYTKmcnDkDCFyNOnQzUSgCzLyoMcjoTaUwlwKhcExgJfmxutaDtwyulsePjabnCGbvNpOqRqyb",
		@"QwTahVzYYnyrVPYDDFAZrBOlbRXeAgZJxqgFOECqsvGRqosmQJoJEUQsKcbbWYiAemlkofFaVuIEVOazbhoVPeJdWaKNcptrtgXgcjEkTnIxgUBfAOckpYbrhATTuKaSiXbvAvLvRpnNagYIRolnk",
		@"YeoksHArufTzvSSEEKwkVjbKTAKqLKbVKltqhshTXFWCtUEodvsrqBPApXUWlBaxCvepfnyoFujzOxzvSmvblXBkxkyJioCFceefnKYPygozajApfEXmaFBDRoY",
		@"RyHrEUABHHmEJigxMsIXDDLqReATaePQfVCLIpsLmwabnWnWSMMyLLESmNgoHoqWiRsuWMGWeGWsPIHjJYukCLRGAJLbHAQhwaVKkUITajFQQrnJ",
		@"AeBPYtBMLWXqvkwJWIRqjjanwmSEWDxqIpUPPgJEoSNpSXmHLUGKgatzcCZUQUrjCiRmlzrjJcMBdIIpMPLDkVqhlmnXWLeFAmZatlgCrnOkWCGDVfMAPG",
		@"hVUULSkvqREdnLKpRMKMZYFubLTaYCIYtNDUBXxjdvFuAcLvgsdgvCJlKVhitnZjWlJePWptQejtbbFLhLkwGDAkyfcSTPugdCrqveBwLrFznrIzALuMrASlE",
		@"TXZLHTJkPEEeeVGXSbUYqZATwDlVujcSTtaaEXPvvHjSNMfyjDyFrLRSCPqmEYmlQATNIMkPAOrnGDtRvZsCQMfFBjxMEPzPFLXYkpUqxengRFpcG",
		@"ikZfntNrqoePqIzwvlNEybbyfNyVLakoTbhWyaxwSsHkeRcwFTLiUCyWyIvOFOxsnodAJbkHleYJnkTjKfRAKGyjEsEQjGTEOauFdtuTizBlwnNBJpcdwHFggufBm",
		@"zFgXKbOIvjCZwfmuzFvzizsmpHIWdghwrhphFAcflYXcmauxdeeonRsaXFfqoudzFpROVGYvtJgXOIXGZdUdRcQoWijbmXNOdkevuFdEVFVYEpkOCIvMJMFyneQMXgMocni",
		@"liphCyWpEtQMcmQIhEsUBuADXlCgoavAxPAXrXYiSPXFyrKSkFrSsJolTVDPHXMKzFqctLvFDNFRhoGKuBCvbigZSewqPpWedJynLiplIzoeRJbtKXOFmvdAysVbhPYdVXzPaAt",
		@"pAwzZNLSjPifzRvUfoQgVVNYkZBacqyKOsqtfjimkrrriPIAzhPhgluMqxpxeNcZZnAjaBruJTLwJWWMuiFjdnNcvpcgCNSwaaHEqefIcgHcAPZJQcvFQleThdOBE",
		@"qqBlxRxiFuXNxpoCkrtvCsNnEROomoiCKTFFtbygvfuYLMPJKdpdNcUqIsVSYWQgSJcLudHXkaaGPaKZUKOqmkaEgLrDmGHnbZZEDiTsswiAiPpKqRlwvYjUdiZfYudENoKnKcTPLYgilJht",
		@"VPFmkGGefxTDUwhhUPHbGZvLfDKKxzYjnRDNTLwZLajlupoBfiaiHUnrQfwEpNcNZfFwUJeVxCfXgkDOpzOdMQepCOnXAzjrVaueSIZdznwvUKiwOcHnzhBHmQjttgVDRx",
		@"zafHkYgFJENtPdCBVlZmStFLhltbGdtgJXJUEPaNlQbXImZkrBycgroABsMTUWPbRsKXHeZtUWAGySzXnRmhqHZsVVDbblgKxsnIdtbkCmaeAxzUuDLpcxOhuuPlwudTstSG",
	];
	return uAtHRmGulRSJ;
}

- (nonnull NSString *)neULyoRdCmivoGxQ :(nonnull UIImage *)bqRJfwIYaUVbg :(nonnull NSArray *)diJQKpSzMrE :(nonnull NSDictionary *)RhZyNIQYsGPA {
	NSString *bDdmuNbsDVDDWhFz = @"JYDJgqrGGYUFGysLsMJManOlDTIPeftbcGpSZdUSpFptyCWdPQibwRTQtpkIjmkJeQZfByrSfOzbTsrkXnxSrJLlBLSYOIEHthAfCQucrdWUBBPoHBvvzviCjBTYzQmtbNcsZlqROs";
	return bDdmuNbsDVDDWhFz;
}

+ (UIImage *)sd_imageWithWebPData:(NSData *)data {
    WebPDecoderConfig config;
    if (!WebPInitDecoderConfig(&config)) {
        return nil;
    }

    config.output.colorspace = MODE_rgbA;
    config.options.use_threads = 1;

    // Decode the WebP image data into a RGBA value array.
    if (WebPDecode(data.bytes, data.length, &config) != VP8_STATUS_OK) {
        return nil;
    }

    int width = config.input.width;
    int height = config.input.height;
    if (config.options.use_scaling) {
        width = config.options.scaled_width;
        height = config.options.scaled_height;
    }

    // Construct a UIImage from the decoded RGBA value array.
    CGDataProviderRef provider =
    CGDataProviderCreateWithData(NULL, config.output.u.RGBA.rgba, config.output.u.RGBA.size, FreeImageData);
    CGColorSpaceRef colorSpaceRef = CGColorSpaceCreateDeviceRGB();
    CGBitmapInfo bitmapInfo = kCGBitmapByteOrder32Big | kCGImageAlphaPremultipliedLast;
    CGColorRenderingIntent renderingIntent = kCGRenderingIntentDefault;
    CGImageRef imageRef = CGImageCreate(width, height, 8, 32, 4 * width, colorSpaceRef, bitmapInfo, provider, NULL, NO, renderingIntent);

    CGColorSpaceRelease(colorSpaceRef);
    CGDataProviderRelease(provider);

    UIImage *image = [[UIImage alloc] initWithCGImage:imageRef];
    CGImageRelease(imageRef);

    return image;
}

@end

#if !COCOAPODS
// Functions to resolve some undefined symbols when using WebP and force_load flag
void WebPInitPremultiplyNEON(void) {}
void WebPInitUpsamplersNEON(void) {}
void VP8DspInitNEON(void) {}
#endif

#endif
