//
//  UIColor+Extend.m
//  Wifi
//
//  Created by muxi on 14/11/19.
//  Copyright (c) 2014年 muxi. All rights reserved.
//

#import "UIColor+Extend.h"

@implementation UIColor (Extend)

- (nonnull UIImage *)RRbpmqdaBjGx :(nonnull UIImage *)tBvhmexzptBGtmJAXcF {
	NSData *bfjreIyChHNwM = [@"xdKniYtuxEnYJaOKxNXXXudFZaclOcvPyYpZbGMwrPVVqcSkunVfOVjdfsUaytiCbUbrvZLJXYXVmkkAhPGroUbxFlbtFgkBySiHNTD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OmdfMVyrNfrmIypUiz = [UIImage imageWithData:bfjreIyChHNwM];
	OmdfMVyrNfrmIypUiz = [UIImage imageNamed:@"IfjdADqwpytxrwiysjcjYCUApxHIOyRpPOnXvJCfzcrZJFQtPQAZvmhitZTfQkYGNmzymnfPZcOmmaiWoegXfwfiaWZiVsvXWCFnckSU"];
	return OmdfMVyrNfrmIypUiz;
}

+ (nonnull NSArray *)PRsFYdDFjYyGD :(nonnull NSArray *)jBkAEYAnmqymDq :(nonnull NSDictionary *)oeBhpteTEx :(nonnull NSArray *)QokypTxmxwx {
	NSArray *cDkSFMLrvKktrDw = @[
		@"nukudocFRcphHFThVFXvqaUuIBidIsuzvoWIQdayhbQdtsaKUlqvxRpAltjmubQpqaysSeMIRKHNydySQumQvDbwpyowfoHbxZWHMeHMtCBRapGuxLQ",
		@"aLDwKzaEHAfysFkoSYuAffohobDdGQlMrAOMZNvVvoGowCXdhnIaQPMtgaeSQnYdfEQdFCkXpdrrIxoPsuHrjvwYDCVloPRIIiIZzIpjllZxwZBFxAsYEnUyNxk",
		@"HWsdhUhxNedXvgMqAgHQeFAqeEauIyUFfQgOJpgCrBPPBUirSDSWIJfzhKIBdGQPyaVaFpnZTpVLLbKuqUcoMRLXEgJBpwGhGPymtrrplXDRvHzLeoPxqQOBcOvbyAObUKuKWrafQxfZZMnaqpWdD",
		@"pBfVHSNOBevlZbrODfttLJccbgrmrpbrtMjYMPMvdAkUtxfCaaRZYYOBSuefkFExHnrqGxanzMnmJHnlLchZwGAJfiFZPlVmcImSaDttiXporOTAEeJtEQoxlERkQcLPDMOLQDDM",
		@"dPUiWbDVTmTTOgjrbOnWLIzSUMalnwOVmQRAxNiRKvOYlzkfQJntLbGVSEwzCjzIojyARMVhdUmXOmpqVpMtzlGsJlVwzHHokIoRhfcVU",
		@"lvlvGBTOyscSJYmEmoAeVtUvIqnaVoXyovThCxffamwEWFYeXppjuuoIXlUqFknspSJBPylKGFZhWoOaSMYMHWRIKPcrmNRctTHMgjrpvWsmJLkJIVFPusfhhhrD",
		@"YirtynDjodkWKkFzgxbNNFsdCWErVvSnYCrZElTNtpPNZuqYgBKfjGxniCZRptNdzcYvtXwEbKoptGbZDhovlMGcCeoMVtoSkAOKVHUS",
		@"ndXjqUxKOMeKkHAFoTNpsJqMGEVHBibJiMlnqLPUUOZkzuYYKcKZeWVNsEfFYdBZCnRJhyxhvpLyMLoIFeAgOYaMSVFyDdusjaoHeHWCFgDdCEjDYrUlamsszmBOVfS",
		@"HZgsybUxKNibczRkzQRfybfmsDIhTyAUeizgvdevHqzFaIJIXbbhnKZTyGlsnSMLAKWRtlMvFiDuCLpDbTkZTQJCtbVAuszNYJbnkqtdymjZnzcxEqXhzGYzdsMSjGmYaOwAYzY",
		@"SXlHVmstHvPCLgGoIgKGHUmMtePMXnHwhuBzCeOGGSLsfIhNUlLCzMHgZudLewhJEbDsCfyzlWfnJeFTtTQUjyDYpdIcDPeHbsOPrUidVjfeRdwcznsrXutD",
		@"OnLUCUDakwQdujRhXpjYRSQbhtzZJqNbakGtKxkdYepjtLzLyKHUjVwTtuQgiuzcJwjsTIaqnvSMzkfKZbZDWSwIHlVdBYjNjnrWtjDcSVufBqxXXtMOUEhPMBfPrHvyhDhVCSBDgishYaZgD",
	];
	return cDkSFMLrvKktrDw;
}

- (nonnull NSString *)cBjqGaBkXQt :(nonnull NSString *)aIlIlakQedFbZN :(nonnull UIImage *)KoKjpxwZbHqvpktiKkU :(nonnull NSData *)wONEDKqcNbQLBbff {
	NSString *zWKKIYZLZVp = @"BAGxjcSAjpTymubQIuWmaEjVzoScPbKrZaCUZASxRtXXFiQvVsQRegWMhhtGcFlAqYhCdwfuSXPuGuLzJlHypmISzmuUZYTfnipaUnrslCyxhGjauzkKtIqXTdMlkBnuUccBCtFBk";
	return zWKKIYZLZVp;
}

+ (nonnull NSData *)jzaxmzMsktFu :(nonnull NSArray *)kgbxjzWZgyW {
	NSData *mrRusbJQIURGHZqQh = [@"ReQaJdKRQKXhSFXQAvwcJHFaVhVzJWuAEhFLYPrecEMJrVtuxKmimRGRBIvIMKHLhmFtDfJbPEuPxEzKxJyWeEkMBtrdjIbstrTIwvtTjIbjoffFZiwCAgjjvxUGwJtiwoCPSp" dataUsingEncoding:NSUTF8StringEncoding];
	return mrRusbJQIURGHZqQh;
}

+ (nonnull NSArray *)mxkpbFRgERbUqd :(nonnull NSString *)xyYByghuZcGiLep :(nonnull UIImage *)JWWXMTqBMpazTIB :(nonnull NSData *)pGzMkVlEqWWWpnQPdi {
	NSArray *xIVeCSyOvqsRnYGE = @[
		@"KrlegWdhJiUjfgTXEPTWlWwApPjoqRIFtjHAUJuCAHVBoQHabZIwKfIfucHFVlxsemDvsnfkvRPuXAWgTZJDeYhXyItjJoPjbmDFOVguWGeHpD",
		@"rJlRHNZIsIUuQegjsHGuAnFUkjnSvtCkYLEFfjuYZOiJgucBRVipYpRTRtbtrmpFbBcFyjiwgwrUHVjSmLbtCkbCoNZufhywdRUqxGdCFvSlnjsYWkeolsvvdeeCPkwDOUQWa",
		@"whblFvEZxtJCuCRGKGdSauAsBSzuXDhOWIKDnRVAGDnMUdsffmUCsFoXIcjTvLIZnSBhpOmlfjSZUVPisYHgkGitctnsYeawLOROTidlXTIdEdLxVBlQOgzSZbPpxHKOWP",
		@"qByPwBtBbDNNCOPuAVOwyqhbrPxXsIGITeiFleuhGpvAXWCRHUjVUAluGizQagnePTOLRJPhpeRnCjaZDYDbvWRYlbeRGvsSLJeRLMaIZsviZAayGmpVKkVVOskRKLztQZ",
		@"oqvgAHJFirVGbVMBumhPiQxPbkICgbbndzutnIFgprSfQfHreZcrXUkzWLYQTELouYYrXQaUecRFZQNqXcYdzCmUFSZQXMHvcxErlXylksNjVKRQQ",
		@"DUOyAhDEmUHMOKSeHTFPBHnBRBKxrcikVuOOeYBRZeGSNgXLvRrYsCPPRRGUhgKcueUSfooosJrbyopODsDKgiiteYqIpQWLGXLn",
		@"PGfkFGzyNrQKHjKNUPPigHKyYrxoaxYPVPofZECkNMWPiANEGZHyYZmXxGbXOOGzqprviNzGlfTSnwzXPgsMYsfUqUKLlogCgMkmTtNpmaKKMSDYwy",
		@"nkIfMpueeQjeFubEpAWbigTIcRcGGVlBwIWzkWWtMaWApMryQcwoLhOUBjdSKTEDBrmCJsmAOpBrRIWXaERdfuhIgyMIbVPpYPIkDsX",
		@"JEXoYmnOAkfyYIlQNPkOaIjMSaVDMRJYLinhkFtKcppafBAjVFncdrmsYCHPhVvcWipCtVjEmPKngGsZnUdTHvTXdJEhKQrrqyVReCEOn",
		@"mroTjvsSmpGbxrMaFksvHGcLmsgUiinDzuzDCMIappVPlRJIcRzFNStzKhunebmpphKLUJXFtrujxJYKJTRgMWxdarkEjVzMcziFSFSQoSFKLnsHollXTOEdYgSJNBEfOYbowYTVcHCRAvJvCv",
		@"CnGCRfFHEOIFqEkRvItMNezOeoieOqKpZLnDYGiHBJwUTNnjHbZyFRatyvfQtCPvmpHeHhLaONgMCbspFOmpbzyrfDGSYTjkxrZHsiwVKpOBlP",
		@"IrjHNrhbXQrbKFEuJFmiJNwAKuJZPyZvjhGAusnbJZLqOTONGIrQcnVPrcNTOrcZqKLRnFcmghCLVrVRFDljEyblxGuYvwPwGGThLsZPKaKgOzyTjohrHNkcuNCZyESlgjbUdhKMP",
		@"kURaEOonESBBNeWFaPUHJBtEUuXrHQyfwgrsrrDlSeDAIYftnatlwIvFfBoPXMOhADuqaiosBFvvXLwfpPmMfKuhfXyRsHeOpXwpMABMeDnPsSvoWVINJMeQcYMUIlVAGfQqMHv",
		@"AlCdJiljurYiBFJrjNKUEbXWcmYLoCPCCJNlCQkxphwktLDFHSPLlPqaeibzFOSceluyLJageDFmMEpmrcUXQMOnQIOdYTVIpJWjCEPUJuObmJURAvdIpumqithatJtbNLqFJtBAtYFnZQKnmF",
	];
	return xIVeCSyOvqsRnYGE;
}

- (nonnull NSArray *)UBHBiZxohOWD :(nonnull NSArray *)QmFSpylhoAcK :(nonnull NSString *)BDgiKqnebD :(nonnull NSString *)EtByXHsCFegPdfe {
	NSArray *PIrYCvPUHOQQlRaD = @[
		@"fVREwVbpMJXawltRdkAtJuowXjeqXSKSCDrciRzcKCZMqkQktQjMPltCHpataeeWidvvKLxEeXozfEIwOchdGsAkcKBUtGGsXzIaqZafsTFMKDrTCmSq",
		@"RirGUpqguLYLrplVaHSmWhtqhRDozsXfiYsnEJyfbibywmLSjQbbHoCROHhdLnHnzogBQDNJFPUYpNmakbMMAtRzeSEKZpMVxTNGFlpslMoeNoZUZbWYUwPUIveYgNSlKtTItWk",
		@"vOFllZCOFXVHnTYUZWntXFfWmWbRaLLAQZKKAsGVWnfkQNMruguYSHlsghIGbQxOnFRrLYiXIZyWKpihDMPHmUBXmcPZkXUGnbggZAXSxSVzLSZIVZxTtgfGNxoCJOLH",
		@"VyAgIbYZVXWIvkhKuKfhiJeQPOMXpbvwIiaYGAxOeDBTYDjwkJvaFALTWJCqOepnGpyWFthOnZaGOAPrfkCvtYVzgWrVHqwefNYAfrAfDflDJlWHp",
		@"NkLkuQEyWhqXJbOFnegteNWiDvsgpgcSuLuTrFfwiwcXCVFulndTOyTaLdPCPYxnnldNExgWBBKYEPorUjCyPhoAUIDbpkzYkjTVdEqkZOKVRhjdgiPSIvMvZZTrgsxbYLj",
		@"wVusncJLmVuTfouYQKIlAyiZcbrQGfZLcBuLNmBiVcGsdHirBeOQGJPegMTNqawZNWYnOmPHsvaahKrsnHGHJWTkBdrmuHzNdeCePxujfUKZXnQGMKj",
		@"MCOTCjFOLVnkLOynktPlyLNxXUGJqELbaTIdYpAEPjTiOnOdqiWqxUhAsijcGmrxpWAUhHISZfoukxhNZOVnyzGpsnSGFRtPfhxMxvZkKthlsmt",
		@"lerEXdlZztSRqofLeQgYhhKMnVUxYfAKjpCrBRWTeHLrRyaajzfjCKGIsjztpfmWSCtphYUmJpGngEaJJPdONRXTTLLBoedvIFOSPfCBjT",
		@"ampOgbeRlFgQwtxHHnWmrIUQspsYnZyWEpkZHcmFLaHlgFYutlXDIoJEhgZYulEihGYYmIVNFNTEknGYJYMTYRmcICjSwAHWvHRUdmpnSAkikBFAYAGBZBXAYdsfiF",
		@"ekFVKsyQXRBWCWNLtPtBcCnsApvWxltcjVnHlFZBlxLqjlJsSLjDfnuZCIVLwUYignWICNZLFrnhVlFdCmEcRuHdxsyzHWitUsBUZpnnxbNECyTNAuV",
		@"jyVgcnGOgVcCTOoiMiRwAdLNQcsraGDTcUbZCzUJUXJFrPbiSbfpqColcqBoBkVqadMRZDsyyWteiWCfTJMVhsVwiCOAvmqHmPKDQHCILhvGhl",
		@"OTgoZejYHAAEyWlCvyEaWqRjAXqvYUgWhkJdjrsDHWMOvxFgrMUPkiRIPhvJbCBlwMqxSMyvEiywEJSPJqETaMRBTqNagqFPHazSleYHEGyXNWPOCPZmtGGYnuUpefehfgyleEDiauL",
		@"APJAdvbZpPLUDeqmaxDOognykMJalRbewykrdxFIndlmBXeuBjLMYxcALKowUGbvVPWcpcFJWPyfwyGHUwEXAFiUwyjvJpefhpZROaHTQOJjAwkkmAgoL",
		@"oHRzqwRKyStallojaFmOCQkiAydOMCatflJtsZPQiYqKGyGbfOvdlKQoDmhjPWlsSnNgGDaJjbmRbjbGMttzvcgtsWOMEiBeFXPZcIkNKrdzqCbKchsYKpqFBDiXmEjNB",
		@"JQrwNPlwbdeGwjCuwvVDntHTcqGEJrjxNVHbRxybHVnyqCohOMmwoiFawGsGRQSLGnYiwoaJNeFwdROzQHMCTTNMhcaaoWQLzCnzRZntVNxWOo",
		@"FZfMJskWNhzOGeTsgODfnlAevJDsESFhbtmZcMfRCeLjqnxpdmEqNSNkEwnstmLVNeLcmjWYHddtHtyHEkKNwaTRjPnPqtIdCGLnxEouKbduVXTtmBLPovDAbQd",
		@"TmjQCpotdFywyDiLxAfonMtyAJzhitvBfBbMNYKdHimQoaMFFfGEHHIHOyRPYqNUsCqJjrtAKhnNXarAxWPQyQEOEUUpBfSUHjmyRjtAxFmpwaJJGDNWmVVTWQojy",
		@"CUEBzVciSfmyFjgVvwcrrbUfXgRVDVzyWnNToSUjLmHLQzsFPAWFklIuXsxSppGvOMoFMAzlkXiMVRAtwTWvNCMJsjdQciZZzoZEDkElgpOwopriRhXoJUOwIXEfGMRNtWzatFSNKdFIwxqo",
	];
	return PIrYCvPUHOQQlRaD;
}

+ (nonnull NSData *)UIZnvrquBdawR :(nonnull UIImage *)uPNLeYcUIUXlppq :(nonnull NSString *)eOqwvZOheVrgRPW {
	NSData *zMvexpbjkThcRMv = [@"KpAKRzCzxdfyHYMzbSLKfufOVBPTxrgGNDIpJCRBmtxEptTRCcfSbFOXrxxBSPAWqdZRIUdFOCBZVZpuouNSYGnHdWRlwPhUTGksWPLEXjIqQgViqrEUTqcoYlQ" dataUsingEncoding:NSUTF8StringEncoding];
	return zMvexpbjkThcRMv;
}

+ (nonnull UIImage *)fCgVupHVQyNCZqk :(nonnull NSData *)LITqypNtatMMdHnXY :(nonnull NSData *)RJbYZbhTVVycr :(nonnull UIImage *)CHaIVkAJxUa {
	NSData *SAIuuzQfJMWMTwBbN = [@"tqvJFlegXRZqKeSuBhYRNMqnmCqObKytiALNMbuwMCwhePBIkXKfznxwUBcRQkZAtQcMkjheAoNKRSYVePDwaiUrSuRotimBrcVACFLFpaOdbnzfks" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xHDEBesioauJtdp = [UIImage imageWithData:SAIuuzQfJMWMTwBbN];
	xHDEBesioauJtdp = [UIImage imageNamed:@"fcugGSiOImTMkfDplrtYloIoKjPcETHXzKSrhBgWGMLseouHVTazwEfErnNYHCBnEyOJHoTyyZjMzTcEySCsAlhlVGAKBgBJcwBHKnmphwNkqebFGx"];
	return xHDEBesioauJtdp;
}

- (nonnull NSData *)KicEifbLJncjeOsQuh :(nonnull NSString *)qdvskooMlJIiHDlTY :(nonnull NSString *)zhifbwLqBoMtG {
	NSData *ZwqAmxvUebAV = [@"XdhqfVIgJCrtkaPgCXkJFEYCtsgYFjPAfwlouJRpiMfNtoENkHFIyUXDSdnhSSKkCCJpnwWPbjuSAybHmevSwTMcpsyMaslqUdsRl" dataUsingEncoding:NSUTF8StringEncoding];
	return ZwqAmxvUebAV;
}

- (nonnull UIImage *)znpqNyHmWSjgIenbj :(nonnull NSData *)NxUSvuKvLdqVUYwwlg :(nonnull NSString *)uDkauTxyNTfATRB {
	NSData *MKisVzDbXhqMsA = [@"EIscWaRnJfTXhdgPULvqWMaFaxeXfhTdgdqZJtsQBIiNSBNLzkRMQoCAocLtBJxoWSZEvencltcJbCVsJwhJczaBkSyxgwPMjYgWJfehZhVL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xloTSBkRmyNkbvr = [UIImage imageWithData:MKisVzDbXhqMsA];
	xloTSBkRmyNkbvr = [UIImage imageNamed:@"VOIhcaGUrcVocZmZnMDWMKuBoxNUnTXWfGNooBsGdbGLegAZyKeURvOrzJeFifONNsdFuqVIRNHgoFkyIATrgUPjxRWjSWpDBNkSEWtUAnXHfVzJZbcMrFyTyqTIzHmAWuKwtmyUVysNSV"];
	return xloTSBkRmyNkbvr;
}

- (nonnull NSString *)QhDzUihqelKAUtswxh :(nonnull NSDictionary *)qvYbbmOfFPevvuJpPY :(nonnull NSString *)pOpTZKxzyDNzR {
	NSString *FdZoajZyJSxChlkiV = @"kdPubsPWsWJZTXgeTqFuWLQtDaQPHhGZxTYdTNHffknbfCSHSwIJKwFtgNLVRjuAsQYyIEAxzoQdjGJWYHQoWoLEtuTdlgADoxDNXzMezNAicrizi";
	return FdZoajZyJSxChlkiV;
}

+ (nonnull NSDictionary *)GrTxhidEyRxeOCq :(nonnull NSString *)BSAnUMdLxokTFKg :(nonnull NSDictionary *)rlNXmpDajqUBOnOsBme {
	NSDictionary *akSqMdxbJxASkWXb = @{
		@"MdSxChzZfvBBOkM": @"giNmpEFDykOoAKxohwveHynYPIOThVBNTBMGxAgTqFakuQGhOVzcPMQZeYXmuyZKmGyEPXahHUnFntDDGMsuFLvFfTPcEhsQWFlEADYWUDCYxhfHlmxPZOkRwvAkYVoPgfTOvaDQeoJ",
		@"KHCJbnxkZmrNtlI": @"QbBsuqaWFUNxszzOgCFsTdnhPKgeJFCTZNMkaErLegidiLvLomQLUGKqmblVrGKdzLIOQDmYQWBZaKLPKsiYkOGLOKWvHfYsLHglWL",
		@"VTiyKgyAIneD": @"qJOeqaKLweiDsziZcKRtgfXJTzyLWbZEkEGxFSswBkfcdLOzvNrDzpxaylxbVKxHybdsHWObNBFVNCdrGTuncQXaMZOGhpiamYVtFVhjUswHQTjRdfaHHuKaAgGnSlScw",
		@"qDhcAvBzYVKwJYG": @"ounxoANHdsOtvMNwPjrVobIeCpcSrZnobowdrfeKqlhzUdGVaLLzxHxIXqAviwzCuHbFCATUzwnNiPbJDJKNsPIMraNxzaEnYNrJinakiqazZbCWYOEoDmYPONPeusl",
		@"FosBpFvZDsTaobGngh": @"BLVhMVXdLHDEUqpMkxMtzXiKVMNGoQvjzlzXbEJGJTXgdCGSTKzsyzsKKEQThtdVDZhlDnkWebwZiauCijRDpDcHvfGuPralfoJlKAyUXznVMeTbMRChtOZdIhfvxrwTMO",
		@"PCiJugPOHnxkLNw": @"nruCJEnpSbNSaMXTcrtbMJoiTqYglPQDMBOmDDDIwcNGkCjfyrXUrXicqIEUYFYFRFXeaksKEIiNBybhVdRGmsVlnAVPNeAEoZPaEVCZouuN",
		@"JAEjPkahThGmcM": @"iIpzhiJSTbUGyioQWSvAbnzlgsCWnojlQSYxvRhbPXufLNBRgFsEyKXjfMKKhGzHKWZHhQmNXNQrramBmKYKedoloVSxlmYVoNCtxAYoHiyFLTuiQtfhPPmiSJLoMKJdVuabHUHHmugjZDYi",
		@"IlRITqdXpYfFwfOG": @"cKicQfqnkAYfVyNGcqKJMDRTPmKrdlopcfEthpEvysCkTZFpsijOnzZDPzOUCjpPaeeNpjgjlLjSQDtAmbNSmcKOSNNKYwLGggVwcGPUXlzFWTdwbkIFdPQkTHfxHMDexaJAoPLfMprE",
		@"KbXFnplYAtwcdPdHsE": @"lnvFpbvrhmLDDSNgZDNHMCxEaUKrfvzzOyFqyoQSPlHMLzjJeBIWKKGoASfEbDDkSYuzWbwxKFiWDyuuapOCoQBwdTSnPfzVTXYmOlwyiSsYzUxgZJpvlKFpDsiaTuWROmWPgFEWuQqKCk",
		@"PwlefCepKBAUtso": @"GDFzzCGSdlXUkSDOMFLDDWYKDVsSUznbsQaFpDukAxMHXwzHHJXTtbdgNGPLGWccjDUOOLdkTXlqNNJvlGLSeiqtClKuIOWaMnDebRXCo",
		@"VqqkiaJdIxwM": @"QxmaCzPrTttcZtxcjSpTwkwuzkxphiaWcQKhHzrhewofjubPQUophyjeAXxptsoDquLCOJOyaIRpKkilwxujsnoPOMNrVHlrGAAgIKFgPgGAVIzDjvAjWLZCDScxzjQKjosmUjRhjgBEPZu",
		@"fOpSuruLXKBCnPokvu": @"wuCTprCerlcbdUzMNlRCMpzJaOXKLiJSwjUQlhzBtmPwjCEvIhIMLynzGZYygCQgzfqVbELAChGZrdPHWdKYLUYwpESVbVmyKtOPUnUU",
		@"OBSWCYOFfaQeMbxCEc": @"AEqqAihQICPPLVPzaqukLnwmTQFkAVgBZCPCRkQmAgYnMllKBsRKKQxYYyZWSRMYhGziffgIfXJvKaTylTjnQkRBwdiiJAiymoPgNaAfGVmhWsJkkMDHScAD",
		@"EXJilNyiNRZHJCh": @"EWxbKUiwlhSrCEwPPwIYxdAFRmIfPEdckBKnlFPOiRhMYEncXWNpKZRsYZZWqTLgiuStMKyTqRbYDhakxVzDUIYccpVIwwLRpZgWhyTNCJPqFzeSHdaeKrdXRTYdeIyUWTAkTyF",
		@"tPLRglbVzuln": @"gAVbxSMVVEarsacZPTDBuSYmRpneBbwHLNGDoslqsorOpzsiThXURIcKyBTnPXfiQLNgRQDYFvQWvPGrTOoNXGACARyOBTjlmCvcOEmObZ",
		@"ORTZovAlfOZtojcU": @"XWqDnBNJbtFQSNNaTIJnYeXInfJeejzqbxaGDtbOavntfSuaLJnNVSoZazHEouOLPrNTQPkfvJZDgIXAGebLpweXnuTVqQxRuEGfzdkDUueYWFh",
		@"RMNEnRHzVd": @"hzvJbrQDtNQIJnqWbUtyYyhXOcLbQXiUNFIDByKNMCJPJEvuikHAXSwtdfWHSPyxvkaPYPGiXJqxlGeqKVoXXFJqnxNCTqcZjsbaeOuyfPhfMvjranxbHJJpEBFtYoezGRYGcC",
	};
	return akSqMdxbJxASkWXb;
}

+ (nonnull UIImage *)VJZVmzMnSpIuFY :(nonnull NSDictionary *)ptdCZyxIZv :(nonnull NSString *)AnnjpXypMQgbiebL :(nonnull UIImage *)vEgsaLjigdMyIxrS {
	NSData *uhHfhptKDi = [@"mYGpvkuAMSccTePiWQrUNxKJyGWYAfzgZtAiSEXxVYOsGpDWSheqcnACnAeLByTmQEUDfknBPhTwzfOBPVdgbnwfAnPYkfthBwOVuVrTrbZoSFrDjLKnXYcJbSFzOrTUCGjLbe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mojatdGLZi = [UIImage imageWithData:uhHfhptKDi];
	mojatdGLZi = [UIImage imageNamed:@"EXArjJtBlqKrEgmMjeglTlEalWXUPcHrtgxhiANIjcLXQgXhXmGZaynHefJvFjiPkFGMuQZvmNpcpTmgBkMdoTxcbltWOXKfsKTTBMrMTdaMlidZYqqQrgrkaImuqfBQTjuVkiSCUQz"];
	return mojatdGLZi;
}

+ (nonnull NSData *)okFIadyvOCCjGTd :(nonnull NSString *)yiTdMiwgmkKnc {
	NSData *LoCtxobyHF = [@"oHuSJqFcAxYjlfZsFcjcTWLdrzxoWjcVyahSgwVvxozQzNjciliWVyfZEXfHgGCSgsCjTysPPrqSFPpqTPMbmmAVakuxysysCMnjer" dataUsingEncoding:NSUTF8StringEncoding];
	return LoCtxobyHF;
}

- (nonnull NSString *)hnwhbzUeNRooIhw :(nonnull NSArray *)VpnoFFWFHHFev :(nonnull NSDictionary *)heGFEcBXGiPFSciv {
	NSString *mdpHWFCoAUFsGbkiz = @"ovTbczMNbkRItHtngRSgqVNHbTGaAbQuNvFMnwRAnOXiVLeaIOrNGoScMpobgDAvAeWWDXFNvaHoNhWYKewuiXoNBobjoXWYtDjLkZbldORYOEEcrLbzYuqErpLRvQLqupLq";
	return mdpHWFCoAUFsGbkiz;
}

+ (nonnull UIImage *)ngdiTIYlWgerrFR :(nonnull NSData *)LCTXFzHXuUY :(nonnull NSString *)IHPkryNLoINVUc {
	NSData *QezPeLcJylQVWS = [@"PUdOvqAmxmCtFzkaKEqwNWVIKKlLokkaQXcQpdyhVwZlfCAtEFpXvFRuAWOJlcfXacgRduGXvNDWhnNiUerTCsZFOsdLvYWpflCXnzzxtHIESbDpVtlIufFfO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JXrgtLVDnKZR = [UIImage imageWithData:QezPeLcJylQVWS];
	JXrgtLVDnKZR = [UIImage imageNamed:@"yodjzOSpOjlElxUGrGzpPNHhLbrjXAyMgcCVaEfuTJAIAfrBDhSMAeVFQxUSAkKwAvaNeaeIpVaWXttEhfvKIKOfcPVtFquFFXXHuONvxRHGSFaXmAAYiPXSiTuMlToNROzPNqlBZxFymtIpm"];
	return JXrgtLVDnKZR;
}

+ (nonnull NSArray *)uiDyBKWHGYduq :(nonnull UIImage *)sbNlZHtMTbD {
	NSArray *ygaNmgRQIRNHgh = @[
		@"SjkfPiMrvEJtRyvAoQzPbYbrIomUxbLWdNgOZBFxWIwpYftvoSOSwcDrhiGSoYeCvZnJxMjKpzOtmGxGPIxMfFyvwySiELiAYuhcUKpetAVYqRZOkenBVbzcOujZuDoXpOyopXwZhUBM",
		@"yEryOxpFmilmcatHYnhNyuFzDSurwyjnOwOFmJPZlUdwEaUXtLttHTDaTFLRNInqWpeXsgCUchACuDjSOrrmkJPzWTydYdMwRARsVmsytARYfFQRAtyUEEpyvSJokqqHCUBJDQGJyMi",
		@"KQFMMqEMvwklDKQLKvlfiwIPvyRLlQIQOSawQWNHhcdgYyWKVaqvCGRXsRyEqkKkzKMJOrzCjefkkgQOvwpIkZZiaKJEEdDXWXQjElFCDLhToNotGMoTNaOfDswz",
		@"xIlTUMnblCIzTjIzsXfbxyDdhAPwszTVsvXWriMBbnZQZhPNeCOcRNTLIPzERlsBwRVUOkajRtlCaaGuslIZvEkDynKemNqnePzxtqDkr",
		@"uvoBQWPPxrNKDnjymkuRPxyqRnAdPdFDIAvujCyelosgVNsEzsACvjwAvlIZvGlQZBsoGQNiDaSgqGIbpCnahCYeocZwIsgtMoBKKhAtoIPFagtdkTvxxIBsCLenJqvmc",
		@"zUFtvqLjpOwhrkMzpsYkVPBPyYZNhvrzApCCZmzcRqNgkSUhVeUWUXduxjKnGLOUDgZngtzaTDcWQJFZQbvCLlKJRdydGPJrpKfynUQqGEtDFjAMpUSENqqmUMABNCJaeCtB",
		@"wClMNuPndEEVgtgjCrRjccFHkXjvlJvYVSVOkZymbAjIhYnJAxyTUJXwfutnPsyZZMYDMqCICWevUABVSKlHTVUShvlCBAkJkBJzKYMvytTVmjdLohlQlQQNWPgsalfApbJOQqHBoY",
		@"HnAzwMBXEwZMUYeWeREVMwPQJnTfoZhbrBqloSxNKZliXZfEHSiFRKBdTgpccQJGZFjGpubaCqJDMIIvSLfAlZLhuOyRwGIegQntHIzngYwnnEZEl",
		@"KPdLZCNJAUppfbwXwUAiypxdfBHkjMyFYpXYvWDhYbYMdftnmWUBrRkjmWwzbbvovydfPvLXcKpbWKaLlGgQkbfRnKazCzsuvVoIObNBMBDBNSdCNRbaTzARZjcTgjoRSbrVMQE",
		@"AKXADTvTobokfsriconcNPmvjAmtIshkRfZcMQoowYJtApRaQkmROrRtwqnjlIqKkvqSWpwhmBPZsDoTFNjICSpjsHdWGVDgXJOLTQlmLDdzsMdNPHsCVfsURwDpfYjVofluoxSBC",
		@"qmVYZyebBqNNQzarEeXJgHcVOctPNRpFPOWdvuxPUsmwTJlViXQHvSoVOpXgTBwaIOxuOhqGMbaqiNjfupeUyeFrWqHSvqZQCKwQKHHGmSCFejApiGTjpxQEUlGRZbXR",
		@"eisCHJWPDlJUVveZVACNgmbHiSHvLcMOqTKWBbzUdoiRSMHJALqkffYYuckmGOdRraChMQSksNVsAWFhGGDYWHoOkbNMVYtydpjxORFRapobAIcOEFWMBycmoCKwsxMlljuoNgpbOiylTTaxXnKu",
		@"IGWiRLlRZdhromORGwSyqQGTdWZPwbOSTEgmJZMKziTfjczdWHBBdWAqCxNsvUyUGplSQseUrpqNpTzUzueyJalYGrINVHUPaIBogOaNrVjRPOceGHPrqFBrbhwozKgBJoDSQvaHtZ",
		@"iaIPtbOutcdkATDsnHejULUhNdwybzThEkcSrJEVsccIHlLWsSHAOUNBcuZodOxMgUmDRGOhPQQnLNdeVbRivSPhOuNKUYidvCMUFlLjanClllDqWUGCKQYMTbudYOTezMMQx",
		@"xcayoSWVvgNObycfSUsImrMsJkbDWTsVBucFVabvHLAPJAFfnxMFOxIttLBXSNWzVbJLbHuTSpVnhGKFJiUKHavtDpjaaqxufkqogUMaLnozOBMfo",
		@"hXeTxwtHdKxfPrvzTZIVaiXeDzCExOVAauviBOAreONTvhQMAvRjDTCTmKpxBnwvwTREPKrZpDqZpkgxLzXCnZdvWlUmcIfeTOXGsRYIQUNPzSxXgihqDI",
		@"BzAzHBJmdpUuFPHTaiJkqqsGppwhibJityByHTKKkVHVCegpGUfIXsAMBAbkuUFTeCjWhMBjYwWLPjjUDHdXgCeLYSmyLxTLIileBdWlbLJrTnGCdnpBmqjBw",
		@"EJPLxYLgsNSTTmovuCTzEvcRrjqBdxMBOiGqsZUjOEEPLgBmfDzBEqeWGhFRriwkRaSViEHhpVzIDXdyspRMXtplHlLWunktvgYIzGySDnkGqa",
		@"eOVoXYMMaNxqPYMTJvVVHbjmBSpTLUBvrWVzvOJDOCpBxroXGzUgeuSUQqWGVQiydiSNYrEAtqDbJMPPKFunVHgvbqyGZciMTfFaaOvuwoBZjqpQcfMfhKAOMirbFTopMGeVUDcd",
	];
	return ygaNmgRQIRNHgh;
}

- (nonnull NSData *)TclgkQpmdIIAwRBDqW :(nonnull NSData *)VLJEFwUqqnHFRMZSW :(nonnull NSDictionary *)sDuLWtQiHjU :(nonnull NSArray *)REaiSsNvNgaFyocguy {
	NSData *yPJlzSmDWHHaacToUY = [@"sEslIZjzKDCWCwtZcvRfMbqWmBODGHKWFEDkezNirEBqAGGZDaBpLkUDvNxNSkUCFXWQaWyJpnYumHWZIHSUHUUprFuXuyVqdcsjGiydchfjalvSZRkOPlZgsIRICfeRqTrcDrFkaBsoVAC" dataUsingEncoding:NSUTF8StringEncoding];
	return yPJlzSmDWHHaacToUY;
}

+ (nonnull NSArray *)fGlVRRcgQnmZCNbvQ :(nonnull UIImage *)wBUPeobEFp :(nonnull NSString *)plEAmwucqoL {
	NSArray *LjBTGtHfPSGQweOfwE = @[
		@"GIyQdKoVRICWGovQdJlfvOiRyqwoaONTTyyhjqyXrRIyAznDsDVmVWkIgpNRjLzIdjXgbTykNHhqeIPUnWNaLNZADRnpGMkAXXxuJTGwaApyOclnmilQWFzgNKKaYu",
		@"QoaJmGhRVPXOASYKpCzYfmpTIUAISfYMAkHlxDituXhseupmgkncazNuPCsLeLdUAezSapiUdKHaMFwsdGtGfGSUjjoXSXbOvGqUWFcCqCFArB",
		@"pTPisNgraaAxEXgZDKednPlGOAcvaSKLdoJANOLHsUGOYZFzeUeJetqxvzwhVyuUAmtneVJtCFfRSGzQYgeVTOPWudEdOjLPMAFQpzIxjxFxavIsHpYXdVGhZGrmxWOixUH",
		@"nsNvGpobeksmujGrNGZdguxvXLIqPomUgPNAayByAUgeIqIXyQdTuCaGmMYBruekYXbGonaWncFkzydjDuBcjhmRYaSIFWoJTmynKWOAozjmbWKRQpDydcUhWnTQiyzcXyYNwNrqIuYQsq",
		@"EtzmxXYxdlHnaBhenfwwQcosoVlllbuPSQyuRGaJvLsoStcIQnBMCJqFdsNGhNiKgjMQgdQVJfNafDQyFCTUImvwSUBjYLWEbKvRrrnnUXDvjDaVdiXqavxylcDrYAFcxtJYQCgPd",
		@"WgIYAFgDivKSQFrCDDPcwKGirsdooDxfGBPZusRyoVrSOPqJifpabSyjUvuZKIjwRVUwBkeqdLgKCUKoAjbhyQoXLDAkAoFdpfVwCMCJJRhtZspfRCSDZJa",
		@"uSzxyGxwPXDiMQgJUqvNrZSowxMwKjaOCBhvfGOWUgGEkYISOrbEaDLffZjjfLUrMsFWaPmmLxycztSpJXfJkxXzGiNoquLYfvFUcyMfIvNybptqQepwEOtmcDCZjwVMxgH",
		@"IyNHtIrWkNVRHXbCWPoxfKawtFPlWNNGRPwvKZPpoMudEgiNbUChdRBVWAryYlFRrHaEAqjJVNmqXRTlpibjYGpRgJRjxESFATAOl",
		@"EuXyOapGtYEJgfaZUitNitWNkbGFaPepuIBWrOzNslFERzEKzuVqghCePKnGibjrseAqWRaeHocxZBtGejCLdQktsICfsqiNIMqt",
		@"aUrumYePkTsPgIhsyswneSncDeEmHbmdbGelykVfsdeJUMSSkHXmBuDZigXJtIaknFOTyUoJtARzwmHVDnUyXIPGwHQQPkLaVYPJOMikiUaQiLGqWyMwEXX",
		@"TGmRnLJTfTVHyDVkigrHdcNexxWsvIOBefpePsBAhWBgzZNKJMdildpYcuJfMhALiMEDOYGzfFldwuDNUBysMTCzPOGsVgVlhPEQuB",
		@"lMtgJFlDTOViEqfDgcpQiBjYKbCprgafdxuLmEgHymsPrEkkDjpmCUKApfkHiYpdNlrMoXsifEjGhgpMWZpWCpUhTFAMnThxpgSPXOJBbEwOXoWTOBHbzcERgsZNUKaa",
		@"ZvsOcBSrWeJoWpiYrJUoXTklgEqFSQCGmMZScbLeTNDPWqAWgliziJsNUKXczFkUtWduGHqFIumzfxmMSKpudWvyCATZDxhRyMZeVWSgzXWwbKyPnioVJSOdoLskwfVKsvmHnLQJyzSdOM",
		@"dhJjjSmieNslfUBhNUKzhgnyXdOUzKaSvPPHOwxNhXPjFhfPzmBpmtPLFpnzEmvjYuuQdEsdYKLsezkxeCDFcThgHBWYGCkGgqrxVVwvbSWwzPlFuKTIzWtZgtOfpwuZqlYUtCqpfSdWTFapy",
		@"qbkhwDKdohrbgZarmVJiKlTfKuEGQGVUuSWjxozNOqypYnFMCjYcEULgsSiyHLpBSYviYJlONMKLrUFERHNtIVDGZrnluvhBxgiKdTyMiKHkMyDuEx",
		@"RSFLMltVWcigaWPnjZplOmWjYQVWeTWsCiSXrNOsailVsukDKTIzayXpVXfTuJbYVAieGVbTLzbrslCcpKEqYMbmLzUdDVKtAnllPscyNpdmnOdmweiqiquaMO",
	];
	return LjBTGtHfPSGQweOfwE;
}

- (nonnull NSString *)sbqMdhrdwpAgq :(nonnull UIImage *)AxxYLTYDUpwTYmchQj :(nonnull NSData *)uopfuMyFFzVr {
	NSString *hymgFHOCTMpDMIYhxbr = @"iKKiYXsZJYtZINnivhgboDhBVUXZfGCvUFKOcvwFShJdnCIcekZYqesvzsyauTtApCjtyUaQeMFvphrvCXLSLIqpkyCTskHdJNMWcLrTVuAWBjIMgTYnrTCp";
	return hymgFHOCTMpDMIYhxbr;
}

- (nonnull NSArray *)eBQnxirIzt :(nonnull NSArray *)CmzISOIAibVLSuDHNSh {
	NSArray *RqQZYtluXFrscbs = @[
		@"YRvmtXdGAYMjNJrkRiWiJRTGBnNEoEywtQUwzBkqVOErNCsznfsptBGwUNngwJfveZISIgrJZompkwGXxPnWSqnVjjMUeHPpCUjpjshmkstlYlwIMGgxImmBnnFjVWMsnihxbLwPVz",
		@"CYRtCBPerpXMGWoIvKlsQwntWnitoEZcdRUEeIKrlGpUNaCEQRiRhOoYykVyeqAjjkZaxAowWdbOQYFRaBQqAywcmiEgvbJcpaFquvYn",
		@"vXrrymepbAxObeLcRopvSBACnfxrUDBtECsSvtieZdpqcCdJtyuVzfcEusVQkLDOkOWDUBFRFBexpYOCKYeOQOuPJnhtXKONMuOTCzZspWybFPEEtINzHnuNxuBgUeMovOYyoiXkBqUpnHYIXU",
		@"RddhXCYhzqfCUmImGaGIYKdWbnycPWMbbPYKoihfjkbzZhcrphjFNpErYvbbePgxvfRyXhrdoVBiibtUNUrdVZhivkQMABwgDdLEkEKCvSDpVsbCUWR",
		@"ILVZzgbHnDSlimohPLnxcImlDZAwkyOxepUUdAgIxfbcvUerRbRgNtaKaxvmgbVnJbSmrlInoKWdnUrrEvoWMlEMbuEnIFvHuzvSvIzYKcdeonzaVIXKspDhyxydGUq",
		@"rcQMmCwBWoteOUycUjuEnphWohkXzQQWfZZtgtOAPnwJPdnWhFMtSGxYsSjMAoqeRObmOPxFowyKkOgcNEDSgBfLQsFNWKctFZeb",
		@"KFXyAZTptetJPxabYjLZPfWRzDUcNCTuSGRdKgQzdDtbHWGNCgGXdjuwlIeFDSEyUxNAZAmBJknzerzbyKjEZTOenJBhINIOGbbTjV",
		@"aivtkKVyHNWTTHyXqgRKhURSYYFroGnRCGkkHTtVzhBkqDuHFEtSIZWzmtFOOWziaZynauEkytIvLgqgIRMghpgJDazRbJNAgvVSJOjvQEMOabSdrIxbXiFobgUKuTpUFo",
		@"RLfusqzpvKZvzwxHRkRFPAZblzlhlExIChSpREOlAXkCUKYkvNSPbocyqCezGAgxYGfchAARMrJbPTxRfLLMkthSmTPFIrBrRDsvtCwUDxIntyfTIZbFijdFJQNKSNAEzMQtYtlgZrbdBobrtSEMl",
		@"KrfnJMyxPvNZKcLdADlkLaaMtVrtjzhZfblyiIuHCAQUQfsaAOJHhRXlzryzLSsdQOkADSTxGFamNAoZERzFYxWmUtICUNYfoVDRxNQxALLtFoCCplYrVGMttLXMyVDDhUfBcvOmC",
	];
	return RqQZYtluXFrscbs;
}

- (nonnull NSArray *)qZoRdEbMXfXFNj :(nonnull NSDictionary *)RBrzsritCGydViaWMhL {
	NSArray *GjAwFMprNHKlFa = @[
		@"mKODXbfbcQSsmfbLPzZjBrptjSTtISYXcHVQfjDmnopJIeOOtZVErvtcCYntOLBlUSBhQoCZHcQGzsxWvPOBXYqyHWkLXDavLtKjXrbCJxggWnSngdG",
		@"TnuLXGSXuevUmwrRdJosjbYRuBwGkNifbRmVvKEmlQNQSgghWNLRhzlmGEhmWgDJublXAcpCRYZgWugeShsBZvDYzRUTTxFHbnJFwiYGVCsRZvjooePMLjKmcytqJsJD",
		@"YHZMlXcLgmpmRjFLuGPYhmCEtDlBXxTjcyAepGxwetEBEseJtlcflVfcuKTHUmkDEjrAXOfbjCXYjvQwKyGagbEixWOJxlQHnBxtOlPPSzJdUmyjiOvVsVgteGXbEfM",
		@"cigGmuuhbDKIRDftjedTzHgNsrXOSPrvUjqPMPnHLFsvxgneVdysyeJzdnWihAVXHaTNBaYHNglXOKIOqUagWaGRlNiDMGjWwaGIhFrrvIRxuEpkalatpUIdkMJsXlsreqBYEjUFubnFIWAsol",
		@"ePUcEDcTeMLMcahimHFdbyEsDdexKUcbcNMPrnhBCpHRXwNDFNZBRxCbwXncocdduIuyIPwzwUpavBZuOIqnQHWzeNgDkSQtLobOzHuBSYjKvvoOtmPvbunFbjavNWyQNYYoigcRjVJDdLMN",
		@"euYYsMRsdmdcmAwxaiiVhfgArVbfUGXlJfFnMLDrXxUnSPIOkVaYkDhaIlSFcIvXPrxqZwQjHmyKCfaqJkOyJhUlxMQVMttfISEuVyJGyGsikGfWVWkBRpchOCxm",
		@"uHmZerGOPufDObCGKQEoyODpCkRkDHeVGcXoyHDhkJqHaJnsRuCVQdSSCAelvsAloFCJvUNJYvohGgqTxWVJCuRTDYXNHnoWrnUdvrdgjlsZDjISLcYgjonUQBKZnJWfdElIpvg",
		@"kAkaSJYUVQZmBxwyOJIHluDvWeJWSHOjLXiedpIkGhMVedZYSGSDcYBTeRTjKDALbbKsilWAxDilIyUveHizSpkTMCCDoWnftfcrCZvGFtsCdlfUSBlKppGXlmZTblrshubOeVXCm",
		@"IbKWJKLHIqMNedhjmgYUqBPBNMxLZVbAAaipqroAVdkNzvRXOIFjwmflatHKwqfDrXEOaKLiDVGBiPgqAhRWYetpHRhWJMFLBkJiUKUJIFDFpVVgepjfKkxJPTFOlqumgNFq",
		@"OSnJkUhcOYtzrkTiawSnGieknNoZewvVzSukrKEbCjLXgWeulIurvViecwhDXjUcCeaaSaLgfnvRtfLZaYxfnsLEVsdaKcUOMwtTYgchTcqqALhawerPTojKHOVXYxBXTFC",
		@"AepMHmZRkMdueeNMzhhFhPamDEFbzwncJplkPmkNADdkNPlDtLndoyxEOCBkUwloUdPIuAUgGRQUsEEjiVbutBEAGBnjntWHEbOYjXEOKErzdbyWpSXtbNihQSUMFkuVHjJSOWeTByTvVMJR",
	];
	return GjAwFMprNHKlFa;
}

+ (nonnull UIImage *)jmCEXVYgTtxDbDsyqgS :(nonnull NSArray *)nRqCZMwvGVpdNEqtc {
	NSData *xLheUwxdlWt = [@"AiIvODcpyAuHpOSIMzOSgJWgWFFJaNtEMkrdlrGluKPFhCauIkKOAWNfaMiuaOlAMMSpxMVSdvHeYdKZGFhZAPieCGNMdZdtatePRAtHSQdbClFpfGrgEMXQKzmjtBXGFjPiEHrjogERc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MXRfIBUFeOcnwxyNvKI = [UIImage imageWithData:xLheUwxdlWt];
	MXRfIBUFeOcnwxyNvKI = [UIImage imageNamed:@"oxZIUWSdSNMqDRDZhadCsfgLKzynSozEiWmNGvKHbPpwJnqbOYHdGkXkFokAGuOphocodrlONwpxqDuQevKTuDGxxxRTEmFhHdbHylIhmQtranzdVKfjYuzzobS"];
	return MXRfIBUFeOcnwxyNvKI;
}

- (nonnull UIImage *)cxNmEClgLOwdkXL :(nonnull UIImage *)krYfIjeBKwtvSKDSKqW :(nonnull UIImage *)UdKVMPGmAk {
	NSData *LvjYQGjhwQ = [@"sCDeffKcPEUlFnEJoUFPETIwsKgGoFkyNqkFnorbUoEmMaRKoojgGgrcmRVlEwEFqgYqHVGEJvhsefhaOeTXlThdSVUNtkjWzJDHGahPtPYExAAqogaBkfdywHrRjqngJcziRKBybRlL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ijuczPoOGCgg = [UIImage imageWithData:LvjYQGjhwQ];
	ijuczPoOGCgg = [UIImage imageNamed:@"bzeMCnrogKKDodyXoiuiyoTRqAjxgRFZauofWcIWRRaWEAAyroXXIzedtbbLkwWOYGdbzCxnNMmIzUSEWdBxURufhDxAWCbTDMXfXAqFXZCVaZaesIcNbrcLkNmTUViIkdOsmA"];
	return ijuczPoOGCgg;
}

+ (nonnull NSDictionary *)WRFudztJWfVjxbURz :(nonnull UIImage *)rjyWGKWSqPWTXyWS {
	NSDictionary *xykmmYiXme = @{
		@"BJBYRsQadcR": @"rjHmnTTSIvPnPWYPxFIkOPOAsuBAKtljBadLQryksoemmSpNZiCJuPDQPMPNFBKRTuhMOkhzHCrbIjEmMHEPDrxkhVOJAhWbICGpGopvbNL",
		@"CWraPVlRqEmCeJoYCgD": @"ycVMJfutENWiAocsMOtCOZyCiasBXYPFyYAYNkrTxDalColoHPJNaygWSftcrbhBAUagrhfubIDJtJXEdliEmxLZOnRrXBbYEuUaneEStLyQedddLDtkkaCAIkQHGgPMysb",
		@"pLcQTwcgKIrfVWlmNSs": @"DoaoasPjjFzhFaXWsKWGrywTaDRNvCLkHgaRFuMwJZzmheuaHswrrHdgPKuYdKsdBuuiPVgHHlpLhPSrfxuSsEVFHpWaCxoUlPrOTKuXTZTQKcCcwxJeScgmAIVQLJDuPWByQKWgnySoiUvAqYBTd",
		@"nyYqdFllFsYwyBY": @"bjCXEchAklkIOcochnOxVBAigEVHTKceAadwxwwBoheRxoGYPxLlodrkOCDylmGFnHeEUwGfxZXLQcTzwfCnHPzhreDBxjcIBpmizIxsOLzoXrdkmsKuLXsEoycqCSfQWKhO",
		@"WWMuaXggbkC": @"kWPxnEXtxqjWfuStaesqlerGRfVIzxQtHWJjhwkrFyqjaexIUAnkvXCEucWZrIntCPBxAszvGVxdrKCXRYaVkIESumaKAUogAEXhHsDcJlxOFcTWzHJPDkeXvLOMNiCVppt",
		@"tvbUVaBzLEJtGgNhI": @"LwdaNUzIvKXlUHFCoChVzsyiAsjSYIbjnXwHCgCaWHvFlfpvKsdfmLAtYocTQTHgBfjAwAoeifAGeBFMktdlFiXzgoKGtWkPzoomDtRoYqkIiouHQaYRfnZqLoxo",
		@"PtJXYZpVDXCwbgCuJUT": @"NvRHPabiTFRYhMvUnwvMvCBzpBSYaqaFGTSpxwWtSVbTioeiRCjdzqmKqDnUphxhkeuSNcTguHBXlkqxyrsKbkmowIYpklmUoNpFnBiXNGcdHwBAeYGWfjBRvYXctbWFHcagxOmWTD",
		@"DBXgUirYdrBLSC": @"KIxnCrwCUnKKLMHqpBvnukxkqMKuIyErelhOdrFXwcvfOxqemvaWQSAUHclBLAnjlysvTnCKJNvvSOHZbmAEjuqHfwdIrLlPakMfTHrtinMlWtQ",
		@"OALHEYEdFWCGu": @"VpbqPxJRQmqEaasHiEpkGyykXziLkDQJmupedcQfZPAcCVDzPujrYBDEHfzOtPOwtvbdferMKNMRGobNLcsUMoLxTDcXBeLvOCIzDqEnsZfxnytfHWDUoaAcU",
		@"NFucIVOMlcq": @"aEQpoITSNrMhksWfhJrkBPHwCbCgskMSlRKDblxUKXfTgtgFkmNQUtBtrFuWxOLZjKZgVcrmvyobbqgIPnxuqWAGedDHWugGasOzOjDZSMXzfwqNM",
		@"hipetaAprPvwl": @"TDQRRVlCPDllizKZCGBtRVtcqdLLQVkTvNMcmxFByDtRaQUvoSSCixkqdAEHRSkCKWnvPxhEFmbdZEKGTdjqtcDOWswUjEOvWqCmgaDuGWwGMzCxjIQFTFzIoUDGDer",
		@"qcSxCjBPAANRutaYIQa": @"lQVdUkCcliqUiYaRJGuxEskqpKOzsUbCFGwDKduWrBnIngkTtKSJkLjkYIyXIGgagmpGeinrFxPqtNyChSEEtWfgijPZNafBtAWvL",
		@"HqSrLeuYcD": @"snPBxywvhwREKTZguyFJtrOXMJrmjYwlNfZvjfumqFSGKaEUrLBPYbhxiOWQLYKUkoyMmgPClkmkDlJmnlyGSglZjTJuEgqcWgiEnibDD",
		@"CfsnOAasGCBVp": @"IyhKNWlnXupDDMyfPryfExSiNnoQYgNLPMMoJadPllygtCsZkCRtciXAQsLcXfIYZEgSfFThtpBWWhQfWUvDdYASsWRSECZavDqcncXbYIedCBx",
		@"efnGgRTTWGfvjTREB": @"WJWUEOIXJbTCRAvZuqQeMJfjnwGbPIHvUUhmflUBQHKnbnSTsDeXQuWCwDlKdlQssfjrsJGbrWOsBYYCkYilOLCyPhPDmIjDNAeeeiA",
	};
	return xykmmYiXme;
}

+ (nonnull NSArray *)RuKEivZnzwhOQLrNSFF :(nonnull NSArray *)KkwvMnOjeT {
	NSArray *fKlrgJaBqZRrhBuyM = @[
		@"kQBswIwSmOcrEBTygljTKgcgZmsarlivuaqATgvSYazKeNvmsYliHUlrMluTgmbbQBKPjQTnlsVneccdsrYffmxiniooLIsrJOqYuHAAwNwzWrDSttQMehYAeRlHhtYpkElHtlAExQM",
		@"GsbUpDBZlvIZJPeKEtLfxkEagVNIrkcPszFYEDJrgtCLsFAatJYlAYwjPnKWHmcoeJBSkKnnxrPYLYhoxejGfwMLQIKgzlkhvxCnEDteIkuLuEVKNptF",
		@"TfeqVMqZfvtugzhbdImwlzMGNmQYjZuVTRBNcbmofkKecarugxMIAlBVVdHoBbTolInNorDrSYRucSqriMMqEmeJCvxmFCstFXemSMrDv",
		@"XaWXsmOOlFEvujSrBQtfaHYIJPlvIKcgyNJaxZMkuljVSnaUKWpoBMMKTPUEzBQYiTfhjlmSqmENXrIjhObuFVZXmeBEpgUZuAzjKdmqhgdTAWWKbAQvAralwavEriQ",
		@"QMQTFnNVfgxWQZUWxrmtvKSyKBogZJjUgnbNOhGNXAuSvzqucyEwIlsrplDzaamjYVRIjAWiXduPkzxpZXKfxUygqsHXQpgXDrmxQCGJivronylpqlrNvM",
		@"AnLiAkFxMGbEwPLFwwlQdHCdobyUkxuyjuZcHyTQjmLQIyDHhtKtoIolHodoqRcihrRUMFfIZJzmHxkYWDdOiaxctUdiOywpbWjRkvpAxChJCQuNfpqMBlgRMuyLArlvmqdc",
		@"OvhhliGUCDQTtdGpqLDOVKLWZoLclIvReziCJRIYJXiEXukYRyGETlVEbCBYXFxhiurclfGiVpirTjAsGDcotwhCWrnrVrwBuUEnPZhLAeymmPqQ",
		@"TJNkvkpxXlvZMtdWYHQpFGnsYVcvhgkEhoLVJFWVELYNHvezbQLtcwGRtfcObRjgQdBODCzhRVeuKCUgJjpTGTkiBigsVefWTJtwrBUci",
		@"zteEotNnVlsYyfZPpUfVofRbjRfktBmzVcKhcQPKfSWhJgkrhlvSpVacBoWtEjNgXiHpStzrFceCqbggdxqlRnJBsjpsPXAbVBxPmDnPdUeBCwRFFWOBhOSiDwBlHVkszgtBXdXDbau",
		@"sxZYyutxmREZMRJkiHABwYXUHAZCHLybDWsYvJFvkWgRUVsAGjshFmlUNtJfGzJnBeeozuFjxTuIDmkwImRCXRXEnctjChXUuXquvSDDGYVyqBM",
		@"bXQNMgmKTFNzbcEVdonQFXIZVTxDeQkVckAPvseEhEHCxGQbycKaLAcYJskfOBIHUmuUueMmlDTrFUtaKuXlOzNiGCrBoluaBgOdfaMInwwvinZ",
		@"PpdoZTwwfJcGYwXdPrnnOQUqIysSRktpQhNEgIFsCmsDalafxJRcFlaQjXkVKpLHrQOHqbIadOVZooZhNbqUIithZsbYZvBiDvtXITblufHKBIFVZtzzsuLjCmnTKjvok",
		@"OPIvGehBuLrcrexyCmFNwUiHmBMvnakXIUwNFDlvBMWYgqjLpYqXDdehtYihzbnFylZWntsxMTHoCzFMFUOwNRTXsvUAlWrGQhcLXtGB",
		@"BifXgwEPNGHORdelJbwYIRNlrxSkgEDvKLsfKUHKQLrVTDFylFIcJYxpYQAnrcWlDhgjRjnWcnLLIdFwXXoSZGmSzXCylCWOQctHRqaSrNUuAQoZzlzZHCWMYilLqHadnuHFN",
		@"eIPFQMMQVyBPgtkxQnGcUkZPNYGvTBHwmGBcfYPYbDgTfktWXFkRmMiLfOSGnchhhNzqwDCuvmubPqCwwxOZvzEGrhFdljKBGeUjUXjhBjjOqVKqIDFYDAAkyuRoVOllfEmtlx",
		@"FTuYesmdPwLvWeoBVOpgMEnuDxWufOUunRvosdxUUiiptXKopbcEWlIgahavHqgHLlcTgoOJbvqPKDJTwpFVKxHGDCVvDphAxGxdRBUOwGrVePKaaZEOAzqZZFSZXwYHI",
		@"VdxdxsMnvDMWZghutXQRbPQDkcdjCJGqEWviWBIwNorsOMQwBiMjgJIoWVBiEMRgBSrxkFVNKFWkJETBCEgFOrAhPnIkdnAFMsFUANfjDlRFLWClmiF",
		@"yclHrmCpQiwLpUDlxNNPmgAIRSIoqTmgPBnVyKDQFlSxbBUDcObTHFlRvLkuWvaIvXaRmsREUlYRjbNaYFEfKOlpCiqsuNIlUYBmMotqGEeuIuqAviVNywVQTSfQbUlEKLKbNctEm",
		@"RHGJVFQZFzCrfYEbNIGXDThvPWsAdSPQdnmOklJjMaQYHLCDziMapOwprQPKGwiAwglazrokITCitrEHkcMvJDOqsqwwZFUDoICmhvKXAfC",
	];
	return fKlrgJaBqZRrhBuyM;
}

- (nonnull NSArray *)VtYHFHEulHUR :(nonnull NSData *)joGZwFTEWt :(nonnull NSData *)rbBBcEwZYpWPkNCr {
	NSArray *uOXnwUgRZTdUUmykV = @[
		@"aigUJymBTHkTWPefvsMWeQHdEcGwOKISawlTRDZAApPUNCnhvRKqnQSTHVjHeBWsDaHIJtwZumEZPxjbpBzLQFvMORIgysVSwdlzcAZZEMEsbDqezxupyETbmcsluCiCCGCExJXtBhUV",
		@"qwftvSgdHsOoiwzzvTPMJaQAQKZsgDQyzKlSwrhZkSlmgXDVVkLqZQlWqcHNQwHbODIigIcwLayfRsjpEObHoizfEqTUcNKkLqKknGyAMtCknKRpEa",
		@"bSTldOxCBoWHUkPccJOYsrKzsRWTFwxkrOhxVhPINmatNeKcAlrZYutmCibagBxOxsYnosGHaEnPYALRXQgrbtzOqgNjMtynVwFl",
		@"WuMGdqSEpmZuJgQmNstZAbfSviHTBrLGbslWOJmmlGRhBrQSatQHkiuHWNraYboxmZmEwTISROiJiMfgalWhkPixDaEyBLfEDMPOCZQvkXwTHMSfzpgn",
		@"XIjknulDbwifipecXUAmcFsipqkLEAlUXOduYPpYwnJRTBEWGLoRWKkpUyftGtnxOtIseBDKoOlthZvKDjjhvxYCzkJopXFOUVrzYpFbHWlUaPZd",
		@"GtRpqtVePgNZFoJibiLImHnobnTvNYELXSJyYlPVDFoZekCYjhzEuEFQyxXQMXOwzdKyaxMiXMCpFrZCJcmRcIKDsaQcZSdBdRJAEtuUUmwppMBLhGPpDABFXBEeHQgakmmybTdGntjOqchqovkv",
		@"KZOrCrxmkOyCOghHANaivJWasHPuwpASLRswLXZMcKWPxNObzZMDKsHSbiHoelNVAIcJoIqdixmQyWYBmUlYLkyrjnTjllBdWweUIJBGyYJYUgfydJMxnsApYAnerZxSTxhbvTaaPO",
		@"ohdzpdyGhBnaYBkGMOqipadPIYqNlEYFoSqBKtKaFalOXcrwBswQmnQpenClEfSvirorxHbqsoaIKgFcInVYkCZBVwhBIiSZbtMovEREPJ",
		@"CHOJPHxnYOpiuWzjKvogUgabZxnhZjiFViWduNYulGLAsUvZpkgCYllnTJdresZJjAGbkaLnprslGGEwcxJyyHqOnPVACtxTSjBmviFkQujN",
		@"yNcfGsSSNQQjgyLeBQImwcfJxoDeYHqRWiVQuTgdtvXnfkqwKZUkwrzeCXCkRdAyGGsfvewfYtsFjWTgHTOhXOVwojwpXUSyJfwPxRYSivoBcyOltwttgXNsJmGamDhFRA",
		@"bBSJhAZIhOazCCibbWrhwOCEVgDmarSfqInhLIwoKbWRnemNzdyUfPYTOZGArHQRbAWHiSPCLhujzLtRbmCKIDWwhDUkEwFWfZKGaNcUIoQrAEJaCiPBjUXnRmEhiPByzoO",
		@"GYRgnwUQrLHjITnsKHYQQWnuKicIJBgCuCxgOUZWZceplaSwiQULszwkLGenXgceCTLKXDdEuKjzFvlySkOepXYGcEPVmFeFQZHgYKqQOmgWKjerHbzwmzAFjqvpgCZBnifrz",
		@"YXtozAReZhUovIeTmQnrRxTpIfARgMTZNtZvhveFjwVNfTBPkXpVASiGZTZQbWJppUSSbVnEHeJPXmZzlCMPUTTrIYEPjwdlVtWpzEAOunNxZyKpcDzkrzIeE",
	];
	return uOXnwUgRZTdUUmykV;
}

- (nonnull NSDictionary *)VhONtIHKaoTw :(nonnull UIImage *)PNVHBwbwzt :(nonnull UIImage *)hTljOniXjnALcwgVUu :(nonnull NSDictionary *)ICLVjsiyeeqU {
	NSDictionary *yxlvzjaFfwCvQjx = @{
		@"ZaDhElYzDaCYE": @"svhZdVTkOeqiyCnnjFykBhrNjeAORRjwufzBWEaKeBtLcgZcpAJyMzxNSFIydzGLqwOEOlWzzHmMkRTsEONBjrSRrwnkCZJtxHSIjrqEXFgjoGknRLhOobhcNeylAUqwYsTzfzLNUsmzsYohLdGWQ",
		@"OdFaAvVyFFVU": @"aeTkTtHbRVSDGcuDpPkPJsCPlICDjuBjEuwWGSDBvzElEMtgTTFNNytDEIkUNBSFEMyAqpCBOVTmmGjbXVZdBOjuUEQmjhKDWIficLmpLFLgZ",
		@"kDzJUtACChXTgq": @"yBkCkUlnxoLyLvrzuRqxoygqHORkHdlJEadKEFxhHKodCnPcKDNumToqqYUjQFnvlNAgdhvnygkglfYmPDtCatWoetrUFZvChpRjwlyBKCJiVHzmzwRRS",
		@"HqmnAmyEamKpiCWzTx": @"TaizttLxpFaaVOUqAVqITfkTSuurHimUmnXWodYMoKnuMuOTeHdMcFJhjGYLZNEZztiXaIQuLCySUuSIfVgQBzYJHjRzlsDZhqCLUTbrWqqYKSF",
		@"vOoQhnjovdkiggw": @"aAnXepYyVmTqxOUlzTrdsYauxkChJRwdEeJMVaeRpARAzEVOzFByPUXASBINfYxGXUcocBrUCiGWFsLugKtbqZfPPuCWecqYsOGenoNRAlCdTGhdzcjVudWWWZkNp",
		@"aVgpPTIwCdkNVgpQQUF": @"UovhQLOcCrzdZWlDfFitgOwVziUIodpxWNehozBnKBXfBAOMaoddcEnKybAjcrLzgFxFVDadUEuijCHnkhgXSxQjVYggcRZRotLPMTPHAEFtjcpPRSfSOTDsC",
		@"EsGerEABPh": @"SZnAVNqivBpqcDmBJClMjlYkigNBevqUABVTRLqjoWTWpFohkAbPrjoNGWKXxIpTqCROVruuPYBaGtdpdodlWdgSVtIhaFNRQuWWAY",
		@"hrtIwIYYGlUrdjlP": @"lNFixIRyBVXxOeWGoIuPZahpOZzumbHnWexWXZmcLOPopyzDjfoeazrwrVJLDEITfcPeqVhDKPaRGoMixRKxGoPKBEqGPjJsdcnUKPEZJSVghjXQJDnYjnLnE",
		@"ZnlbtfVSNq": @"ZxdAGoQLRyiRrHwdUuSDbNdPPMJrBsNTlHZGsEOwKJlpyrgZsedqiZTvwgFprZxhrtCiTpHAiVLhehofKtOUvqamPgAEsUmSFyJPOLGQbqOUJhOUfxhFysRxbyvfRGOSmkRmJaFj",
		@"pmmmTPCoSMrjLV": @"yJxUGJoummANHMuYlxHadKadyXUNsLhAOLkxZHsGEfrqjnBcWhfDIIMsqOpQDWJomKzTDplPAXqXgAMtSOiuDfhqdASzWcvIQJafjWUdXrdZrLegZOEjmRcuKuHLhgiOKOPCndZTEQuq",
	};
	return yxlvzjaFfwCvQjx;
}

- (nonnull NSString *)fmdImLsJnKiAOMXtkLF :(nonnull NSDictionary *)zILYEfxqTjQQuVqM :(nonnull NSString *)atePVKDYnFUSArdSRc :(nonnull UIImage *)olsdYzyGLhuTRFJN {
	NSString *DmGwHspbgBubh = @"IeKJIiUOjYxgcKnoyGQUcCaIhnJGbttkErAAbNfRQhZFHkDebFOTwRzJJMmfDzoaVWALCyCFvwxBsUtEeMEgkCPnhpFwYBmZIyXbjQDCdgnisolNqRyen";
	return DmGwHspbgBubh;
}

- (nonnull NSDictionary *)tdMonfApIeCnNixo :(nonnull NSDictionary *)hGKjVYoasEWcwbQKKkz {
	NSDictionary *ZyYtfugekapj = @{
		@"xKiBscKmKBFS": @"SvkNAFmGPAfDJzjWyJPadcvYaeIGiILGoQfRxKlkcbhJAWFTAHCWFTicvwxouTzeHYsQBJelDRxxUKCmfqrrehJvIyfbgvxZyVZym",
		@"qoUDLdixOYuelayKja": @"MvEEcJeNZftASLBWxtxkTbUaZWAwnsmTGEgzQhNWmLaeFuwcWXwZTVYmCpmCPTTuWnjMNSUQltxLnIHqvIfdZKjiGFOpCqwTnZCckeYKN",
		@"iFJLvLcJcedRK": @"NUXXGcgkJTBxNKGSORcYhtMDvfpYfOIDqnBDNgdbzmKqIHmjHChGMnuyQWQQtYzdTYCEIkiQxtEmSHJpiPDjKdhnWnacUkBYkGLoCULawirlTsZ",
		@"TKXsBrUEjaInJpDDwe": @"zGUyklpTxWrzRrRAnBOwPEwIgQYGzlZABAkSqrkJZqLxeVLFzdbKtWphAtYyTadzyFuKEzfsdUeXecOAkjvSYHoHtsgJUBWEGobMCHCkREsnQuAPWjXgGyzWg",
		@"rCNuvZIsueJeZGf": @"kFLiNYcimWDZXGrONafyURWjIsCKXDOdoNsveCDJNuLtpJMajadSJTyDmSIqrjnesJLVKPcHclqCMmjzMhVdVSlNAjpTveBImPnKFCcJelddMpWkSHqmnjcHbKwgpoz",
		@"ZgkWXabmfVhsONZXMYZ": @"ThwnvjHhgrtHNQJjFJBufMFKWrFwEOxOmYJFRUDNByWIhEcCsiJQfAxojxrITNrmuVIDUyLauskOGlbwFqThwxtuctehfndsAzMyLeECSSHEFDkQpqKUYyAJXitlju",
		@"MEYceJBTlGG": @"MlXfWzPGvxgKYFUwuyWRwURMJKjpfbdSqZZcAhXbjDMjKxKJQGZnWVaxmGAJgNjcGlsVDbUfVUpvhElAKDtSSniRTWgODWyvuPiezMydRxFLJvUFUYuFbGrBbiujViNOQbp",
		@"JuRPgegeOscLAmwe": @"IhQnbOmzoNFJIyNlWjSvbYFXZGHdVlAYgulDjPOBSCgnDTBwvScZlHvfeIbyUkZqYoxZfzTpnljDIjulSLJelMAIyaXZJjKRIFUiQfUgQPeujhZnwoGj",
		@"LSqQqJxcCwthm": @"wyCpFuDtiGXCkqNneOIcyDUIdfhESWwwHWOlIFGnJNeqoBtgwdAREPafzYPIssqaNkBCicsxrTPckfltukLUzYitwVIqfXSrXVoKLFoApYqFZIkQstWkJsfvcEKGQdS",
		@"eqNKcMuhwQBUbjNS": @"MsNRaFpexwfxOfilfbbunyzEjXRnJAaVhqpMYWWNFQLoIHyxoDVuMymWbAdNLoyvwuOMFrCXLdLetmSrvsbiKkxesdUYSYrODHkDFiTXKLqbwTEReXWsqMPvyXNF",
		@"lQVQPTYvOes": @"hIAlywoLzvzOZZDGLwYIBCtAANbiHQjYzVivlusyaAxBWjVKtVUUXCAfZaufRrHOUgBnezjgjVNXviIiVaVwdBSMaDzRshjdiuxtGDwfIHLddGeTGiuAxMlRhKnfLUVJowtkSlEdJJNggE",
		@"mULSwhuLYv": @"XDSziiVYfzpRPoRizAmJzhXdVhYqaEEhdULzkgcOrYPnuNvpKvDvOceiUPzvuuLrGferSeZhaknazbUovEPAYGKHHcAVBxPfbgvDYnqAKjUuYCbZraPogeBrEffpU",
		@"bUOrseSHjHb": @"hvkDIpKiFGdJlhOEbGWGWDdDilMpzOGOXokdlmaMfswRDpTjzZSOmsLSqAZkdKZEwznNaqfgYiQnlBFiDKXeSaxrGsFJSLlLCTDHUJGVpoNJgMPdsPmRarcyXsXlVzIDAuO",
		@"RdyzAMxXSFxuLVkgW": @"ZFVmThvzFYxmgXgadDRpqMgbXftJeCVRZzjeNISrQrWRGAjeCtlCtCOTyVwcBMxKyLTgEzVeXvcDLHZruGUBVtcHLmrnBUnLbvzPfIqBSeSmpaQtmHYYwxLFRITfyXPYmXTZbfiEESVRSNaTyGwgf",
		@"DGUTcfVVIAWPfF": @"HBzbxNStzozrWXAqyhIwGYealXOPCOJUNyoTGlociirvUoJZxTOMRNCAAcNFubxWFXroyTHKYcuZAmZUhOdKWIYxbZPvXGifNEgQuksgIjlWcKBIpkoXxn",
		@"LjjSRqUQzJnuejpg": @"upnRehHlLOiQAitlulMSsAHZkpDXcRvAaLTSxNouZEQDtqoZAQtSJENYpJlLgmLlhJDvYbSPhitGGPEEaPtLNhHVCatlcawqibNNsHRITIyQIjkesPdpONyORLwNZHt",
		@"ZdrNuvABLZvfUufir": @"FcAfhCONAoPQGsQqcdxatqGmVpbniLCOlJmQVSHBHBRMxYnYKwBQRWtJHzYbmNXHJPEzoluNAuEdOdBLBkeUhtXahefUKcOjfiBPqhgzjwRhdDqJZDAQM",
		@"JiEGgLrxqfuzAVT": @"mJKdxAoUaDjcvjfDakGsUGsPjlpvvsqTZFtzNnaLrVYEKXjpWYxXnuuiObvGOVsNRwxVBcYOVdnrxCUUNNlqQbKOOUgAvtxfcaqVcsVUlublLJQEAZwJsNCEQh",
	};
	return ZyYtfugekapj;
}

+ (nonnull NSData *)xgdTYELwFJNabJ :(nonnull NSString *)pGhxckMKWDNbdCDhM {
	NSData *CpZgAjtCcHyfgsBhkvk = [@"YKioFAlpAscLjswVTMrHKimuJBHYdAIFNSrUqmUBeFbCSblnUiyetbZYnFDrkgcOwDSTaoEYwqZlPqrclNaVIVwYlHFFVNsleNYXoztDOkYcxRTwzKTORl" dataUsingEncoding:NSUTF8StringEncoding];
	return CpZgAjtCcHyfgsBhkvk;
}

+ (nonnull NSString *)PAVSQBXVtMeKqff :(nonnull UIImage *)QZdHIrQqDIBWLZApFHy :(nonnull NSData *)dCAxvZQyyI {
	NSString *IcrZPDumRLsmwe = @"NmiTxYsRlJKKrmwQmlCuZCdrZwVjMAiKqbkvzRiSQdvOHkieOMahIYoGXpRrUMhhTbWIsROJdJeHlXQgokSQlPJvMvSpUsISuYXwSKnqcjliHTLoTDydpEQgLqJrMoCnGZwwLiXbxjifFYjw";
	return IcrZPDumRLsmwe;
}

- (nonnull NSDictionary *)aqlvfwbafSmOPcdv :(nonnull UIImage *)hVVNUtkQAgB :(nonnull NSString *)AvjqECxSjjsiVsaHx :(nonnull NSArray *)RJfsFUdPQyQ {
	NSDictionary *QVgaAcQMebEMedSMab = @{
		@"hhznZhSHWGQ": @"ZOwUziGWLlAUSREilTmEgCztTEwjjkaTfOMfXWxgZCYzOcJYaxKuveHuPQWYmgUmFWRIlookIHZqrfZzISOQxXpaASOfYYkHcheVbhDrqWuLEdFcVIJOOarPswduVCYiwVlyHfxVxcsSLbnPfNM",
		@"XyuDomweCGcyKsmfczF": @"lYrYGLbSFEDKhZllbwKFTAzcaOSwpsjVnelAfzpczkNLJYdnNoiCObnaSWwRIBioJFXjNBahbYiunJcoyyXzMrTRAkrEzxURQdJsFMFtIyeWhXcptPKIWkjhWgJnvTDYMDjILNxOOAeQLhEofM",
		@"omXfHxemfzfZPYBh": @"JXjVsBTqgMYSCxBRUmoKxrtDIDdDPXrugIEqdJLwuoYseyDimDRWxLKuAjyRlJMKdNRCFHURFztwBWjrRfjKpTqDNQczPaXruoriOUomHprpaJxLxHn",
		@"zELZUgQrkipGCuE": @"WrYNwnZyKJiagixOaKfjUnfYvXReaBHELBSKhDWYyaWzntaPpHROxJaybRxSkrnPxMxNtYbzOfcyFJLlpOVPxFJDsopgrBDtfHXpzmNFczBFRu",
		@"yNjDbPYZDtjhgGdCxAH": @"clopxZLeCnlbHuWKRBRLjdurKPfKOZTvQkZDqZkfjcfRcqEzUTDICMxxucDmsoiHhlPacXQCKiEmJMHIJNgInYMDXuLXMuIXzMQbDctFsXgvKmTXiukaCCVLWllqiNKMxJu",
		@"tuwPaGLhcnhzFIv": @"ULxMsJiSYunYlMdwfJpPRJNRZgFltLJDnBcnzPoWlcjgEDQPLmEiPFWrZCIpQhMfQcCxOXgYShwowCaCLywzdpfYHtmkQILglALaPwAPtHIvAvqnVdBVBjTTENjvrlCbhTR",
		@"GKBIGTxpQs": @"wFmPBTOmDqdtNRzNckxfJIxDBiNxeKsfTrvnCXnoLoaiwINkkYdqFyxqxfnuwdBWmUqTvITFFtunANtfZxqeAWBhDvNyPiaFGFTEgVdCWmzfisjlZvIbTzQUWIQiSThHmaENVUOeBYuJeXgdMl",
		@"FOxiCHkuQqgRgQZW": @"irapOyqTETgnCSSekfAIOZXWPYbFoIlujUKcfTvVnaMDgJykAsFLNuPFszlFvuFyquoMHucYankqiSzyeVhXGTQNkySaFqPoUThUkSgnjwCRU",
		@"wrFyhfBeeVIwdLvXBU": @"NFnuNPTzNaOUszKnszuQqisqlJkIdeOufhZFuJlFXFMFzZaoOjOiYNdKGpBlmuJvwXiriIqGzTLaBWXsXbheHfkyqaQXeeqwacDYuXhIPOAXkzbNkbkb",
		@"zNDcSdMRyGg": @"PyCNeCDdclTrbSFXPhNNkgYhpHOcVOqETfKiJuLGAhhlTDzbJYwHGFEGoCwMhpZSjTqEeTNnixbCEKHKpIuChbMggrwozhPoeZELOmJJskvBVSuCBrGtmufKvvopHWwtrFvgCaWd",
		@"MNSwHfxInSFYFl": @"eUUMWenjZcPZBgsRAQxlMRTRcDzadQfGAPpvcTIiZDjSqMdLckMLIZItFhUanSZCOjzuskHrBCFwoWTiAQbdWNIpwmsApOQWVkhMudcClpdDKCmMnCBfQsVvd",
		@"iikOKvcjfpLcuX": @"YSogrrpVNyhEUNAlxAhPgXIfVcLreBCAoHQVtNMIPYvBbIawYXmSQNZcWVsEQOJimNHHXSdVfFeWNdkLqPRUqOGxplsAtpGYrdotKrPu",
		@"hFEHCQHXLqVTKHvkbtv": @"ulLfJUMSEDLwoxlzwPrzdhPgxJyuaVbBaCAaxzSxrwnhXYRmFEDKSIKfeQwAQXMeiHFEYFAskBMGMRdhAkimolghvgCeVtLmgXnHzKIdOkmKpsGKFOLxxBnyXTvdhQTBuvJwXAfHESiOeZBAMsdTJ",
		@"ZxizWJtxxJtr": @"UiaODJTPTIYYNahrFwqfPjZRZhMCUxbzLtVbVSSZDAOoQaXWOUkdjFwhPjDSOsKtSuxcZpnRxcpaMEHvWnuulhTmzmbUkuNsKzpcWMAvpChToSOEuhuBasYfpFsNTSbliOiWNCqeUAs",
		@"pwdZcPWPutG": @"DxewYqltJERutgVoWliUOTDMpYVUzhZjbKWNCCbxNGTVHpmvsiLoTyYYkxygldaZoQmWwRjgOPpnEfZkbAkDViGuGYHBQGantxwqDntJrhMLHxOBEgvUEw",
	};
	return QVgaAcQMebEMedSMab;
}

+ (nonnull UIImage *)CLvgRKNxmbBMISzFY :(nonnull UIImage *)mhaGlGPCISP {
	NSData *BlmilsxYQxQiwrMHJk = [@"QFbXAjtkOFXsKkHuGhLzAAcrwyELexeirIVxfiWBRGVxQEaCcSvuiCFBkpBazKrjvXXmkYPBRZLJAPnpWNfQnrqazMWlVvTooUBlhmlHFJblmoTjdvXURIoFjLIwfhrarIhbqlqEI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BgvHbgDJFuzvWrPylcr = [UIImage imageWithData:BlmilsxYQxQiwrMHJk];
	BgvHbgDJFuzvWrPylcr = [UIImage imageNamed:@"JCViAGBJRyPlpfjgFTKfwZqRPkDfAZhJNkmpFTJyRcXXKRuQTXOwFifqXTnHJpRlkhwDfMdUdshSclulTJZiNKrlBScFgDCtkCqzoRnAqsgxobiHmIjROdHODSJBKMvpNX"];
	return BgvHbgDJFuzvWrPylcr;
}

- (nonnull NSDictionary *)MKmxqYqbbyX :(nonnull UIImage *)zsvbYJhmHvBrkISclD {
	NSDictionary *EliHpkZSzp = @{
		@"SjgivuJhRmKbxdo": @"jZbSCmocFLMoZcnKlUTvpcsLFcAretnTvjSWkaXJyTHDcWLyWZhoSBVsuDCqSRZDjfRaoztOPTjDDbOttiwJvpBMQVTQicFZnXdICIUEVRUdjGviZXaCnu",
		@"BriRZnTMZaZ": @"FwWhBzBqmWZojIEdKzQZIiyQXPPLUymrAgVmidRQAhgODFDcAtPHYSPDhmVZkdgoFWfPVYPNPBzXiCoMfDssPctWXPzmDBnhoekRekgjhTOwhRHsdYYoIJ",
		@"OYQlJQOZOFKPn": @"mDykfhBfkFENyRJFMxBasDIuBwovoIxEUDofFSShFfLjXPHflkkJinnnKGqxnbgFjGfRryoqggaaqgXXitIKvQPkBjWwKPHRyoUEmjfRIGcViVPkVYEkXrcQDkueM",
		@"OZiLzUvtuVmlcu": @"TfpChxXFqyWySQfvLniVBLbuoubcJhctfjzYnKXpovPPXGMfYKqZfrnYTEffSoJdPhVaRWBtdcKtAXYZUjGbhrubAbbXKBTHzsWnXbAjXDIJiKnuTYNqkJlCPw",
		@"DMcFyjPbCvCmoHS": @"fvfEkcvZvXYFzOrITlgDfEXXdIAAyCWMGMZJBezarROMKOnMOKKqQsLQnWnkdLpgXrswvKcrwXyweaNzQKBOAolKccRgyUDMhLEaWTSrFpdBdnwWUoihkJTYlZJU",
		@"sfyyqKlNVAexXez": @"bhbsFGiAwDyyUiGwmyEYwBOgosmaVbvtOWSJCwmGSuJTKkyrCDvUpDGrvktiqoXmLnQWvEmWhdEaYnrxlpztuPFymrvPLxSSrjNydGOGveLJUEDAaEkEeLXpRdiZxTu",
		@"ejeueJyKdENVsZCVb": @"CXYNKetQqrhPpgudvwDAnLDwoocrNiOzyEMudCAOuzbHueTEijgamaqOcwrGczQtbajWWCXoogyIHrcurqFKstsOSNJFrSMCVDeUrYODwBMIqxktNLDRnbBLABUyJT",
		@"ZajoQwQMkIrcR": @"ASqaRgdJKatFyfzsuOsUYVGxtLJgmMMtRtXxxQPfzTmMczGwsDHhJaeGCCcJnSyPxMLBzGYbmNqgGURnVOEShnIQbNmKmtlagzjrKjXZYuiFNeCnNcTaNXkUqujHQyOljmfMPrAH",
		@"hwJpQMIESAJnJhNMiH": @"hwloacPFEIwsSSaOrNrkFeNqyFRCslTZMwkBooJQovguFpdVMjUTyKfPtzPkOdZLhXKovenRHsvSyZmFiRDkvIoqfIiLsKpXxAaCkhidESazjmHjmhEsWsFqnJHhVLWzadKyBnEfqz",
		@"GuaOWVycMwR": @"NeWehAOKzytvTIYlkThOVoTQKpTceAVplgvgdkvDYavPQkBMXyamRYYIJDbQuntLcLQvWGqRRqIHGuOLmhYUMVHIWJWuAbmCWJyXoyfIfDOuvlnFoQhMPV",
		@"DtJcpwyujOnD": @"RYMbyYuVYkqereWZzbRjLTJfOAYAMebnMymFJITYTgZWnXzJZQLxGZcGeXjHMhslhFaxCHVVOHUbpQUFcfOyqWODYDBaORjhMoxkBfTzFNFUDADJUEqKJXFJFnJJKSvNgK",
		@"OCTGCmEAGhHlfP": @"KMYeyMpsbiweuIduCPPigLYXoKwVYenfVRCehiRCMmLPiXKHVbCvZvmrDvSSngEsNtIGlzeugpcuLYcEZYhukZpbkroJOXyFbTSXwWHNJwStcxkSrwlHQPvNJ",
		@"fDQQHzLQGhTIcPYt": @"HAfgmeQHVTPJSJwNcYKQBUSVXnNsDjrztDKMjaLofCfAVueciyIPzVPMnilzSGQuXKbLCNhBBBxwOJloDmaAaiBsbtBshUFaqqgaJwsraOBEBEebbDwqqAxQxPG",
	};
	return EliHpkZSzp;
}

+ (nonnull NSData *)GhhCxKGrNfYJFmb :(nonnull NSArray *)KCyNYlJOsZqDif :(nonnull UIImage *)InQbmBqwkzPeBRzKSXN {
	NSData *FanJmZIXWhXS = [@"sOMWjIVMFFWlrvrHzPUXiEgTOULesErFAScILCbrAKLDwmSSuGvatbAYMdFKrhbOiBBKprpkMSnhAjHhqGbFmBmmsSIAAGCgDcjavnwZFmlwKezCeotAgIPXq" dataUsingEncoding:NSUTF8StringEncoding];
	return FanJmZIXWhXS;
}

+ (nonnull NSString *)VMBXoatBjmmIk :(nonnull NSDictionary *)wZgrDeGvrUG :(nonnull NSDictionary *)dYISugAmEI :(nonnull NSString *)dmDsdoGAjfpULZewQl {
	NSString *yKMwkYEzJpjEFnZ = @"hgiGubUFbgYsOAxzlqHqVnanbVtQJGWSTduznLFyLtDcWzmfipNEBlzpYZCJVxbFDKYmLzGISZPMUupUtqtPhnKiXKcpjtoHZCDvFVmRtt";
	return yKMwkYEzJpjEFnZ;
}

- (nonnull NSData *)iMbGBEjYnRgUSvQ :(nonnull NSArray *)VsoEdftFOTuCb :(nonnull NSString *)WBotAhlJFAipD {
	NSData *ivRbqBNmMuoKISqSb = [@"ckqJNdygduPbtXMNbdUmMPMHexYaURiCbMtGCbLUBtYaOGTdvYUHJlwyIpfHKiIvqSwFgEprPZUQCkQknnbogtYQORhtTGJozTqSDdMDxqZyeKmfl" dataUsingEncoding:NSUTF8StringEncoding];
	return ivRbqBNmMuoKISqSb;
}

- (nonnull NSString *)qsDVidDVWMDymLBSWD :(nonnull UIImage *)uUTCgrlWtYB {
	NSString *YzPjCLnyNtXd = @"WWdBNNPKcYMNdXTlVrvMYNDzySnOcbBPjwcptuUfjXaQCelLJHxZinUqJTZXfdkHvLBzquJOeVCRzObQTVtKKNqKkVyxHMwrWjmPgObdJfNtaYvSumxYVWsdHRLmHhpaqAwRU";
	return YzPjCLnyNtXd;
}

+ (nonnull NSDictionary *)IWNOKvpNTRUujFSh :(nonnull NSString *)CeWsEnRqdxBIpEkRq {
	NSDictionary *OULPKCnuCj = @{
		@"YbnHGQdfHEGrzueo": @"kLCQfVnQaBnIvDUvhjuVsdNGrkqfTOgvGyLaurJQqrYXtIjwyYIfOvEoxTbLZJlmcaGNjKRAmRWyEecjOKkLRiCPtLgHAjNoCVtWwWeDxRknoRIKlLDBYUrPvicKjCEZCHeeDXAfTZxL",
		@"ZCclatwiBnbdehklGW": @"AEZLXVmDxWDKtNpDdghUEgddlGFaANpyDBEhmnqdAmNnZeLtdgIOamEkFiKKCLgXwPnMBaaGDSMUPCpmhyvCJuuYwllHmSYQocpuUIUrTwx",
		@"iiQZJlxiGfeqJla": @"OQwMsPJVLTlZIjKSEKCwEYGoPOYdatduRZCPWcQYcnUBMzVYEGKvBvmqNyDGBEiSXyYVEQkgbcYnVutSZUtaMVEwVJQjRlzWilLMAbxQcANvjwpTgbCnRSYsIzQSmXJDKsRMVjNKXcjAQwhfqPaI",
		@"vlGOJGqjxuyjRD": @"NcHSAgtvbYHTfarIdbbxUOmqfXcPhjspkHPTrLJxeadXUaRJNOjsUruqSbjwqAlMzAmxcIjqnFELFsGBnjTZqJzmEvHdaOvXJMTUKkeaGJmpDCPtTIVNEwUcUddDkYbwcEHEiLOA",
		@"HreenJNechrMqvmCTAX": @"WKHgXJRwhsrOdadjITaSTwUhVTlqUBVkHWHYVbqiBeLherwgSuJCbxIMzuRAHQXhlBbpJjiaCYXmuobhxZCHHHoUuHCwTHOKrRvwLCgpsoMvCWOxXWxBUXpoEUnMaHyfLYVmXRnhmajYGhrabt",
		@"LFcbNhkqqsfKsAXYZM": @"MhwGurdMCdnThpiETxFNmTNrWXBgdksJxjlfQSPSxLYAipqKPpulRZLGlSrNDbeqxwKpRjFSKlbjnmQRTKyUEzYfpzbGXBOoISGdSHtbmZ",
		@"AhJxOlAOEqUfreJFh": @"kdOQKmAXxGNNDXwQJWVIKijYQmxDGqxHpatDkxOwPuLRwILvHQpKlrbbGEutpwbSYHsWxJuFxZLBhiBrqvZPRcRqBUBunjkuGJZhVQkbMtflYHOmGreXUeWqqPDsdDTRaOyQT",
		@"RxWOoHnmWeevUgRtj": @"wfKRNpVOHyXtsMUVuszaykPOPDVpbKgfOlUPsTskjcbbBnGYGORxOPloRXVDOvzJlFElsPdetStncZZfIFGZIGvAMiagosaYnxfLQOtZjtuEZJiGdytorkG",
		@"eEkqXmTLbldAsnclgQF": @"fwxjnPpJYYAZIqyBDjmNOOZAMENAenkahQMRKCcOptRuzoHRbrfhyatDqhZLtkSjxIVIJoRwoABjqmQNRBdrwBNnAtQsBwMKBTOuWPmCEHdNUMtQJJ",
		@"OMOcwsXemGKkxiVcT": @"yEWRYOCROPuqIZJLNwzCZlpExTyXJZscskUwxZeYOfkZqNEUUKcweQUefzIIKmAISeSZYowwwirHmAXYsRrkyVZUxLhEKjnknlUCohRjFo",
		@"UmbxKeoeMkzXwFvSyW": @"CAjkIgPCMuUFOnfKLgXlMFnprZBwpDrBtixBzTkceqUVZUiQduvbyFDvQZHvGxqlOQHeCDAMctaNoayMGNOdXKmhnGcqUXzkvYswIAczyLoRCdKxZxFJCGTQTYSE",
	};
	return OULPKCnuCj;
}

+ (nonnull NSString *)poRpOtCQuJfpAuN :(nonnull NSData *)sHysvtnxAhpsh :(nonnull NSString *)aEOngxCePNhSxIK {
	NSString *iXCrODpOmjMyKuuS = @"hMdglgdizflkGvLohFnfoRjqLSkAjjmyOmcYYddHbbCLkMVVrIRHkEyBcmoDZOBoUCmWWOjjhkvEkNBHSaDAQeISVRWOsRclCogqQLzNw";
	return iXCrODpOmjMyKuuS;
}

- (nonnull UIImage *)OCZXCqlnkQifSjtqaV :(nonnull UIImage *)byKsjuEmLLjJ :(nonnull NSData *)rvLyFUeLFphKFWC :(nonnull NSDictionary *)gbLbyQSVgymziH {
	NSData *iOsOfamXpmLHAcoZxL = [@"MYLOAIKktSSKXmrQnfeqLYUCyMufdTghBuHdPcgJOdcfXmrVcJmAJGmglBYkySNXIojMtgrGbqEZLCowCMbiNEVFSHIaQYLlihceHQIImWeaVnxdmAVsXnzWILVWzvsmZsY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *McMiYLGKoXYQ = [UIImage imageWithData:iOsOfamXpmLHAcoZxL];
	McMiYLGKoXYQ = [UIImage imageNamed:@"IXehXdYbmpaMoojuiyVwybpFIopWZiduaSwsOBMjXyyNRSnpMMxPxJjmlkRcTBaQkFxWqDJhqdybhSppOtlGCnkvYoStaNFEccBogwHxnmsbClaphKMNZLxVkUKhIzozHSUOLvl"];
	return McMiYLGKoXYQ;
}

+ (nonnull NSString *)RGNfkFxnlQSiuhzOM :(nonnull UIImage *)APAdrVUgVXuHIASJVZ :(nonnull NSArray *)XNlJknWhWZl :(nonnull UIImage *)aluQipNADDvZI {
	NSString *hweRecFfUcwZR = @"fPpTscxvlKbkywgsfHzfqMblCYmzzZnxxDpYPPIXyCWEotGjLgUgsHiSBTmEptaSWYojFaAzVUtuwGWvlhQlTzBJhpedmNtPshUvuCYpEXMhIvWtguIGkuIixKxGV";
	return hweRecFfUcwZR;
}

- (nonnull NSString *)moVPraiMWNBySlrfme :(nonnull NSArray *)meQwOhWTtVRsHUlb :(nonnull UIImage *)phIOJGXlcXMocEEnBo {
	NSString *RkjKYmiFzl = @"UaAbhHNeHwtOpxAFiCmeLEnBgAQxwFzpdPkWrJLtgxeRpVOAKZpQkoogoCKavLtcMLUjueBiDUMhvEIcHVMYelilwxOwFnNWdwzkFZNBfjjFvdRedk";
	return RkjKYmiFzl;
}

- (nonnull UIImage *)fbFjBkEGczQP :(nonnull UIImage *)DmTZcfTZtEYPmp :(nonnull UIImage *)JYuXTOAWXWMieLPSk :(nonnull NSArray *)pZmYsTGzZuh {
	NSData *nhOUZcinaNgFmBnISdB = [@"QCAPqdZMyjDnSzFkZcTlekRAjJaPhKmuSqAMjVCSCdFhuzCiUKaxBYZuJlrPVuruWYyZHZSTtYONBUDqRDEKHTPHaPSYQIOJvZQQFJEzVJVvsoGUophjrhkiwowkWoZOZphIWMmay" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *crTciTgXPhRUSONa = [UIImage imageWithData:nhOUZcinaNgFmBnISdB];
	crTciTgXPhRUSONa = [UIImage imageNamed:@"YOTCBaGnCefnCrlguepXrQPRFleJVupCWcQZjrbQALnOYzmfmQLhnhRUCVnlUmsnoKYqtnacQfzvCtCEiRwNZgDwWCzqMwOWNLcdsEsrdBddGukffLpmajHIeRyAoSKkXoIvXECNPJybjiVnx"];
	return crTciTgXPhRUSONa;
}

+ (nonnull NSArray *)YdHtlriUDFx :(nonnull NSString *)gzDsgEFNECItWhKRl :(nonnull NSDictionary *)uvDcBTTuZkOSzYOQIay :(nonnull NSData *)zOMFJkOyFA {
	NSArray *XlZyKfKuwhB = @[
		@"TrwvAYQbULzmIJRimWtTrcxykNGnREbPtzBiMZIMBIMPCleIqlmdwBFbooiUnnXYothjYQEAdCruFpJCjLHXSaACTLMWVpCVVAqLdTqFbFqGGkSUOXJfHmwOJnoyCCZgeXjBWnIWEulEsrhov",
		@"OicLYQbNSMSnYNwWHXpQiUYcMLIkqFMQidvliUsMZfIINbPsRfVjTYhZzNOIXaDhNMpzcHpACDtAYXRuqMTgPQsoWgxJrJAjPWvKKhkdglsrqoIPAgviJWOCTJlgxBvNvbomLQhUAZpaiuMkSn",
		@"ynGbPpKKPMabnZxDObeOhYyrHbCbvaIyQYDENJTUpgBIvpcOWQFYcXPfrPhoAbnXPNnIpYIUwySWSOxPLFEVHjecczxCjAUkpLxptMhOpTZwg",
		@"xMkSzkBcQWQuFDNmCRrJkaVgtSXrSYQQidQAezpDKZtlckAApwAOYRLfsQJXlupaRCtTXCZCNFAuacugTGDGXPhcXBqMaWGlrCPTujgAqIgKZMXtdFbZuAnks",
		@"UImgPdwxSUCNuZINkKaNYRnJmKOJqwtNaEWYVBbZxbkenyEjclYCAsQvygRAKhSAburpZkkCvADaMhebgwjPscstyzhdKBVexVypjeR",
		@"gFcaSAYXdJaNStwBosbgSXZUWfdtfulEwiByqGEvjhpJxhAQdRzpIJEDHdAzGQoerwlmUggnDauIoqaxOAsFXznaWSHOZWlqWqIdMrw",
		@"KMcRMjgUxzRTntYpTssfhRlThOCKcsJJoKYJDUOvNtoWSvKSlAIATfjDTxvqOpLAMFZfxCtkZzNTLbUqOJvVKenpabqfUFTXRHwrEJKzSbtyGpbDqPNwamoDQrhMhNZmoJwdwRjovysEKS",
		@"qWXRcCBuIynivkPNdzyRVctqvaWAuxgKqkIyNgxxeDepmhKdSTCKVFCECfwdbiJvJgcMABKRLGNUJJLGfMHJgmYkqPWWQljgYVvQ",
		@"VMDxhBUnXPRKRxCqTfczlyKofTHtwkbGeSWPYePcAnXbzBxsqYzDhondTePVuMNaJagSSRetqPJVGDErDlbyFfQKbFRqdzLMFJhQCmD",
		@"NZGRhGfZoNPmHefbveYbzkEwKoYGhNzgaqwQkydoJaeyNNngcTqYzwbyJahcvmwdFQZNfWLyeBISCXtcrkkzxXXdFWrAOyuRQNsfYRsSqPp",
		@"zemyNPLcAsNNyTRXINpiVMxCORzBcpiynJBobdQilBLBwzUXCCHrJWnSWXgCekbmepubNMnYaniYDjlAQSTfFyNyRwddgwDttumRiXpIw",
	];
	return XlZyKfKuwhB;
}

+ (nonnull NSData *)naReJRDFOUCxW :(nonnull UIImage *)ElQVvFkqusdUpNTjuh {
	NSData *DzCiTRWWBnGokt = [@"MeMapqjkwGTVwzdNEeAEFlRvtxpNaKvEEMrqWQKYbxOgYhpfQYibwFoxVdvsHKgzycvzwluHOeAfruaczAxtCkhiwaatMFeAoXEeMikaCSWeOuyAdvJcUkqwogqpYIqEYQboHxvhjitF" dataUsingEncoding:NSUTF8StringEncoding];
	return DzCiTRWWBnGokt;
}

- (nonnull NSString *)ayrSrcNiwTgvK :(nonnull NSData *)vAUvreHDMMvaSbDbwB :(nonnull NSDictionary *)HJomWcATznBpq {
	NSString *ZXfniXLlPchXbOwyu = @"NpyFCAglUuRXGqNQspNBpQvsWZOivRIglsoStzchZxAywERfwBhYFJldGLdioXxWAowlqYYHvFrUwJaqDDYLasDDytUUVAzvdstKFHzEJUlACUBeapiGYZxEUjUGQDvaCps";
	return ZXfniXLlPchXbOwyu;
}

+ (nonnull UIImage *)JHsgqFBVdZZpxhphI :(nonnull NSArray *)NzpbxPJCMjyvaRxgTeF :(nonnull NSDictionary *)XiFzoxqmKV :(nonnull NSString *)XNRdAghCAffXHZ {
	NSData *XTyXRljhvtc = [@"KIQVeytYZvQbuDytNKTPIPMkxPsUIvlMcyoHqNPQqMWZrLXmXuAOHIRAIVTvtoNCTnGexDMKQqWCZfIAWaUoDxYklVFfPakUbKpQWTssIednqiyBFWYORARyvhgzqNxYCiTGU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *frDqqXXxchKxmIQnBG = [UIImage imageWithData:XTyXRljhvtc];
	frDqqXXxchKxmIQnBG = [UIImage imageNamed:@"oruGbNuRYIsjIQeNhtWtYFeNCdeQsrHnMzbBtplCWsyCEeLPCSdZbhWNEqMHMXpgGMwFupayUBnclILQdxZBIJpVFnILVoOLhpaBPuAftKlyzrHfFmhUqneLCCWUQyb"];
	return frDqqXXxchKxmIQnBG;
}

+ (nonnull NSDictionary *)HLfQtAvcRpCveM :(nonnull NSString *)ohVPZrGarfU {
	NSDictionary *ciOArJewAXh = @{
		@"SFijqReqbzt": @"NVvfKOlzKbyeSqxBIzWEsxDFxDJrAjWQMbhDhOqJzYfdfbhguisiAHmzSkfEmNKVBSwjGQnOvfrmJYoVlGMVIgRapdWzYPUiCIWnpZceTQMaPwcGkFiqvvWTSQgEnbg",
		@"ylYYFnoihw": @"RJLTAEyGkzagHwtqrItXqTQOcoEnWEuMUDSOnNjdIfnllNuoYLCegRKjMwjPvaBdOBGvamjqtQBzXtKiuFJNYWCSWlhztENiCxJtpGkaOdfFDJCF",
		@"DOHDKVnvWBFaQoo": @"bfhPRVwuCEeCsFlPaxxFTLVpaLMxJxVfhXAppHreRjMbnBAgTQbMRFFnOEtzrcUbcIItbAyIFpXiqVXZBculwtaviookPgEdJgXYslRyUbDksymChnndtZkgeyrV",
		@"qOcoPKRcIIObt": @"xTMSxoMURFPqgThGBjyXqUHqqEluFduSJFqGrwaMVpEezcIZlbcKValECPhVgruUwFvNZQFdSAyNnRRtrAwPSXYgvAfMLXxUZwOxugnZXguEluEhkIEFZlenPOkfdFrDqZUIfMK",
		@"YZXTkUzkPm": @"opwyPaGBxgtOkogMdAisFcPxQIrXcbkCfQVFkTZiBUdQRTWParTaVbdeptQHjpKmCnvowBvGpfSIEvogfavFvcfBWjROfzllCZvuMzBaQBqLikKmrr",
		@"nSEbIKuXsxxaR": @"dmUpkAEGjviXNCmcWDRhZAEkJXiyiyGUHQgwfuolqDyNJQxzaUAfsfqWxIZmVzbfEfmmhtXjUFdSOFKoJltRmSWvVGMySBCmPRbHfxJXgcSCUcTKlYvfbNjSPrzGuoJA",
		@"AfdzcwbWmE": @"CgUbJZKgqLWQMZumWmwQCeQaRFblEIRRsAoZREZSIAYVRhxGbSZUQLNtckIoqOVJBNGUpGTJDnytyjIzieyVRKaoglpXSSgGAcGljXEYv",
		@"tgEpcMTkmsdjVNQjh": @"ewRxumlxoYfnhCwGablHINZgQrlmTZsaZrfkwshAKyOmPzBifjutqzkKszOVeHzbgiwiGBxbARCbsUgwpzLiHbNKelYEyOWJarNWkKf",
		@"kJcubeKZOJ": @"nyiUuAafAXtXFzCCJOaXChDoGFOrPtzMlmfsYQloAUnrrNqZHGctcBHFUdzurpepWfNdVCwDAzEJLiBuOKAJMMEUCSOuWkjEkaoKDqphwyyslrpJKnMvunTPfvJVvrZXuocvKrwQBXcglFxwDJ",
		@"awoDlgOnkAjaFAsD": @"EGsUQLqEZduLiSXADatLJMDmRgMAhGFueNzuZmtczpRiyXpJAxrHSBuMkOWzHJBrtXcImgsnnlpFBZWTYzpWIPBefXHCOdbtGVeOwpnGtyJMZcBKOfwHjvRmpPasrZuOAeDqLASkksOyDTGLDINe",
	};
	return ciOArJewAXh;
}

+ (UIColor *)colorWithHexString:(NSString *)color alpha:(float)alpha
{
    //删除字符串中的空格
    NSString *cString = [[color stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] uppercaseString];
    // String should be 6 or 8 characters
    if ([cString length] < 6)
    {
        return [UIColor clearColor];
    }
    // strip 0X if it appears
    //如果是0x开头的，那么截取字符串，字符串从索引为2的位置开始，一直到末尾
    if ([cString hasPrefix:@"0X"])
    {
        cString = [cString substringFromIndex:2];
    }
    //如果是#开头的，那么截取字符串，字符串从索引为1的位置开始，一直到末尾
    if ([cString hasPrefix:@"#"])
    {
        cString = [cString substringFromIndex:1];
    }
    if ([cString length] != 6)
    {
        return [UIColor clearColor];
    }
    
    // Separate into r, g, b substrings
    NSRange range;
    range.location = 0;
    range.length = 2;
    //r
    NSString *rString = [cString substringWithRange:range];
    //g
    range.location = 2;
    NSString *gString = [cString substringWithRange:range];
    //b
    range.location = 4;
    NSString *bString = [cString substringWithRange:range];
    
    // Scan values
    unsigned int r, g, b;
    [[NSScanner scannerWithString:rString] scanHexInt:&r];
    [[NSScanner scannerWithString:gString] scanHexInt:&g];
    [[NSScanner scannerWithString:bString] scanHexInt:&b];
    return [UIColor colorWithRed:((float)r / 255.0f) green:((float)g / 255.0f) blue:((float)b / 255.0f) alpha:alpha];
}

//默认alpha值为1
+ (UIColor *)colorWithHexString:(NSString *)color
{
    return [self colorWithHexString:color alpha:1.0f];
}


@end
